### ISSUE TITLE
Whitescreen

### ISSUE THREAD

**Issue by islanddog** [Varying-Vagrant-Vagrants/VVV#1006]
Morning Everyone;

I have been using VVV, TopDown and Variable VVV for the past few months without issue on a Windows based client. After adding a new site using Variable VVV today I was unable to access previously created sites. After removing several plugins and altering a few of the local files I was able to access the site again with multiple errors coming up:

`Fatal error: Uncaught Error: Call to undefined function mysql_escape_string() in /srv/www/catering/htdocs/wp-content/themes/porto/functions.php:60 Stack trace: #0 /srv/www/catering/htdocs/wp-settings.php(387): include() #1 /srv/www/catering/htdocs/wp-config.php(81): require_once('/srv/www/cateri...') #2 /srv/www/catering/htdocs/wp-load.php(39): require_once('/srv/www/cateri...') #3 /srv/www/catering/htdocs/wp-blog-header.php(13): require_once('/srv/www/cateri...') #4 /srv/www/catering/htdocs/index.php(17): require('/srv/www/cateri...') #5 {main} thrown in /srv/www/catering/htdocs/wp-content/themes/porto/functions.php on line 60`

from what I have seen from Googling this was due to an upgrade to the PHP or MySQL causing the commands to be different. I have tried several stopgap solutions to fix this with no success. I finally installed an old version of WAMP and manually deployed the site onto it to get it updated and ready for live. Can anyone provide assistance on this or know of any solutions to fix the other sites going forward?

**Comment by jeremyfelt** [comment]
Hi @islanddog. This looks like a compatibility issue with PHP7.0, which is the version of PHP that VVV installs by default. `mysql_escape_string()` was deprecated in PHP 4.3.0 and has finally been removed completely. http://php.net/manual/en/function.mysql-escape-string.php

It would be a good idea for the porto theme in use to update their code base.
