### ISSUE TITLE
MySQL Sandbox

### ISSUE THREAD

**Issue by tyler-barnes** [Varying-Vagrant-Vagrants/VVV#1009]
I'm trying to wrap my head around how to use mysql sandbox with vvv but I can't seem to figure it out. I've spent a few hours trying to figure it out but I'm realizing I just don't know enough about ssh, vvv, and vagrant to do this. Is there a guide anywhere on how to do this? I'm trying to match my local development environment to the server I'm developing for.

**Comment by jeremyfelt** [comment]
Hi @tyler-barnes. MySQL Sandbox is not yet part of VVV, though #835 is an open issue suggesting its inclusion. I'm hoping that we can get that as part of the default provisioning in the next several months.
