### ISSUE TITLE
Vagrant up timeout after MacOS update

### ISSUE THREAD

**Issue by antoscarface** [Varying-Vagrant-Vagrants/VVV#1011]
Hi,

I'm happy with VVV and I worked without any problem until yesterday, but after the last update of MacOS 10.12.1 (I've already updated my mac to MacOS previously and no problems occurred), `vagrant up` goes to timeout, as you can see in the screenshot:

![image](https://cloud.githubusercontent.com/assets/1921869/19801598/1ff92848-9d00-11e6-96d1-b7f85b81b20b.png)

If again I type `vagrant up`I receive this:

![image](https://cloud.githubusercontent.com/assets/1921869/19801666/771e293e-9d00-11e6-8ace-13df0d346f63.png)

I tried to update vagrant and virtualbox to the latest version, I tried to power off the virtual machine from virtualbox, but no luck. 

What happens?

**Comment by jeremyfelt** [comment]
Hi @antoscarface, thanks for opening an issue. I haven't tried things in the latest MacOS yet, but this seems likely to be an issue with Vagrant or VirtualBox rather than VVV. Check out this issue on the Vagrant repo for some ideas: https://github.com/mitchellh/vagrant/issues/7930
