### ISSUE TITLE
VVV and Gulp BrowserSync outputs a useless (?) public IP

### ISSUE THREAD

**Issue by kevinmamaqi** [Varying-Vagrant-Vagrants/VVV#1016]
I am running VVV, (just installed) for theme development using gulp altogether with Gulp-BrowserSync (and other npm packages).

In VVV I've created a new WP install called organic with organic.du.dev as URL. It is working fine.

In my gulpfile.js I got the following BrowserSync task:

    gulp.task( 'browser-sync', function() {
      browserSync.init( {
    
        // For more options
        // @link http://www.browsersync.io/docs/options/
    
        // Project URL.
        proxy: projectURL,
    
        // `true` Automatically open the browser with BrowserSync live server.
        // `false` Stop the browser from automatically opening.
        open: true,
    
        // Inject CSS changes.
        // Commnet it to reload browser for every CSS change.
        injectChanges: true,
    
        // Use a specific port (instead of the one auto-detected by Browsersync).
        // port: 7000,
    
      } );
    });

When I initiate GULP (login via vagrant ssh) in the working folder everything runs and I receive the following message:

[

    BS] Proxying: http://organic.du.dev
    [BS] Access URLs:
     ----------------------------------
           Local: http://localhost:3000
        External: http://10.0.2.15:3000
     ----------------------------------
              UI: http://localhost:3001
     UI External: http://10.0.2.15:3001

The problem is that http://localhost:3000 is not accesible from Chrome or Safari and that http://10.0.2.15:3001 is a public (and useless as far as I know) IP. Running ifconfig in vagrant@vvv I receive the following prompt:

    vagrant@vvv:~$ ifconfig
    eth0      Link encap:Ethernet  HWaddr 08:00:27:67:05:88
              inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0

and also the working localhost IP, which is:

    eth1      Link encap:Ethernet  HWaddr 08:00:27:4e:59:e0
              inet addr:192.168.50.4  Bcast:192.168.50.255  Mask:255.255.255.0

It took me a while to realise and find what's going on, but the problem is that I still don't understand it. I think that is an error and should be solved.

**Comment by jeremyfelt** [comment]
Hi @kevinmamaqi, thanks for opening a ticket. Have you checked with the Gulp or gulp-browsersync documentation to see if you can manage how that IP is generated?

VVV doesn't provide either of these by default, so it's probably not the best place to have a config setup. It would be interesting to document for others though.

**Comment by kevinmamaqi** [comment]
Hello @jeremyfelt,

Thank you for your help. I've checked the gulp-browser-sync repository in order to find a solution and opened an Issue, now I'm waiting for the reply.

On the other hand, while trying to find a solution (or explanation) I can't find something similar or I don't know how to search for it. In addition I think that is more related with Vagrant or VVV because when I log in via vagrant ssh I receive the following message:

**_Last login: Wed Nov  2 12:36:09 2016 from 10.0.2.2_**

**PD**: I just got started with OSX and VVV.

**Comment by jeremyfelt** [comment]
The `10.0.2.*` IP is the NAT IP assigned for the communication between Vagrant and VirtualBox when the VM is initialized. https://www.virtualbox.org/manual/ch06.html#network_nat

That value will always be assigned to the default `eth0` interface. Some more helpful reading can be found in some Vagrant issues [like this](https://github.com/mitchellh/vagrant/issues/2093), but I'm not sure of the exact reasoning myself.

The missing piece here seems to be how to get gulp-browser-sync to pick up the `eth1` interface instead, which is the one our private network is assigned to. Another possibility may be to assign the IP statically in the gulp-browser-sync configuration. As 192.168.50.4 doesn't change as part of the VVV config, then it should be safe to always use it.

I'm hoping the gulp-browser-sync team has a suggestion. :)
