### ISSUE TITLE
An error occurred in the underlying SSH library that Vagrant uses.

### ISSUE THREAD

**Issue by neilgee** [Varying-Vagrant-Vagrants/VVV#1019]
Got a new error today on my VVV Vagrant set up...

```
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 website.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 wsl.dev
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
neilg@[~/vdev]:(develop)
```

Anyone experience this before - am running Vagrant 1.8.6, VVV 1.3.0 on VirtualBox, force provisioning has no effect.

Technically this is not a VVV issue but I only use it for VVV - found a ref here https://github.com/mitchellh/vagrant/issues/6812 so will pursue over there, but by the look of the thread a few recent users are affected by it.

**Comment by jeremyfelt** [comment]
From time to time when I've run into a Vagrant issue like this I've tried changing the versions of VirtualBox and Vagrant that I'm running. It could be worth trying Vagrant 1.8.5 with VirtualBox 5.0.x to see what happens.

Also, make sure you run `vagrant box update` to update the underlying Ubuntu box.

**Comment by neilgee** [comment]
Yes, had made sure the box is up to date, also have latest VB - opened an issue over on vagrant https://github.com/mitchellh/vagrant/issues/7965

**Comment by anilranathunga** [comment]
If you have two vagrant environments with same name both creates vagrant box with same name, second one replaces the first one, 

destroy each and up again.
vagrant destroy
vagrant up

this will sort the issue in above scenario

Keep different names for each vagrant environment .
