### ISSUE TITLE
Segment PHP logging to a separate log for each site

### ISSUE THREAD

**Issue by westonruter** [Varying-Vagrant-Vagrants/VVV#102]
As more and more sites get added to a VVV instance, the PHP error log can quickly get overwhelmed with entries from all of the sites combined. So it would be ideal if each site got its own separate PHP log which could be tailed.

cf. https://github.com/10up/varying-vagrant-vagrants/commit/1fb1a47992250d81a61c4e0171e84eea66eb4ee1#commitcomment-3676483

**Comment by jeremyfelt** [comment]
I think the only way of this happening would be to specify multiple pools in the PHP config. There may be a way to output different logs then. If not, you could still `tail -f | grep [pool www]` or similar.

I'm leaning towards this not being a thing in VVV, so I'm going to close this. But we can always reopen if there's interest. :)
