### ISSUE TITLE
How to configure SublimeLinter to work with PHP_CodeSniffer from VVV?

### ISSUE THREAD

**Issue by lumberman** [Varying-Vagrant-Vagrants/VVV#1020]
I like getting coding standards errors highlighted in real-time while I'm coding. Since VVV already has PHP_CodeSniffer with WP CS included is there a possibility to configure Sublime Linter to work with it?

**Comment by lumberman** [comment]
After some Google + Terminal play I found solution:

1. Open Terminal and go to your home user folder.
2. Do **nano .profile** command
3. Add the next path /Users/yourusername/path/to/vvv/vagrant-local/www/phpcs/scripts/ to the **export PATH=** statement. Make sure to add "**:**" to divide your path from other paths in the statement. Also make sure to add "**\**" before any spaces in the path.

In my case the path looks like this:

**export PATH=/Users/lumberman/Dropbox/Work/Local\ Development/vagrant-local/www/phpcs/scripts/:/srv/www/phpcs/scripts/phpcs:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin**

Restart your SublimeText. Sublime Linter should be working now highlighting all the errors in real-time.

**Comment by jeremyfelt** [comment]
Thanks for following up with the answer, @lumberman! :+1:
