### ISSUE TITLE
Disable memcached + opcache

### ISSUE THREAD

**Issue by gtamborero** [Varying-Vagrant-Vagrants/VVV#1022]
Hi! VVV is working very good and fast for me. My only issue is that (sometimes) when I change a .php file, I have to refresh the browser several times... Or I have to wait like 10 seconds and try again. It's a bit annoying.
I have tryied disabling op cache everywhere round the /conf/ files and restart vagrant but it's stills appear activated If I go to: http://vvv.dev/opcache-status/opcache.php

/php-config/opcache.ini -> opcache.enable=0
/php-config/php7-fpm.conf ->php_admin_flag[opcache.enable] = off
/init/vvv-start.conf -> #service memcached start

Someone knows how to disable opcache, memcached, etc.? That's what I need for developing ;)

**Comment by gtamborero** [comment]
Since I had this issue, I deactivated permanently my browser (firefox) caching system and It seems to work everything ok ;)

**Comment by jeremyfelt** [comment]
Thanks for leaving a note @gtamborero. :)

We went through this a bit waaaay back in the beginning of VVV, but things should clear pretty quickly now, so it's nice to hear that it may have been browser caching.
