### ISSUE TITLE
automation on staging/production server

### ISSUE THREAD

**Issue by vljankovic** [Varying-Vagrant-Vagrants/VVV#1025]
I installed vvv local dev environments on several computers, all work well. Now, i rented unmanaged VPS for testing and maybe production server. VPS is initialized with Ubuntu 14.04. Is there any posibillity to install exactly the same LEMP stack as in local dev. env. (with all php extensionns etc)? Should I install it one by one or is there any way to do it with vagrant or some script?

**Comment by LoreleiAurora** [comment]
what vm provider are you using?

**Comment by vljankovic** [comment]
sorry for delay. I'm using aruba cloud vps server smart. Bare Ubuntu 14.04 is installed from template. Now I have to install nginx, mysql, php. I can do that, but I wonder if there is possibility to use provision.sh from VVV to do the job. My intention is to make exact same environment as on local machine.

**Comment by LoreleiAurora** [comment]
VVV is not really designed for a production env but it could be done. You would probable be better using a real provisioner for a production ready box. Check out the links from when this question was asked before in #569 #257.

**Comment by vljankovic** [comment]
Lorelei, I want to thank you for your answer. I'll try to use directions given on those posts. My intention was to create test or production server as like as development environment, with all php extensions etc. Thanks, anyway.

**Comment by ivomarino** [comment]
appflow.sh is doing exactly this, via provisioning.

**Comment by vljankovic** [comment]
On 24.1.2017 17:29, Ivo Marino wrote:
    
    
      appflow.sh is doing exactly this, via provisioning.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Varying-Vagrant-Vagrants/VVV","title":"Varying-Vagrant-Vagrants/VVV","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Varying-Vagrant-Vagrants/VVV"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ivomarino in #1025: appflow.sh is doing exactly this, via provisioning."}],"action":{"name":"View Issue","url":"https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1025#issuecomment-274855704"}}}
    
    thank you very much, I'll give it a try.
