### ISSUE TITLE
Permalinks with %postname% returning 404

### ISSUE THREAD

**Issue by sntiagomoreno** [Varying-Vagrant-Vagrants/VVV#1026]
Hi, it's the first time I'm having this issue. Everytime I try to set up the permalink structure with %postname% or %category%/%postname%/ it shows me the default 404 theme's page. Can't find any solution online. Thanks

**Comment by grks** [comment]
You should probably have a / before. I run with /%category%/%postname%/ and then set Category base to .

Seems to work fine.
