### ISSUE TITLE
local.wordpress.dev/admin/ doesn't show login

### ISSUE THREAD

**Issue by mikromakro** [Varying-Vagrant-Vagrants/VVV#1028]
I messup the wordpress-default install. I deleted the folder. Ran `vagrant provision` and the original folder was restored. But when I go to local.wordpress.dev/admin/ or local.wordpress.dev/wp-login the pages just reloads and I never get presented with the login form. 

How do I fix this?

**Comment by aaronware** [comment]
@mikromakro have you tried going to the standard /wp-admin/ or /wp-login.php directly vs the urls you shared?

**Comment by LoreleiAurora** [comment]
@mikromakro Have you tried clearing all cookies/browser cache?

**Comment by mikromakro** [comment]
Thanks @aaronware it worked. I can't believe I didn't try that.
