### ISSUE TITLE
I can only access to http://src.wordpress-develop.dev/ on windows 10

### ISSUE THREAD

**Issue by miguelangeltorresfp** [Varying-Vagrant-Vagrants/VVV#1031]
Hi, after many hours trying with different versions, I finally got it working, but I can only access to http://src.wordpress-develop.dev/.

http://local.wordpress.dev/ shows the nginx welcome page although I can access the admin panel

and http://local.wordpress-trunk.dev/ shows 404 Not Found nginx message.

My pc has
virtual box 5.1.6
vagrant 1.8.7
vvv 1.4.0
vv 1.12 

Thanks in advance.

**Comment by smashstack-dennis** [comment]
Up,

I got error also on windows 10.

Everytime I create new site, It redirects me on default dashboard the vvv.dev.

I correctly configured the config/nginx-config/sites/new.conf and the Windows\System32\drivers\etc\hosts file

**Comment by cfoellmann** [comment]
Make sure you have NOT installed hyper-v
Reinstall the vagrant plugins
Test a new provisioned vvv. Shouldn't take too much time but provisioning a vagrant on windows sometimes has hickups

**Comment by jeremyfelt** [comment]
@miguelangeltorresfp if you are on the latest version of VVV, `local.wordpress-trunk.dev` is no longer provisioned automatically. See https://github.com/Varying-Vagrant-Vagrants/VVV/pull/959

If you have upgraded, and it was working before, it should still be available.

Was this an existing VVV installation that was upgraded or a new installation of 1.4.0?
