### ISSUE TITLE
Solution - unknown service

### ISSUE THREAD

**Issue by MortalCatalyst** [Varying-Vagrant-Vagrants/VVV#1032]
Hi just noticed an issue that I had was had here before but I was unable to find a solution in #467 #417 .

There was a similar in SO [VVV SO ](http://stackoverflow.com/questions/25986069/first-vagrant-up-fails), none of the answers worked but in a comment and thought may be useful for others.

As other issues get a response similar to this.
```bash
   default: Running: inline script
==> default: mysql: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
The solution for me was 
```bash
vagrant up --provision
```

**Comment by MrVibe** [comment]
Thanks for sharing, but it did not work for me. I got the exact same error with this command.

**Comment by jeremyfelt** [comment]
Hi @MortalCatalyst, thanks for sharing this info.

To explain a bit further, `mysql: unrecognized service` *should* be an indication that something failed during provisioning. In this example it's likely that `mysql` failed to install at all. Without a log of the full `vagrant up` or `vagrant provision`, it's hard to determine the exact cause, but it does make sense that `vagrant up --provision` works.

**Comment by MrVibe** [comment]
I forgot to update, the vagrant --provision worked fine after I restarted the VirtualBox.
