### ISSUE TITLE
Incomplete first 'vagrant up', *-provisioner directories

### ISSUE THREAD

**Issue by ihorvorotnov** [Varying-Vagrant-Vagrants/VVV#1033]
Decided to update the stack by completely uninstalling everything and installing from scratch. Never had any issues before, but today everything went fine until the first `vagrant up`. It went as usual, showing some npm warnings etc - nothing wrong from the first sight. However, when it went up, only `vvv` and `vvv.dev` domains were added to `/etc/hosts` and in `www` directory I see couple extra directories:

- default
- phpcs
- wordpress-default
- **wordpress-default-provisioner**
- wordpress-develop
- **wordpress-develop-provisioner**
- wp-cli

Those `-provisioner` directories I see for the first time. And from what I understand, it's missing one more standard WP install - `wordpress-trunk`.

If I halt vagrant and up it again, the domains are added to `/etc/hosts` and both `wordpress-default` and `wordpress-develop` installations work. However, those `-provisioner` dirs are still there. Any ideas what went wrong?

<img width="628" alt="screen shot 2016-11-15 at 22 41 12" src="https://cloud.githubusercontent.com/assets/1066083/20323407/3fec678a-ab85-11e6-8da2-0d9b97021f01.png">

**Comment by ihorvorotnov** [comment]
Re-installed again, used VVV stable zip, works fine.

**Comment by LoreleiAurora** [comment]
Nothing has gone wrong, thats the start of the efforts to split provisioners into different repos, see #980
