### ISSUE TITLE
Local .dev sites no longer rendering

### ISSUE THREAD

**Issue by mkjonesuk** [Varying-Vagrant-Vagrants/VVV#1034]
Did a vvv re-build recently, new VirtualBox, Vagrant, new local folder etc.

After a few hours of suffering I still can't get the custom .dev domains I had working previously (via 'Auto site Setup') to render. 

VirtualBox: `5.1.8 r111374 (Qt5.5.1)`
Vagrant: `Vagrant 1.8.6` (1.8.7 was tried and removed as an attempt to fix)
VVV: `latest` 

To be clear, when I visit `coolsite.dev` this would normally load the custom site, setup using `www/coolsite/vvv-hosts` - but instead I'm just getting the basic `vvv.dev` welcome page.

All of the .dev domains **are** being added to my /hosts file - they also remove on reload/provision as standard.

All I can work out at this hour is that once the provision goes through the business of creating the built-in WP test sites it skips to the end of the provision rather than creating the custom .dev sites, see:

```
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: -----------------------------
==> default: Provisioning complete in 139 seconds
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: site-wordpress-default (shell)...
    default: Running: /var/folders/6n/4pcgv2ps39g5rfqcx8dsd6bm0000gn/T/vagrant-shell20161116-633-dd2z5y.sh
==> default: Updating wordpress-default...
==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Already on 'master'
==> default: Your branch is up-to-date with 'origin/master'.
==> default: Creating database 'wordpress_default' (if it's not already there)
==> default:  DB operations done.
==> default: Updating WordPress Stable...
==> default: Error: The site you have requested is not installed.
==> default: Run `wp core install`.
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added local.wordpress.dev from /srv/www/wordpress-default-provisioner/vvv-hosts
==> default: Running provisioner: site-wordpress-develop (shell)...
    default: Running: /var/folders/6n/4pcgv2ps39g5rfqcx8dsd6bm0000gn/T/vagrant-shell20161116-633-1pbuepb.sh
==> default: Updating wordpress-develop...
==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Already on 'master'
==> default: Your branch is up-to-date with 'origin/master'.
==> default: Creating database 'wordpress_develop' (if it's not already there)
==> default:  DB operations done.
==> default: Updating WordPress develop...
==> default: Updating '.':
==> default:
==> default: Fetching external item into 'tests/phpunit/data/plugins/wordpress-importer':
==> default: External at revision 1534736.
==> default: At revision 39263.
==> default: Updating npm packages...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added src.wordpress-develop.dev from /srv/www/wordpress-develop-provisioner/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/wordpress-develop-provisioner/vvv-hosts
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql stop/waiting
==> default: mysql start/running, process 11056
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: Command execution finished.
```

From memory, this part of the process was much longer previously.

I've checked permissions and I have the correct `user:group` permissions to the `vagrant-local` folder. I've also tried with `sudo` a few times which did not help, it in fact made things worse forcing me to destroy the VM and re-provision. 

Any ideas? All I haven't tried is using an older version of VirtualBox or Vagrant, which I had previously (sorry not sure which but well over 1 year ago).

Finally - I'm running OSX 10.10.5 (14F2009).

**Comment by LoreleiAurora** [comment]
What OS are you using?
Do the built in sites show up?
Have you added the site to the config file? (see #980)

**Comment by mkjonesuk** [comment]
Hi @LoreleiAurora here you go:

1. OSX 10.10.5 (14F2009)

2. Yes but they show the WP install screen even though the three databases (_default, _develop, _unit_tests) already exist 

3. Not sure what you mean by 'site' here?

**Comment by grappler** [comment]
> Not sure what you mean by 'site' here?

@mkjonesuk Did you add `coolsite.dev` to the new YMAL cofig file?

**Comment by mkjonesuk** [comment]
I didn't @grappler - note that coolsite.dev doesn't exist but I have 14 folders with pre-configured sites which were copied over from my previous vvv instance. 

Are you saying all of these .dev domains need adding to the YMAL? Is this a new thing in VVV that we need to be aware of when new sites are created? If so is there any way to automate this?

**One small update, I ran `vagrant provision --provision-with site-sitename` this morning and got this:**

```
➜  www git:(develop) vagrant provision --provision-with site-garthwest
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx-xxxxxx-xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx-xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx-xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx-xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xxxxxx.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
➜  www git:(develop)
```

So it's as if it did the hosts update and then just quit - no actual site provision was done. 

I can't test this ATM as I'm not at my develop machine for the next few hours - but if you think adding all those sites to the 'vvv-config.yml' will fix this please confirm and I will give this a shot.

**Comment by LoreleiAurora** [comment]
So you would need to add your custom sites to the `vvv-config.yml` file now, you should end up with a file like below as provisioners for sites don't exist without it. I can guarantee this will fix it.

```YAML
---
sites:
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    vm_dir: '/srv/www/wordpress-default-provisioner'
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    vm_dir: '/srv/www/wordpress-develop-provisioner'
  wordpress-trunk:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
    vm_dir: /srv/www/wordpress-trunk-provisioner
  site1-dir-name: //<-- this is the name of a directory in www, the colon is important.
  site2-dir-name:
  site-3-dir-name:
```

**Comment by mkjonesuk** [comment]
Still no progress @LoreleiAurora could you conform the format here, I've tried:

```
  site-name:
    vm_dir: 'srv/www/site-name'
  site-name:
    local_dir: '/srv/www/site-name'
  site-name:
    vm_dir: '/users/username/server/vagrant-local/www/site-name'
```

Each of these shows: `The host path of the shared folder is missing: /path...` error

**Comment by LoreleiAurora** [comment]
Site: `site-name.com`
Dir: 
```
www/site-name
  - vvv-hosts
  - vvv-provision.sh
  - vvv-nginx.conf
```

Would equal a config of `site-name:` with the colon, without any parameters.

Site: `foo-site.com`
Dir: 
```
www/foo-site-provisioner
  - vvv-hosts
  - vvv-provision.sh
  - vvv-nginx.conf
```

Would equal a config of `foo-site-provisioner:` with the colon, without any parameters.

**Comment by mkjonesuk** [comment]
Sorry @LoreleiAurora - I don't understand this. Could you try explaining further with a different example?

**Comment by kapilpaul** [comment]
Hi @LoreleiAurora I tried everything. but cannot go to my site with desired name.

in vvv-hosts

`# The main site domain
kaps.dev`

in vvv-config.yml
`kaps:
    vm_dir: '/srv/www/php_oop_practice'`

and change in etc/hosts file. but nothing changed

**Comment by LoreleiAurora** [comment]
is the site dir in www named `kaps`?

**Comment by kapilpaul** [comment]
yes its in www dir

**Comment by LoreleiAurora** [comment]
So if your dir is names kaps you should add `kaps:` to the bottom of the sites array __indented with 2 spaces__, tabs will not work.
The other config options should not be needed.
After doing this please post the output of `vagrant provision --provision-with site-kaps`

**Comment by kapilpaul** [comment]
@LoreleiAurora 

I tried as you advised. but now its 403 forbidden. (http://prntscr.com/df9xxz)

please check the screenshots.

these are my two folders http://prntscr.com/df9wue
for /etc/hosts http://prnt.sc/df9vbo
in vagrant ssh http://prntscr.com/df9vwp
for vvv-config.yml  http://prntscr.com/df9w9d
for vvv-hosts in provision folder http://prntscr.com/df9wje

**Comment by LoreleiAurora** [comment]
Okay, i have nearly all i need but can you please post the actual output of `vagrant provision --provision-with site-testoop`

**Comment by kapilpaul** [comment]
this is the output

`Kaps-Virtual-World:vagrant-local kapilpaul$ vagrant provision --provision-with site-testoop
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 testoop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: Running provisioner: site-testoop (shell)...
    default: Running: /var/folders/ww/sb4qb21x5rv43znjhwcgq1k00000gn/T/vagrant-shell20161205-6518-nzeg1g.sh
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added testoop.dev from /srv/www/testoop-provisioner/vvv-hosts`

**Comment by LoreleiAurora** [comment]
Okay so it dosen't actually run the provisioner, can you show a file list of those 2 directories?

**Comment by kapilpaul** [comment]
In testoop dir http://prntscr.com/dfasts
in testoop-provisioner dir http://prntscr.com/dfat73

NB: init & nginx are empty.

**Comment by LoreleiAurora** [comment]
Please delete the vm_dir line and rename the site to `testoop-provisioner:` so your entire config entry is `testoop-provisioner:`.

then re-run `vagrant provision --provision-with site-testoop`

**Comment by kapilpaul** [comment]
I just did like that but the same problem is still there. now its redirect to vvv.dev

**Comment by LoreleiAurora** [comment]
can you post your vvv-init.sh file (not a screenshot) so i can test this further.

**Comment by kapilpaul** [comment]
sure.  but the file is empty. i wrote it earlier init & nginx files are empty.

**Comment by LoreleiAurora** [comment]
If the vvv-init.sh file is empty then there is no provisioner for the site & if the vvv-nginx.conf file is empty the site is not added to nginx and therefore will show vvv dashboard no mater what we do.

**Comment by kapilpaul** [comment]
i donot want to install wp in this directory. I want to use it for php. can you send me these two files with the codings in it?

**Comment by kapilpaul** [comment]
I just did it. Now its successfully running. Thanks a lot

**Comment by kapilpaul** [comment]
in vvv-init.sh

<pre>
`
# Nginx Logs
if [[ ! -d /srv/log/testoop ]]; then
    mkdir -p /srv/log/testoop
fi
    touch /srv/log/testoop/error.log
    touch /srv/log/testoop/access.log
`
</pre>

in vvv-nginx.conf
<pre>
`server {
    listen       80;
    listen       443 ssl;
    server_name  testoop.dev *.testoop.dev ~^local\.testoop\.\d+\.\d+\.\d+\.\d+\.xip\.io$;
    root         /srv/www/testoop;

	error_log    /srv/log/testoop/error.log;
	access_log   /srv/log/testoop/access.log;

    include      /etc/nginx/nginx-wp-common.conf;
}`
</pre>

**Comment by kapilpaul** [comment]
@LoreleiAurora 

Again i have the same problem. On that you show me correct path to solve the issue and Its works. but now I have again the same problem. this tricks not working. I dont know why.

please check this

<pre>
`$ vagrant provision --provision-with site-testoop-provisioner
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.50.4  testoop.dev  # VAGRANT: e30ec159fbdb81f491bb8d0334ad4c7d (default) / 7212251b-7963-4c84-845a-917aa4246957
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.`
</pre>

**Comment by jeremyfelt** [comment]
@kapilpaul The [1.4.0 release](https://github.com/Varying-Vagrant-Vagrants/VVV/releases/tag/1.4.0) of VVV loops though all of your directories to look for individual provision files for each of your sites.

The [develop](https://github.com/Varying-Vagrant-Vagrants/VVV) branch of VVV, which should currently be considered unstable, has a new provisioning process that we're still working out the details on. See #1046 and #980 as well as the documentation in progress at https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/7

I would recommend sticking with the stable version for now as things are still likely to change. If you'd like to dig further, I'd recommend reading through those previous pull requests to become familiar with the configuration.

I'm going to close this issue out for now as it seems to be a side-effect of the process not being completely documented yet. Please feel free to open new issues with specific bugs. Thanks!
