### ISSUE TITLE
Document the new provisioning system

### ISSUE THREAD

**Issue by LoreleiAurora** [Varying-Vagrant-Vagrants/VVV#1035]
I need help from somebody to document the new provisioning system in #980, #1021 #1053 & #1055.
Every time i try to write the docs they make no sense.

**Comment by grappler** [comment]
@LoreleiAurora Do you have the draft that you have started? Perhaps I could attempt to follow it and then let you know what I don't understand and give a few suggestions.

**Comment by LoreleiAurora** [comment]
Thanks, will get one over to you this week :)

**Comment by AdamQuadmon** [comment]
@LoreleiAurora , @grappler I'm also interested in this, may I help?

**Comment by LoreleiAurora** [comment]
@grappler @AdamQuadmon Sorry, totally forgot about this, have added you both [Here](https://github.com/LoreleiAurora/varyingvagrantvagrants.org) and uploaded my terrible draft.

**Comment by kopepasah** [comment]
@LoreleiAurora should this be closed in lieu of #1049? If so, I recommend creating an addition ticket to for creating an automated process to push the documentation to the vvv.org repo.

**Comment by grappler** [comment]
@leewillis77 @tomjn wrote a good blog post on it. https://tomjn.com/2017/01/16/whats-new-vvv-2-0/

**Comment by leewillis77** [comment]
@grappler Not sure why I got pinged on this? It's not anything I recognise?

**Comment by grappler** [comment]
@leewillis77 Sorry meant to ping @LoreleiAurora

**Comment by leewillis77** [comment]
No worries - just checking!

**Comment by tomjn** [comment]
I'm more than happy for the blog post to be broken up into pages and used as the foundation of the documentation, I spoke with @LoreleiAurora in writing it and I mentioned if every heading was turned into a page, an installation page added, a page saying what VVV is, and a reference section that listed each `vvv-config.yml` value and some other things then that's documentation mostly done

**Comment by LoreleiAurora** [comment]
Fixed in #1112
