### ISSUE TITLE
Updating phpMyAdmin

### ISSUE THREAD

**Issue by joffff** [Varying-Vagrant-Vagrants/VVV#1036]
I'd like to update the version of phpMyAdmin that's included in the provision file (4.6.0 - latest is 4.6.4) but I'm unsure on how to do this.

I've updated the provision file to use the latest version and have tried to reload and force provision vagrant but my changes aren't taking effect.  Can I do this via SSH?

**Comment by cfoellmann** [comment]
We are working on making updates automatic.
For what you have done to work you need to delete the default/database-admin folder so the provision process "installs" phpmyadmin with your modified versuob

**Comment by joffff** [comment]
Thanks @cfoellmann that's worked.  I had tried to bypass the conditional test for the database-admin folder in the provision file but removing the entire folder works as intended.

**Comment by cfoellmann** [comment]
Keep an eye on this https://github.com/Varying-Vagrant-Vagrants/vvv-utilities
