### ISSUE TITLE
Wrong permission on db_restore

### ISSUE THREAD

**Issue by grks** [Varying-Vagrant-Vagrants/VVV#1038]
Shouldn't db_restore in config/homebin have permission +x (git update-index --chmod=+x)?

**Comment by jeremyfelt** [comment]
Hi @grks, thanks for opening an issue. You're right, it does look like this is not executable like the other files in this directory. It's surprising this hasn't been noticed! Maybe a good indicator of how often people are restoring databases. :)

**Comment by tomjn** [comment]
Closing as this isn't an issue in the latest VVV releases
