### ISSUE TITLE
Make setting up a custom site EASY. (How to do it right now?)

### ISSUE THREAD

**Issue by nextgenthemes** [Varying-Vagrant-Vagrants/VVV#1044]
Please provide me with simple steps how to have a custom site with wordpress trunk and its own database setup.

I will keep it short there seems to be a new provisioning system and I just after trying various things I failed to set up a custom local domain. I keep it short. I read the wiki, tried to setup a new site and failed.

I also tried the vv site setup tool, it failed, also current build shows as failed on github. I think such a tool, at leasts the basics of it should actually be part if this project I think. Like a simple command to setup a new site for example.

There seems to be new provisioning system involving the yml config file with documentation in the works.

I am a technical person and usually have no problems figuring things out but I don't know whats new way whats the old way. It seems new way needs to be on top of the old way. It seems to me its a pain in the ass to just setup another site. I think it should be actually made **easy!**

Maybe I am missing something and its actually easy but ...

It seems I need to create/copy/edit 3 different files to just setup a new site? Is this right? https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Auto-site-Setup and the new provisioning yml. I do not know what to put in there. I setup `vm_dir: '/srv/www/arve-dev-provisioner' for a arve_dev: site I want to setup but it says the directory does not exist during provisioning.

Here is my proposal how to create a site.

```
  arve-dev:
    domain: arve.dev
    wp_version: nightly
```

Simple as that, database folders and stuff should be created automatically.

**Comment by kopepasah** [comment]
@nextgenthemes this may be related to #1045. Can you try checking out the latest tag (currently `1.4.0`) and see if you still experience this issue?

**Comment by nextgenthemes** [comment]
@kopepasah Its not about a "issue" I asked various specific things ...

**Comment by LoreleiAurora** [comment]
@nextgenthemes 
- If you have a vvv-config.yml you are not on 1.4.0 you are on the develop branch.
- 1.4.0 is available on the master beanch or as a tag.
- The VV setup tool will work with 1.4.0.
- The docs in the wiki work for all versions up to and including 1.4.0.
- For as long as VVV has supported custom sites it has required 3 files. (an example of these files can be found [here](https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default))
- You create your own provisioning scripts as alot of people have different requirements for alot of sites.

If you downgrade to 1.4.0 then you can just base your config off my example above.

If you do not downgrade then you still create the 3 files but add the directory name followed by a colon to the sites list in vvv-config.yml

Also i did not tag this and leave, i typed this out, got a github error which deleted my comment then went to bed angry with the intent to reply next time i had time.

I think i have answered all your questions, let me know if i missed any.

**Comment by jeremyfelt** [comment]
The new provisioning process is still a work in progress. See #1035 for the effort to document the changes.

Once we have a few things settled, it will be easier to determine (before the 2.0.0 release) what can be improved. In the meantime, please open new issues for any specific suggestions to markup changes in the YAML configuration.

**Comment by nextgenthemes** [comment]
@LoreleiAurora 

> For as long as VVV has supported custom sites it has required 3 files. (an example of these files can be found here)

This is still not clearly answering my question. I am not interested in the past, I am interested in how its done on your current dev versions. As far as I understand it the vvv-hosts is optional if I edit my hosts manually. But my question was of the new .yml file relates to this. It seems like its needed to edit this as well to make the other 2 or 3 files work. So a 3rd time:

Do you need to edit/modify/copy 3 with a optional 4th file now? the .yml and the 2 (or 3) files in the sites folder? It seems this is the case now and instead of making it more easy you seem make it even more complicated.

**Comment by LoreleiAurora** [comment]
To quote my last answer:

> you still create the 3 files from the example and add the directory name followed by a colon to the sites list in vvv-config.yml

For some more advanced users vvv-config.yml makes the too way more powerfull, for less advanced users adding 1 line to a file is not really more complicated.

**Comment by jeremyfelt** [comment]
> This is still not clearly answering my question. I am not interested in the past, I am interested in how its done on your current dev versions.

@nextgenthemes The changes to the provisioning process in the development branch will be documented properly before VVV 2.0.0 is released. See #1035

For now, the documentation reflects the provisioning process from 1.4.0 and earlier. You can get a copy of the stable version of VVV at https://github.com/Varying-Vagrant-Vagrants/VVV/releases/tag/1.4.0

It's tough to parse what seems like a mix of support questions and enhancement suggestions, especially on something that's still in progress. Please appreciate the attempts to help.
