### ISSUE TITLE
Manage README table of contents with markdown-toc

### ISSUE THREAD

**Issue by corysimmons** [Varying-Vagrant-Vagrants/VVV#1047]
https://github.com/jonschlinkert/markdown-toc

**Comment by jeremyfelt** [comment]
Hi @corysimmons, thanks for opening an issue. Can you expand on your request? How do you see markdown-toc being used as part of the VVV project? Is this directed at the (now very long) README file or toward our newer documentation efforts? See #1049.

**Comment by corysimmons** [comment]
Most READMEs, including this one, have a lot of sub-headings I'd be interested in browsing over.

markdown-toc will automate that and makes skimming for particular content in larger READMEs (like this one) much easier.

**Comment by jeremyfelt** [comment]
Thanks for the clarification, @corysimmons. Let's keep this issue open for now (I'm going to adjust the title) and then revisit after the README has been split into pieces for varyingvagrantvagrants.org via #1049 and #963. The markdown-toc project looks cool and may be useful in the future depending on how long our README ends up being.

**Comment by tomjn** [comment]
Closing this as since this issue was last touched, the vvv docs site underwent an overhaul
