### ISSUE TITLE
Provide versioned documentation for use on varyingvagrantvagrants.org

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1049]
I had a conversation with @kopepasah via Slack the other day about how to better organize documentation so that it can be properly versioned as new releases are posted.

The brief conclusion from that conversation was that we could have a `docs/` directory inside this (VVV) repository. Through a deployment process, this `docs/` directory can be combined with the [vvv.org repository](https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org) to create the final version at varyingvagrantvagrants.org.

The URLs should probably result in something like:

* `https://varyingvagrantvagrants.org/documentation/en-US/current/` (latest release docs)
* `https://varyingvagrantvagrants.org/documentation/en-US/develop/` (develop branch docs)
* `https://varyingvagrantvagrants.org/documentation/en-US/x.y.z/` (archived release versions)

Note the `en-US/` directory in the URLs. It'd be great to account for translations in the planning for this. I'm not sure how much we'd have right away or how great the translation workflow would be, but future proofing would be :100:.

I think @kopepasah has already started thinking about this and was planning on a fork/PR to add some initial documentation. I'll start thinking about how to setup the deployment(s) in the right way to feed the Jekyll based varyingvagrantvagrants.org.

Feedback welcome!

**Comment by jeremyfelt** [comment]
Some more notes on possibilities here after a chat with @LoreleiAurora.

* @LoreleiAurora has done some cross repository builds in Travis before, so we can look to those repositories as an example.
* We should consider the possibility of a process that submits the documentation maintained in markdown as part of the repository to a WordPress site via the REST API.
* Some form of documentation should be created against `master` based on the README and then merged so that it can exist in `documentation/en-US/1.4.0` to show the previous state before the changes in 2.0.0 are officially released.

**Comment by jeremyfelt** [comment]
#963 can probably be closed as part of a pull request to add 1.4.0 documentation.

**Comment by kopepasah** [comment]
Just a quick update that I have [forked VVV](https://github.com/kopepasah/VVV) and will start documentation.

**Comment by grappler** [comment]
@kopepasah See this [issue](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1035) too where @LoreleiAurora already started part of the documentation.https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1035

**Comment by kopepasah** [comment]
@grappler thanks for mentioning. We discussed and the documentation on vvv.org will just use the data from documentation within a specific tag or branch, utilizing a `/docs` directory within VVV. #1035 was created before the discussion and probably can be closed in lieu of this ticket.

**Comment by jeremyfelt** [comment]
We're doing this now. :1st_place_medal:
