### ISSUE TITLE
Provide some basic information on available utilities

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1056]
We should have an overview of the utilities in the [VVV Utilities](https://github.com/Varying-Vagrant-Vagrants/vvv-utilities) repository README along with a basic example of how to enable each in the `vvv-config.yml` or `vvv-custom.yml` files.

Detailed documentation for this should live in VVV, but at least a hint of what's going on will be good to have there.

**Comment by tomjn** [comment]
Ah forgot about this issue, it's live at https://varyingvagrantvagrants.org/docs/en-US/utilities/
