### ISSUE TITLE
"vagrant destroy" followed by "vagrant up" makes me re-install WordPress

### ISSUE THREAD

**Issue by jeffjg** [Varying-Vagrant-Vagrants/VVV#1059]
Is this how it's supposed to operate?

-Jeff

**Comment by jeremyfelt** [comment]
Hi @jeffjg, welcome. :)

Yes, `vagrant destroy` destroys the virtual machine completely. All of the software and data stored inside the virtual machine is no longer available. This includes things like the MySQL databases that contain the data from a WordPress installation.

There are a couple scripts included with VVV that are an attempt to help with automatic backups and imports, but nothing is a replacement for creating a workflow that fits for what you're doing. Backups can be created manually through phpMyAdmin (via vvv.dev) or through the MySQL command line utility.

**Comment by masteryprep** [comment]
Excellent, thanks for the detailed information!

**Comment by jeffjg** [comment]
Excellent, thanks for the detailed information!
