### ISSUE TITLE
Strange Error on vagrant up: nginx: [emerg] directive "set" is not terminated by ";" in /etc/nginx/custom-sites/...

### ISSUE THREAD

**Issue by pierrerocket** [Varying-Vagrant-Vagrants/VVV#1061]
Greetings, 

I am a new vagrant user. My apologies, I hope this is the place for me to ask a question.

I followed the instructions, got everything working.  Was using it for a few days trying to get the hang of things.  Well, today I decided to delete a site.   I deleted the site and went to create a new one and I got an error on vagrant up.

Here is what i get in console...

https://gist.github.com/pierrerocket/9d2cc7e8829fa92c04662e68700dedc3

I tried my best to google around and figure this out, but I am stuck.  Can anybody give any advice?  

Kind Regards,

**Comment by Seabastian** [comment]
I had this issue today, the problem was that i didn't do vagrant halt on a computer restart.

Maybe you can try to run this at te folder where your vagrant is installed: 
vagrant reload --provision

That did the trick for me.

**Comment by LoreleiAurora** [comment]
@pierrerocket @Seabastian This is due to you using the develop branch which is under very active development.

Please do a `git pull` on the VVV repo followed by a `vagrant provision` as there have been breaking changes in the last few days.

**Comment by Seabastian** [comment]
@LoreleiAurora Oke.. 

This is on line 15 of the file you asked about:

access_log   /srv/log/wordpress-develop/src.access.log;

**Comment by LoreleiAurora** [comment]
@Seabastian Sorry i got my line numbers wrong, i mean line 17.

**Comment by Seabastian** [comment]
That's :

set $upstream {upstream};

**Comment by pierrerocket** [comment]
git pull and provision did the trick, thanks a ton @LoreleiAurora

**Comment by ColeHub** [comment]
@LoreleiAurora that did it for me, thanks a bunch!
