### ISSUE TITLE
Query parameters are ignored when accessing the WP REST API

### ISSUE THREAD

**Issue by jmichaelward** [Varying-Vagrant-Vagrants/VVV#1062]
## Expected Behavior

When accessing the WordPress REST API, users should be able to pass a query parameter to receive a particular set of data. For instance, accessing `https://example.com/wp-json/wp/v2/posts?page=2`should return a response containing a second page of posts data.

See https://developer.wordpress.org/rest-api/pagination for additional examples.

## Current Behavior

Currently, adding a query parameter to an endpoint returns the same set of data. If, for instance, WordPress is set to show 10 posts per page, accessing the `posts` endpoint will return 10 results, and accessing the `posts?page=2` endpoint will return the same results.

## Possible Solution

The WP REST API documentation suggests that Nginx needs to be configured properly in order for query parameters to function correctly. See: http://v2.wp-api.org/guide/problems/#query-parameters-are-ignored

Thus, it would seem that Line 12 of the `nginx-wp-common.conf` file would need to be updated to reflect this recommended change. 

## Steps to Reproduce (for bugs)

1. Boot up a VVV site running WordPress 4.7
2. Ensure you have more posts entered than is set to display on a single page.
3. Visit `http://[your-domain].dev/wp-json/wp/v2/posts` and take note of the results.
4. Visit `http://[your-domain].dev/wp-json/wp-v2/posts?page=2` and compare the results from step 3. They will be the same, though they should be different.

## Context

I'm attempting to use the new WP REST API to output a collection of posts plus pagination, and to provide users with inputs to filter the result set by taxonomy. Currently, I am not able to test this in VVV. 

## Your Environment

* VVV version: Latest
* Vagrant version: 1.8.1
* VM Provider name:  VirtualBox
* VM Provider version: 5.0.24
* Operating System and version: macOS Sierra 10.12.1

**Comment by jeremyfelt** [comment]
Thanks for opening a ticket, @jmichaelward!

We'll want to make sure our `try_files` directive is as follows:

`try_files $uri $uri/ /index.php$is_args$args;`
