### ISSUE TITLE
extconf failed, exit code 1

### ISSUE THREAD

**Issue by devloprs** [Varying-Vagrant-Vagrants/VVV#1066]
I am just following the basic install of vvv. I have vagrant and virtualbox installed and at the first line of preparing vagrant for vvv where you set up the host autoconfig I get a ton of ruby errors. 

I am using ubuntu 16.10 with Vagrant 1.8.5 I then run:
vagrant plugin install vagrant-hostsupdater
and I get the following error:

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.7.0), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.7.0'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/midi/.vagrant.d/gems/gems/nokogiri-1.7.0/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20161229-27876-sq49lt.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/midi/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/nokogiri-1.7.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/midi/.vagrant.d/gems/gems/nokogiri-1.7.0 for inspection.
Results logged to /home/midi/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/nokogiri-1.7.0/gem_make.out

I also get that error when installing Triggers. 

Any help appreciated.

@devloprs

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version:
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by jeremyfelt** [comment]
Hi @devloprs, thanks for taking the time to open a ticket.

This appears to be an issue either with Vagrant or one of the Vagrant plugins rather than something specific to VVV.

Strangely enough, I just setup a fresh install of Ubuntu 16.10 today on my laptop, so I can offer at least one suggestion! :smile: 

I installed VirtualBox 5.1.12 and Vagrant 1.9.1 and had no issue installing either `vagrant-hostsupdater` or `vagrant-hosts`.

I would recommend upgrading VirtualBox and Vagrant to those versions and trying again. Otherwise, it would be worth searching through open Vagrant issues for a possible match.

**Comment by devloprs** [comment]
How did you get that version of vagrant?

**Comment by jeremyfelt** [comment]
@devloprs It's the one currently available as a `.deb` package via https://www.vagrantup.com/downloads.html

**Comment by devloprs** [comment]
k thanks alot I got 1.8 from the ubuntu repos also got Virtual Box 
5.1.6_Ubuntur110634 out of the repos. Thanks for the help

**Comment by devloprs** [comment]
The Vagrant Version did it. You rock. I would be disappointed if I 
couldn't use this with 16.10

Thanks,

Bradley
