### ISSUE TITLE
Provide php-memcached in default provisioning

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1067]
I'm not familiar with all of the details, but it seems that the `php7.0-memcache` package we install during provisioning doesn't really all that well. If it does work, then it at least does not work with the WordPress core unit tests and [batcache](https://wordpress.org/plugins/batcache) as the drop-in.

I think we can install `php-memcached` alongside the `php7.0-memcache` package. With this available, we can use the [PECL memcached](https://github.com/tollmanz/wordpress-pecl-memcached-object-cache) drop-in instead.

**Comment by JJJ** [comment]
This is exactly what I do. I half-assumed it was my goofy setup for WP Spider Cache that was the problem.

Here's the extra dependencies, if that matters:

<img width="493" alt="screen shot 2016-12-30 at 8 06 28 pm" src="https://cloud.githubusercontent.com/assets/88951/21575232/970d2068-cecb-11e6-9af6-d49451ca0d7f.png">

**Comment by grappler** [comment]
We had a similar problem with our our vagrant setup which we solved by installing the `memcached` package  on the server alongside `nano`.
