### ISSUE TITLE
Re-add auto site creation to the new provisioning system.

### ISSUE THREAD

**Issue by kopepasah** [Varying-Vagrant-Vagrants/VVV#1081]
One thing that existed prior to the new provisioning system is the ability to have sites auto provision (without editing any files). This was accomplished by using `vvv-init.sh` within five subdirectories of VVV root, and is especially beneficial for non-devs (who do not want to edit files).

As such, we should have the ability to include something link a `vvv-config.yml` or `vvv-custom.yml` within a site, to auto add a site to the `sites` object. After much thinking and testing, believe the only way to do this is to add an additional option (to `vvv/vvv-config.yml) to designate a location for provisioning to look for these files.

I am not 100% convinced that this is needed (but I do know it is beneficial). 

Let's discuss.

**Comment by LoreleiAurora** [comment]
Personally i do not like this idea as the only change to the process is adding a single line to vvv-config.yml.
This could get confusing in the end with vvv-config.yml files all through www (and difficult to debug).
Plus i know vv is getting updated as soon as bradp has time.

**Comment by kopepasah** [comment]
@LoreleiAurora I tend to agree with you but wanted to bring it up as this is a feature which I know many people tack advantage.

**Comment by jeremyfelt** [comment]
Agreed with @LoreleiAurora. I think the auto provision process served its purpose in earlier versions of VVV, but the YAML config is much more powerful. The biggest reason may be that you can target a new site for provisioning without running everything else at once.

Thanks for the suggestion, @kopepasah!
