### ISSUE TITLE
Issues with accessing front page of wordpress site

### ISSUE THREAD

**Issue by mxp83** [Varying-Vagrant-Vagrants/VVV#1083]
I'm having an issue when I build a site using Variable VVV - a VVV Site Creation Wizard, where the site builds completely fine, but I cannot access the domain (let's say example.dev) when I type it on the browser.  I can access the wordpress admin by adding /wp-admin at the end, but I cannot access the website otherwise.  I have access to the database as well, but I just can't see the site, even if I click on the url through the dashboard.

I've deleted the site multiple times, removed the hosts, and even reinstalled vagrant and vvv...I still can't access example.dev...Is there something I'm missing?

**Comment by LoreleiAurora** [comment]
@mxp83 The issue template is there to help people support you easier, and avoid this question.

Please can you give the following information.

## Your Environment
Include as many relevant details about the environment you experienced the bug in
* VVV version:
* Vagrant version:
* VM Provider name: This is likely VirtualBox, but VVV supports Parallels and VMWare Fusion as well.
* VM Provider version:
* Operating System and version:

**Comment by mxp83** [comment]
My apologies.  I just realized that there's far more than just this virtual domain being an issue.  I am going to reinstall everything from scratch and hopefully this should fix the error.  Please close this thread.
