### ISSUE TITLE
Newly created databases not backing up on vagrant halt after upgrade

### ISSUE THREAD

**Issue by blairworks** [Varying-Vagrant-Vagrants/VVV#1085]
## Summary of issue
After updating VVV and new sites I create to not have their databases dumped on halt. All the sites that already existed pre-upgrade are dumping during the halt trigger just fine.

## How I got here
I've recently updated VVV (1.4), as well as bradp's Variable VVV (1.12) and have stumbled through learning the new provisioning system. The steps I took to add a new site were:

- Used bradp's wizard to create a site. This left me with 3 files in the directory, but no WordPress install yet, as used to occur.
- I added the directory name to the sites object in vvv-config.yml and did a "vagrant up --provision"

Everything seemed to work until I did a "vagrant halt". The db_backup triggers dumped the databases for every site except for the new one. There are no errors written to the terminal output.

Is there another step I am missing in the new provisioning process to add the triggers so that the database is dumped to /database/backups/ ? Or is this possibly a bug. 

After reading through how the db triggers work, I'm under the impression that all databases are dumped -- I'm not sure how these databases are any different.

The databases themselves do seem to survive a "halt" just fine, but I'm assuming I cannot do a "destroy" until I sort this out unless I resort to manual backups.

If this is not a bug, any debugging tips or help would be greatly appreciated.

## My Environment

* VVV version: 1.4
* Vagrant version: 1.8.6
* Variable VVV version: 1.12
* VM Provider name: VirtualBox
* VM Provider version: 5.1.8 r111374
* Operating System and version: OS X El Capitan 10.11.6

**Comment by LoreleiAurora** [comment]
As you have a vvv-config file you are on develop not 1.4.

The [script to dump databases](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/db_backup) has not been modified in ~ 3 years and should not be affected by the new provisioner.

Can you provide steps to reproduce this behaviour?

**Comment by blairworks** [comment]
Ahh... I **am** on develop. I had seen 1.4 in the changelog and had thought I was originally setup on a stable branch. Is it possible that the original setup instructions from a couple years ago recommended the develop branch? I don't think I would have picked that. 

Thanks for pointing out the [relevant script](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/db_backup). I think I see the issue. The new sites I have created all have the word "test" in the directory name. It looks like databases that include "test" in the name are skipped over in line 10:

`grep -v -F "test" | \`

 Now I'll know to avoid that, but I'm thinking this may be a common pitfall as there are many legitimate reasons to use 'test' as part of a name where a backup would still be desired.
