### ISSUE TITLE
Provisioning gets stuck after an NPM warning

### ISSUE THREAD

**Issue by benlk** [Varying-Vagrant-Vagrants/VVV#1086]
## Expected Behavior

When running `vagrant up` on [a fresh install](https://github.com/Varying-Vagrant-Vagrants/VVV#installation---the-first-vagrant-up) of vvv, the provisioning script runs, and should finish running.

## Current Behavior

When provisioning, the log hangs after this message, and makes no progress thereafter (at least, for 20 minutes while connected to the internet)

```
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: deprecated
==> default:  minimatch@0.2.14: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: deprecated
==> default:  minimatch@0.3.0: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: deprecated
==> default:  graceful-fs@1.2.3: graceful-fs v3.0.0 and before will
fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as
soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
^C==> default: Waiting for cleanup before exiting...
^C==> default: Exiting immediately, without cleanup!
```

This only happens when the box is being provisioned (I'm using vv, which when running `vv create` re-provisions the box), and not at any other time that `vagrant up` is run.

This prevents the `vvv-init.sh` script from running, so you have to run that manually from within `vagrant ssh`

## Possible Solution

I'm not sure, but a look at the bootstrap scripts and the versions of various Node scripts used there might be warranted.

## Steps to Reproduce (for bugs)

1. From the current `master` branch of VVV, create a fresh installation: https://github.com/Varying-Vagrant-Vagrants/VVV#installation---the-first-vagrant-up and run `vagrant up`

## Your Environment

* VVV version: current `develop`
* Vagrant version: 1.9.1
* VM Provider name: Virtualbox
* VM Provider version: 5.1
* Operating System and version: OSX 10.10

**Comment by benlk** [comment]
sorry, when I created this ticket I was on `develop`, not `master`. I've updated the ticket and will try again with master, and, failing that. 1.4.0

**Comment by LoreleiAurora** [comment]
Master is 1.4.0

The develop branch has a new provisioner, you need to do the following:
1. copy `vvv-config.yml` to `vvv-custom.yml`
2. add the site dir to the list in vvv-custom.yml

e.g. if your site is in `www/example` under sites add `example:` (the trailing colon is important)
if your site is in `www/foo.com` under sites add `foo.com:` (the trailing colon is important)

**Comment by benlk** [comment]
I just decided to do a reinstall from the 1.4.0 branch, because in this case I need a stable user experience.

Before doing the reinstall, the script passed the point noted in this issue, so it looks like it was more of a network problem than anything in the provisioner scripts.
