### ISSUE TITLE
Could not rename the directory... to save the settings file (VERR_ALREADY_EXISTS)

### ISSUE THREAD

**Issue by glerner** [Varying-Vagrant-Vagrants/VVV#1087]
Posted comment to same issue on https://github.com/Varying-Vagrant-Vagrants/VVV/issues/918 
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/997
but both those issues are marked 'closed'.

Windows 10, Oracle VirtualBox Version 5.1.12 r112440 (Qt5.6.2), Vagrant 1.9.1
Administrator: Windows PowerShell (same results in GIT Bash shell)

git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git vagrant-local
cd vagrant-local

Vagrant up -- Is trying to move the Ubuntu folder to the just-created VVV folder, which is of course not empty. No "VM with that name already exists", but rather "Could not rename the directory".

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vagrant-local
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\home\glvagrant\ubuntu-cloudimg-trusty-vagrant-amd64_1484515175502_39880' to 'C:\home\glvagrant\vagrant-local' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManageModifyVM.cpp

If am in GIT Bash shell, and have (in Oracle VM VirtualBox Manager) Started the just-installed ubuntu/trusty64 VM, I instead get:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: Running provisioner: fix-no-tty (shell)...
SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.

**Comment by lv7777** [comment]
I have a same issue.
when use vagrant via wsl, this error was occurred.
```
(VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknownVBoxManage.exe: error: Context: "SaveSettings()" at line 3093 of file VBoxManageModifyVM.cpp
```

**Comment by tomjn** [comment]
I this still persists when using Vagrant 2.1.x or higher please open a new issue. A lot has changed since this issue was raised. This issue sounds like a naming issue of the VM, something that was encountered and fixed elsewhere years ago
