### ISSUE TITLE
Virtual Box Guest Additions not mapping after an upgrade

### ISSUE THREAD

**Issue by devloprs** [Varying-Vagrant-Vagrants/VVV#1091]
virtual box guest additions is not mapping back to the www folder of my vvv-develop directory

I recall an upgrade of somesort to vvv and I have not been able to get it to work since. I have read most people do not upgrade as this is often a resultant problem

I must think that as a result of searching around on uncle google that this happens but I'll be danged if I can find a resolution. :(

## Steps to Reproduce (for bugs)
just reset up a new vvv-develop folder and run vagrant up and vagrant provision from within the folder
No local files set up to be mapped to and no mapping taking place. 

I get numerous errors:

==> default: From https://github.com/squizlabs/PHP_CodeSniffer
==> default:  * branch                master     -> FETCH_HEAD
==> default:    521692bdc..339dc9cda  master     -> origin/master

==> default: From https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
==> default:  * branch            master     -> FETCH_HEAD

==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-utilities
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Already on 'master'

==> default: From https://github.com/rlerdorf/opcache-status
==> default:  * branch            master     -> FETCH_HEAD

==> default: From https://github.com/michaelschiller/webgrind
==> default:  * branch            master     -> FETCH_HEAD

==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default
==> default:  * branch            master     -> FETCH_HEAD

==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Already on 'master'

I don't think these errors relate to my issue but red is so scary. I am frightened.

thanks

Bradley

Oh I get all this scary stuff too....

==> default: Previous HEAD position was 1b23052... [install script] Use `$HOME` variable in `NVM_DIR`
==> default: HEAD is now at 40e4097... v0.33.0
==> default: /usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
==> default: /usr/lib
==> default: └── npm@4.1.1 
==> default: /usr/bin/npm-check-updates -> /usr/lib/node_modules/npm-check-updates/bin/npm-check-updates
==> default: /usr/bin/ncu -> /usr/lib/node_modules/npm-check-updates/bin/ncu
==> default: /usr/lib
==> default: └── npm-check-updates@2.8.9 
==> default: ack-grep already installed
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Updating Composer...
==> default: You are already using composer version 1.3.1 (stable channel).
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Loading composer repositories with package information
==> default: Updating dependencies (including require-dev)
==> default: Nothing to install or update
==> default: Generating autoload files

## Your Environment

* VVV version:
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by jeremyfelt** [comment]
Hi @devloprs, thanks for opening an issue. Can you provide more details about the error or problem you're seeing? The pasted text above is all normal as part of provisioning. It is annoying that it switches to red for some things.

It would also be helpful to know your environment details - VVV version, Vagrant version, etc...

**Comment by devloprs** [comment]
ok 

midi@Aspire-E5-411:~/DEV/websites/sites/VVV-develop$ vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.1

VVV:

* **Version**: develop
* **Latest Stable**: [1.4.0](https://github.com/varying-vagrant-vagrants/vvv/tree/1.4.0)

I might add that this was the only version I really had _any luck_ with at all. It was recommended by to Tophler to use that one. It was working well for a while and then died. I do remember some kind of upgrade but like an idiot I didn't note what it was for I thought it might be VVV so I did it without taking note. 

I am totally willing to remove vagrant and vvv if I can find out a way to get rid of all of it's various init mapping locations as well. I know I love it when it works and I can develop in one environment with it. I don't know how to use it in any advanced way and have had no luck with VV either which btw I have installed as well but did not use to provision anything. In the case of this scenarion I destroyed the VB box and start fresh and it runs wordpress but my files are all in the VB box and not in my dev project directory. 

I appreciate your help in this!

Bradley

**Comment by jeremyfelt** [comment]
@devloprs Thanks for the additional info. I'm going to bug you for a few more pieces of information:

* Operating System
* VirtualBox version
* Output of `vagrant plugin list`
* Output of `vagrant box list`

And from the report, I gather that the `VVV-develop/www/` directory is not mapping to `/srv/www/` inside the VM?

**Comment by jeremyfelt** [comment]
Closing this out for now, feel free to reopen if needed. :)
