### ISSUE TITLE
local.wordpress-trunk.dev Removed

### ISSUE THREAD

**Issue by Gemfruit** [Varying-Vagrant-Vagrants/VVV#1096]
I just did a fresh install of Windows, and had to set up my environment one again. For testing, I was visiting https://local.wordpress-trunk.dev , which wasn't working. It took me a bit to realize this, but the other default links work, while this is the only one that doesn't. I haven't read up on it, but it appears to have been removed from the setup.

Simply put, if I'm correct, please remove the local.wordpress-trunk.dev link from the documentation on https://varyingvagrantvagrants.org/ to avoid confusion, thanks!

**Comment by jeremyfelt** [comment]
Hi @Gemfruit, thanks for opening an issue! This will be resolved once VVV 2.0.0 is released via the new documentation from #1112.
