### ISSUE TITLE
Everytime i do VV create, mysql db server gives error

### ISSUE THREAD

**Issue by cinghaman** [Varying-Vagrant-Vagrants/VVV#1098]
I have updated vagrant and virtualbox (ubuntu), everytime i do vv create to setup a new site i get this error in the end
 error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
is it something with vagrant or vv?

**Comment by lstanard** [comment]
I'm also seeing this error when running `vagrant up` or `vagrant halt`.

**Comment by cinghaman** [comment]
@lstanard i manually updated my provision.sh file and added mysql latest server 5.6 instead of Maria DB and other thing i did was which i think also was a culprit was i close my laptop (sleep mode) and i think it was somehow corrupting the vagrant so now when i ever i am closing i vagrant halt, havn't faced a problem, yes had to re do the setup but it works now.

**Comment by cfoellmann** [comment]
Had issues with always going to sleep mode in the past, too.

**Comment by cinghaman** [comment]
Yup so made a habit now not to do put on sleep without halting
