### ISSUE TITLE
develop_git no longer works

### ISSUE THREAD

**Issue by sirbrillig** [Varying-Vagrant-Vagrants/VVV#1099]
## Expected Behavior
```
vagrant ssh
# then, on the remote machine
~/bin/develop_git
```
Running the `develop_git` script should convert the `wordpress-develop` directory to a git clone of WordPress rather than the svn repo.

## Current Behavior
The script exits saying, "Repo has already been converted to Git", when it actually has not.

## Possible Solution
[The script](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/develop_git) needs an update. Changing instances of `/srv/www/wordpress-develop` to `/srv/www/wordpress-develop/public_html` seems to fix it.

**Comment by jeremyfelt** [comment]
Good catch, @sirbrillig, thanks for opening an issue. It may be the case too that we should move the definition for this function to the [vvv-wordpress-develop repository](https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop) because it is so specific.

**Comment by JJJ** [comment]
Just ran into this myself.

A consequence of this is that the `.gitignore` doesn't apply to the Subversion repository, and IDE's (like Netbeans/PHPStorm, specifically) have issues displaying changes of Git repositories inside of Subversion repositories (in my case, plugin & theme development.)

I'd be fine with this just checking the correct path for now (to fix the bug) and doing what @jeremyfelt suggests later.

**Comment by LoreleiAurora** [comment]
#1119 && Varying-Vagrant-Vagrants/vvv-wordpress-develop#2 move the `develop_git` script to the WordPress develop site repository and symlink it into place, allowing the site to be moved in `vvv-config.yml` without breakage.

**Comment by joemcgill** [comment]
Just ran into this as well and the two changes from @LoreleiAurora above are working for me. It may be nice to move the `.svn-backup` folder up a level, outside the `public_html` dir or alternately add it to the `.gitignore` file.
