### ISSUE TITLE
Allow WP_CORE_DIR to be overridden

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#1100]
Currently, there is no way to configure `phpunit` to use a directory other than `/srv/www/wordpress-develop/` for running tests. There could be scenarios I may want to run tests with a version of WordPress other than trunk, especially when/if #992 and #847 get merged.

This is currently set in [`bash_profile`](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/bash_profile#L33).

It would be nice if this could be overridden in a custom configuration file for specific sites.

Talked this over with @jeremyfelt privately in case I was missing something. He had the following suggestions: 
```I *think* you could overwrite that with a custom `config/bash_aliases` file that is copied over during provisioning. Otherwise, you may need a script that sets the environment var manually```

I tried that on an already provisioned checkout, and tried it before provisioning an instance for the first time, but couldn't get it to work.

**Comment by LoreleiAurora** [comment]
I think we should allow it to be overwritten from vvv-config.yml

**Comment by jeremyfelt** [comment]
> I think we should allow it to be overwritten from vvv-config.yml

That would be cool. I wonder if it would make sense to allow arbitrary environment variables to be set this way.
