### ISSUE TITLE
'vv create' triggers provisioning, then: 'Stderr: VBoxManage.exe: error: Code E_FAIL (0x80004005)'

### ISSUE THREAD

**Issue by ryanfurtner** [Varying-Vagrant-Vagrants/VVV#1102]
## Expected Behavior

Create new sites with 'vv create' and have things work like normal afterwards.

## Current Behavior

After creating a new site with vv create, it runs 'vagrant up --provision'. After provisioning, it says the new site is successfully created. When I try to run vagrant up after doing this, I get: 
`C:\vvv-dev>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "336d27ef-272e-45e1-a593-7c0adde21e56", "--natpf1", "delete", "ssh"]

Stderr: VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 507 of file VBoxManageModifyVM.cpp`

I created a snapshot before trying to create the new site incase something like this happened, but I cannot restore from it. I get this error in VirtualBox: `Callee RC: E_FAIL (0x80004005)`

This is actually the second time this has happened to me. It happened the other day when I created a new site. I figured it must have been because I hadnt updated/provisioned everything in ages. So, I downloaded the latest 'vvv', updated virtualbox, updated vagrant and started again from scratch. The first site I created worked just fine. This second site I tried broke everything. 

## Steps to Reproduce (for bugs)

1. Run 'vv create'
2. After it is done provisioning, try running 'vagrant up', hit error.

Full log here:
https://gist.github.com/ryanfurtner/6b37d4a6d5f16b5b9677a7b5e340723a

## Context

I am a front end web dev who really really wants this set up to finally be the end to my search for a professional wordpress dev environment! I was adding a new site for a new client.

## Your Environment

* VVV version: 1.4.1
* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: Version 5.1.14 r112924 (Qt5.6.2)
* Operating System and version: Win10

**Comment by rafaelwinter** [comment]
I had this problem once, solved it by running the command in a shell with administrative priviledges: right click on Windows and choose Command Prompt (admin).

**Comment by ryanfurtner** [comment]
...Flipping hell, that worked. Thanks so much @rafaelwinter !
