### ISSUE TITLE
Changes to auto site setup?

### ISSUE THREAD

**Issue by ashmatadeen** [Varying-Vagrant-Vagrants/VVV#1103]
Adding the following files to a folder within www  
vvv-hosts
vvv-init.sh
vvv-nginx.conf
as detailed in the [wiki](https://github.com/varying-vagrant-vagrants/vvv/wiki/Auto-site-Setup) is no longer working for setting up a custom site with the latest version of VVV. The url specified in vvv-hosts does get added to /etc/hosts with the correct IP but visiting the URL just loads the page at vvv.dev

Has the auto site set up process changed?

## Environment
* VVV version: 
commit 5b4ee4b71bdb2fe633bb785009e1fc789db493a9
Merge: 78f8a33 e95c85a
Author: Jeremy Felt <jeremy.felt@gmail.com>
Date:   Mon Feb 6 11:54:20 2017 -0800

* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: 5.0.32 r112930
* Operating System and version: macOS 10.12.3

**Comment by LoreleiAurora** [comment]
This is on the develop branch (as yet undocumented), please see #980 for docs on how to use the `vvv-config.yml` file.

**Comment by matthias-chlechowitz** [comment]
thank you for the helping hand @LoreleiAurora :) works like a charm now.
