### ISSUE TITLE
vagrant up dependency installation issues

### ISSUE THREAD

**Issue by lstanard** [Varying-Vagrant-Vagrants/VVV#1104]
I cloned VVV locally into a `~/vagrants/` directory and ran `vagrant up` for the first time. Here's a gist of the full output https://gist.github.com/lstanard/a8f94a4be05d156c7368e05a0fb0f8e1. 

At around line 122 is where it starts to report some dependency problems: 

```
==> default: Failed to open terminal.u.com trusty-backports/multiverse amd64 Packages
==> default: debconf: whiptail output the above errors, giving up!ranslation-en
==> default: dpkg: error processing package libssl1.0.0:amd64 (--configure):lation-en
==> default:  subprocess installed post-installation script returned error exit status 255
==> default: dpkg: dependency problems prevent configuration of libaprutil1:amd64:n
==> default:  libaprutil1:amd64 depends on libssl1.0.0 (>= 1.0.0); however:
==> default:   Package libssl1.0.0:amd64 is not configured yet.
```

Vagrant then fails to start due to various missing services/dependencies. This happens when running `vagrant provision` or `vagrant up --provision`. 

When I try to simply run `vagrant up` I get the following output: 

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I've tried halting the box and restarting, and also completely removing the `~/vagrants/` directory, cloning the repo again but get the same results. 

## Your Environment
* VVV version: 1.4.1
* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: 
* Operating System and version: OS X 10.11.6

**Comment by cfoellmann** [comment]
This looks like there was a connection or uptime issue with the repo for the Linux packages.
Might be intermittent. Trying later might help.

**Comment by lstanard** [comment]
I was encountering this issue last night and again this morning, but I think you're correct. Just tried again and it downloaded all dependencies. Thanks!
