### ISSUE TITLE
MariaDB Provisioning Failure

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1105]
## Expected Behavior

`vagrant up --provision` should provision the box

## Current Behavior

An issue occurs that prevents apt-get from running, failing provisioning, e.g.:

```
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.13.0-105-generic is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-5.5 (>= 5.5.53-1ubuntu0.14.04.1) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
/home/vagrant/.bash_profile: line 39: /srv/config/wp-cli/wp-completion.bash: No such file or directory

==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vip.localhost
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 wphooked.localhost
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.13.0-105-generic is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-5.5 (>= 5.5.53-1ubuntu0.14.04.1) but it is not going to be installed


Stderr from the command:

E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

SSH'ing into the box reveals:

```
Last login: Wed Jan  4 01:39:29 2017 from 10.0.2.2
-bash: /srv/config/wp-cli/wp-completion.bash: No such file or directory
vagrant@vvv:~$ sudo apt-get upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-5.5 (>= 5.5.53-1ubuntu0.14.04.1) but it is not installed
N: Ignoring 'vvv-sources.list' in directory '/etc/apt/sources.list.d/' as it is not a regular file
N: Ignoring 'vvv-sources.list' in directory '/etc/apt/sources.list.d/' as it is not a regular file
E: Unmet dependencies. Try using -f.
vagrant@vvv:~$ sudo apt-get -f install 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  libmariadbclient18 mariadb-client-5.5 mariadb-client-core-5.5
  mariadb-server-5.5 mariadb-server-core-5.5
Suggested packages:
  mailx mariadb-test tinyca
The following NEW packages will be installed:
  mariadb-server-5.5
The following packages will be upgraded:
  libmariadbclient18 mariadb-client-5.5 mariadb-client-core-5.5
  mariadb-server-core-5.5
4 upgraded, 1 newly installed, 0 to remove and 44 not upgraded.
10 not fully installed or removed.
Need to get 10.0 MB of archives.
After this operation, 68.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^Cvagrant@vvv:~$ y
WARNING:root:could not open file '/etc/apt/sources.list.d/vvv-sources.list'

y: command not found
vagrant@vvv:~$ 
```

## Steps to Reproduce (for bugs)

1. Pull down the latest VVV `develop` branch
2. Provision sites

## Context

I was trying to demonstrate something that previously worked but is now broken

## Your Environment

* VVV version: `develop` `5b4ee4b71bdb2fe633bb785009e1fc789db493a9`
* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: 5.0.32
* Operating System and version: macOS v10.12.3

**Comment by cinghaman** [comment]
I have been having same issue, with i try to create a new site using vv create and vagrant does vagrant --provision it fails at the DB and i also get same error The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
Even though it creates a folder but never creates an htdocs folder i have to then manually go to vagrant ssh /vagrant/www/site.dev and run ./vvv-init.sh 
and then i have to manually setup database for the site.

**Comment by jeremyfelt** [comment]
@tomjn - I just tried to reproduce this unsuccessfully on a new `vagrant up` and an existing `vagrant up --provision`. The portion I'm most confused by is this:

```
dkms is already the newest version.
linux-headers-3.13.0-105-generic is already the newest version.
```

I don't think we update these as part of provisioning, so it may be that something else (vbguest plugin?) is injecting this part. I'm not sure how that would cause any issues with the MariaDB install though. It's very strange that mariadb-server is failing on a dependency of what appears to be itself.

Can you paste the output of `vagrant box list` and `vagrant plugin list` so that I can try to match the setup a bit more?

@cinghaman It's possible that this is more related to the `vv create` command. Do you get the same `mariadb-server` error?

**Comment by LoreleiAurora** [comment]
This caught me upgrading my own and @jtsternberg's installs, still cant figure out how to reproduce it though.

**Comment by tomjn** [comment]
I've not encountered this in a long time, @LoreleiAurora shall we close this one out?

**Comment by cinghaman** [comment]
@jeremyfelt it happens when I do either vv create or run provision command, once I do that my setup changes to mariaDB and I have to manually go to vagrant ssh and re-install mySQL.

**Comment by cinghaman** [comment]
on my provision this the error i get 
==> default: ERROR
==> default:  2002 (HY000)
==> default: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by cinghaman** [comment]
vagrant box list
bento/ubuntu-16.04  (virtualbox, 2.3.5)
hashicorp/precise64 (virtualbox, 1.1.0)
ubuntu/trusty64     (virtualbox, 20161207.0.0)
ubuntu/trusty64     (virtualbox, 20170112.0.0)
ubuntu/trusty64     (virtualbox, 20170123.0.0)
ubuntu/trusty64     (virtualbox, 20170220.0.1)
ubuntu/trusty64     (virtualbox, 20170222.0.0)

vagrant plugin list
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.7, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.13.0)

**Comment by cfoellmann** [comment]
Your vagrant-vbguest is not the newest.
Maybe try there?

**Comment by tomjn** [comment]
> vv create

VV is unsupported, and can cause lots of problems, I **strongly** advise against using it. You can do everything `vv` does by modifying `vvv-custom.yml`

**Comment by cinghaman** [comment]
@tomjn thanks, can you recommend the utility?

**Comment by tomjn** [comment]
It doesn't exist at the moment, you'd have to create it, here are the docs on how VVV Utilities work:

https://varyingvagrantvagrants.org/docs/en-US/utilities/

It's how PHPMyAdmin etc get installed, and how optional system wide stuff should be configured and installed.

I'm going to close this out as it's non-standard stuff for now
