### ISSUE TITLE
All of sudden it's impossible to run vagrant up

### ISSUE THREAD

**Issue by uitta** [Varying-Vagrant-Vagrants/VVV#1106]
i'm trying to make vagrant work on os x. The first time everything worked and i was able to see local.wordpress.dev
Beeing my first time with vvv i tried to replicate again every passage to fully understand what i was doing and trying to learn better. Delete everything and started again.
This time, when i try to vagrant up i receive the follow error and, even if i tried to search the same problem, i am not able to find a solution.

==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/vitta/Desktop/wordpress-vvv
    default: /srv/www => /Users/vitta/Desktop/wordpress-vvv/www
    default: /srv/log => /Users/vitta/Desktop/wordpress-vvv/log
    default: /srv/config => /Users/vitta/Desktop/wordpress-vvv/config
    default: /srv/database => /Users/vitta/Desktop/wordpress-vvv/database
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: default (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-x0s237.sh
==> default: Network connection not detected. Unable to reach google.com...
==> default: No network connection available, skipping package installation
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-1092grj.sh
==> default: Downloading core resources, see https://github.com/Varying-Vagrant-Vagrants/vvv-utilities.git
==> default: /tmp/vagrant-shell: line 11: git: command not found
==> default: /tmp/vagrant-shell: line 12: cd: /vagrant/provision/resources/core: No such file or directory
==> default: /tmp/vagrant-shell: line 13: git: command not found
==> default: Running provisioner: utility-core-memcached-admin (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-bf6oww.sh
==> default: Running provisioner: utility-core-opcache-status (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-19b2veh.sh
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-96xhdh.sh
==> default: Running provisioner: utility-core-webgrind (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-1h0ulcg.sh
==> default: Running provisioner: site-wordpress-default (shell)...
    default: Running: /var/folders/gc/6h8kl45x7sb7fmnnmjrw6nlh0000gn/T/vagrant-shell20170216-3654-q9riy7.sh
==> default: Downloading wordpress-default, see https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
==> default: /tmp/vagrant-shell: line 37: git: command not found
==> default: find: 
==> default: `/srv/www/wordpress-default'
==> default: : No such file or directory
==> default: nginx: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

what am i missing?

**Comment by LoreleiAurora** [comment]
Vagrant cannot connect to the internet therefore the provisioner has not been run

**Comment by uitta** [comment]
mhh... i thought about it and tried to disabled my firewall but still no luck. I am connected...

**Comment by LoreleiAurora** [comment]
well in your log it says 
```
==> default: Network connection not detected. Unable to reach google.com...
==> default: No network connection available, skipping package installation
```

**Comment by uitta** [comment]
you are right... it says so and it was one of my first concern... but still i am connected and i cannot figure out what or where the problem is...

**Comment by LoreleiAurora** [comment]
what country are you in?

**Comment by uitta** [comment]
italy

**Comment by LoreleiAurora** [comment]
So its not a region block
What version of vagrant/virtualbox are you using?

**Comment by uitta** [comment]
vagrant 1.9.1 / virtualbox 5.1.14

**Comment by LoreleiAurora** [comment]
Hmm, im really not sure on this one
can you ping google.com from inside the VM?

**Comment by uitta** [comment]
ping:unknown host google.com

so no

**Comment by tomjn** [comment]
Hey @uitta I notice your virtualbox version is 5.1 which is out of date, and your guest additions are for v4.3 of Virtualbox which is mismatched. This is likely causing problems for you and it would be good to eliminate that as a source of problems.

I updated my software earlier today so the latest versions at the time of writing are:

Vagrant: 1.9.1
Virtualbox: 5.1.4

Make sure your VVV instance is powered off and update the software to at least those versions

Then, open up Virtualbox and check for guest additions updates ( and check https://www.virtualbox.org/wiki/Downloads for the VMBox extension pack )


Finally, ensure that the box it's being built on top of is up to date:

```
vagrant destroy
vagrant box update
vagrant up
```

**Comment by uitta** [comment]
Thanks for you suggestion...
how is it that on virtualbox download page ther's only the 5.1.14?
I've searched and found the 5.1.4 (when i open it says ther's a new version.... the 5.1.14) but it's impossible to install the extension pack, it gaves me error, due not beeing the last version....
I've tried building ex novo a new box but it gives me the same error again.

**Comment by uitta** [comment]
i was able to connect a box to internet, changing manually the connection type from nat to bridge-airport.
But when i run vagrant up it change back it to nat.
Beeing completly new.... is it possible to specify wich type of connection use in the vagrant configuration file?

**Comment by tomjn** [comment]
@uitta did you do all or as many of the steps I suggested? And you have the latest versions of Vagrant and Virtualbox?

How do you have your local network set up? I have a standard wifi connection to an access point here, and I encounter none of these issues

**Comment by tomjn** [comment]
Can you confirm with the output of `vagrant --version` and `vboxwebsrv --version` so that there's no confusion

**Comment by tomjn** [comment]
Also, the output of `vagrant plugin list` would be helpful

**Comment by uitta** [comment]
i've tried as you suggested me. The only problem is that is impossible to install the extension pack.
Right now my configuration is
Vagrant 1.9.1
vagrant-bindfs (1.0.3)
vagrant-hostmanager (1.8.5)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.6, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.13.0)
Oracle VM VirtualBox web service Version 5.1.4
(C) 2007-2016 Oracle Corporation
All rights reserved.
5.1.4r110228

i've deleted every box already installed. I've tried removing comment to  config.vm.network "public_network" but still no luck. Any suggestion before i try again?

**Comment by uitta** [comment]
Like you i'm connected with my wifi on mac os 10.11.6

**Comment by tomjn** [comment]
I'm on macOS 10.12.3, the extension pack should be a drag and drop in to VirtualBox, i can only advise that you read the relevant support information on VBox for appropriate installations and the relevant versions

**Comment by uitta** [comment]
you're wright i downloaded the worng version, even if it says now i got and old one...

**Comment by uitta** [comment]
well.... i managed to make it work but still i cannot understand the reason.
As @LoreleiAurora suggested the problem was the connection. I tried replicate the first time i successful make it work. So i disabled my wi-fi, connected my phone via usb and tried.... and now it's working. So the problem is, why it didn't detect my wifi in the first place?

**Comment by LoreleiAurora** [comment]
This is a Vagrant or VirtualBox issue not a VVV issue, as all we do is ping google.

**Comment by uitta** [comment]
you're right. thanks.
