### ISSUE TITLE
My devsites are not listed in ssh vagrant directory

### ISSUE THREAD

**Issue by cmackler** [Varying-Vagrant-Vagrants/VVV#1111]
Hello,

I installed VVV v1.3 and when I ssh into my vagrant box none of my sites are there. I use VV to create my new sites but the default ones that VVV creates are not there.

Is that normal? Or do I have a configuration error somewhere. Please help.

**Comment by LoreleiAurora** [comment]
The issue template is there to help us help you, you should fill it in not delete it.

Can you please post the output of a full vagrant provision in a gist and link it here.
Also answer the following.
## Your Environment

* VVV version:
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by cmackler** [comment]
Here is the gist:
https://gist.github.com/cmackler/553dda69db530955ed949ac02c01506c

Expected Behavior
SSH into vagrant should show installed Wordpress directories. In other words, it should mirror my project directory.
Current Behavior
SSH into vagrant and it just lists:

vagrant@vvv:~$ ls
bin
vagrant@vvv:~$ cd bin
vagrant@vvv:~/bin$ ls
db_backup    makepot          vagrant_halt     vagrant_up  xdebug_on
develop_git  vagrant_destroy  vagrant_suspend  xdebug_off

Steps to Reproduce (for bugs)
??
Context

Your Environment


VVV version: 1.3.0
Vagrant version: 1.9.1
VM Provider name: Virtualbox
VM Provider version: 5.0.32r112930
Operating System and version: Mac OS Sierra 10.12.3

**Comment by LoreleiAurora** [comment]
Ok, looking at your log there is absolutely nothing wrong here, after typing `vagrant ssh` you need to cd to `/srv/www`

**Comment by cmackler** [comment]
Ok, I see it know. Thank you so much for your help. I feel like such a noob!
