### ISSUE TITLE
Updating Provision.sh to show Latest MySql server 5.6

### ISSUE THREAD

**Issue by cinghaman** [Varying-Vagrant-Vagrants/VVV#1113]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version:
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by jeremyfelt** [comment]
Hi @cinghaman, can you provide some more detail for this issue? Note that we have switched from MySQL to MariaDB for the upcoming VVV 2.0.0 release.

**Comment by cinghaman** [comment]
Yes, i had updated MySQL 5.6 on my vagrant ubuntu box, I updated provision.sh to reflect the same, but every time i do vv to create a new WP install, somehow MySQL gets corrupted and uninstalls everything and goes back to MariaDB 5.5.
This is the starting point of errors 
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
default: Failed to open terminal.debconf: whiptail output the above errors, giving up!
efault: dpkg: error processing archive /var/cache/apt/archives/mariadb-server-5.5_5.5.54-1ubuntu0.14.04.1_amd64.deb (--unpack):
default:  subprocess new pre-installation script returned error exit status 255
==> default: Errors were encountered while processing:
==> default:  /var/cache/apt/archives/mariadb-server-5.5_5.5.54-1ubuntu0.14.04.1_amd64.deb
==> default: E
==> default: :
==> default: Sub-process /usr/bin/dpkg returned an error code (1)
And it starts to remove MySQL and install MariaDB
and by the end of provisioning 
mysql fails to start 
and shows error 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

I am on Macbook OS serra, Installed Version: 1.9.2 of vagrant, ubuntu/trusty64 (virtualbox, 20170222.0.0), 
VBoxManage --version (5.1.14r112924)

**Comment by LoreleiAurora** [comment]
vv re-runs the full provisioning script on `vv create`, had you modified the provision.sh file or just installed MySQL manually?

**Comment by cinghaman** [comment]
Updated provision.sh and added MySQL server 5.6 in place of MariaDB

**Comment by jeremyfelt** [comment]
As long as all references to MariaDB have been removed from `provision.sh` and any other additional provisioners, then I don't see any reason why it would be reinstalled automatically. If this is still happening, can you paste a [gist](https://gist.github.com) containing the entire output of `vagrant provision` or `vv create`?

**Comment by cinghaman** [comment]
@jeremyfelt is there any other file other than provision.sh where it mentions or looks for mariaDB?

**Comment by jeremyfelt** [comment]
Ahh, one other place actually! In the [apt sources list](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/apt-source-append.list), the repo for MariaDB is added. I believe since it's a MySQL drop-in replacement, it may alias an attempt to install MySQL as MariaDB instead.

**Comment by cinghaman** [comment]
Thanks will check and see if it will fix, cheers for looking into it
