### ISSUE TITLE
Make it easier to provision a new site

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#1125]
The new provision improvements in version 2 make it mush easier to provision and configure new sites. You can define a new site with one line.
`new-site:`

This is great, but because there are no provisioning instructions, only the site folders are created. It would be great to have generic repositories that could be re-used for sites that do not need any custom configurations.

## Possible Solution
I have created two repository forks that will provision a generic site. I envision these living under the Varying-Vagrant-Vagrants account. One provisions a site using the latest stable version of WordPress, and the other using trunk. The site name listed in the `vvv-custom.yml` file is used as the folder name and URL.

1. [Latest Release Provisioning](https://github.com/desrosj/vvv-wordpress-default)
1. [Trunk Provisioning](https://github.com/desrosj/vvv-wordpress-trunk)

I think by default, the minimal configuration mentioned above could just use the latest release repo, ensuring a site is created when added to the `vvv-custom.yml` file.

Other ideas expanding on this:
- Add parameters to the `vvv-custom.yml` file for:
    - The domain to use as the site's URL. Will allow the site folder to use one name and the URL to use another. My repo currently uses the sitename.dev.
    - Which version of WordPress to use, ie. trunk or latest.

There is one issue in both of my forks. I am unsure of the proper syntax in `vvv-nginx.conf` for using the environment variable for `vvv_site_name`.

**Comment by LoreleiAurora** [comment]
@desrosj I'm actually working on something like this at the moment. Your feedback/testing would be greatly appreciated.
https://github.com/Varying-Vagrant-Vagrants/custom-site-template

**Comment by desrosj** [comment]
@LoreleiAurora Yes! Perfect. I love that it has multisite as well (which I forgot to mention in my issue).

I will check this out. I can report my testing results here, or close this out and open separate issues if anything come sup.
