### ISSUE TITLE
Demoing v2 at meetup - not working

### ISSUE THREAD

**Issue by mkjonesuk** [Varying-Vagrant-Vagrants/VVV#1126]
Hey all, sorry to be a pain, I'm looking to demo v2 at our meetup next week - I did a fresh pull and install from the develop branch and I still have the same issue I had back in November (see #1034).

I get that v2 will use vvv-config.yml to manage local sites - but it doesn't seem to be working. I can get to vvv.dev but not local.wordpress.dev/etc and there doesn't seem to be any databases setup.

Aware this is all still WIP and likely there's some 'magic' missing but I wondered if there was any way I could throw in a workaround, perhaps some missing perimeters in vvv-config.yml to get the sites to run?

**Comment by LoreleiAurora** [comment]
@mkjonesuk v2 is actually pretty stable and has been tested on bds osx ubuntu and windows, and I'm still unable to reproduce what was happening on your machine. Mind if I take another look?

**Comment by mkjonesuk** [comment]
Hey @LoreleiAurora - sure thing, I've actually just managed to get local.wordpress.dev working by updating vvv-config.yml to look like this:

```---
sites:
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    vm_dir: '/srv/www/wordpress-default-provisioner'
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    vm_dir: '/srv/www/wordpress-develop-provisioner'
  wordpress-trunk:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
    vm_dir: '/srv/www/wordpress-trunk-provisioner'

  #wordpress-trunk: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
  #multisite: https://github.com/Varying-Vagrant-Vagrants/vvv-multisite.git
  #wordpress-meta-environment: https://github.com/WordPress/meta-environment.git

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
```

The only thing that doesn't make sense now is why the site is running from the :

`www/wordpress-default-provisioner/public_html`

Folder and not:

'www/wordpress-default'

Which is what I would expect.

**Comment by LoreleiAurora** [comment]
https://hangouts.google.com/call/lpfrhkpvvbhxtidpvl4kdjux5ae

**Comment by mkjonesuk** [comment]
@LoreleiAurora heh, can't do a hangouts at 3am sorry! Maybe next time. 

Feel free to drop me a Twitter DM / email and we'll book something in for a more sane time of day 👍

**Comment by LoreleiAurora** [comment]
Ok, what's the output of git `rev-parse HEAD` and `ls www` (from the vvv dir)

**Comment by jeremyfelt** [comment]
Any progress on this @mkjonesuk?

**Comment by mkjonesuk** [comment]
Yep @jeremyfelt I got some help from @LoreleiAurora after I made a video showing the issue of site generation, just needed to understand how this new .yml config works.

The demo was last night, although the meetup was a bit of a bust and none of the students who it was aimed at showed up so I didn't do the full demo - the audience was too green!
