### ISSUE TITLE
VirtualBoxGuestAdditions requirement

### ISSUE THREAD

**Issue by apidevlab** [Varying-Vagrant-Vagrants/VVV#1143]
## Expected Behavior

A small explanation and link to the Virtualbox docs page ... 

## Current Behavior

The current installdocs don't mention the Guest Additions requirement at all, you only get advised about it after performing the initial `vagrant up`

## Possible Solution

"The VirtualBox Guest Additions for all supported guest operating systems are provided as a single CD-ROM image file which is called `VBoxGuestAdditions.iso`. This image file is located in the installation directory of VirtualBox. To install the Guest Additions for a particular VM, you mount this ISO file in your VM as a virtual CD-ROM and install from there." 

The official docs for this are available at: [Installing and Maintaining Guest Additions](https://www.virtualbox.org/manual/ch04.html)

## Steps to Reproduce (for bugs)

N/A

## Context

The context was in the OOBE (Out of the Box Experience) it was a showstopper
## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.92
* VM Provider name: VirtualBox
* VM Provider version: Latest
* Operating System and version: Win 7 x64

**Comment by jeremyfelt** [comment]
Hi @apidevlab, thanks for opening an issue. I'll admit just recently removing `vagrant-vbguest` as a recommended plugin because I've never used it myself. I've been suspicious in the past that more issues are caused updating the guest additions, but I have no real proof. :) Happy to reconsider adding it back to the installation guide.

Is something broken after `vagrant up`, or is it just the message that appears?

**Comment by LoreleiAurora** [comment]
If guest additions get too far out of sync with VirtualBox it will cause issues. If you use the plugin you need to keep VirtualBox up to date.

**Comment by jeremyfelt** [comment]
That makes sense. Is it enough to use `vagrant box update`? I've never actually paid attention to the guest additions version on the box.

**Comment by LoreleiAurora** [comment]
Yes it is, every `box update` uses the latest guest additions

**Comment by apidevlab** [comment]
Hi @jeremyfelt I tried a new install with the new 2.0 as I have had the project sat here on my to try list for a few weeks. 

Essentially all is well until the mount stage I got an error specifice to 'This is not vvv you need to check virtualbox' (or similar) I read up a little on VB Guest Additions and thought it would be worthwhile noting that at install however, all is not as it seems. 

I have still not been able to install and have now resorted to the info on https://varyingvagrantvagrants.org/docs/en-US/troubleshooting which includes advice:

```
# Make sure the recommended vagrant plugins are installed
vagrant plugin install vagrant-triggers vagrant-vbguest vagrant-hostsupdater
```

So to be honest I am not sure my original post was appropriate (in so much as the VB Guest additions is handled via a plugin?) I am currently cleaning up in Virtualbox for a real clean start as other errors are now appearing ;(

**Comment by tomjn** [comment]
@apidevlab is this an issue currently with v2.3 + vagrant 2.1.x + the latest virtualbox?

**Comment by Mte90** [comment]
With the new box we don't need anymore this alert, right @tomjn?

**Comment by tomjn** [comment]
I don't believe that's a VVV message, that's a Vagrant message. Nothing to do with us.

Since this doesn't usually happen, and isn't an issue with current users, I'm inclined to close this out. Vagrant and VB have had major versions released since, if it becomes a problem again we can open a new issue
