### ISSUE TITLE
Can't install wordmove gem in fresh vvv (ruby folder permission denied)

### ISSUE THREAD

**Issue by lindsaymarkward** [Varying-Vagrant-Vagrants/VVV#1146]
Thanks :)

## Expected Behavior
    gem install wordmove
should install wordmove ruby gem

## Current Behavior
    gem install wordmove
produces the error:

    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /usr/local/rvm/gems/ruby-2.4.0 directory.

## Possible Solution
The default user is not a member of the rvm group. The solution described at http://stackoverflow.com/questions/26242712/installing-rvm-getting-error-there-was-an-error23 works for me:

    rvm group add rvm "$USER"
Could this be part of the initial VVV setup?

## Steps to Reproduce (for bugs)
    vagrant ssh
    gem install wordmove

## Context
wordmove is a very useful gem for pushing and pulling WordPress installations. I imagine many VVV users want to be able to use it, and based on blog posts, many people are (trying to) use VVV and wordmove together. I had no such problems with it in an earlier version of VVV (prior to ruby 2.4 perhaps).

## Your Environment
* VVV version: 2.0.0 (current)
* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: 5.1.16
* Operating System and version: Mac OS 10.12.3

**Comment by pento** [comment]
I just ran into the same problem trying to install the `travis` gem.

**Comment by tomjn** [comment]
@LoreleiAurora is this caused by the provisioner running as root?

**Comment by kstefanini** [comment]
Same problem here.
A simple `sudo chmod 777 -R /usr/local/rvm` do the trick. But OP fix looks proper.

**Comment by tomjn** [comment]
I would note that when the initial provisioner runs it runs as root, unlike the user you get on `vagrant ssh`, so `rvm group add rvm "$USER"` will need some adjustment

**Comment by Mte90** [comment]
Right now ruby is not installed anymore with VVV so `gem` and others are required to be installed manually so I don't think that is anymore a bug for VVV.
