### ISSUE TITLE
migration documentation: 404

### ISSUE THREAD

**Issue by hearvox** [Varying-Vagrant-Vagrants/VVV#1151]
In the "VVV 2.0.0" doc:
https://github.com/Varying-Vagrant-Vagrants/VVV/releases/tag/2.0.0

The link-text "migration documentation" goes to this 404:
https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/migrate-vvv-1/

**Comment by LoreleiAurora** [comment]
The link in which file?

**Comment by hearvox** [comment]
The link in what-I-believe-is part of the press release:
https://github.com/Varying-Vagrant-Vagrants/VVV/releases/tag/2.0.0

Look like the URL on the link-text "migration documentation" should be:
https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/

**Comment by LoreleiAurora** [comment]
Good catch, should be fixed now :)
