### ISSUE TITLE
New Release Compatibility Warnings

### ISSUE THREAD

**Issue by topdown** [Varying-Vagrant-Vagrants/VVV#1153]
We need a release warning or something in place when new VVV releases change things that could cause other tools to break.

Since the release of 2.0, I have tickets coming in for my VVV Dashboard because host paths changed on the default installs.

Also, paths most of changed in the documentation for setting up custom sites.

I now have to spend this weekend debugging and fixing this and figure out a way to be backward compatible for those that did not update VVV. 😞 

So there needs to be something setup that lets us know when a release is coming so we can go through or plan to go through it and see what may break in our own tools.
Thanks

**Comment by cfoellmann** [comment]
You should create a "new version" for vvv 2.x.
Maybe a `vvv-2` branch?
Let's have a look at fetching the package via the new config.
This way vvv 1.x users can use your stable version from the known location.

**Comment by LoreleiAurora** [comment]
@topdown There was something setup for months (a github milestone) if you need to know when a release is comeing follow this repo. All repos are tracked here. Most software projects do not inform you when a release is comeing (apart from maybe betas, the develop branch is our version of a beta) and we are no different.

**Comment by jeremyfelt** [comment]
Hi @topdown, thanks for the comment. The VVV project has become a lot more organized in the last few months. I'm hoping this leads to a stronger release process in the future.

As a maintainer of an extension to VVV, I imagine that you follow the progress of the repository closely. At this point that's the best way to stay on top of changes. It may make sense for the next release to spread the word beforehand with a blog post. I also don't expect that we'll make such drastic changes to the underlying code. :)

It's worth noting that site's paths are very dynamic now. They can be [changed in a couple different ways](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-paths-and-folders/) in VVV 2.0.0. The `vm_dir` config specifically can put them pretty much anywhere in the VM.
