### ISSUE TITLE
VVV with new VirtualBox Release

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1154]
When VirtualBox releases a new version, how long does it take for you guys to add the new release of virtualbox to work.

**Comment by LoreleiAurora** [comment]
We do not need to "add support", as long as VirtualBox, Vagrant & the box (`vagrant box update`) are up to date it *should* just work.

(VirtualBox 5.1.8 works right now)

**Comment by jeremyfelt** [comment]
+1 @LoreleiAurora 

Some more context - I don't think we've ever had a VVV specific issue with VagrantBox versions. Vagrant has had a handful, but it's usually something small that Vagrant resolves quickly.
