### ISSUE TITLE
Not creating htdocs

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/VVV#1163]
## Expected Behavior
Create new site should work and create htdocs in folder.

## Current Behavior
Create new site creates hosts record, `.config` file in nginx-config, but does **not** create the `htdocs` directory with the WordPress install. It *does* create the site directory in `www` containing `vvv-init.sh`, `vvv-hosts`, and `wp-cli.yml`, but that's it.

* VVV version: Don't know how to find this but I pulled from `develop` today. Bug happened before pulling and after.
* Vagrant version: 1.9.1
* VM Provider name: Virtualbox
* VM Provider version: 5.0.30 r112061
* Operating System and version: OS X El Capitan - 10.11.6

**Comment by LoreleiAurora** [comment]
Are you using VV by any chance?

**Comment by joelworsham** [comment]
@LoreleiAurora yes I am

**Comment by LoreleiAurora** [comment]
Okay this is a problem because VV is not yet compatible with the latest version of VVV.

You can try using either:
- https://github.com/Varying-Vagrant-Vagrants/custom-site-template
or
- follow there progress fixing this here bradp/vv#348

**Comment by joelworsham** [comment]
Ah yes, thanks for the info
