### ISSUE TITLE
Add Satis to the VM

### ISSUE THREAD

**Issue by jonathan-dejong** [Varying-Vagrant-Vagrants/VVV#1176]
Hi, 

This is not a bug (so I removed the default info). 

I was just wondering wether it'd be possible to extend the new VVV 2.n utilities to also install Satis for private repos in composer?

Or would it just be more complicated than attempting to add authentication to the github account inside VVV?
I read this https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1158 and it seems it's really not straight forward.

**Comment by tomjn** [comment]
You can add your own utility repo in `vvv-custom.yml`, a Utility is just a subfolder in a utility repo with a bash shell script to provision the utility, and any other files it needs

**Comment by tomjn** [comment]
I've had some words, and if you'd like to add Satis to the official utilities repo, PR's are welcome and @LoreleiAurora will maintain it :)

**Comment by tomjn** [comment]
I'm going to close this one as it can come back as a PR in the future
