### ISSUE TITLE
Use mailcatcher in other php versions

### ISSUE THREAD

**Issue by s-ferdie** [Varying-Vagrant-Vagrants/VVV#1181]
## Context
For certain projects I switch to another php version for example 5.6. To test certain functions I rely on the mailcatcher tool. With php version 5.6 mailcatcher is not configured. In `provision.sh` the `mailcatcher.ini` is only copied to `/etc/php/7.0/mods-available/mailcatcher.ini` not to the other php versions 5.5, 5.6 and 7.1.

## Possible Solution
I've enabled mailcatcher in 5.6 with copying these lines and run `vagrant provision`

```
 if [[ -f "/etc/php/5.6/mods-available/mailcatcher.ini" ]]; then
    echo " *" Mailcatcher php56 fpm already configured.
  else
   cp "/srv/config/php-config/mailcatcher.ini" "/etc/php/5.6/mods-available/mailcatcher.ini"
    echo " * Copied /srv/config/php-config/mailcatcher.ini    to /etc/php/5.6/mods-available/mailcatcher.ini"
  fi
```  

Is it the expected behaviour that mailcatcher should only work in 7.0? Is copying these lines for each version a possible solution? Maybe a bash magician should look into it;)

**Comment by LoreleiAurora** [comment]
Can you open a pull request against Varying-Vagrant-Vagrants/vvv-utilities to solve this for both 5.6 and 7.1?

**Comment by s-ferdie** [comment]
Sure, https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/9
