### ISSUE TITLE
Configurable network detection timeout

### ISSUE THREAD

**Issue by wizonesolutions** [Varying-Vagrant-Vagrants/VVV#1183]
## Expected Behavior

It would be good if the timeout for network detection was configurable. I hit a number of problems because it took more than 5 seconds on conference Wi-Fi to wget google.com.

## Current Behavior

The timeout is currently hardcoded to 5 seconds.

## Possible Solution

A configuration option that was interpreted during provisioning would be ideal. The default could be the current value.

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.1
* VM Provider name:  Parallels Desktop
* VM Provider version: 12.1.3
* Operating System and version: macOS 10.12.4

**Comment by tomjn** [comment]
For reference, since this was opened, and tagged, the network check was changed to instead poke the launchpad PPA domain. It now retries 3 times, and has a timeout of 10s
