### ISSUE TITLE
Do not upgrade to VirtualBox 5.1.20 (yet)

### ISSUE THREAD

**Issue by JJJ** [Varying-Vagrant-Vagrants/VVV#1187]
There's an issue with VirtualBox 5.1.20 that causes problems with VB Guest Additions and VVV.

Updating everything doesn't seem help, so my advice is to hold off for now.

5.1.18 appears to still be OK.

**Comment by grappler** [comment]
If you do update and don't want to downgrade here is a easy solution http://stackoverflow.com/a/43497420/3507335

**Comment by thebrandonallen** [comment]
VirtualBox 5.1.22 is out now, and fixes the issue. https://www.virtualbox.org/ticket/16670
