### ISSUE TITLE
Make `vvv-hosts` check optional

### ISSUE THREAD

**Issue by JPry** [Varying-Vagrant-Vagrants/VVV#1190]
When running just about any vagrant command, the `Vagrantfile` is parsed. A number of things happen regardless of the type of command (`up`, `provision`, `ssh`, etc.):

* Decorative VVV2 banner (assuming `VVV_SKIP_LOGO` isn't defined)
* Finding the config file to use
* Scanning for any `vvv-hosts` files
* etc...

Depending on how many sites have been added to Vagrant, scanning for `vvv-hosts` files can take a long time. For my current setup with about a dozen sites (including the defaults), this means waiting about 10 seconds at this point, even for something like `vagrant ssh`.

## Expected Behavior

There should be some manner of making the scan for `vvv-hosts` files optional, especially considering that hosts for each site can now easily be defined in `vvv-custom.yml`.

## Current Behavior

The `Vagrantfile` currently always looks for `vvv-hosts` files in the filesystem.

## Possible Solution

The ideal solution would be to make the check for `vvv-hosts` configurable directly in the `vvv-custom.yml` file.

## Context

This affects most commands that I use regularly, particularly `vagrant ssh`. While a delay during provisioning or `vagrant up` isn't as much of an issue, a delay during `vagrant ssh` is a particular pain point. 

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.8.6
* VM Provider name: VirtualBox
* VM Provider version: 5.1.8
* Operating System and version: Mac OS 10.12.4 (Sierra)

**Comment by tomjn** [comment]
I think this is a good idea, given VVV 2.6 changes that optimised this, `vvv_hosts` isn't searched for in a number of circumstances, so it has less of a benefit, but being able to specify under `general:` in the config that this isn't needed would be good

**Comment by tomjn** [comment]
This isn't that big a performance cost nowadays, if hosts are defined in the config, the search doesn't happen at all. If not, VVV looks for the file in several explicit locations to avoid doing a search
