### ISSUE TITLE
Custom Site Template - Allow "skip" as a value for wp_type

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#1194]
## Expected Behavior

I want to be able to quickly scaffold sites with the custom-site-template repo that aren't WordPress based.

## Current Behavior

Not possible, defaults to single site install

## Possible Solution

Allow wp_type to be set to "skip" or "none" or similar.

## Context

Having the database and the nginx conf etc being automatically setup for me is handy. Sometimes I just need to quickly set up an empty site + db. Right now i'm trying to copy a Magento site down to do some local development. I've had to create all of the site setup files manually because there isn't a way to just say "skip wordpress install".

## Your Environment

* VVV version: 2.0.0

**Comment by JPry** [comment]
@rtpHarry VVV is primarily focused on WordPress. If you want a custom template that doesn't set up WordPress for you, you could easily fork the `custom-site-template` repo and create your own script to do what you need instead. However, it may actually be better to use something other than VVV for non-WordPress sites.

**Comment by rtpHarry** [comment]
I thought somebody might say something along these lines and I was hesitant to suggest it.

However, it would only take an extra if statement to skip over installing WP. The alternatives all seemed like a lot more work. For me, yes it VVV is for WP but its also my primary local dev server. If I have the occasional different requirement I'm not wanting to go out, find and configure an entire ecosystem when 99% of the problem is already solved by VVV. I have scripts in place which backup the exported databases for example, and automatically run vagrant update to keep the underlying box up to date.

In fact I would potentially use a "none" solution even for WordPress development. I use the Duplicator plugin to move live sites around and when I make a new site in VVV I just want the server+db so I can run the duplicator installer and deploy the site into it.

**Comment by tomjn** [comment]
I agree with @JPry and think a new repo with a new name representing a clean slate would be more appropriate. It'd have a minimal vvv-init.sh that creates a DB and a `vvv-nginx.conf` to match, but make no attempt to install things

**Comment by tomjn** [comment]
I've ammended the PR to the custom site template to use the value `none` rather than `skip` and fixed some merge conflicts, waiting on review
