### ISSUE TITLE
Host file don't update after VVV update

### ISSUE THREAD

**Issue by urre** [Varying-Vagrant-Vagrants/VVV#1195]
## Expected Behavior
I have a number custom sites added since before. They usually update the /etc/hosts file with correct entries. 

## Current Behavior
After updating to VVV 2.0 only the standard ones is the hosts fle (vvv.dev, local.wordpress.dev etc). A `vagrant up --provision` doesn't fix it either.

## Steps to Reproduce (for bugs)
First when updating i did this, and this worked fine for updating to the new VVV and updating the Vagrant box.
1. I did a `git pull` in the VVV repo
2. I also did a `vagrant box update` so everything is up to date

## Context
Updating hosts file don't work any longer. I Have a number of sites added using the VV Site wizard since before.

## Your Environment
* VVV version: Varying Vagrant Vagrants 2.0.0
* Vagrant version: 1.9.1
* VM Provider name: Virtual Box
* VM Provider version: 5.0.32
* Operating System and version: macOS Sierra 10.12.4

**Comment by onthisearth** [comment]
Please have a look at the "Migrating 1.x Sites" section here [https://tomjn.com/2017/01/16/whats-new-vvv-2-0/](https://tomjn.com/2017/01/16/whats-new-vvv-2-0/)

**Comment by urre** [comment]
@onthisearth ah, thank you! Missed this.
