### ISSUE TITLE
Network timeout error

### ISSUE THREAD

**Issue by inetbiz** [Varying-Vagrant-Vagrants/VVV#1196]
## Expected Behavior
Expect it to build a VM

## Current Behavior
Network timeout and destroys box

## Steps to Reproduce (for bugs)
https://pastebin.com/MCkWfvre

## Context
See Gist. Cannot get past its ssh login with a timeout error

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22 r114126 (Qt5.6.2)
* Operating System and version: Win7

**Comment by inetbiz** [comment]
It seems the upgrade from `1.9.4` to `1.9.5` got me past the warning. It looped 5 or 6 times on that script section and moved past it.

**Comment by inetbiz** [comment]
Getting somewhere now.
```
F:\myvm\vagrant-local>vagrant up


  __     ___     ___     __  ____
  \ \   / \ \   / \ \   / / |___ \
   \ \ / / \ \ / / \ \ / /    __) |
    \ V /   \ V /   \ V /    / __/
     \_/     \_/     \_/    |_____|

  Varying Vagrant Vagrants 2.0.0

  Docs:       https://varyingvagrantvagrants.org/
  Contribute: https://github.com/varying-vagrant-vagrants/vvv



Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "64ea7a97-f5ed-4cad-8015-4c0d443faf81", "--natpf1", "delete", "ssh"]

Stderr: VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 507 of file VBoxManageModifyVM.cpp
```

**Comment by LoreleiAurora** [comment]
This isn't a Vagrant issue, or a VVV issue, it is Virtualbox trying to set up a host only network adapter. You can probably find a solution in there [forum](https://forums.virtualbox.org/).
