### ISSUE TITLE
Problems bumping php version in non-standard installation

### ISSUE THREAD

**Issue by designlobby** [Varying-Vagrant-Vagrants/VVV#1198]
Hi there,

I have previously been using a modified script to create a "bedrock" WP installation.

Bedrock - https://github.com/roots/bedrock
Script - https://github.com/julykaz/vvv-demo-1-bedrock

I have only just upgraded to VVV 2.0 but everything seems to be working fine. I was installing a plugin via composer and hit an error "This package requires php >=5.6 but your PHP version (5.5.31) does not satisfy that requirement.".

I have followed the documentation to change php with "nginx_upstream: php56" in my vvv-custom.yml file, and run "vagrant reload --provision". I have also tried adding "set $upstream php56;" to my vvv-nginx.conf file but still got the same PHP version error.

Finally, I have been through the troubleshooting docs and to make sure everything is up-to-date. https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/

I can only guess that its something from the original build using https://github.com/julykaz/vvv-demo-1-bedrock that is stopping this from working. Is there a way I can find out what is missing and fix?

Thanks

**Comment by onthisearth** [comment]
I managed the change to PHP 5.6 for one of my projects by adding "set $upstream php56;" in mytestsite.conf in vvv\config\nginx-config\sites and running the mandatory "vagrant reload --provision".

I followed the way with the vvv-custom.yml and vvv-nginx.conf files before, but it did not work. It's a fresh VVV 2.0 install on a new system (Win 10). It was yesterday evening, I want to give it another try tomorrow.

**Comment by LoreleiAurora** [comment]
@designlobby This seems very odd as VVV 2 only supports PHP5.6/7.0/7.1
Did you destroy the box when upgrading to 2.0.0?
If this is on a laptop are you able to attend [MWUG](https://www.meetup.com/ManchesterWordPressUserGroup/events/239333243/) tomorrow so i can take a look?

**Comment by designlobby** [comment]
@onthisearth Thanks, I'll give this a try.

@LoreleiAurora I followed the instructions here: https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/ 

This includes destroying the box. The box was also destroyed again later when I went through the troubleshooting guide. 

This is on my imac I'm afraid, not laptop. I've not been to MWUG before but will take a look, thanks!

**Comment by LoreleiAurora** [comment]
What is the output of `dpkg --list | grep php | awk '/^ii/{ print $2}'`?

**Comment by designlobby** [comment]
-bash: dpkg: command not found

**Comment by designlobby** [comment]
Sorry, I'm not sure what this is!

**Comment by LoreleiAurora** [comment]
Was that in the box?
If it was there is something very wrong here.

**Comment by designlobby** [comment]
No! That was just in terminal - It's been a while since I ssh'ed int vagrant... bear with me I'll try again!

**Comment by designlobby** [comment]
So if I've done his correctly the output is:

dh-php
php-common
php-igbinary
php-imagick
php-memcache
php-memcached
php-msgpack
php-pear
php-ssh2
php-xdebug
php5.6-bcmath
php5.6-cli
php5.6-common
php5.6-curl
php5.6-dev
php5.6-fpm
php5.6-gd
php5.6-imap
php5.6-json
php5.6-mbstring
php5.6-mcrypt
php5.6-mysql
php5.6-opcache
php5.6-readline
php5.6-soap
php5.6-xml
php5.6-zip
php7.0-bcmath
php7.0-cli
php7.0-common
php7.0-curl
php7.0-dev
php7.0-fpm
php7.0-gd
php7.0-imap
php7.0-json
php7.0-mbstring
php7.0-mcrypt
php7.0-mysql
php7.0-opcache
php7.0-readline
php7.0-soap
php7.0-xml
php7.0-zip
pkg-php-tools

**Comment by LoreleiAurora** [comment]
So that output shows there are no PHP5.5 packages installed, so i'm not sure how its being detected. Do you know which package/plugin the error is coming from?

**Comment by designlobby** [comment]
The error happens when I try to install the Soil plugin with composer (https://github.com/roots/soil)

`composer require roots/soil 3.7.0`

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - This package requires php >=5.6 but your PHP version (5.5.31) does not satisfy that requirement.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by nerrad** [comment]
were you running the composer command in the vagrant box or your local machine?

**Comment by designlobby** [comment]
@nerrad On my local machine, as usual. I never ssh into vagrant, apart from just now!

**Comment by nerrad** [comment]
that's why you are getting the error then because on your local machine you don't have the right required version of PHP.  This isn't a vagrant issue.

**Comment by designlobby** [comment]
Yes I think you're right! 
I just ran `php -v` and it showed 5.5.31... Thank you for the help everyone, I'll try again!

Would this also explain my original question about why editing my `vvv-custom.yml` file to upgrade php didn't work?

**Comment by LoreleiAurora** [comment]
Yes `vvv-custom.yml` only affects php version used by nginx
