### ISSUE TITLE
phpcs not available on PATH

### ISSUE THREAD

**Issue by victorlopezg** [Varying-Vagrant-Vagrants/VVV#1199]
## Expected Behavior
After running the initial provisioning `phpcs` should be available on PATH. 

## Current Behavior
Executing `which phpcs` returns an empty response.

## Possible Solution
The provsion script creates links to `/srv/www/phpcs/scripts/phpcs` and `/srv/www/phpcs/scripts/phpcs`, however that directory does not contain the binary files.

Instead, they're in `/srv/www/phpcs/bin/`

<img width="835" alt="screen shot 2017-05-17 at 7 54 00 pm" src="https://cloud.githubusercontent.com/assets/2754872/26183212/9e147614-3b3a-11e7-9294-db112f453848.png">

The corresponding command for linking on provision.sh (`php_codesniff()`) should be updated.

## Steps to Reproduce (for bugs)

1. Provision a new machine (`vagrant up`)
2. `vagrant ssh`
3. `which phpcs`

**Comment by thebrandonallen** [comment]
The problem here is that we're still provisioning with the `master` branch of PHP_CodeSniffer, which contains version 3.0. However, we should actually be on the `2.9` branch, because WordPress Coding Standards sniffs aren't, yet, compatible with PHP_CodeSniffer 3.0 (see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718).

Changing the paths will fix `phpcs` not being available, but it will break the WP sniffs.

This may be a good time to make a move on #1169.

**Comment by TangRufus** [comment]
Any temporary workaround for now?

**Comment by victorlopezg** [comment]
I just tested the fix for #1169 and it also fixes this. Can be closed in my opinion.

@TangRufus as for a workout, manually applying the patch for #1169 and doing a `vagrant reload --provision` should work.

**Comment by TangRufus** [comment]
thanks @victorlopezg 
Using the `develop` branch works

**Comment by tomjn** [comment]
I've updated to the latest `develop` branch and my own `phpcs` is located at `/srv/www/phpcs/scripts/phpcs` not `/srv/www/phpcs/bin/phpcs` as it is in new machines

**Comment by philipjohn** [comment]
Pulling the latest from `develop` resolves this for me too.

**Comment by bjorn2404** [comment]
Looks like it's been a few months since the last comment but pulling from `develop` is not working on my end. `which phpcs` is still returning nothing.

**Comment by tomjn** [comment]
@bjorn2404 does reprovisioning fix that?

**Comment by tomjn** [comment]
This should be fixed in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1200

Switch to the `develop` branch and pull down the latest, and reprovision. If that doesn't work, `vagrant destroy;vagrant up --provision`,
