### ISSUE TITLE
WP Multisite install - Core in a separate folder, using Subdomains, on Nginx- broken links issues

### ISSUE THREAD

**Issue by ilibilibom** [Varying-Vagrant-Vagrants/VVV#1201]
HI
I've been trying for a while to install WP Multisite in its separate folder, and run into many issues with links and rewrites.

My root project look like this:
```
     - wp 
     - wp-content
     index.php 
     wp-config.php
```
The first issue was the the Multisite network link in admin panel would be missing the /wp/ within the URL - For example:
All network admin links in admin where:
wp-admin/network/
instead of being:
wp/wp-admin/network (this link did work when typing it in the browser).
I couldn't find an Nginx rewrite rule solution that would fix this, instead I found a WP filter function workaround that seems to work fine on the main site (was added to functions.php in activated theme).:
```
add_filter( "network_site_url", function( $url, $path, $scheme ){

    $urls_to_fix = array(
        "/wp-admin/network/",
        "/wp-login.php",
        "/wp-activate.php",
        "/wp-signup.php",
    );
    foreach( $urls_to_fix as $maybe_fix_url ) {
        $fixed_wp_url = "/wp" . $maybe_fix_url;
        if ( false !== stripos( $url, $maybe_fix_url )
            && false === stripos( $url, $fixed_wp_url ) ) {
            $url = str_replace( $maybe_fix_url, $fixed_wp_url, $url );
        }
    }
    return $url;
}, 10, 3 );
```
The issue is that on the subdomain site admin this function is not working (although it shares the same theme), all link are calling wp-admin & wp-includes instead of wp/wp-admin & wp/wp-includes

My nginx-wp-common.conf file located in -
/Users/myName/vvv/vagrant-local/config/nginx-config looks like this:

```
# nginx-wp-common.conf
#
# Contains a common configuration for use by nginx on a WordPress
# installation. This file should be included in any WordPress site
# nginx config with the following line:
#
#     include      /etc/nginx/nginx-wp-common.conf;
#
# See local-nginx-example.conf-sample for a full example

location /wp {
        try_files $uri $uri/ /wp/index.php?$args;
}

# Specify a charset
charset utf-8;

# Weird things happened to me when I had gzip on, may need to try
# again in the future as it could have been related to many other
# factors - JF
gzip off;

# Add trailing slash to */wp-admin requests.
rewrite /wp-admin$ $scheme://$host$uri/ permanent;

# this prevents hidden files (beginning with a period) from being served
location ~ /\. {
    access_log off;
    log_not_found off;
    deny all;
}

# Pass uploaded files to wp-includes/ms-files.php.
rewrite /files/$ /index.php last;

if ($uri !~ wp-content/plugins) {
    rewrite /files/(.+)$ /wp-includes/ms-files.php?file=$1 last;
}

# Rewrite multisite in a subdirectory '.../wp-.*' and '.../*.php'.
# Rewrite multisite '.../wp-.*' and '.../*.php'.
if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) /wp$1 last;
    rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ /wp$1 last;
}

location ~ \.php$ {

    # Try the files specified in order. In our case, try the requested URI and if
    # that fails, try (successfully) to pass a 404 error.
    try_files      $uri =404;

    # Include the fastcgi_params defaults provided by nginx
    include        /etc/nginx/fastcgi_params;

    # The amount of time for upstream to wait for a fastcgi process to send data.
    # We keep this *extremely* high so that one can be lazy when remote debugging.
    fastcgi_read_timeout 3600s;

    # Buffer size for reading the header of the backend FastCGI process.
    # This defaults to the value of a single fastcgi_buffers, so does not
    # need to be specified in our case, but it's good to be explicit.
    fastcgi_buffer_size 128k;

    # The number and size of the buffers into which the reply from the FastCGI
    # process in the backend is read.
    #
    # 4 buffers at 128k means that any reply by FastCGI greater than 512k goes
    # to disk and replies under 512k are handled directly in memory.
    fastcgi_buffers 4 128k;

    # SCRIPT_FILENAME is a required parameter for things to work properly,
    # but was missing in the default fastcgi_params on upgrade to nginx 1.4.
    # We define it here to be sure that it exists.
    fastcgi_param   SCRIPT_FILENAME         $document_root$fastcgi_script_name;

    # Use the upstream defined in the upstream variable.
    fastcgi_pass   $upstream;

    # And get to serving the file!
    fastcgi_index  index.php;
}
```
I would really be happy to have an Nginx solution for this issue - instead of a theme function solution that anyway doesn't work in subdomains.
Thanks you so much for helping.

**Comment by LoreleiAurora** [comment]
This is actually not a VVV issue, but here goes.

Lay your project out like this
```
- wp 
- wp-content
wp-config.php
```

Use this nginx config in your site
```
server {
    listen       80;
    listen       443 ssl;
    server_name  DOMAIN HERE;
    root         {vvv_path_to_site}/public_html/wp;

    error_log    {vvv_path_to_site}/log/error.log;
    access_log   {vvv_path_to_site}/log/access.log;
    
    set          $upstream {upstream};

    # Requests to WordPress are made in /wordpress/, which is at the same
    # level as /wp-content/. To properly handle these, we provide an alias
    # to move up a directory and find static files.
    location ~ ^/wp-content/(.*)$ {
        expires 7d;
        alias {vvv_path_to_site}/public_html/wp-content/$1;
    }

    include      /etc/nginx/nginx-wp-common.conf;
}
```

Add this to `wp-config.php`
```
// Load wp-content from parent direc
define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content' );
```
DO NOT DEFINE `WP_CONTENT_URL`

**Comment by ilibilibom** [comment]
Thanks for your replay LoreleiAurora 
I've added your script to the vvv-nginx.conf file I the root of my project. The only change I made was replacing public_html to htdocs - since I have my vvv project configured that way. 
 
The main sites admin is working fine but:

I'm still getting 404 on all links within my network admin panel links, and in all my secondary site dashboard (both are missing missing the /wp/ in the URL)

Any Idea why is this happening ?

**Comment by LoreleiAurora** [comment]
You should not need the WP in the URL with this config

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ilibilibom** [comment]
Well all of my admin has /wp/ in its URL. 
If I remove it I get 404

**Comment by ilibilibom** [comment]
my vvv-nginx.config is in the root of the project along side the htdocs folder  
- vvv-nginx.config
- htdocs

Is this the right  ?

**Comment by ilibilibom** [comment]
Where would be a good place to ask this kind question ?

**Comment by wdiaz** [comment]
Hello Ilibilibom,

I am facing the same EXACT problem.  I was able to resolve the problem when I replicated it on apache but not on vvv/nginx.

Did you find any solution you might want to share?

Best,
Walter

**Comment by wdiaz** [comment]
I found a solution. My root folder was pointing to public_html not to public_html/wp

**Comment by tomjn** [comment]
> my vvv-nginx.config is in the root of the project along side the htdocs folder
> 
> vvv-nginx.config
> htdocs
> Is this the right ?

`vvv-nginx.conf` should be in a `provision` subfolder, refer to the custom site template for a good example

I'm going to close this out, at this point there's nothing VVV specific once you know where the nginx config is, and the contents of `nginx-wp-common.conf` it's all generic Nginx and WordPress config values. Just copy the nginx wp common file and include the copy instead, then make your changes
