### ISSUE TITLE
Hosts not found after creating a new domain/website (wordpress)

### ISSUE THREAD

**Issue by aluxh** [Varying-Vagrant-Vagrants/VVV#1204]
## Expected Behavior
After a new domain/website (wordpress) is created. I'm expected to see vagrant-hostsupdater to find new domain/website entry, however hostsupdater can only find the default sites comes with VVV.

## Current Behavior
Currently, it doesn't allow me to access my new website after creation and provisioning. I can see all the wordpress files in the htdocs, and database in phpmyadmin. However, I can't access it.

And, it happens after I updated VVV, and also deleted my old box and recreated a new ones.

Lastly, at the end of the provisioning, up and close no longer prompt me for password.

## Your Environment
* VVV version: 2.0.0
* Vagrant version: 1.9.1
* VM Provider name: Virtualbox (ubuntu/trusty64)
* VM Provider version: Virtualbox 5.1, Guest Addition version: 4.3.36
* Operating System and version: Ubuntu

Can anyone help me with it? 
I don't know what can I do manually to get my websites work

Provision Log: https://gist.github.com/aluxh/b981caf34005213bd543b04f45b7ad8c

**Comment by ascottmccauley** [comment]
Same issue here.
Upgrading to VVV 2.0 has been the biggest mistake for me.
I used to use bradp/vv/vv to setup sites easily, but now nothing works!
