### ISSUE TITLE
NPM permissions error using custom utilities repo

### ISSUE THREAD

**Issue by davetgreen** [Varying-Vagrant-Vagrants/VVV#1205]
## Expected Behavior
As per advice I received from @LoreleiAurora last week, I've created a utilities repo in order for us to be able to pull a couple of extra dependencies into our workflow.

So I'm expecting this to install `bower` as a globally dependency within the VM.

## Current Behavior
When the provisioner gets to this script, I get the following error:

```
default: Running provisioner: utility-kapow-bower (shell)...
    default: Running: /var/folders/xz/0tj4_7vx3l55z02z0_b0pg940000gp/T/vagrant-shell20170529-23258-h7w5bq.sh
==> default: /tmp/vagrant-shell: line 5: /vagrant/provision/resources/kapow/bower/provision.sh: Permission denied
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Line 5 is of course the NPM install command.

## Steps to Reproduce (for bugs)
Here's an example of one of the `provision.sh` scripts from that repo:
```
#!/usr/bin/env bash
# Install Bower.
if [[ "$(bower --version)" ]]; then
  echo "Bower already installed."
else
  npm install -g bower
  echo "Bower installed!"
fi
```

## Context
I'm currently unable to get additional NPM modules installed whilst provisioning.

## Your Environment
* VVV version: 2.0.0
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22 r115126
* Operating System and version: macOS Sierra 10.12.4 Beta

**Comment by LoreleiAurora** [comment]
The executable permission bit was not set on the script.

**Comment by davetgreen** [comment]
@LoreleiAurora Where exactly do I set the permissions? Do you have an example anywhere I can look at?

**Comment by LoreleiAurora** [comment]
In your utility repo `chmod +x bower/provision.sh`, then commit and push
Then run `vagrant provision`

**Comment by davetgreen** [comment]
@LoreleiAurora So VVV will run a `provision.sh` script in the root of the utilities repo that can then in turn be used to apply those additional permissions? Sorry if I am sounding truly thick here 😄
