### ISSUE TITLE
Question about loading different PHP Versions

### ISSUE THREAD

**Issue by nickyoung87** [Varying-Vagrant-Vagrants/VVV#1206]
I am following this guide: https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/changing-php-version/

I was able to follow this to get PHP 7.1 working. I need to test on PHP 5.2 (WP's minimum requirement). So I add `php52` into the `.yml` file and then run `vagrant reload --provision`. Now when I go to my local site it just gives a 500 server error.

I feel like I am missing some step, like maybe I need to actually install the correct PHP version somewhere before I can switch to it?

Any help would be greatly appreciated.

**Comment by tomjn** [comment]
Packages for unsupported versions of PHP aren't available, so there's no way for the provisioner to install PHP 5.5 and below. You can still get them but you'll need to build the packages yourself, I'm unsure of the specifics.

**Comment by nickyoung87** [comment]
Alright that's unfortunate, but thank you for the info.
