### ISSUE TITLE
Vagrant up causes BOSD

### ISSUE THREAD

**Issue by themaawaa** [Varying-Vagrant-Vagrants/VVV#1208]
## Expected Behavior
Just a normal vagrant up

## Current Behavior
Pc crashes with service exception BOSD

### vagrant code 
```
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "maarten.be"
  config.vm.network "private_network", ip: "172.16.240.81"
  config.vm.network "forwarded_port", guest: 8080, host: 1264
  config.vm.provision "shell", path: "nginx-prov.sh"



end`
```
### Provision shell 
```
#!/usr/bin/env bash

apt-get update
apt-get install -y git
apt-get install -y nodejs
apt-get install -y mongodb
apt-get install -y npm
apt-get install -y w3m
nodejs
npm install --save body-parser
npm install --save nodejs
npm install --save ui-router
npm install --save angularjs
npm install --save express
npm install --save mongodb



git clone https://username:pass@github.com/themaawaa/stackweb

sudo service mongodb start
nodejs stackweb/server.js

sudo w3m localhost:8080

```

## Context
Whenever I am doing Vagrant Up and it gets to it's end cycle it just throws a blue screen. I can't actually see the error because it just instantly crashed my pc

## Your Environment
Vagrant v1.9.5
Windows 10 Pro
Virtualbox "ubuntu/trusty64"

## Tried solutions

1. Reinstalling Vagrant
2. Reinstalling VirtualBox
3. Reinstalling windows
4. Ran a different vagrantfile

**Comment by tomjn** [comment]
You can modify system settings to not reboot when a blue screen of death occurs. Finding out what the error message on the BSOD is super critical, and your problem is impossible to resolve without knowing that.

It may also be possible to find out what it was from logs, but it's a stretch

**Comment by Shawdooow** [comment]
I also have this problem, any information I can provide to help?

-Win 10 64x
-Vagrant 1.9.7

**Comment by tomjn** [comment]
@themaawaa @Shawdooow I'm going to close this out, it doesn't appear to be a VVV install from the information provided. If that's not the case, reopen with the VVV version, a log of `vagrant up --provision --verbose` on a fresh vanilla VVV 2 install, and the stop code from the BSOD ( you can acquire this in Windows once its restarted ). We try to help with VVV support, but we can't help with arbitrary vagrant boxes that don't run VVV, and we can't provide support for custom vagrant files.

**Comment by themaawaa** [comment]
It's most definetly vagrant in combination with Hyper-V. It somehow
corrupts (in my case) vagrant and virtualbox. I had to do a clean install
since vagrant did NOT want to get removed. Not via registry or any other
means

**Comment by tomjn** [comment]
When HyperV is turned on, only Hyper V boxes will work. Virtualbox/VMWare/etc will not function, and there is no workaround other than to turn off HyperV, or petition Microsoft to re-engineer it
