### ISSUE TITLE
New VVV install results in nginx error page.

### ISSUE THREAD

**Issue by Stegosource** [Varying-Vagrant-Vagrants/VVV#1209]
## Expected Behavior
Running a vagrant up command should spin up my machine and going to local.wordpress.dev should show a blank WordPress install.

## Current Behavior
I ran a brand new VVV install (upgraded to V2) with brand new Vagrant and VBox. When I do any vagrant up, I can go to local.wordpress.dev, but it returns the nginx "An error occurred." page.

## Steps to Reproduce (for bugs)
1. Download and install latest version of Vagrant and VirtualBox (Im on Windows)
2. Follow steps to install VVV
3. Also install recommended dependencies.
4. Run vagrant up command
5. Visit local.wordpress.dev
6. OPTIONAL: Experience the feeling of being sad and alone.

## Context
Im on a Windows machine which has had an older version of VVV working on it. I only recently started getting the nginx problems, and it happened on this computer before and after upgrading to VVV2 and it also happens on my home machine from the very first install. Also VVV2.

## Your Environment
* VVV version: 2
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22
* Operating System and version: Windows 10

**Comment by Stegosource** [comment]
So, I found what the problem is. Apparently VVV doesnt work in Opera. I spent so much time trying to figure it out and finally opened the site in Chrome and it all works fine now.

**Comment by LoreleiAurora** [comment]
Do you have opera turbo mode turned on?

**Comment by Stegosource** [comment]
That I do not know. Why? Does that make a difference?

**Comment by LoreleiAurora** [comment]
Yes it does as opera turbo is a proxy server with server-side compression of webpages.

Here's some more info on how it works.
http://help.opera.com/Windows/11.60/en/turbo.html

**Comment by Stegosource** [comment]
Oh ok. Well Ill check that out. Thank you. 

Also, Ill go ahead and close this thread now.

**Comment by Stegosource** [comment]
FYI. I didnt see anything on Opera Turbo, but there is a setting in Opera under Settings -> Browser -> Network -> Use proxy for local servers.

This was on (which may be default). Turning it off fixed it. Thank you @LoreleiAurora for pointing me in the right direction.
