### ISSUE TITLE
Unable to access local sites after first time VVV installed

### ISSUE THREAD

**Issue by georgiac44** [Varying-Vagrant-Vagrants/VVV#1210]
Hi I have just downloaded VirtualBox, vagrant and VVV for the first time and cannot access local sites after vagrant up.

I have been through the process a couple of times, initially i also installed vagrant-hostsupdster but this kept asking me for a password, which after trying 'vagrant' and my mac password numerous times and adding my user to the sudoers file I still could not get past the password.

After removing the plugin vagrant up seemed to run okay, but i cannot access any of the default local sites (local.wordpress.dev etc.)

I feel like i am missing something really obvious but after hours of trying and searching for help i cannot figure out what! Any advice is greatly appreciated :)

**Comment by FrankM1** [comment]
I think what you need to do is add the site addresses and the box ip to the host's /etc/host file. Something like this.

192.168.50.4 local.wordpress.dev
192.168.50.4 src.wordpress-develop.dev
192.168.50.4 build.wordpress-develop.dev

**Comment by tomjn** [comment]
@georgiac44 the password it's asking for is the same password you would use for `sudo`, hosts updater can't write to your hosts file without elevated priviledges.

Without those changes to the hosts file, the domains VVV uses will never work, the browser doesn't know which IP they map on to

**Comment by georgiac44** [comment]
Thanks guys! Got it sortes :)
