### ISSUE TITLE
VVV installer halts if grunt is nor installed

### ISSUE THREAD

**Issue by jnystromdesign** [Varying-Vagrant-Vagrants/VVV#1212]
When starting up vvv for the first time with `vagrant up` it will halt if grunt is not installed. 
After the message 
`==> default: /tmp/vagrant-shell: line 358: grunt: command not found` 
it will output
`==> default: Installing Grunt CLI`
which will go on forever. By installing grunt cli manually this can be avoided. 

## Expected Behavior
Grunt cli should be installed if it's not already installed or it should ask the user to install grunt cli manually.

## Current Behavior
Sais it is installing grunt cli (which it doesn't seem to complete)

## Possible Solution
Install grunt cli manually and run vagrant up again.

**Comment by ktmn** [comment]
Happened to me too. First time stalled at installing Grunt, so I did `VBoxManage controlvm vvv poweroff`
to turn the machine off and ran `vagrant up --provision` again and then it worked.

**Comment by mpmumau** [comment]
Just by way of confirmation, I can vouch that this bug happens with the current, fresh-off-the-repo commit.

**Comment by daveshaw** [comment]
Seeing this as well, but in my case manually installing grunt-cli doesn't fix the problem.  I'm stuck.

**Comment by mklasen** [comment]
Running `vagrant halt` and `vagrant up --provision` after running into this issue fixes the problem.

**Comment by mpmumau** [comment]
@mklasen Not for me; I tried that and many other things after much Googling, to no avail.

**Comment by LC43** [comment]
did the same as @mklasen and on the second run it completed provision. only catchmail seems to have failed, but its not critical.

**Comment by kraftner** [comment]
So I *thought* I've hit that issue as well but as it turned out it just took *forever* until the provision continued. I still don't know why that is, but just as a hint for others that this *maybe* is fixable by patience™.

**Comment by jonathan-dejong** [comment]
I noticed my mailcatcher stopped working as well. So I did a vagrant destroy and on up this now also occurs for me. And even when successful after a loooong time mailcatcher does not work :/

**Comment by kraftner** [comment]
@jonathan-dejong I think the mailcatcher thing could be another issue  - see #1235

**Comment by jonathan-dejong** [comment]
@kraftner thank you! Was looking for something like that but couldn't find anything (my googlefu was not strong enough). The fix in that thread did solve my issue (with mailcatcher).

**Comment by jerturowetz** [comment]
I can report same issue, I'm hanging on exactly the same line on a a fresh Windows 10 install (Oracle VirtualBox 5.1.24, Vagrant 1.97, VVV 2.0.0). I'm guessing no one's figured out a temporary work around?

**Comment by spuddick** [comment]
I can vouch as well that it was just a very long wait. I found this thread by searching for issues related to hanging on "Installing Grunt CLI". As I was reading, I saw movement in my command line window. It was about a 15 - 30 min wait for me too.

**Comment by nylen** [comment]
#1246 should fix this.

> Still seems like something fishy is going on

Confirmed.  The fishiness is a Node.js post-install script failing to download a binary, then `node-gyp` going into an infinite loop until it uses all available memory.  Towards the end of this process you'll get a memory-related error if you attempt to `vagrant ssh`.

**Comment by cj-andrew** [comment]
I can confirm that this was a really long wait for me as well, using VVV2.  

`vagrant up` seemed to stall at `Installing Grunt CLI..`. After waiting for about 25-30 minutes, it moved through and completed successfully on its own. In the recent past, I had exited with a Ctrl-Break, and tried a `vagrant up --provision`. That helped move past the stall. 

This time round, however, I just waited and it eventually completed.

@nylen makes an interesting observation about the Node.js post-install script failing at some point in the process.

**Comment by devanonyme** [comment]
For the record, I wont open a new bug for this.

Had the same problem using latest master ( Oct 12, 2017) on two different install (at home and work) and other undecipherable errors (The SSH command responded with a non-zero exit status. ).

I had to rerun provision multiple times to get it to pass.
