### ISSUE TITLE
The WordPress Importer plugin should be part of the WordPress develop git clone

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1214]
The WP develop SVN repository includes the WP importer as an svn external. We can mimic this in the git clone by using `svn` to checkout the importer separately from the main repo.

See https://github.com/WordPress/wordpress-develop/blob/master/.travis.yml#L37

**Comment by johnbillion** [comment]
Background on why this is pinned to a tag instead of trunk: https://core.trac.wordpress.org/ticket/40620
