### ISSUE TITLE
Add provisioning for WordPress.com VIP development environment

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1217]
Now that VIP Quickstart has been deprecated, it may be useful for VVV to provide the VIP development environment as part of the Custom Site Template or a new template.

See: https://vip.wordpress.com/documentation/vip/dev-environment/

I'm guessing @tomjn has some thoughts on this. 😄

**Comment by westonruter** [comment]
Chassis has implemented this as well: https://github.com/Chassis/vip-classic

**Comment by LoreleiAurora** [comment]
@jeremyfelt Tom already did this 😀
https://github.com/tomjn/VIP-VVV

**Comment by tomjn** [comment]
I'm happy for it to be forked and maintained as part of VVV

Also, @simonwheatley started on a VIP Go build a while back at https://github.com/Automattic/vvv-vip-go .

Both projects could do with some extra eyes and testing

**Comment by simonwheatley** [comment]
> Also, @simonwheatley started on a VIP Go build a while back at https://github.com/Automattic/vvv-vip-go .

Also unofficial 🙂

> Both projects could do with some extra eyes and testing

*/me nod*

**Comment by tomjn** [comment]
Closing this out as multiple options are available
