### ISSUE TITLE
OpenSSL Self-Signed certificates working with new version of Chrome

### ISSUE THREAD

**Issue by willenglishiv** [Varying-Vagrant-Vagrants/VVV#1221]
## Expected Behavior

to access https://local.wordpress.dev and not have the lock break

## Current Behavior

I get a screen with the following warning:

Your connection is not private

Attackers might be trying to steal your information from local.wordpress.dev (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

This server could not prove that it is local.wordpress.dev; its security certificate is from [missing_subjectAltName]. This may be caused by a misconfiguration or an attacker intercepting your connection. 

## Possible Solution

To update the OpenSSL command in provision.sh like below:

```bash
	  vvvsigncert="$(openssl req -new -x509 \
            -key /etc/nginx/server.key \
            -out /etc/nginx/server.crt \
            -days 3650 \
            -reqexts SAN \
            -extensions SAN \
            -config <(cat /etc/ssl/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS.1:*.wordpress-develop.dev\nsubjectAltName=DNS.2:*.wordpress.dev\nsubjectAltName=DNS.3:*.vvv.dev')) \
            -sha256 \
            -subj /CN=*.wordpress-develop.dev/CN=*.wordpress.dev/CN=*.vvv.dev 2>&1)"
```

however, that's not an 'automatic' solution, I was going to submit it as a PR, but then you'll have to take the generated cert and move it to a shared folder to exempt it on Mac.

## Steps to Reproduce (for bugs)

1. Provision VVV
2. Update to Chrome 58 or 59
3. Access https://local.wordpress.dev
4. View the warning

## Context

I need to have an SSL certification so my OAuth2 testing and my push notifcations work.

## Your Environment

* VVV version: vvv2
* Vagrant version: 1.9.3
* VM Provider name: VirtualBox
* VM Provider version: 5.1.18
* Operating System and version: MacOS Sierra 10.12.5

**Comment by tomjn** [comment]
SSL won't work automatically out of the box, you can add it by adjusting the Nginx templates to use a certificate your machine trusts, but you'll need to generate those certificates yourself
