### ISSUE TITLE
No admin priveliges for 'vagrant up' using vagrant-hostsupdater

### ISSUE THREAD

**Issue by drawcard** [Varying-Vagrant-Vagrants/VVV#1223]
## Current Behavior
If running ```vagrant up``` for the first time, the provisioner asks for the system admin password but no opportunity is presented to enter it in. Subsequently the setup fails. Same error as reported here: https://github.com/cogitatio/vagrant-hostsupdater/issues/92

## Possible Solution
* run ```vagrant up``` as ```sudo``` (workaround, not ideal, since ```vagrant ssh``` has to be run subsequently as sudo as well)
* use ```vagrant-hostmanager``` instead of ```vagrant-hostsupdater``` (works great, found via https://github.com/cogitatio/vagrant-hostsupdater/issues/92#issuecomment-168702403) 
The issue seems to stem from the fact that /etc/hosts needs to be modified, but ```vagrant-hostsupdater``` cannot do so for some reason.

I suggest updating the official docs to use ```vagrant-hostmanager``` as the required vagrant plugin, which works great.

## Your Environment

* VVV version: master
* Vagrant version: 1.9.5
* VM Provider version: Virtualbox 5.0.x
* Operating System and version: macOS 10.12.1

**Comment by johnkeates** [comment]
This happens when you set an ACL on /etc/hosts. Some apps (like Gas Mask) do this.

Check with `ls -le /etc/hosts` and delete the ACL with `sudo chmod -R -N /etc/hosts`

By default it has no ACL and is root:wheel owned with permissions rw/r/r

**Comment by drawcard** [comment]
I use Gas Mask, so that makes sense!

**Comment by tomjn** [comment]
I use gasmask too, though I'd changed my hosts file permissions long before. If you leave it running it can mess with the hosts updater by reverting its changes, so I would avoid using it and VVV at the same time

**Comment by drawcard** [comment]
Do you happen to know of a good alternative to Gasmask for Mac?

**Comment by tomjn** [comment]
It would have the same problem. Wait until provisioning completes before opening gas mask again so it doesn't overwrite Vagrant/VVV's changes
