### ISSUE TITLE
vvv-config.yml replace on pull

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1224]
## Expected Behavior
To update the local installation of vvv do a `git pull origin develop`, no problems.

## Current Behavior
The vvv-config.yml is replaced by the file on the repo and we need to reconfigure everything.

## Possible Solution
Rename vvv-config.yml like vvv-config-example.yml

**Comment by LoreleiAurora** [comment]
You should copy `vvv-config.yml` to `vvv-custom.yml`
