### ISSUE TITLE
How to map external Theme or Plugins folders

### ISSUE THREAD

**Issue by Pezzab** [Varying-Vagrant-Vagrants/VVV#1228]
Hi there, in the previous version of VVV I was able to keep my themes and plugins in a directory elsewhere on my Mac and map them to my VVV WordPress installs with a config. This was very convenient as I was able to keep all my dev work in a separate back up folder and only have to work on one theme copy at a time while mapping it to multiple installs.

I'm guessing (hoping) this can be done with VVV 2. I can see that it is possible to map an entire external WP install ([Custom Paths and Folders](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-paths-and-folders/)), but can't find a way to do this with wp-content folders only.

**Comment by LoreleiAurora** [comment]
What is the config you used before?

**Comment by tomjn** [comment]
Or rather how did you do this in VVV1? There were no configs in v1, I can only guess this was done with symlinks. If so, what prevents that in VVV2?

**Comment by LoreleiAurora** [comment]
@tomjn Vagrant shares do not follow symlinks for security reasons. Thanks for clarifying my question 😀

**Comment by Pezzab** [comment]
I used to to do it in Customfile in VVV 1 using `config.vm.synced_folder` etc

**Comment by LoreleiAurora** [comment]
VVV2 still supports the `Customfile`, there should not be any change here.

**Comment by Pezzab** [comment]
Ah thanks, I managed to wipe out my old Customfile after I messed up my update to VVV 2 and assumed it wasn't supported as I couldn't find any mention in the docs.
