### ISSUE TITLE
Turn XDebug off when running phpunit

### ISSUE THREAD

**Issue by JJJ** [Varying-Vagrant-Vagrants/VVV#1230]
## Expected Behavior

I've noticed significant speed improvements running `phpunit` when XDebug is turned off, and I can't see very much benefit from ever having it on when running tests.

## Current Behavior

When running `phpunit` the XDebug status remains whatever it currently is.

## Possible Solution

Alias `phpunit` to see if XDebug in on, trigger `xdebug_off` if so, then turn it back on when finished if need be.

## Context

In bbPress's unit tests:

* XDebug Off: `Time: 25.54 seconds, Memory: 44.00MB`
* XDebug ON: `Time: 1 minute, Memory: 52.00MB`

## Your Environment
* VVV version: Latest nightly (2.0.0)
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22 r115126 (Qt5.6.2)
* Operating System and version: macOS 10.13 Beta (17A291m)

**Comment by thebrandonallen** [comment]
XDebug is needed to generate code coverage reports. I'm not, necessarily, arguing against, but it is needed sometimes.

**Comment by JJJ** [comment]
That's a good point. I'll close this issue for now, and anyone can reopen it if it's actually worth doing.

**Comment by blackandred** [comment]
You can use Phpunit without xdebug just for test running, and with xdebug just for coverage sometimes.

**Comment by JJJ** [comment]
> You can use Phpunit without xdebug just for test running, and with xdebug just for coverage sometimes.

I understand. I think it rarely makes sense to have XDebug active when running PHPUnit, though. I can imagine circumstances where I want to confirm if a certain test is performing what I expect for it to, but that, to me, seems like an edge-case.

Regardless, issue is closed since it's something I can handle in the VM independent of needing to be a VVV feature.
