### ISSUE TITLE
Database for sites configured in vvv-custom.yml points to wordpress_default

### ISSUE THREAD

**Issue by Pezzab** [Varying-Vagrant-Vagrants/VVV#1231]
If I understand it correctly the name you add to your new site configuration in vvv-custom.yml will determine the name of the WordPress database for that installation, as explained in [Custom Site Template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template).

But when I run vagrant provision the site just defaults to wordpress-default, no new database is set up and in fact all the files in my new site's provision folder (hosts, init and nginx.conf) point to local.wordpress.dev not the new site

**Comment by LoreleiAurora** [comment]
Can you please post the entry you are using in `vvv-custom.yml`

**Comment by Pezzab** [comment]
As per the instructions and format laid out in the docs.

I made the error of assuming that the configuration in vvv-custom.yml would create a database, host and init automatically. I realise now that the set up needs much more manual intervention.

This is described in the docs though I didn't understand it clearly, I made an assumption about how it worked rather than reading the instructions properly!

Not specifying a repo means that vvv-wordpress-default takes over and logically dictates the install,, host, database and so on.

I evidently need to create then specify my own git repo per site install, unless there's another way to do this.

**Comment by tomjn** [comment]
@Pezzab that might not be the case, but we'll need to see your config file to advise, can you post the relevant part you modified here?

**Comment by Pezzab** [comment]
Sorry for the slow reply @tomjn. I've been away for a while.

I think I've got a handle on it. As I haven't set up a repo for provisioning this is my process:

So this is in my vvv-custom.yml:
```
  gentest:
    hosts:
      - gen.test
```
I then manually create my gentest directory and under this my provision and log directories.

I copy vvv-hosts, vvv-init.sh, vvv-nginx.conf from one of the default installs and search and replace the host names etc.

Running vagrant reload --provision then installs my site.

That works pretty well for me though it seems a shame that all this can't all happen automatically with the details in vvv-custom.yml, which is how I expected it to work when I first tried it - before actually reading the docs properly :)

**Comment by LoreleiAurora** [comment]
@Pezzab You can set the [custom-site-template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template) as the repo for your project and configure the site entirely from the yaml file. This removes the need to copy pasta files.

**Comment by Pezzab** [comment]
Thanks @LoreleiAurora, I don't know how I managed to overlook that!
