### ISSUE TITLE
Woocommerce extremely slow, related to VVV 1.0?

### ISSUE THREAD

**Issue by brograhamer** [Varying-Vagrant-Vagrants/VVV#1240]
## Expected Behavior

Woocommerce needs to load quicker on local.

## Current Behavior

Woocommerce has been consistently loading slowly on local development. We are doing nothing spectacular with Woocommerce other than basic theme integration. Once out of development and onto live staging or production servers we do not get the 8-12 second load times for ~10 products. We are wondering if this might be a VVV issue since WAMP does not harbor these same load deficits. 

Does VVV 2.0 address this issue?

## Possible Solution

Unsure.

## Steps to Reproduce (for bugs)

Load VVV 1.0, or less than 2.0, and run a basic wordpress install and Woocommerce with theme support. Any shop template loads more slowly on a local environment than a live one.

## Your Environment
* VVV version: 1.0
* Vagrant version: 1.9.7
* VM Provider name: Virtualbox
* VM Provider version: 5.0
* Operating System and version: Windows 10

**Comment by swashata** [comment]
Hi,

I am on VVV version 2.0 (on the develop branch, since mailcatcher refuse to install on the master branch) and everything runs smoothly. Additionally I have setup NFS based synched_folder. I have written a detailed tutorial here https://www.intechgrity.com/nfs-based-file-sharing-for-varying-vagrant-under-windows/ :)

**Comment by tomjn** [comment]
@brograhamer I can't comment on VVV 1, but VVV 2 fixes a lot of things and brings a lot of internal improvements. If it is a VVV 1 only issue the solution would be to upgrade, we're not updating the two separately. Try it on VVV 2, [migrating is easy](https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/), just add an entry for your site in `vvv-custom.yml` and reprovision

**Comment by tomjn** [comment]
I'm going to close this one out, I'd strongly recommend moving from VVV 1 to VVV 2.x
