### ISSUE TITLE
Wrong MySql path shared in guest

### ISSUE THREAD

**Issue by simonschllng** [Varying-Vagrant-Vagrants/VVV#1243]
## Expected Behavior

Vagrant shares guestpath `/srv/database` with host. MySql should use this path.

## Current Behavior

MySql stores databases in `/var/lib/mysql` on the guest. `/srv/database` does exist in guest and contains the backup and data folders from host.

## Possible Solution

Change MySql config or vagrant config? 

## Steps to Reproduce (for bugs)

I don't know how I get there. Using vvv with vv for many years now. Seems that this was never working.

## Context

I want to get the database backups in `database/backups` working.

## Your Environment

* VVV version: 1.2.0 (readme says...)
* Vagrant version: 1.8.1
* VM Provider name: VirtualBox 
* VM Provider version: 5.0.40
* Operating System and version: Ubuntu 16.4

**Comment by LoreleiAurora** [comment]
The mapping you are referring to is correct. The old way of mapping DB data to the host was deprecated as it caused a lot of problems.
To enable backups install the vagrant-triggers plugin on the host by running `vagrant plugin install vagrant-triggers`

**Comment by tomjn** [comment]
@simonschllng did that work for you?

**Comment by tomjn** [comment]
I'm going to close this out as the change was intentional
