### ISSUE TITLE
Shiny VVV2 logo shown when checking global status

### ISSUE THREAD

**Issue by johnbillion** [Varying-Vagrant-Vagrants/VVV#1245]
## Expected Behavior

When running `vagrant global-status --prune`, the standard Vagrant output should be shown.

## Current Behavior

The lovely shiny VVV2 logo is shown in addition. Screenshot:

<img width="523" alt="" src="https://user-images.githubusercontent.com/208434/29127823-7315fefe-7d22-11e7-96a1-c705ad8b177e.png">

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.2
* VM Provider name: VirtualBox
* VM Provider version: 5.1.14
* Operating System and version: macOS 10.12

**Comment by tomjn** [comment]
I wonder if this can be resolved using the `ARGV` variable to check which command is being ran? In the meantime a workaround is to set `VVV_SKIP_LOGO=false`

`VVV_SKIP_LOGO=false vagrant status`

<img width="570" alt="screen shot 2017-11-04 at 16 33 21" src="https://user-images.githubusercontent.com/58855/32407235-e6e71f58-c17d-11e7-8d1c-cb61a6c2905a.png">
