### ISSUE TITLE
Broken link in installation instructions

### ISSUE THREAD

**Issue by nylen** [Varying-Vagrant-Vagrants/VVV#1249]
## Expected Behavior

From https://varyingvagrantvagrants.org/docs/en-US/installation/:

> 6. Visit any of the [built in WordPress sites](https://varyingvagrantvagrants.org/docs/en-US/installation/built-in-wp-installs.md) or the VVV Dashboard at http://vvv.dev

I expect that clicking the "built in WordPress sites" link will take me to a working page.  I didn't know that VVV supported multiple sites, but it sounds useful and I'd like to read more about this feature.

## Current Behavior

The link points to https://varyingvagrantvagrants.org/docs/en-US/installation/built-in-wp-installs.md which is "403 Forbidden".

## Possible Solution

Restore this docs page if it was removed, or remove the broken link.

**Comment by tomjn** [comment]
There is a page here:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/docs/en-US/references/basic-usage.md

But I can't access it on the site due to a redirect and a 403 forbidden response

**Comment by nylen** [comment]
This doesn't appear to be the same page?  Or maybe you are mentioning it as a further example of the same server error?  I also see this error at https://varyingvagrantvagrants.org/docs/en-US/references/default-sites.md.

`built-in-wp-installs.md` was moved to `references/default-sites.md` in https://github.com/Varying-Vagrant-Vagrants/VVV/commit/08a31d51e5ccb530c7725b5babd7619be869c874 (cc @jeremyfelt).  However, this document doesn't actually describe anything about the built-in sites in a default VVV install.

**Comment by tomjn** [comment]
Yeah I copied the URL from the tab next to the one with default sites, https://varyingvagrantvagrants.org/docs/en-US/references/default-sites.md also won't work because there are no markdown files on the built site. I think Jekyll is converting them to their final URLs if they're found, so it would be:

https://varyingvagrantvagrants.org/docs/en-US/references/default-sites/
