### ISSUE TITLE
VM Box Already Exists

### ISSUE THREAD

**Issue by Gemfruit** [Varying-Vagrant-Vagrants/VVV#1251]
Whenever I run vagrant up, I get an error that the VM already exists. When I try to restart my computer, VirtualBox says it has an active connection, despite me running vagrant halt, and having everything powered down.

![vm-issue](https://user-images.githubusercontent.com/1664812/29193114-f8bff92c-7df1-11e7-97eb-3b7d14e5471f.jpg)

When I restart anyway (force closing the connection), and attempt to run vagrant up again, I get the above error, and the default VM says it's inaccessible. The virtualbox VM folder shows TWO boxes, the default, and one named vagrant-local, my current working folder. VirtualBox itself shows the default (powered down), but the vagrant-local does not exist. I have removed the vagrant-local machine manually, re-run vagrant up (downloads the box again), and this issue still persists. Every time I run the instructions as stated, or do what the errors say, I end up in a loop, back where I am now.

This appears to be an issue with how the box is shutting down, but I'm too new to all of this to figure it out.

In my previous installation, I recall virtualbox showing a vagrant-local VM in the UI, and not having the default, but that's not the case anymore - not sure if that's just the new setup, or what.

When I first run vagrant up, everything works, I can visit the default sites, provision a new site, etc, everything breaking pertains to the shutdown process, restarting my computer, etc.

I have a fresh install of vagrant, virtualbox, and vvv, and followed the instructions on the vvv page. I've been at this for over 5 hours now (uninstalling, reinstalling, restarting, trying to figure things out, etc, and I cannot get it to work for the life of me. I would greatly appreciate any help regarding this issue, as I'm finding myself completely lost.

**Comment by Gemfruit** [comment]
I've since solved the issue - details below.

For whatever reason, uninstalling Vagrant and Virtualbox simply wasn't enough, there was a lot of junk files left over in both my Users\my-name directory, Users\my-name\vagrant-local (I had a VERY hard time deleting this directory, even after removing all software pertaining to it), and the VMs directory. Despite running destroy, unintalling, using the Virtualbox GUI, etc, files were left behind from previous installations. I manually removed everything I could find on my machine pertaining to Vagrant and Virtualbox, and a fresh install did the trick.

My concern here, is that this wasn't a very old install - I reformatted my machine roughly 5 months ago, which means this software was somewhat up to date (and I did update as updates came out). This much garbage being left behind caused tremendous issues, such that someone not completely well-informed with this technology spent hours upon hours trying to debug what is supposed to be simple, straightforward software, that takes the challenge out of a local web environment. I had errors ranging from vb-guest (or whichever plugin is used to install triggers and hosts-updater) not being installed, to a box already existing, to restarting my computer not working due to a Virtuabox connection still existing.

I absolutely love this software, but given my experience, I think some more testing would benefit the smoothness of the experience. Uninstalling the software should completely remove all of these files (if desired), and perhaps a separate, open-source tool could exist to locate and remove lingering files. I'm not too sure on a solution, but I'm certain I didn't venture into tasks that were advanced, or out of the basic scope of creating an environment, and 2 sites.

All in all, it's working again, and I hope my input helps someone device some future testing, planning, and bug hunting. Note, this an open-ended suggestion to the entire workflow, and isn't directed at any one piece or person.

**Comment by LoreleiAurora** [comment]
All of the issues you have outlined in this issue are actually upstream in the Vagrant/Virtualbox pieces of software. We have seen them all before, but have never seen a solution work more than once.

Glad you got this sorted, Thanks for the feedback :)
