### ISSUE TITLE
Can't delete file after vagrant detroy

### ISSUE THREAD

**Issue by caseyallen386** [Varying-Vagrant-Vagrants/VVV#1254]
![image](https://user-images.githubusercontent.com/11019110/29256997-d03f4210-806b-11e7-8332-025b33d52639.png)

OS: Windows 10
Ruby is installed also have MSYS2 and Mingw64 - (Which I think allowed me to vagrant ssh with out using putty) 

After I destroyed the vagrant, I deleted the files left over in the project folder, all except one. You see from the image that it says that the file is no longer located in the in the folder location. 
The path is: config>nvm>test>fast 
the file name is: "Sourcing nvm.sh should make the nvm command available"

I think it is somehow a symlink file but I am not sure about that and I don't know how to correct this issue

Any help would be appreciated, not a major issues but the folder is pretty much useless I can't delete it and I cant create any more vagrants in it because they don't install correctly.

**Comment by tomjn** [comment]
Can it be deleted from the command line?

**Comment by Gemfruit** [comment]
I've encountered this issue a few times over the last couple of days (had a corrupted setup, had to start from scratch, and manually remove files). You should be able to remove the directory via command line, give yourself administrative access just to be sure:

`rmdir /s /q C:\Vagrant\portfolio\VVV\config`

**Comment by caseyallen386** [comment]
No its still give the same error message of not being able to find the file.


________________________________

**Comment by caseyallen386** [comment]
Thanks Matt that worked, using both params.


________________________________
