### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by axelson** [Varying-Vagrant-Vagrants/VVV#1257]
I'm getting a 403 on the documentation for the custom domains and hosts: 

https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-domains-host.md

Linked from: https://varyingvagrantvagrants.org/docs/en-US/

**Comment by tomjn** [comment]
Thanks @axelson I've created a Pull request fixing it, there's a few docs changes pending deployment at the moment, so once that's merged I'll poke a few people to get it all live

In the meantime, all the docs are in git and bundled with every copy of VVV
