### ISSUE TITLE
Dashboard List all Sites

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1261]
Right now the list of sites on vvv.dev is hardcoded. This makes discoverability and UX poor, I saw someone install the WP meta environment only to see no change and assume it was broken

Instead it should load up the `vvv-custom.yml` and read the hosts list. A description field for `vvv-custom.yml` would be super useful too

**Comment by borjalofe** [comment]
I assume you can read the `vvv-custom.yml` from inside the VM -which I didn't think of and opens lots of possibilities.

Wouldn't it be easy to read the databases you have in VM's MySQL?

**Comment by tomjn** [comment]
The sites aren't stored in MySQL, they're in `vvv-custom.yml`, so a YAML parser in PHP can read `/vagrant/vvv-custom.yml`

**Comment by borjalofe** [comment]
I see. Thanks for the clarification!

**Comment by tomjn** [comment]
This was added in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1280
