### ISSUE TITLE
Unclear how to map smb drive/folders to webroot

### ISSUE THREAD

**Issue by filip-van-hoeckel** [Varying-Vagrant-Vagrants/VVV#1264]
## Expected Behavior
Unsure how to notate smb path in config, or use synced folder (rather not) as Vagrant docs suggest

## Current Behavior
Tried driveletter:\ and driveletter:/ and \\ipaddress\absolutepath. None work

## Possible Solution
unsure

## Steps to Reproduce (for bugs)
try configuring a site using localdir and vmdir to use files on a networkdrive 

## Context
Trying to use files that are on a network path, so there's no need to cp them over to local machine.

## Your Environment

* VVV version: latest
* Vagrant version: latest
* VM Provider name: VirtualBox
* VM Provider version:
* Operating System and version: Win10 X64 Pro

**Comment by tomjn** [comment]
@filip-van-hoeckel can you post your vvv config so we can see what you tried? It might be that you only specified a single key out of the two required, that you used the wrong one, the wrong format, or put it in the wrong place, we need to see the config file to be able to diagnose

**Comment by filip-van-hoeckel** [comment]
---
sites:
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.dev

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.dev
      - build.wordpress-develop.dev	  
  # Optex
  optex:
    vm_dir: /srv/www/customername
    local_dir: X:\\www.customername.dev
    hosts:
      - customername.dev

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.dev

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind

**Comment by tomjn** [comment]
@filip-van-hoeckel have you tried wrapping them in quotes? Does it work when it isn't a network drive? I googled and a lot of what I found looked very complex and fragile, so I wouldn't recommend using a shared network mapped drive for development in general, nevermind with vagrant. I would suggest using basic version control instead

**Comment by tomjn** [comment]
I looked further, and no, right now VVV out of the box probably won't work with SMB shares directly. If you get it working using just `vvv-custom.yml` then let us know and I'll update the docs, but your chances are low.

An SMB share should be possible via Vagrant, but it's Windows specific and require Vagrant level changes:

https://www.vagrantup.com/docs/synced-folders/smb.html

You can't just specify the mapped directory/drive. I'm going to close this as it requires some pretty specific Vagrant changes that will only work for you, but you now have everything you need to continue, and there are some examples out there, but be warned, some of them look intimidating
