### ISSUE TITLE
Mailcatcher not being installed

### ISSUE THREAD

**Issue by marcc1213** [Varying-Vagrant-Vagrants/VVV#1265]
I already had Mailcatcher installed. When I install vvv Mailcatcher is not found. 

http://vvv.dev:1080 returns a Server not found error.

I am running on a new Mac using Sierra.

This is from the terminal:

==> default:  * Mailcatcher [not installed]
==> default: Building native extensions.  This could take a while...
==> default: ERROR:  Error installing mailcatcher:
==> default: 	ERROR: Failed to build gem native extension.
==> default: 
==> default:         /usr/bin/ruby1.9.1 extconf.rb
==> default: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
==> default: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
==> default: 	from extconf.rb:2:in `<main>'
==> default: 
==> default: 
==> default: Gem files will remain installed in /var/lib/gems/1.9.1/gems/eventmachine-1.0.9.1 for inspection.
==> default: Results logged to /var/lib/gems/1.9.1/gems/eventmachine-1.0.9.1/ext/gem_make.out
==> default: Regenerating system wrappers
==> default: .............
==> default: Could not find file 'mailcatcher' nor '/usr/local/rvm/wrappers/system/mailcatcher'.
==> default: Could not find file 'catchmail' nor '/usr/local/rvm/wrappers/system/catchmail'.
==> default:  * Copied /srv/config/init/mailcatcher.conf    to /etc/init/mailcatcher.conf
==> default:  * Copied /srv/config/php-config/mailcatcher.ini    to /etc/php/7.0/mods-available/mailcatcher.ini
==> default:  * Copied /srv/config/php-config/php7.0-fpm.conf   to /etc/php/7.0/fpm/php-fpm.conf
==> default:  * Copied /srv/config/php-config/php7.0-www.conf   to /etc/php/7.0/fpm/pool.d/www.conf
==> default:  * Copied /srv/config/php-config/php7.0-custom.ini to /etc/php/7.0/fpm/conf.d/php-custom.ini
==> default:  * Copied /srv/config/php-config/opcache.ini       to /etc/php/7.0/fpm/conf.d/opcache.ini
==> default:  * Copied /srv/config/php-config/xdebug.ini        to /etc/php/7.0/mods-available/xdebug.ini
==> default:  * Copied /srv/config/memcached-config/memcached.conf   to /etc/memcached.conf
==> default: Restart services...
==> default:  * Restarting nginx nginx

**Comment by matthewhegarty** [comment]
Workaround and possible related bug [here](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/985)

**Comment by marcc1213** [comment]
Tried that with no luck.

**Comment by matthewhegarty** [comment]
What was the issue? I had to install correct dependencies re this [thread](https://github.com/sj26/mailcatcher/issues/277)

**Comment by tomjn** [comment]
@marcc1213 does this still happen in 2.1 on the latest `develop` branch?

**Comment by marcc1213** [comment]
Sorry, I had to move on to another solution and have not revisited this

**Comment by tomjn** [comment]
I'm going to close this then, there was a PR that attempted to fix this that got merged, if this is still an issue for anybody on the latest `develop` branch, please open a new ticet

**Comment by marcc1213** [comment]
I know this is closed but since someone else may run into it, I was able to resolve it. I completely removed node and ruby which I had installed manually, and reinstalled using homebrew. Works like a charm now.

I assume the issue was something with how I installed node and/or ruby in the first place.
