### ISSUE TITLE
WordPress coding standards are not installed in PHP_CodeSniffer

### ISSUE THREAD

**Issue by kmgalanakis** [Varying-Vagrant-Vagrants/VVV#1266]
When I `vagrant up` after cloning the `develop` branch, I get PHP_CodeSniffer installed in `/srv/www/phpcs` but if I run `./bin/phpcs -i`, I get:

`The installed coding standards are MySource, PEAR, PSR1, PSR2, Squiz and Zend`

Can anyone help?

**Comment by matthewfarlymn** [comment]
I just tried to use this as well and WordPress folder is no longer listed in the CodeSniffer directory ^

**Comment by kmgalanakis** [comment]
@matthewfarlymn where is the CodeSniffer directory?

**Comment by matthewfarlymn** [comment]
@kmgalanakis  [VagrantFolder] > www > phpcs > CodeSniffer

**Comment by kmgalanakis** [comment]
I don't even have that directory there. 😞

**Comment by tomjn** [comment]
Fixed in #1239
