### ISSUE TITLE
Custom site hostname is resolving to vvv.dev dashoard

### ISSUE THREAD

**Issue by twoelevenjay** [Varying-Vagrant-Vagrants/VVV#1267]
## Expected Behavior
I expected to create a custom site in addition to the default WordPress installs that VVV ships with. 

## Current Behavior
It appears the site is created in the file structure and added to the host file, but the virtual server is resolving the custom host name to the vvv.dev dashboard instead.

## Steps to Reproduce (for bugs)

1. I created a vvv-custom.yml file like this: https://gist.github.com/twoelevenjay/6995d0250c0c6842b8d557def00c2517
2. I ran `vagrant provision`.
3. I navigated to trg.dev
4. VVV resolves to the vvv.dev dashboard instead of the trg.dev directory.

Provision log:
https://gist.github.com/twoelevenjay/7c765682687f28672ad46bcef682b8a9

## Context
I am trying to add a new site to VVV with the vvv-custom.yml file.

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.5
* VM Provider name: Virtualox
* VM Provider version: 5.1.26
* Operating System and version: Mac OSX 10.12.6

**Comment by tomjn** [comment]
It's likely that the provisioner in https://github.com/JPry/vvv-base.git failed for whatever reason before stuff could get setup, so the nginx config step was never reached.

To diagnose this further, we'd need to see output of a `vagrant up --provision` for this site. You can use the skip provisioning flag to turn off other sites to diagnose just that site

**Comment by tomjn** [comment]
As an aside, the fix for this will need to be done in the 3rd party `vvv-base` repo, so you're probably better raising the issue at https://github.com/JPry/vvv-base/issues

**Comment by tomjn** [comment]
Latest VVV dashboard puts a notice up if it detects it's not on the dashboard domain with a note. I'm going to defer to the vvv-base issues for this, if you can point at an error in the core provisioner though let us know what it is and we'll look into it
