### ISSUE TITLE
Documentation page link "Custom Domains and Hosts" returns 404

### ISSUE THREAD

**Issue by jmslbam** [Varying-Vagrant-Vagrants/VVV#1271]
## Expected Behavior
See documentation about "Custom Domains and Hosts"
This markdown's content
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/57cc18d6555cc9e036e63c0b301ab55a5492c0da/docs/en-US/adding-a-new-site/custom-domains-hosts.md

## Current Behavior
On this page https://varyingvagrantvagrants.org/docs/en-US/ the page "Custom Domains and Hosts"  returns an 404 to 
https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-domains-host.md

## Possible Solution
Don't know :)

## Steps to Reproduce (for bugs)

1. Go to this page https://varyingvagrantvagrants.org/docs/en-US/ the page 
2. Click on "Custom Domains and Hosts"

## Context
Trying to read the documentation

## Your Environment
Just a browser

Ciao!

**Comment by tomjn** [comment]
This is already fixed in `develop`, but those specific changes need merging into `master` and deploying. Until then, https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-domains-hosts/ works, and there's a markdown copy on github and in every VVV install

**Comment by jeremyfelt** [comment]
Docs are deployed and this is resolve now. :) Thanks, @jmslbam.

**Comment by jmslbam** [comment]
👍 great, gracias!
