### ISSUE TITLE
Possible to have old version and new 2.0 installed?

### ISSUE THREAD

**Issue by PsySolix** [Varying-Vagrant-Vagrants/VVV#1272]
Hello! 
Because I'm having difficulties working on my original vagrant setup 
see [Issue](https://stackoverflow.com/questions/45976706/vagrant-multiple-wp-performance-suddenly-dropped-ttfb-1minute) 
** If anybody maybe has an idea for my original issue, please let me know

I was wondering if it's possible to have the 1.2.1 version installed and install the new 2.0 version in another location. Would it interfere with the DB? Overwrite local files? Or would it work flawless?

I would test it myself but can't afford to lose any data. We are speaking in terms of 30+ sites.

Thanks in advance!

## Environment
* VVV version: 1.2.1
* Vagrant version:  1.8.1
* VM Provider name: VirtualBox
* Operating System and version: Mac, El Capitan

**Comment by LoreleiAurora** [comment]
you can have both installed at the same time, just check them out in folders with different names.

**Comment by PsySolix** [comment]
Hi Lorelei, and there will be no clash between the Database data?

**Comment by LoreleiAurora** [comment]
There will be no clashes as they will be different vms.
The `vagrant-local` would be the name to change.
