### ISSUE TITLE
Add VVV version to vagrantfile

### ISSUE THREAD

**Issue by topdown** [Varying-Vagrant-Vagrants/VVV#1273]
I was going to make a pull request for this but thought I would get opinions first. I would like the VVV version to be available somewhere that is readable by the VM's PHP
I think it would be possible to read the vagrantfile so having a comment on like line 3 with the version would be much appreciated. It only needs to be managed on major changes so that I have something to trigger on for backwards compatibility in my VVV Dashboard and other tools.

Eg.
```
# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 et:
# vvv2

require 'yaml'
```

**Comment by tomjn** [comment]
This might be useful, but you can differentiate VVV 1 and VVV 2 based on the presence of `vvv-config.yml`. You can also look at `/vagrant` which is the root VVV folder on the host shared with the VM, at which point you could check the git repo or the readme, or look for the VVV2 logo in the vagrant file

**Comment by LoreleiAurora** [comment]
If we were to do this i would prefer to set it as a ruby variable and a environment variable inside the box. Would that work for you?

**Comment by topdown** [comment]
Sure, an environment variable would be fine as it should be accessible by PHP.

**Comment by tomjn** [comment]
As an aside, this would allow the version to be shown in the dashboard

**Comment by tomjn** [comment]
There's now a version file in the root that can be used for this.

Re: backwards compatibility, people should always be using the latest VVV, if an update of VVV breaks a site template, then that's a bug

**Comment by topdown** [comment]
@tomjn I have never been able to stay on top of the latest VVV as it was always an issue getting 
 the latest working. Which is tough to chew on when you have a working version.
This was also the issue of me slowing down on my Dashboard repo as I have never successfully been able to get the new version of VVV running to fix the issues.

Either way, thanks for adding the version file. 👍

**Comment by tomjn** [comment]
Getting it working should be less of an issue these days, but please open issues so we can look into stuff! One of my hopes is to refactor how logging works so that we get a lot more information, and in a way that it can be surfaced to people, rather than the mystery meat of a wall of provisioner text in a console
