### ISSUE TITLE
Host and Guest machine compatability over a network drive

### ISSUE THREAD

**Issue by brograhamer** [Varying-Vagrant-Vagrants/VVV#1278]
## Expected Behavior

Windows 10 OS.

**Developer 1** runs `vagrant up` on the host machine that has all the files.

**Developer 2** accesses the host machines files through the network (mapped to x:) runs `vv create` on a guest machine, spins up a new Wordpress website, and runs `vagrant reload --provision`

Right now, it would completely reinstall the virtualbox on the guest machine if `vagrant reload --provision` is run.

Right now, the guest has to hop onto the host machine to run these commands to prevent anything from reinstalling or breaking.

If **Developer 1** is on vacation **Developer 2** needs to run these commands from the guest machine without reinstalling vagrant, the virtualbox, or messing up the IP that the vagrant uses. 

## Current Behavior

If **Developer 2** runs `vagrant up`, `vagrant halt`, or `vagrant reload` on the guest machine the entire server will be reinstalled on the guest machine, which screws up the virtualbox and install on the host machine.

## Possible Solution

Unsure. I need **Developer 2** to run these commands on their guest machine and have it directly affect **Developer 1**'s host machine without messing up or reinstalling anything.

## Your Environment

* VVV version: 2.0
* Vagrant version: 1.9.7
* VM Provider name:  Virtualbox
* VM Provider version: 5.0 or 5.1 something
* Operating System and version: Windows 10

**Comment by LoreleiAurora** [comment]
you will not have much luck with this and it is not supported. VVV is meant to be installed separately to each developers machine.

**Comment by brograhamer** [comment]
Understood. This seems to be the closest thing to what we're trying to achieve. Unsure of anything else that can do this.

**Comment by LoreleiAurora** [comment]
why not store the project files in version control and install VVV on all machines?

**Comment by brograhamer** [comment]
Well right now I own the host machine, which contains the virtualbox, the vagrantfile, Wordpress sites, and databases. 

The database folder is backed up hourly and symlinked to dropbox.

We only have each sites `theme` as git repository. I'm unsure about uploading the entire `wp-content` folder. That seems like overkill for git. Maybe this is where I'm getting hung up?

As of now I (host machine) am in charge of running `vagrant` related commands. Everything relating to vvv is hosted on my machine, no one elses.

The other developer can access each websites theme through a network drive and run `gulp` or `git` commands as needed. As I stated, they can't run `vagrant` commands basically because of what you said - it's for individual machines.

So far this hasn't posed a huge problem. I'm usually always here and when a site needs to be spun up they let me know. Gives me some control so I know what all is on the server at all times. Would be nice for future, multiple developers to have access to the same commands on their machines over time (which, from what I see, isn't possible). 

Thank you for reading, hope that clarifies our usage of VVV.

**Comment by cfoellmann** [comment]
as a "hotfix" you could use Remote Desktop, Teamviewer or even a SSH/Powershell remote session to run the vagrant commands on the hosting pc (yours).
