### ISSUE TITLE
Add vvv.local and vvv.localhost

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1282]
Currently we use vvv.dev but recent reports suggest that Google are going to enforce HTTPs via preloaded HSTS:

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

https://chromium-review.googlesource.com/c/chromium/src/+/669923

Instead, lets add support for `vvv.local` and `vvv.localhost`, and switch our documentation over. These TLD's are unavailable for purchase, and reserved as per RFC 6762 and RFC 2606

**Comment by jeremyfelt** [comment]
Agreed! We've had https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583 as a warning for 2.5 years now, but never actually got around to it. There's some good conversation on that, so let's close this and re-spark the conversation there.
