### ISSUE TITLE
.dev domains to be forced on HTTPS in Chrome

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1283]
A news came out that Chrome will, in their next release, force `.dev` domains to HTTPS using HSTS (HTTP Strict Transport Security) header.

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

Since all the bundled environments on VVV are on .dev domains this could impact the users of VVV.

How can/will this be solved?

**Comment by rebeccahum** [comment]
Article suggests to change it to `.test` or `.localhost`, which is probably the best course of action.

**Comment by tomjn** [comment]
Closing as a duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583
