### ISSUE TITLE
vboxnet not being created ?

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#1284]
Using Windows 10 64bit
VirtualBox 5.1.28
Vagrant 2.0.0

I can do `vagrant up`.
I cannot load the dashboard or any of the default sites like http://local.wordpress.dev
In Chrome, I get `Cannot connection - ERR_ICANN_NAME_COLLISION`
In Firefox, I get `Unable to Connect`

When I tried [LoraleiAurora's fix from here](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1219)

- vagrant up
- ip link note the number of the vboxnet in the output
- sudo ip link vboxnet0 up Replace vboxnet0 with the one retrieved from the last command

I cannot get past the second step.  Using ssh, I see: 
```
vagrant@precise32:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:12:96:98 brd ff:ff:ff:ff:ff:ff
```
But there is no listing for vboxnet. 
So is it not being created ?  
Or is there some other issue ?

**Comment by tomjn** [comment]
Loreleis fix is for Linux not Windows machines, it shouldn't be possible to use it on Windows. It was intended for the host machine not the Virtual Machine. Since the issue was caused by changes to the Linux kernel, this can't be the same problem ( you're not running Linux )


Have you:

 - rebooted after the Vagrant/Virtualbox installations
 - reprovisioned after a reboot
 - verified that you don't have multiple entries for VVV domains in your hosts file as implied by `ERR_ICANN_NAME_COLLISION`

**Comment by rmurillo21** [comment]
I have the same setup and its working well.  Try to ping and curl the site on Windows and post results here.

```
ping vvv
curl -I http://vvv.dev

```

For reference, here is my `ip link` output:

```
vagrant@vvv:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:01:15:46 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:9b:35:98 brd ff:ff:ff:ff:ff:ff
```

**Comment by rmurillo21** [comment]
Regarding `ERR_ICANN_NAME_COLLISION`:

See https://superuser.com/questions/919278/err-icann-name-collision-when-trying-to-use-localhost-dev-in-chrome

and  https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583

Not sure, but it could be related to the `.dev` TLD?

**Comment by shanebp** [comment]
@tomjn - The answer is 'yes' to all 3 of your questions. 
My hosts file:
```
127.0.0.1       localhost
::1             localhost
127.0.0.1 local.wordpress.dev # vvv-auto
127.0.0.1 src.wordpress-develop.dev # vvv-auto
127.0.0.1 build.wordpress-develop.dev # vvv-auto
```

**Comment by shanebp** [comment]
@rmurillo21 

Re:  collision - I've read those posts and I'm unclear as to what I can beside the edits I've already made to hosts file. 

But perhaps first I need to find out why the vbox cannot be found: 
```
E:\VVV>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'hashicorp/precise32' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.1
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Mounting shared folders...
    default: /vagrant => E:/VVV
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

E:\VVV>ping vvv
Ping request could not find host vvv. Please check the name and try again.

vagrant@precise32:~$ ping vvv
ping: unknown host vvv

vagrant@precise32:~$ curl -I http://vvv.dev
curl: (7) couldn't connect to host

vagrant@precise32:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:12:96:98 brd ff:ff:ff:ff:ff:ff
```

**Comment by rmurillo21** [comment]
Thanks I see there that "Machine already provisioned." message on vagrant up. So we sort of miss all the good stuff you would see on a full provision.

I would suggest doing a full provision, and then post that as a gist.

Can you also post c:\windows\system32\drivers\etc\hosts?

**Comment by rmurillo21** [comment]
Are you running with administrative privileges? If not, open a DOS window with admin rights and try again.
I am thinking you have not, and for that reason there are no host entries in etc\hosts.
Compare your log to this one in my vagrant up:
```

==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.50.4  custom.localhost  # VAGRANT: dd65e59ab9bf4e24239d0e1500b962b4 (default) / 172a4a8b-26b0-4efe-ae10-cd91447b6ce5
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file. 
```
Your log does not show any host entries, which would explain the problem.

**Comment by shanebp** [comment]
From cmd as admin:  https://gist.github.com/shanebp/7a5b3eff4524c97d9494f2633d420d36

It seems that _host entries_ are still not being found. 

hosts file:
```
127.0.0.1       localhost
::1             localhost
127.0.0.1 local.wordpress.dev # vvv-auto
127.0.0.1 src.wordpress-develop.dev # vvv-auto
127.0.0.1 build.wordpress-develop.dev # vvv-auto

```

**Comment by shanebp** [comment]
Also tried changing hosts to:
```
127.0.0.1       localhost
::1             localhost
192.168.50.4 vvv 
192.168.50.4 vvv.dev
192.168.50.4 local.wordpress.dev
```
But _host entries_ are still not being found.

**Comment by tomjn** [comment]
Does this issue happen in all browsers? Or just chrome? Are you using a custom DNS application? Keep in mind that browsers such as chrome have DNS caches

Note that you shouldn't be adding `vvv` in your hosts file, as that's not a URL VVV tries to add, and you should be using the hosts updater plugin else you'll be constantly modifying your hosts file

**Comment by tomjn** [comment]
>But host entries are still not being found.

Keep in mind that the error is `ERR_ICANN_NAME_COLLISION`, not `ERR_NAME_NOT_RESOLVED`. This means that DNS *was* found, but that it was found **multiple times**. This is why it's important you don't have duplicate or redundant entries inside your hosts file

**Comment by shanebp** [comment]
I have removed all the entries from the hosts file. 

vagrant up,  then try to load: http://vvv.dev/

In Chrome, I get `Site can not be reached - ERR_ICANN_NAME_COLLISION`

In Firefox, I get` Server not found. Firefox can’t find the server at www.vvv.dev.

**Comment by tomjn** [comment]
are you entering http://vvv.dev or vvv.dev into firefoxes address bar? www.vvv.dev is unexpected

What does this command ran in a windows command prompt give you after a succesful provision:

```
nslookup vvv.dev
```

Also can we see a full log of your provisioner on `vagrant up --provision`? If you halt the VM, remove any hosts file entries, do you still get this error? Or does it indicate something different as expected ( if so which? )

**Comment by shanebp** [comment]
I entered vvv.dev into firefoxes address bar.

The provision log is here: https://gist.github.com/shanebp/7a5b3eff4524c97d9494f2633d420d36

I removed all host file entries and still get the errors in both browsers. 

Your command gives this: 
```
E:\VVV>nslookup vvv.dev
Server:  cdns01.comcast.net
Address:  2001:558:feed::1

Non-authoritative answer:
Name:    vvv.dev
Address:  127.0.53.53
```

Entering 127.0.53.53 in chrome gives: ERR_CONNECTION_REFUSED
Entering it in Firefox gives:  Unable to connect

**Comment by tomjn** [comment]
`nslookup` gave good information back

Enter http://vvv.dev into firefox instead. Be precise and specific about it, don't let the browser try to be clever and interpret what you wanted. www.vvv.dev will never work.

What does Chrome tell you if you halt the VM, remove the hosts file entry, and restart chrome, then visit http://vvv.dev?

**Comment by shanebp** [comment]
>Enter http://vvv.dev into firefox
Result:  `Server not found. Firefox can’t find the server at www.vvv.dev.`

>What does Chrome tell you if you halt the VM, remove the hosts file entry, and restart chrome, then visit http://vvv.dev?

ERR_ICANN_NAME_COLLISION

I did `vagrant halt` and restarted chrome.   
Not sure what you mean by `remove the hosts file entry`.  There are no entries in /etc/hosts.

**Comment by tomjn** [comment]
If you're getting a name collision error in Chrome, and VVV is turned off, hosts are clear, then this can't be a VVV issue. You should be seeing something about being unable to resolve the domain, not a collision. There's something else going on here, unrelated to VVV

Some questions:
 - Has VVV or any vagrant based project ever worked on your system in the past
 - Does specifying a site with a hostname that isn't .dev work?
 - Do .dev domains work in other non-vagrant non-VVV projects
 - Does anybody else on your network use VVV
 - Do you have any other local environments such as WAMP, or copies of VVV?

**Comment by shanebp** [comment]
>Has VVV or any vagrant based project ever worked on your system in the past

No, never tried it before. 

>Does specifying a site with a hostname that isn't .dev work?

No.

>Does anybody else on your network use VVV

No, not networked. 

>Do .dev domains work in other non-vagrant non-VVV projects
>Do you have any other local environments such as WAMP, or copies of VVV?

To ensure that I could use localhost on this new Windows 10 computer, 
I installed DesktopServer and it loads `http://tester.dev/` without any issues in any browser and thru the firewall and antivirus programs.  

So there is a issue somehow related to VVV.   

Perhaps that it's installed on E:  rather than C: like  DesktopServer - but I thought that shouldn't matter when running a virtual box.

**Comment by rmurillo21** [comment]
Try a sanity check please?  Please post your entire Windows hosts file, *after* a full provision. Use `vagrant up--provision`.  That will run all the provisioners.

You Windows host file is located at \windows\System32\drivers\etc\hosts

For reference, it should look something like this:

```
C:\Users\xxx>cat \windows\System32\drivers\etc\hosts
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost

192.168.50.4  vvv  # VAGRANT: 909b945f972e394d3a9494b1303b1f7d (default) / 2825b7b9-ff66-4226-9d59-1f8f5e7d6967
192.168.50.4  vvv.dev  # VAGRANT: 909b945f972e394d3a9494b1303b1f7d (default) / 2825b7b9-ff66-4226-9d59-1f8f5e7d6967
192.168.50.4  local.wordpress.dev  # VAGRANT: 909b945f972e394d3a9494b1303b1f7d (default) / 2825b7b9-ff66-4226-9d59-1f8f5e7d6967
192.168.50.4  src.wordpress-develop.dev  # VAGRANT: 909b945f972e394d3a9494b1303b1f7d (default) / 2825b7b9-ff66-4226-9d59-1f8f5e7d6967
192.168.50.4  build.wordpress-develop.dev  # VAGRANT: 909b945f972e394d3a9494b1303b1f7d (default) / 2825b7b9-ff66-4226-9d59-1f8f5e7d6967
```

As a second test, please add 

`1270.0.01 test123.test`

to  \windows\System32\drivers\etc\hosts, save it, then try to ping that host name from the command line. Please paste that output here. Thanks

**Comment by rmurillo21** [comment]
It would be useful to also see the full provision log in a Gist. The last log https://gist.github.com/shanebp/7a5b3eff4524c97d9494f2633d420d36 was not a full provision run.

**Comment by shanebp** [comment]
The hosts file is empty after I do `E:\VVV>vagrant up --provision`

I added this to hosts `1270.0.01 test123.test`  and then... 
```
vagrant@precise32:~$ ping test123.test
ping: unknown host test123.test
```

What you see in the gist log is _everything_ I see after doing `E:\VVV>vagrant up --provision`

**Comment by tomjn** [comment]
@shanebp can you do the ping from the host machine not the VM, we're trying to connect to the VM, if we need to run the command inside the VM we'll say so explicitly

As for your hosts, file, it should have entries, that it did not have entries and was empty, suggests that you have a permissions issue, or the hosts updater vagrant plugin is not installed correctly. There should have been at least localhost entries from Windows.

I'm also mindful that your `vagrant@precise32` is not what the VVV shell should look like, you should have an Ubuntu 14 base box e.g.:

```
❯ vagrant ssh


  __     ___     ___     __  ____    
  \ \   / \ \   / \ \   / / |___ \   
   \ \ / / \ \ / / \ \ / /    __) |  
    \ V /   \ V /   \ V /    / __/   
     \_/     \_/     \_/    |_____|  

  Varying Vagrant Vagrants 2.0.0

  Docs:       https://varyingvagrantvagrants.org/
  Contribute: https://github.com/varying-vagrant-vagrants/vvv



Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-116-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Sep 22 16:39:17 UTC 2017

  System load:  0.0               Processes:           95
  Usage of /:   7.1% of 39.34GB   Users logged in:     0
  Memory usage: 38%               IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.50.4

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

197 packages can be updated.
85 updates are security updates.

New release '16.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


You have new mail.
Last login: Fri Sep 22 16:39:19 2017 from 10.0.2.2
vagrant@vvv:~$ 
```

**Comment by tomjn** [comment]
Also, can you clear chromes host cache, destroy the box via `vagrant destroy` in an admin shell, and start fresh using the `develop` branch from a clean slate?

**Comment by rmurillo21** [comment]
Sorry for the typo re `127.0.0.1 test123.test` 127.0.0.1 is the correct value.  Update that and ping from the Windows host (_not_ from the the VM)

**Comment by shanebp** [comment]
Thanks to both of you for your input and persistence.

But if I run the command window as administrator and do `❯ vagrant ssh` and end up at `vagrant@precise32`  then perhaps a more effective step would be to uninstall everything and start from scratch ?

**Comment by rmurillo21** [comment]
You bet @shanebp happy to help.  I would go ahead and follow @tomjn suggestion here https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1284#issuecomment-331607323

**Comment by shanebp** [comment]
I reinstalled vagrants and then installed VVV on C:\vagrant-local
**Everything works now**, in all browsers, dashboard, bundled WP sites.  
`vagrant ssh` sends me to `vagrant@vvv:~$`

So trying to run VVV from a partition on the drive was at least part of the problem. 
Or running it from a dir that was not called vagrant-local
Or... 

Thanks again to both of you... Time to start learning how to actually use VVV.

**Comment by rmurillo21** [comment]
Good news @shanebp, thanks for the update. Let us know if you have any questions.
