### ISSUE TITLE
Remove develop branch on varyingvagrantvagrants.org repository

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1286]
There's not really another place to have this conversation. 😆 

@LoreleiAurora @tomjn - What do you think about removing the `develop` branch from the [docs repo](https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org) so that PR's can be made against master and then deployed *much* easier?

**Comment by LoreleiAurora** [comment]
Im in agreement with this as we are not deploying the develop branch anywhere.

**Comment by tomjn** [comment]
Sounds good to me, lets make it so

**Comment by jeremyfelt** [comment]
This was done the other day. 👍
