### ISSUE TITLE
`.dev` domain will be redirect to HTTPs on next version of Chrome

### ISSUE THREAD

**Issue by miya0001** [Varying-Vagrant-Vagrants/VVV#1288]
Chrome is going to force all domains ending on .dev (and .foo) to be redirected to HTTPs via a preloaded HTTP Strict Transport Security (HSTS) header.

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

Should we change the default domain?
I have no idea which domain is better for us for now.

Actually, I am developing an another Vagrant based environment.
I want to follow the domain which is decided by this project. :)

**Comment by tomjn** [comment]
Closing as duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583

**Comment by Luc45** [comment]
According to this article, .test is a reserved TLD suited for development:
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
