### ISSUE TITLE
docs > adding-a-new-site > 403 on links

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#1291]
https://develop.varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/

All the links under _Add New Sites_ are 403.

I think they just need `.md` replaced with `/`

**Comment by jeremyfelt** [comment]
Looks like these are also double pre-pending `adding-a-new-site/` due to the relative link - `<a href="adding-a-new-site/changing-php-version.md">Changing a sites PHP Version</a></li>`

**Comment by tomjn** [comment]
Those are the `develop` docs, we removed the `develop` branch, so those are both out of date, and should have been removed

@jeremyfelt can you do the honours? Probably best to redirect to the main site, the links in question were removed with the switch to the new theme now that we have a sidebar nav for those things

**Comment by tomjn** [comment]
I'm going to close this out and create a new issue for removing https://develop.varyingvagrantvagrants.org

In the meantime, use https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/ the `master` branch is now the latest and greatest with a rolling release processs
