### ISSUE TITLE
.dev domain will require SSL.

### ISSUE THREAD

**Issue by renatonascalves** [Varying-Vagrant-Vagrants/VVV#1292]
This change will impact the vvv.dev url from VVV.

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by rmurillo21** [comment]
This is already being tracked:
https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default/pull/2
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583

**Comment by renatonascalves** [comment]
Good! Should have searched it first! :)
