### ISSUE TITLE
Lost my db

### ISSUE THREAD

**Issue by birdm99** [Varying-Vagrant-Vagrants/VVV#1294]
I have huge problem with my wordpress installation. When I finished work few days ago I used `vagrant halt`. I try to rerun vagrant with `vagrant up` totay.  When I tried to login to my wordpress site something strange happend. It didn't  show me my website, but it showed wordpress isntallation screen. I've check file structure in wordpress-default directory and everything seems to be ok.  I've also checked mysql - DB for wordpress-default is empty!! Is it possible to recover my previous DB??

**Comment by LoreleiAurora** [comment]
do you have vagrant triggers installed?

**Comment by birdm99** [comment]
Yes. and I'm pretty sure that it made a backup sql in backup folder. Unfortunately it weights only 1 kb, so it's empty. I think that I run `vagrant halt` when I saw that the wp site is empty and it triggered the backup, but the site was already empty....

**Comment by tomjn** [comment]
Some questions:

 - Did you `vagrant halt`, or `vagrant halt --force`?
 - At any point was there an unplanned halt such as when battery reaches 5% and it automatically stops, or loss of power, BSOD, kernel panic etc?
 - Any uses of `vagrant destroy`, or reinstallation of Virtualbox?
 - Do you have a log of the provisioning from when you ran `vagrant up`? ( specifically from when you ran it today and saw the install screen, running it again won't be useful )
 - Do other sites on your install have the same issue?
 - Have you recently updated from VVV 1 to VVV 2?
 - What are your versions for Vagrant and Virtualbox?
 - Which OS and which version?
 - Are you running the `master` branch or the `develop` branch of VVV and are you up to date?
 - Have there been any recent changes to `vvv-custom.yml` or `vvv-config.yml`?

**Comment by birdm99** [comment]
Hello
Thanks for replay
I used `vagrant halt`. I haven't update neither Vagrant nor Vbox. I'm using MacOs 10.12. There wasn't any power losses or anything like this.  I assume that my problems was caused by my mistake. I changed init-custom.sql. It seems to be ok, but after restarting vagrant I've noticed changes and my mistake. I panicked and restart vagrant(that triggered backup overwrite) Unfortunately I'm almost sure it's too late to recover my db.

**Comment by tomjn** [comment]
I doubt you can retrieve your database unless you've made backups. Keep in mind that you want your local dev environment to be such that you can tear it down and build it back up at a moments notice, and it shouldn't contain mission critical data
