### ISSUE TITLE
Vagrant SSH doesn not contain folder structure 

### ISSUE THREAD

**Issue by designlobby** [Varying-Vagrant-Vagrants/VVV#1296]
I'm a novice at SSH stuff, so apologies if this is something dead simple that I've missed!

I have VVV 2.0.0 installed in `~/sites/vvv`. Everything working fine but I haven't ssh'd into the server for a while, until today.

## Expected Behavior

Running `vagrant ssh` to navigate vvv/www/{my sites}. 

## Current Behavior

Running `vagrant ssh` connects successfully, but `ls` shows only 2 items, "bin" and "google.com". There are no other folders to access.

I have tried running `vagrant halt;vagrant up --provision` but there was no change. I have also created a fresh install of VVV in a new location but get the same results. 

## Possible Solution

I recently created new SSH key on my mac to connect to github. Not sure if this is a problem!

Also, I have updated Virtualbox and on `vagrant up` I see a comment about GuestAdditions that reads:

```

==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.28
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.1.28 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.28
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1

```

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 2.0.0
* VM Provider name: VirtualBox
* VM Provider version: 5.1
* Operating System and version: OS Sierra

**Comment by designlobby** [comment]
Update - I fixed the different GuestAdditions version using the plugin https://github.com/dotless-de/vagrant-vbguest.

No longer getting the notice, but no change to when I run `vagrant ssh`. Still only the 2 folders, bin and google.com.

**Comment by LoreleiAurora** [comment]
The guest additions issue should be safely ignored.
The files live inside the vm at `/srv/www`

**Comment by designlobby** [comment]
But I'm unsure how to reach `/srv/www`. I don't see those folders when I run `vagrant ssh`, only `bin` and `google.com`?

**Comment by LoreleiAurora** [comment]
When you run `vagrant ssh` you are dropped into the server at `/home/vagrant`, so to get to the sites directory you would `cd /srv/www`

**Comment by designlobby** [comment]
There is no `/svr` folder for me to cd into, let alone `/srv/www`.  I only see `bin` and `google.com`?

**Comment by designlobby** [comment]
Just to be clear:

1) I go to `cd ~/sites/vvv && vagrant up` - Vagrant boots up.
2) I run `vagrant ssh && ls`
3) Terminal lists 2 folders: `bin` and `google.com`

I don't see any `/svr` folder at all. If I list the folders inside bin there is `db_backup`, `develop_git`, `vagrant_destroy`, `vagrant_suspend`, `xdebug_off`, `db_restore`, `makepot`, `vagrant_halt`, `vagrant_up`, `xdebug_on`.

Everything else is working, I can get my sites up, access vvv.dev, etc.

**Comment by LoreleiAurora** [comment]
That is because `vagrant ssh` drops you into the `/home/vagrant` directory.

- You are in `/home/vagrant` on the VM. You can see this by running `echo $PWD`
- `ls` is an alias for `ls $PWD` so lists the current directory
- `ls /` will list all the directories in the root of the VM

So to clarify
1. Run `vagrant ssh`
2. Run `cd /srv/www` to navigate to the sites directory.

**Comment by designlobby** [comment]
Bah, I knew it was me getting confused, I didn't realise what I was looking at. This totally makes sense:

> ls / will list all the directories in the root of the VM

Thank you so much for helping me!
