### ISSUE TITLE
Remove https://develop.varyingvagrantvagrants.org

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1297]
Now that we've removed the `develop` branch of the docs repo, we should remove https://develop.varyingvagrantvagrants.org or redirect it to https://varyingvagrantvagrants.org

**Comment by LoreleiAurora** [comment]
I didn't even realise that still existed

**Comment by jeremyfelt** [comment]
Good catch, removed!
