### ISSUE TITLE
Beginner question with regards to replicating production environment

### ISSUE THREAD

**Issue by vinodMS** [Varying-Vagrant-Vagrants/VVV#1299]
## Question
I've been reading the documentation [here](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) and came across the section where it explains the steps that should be taken to copy an existing site to the development environment. 

> If you have an existing site you want to work with, you will be able to manually copy the site files into the public_html or equivalent subdirectory created when the site is provisioned.

I do not want to do this and would like to automate this step.

> As an alternative, rather than manually copying files into the folder, copy them into a git repository, and use the repo key to tell VVV where to find it.

Does this mean that I should have the entire WP instance copied into GIT? It's not very clear what's meant above. 
The ideal scenario I have in mind is that vagrant takes care of,

1. Installing WP from scratch (same version as production)
2. Installing all the themes and plugins (based on the config)
3. Finally, use the GIT repository to complete the installation. Git should contain any child theme code and custom developed plugins. 

Have I got it right?

Finally, am I right to assume that the production database should be manually exported and imported into the new development site?

**Comment by tomjn** [comment]
> Installing WP from scratch (same version as production)

This is what the provisioner script `vvv-init.sh` does in all the bundled sites, see:

 - https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default/blob/master/provision/vvv-init.sh
 - https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-init.sh
 - https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop/blob/master/provision/vvv-init.sh

I recommend you use the custom-site as a basis, as it's intended to replace the other two in the longrun

> Installing all the themes and plugins (based on the config)

You can do this via WP CLI in `vvv-init.sh`

> Finally, use the GIT repository to complete the installation. Git should contain any child theme code and custom developed plugins.

So there's a bit of a misunderstanding here about how VVV sets up a site and what it expects.

When you set the repo key, as the default sites do, VVV checks out that git repository into the relevant folder, then looks inside it for the provisioner. It's not that it clones the repo inside the site, it's that the repo **IS** the site in a very literal sense.

Take a look at the `custom-site-template` repo, if you add a new site to your config named `apple` and use that repo, then the first thing VVV does is check if the `www/apple` folder exists, and if it doesn't it does a `git clone`  and clones the repo specified to the `www/apple` folder. So the git repo you specify is the initial starting point VVV uses. Then it does the provisioner stuff.

So you might fork the `custom-site-template` repo and put all the WP files into git, and then tell VVV to create a new site using that fork, and hey presto, it will clone that repo and you'll have a folder with all of that stuff in it, and then it'll run `provision/vvv-init.sh`, where you can do whatever you like.

That might be installing a theme, updating a plugin, doing another git clone into a subfolder, that's entirely up to you and your skills at shell scripting.

> I do not want to do this and would like to automate this step.

Great, your `vvv-init.sh` could even FTP in and pull them down if you're happy to write that code, but I personally wouldn't recommend doing that as it sounds slow, and your code should be under version control anyway

> Finally, am I right to assume that the production database should be manually exported and imported into the new development site?

Yes, VVV has no special magic voodoo here, you can roll out whatever system you want here.
