### ISSUE TITLE
403 error on built-in-wp-installs.md

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1302]
In the installation documentation:
https://varyingvagrantvagrants.org/docs/en-US/installation/

Step 8 is:
Visit any of the built in WordPress sites or the VVV Dashboard at http://vvv.dev

The link for "built in WordPress sites" is
https://varyingvagrantvagrants.org/docs/en-US/installation/built-in-wp-installs.md

Which generates this error:
```
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: 62996B9946A0D0E3
HostId: X/MpN6neIYR3SKRmD5Ct5E6gB6FX7aAIwSSZXSbtTJBEPxrVqtfDIEFT47lIbVocslHlggY0zeg=
```

**Comment by tomjn** [comment]
This is usually caused by Jekyll being super fussy over things like trailing slashes

**Comment by tomjn** [comment]
Fix in https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/29

**Comment by paulschreiber** [comment]
This is still broken. Has the change not deployed yet?

**Comment by tomjn** [comment]
It would appear the change did not correct the issue as anticipated. This is clear from the issue being present along with changes in the PR that a quick check would reveal.

Though I would add, it would be **enormously** helpful if you could help identify the cause. The rules Jekyll is following are not 100% clear, hence it's difficult to know why it's broken. Especially when it's broken on the site but not when Jekyll runs locally.

**Comment by paulschreiber** [comment]
I have never use Jekyll, and don't have access to your deploy server, so I can't assist with debugging.

**Comment by tomjn** [comment]
It's all there in the repo in the travis build:

 - https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org
 - https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/blob/master/.travis.yml

That repo and travis CI file should be enough to replicate and test, I don't have direct access to the servers myself, only @jeremyfelt does, but it's on a continuous deployment process
