### ISSUE TITLE
Config file access

### ISSUE THREAD

**Issue by arkytn** [Varying-Vagrant-Vagrants/VVV#1310]
Not sure if I understand the design here. I need to change the php.ini to change timeouts, memory etc. on a windows install.  phpinfo shows the primary php.ini is at

/etc/php/7.0/fpm/php.ini

which is fine but not editable from windows. There are ini and conf files in the /config/ directory which is reachable from windows. But changing them doesn't do anything for sites. Also tried a local php.ini in the htdocs for a site. Again no effect. I've done vagrant reload and no help.

What should be the proper way to change configs? I can ssh to etc, it's just a pain and I really think should be editable from windows.  Why a php-custom.ini if it doesn't do anything?

**Comment by LoreleiAurora** [comment]
You need to edit the php.ini in the config directory then reprovision

**Comment by arkytn** [comment]
Ahh. That's the incantation. Thanks.
