### ISSUE TITLE
Virtual Machine Terminates Unexpectedly

### ISSUE THREAD

**Issue by ClintonGallagher** [Varying-Vagrant-Vagrants/VVV#1315]
## Expected Behavior

vagrant up 853c6df usually starts and allows requests to load WordPress website

##Error Message
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["startvm", "cf080895-f04b-419c-9385-31d73fe9a1d6", "--type", "headless"]

## Current Behavior

vagrant up does not load or run the virtual machine after upgrading VM VirtualBox from v5.1.x to v5.2.x on Windows 10 Aniiversary Edition recently upgraded by Microsoft with latest updates

## Possible Solution

Web search has provided no solution understood.
Have tried uninstalling and reinstalling several different versions of VirtualBox to no avail

## Steps to Reproduce (for bugs)

vagrant up 853c6df

## Context

VBoxHardening.log is indecipherable leaving no idea how to proceed to restore

## Your Environment

* VVV version: 1.12
* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22 r115126 (Qt5.6.2)
* Operating System and version: x64 Windows 10 Pro Version: 1709 OS Build: 16299.19

**Comment by andyspw** [comment]
@ClintonGallagher 
I had the similar problem. 
After VirtualBox update ( from 5.1.22 >> 5.1.30 ) everything works fine. 

My Environment:
- VVV 2.0.0
- Vagrant 2.0.0

According to these tickets there were some problems with VirtualBox 5.1.22 and latest Windows updates:
- https://www.virtualbox.org/ticket/16890
- https://www.virtualbox.org/ticket/16892

**Comment by ClintonGallagher** [comment]
You da' man Andy. 5.1.3 is the magic number.

Updating VirtualBox is how I got into trouble in the first place. All be advised when updating to VirtualBox-5.1.8-111374-Win everything can go boom.
