### ISSUE TITLE
PharData fails, generates warnings when provisioning new sites

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1317]
PharData fails and generates warnings when provision new sites

```
==> default: Downloading WordPress 4.8.2 (en_US)...
==> default: Using cached file '/home/vagrant/.wp-cli/cache/core/wordpress-4.8.2-en_US.tar.gz'...
==> default: Warning: PharData failed, falling back to 'tar gz' (unable to decompress gzipped phar archive "/home/vagrant/.wp-cli/cache/core/wordpress-4.8.2-en_US.tar.gz" to temporary file)
```

## Expected Behavior
No warnings or errors.

## Current Behavior
Warning: PharData failed, falling back to 'tar gz'...

## Steps to Reproduce (for bugs)
1. Add site to `vvv-custom.yml`
2. `vagrant up --provision`

## Your Environment
* VVV version: 2.0.0
* Vagrant version: 2.0.0
* VM Provider name: VirtualBox
* VM Provider version: 5.1.28
* Operating System and version: macOS 10.12.6

**Comment by tomjn** [comment]
By Vagrant 2.0, are you referring to `master` or `develop`?

**Comment by paulschreiber** [comment]
Are you asking about Vagrant or VVV?

**Comment by tomjn** [comment]
VVV 2 sorry

**Comment by paulschreiber** [comment]
I'm using master for VVV.

**Comment by tomjn** [comment]
I would **strongly** recommend using `develop`, it has a huge number of fixes ( releasing 2.1 has been very heavily delayed for IRL reasons ).

Also keep in mind that for any bugs that happen on `master`, we need to know if they happen on `develop`

**Comment by paulschreiber** [comment]
I repeated this with VVV 2.1.0-develop. I created a new site in `vvv-custom.yml` and ran `vagrant up --provision`.

I did not see the problem:
```
==> default: Downloading WordPress...
==> default: Creating directory '/srv/www/extrasite/public_html/'.
==> default: Downloading WordPress 4.8.3 (en_US)...
==> default: md5 hash verified: 4a8c83d449351c76a8d5bea7d42710a2
==> default: Success: WordPress downloaded.
==> default: Configuring WordPress Stable...
==> default: Installing WordPress Stable...
```

**Comment by tomjn** [comment]
Awesome, in that case I'm going to close, if anybody else encounters this on the `develop` branch please reopen
