### ISSUE TITLE
When provisioning new site, composer is run as root

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1320]
When provisioning a new site with VVV 2.1.0-develop, composer is run as root, generating many errors:
```
==> default: ack-grep already installed
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Updating Composer...
==> default: You are already using composer version 1.5.2 (stable channel).
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: ./composer.json has been updated
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: ./composer.json has been updated
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: ./composer.json has been updated
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: ./composer.json has been updated
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Changed current directory to /usr/local/src/composer
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Loading composer repositories with package information
==> default: Updating dependencies (including require-dev)
==> default: Nothing to install or update
==> default: Generating autoload files
==> default: Updating Grunt CLI
```

Full log:
https://gist.github.com/paulschreiber/9c9cefbbf9cd59ccd92f4f4584762bc0

## Expected Behavior
No errors.

## Current Behavior
Many errors.

## Steps to Reproduce (for bugs)
1. Add site to `vvv-custom.yml`
2. Run `vagrant up --provision`

## Your Environment
* VVV version: 2.1.0
* Vagrant version: 2.0.0
* VM Provider name: VirtualBox
* VM Provider version: 5.1.30
* Operating System and version: macOS 10.12.6

**Comment by dingo-d** [comment]
I think those are warnings since once you provision vagrant, it works fine (at least for me).

**Comment by paulschreiber** [comment]
Yes, they are warnings (in the sense they don't prevent the commands from succeeding).

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1155 and https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1156 already fix this, but they haven't been merged for good reasons

SImply put, they would break all existing VVV installs. Until a mechanism for either converting existing users over, or running as root for existing and non-root for new users, they can't be merged. Just changing the user it runs under isn't enough
