### ISSUE TITLE
"Software Requirements" page is missing from docs

### ISSUE THREAD

**Issue by johnbillion** [Varying-Vagrant-Vagrants/VVV#1324]
When viewing [the Installation page on the docs website](https://varyingvagrantvagrants.org/docs/en-US/installation/), clicking "Software Requirements" results in a 403 error.

**Comment by tomjn** [comment]
related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1325

**Comment by tomjn** [comment]
So this is still an issue after a fix that should have corrected it =/ Not sure why the page just doesn't exist

On the other hand a lot of other things got fixed!

**Comment by dfinster** [comment]
Fortunately [Google cache](https://webcache.googleusercontent.com/search?q=cache:kkviOWa51EoJ:https://varyingvagrantvagrants.org/docs/en-US/installation/+&cd=1&hl=en&ct=clnk&gl=us) still has the page so I was able to move forward with a new install.

**Comment by tomjn** [comment]
For reference, the docs are markdown files available at https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org

**Comment by jeremyfelt** [comment]
It looks like https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/32 took care of it. Thanks all!
