### ISSUE TITLE
Fix command for running vagrant with verbose, debugging output

### ISSUE THREAD

**Issue by skorasaurus** [Varying-Vagrant-Vagrants/VVV#1330]
Hi, 

In the [troubleshooting guide; ](https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/blob/c3fed710b5580df320cec563c1418e1d756ce7d3/docs/en-US/troubleshooting.md ), running ```vagrant up --provision --verbose | vvv.log```  returns a syntax error (```An invalid option was specified. The help for this command
is available below.```) 
I couldn't find a verbose argument on [vagrant's website](https://www.vagrantup.com/docs/other/debugging.html); but there is  ```--debug```. 
So the command would be  ```vagrant up --provision --debug | tee vvv.log```
(I also included tee, which is a standard unix tool to read input and store it files; it's in coreutils and in most unix installs](http://man7.org/linux/man-pages/man1/tee.1.html)).

**Comment by skorasaurus** [comment]
I compared the output results between 
(I didn't include provision because I don't want to reprovision them ): 
`vagrant up --debug | tee 2vvv.log` and 
`vagrant up --debug &> vvv.log`. The latter, recommended on https://www.vagrantup.com/docs/other/debugging.html ; gave about 10x larger file size than using tee and included a lot more information on my vagrant configuration; so I made a PR using that - https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/41

**Comment by tomjn** [comment]
Awesome :), i see your PR got merged so I'm going to close this
