### ISSUE TITLE
Display available updates to VVV in dashboard

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1333]
It would be cool if the dashboard at `vvv.test` periodically checked for updates.

* If `master` or a versioned release, it could check for the latest tag.
* If `develop`, it could display recent commits or number of commits behind.

I haven't really thought through where to cache the data in between checks. `memcached` is running by default, so it could work. We can probably also rely on MySQL.

**Comment by tomjn** [comment]
I did consider having the splash screen ASCII art prompt you if your git repo was behind by several commits to do a `git pull`

**Comment by jeremyfelt** [comment]
@tomjn I like that idea - Is there a way to store that data without making a remote request to GitHub each time? We could probably also combine in via the dashboard into a file that gets stored and then read for that purpose.

**Comment by tomjn** [comment]
git can figure it out after a fetch, I say we figure it out on provision, or poke if the person hasn't done a `git pull` in a while, no need to be precise

**Comment by tomjn** [comment]
We store the version VVV was provisioned with in `/vagrant/version`, comparing that against the list of releases in the GH API should tell us if we're up to date or not

**Comment by Mte90** [comment]
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1717

**Comment by tomjn** [comment]
closing in favour of #1717
