### ISSUE TITLE
Autorun xDebug on vagrant up

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1340]
## Expected Behavior
* Parameter to enable this behaviour
* xdebug_on is executed at the end of vagrant up

## Current Behavior
* run xdebug_on manually

## Your Environment
* VVV version: 2.1.0
* VVV Git Branch: develop
* Vagrant version: 2.0.1
* VM Provider name: Virtualbox
* VM Provider version: 5.2
* Operating System and version: Debian Sid

**Comment by tomjn** [comment]
I'm unsure what your exact steps are so I can reproduce, but:

 - `vagrant up` to start the VM
 - `vagrant ssh` to enter it
 - `xdebug_on` to turn on XDebug
 - `xdebug_off` to turn off XDebug

Are you having different behaviour to the above? Or is it that XDebug isn't on by default? Note that turning it on by default causes performance problems for `composer`, and provisioning would take a lot more time

**Comment by Mte90** [comment]
Yes this is my workflow, I don't know the process on startup of the machine but maybe on provision can be executed the script to turn off xdebug and after start again.

**Comment by tomjn** [comment]
hmmm so I'm still trying to piece together exactly what the request is, is it to:

 - have xdebug turned on by default when a VM starts?
 - Have `xdebug_on` turn it on permanently, and `xdebug_off` turn it off permanently?

If I understand correctly, you'd prefer xdebug was always turned on and never had to do that manually

If so, have you considered putting `xdebug_on` inside a vagrant up custom script at `config/homebin/vagrant_up_custom`?

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/vagrant_up

**Comment by tomjn** [comment]
Also **Todo:** document vagrant up custom

**Comment by Mte90** [comment]
I didn't know about this script!
There is a way to check from bash if is running provision? In that way I can do that check to disable xDebug :-)

**Comment by tomjn** [comment]
hmm I'm not sure why you would turn off xdebug to turn it on again, you can probably check via `phpenmod` or by running a piece of PHP code that returns on a check

I've also been made aware by @LoreleiAurora that when you turn xdebug on it stays on or off, it persists until the next reprovision

**Comment by Mte90** [comment]
There is a script like for `vagrant up` to run before `vagrant provision` and after? In that way I can disable xdebug and enable later.

**Comment by Mte90** [comment]
Nevermind, looking on `vagrantfile` I found that is possible to have `provision-custom.sh` and I added:
```
#!/bin/bash
xdebug_off
provision.sh
xdebug_on
```
