### ISSUE TITLE
Latest installed PHP version is also the default CLI version

### ISSUE THREAD

**Issue by ocean90** [Varying-Vagrant-Vagrants/VVV#1342]
While working on https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1263 I noticed that after PHP 7.2 was provisioned the CLI version was also updated to use PHP 7.2.

```
root@vvv:~# php -v
PHP 7.2.0RC5 (cli) (built: Oct 27 2017 14:07:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0RC5, Copyright (c) 1999-2017, by Zend Technologies
```

Output of `update-alternatives`:
```
root@vvv:~# update-alternatives --config php
There are 4 choices for the alternative php (providing /usr/bin/php).

  Selection    Path             Priority   Status
------------------------------------------------------------
* 0            /usr/bin/php7.2   72        auto mode
  1            /usr/bin/php5.6   56        manual mode
  2            /usr/bin/php7.0   70        manual mode
  3            /usr/bin/php7.1   71        manual mode
  4            /usr/bin/php7.2   72        manual mode
```

## Expected Behavior
Not 100% sure what the expected behavior is. Looking at [`services_restart()`](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/5d6cc50c7cd2c8e44ff9118c981283e9ac85fc1c/provision/provision.sh#L570-L593) it seems like it should stick to PHP 7.0, VVV's default version (Related: #1287).

## Current Behavior
`phpenmod mcrypt` produces a warning `services_restart()`:
```
root@vvv:~# phpenmod mcrypt
WARNING: Module mcrypt ini file doesn't exist under /etc/php/7.2/mods-available
WARNING: Module mcrypt ini file doesn't exist under /etc/php/7.2/mods-available
```

This is because `phpenmod` enables the module for **all** versions unless a version parameter is provided like `phpenmod -v 70 mcrypt`.

## Possible Solution
a) Enable the modules only for VVV's default version
b) Pipe warnings into `/dev/null`
c) Don't let the core utilities change the CLI version

For back-compat we probably should do b) and c).

## Steps to Reproduce (for bugs)
1. SSH into your box and check the PHP version with `php --version`
2. Checkout https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1341 and extend your `vvv-custom.yml` with
```yml
utilities:
  core:
    - php72

utility-sources:
  core:
    repo: https://github.com/ocean90/vvv-utilities.git
    branch: feature/php72
```
3. Run `vagrant reload --provision` and make sure that everything gets installed
4. Run `vagrant reload --provision` again and watch for the "Restart services..." step
    <img width="726" alt="warnings" src="https://user-images.githubusercontent.com/617637/32689158-69652cd4-c6df-11e7-8bd8-339e2b8504f2.png">
5. SSH into your box and check the PHP version with `php --version`

**Comment by tomjn** [comment]
@LoreleiAurora can you take a look at this?

**Comment by tomjn** [comment]
7.2 is now both the latest and the default
