### ISSUE TITLE
meta environment hosts undefined index

### ISSUE THREAD

**Issue by afercia** [Varying-Vagrant-Vagrants/VVV#1347]
Just installed a new VVV, we're close to WordCamp Milano so I've used the script to generate the USB sticks to distribute during the contributor day (https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator)

Seems everything works fine, just one small thing: I get a generated `vvv-custom.yml` where the meta environment is uncommented and it lacks the hosts:
```
  wordpress-meta-environment:
    repo: https://github.com/WordPress/meta-environment.git
```

This results in an undefined index notice in the `/srv/www/default/index.php` when visiting vvv.test

![screen shot 2017-11-12 at 19 18 39](https://user-images.githubusercontent.com/1682452/32702202-873e63b0-c7e3-11e7-889a-2df34d2ef308.png)

**Comment by ocean90** [comment]
Related: https://github.com/WordPress/meta-environment/issues/99
