### ISSUE TITLE
Default gateway not present when using both private and public network

### ISSUE THREAD

**Issue by swashata** [Varying-Vagrant-Vagrants/VVV#1350]
I need to give my VVV network access so that I can connect browserSync to other devices. For this I have created a `public_network` in the `Customfile`.

```ruby
config.vm.network :public_network
```

While this works, around 50% of the time, the VM would have no internet access because no default gateway is actually configured when both `private_network` and `public_network` is enabled.

Do note that I have a OpenWRT router, so I have set a static lease IP for the `public_network` and have the router `/etc/hosts` updated to point VVV domains to the leased IP.

## Expected Behavior

When both `private_network` and `public_network` is configured, the VM should use `public_network` gateway as the default gateway or the `private_network`, but the default gateway should at least be configured.

## Current Behavior

In the VM, no gateway is actually configured, which leads to some weird behavior. 50% of the time, from the VM, I am able to ping outside websites, but for the rest of the time, I am not.

## Possible Solution

So in my `Customfile`, I have the following inline shell, which would configure the network.

```ruby
# Vagrant Custom File
# Enable Public Network
config.vm.network :public_network

# Provision to use eth2 as default gateway
config.vm.provision :shell, inline: "echo 'Configuring Network Gateway'", run: "always"
config.vm.provision :shell, inline: "route del default gw 10.0.2.2 eth0 2>/dev/null || true", run: "always"
config.vm.provision :shell, inline: "route add default gw 192.168.1.1 eth2 2>/dev/null || true", run: "always"
config.vm.provision :shell, inline: "echo 'Network Gateway Configured'", run: "always"
```

This creates a default gateway and now the VM is always able to connect to the internet.

If this is the right way to do stuff, then I think a documentation would be nice. Let me know if this is correct, and I will send in a pull with updated docs.

## Steps to Reproduce (for bugs)

1. Install VVV `develop` branch.
2. Create a `Customfile` and put just `config.vm.network :public_network`.
3. Start the VM.
4. See that the gateway is not present.
```bash
ip route | grep default
```
doesn't show any default gateway.

## Context

The VM needs to stay connected to the internet because of a lot of things. Like WP update, developing some stuff which relies on `cURL`, `wp_remote` etc.

## Your Environment

* VVV version: 2.1.0-develop at 39450a478b1d2b66295402b3172c8f2bcbfd798b
* VVV Git Branch: `develop`
* Vagrant version: Vagrant 2.0.0
* VM Provider name: VirtualBox
* VM Provider version: 5.1.28 r117968
* Operating System and version: macOS High Sierra `10.13.1`

**Comment by tomjn** [comment]
I'm not surprised you ran into issues, but instead of running those shell commands from the vagrant custom file, I'd have suggested using a VVV utility.

However since you're already doing custom Vagrant things it doesn't hurt. I don't think this kind of behaviour is something we'd officially support, especially since we'd need to now the layout of the connected network, which may not have a default gateway of `192.168.1.1` as your code suggests

**Comment by tomjn** [comment]
@LoreleiAurora thoughts?

**Comment by swashata** [comment]
@tomjn understood. May I ask what VVV utility you were suggesting?

**Comment by tomjn** [comment]
@swashata I didn't have an existing utility in mind, a Utility is just a git repo with folders containing `provisioner.sh` files. See the docs or the core utility for examples

**Comment by swashata** [comment]
@tomjn Understood. For now (as you've mentioned) I will simply go with the Customfile method. It works good.
