### ISSUE TITLE
Auto create vvv-custom.yml or abandon it

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1356]
Right now people get a `vvv-config.yml` and they're supposed to copy it to `vvv-custom.yml` so that updating VVV doesn't overwrite it. A lot of people aren't though

I present these options for consideration:

 - create a `vvv-config-default.yml` in the core provisioner folder so that people can continue using `vvv-config.yml`, and auto-copy the file in if it's missing rather than reading the default
 - Auto create `vvv-custom.yml`

We'll need to support `vvv-custom.yml` going forwards, and we can probably put a brief note in the dashboard with the scream emoji

@LoreleiAurora @jeremyfelt thoughts?

**Comment by Mte90** [comment]
I think that the second approach is better, maybe with a skeleton and comments like for the resources part.
