### ISSUE TITLE
Broken Dashboard PNG logos

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1358]
For some reason the logos in the dashboard are mangled in git, we should set them again so they render correctly

**Comment by kstefanini** [comment]
```
<img src="//vvv.test/dashboard/vvv-tight.png"/>
```
See : https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/www/default/index.php#L32

**Comment by tomjn** [comment]
Awesome catch on the CRLF conversion
