### ISSUE TITLE
Where to post general VVV support questions?

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1359]
Sorry to clutter your Issues.  But the [VVV Troubleshooting page](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/) indicates I can post here if I "run into trouble."  I am indeed experiencing trouble.  Specifically, I am trying to get VVV up and running on my system, but encountering error messages that I cannot decipher.  Is this the right place to ask about those error messages?  If not, can you point me to a better place?

In the past I've tried posting VVV questions to the [Vagrant Google Group](https://groups.google.com/forum/#!forum/vagrant-up), the [Vagrant subreddit](https://www.reddit.com/r/vagrant/) and the [WordPress subreddit](https://www.reddit.com/r/Wordpress/).  But I did not receive answers from any of them.

Thanks very much in advance.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version: 
* VVV Git Branch: 
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by cfoellmann** [comment]
Yes, for now the Github issues is the best (and maybe only) place to get help for VVV.

We try to help as much as we can.
Just try to post detailed info about what is not working and what error messages you get.

**Comment by cagross** [comment]
Great, thanks for that.  Let's mark this particular issue resolved then.  Over the next few days I'll assemble all the relevant information and post a new issue here.

Thanks.

**Comment by cfoellmann** [comment]
@cagross I am not sure you can add tags. Just try to fill as many categories in the issue template

**Comment by cagross** [comment]
Gotcha--will do.

**Comment by tomjn** [comment]
Here is the place for VVV support, bug reports, feature requests, and questions, keep in mind that if you're doing something unusual and complex with Vagrant we may not be able to help you ( e.g. trying out different box provisioners such as xhyve instead of Virtualbox )
