### ISSUE TITLE
Provisioning not successful

### ISSUE THREAD

**Issue by jimlongo56** [Varying-Vagrant-Vagrants/VVV#1362]
Installed the latest version of VVV from github into ~/VVV

Made and edited the file vvv-custom.yml
```
---

sites:

  smalltalks:
    repo: https://github.com/jimlongo56/smalltalks.git
    hosts:
      - smalltalks.dev
```

made the directory VVV/www/smalltalks
made the directory VVV/www/smalltalks/provision

After provisioning there is nothing in the VVV/www/smalltalks/provision directory and the URL http://smalltalks.dev displays the VVV page `Problem: Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision.`

The relevant log section 
```
==> default: Running provisioner: site-smalltalks (shell)...
    default: Running: /var/folders/f8/m9ncrzd925j7m2pg4lwzt5xw0000gn/T/vagrant-shell20171121-693-76rcw4.sh
    default: Downloading smalltalks, see https://github.com/jimlongo56/smalltalks.git
    default: fatal: destination path '/srv/www/smalltalks' already exists and is not an empty directory.
    default: Adding domains to the virtual machine's /etc/hosts file...
    default:  * Added smalltalks.dev from /vagrant/vvv-custom.yml
```

## Environment
* VVV version:   Varying Vagrant Vagrants v2.1.0-master
* VVV Git Branch:  master
* Vagrant version: 2.0.1
* VM Provider name: Virtual Box 
* VM Provider version:   Version 5.1.30 r118389 (Qt5.6.3)
* Operating System and version:   Mac OSX 10.3.1

**Comment by jimlongo56** [comment]
P.S. tried it without creating the VVV/smalltalks/provision and same result.  Log follows:
```
==> default: Running provisioner: site-smalltalks (shell)...
    default: Running: /var/folders/f8/m9ncrzd925j7m2pg4lwzt5xw0000gn/T/vagrant-shell20171121-944-3xwsx2.sh
    default: Downloading smalltalks, see https://github.com/jimlongo56/smalltalks.git
    default: Cloning into '/srv/www/smalltalks'...
    default: fatal: could not read Username for 'https://github.com': No such device or address
    default: find:
    default: `/srv/www/smalltalks'
    default: : No such file or directory
```

**Comment by jimlongo56** [comment]
I didn't understand that I needed to also supply the vvv-nginx.conf and vvv-init.sh files.  When I did that I could provision the site.

**Comment by tomjn** [comment]
Also keep in mind that you don't need to create the folder in advance, VVV will do that for you when it `git clone`'s your repo

**Comment by tomjn** [comment]
@jimlongo56 no, most repos use WP CLI to download them on provision, in the provisioner script `vvv-init.sh`
