### ISSUE TITLE
Last mail gem is broken

### ISSUE THREAD

**Issue by kstefanini** [Varying-Vagrant-Vagrants/VVV#1364]
Hello, mail 2.7.0 is broken (see: https://github.com/mikel/mail/issues/1174); have to downgrade to 2.6.6 to get WordPress lost password mail working again.

Btw, it's a pain to find out how to downgrade this gem:
```
/usr/bin/env rvm default@mailcatcher --create do gem uninstall mail
/usr/bin/env rvm default@mailcatcher --create do gem install mail --version 2.6.6
```

Sorry to bother you here with this problem who is not directly related to VVV, but maybe it's time to use another modern local smtp relay like MailHog or MailDev ?

**Comment by cfoellmann** [comment]
moving away from mailcatcher might be a good idea.
Possible alternative
- https://github.com/djfarrelly/MailDev

- https://github.com/mailhog/MailHog

Others?

**Comment by jimmyko** [comment]
I would recommend MailHog.

**Comment by kstefanini** [comment]
@jimmyko Why do you recommend it ?

MailHog seems more popular (i.e has more stars). 
MailDev is pure JS (+HTML+CSS), is available _via_ NPM and has dev features.

**Comment by jimmyko** [comment]
@kstefanini 

MailHog is built with go and the installation is instantly fast. And I used it in other projects which make me feeling good so far. But honestly, I didn't heavily use MailDev. Its interface looks better though.

**Comment by cfoellmann** [comment]
I would choose the one with the most reliable install process. "Anything" is better than breaking installations constantly like mailcatcher.

**Comment by tomjn** [comment]
I'm going to close this in favour of #1485
