### ISSUE TITLE
Consider to increase the default VM memory

### ISSUE THREAD

**Issue by afercia** [Varying-Vagrant-Vagrants/VVV#1366]
With the current default VM memory setting (1024), many tasks just fail and can't be completed. For example, running phpunit or grunt precommit or other "heavy" tasks fails with the error:

```
PHP Warning:  proc_open(): fork failed - Cannot allocate memory in /usr/local/src/composer/vendor/phpunit/phpunit/src/Util/PHP/Default.php on line 99

Warning: proc_open(): fork failed - Cannot allocate memory in /usr/local/src/composer/vendor/phpunit/phpunit/src/Util/PHP/Default.php on line 99
Unable to spawn worker process
```

I understand the tests should be optimized 🙂 however, maybe 1024 is a bit too low.

While experienced users can easily configure their VVV and increase the VM memory in their `vvv-custom.yml`, new users should get a fully working installation out of the box. This is especially important during contributors days, where many people are first time VVV users. Please consider it's not uncommon contributor days attendees are unfamiliar with these kind of tools, configuration files, etc., and sometimes they're unfamiliar with the command line too. After they finally get their VVV running, it's a bit impractical to ask them "and now please stop your VM, edit the config file, increase the memory limit, start the VM again" just to run tasks that should work out of the box.

Maybe it's safe to assume machines dedicated to development have enough RAM today to allow for a higher default. I've tested a bit different settings and running some tasks. Tried first to increase to 1536 and some tasks still fail. 2048 seems fine.

**Comment by jeremyfelt** [comment]
I've setting mine to 2048 for a long while now, well before we had a `vvv-custom.yml`. I'd be in favor of bumping the default up, especially because it's now easy to customize to a lower value as needed.

**Comment by cfoellmann** [comment]
+1

**Comment by tomjn** [comment]
I think we can do this, and i'd like to add the necessary config value to `vvv-config.yml` so that it's more apparant to users

**Comment by tomjn** [comment]
@cfoellmann @jeremyfelt if either of you can approve those PR's I can merge in and fix this
