### ISSUE TITLE
Can't access vvv.dev Ubuntu 16.04

### ISSUE THREAD

**Issue by oscarssanchez** [Varying-Vagrant-Vagrants/VVV#1373]
## Expected Behavior

Hi guys, i tried to install VVV on ubuntu 16.04, but i can't go to http://vvv.dev (This site can’t be reached) 

## Current Behavior

I can access: http://192.168.50.4 though. When in http://192.168.50.4 it shows me the following message: Problem: Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision.

I've tried so far solutions like: 

1.- https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1219
2.- Fresh install of ubuntu 16.04 instead of ubuntu 17.04
3.- Starting from fresh solution on : https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/
can access: http://192.168.50.4 though. 

## Your Environment

* VVV version: 2.2.0 
* VVV Git Branch: 
* Vagrant version:
* VM Provider name: VirtualBox 
* VM Provider version:
* Operating System and version: Ubuntu 16.04

**Comment by tomjn** [comment]
1. Do you have the hosts updater vagrant plugin installed?
2. Does `http://vvv.test` work? ( You should always go for `.test` not `.dev`
3. Which version of Vagrant are you running?
4. Which version of Virtualbox are you running?
5. Is this `master` branch, `develop` branch, or a zip install?
6. Has it ever worked before

**Comment by tomjn** [comment]
@oscarssanchez were you able to check the above info? If you're unable to or need help let me know

**Comment by oscarssanchez** [comment]
Hi @tomjn i was able to install VVV without issues doing the following: 

- Uninstall vagrant and virtualbox
- Download the packages from the official site
- Install them
- Do the whole process again.

Thank you very much for your compromise with giving support Tom, i really appreciate it.

**Comment by tomjn** [comment]
As a sidenote, once https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1377 is merged, if you visit the IP directly, it'll give a note about the hosts updater and some info, and try to prompt the user to use `http://vvv.test` instead
