### ISSUE TITLE
Add monitoring tool?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1374]
Currently, the only monitoring tool that is available almost out of the box is `htop`, which you need to install when ssh-ed in the vagrant.

And `htop` is not that powerful. I don't know if it has any kind of logging available.

I tried installing [Prometheus](https://github.com/prometheus/prometheus), but I couldn't start [node exporter] on it. Prometheus adds a nice dashboard, and is good for tracking metrics on the virtual server.

[Installing Prometheus on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-use-prometheus-to-monitor-your-ubuntu-14-04-server).

Thoughts on adding it to the VVV by default?

**Comment by tomjn** [comment]
This should be added via a utility, I'd recommend building it into a custom/3rd party utility, and if it's super handy we can merge it into the main VVV core utility, though people will need to update their `vvv-custom.yml` to get it

On the other hand, what is the purpose of this on a local developer environment intended for a single person? How would this integrate with the existing stuff? PHP error logs are set via nginx configs which could be anywhere depending on the site provisioner

**Comment by dingo-d** [comment]
Well currently I'm working on a multisite and it's a rather heavy site, so I wanted to see the server activity on save, and compare it with logs, to see if I can find any bottlenecks, so that I can fix them, before the site goes to production.

**Comment by tomjn** [comment]
@dingo-d I tracked down your problem, the instructions you're following aren't for Prometheus 2

You should be able to start prometheus with this:
```
./prometheus --config.file=prometheus.yml
```

After following this:

https://prometheus.io/docs/prometheus/latest/getting_started/

Then visiting:

<img width="324" alt="screen shot 2017-12-06 at 14 19 24" src="https://user-images.githubusercontent.com/58855/33666032-a180fc82-da90-11e7-8fc0-2ef049f4fd15.png">

http://vvv.test:9090/graph also works here, although I have no data, and I'm not sure how I would record data. You'd probably also want Grafana or Kibana.

I'd suggest you create a VVV utility for this, along with grafana etc, a git repo with a `prometheus/provision.sh` and a `grafana/provision.sh` that checks if it's installed and starts it will do

**Comment by tomjn** [comment]
In the meantime though, I'm going to close this, let us know if you manage to get this working well and we might merge it into VVV utilities as an option

**Comment by dingo-d** [comment]
Will try that. Thanks!
