### ISSUE TITLE
"default web page" appears instead of WordPress when I access http://local.wordpress.test/ after a new installation

### ISSUE THREAD

**Issue by stevediabo-sa** [Varying-Vagrant-Vagrants/VVV#1375]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version: 
* VVV Git Branch: 
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by tomjn** [comment]
Hello @stevediabo-sa !

I notice you've left all of the questions and details blank, so at the moment it's impossible to diagnose what went wrong.

To help I'm going to need:

 - VVV version
 - git branch? Or zip install?
 - Vagrant version?
 - VM Provider ( probably virtualbox but we need to know for sure )
 - VM Provider version?
 - OS? Windows? MacOS? Ubuntu? Etc

And finally, a copy of the provisioning output, if there were any errors we'll need to see them, so run `vagrant up --provision` and show us the output

Also, your issue title says "default webpage", but it's not clear what you mean by that, do you mean the VVV dashboard? Or do you mean the Nginx default page? Please be explicit about the details

**Comment by tomjn** [comment]
@stevediabo-sa are you able to get any of the information I asked for above? There's not enough info to help at the moment, or diagnose the issue

As a sidenote, are you using the `vv` command?

**Comment by stevediabo-sa** [comment]
Hello Tom,

Here’s the information:

- VVV version 2.1.0 (latest)
- git master branch
- vagrant Installed Version: 1.9.7
- VM is virtualbox Version 5.1.26 r117224 (Qt5.6.2)
- macOS High Sierra


I did have a working installation of vvv a few months back but my Wordpress work was put on hold. It stopped working after I attempted to upgrade VVV to latest. All I get on any .test domain is “It Works!” Which is obviously quite frustrating to see because It Doesn’t!

Thanks for your assistance in this matter!






Steve Diabo  |  Front End Engineer
steve@stackadapt.com
www.stackadapt.com
- To Fearlessly Invent The Future -


StackAdapt debuts in Deloitte Technology Fast 50 <https://www2.deloitte.com/ca/en/pages/press-releases/articles/Deloitte-Technology-Fast-50-winners-achieve-strong-growth-in-a-challenging-labour-market.html> and Technology Fast 500 <https://www2.deloitte.com/content/dam/Deloitte/us/Documents/technology-media-telecommunications/us-tmt-fast500-2017-winners-ranking.pdf> ranking 6th in Canada and 23rd in North America.

**Comment by tomjn** [comment]
If you're ok with starting afresh, can you run:

```
vagrant destroy
vagrant box update
git pull
vagrant up --provision
```

And put the output in a gist?

**Comment by stevediabo-sa** [comment]
Thanks Tom, stand by while I follow these steps.





Steve Diabo  |  Front End Engineer
steve@stackadapt.com
www.stackadapt.com
- To Fearlessly Invent The Future -


StackAdapt debuts in Deloitte Technology Fast 50 <https://www2.deloitte.com/ca/en/pages/press-releases/articles/Deloitte-Technology-Fast-50-winners-achieve-strong-growth-in-a-challenging-labour-market.html> and Technology Fast 500 <https://www2.deloitte.com/content/dam/Deloitte/us/Documents/technology-media-telecommunications/us-tmt-fast500-2017-winners-ranking.pdf> ranking 6th in Canada and 23rd in North America.

**Comment by stevediabo-sa** [comment]
Hi Tom,

After following these steps I now have a working VVV dashboard at http://vvv.test/ <http://vvv.test/>

http://local.wordpress.test/ <http://local.wordpress.test/> does not work. Is it not meant to work out of the box?

http://src.wordpress-develop.test <http://src.wordpress-develop.test/> and http://build.wordpress-develop.test/ <http://build.wordpress-develop.test/> both take me to Wordpress installation language selection.

I’ll be developing a Wordpress theme on top of Twenty Seventeen, am I best off using the Wordpress stable installation or can I use one of these develop installations?

Thanks again for the assistance!






Steve Diabo  |  Front End Engineer
steve@stackadapt.com
www.stackadapt.com
- To Fearlessly Invent The Future -


StackAdapt debuts in Deloitte Technology Fast 50 <https://www2.deloitte.com/ca/en/pages/press-releases/articles/Deloitte-Technology-Fast-50-winners-achieve-strong-growth-in-a-challenging-labour-market.html> and Technology Fast 500 <https://www2.deloitte.com/content/dam/Deloitte/us/Documents/technology-media-telecommunications/us-tmt-fast500-2017-winners-ranking.pdf> ranking 6th in Canada and 23rd in North America.

**Comment by tomjn** [comment]
http://local.wordpress.test/ should work, and that's what I'd recommend you use, can you describe what you see when you visit that address? And can you send a copy of the output of the vagrant up command you ran?

**Comment by stevediabo-sa** [comment]
Sure: https://gist.github.com/stevediabo-sa/01ea43dfdb5d923eb2abbe3bde38bb71 <https://gist.github.com/stevediabo-sa/01ea43dfdb5d923eb2abbe3bde38bb71>










Steve Diabo  |  Front End Engineer
steve@stackadapt.com
www.stackadapt.com
- To Fearlessly Invent The Future -


StackAdapt debuts in Deloitte Technology Fast 50 <https://www2.deloitte.com/ca/en/pages/press-releases/articles/Deloitte-Technology-Fast-50-winners-achieve-strong-growth-in-a-challenging-labour-market.html> and Technology Fast 500 <https://www2.deloitte.com/content/dam/Deloitte/us/Documents/technology-media-telecommunications/us-tmt-fast500-2017-winners-ranking.pdf> ranking 6th in Canada and 23rd in North America.

**Comment by tomjn** [comment]
ok I think the problem is because it did stuff the first time but failed, it's seeing those files and trying to update WP rather than install it

Delete the `www/wordpress-default` folder and `vagrant up --provision`, I'll look into improving that check

**Comment by stevediabo-sa** [comment]
I did this but I’m still getting the “It Works!” Page on http://local.wordpress.test/ <http://local.wordpress.test/>

Is there something else I need to do?





Steve Diabo  |  Front End Engineer
steve@stackadapt.com
www.stackadapt.com
- To Fearlessly Invent The Future -


StackAdapt debuts in Deloitte Technology Fast 50 <https://www2.deloitte.com/ca/en/pages/press-releases/articles/Deloitte-Technology-Fast-50-winners-achieve-strong-growth-in-a-challenging-labour-market.html> and Technology Fast 500 <https://www2.deloitte.com/content/dam/Deloitte/us/Documents/technology-media-telecommunications/us-tmt-fast500-2017-winners-ranking.pdf> ranking 6th in Canada and 23rd in North America.

**Comment by tomjn** [comment]
are you ok with destroying your VVV instance? If the default local site doesn't work I would expect to see the VVV dashboard, not "it works".

If so:

```
vagrant halt
vagrant destroy
vagrant box update
vagrant up --provision
```

You should also update Vagrant, v1.9.7 is out of date, the current latest is v2.0.1. Make sure to uninstall Vagrant before installing 2.0 so that it's a clean unbroken install

Also keep in mind that when you reply via email, it inserts a huge email signature, along with quoted copies of all previous replies, that i have to edit out each time. If you can use GitHub or edit your signature down that would be helpful

**Comment by stevediabo-sa** [comment]
Hi Tom,

Saw your note about my signature and the quoted thread, will edit these out in future emails.

The advice you sent me on Dec 17 is the same as the advice you sent me on Dec 15. I did follow these steps and my VVV is mostly working, but my stable build is not. 

http://local.wordpress.test/ <http://local.wordpress.test/> = “It Works!”
http://build.wordpress-develop.test <http://build.wordpress-develop.test/> = WordPress installation language select

I need my local to work. As I said before, on Dec 15 I followed these steps:

vagrant destroy
vagrant box update
git pull
vagrant up --provision
I put the console output in a gift and sent it to you all last week. So that’s where we’re at. Dashboard works, dev branch WP works, stable branch does not.

Do you have any other procedures for me to try?

- SD

**Comment by stevediabo-sa** [comment]
Oh — It’s even worse. I ran vagrant up —provision again and now NOTHING works. http://vvv.test/ <http://vvv.test/> http://local.wordpress.test/ <http://local.wordpress.test/> http://build.wordpress-develop.test <http://build.wordpress-develop.test/>/ all point to an “It Works!” page now.

**Comment by tomjn** [comment]
hmmm I've never encountered this before, and you said you did this with a brand new fresh copy of VVV?

I was going to ask if I could see the nginx config for the default site, which you can grab by doing this:

```
vagrant ssh
cp /etc/nginx/custom-sites/vvv-auto-wordpress-default-provision-* /vagrant/
exit
```



Which should dump the file in the main VVV folder. This and the other files should be copies of the files in `config/nginx-config`, and the wordpress-default config should look like this:

```

################################################################
# WordPress stable nginx configuration
#
# http://local.wordpress.dev - this server configuration is
# setup to listen on port 80 for any requests coming in to
# local.wordpress.dev and use the /srv/www/wordpress-default/public_html directory
# to serve them.
server {
    listen       80;
    listen       443 ssl;
    server_name  local.wordpress.test *.local.wordpress.test local.wordpress.dev *.local.wordpress.dev ~^local\.wordpress\.\d+\.\d+\.\d+\.\d+\.xip\.io$;
    root         /srv/www/wordpress-default/public_html;

    error_log    /srv/www/wordpress-default/log/error.log;
    access_log   /srv/www/wordpress-default/log/access.log;

    set          $upstream php;

    include      /etc/nginx/nginx-wp-common.conf;
}
```
Your gist suggests they were succesfully copied however:

```
==> default:  * Copied /srv/config/nginx-config/nginx.conf           to /etc/nginx/nginx.conf
==> default:  * Copied /srv/config/nginx-config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf
==> default:  * Rsync'd /srv/config/nginx-config/sites/              to /etc/nginx/custom-sites
```


In the meantime I was also going to suggest you add an additional site via the custom site template repo, which would give you another stable WP install ( you can have as many as you like )

Add this under the sites section of `vvv-custom.yml` and reprovision:
```
  my-site:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
    hosts:
      - my-site.test
```

Additionally, can you run `sudo nginx -t`? You should see this output:

```
vagrant@vvv:~$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

Finally, if you can send the results of `sudo nginx -T` in a gist?

Apologies for the number of requests, and thanks for getting me more information :) I've already ascertained some changes that could be made to improve things, but none that directly impact this issue.

**Comment by stevediabo-sa** [comment]
Hi Tom,

No progress on fixing this. The nginx config file was dumped and matched what was in your email.

I set up http://my-site.test/ <http://my-site.test/> and reprovisioned as you directed, and it opens up that damn “It Works!” page when I try to hit that URL.

As for the output of sudo nginx -t, no need for a gist, I can paste it right here for you:

Steves-MacBook-Pro:vvv-local stevediabo$ sudo nginx -t
Password:
sudo: nginx: command not found
Steves-MacBook-Pro:vvv-local stevediabo$

**Comment by tomjn** [comment]
wait whaaat?!

Run:

```
vagrant ssh
sudo apt-get install nginx
exit
vagrant halt
vagrant up --provision
```

then try visiting the sites

**Comment by tomjn** [comment]
Also can you screenshot the "It works!" page? And check its source code to see if it has a generator? I suspect "It works!" is actually an Apache page. Also can I see a full copy of your `vvv-custom.yml` and `vvv-config.yml` and can you verify no other dev environment MAMP/Valet/Chassis/etc are running?

**Comment by stevediabo-sa** [comment]
In all honesty I decided the best course of action was to nuke my entire VVV folder, reclone the repo, run first use stuff all over again. Now I have a working wordpress install at http://local.wordpress.test/ <http://local.wordpress.test/>, but nothing else. No dashboard at http://vvv.test/ <http://vvv.test/> and no other wordpress install at http://build.wordpress-develop.test/ <http://build.wordpress-develop.test/>… just “it works” pages on those.

I really thought that would eliminate all remaining issues but I’m beginning to lose hope I’ll ever get this thing to work properly.

**Comment by tomjn** [comment]
Also the output of `service --status-all`

**Comment by stevediabo-sa** [comment]
output of service --status-all:
Steves-MacBook-Pro:vvv-local stevediabo$ service --status-all
-bash: service: command not found
Steves-MacBook-Pro:vvv-local stevediabo$

**Comment by tomjn** [comment]
ah, can you run that inside the VM via `vagrant ssh`?

I managed to track down that if Nginx was just showing the default, it would be saying "Welcome to Nginx" like this:

![image](https://user-images.githubusercontent.com/58855/34175561-b87fc300-e4f4-11e7-9b34-8cfbd7f42ec1.png)

But if this is what you're seeing:

![image](https://user-images.githubusercontent.com/58855/34175581-d600a804-e4f4-11e7-8c52-0b7cc987135f.png)

Then that's an Apache server, VVV doesn't use Apache, @LoreleiAurora @jeremyfelt thoughts?

**Comment by stevediabo-sa** [comment]
The behaviour is also erratic — after a few minutes if I reload http://local.wordpress.test/ <http://local.wordpress.test/>, which worked before, now shows the “it works!” page.

My gut tells me there’s apache running somewhere and port collision or something? But I’ve never installed or configured Apache on my MacBook.

**Comment by stevediabo-sa** [comment]
vagrant@vvv:~$ service --status-all
 [ + ]  acpid
 [ - ]  apparmor
 [ ? ]  apport
 [ + ]  atd
 [ + ]  chef-client
 [ ? ]  console-setup
 [ + ]  cron
 [ ? ]  cryptdisks
 [ ? ]  cryptdisks-early
 [ - ]  dbus
 [ ? ]  dns-clean
 [ + ]  friendly-recovery
 [ - ]  grub-common
 [ ? ]  irqbalance
 [ ? ]  killprocs
 [ ? ]  kmod
 [ - ]  landscape-client
 [ + ]  memcached
 [ ? ]  mysql
 [ ? ]  networking
 [ + ]  nginx
 [ + ]  nginx-debug
 [ + ]  ntp
 [ ? ]  ondemand
 [ ? ]  open-vm-tools
 [ + ]  php7.0-fpm
 [ - ]  postfix
 [ ? ]  pppd-dns
 [ - ]  procps
 [ + ]  puppet
 [ ? ]  rc.local
 [ + ]  resolvconf
 [ + ]  rpcbind
 [ - ]  rsync
 [ + ]  rsyslog
 [ ? ]  screen-cleanup
 [ ? ]  sendsigs
 [ + ]  ssh
 [ - ]  sudo
 [ + ]  udev
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot
 [ - ]  unattended-upgrades
 [ - ]  urandom
 [ + ]  vboxadd
 [ + ]  vboxadd-service
 [ - ]  vboxadd-x11
 [ - ]  x11-common

**Comment by tomjn** [comment]
That's possible, your output for the service command matches mine. I'd expect you'd be aware of any MAMP or equivalents still running though, `vagrant global-status` should show you all the vagrant instances on your machine, running or turned off

**Comment by stevediabo-sa** [comment]
id       name    provider   state   directory                           
------------------------------------------------------------------------
cc7b264  default virtualbox running /Users/stevediabo                   
83dff14  default virtualbox running /Users/stevediabo/vvv-local

**Comment by tomjn** [comment]
hmmm do you have any clues as to what the `cc7b264` box is that's running in your home folder? You should be able to run `vagrant halt cc7b264` to stop it

**Comment by stevediabo-sa** [comment]
Yes -- for local development of our company website we run rails in vagrant. I’ve halted it and things seem to be running fine for the time being. 

I didn’t think it would interfere because it runs rails on port 8080 but there’s obviously something else in the stack that runs on port 80 and was causing all that trouble. For the moment this seems to have resolved the issue. Thanks for all of your help trying to pinpoint the issue.

If I may ask — what’s the admin user for this default-wordpress installation? I’m looking around in the docs and I haven’t found anything to help me log into the WP admin!

**Comment by tomjn** [comment]
Glad you got it working!

Those should be listed at https://varyingvagrantvagrants.org/docs/en-US/default-credentials/

**Comment by stevediabo-sa** [comment]
Hello Tom,

I’m setting up VVV on another machine today and vagrant up or vagrant up —provision won’t add anything to my hosts file or even ask for my password to do it. Any ideas why?

- SD

**Comment by tomjn** [comment]
Sounds like the hosts updater plugin isn't installed
