### ISSUE TITLE
VVV 2.0 doesn't work with xip.io?

### ISSUE THREAD

**Issue by certainlyakey** [Varying-Vagrant-Vagrants/VVV#1376]
## Expected Behavior

With VVV1 it used to be quite simple to test a local site on a mobile — you could just open the URL `<local-domain-without-tld>.<computer-IP-in-the-network>.xip.io` while in the local network (where, for a Mac, the computer IP is what you get on the Network screen in OS X settings). I remember that I also had added something like this

```
config.vm.network "forwarded_port", guest: 80,  host: 8080
config.vm.network "forwarded_port", guest: 443, host: 8443
```

to the `Customfile`. 

On VVV1 `<computer-IP-in-the-network>.xip.io` would also expose the VVV dashboard page, and this doesn't work with VVV2 as well — the same 403 error.

## Current Behavior

Now every time I go to this address it gives me 403 Forbidden error. I tried creating a `Customfile` and putting the lines above in it, but it didn't have any effect. 

## Steps to Reproduce (for bugs)

1. Do a `vagrant up`. 
2. Go to `<local-domain-without-tld>.<computer-IP-in-the-network>.xip.io`
3. The local website is expected to load
4. 403 Forbidden shows up (with `You don't have permission to access / on this server.` message)

## Context

I'm using [ngrok](http://ngrok.com) now as a replacement for the xip.io method, but it's tougher to set up and slower to run — and you need to switch it turn it on and off. It has one advantage — the site can be tested in any network, but for a quick check xip.io was perfect. 

## Your Environment

* VVV version: VVV 2.0
* VVV Git Branch: master
* Vagrant version: 1.9.7
* VM Provider name: VirtualBox
* VM Provider version: 5.1.30
* Operating System and version: OS X 10.11.6

**Comment by tomjn** [comment]
I don't believe VVV has ever directly supported xip.io, so any support it had was accidental. Having said that, it's certainly possible to have it done with the right provisioner changes, and a PR is more than welcome

You might also consider upgrading from VVV 2 -> 2.1 and Vagrant 1.9.7 to 2.0.1

This issue and the linked details may be helpful:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/483

**Comment by tomjn** [comment]
Also relevant:

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/449/files

Nginx rules for your sites will need adjusting so that Nginx knows to serve the correct site

**Comment by certainlyakey** [comment]
Thanks @tomjn! Updating vagrant and vvv didn't help. The changes to nginx are integrated to vvv already; I also tried to put just the supposed `xip.io` literal URL as the value of the  `server_name` but this hasn't worked as well. 

Sure, as soon as I know what's causing this I suggest a PR.

**Comment by tomjn** [comment]
@certainlyakey those were merged back in VVV 1, that entire sub-system has seen a near total rewrite since then, and the xip.io nginx configs are not currently present.

The only current reference to xip.io is in a changelog markdown file. At the moment there is no built in support for xip.io, you would have to add it

**Comment by tomjn** [comment]
As a sidenote, some forks of the custom site template implement xip.io, and use a xipio key when defining a site, implementing this would involve backporting those changes, though I've misplaced where that fork is.

**Comment by tomjn** [comment]
I'm going to close this one out. Since this isn't something VVV core currently supports, it isn't a bug. If in future this gets added it'll be via the custom site template

**Comment by certainlyakey** [comment]
OK, thanks.
