### ISSUE TITLE
default: stop: Unknown instance:

### ISSUE THREAD

**Issue by adrianosferreira** [Varying-Vagrant-Vagrants/VVV#1379]
I'm trying to run vagrant up in VVV and I get this today:

==> default: stop: Unknown instance: 
==> default: start: Job failed to start
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by tomjn** [comment]
@adrianosferreira can you provide some super critical information? E.g.

 - what command is that the output of? `vagrant up`? `vagrant up --provision`? `vagrant reload`? etc
 - can you provide the entire output?
 - Which version of VVV is it?
 - Is this a `git` install or a `zip` install?
 - `master` or `develop`? And is it up to date?
 - Which version of Virtualbox are you using
 - Which version of Vagrant are you using
 - Windows? Mac? Linux? Which version?
 - Does the issue persist after a reboot?

All this information is needed, even if the answer is "I don't know" or `?`

**Comment by tomjn** [comment]
@adrianosferreira were you able to get anymore information?

**Comment by adrianosferreira** [comment]
@tomjn I've lost a working day trying to fix this out so I gave up and started using another platform. If I will use it again I will open a new issue, feel free to close this one. Thanks!

**Comment by tomjn** [comment]
@adrianosferreira that's unfortunate, I could have helped, but in the meantime, if any of the questions I asked can be answered it'd be a great help

**Comment by tomjn** [comment]
Encountered this on another machine, debugging

**Comment by tomjn** [comment]
So after some tracking down by @LoreleiAurora it seems the maria DB server wasn't present for whatever reason. Unsure why it happened, but if anybody encounters this:

 - `vagrant ssh`
 - `sudo apt-get install mariadb-server`
 - `exit`
 - `vagrant reload --provision`

**Comment by kristoffeb** [comment]
@tomjn Thanks for this answer, spent half a day trying to figure out what was happening while upgrading VVV from 1.* to 2.1.0. This should be documented somewhere.

**Comment by tomjn** [comment]
@kristoffeb it shouldn't happen to begin with, and I'm not sure why it happens. Having said that, a reprovision should have installed everything that needed installing, and when moving from VVV 1 to 2, I'd recommend destroying the box first anyway via `vagrant destroy`

**Comment by ruucm-working** [comment]
@tomjn life saver 💯

**Comment by tomjn** [comment]
Marking this as closed as nobody has encountered it in a while, also #1469 would eliminate this as an issue
