### ISSUE TITLE
Add browser capability check - utility or?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1380]
I'd like to add [browscap](http://browscap.org/) to my vvv, but upon reading the [docs](https://varyingvagrantvagrants.org/docs/en-US/default-credentials/), I'm not sure if this should be added as a utility or php extension? Or should I just download the `php_browsercap.ini` and place it somewhere and reference it in my `php-config`?

**Comment by tomjn** [comment]
You can do that but it'll need to be redone everytime you provision, hence utilities

So create a utility repo, create a `browscap` folder, and put a `provision.sh` inside that sets up `browscap.ini` and the PHP extension. Remember to check if it's already installed, and remember to check PHP versions so you install the correct extension

**Comment by dingo-d** [comment]
Will try to add this. Cheers!

**Comment by dingo-d** [comment]
I added the utility https://github.com/dingo-d/browscap-vvv-utility but I'm getting error on provision

> default: /tmp/vagrant-shell: line 5: /vagrant/provision/resources/browscap/browscap/provision.sh: Permission denied
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Any idea what I'm doing wrong?

**Comment by tomjn** [comment]
No, it sounds like either the file can't be executed or it isn't readable by the root user, check it's permissions and flags

**Comment by dingo-d** [comment]
I updated it but the copy command seems to be failing

>==> default: /vagrant/provision/resources/browscap/browscap/provision.sh: line 18: /php_browscap.ini: No such file or directory
==> default: cp:
==> default: cannot create regular file ‘’
==> default: : No such file or directory

```sh
# Check if browscap is already installed/set up
FOLDER=`/etc/php/$PHP_VER/mods-available/`
FILE=`$FOLDER/php_browscap.ini`

if [[ -f "$FILE" ]]; then
  echo "Browscap is already installed"
  exit 0
else
  # Set the browscap.ini and the php extension
  cp "${DIR}/php_browscap.ini" "$FILE"
fi
```

https://github.com/dingo-d/browscap-vvv-utility/blob/1654219f24eab73286961bbd9d4ccd96f79149ce/browscap/provision.sh#L25

**Comment by tomjn** [comment]
If you never change the current directory could you not do away with `DIR`?

**Comment by dingo-d** [comment]
You mean removing it? Well, sure I guess I don't need it. I was looking at this as an example: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/php56/provision.sh

I noticed that, when provisioning, for the `$FOLDER` variable it says:

> /vagrant/provision/resources/browscap/browscap/provision.sh: line 17: /etc/php/7.0/mods-available/: Is a directory

And for the `$FILE`

> /vagrant/provision/resources/browscap/browscap/provision.sh: line 18: /php_browscap.ini: No such file or directory

Should I actually do `cp "php_browscap.ini" "$FOLDER/php_browscap.ini"` ?

**Comment by tomjn** [comment]
try it and find out :)

**Comment by dingo-d** [comment]
Sorry to bother, I would just like to know if I'm on a right track.

I think I need to change the php.ini to point to the browscap in the `mods-available`. So I'm trying with

```sh
sed -i "s/;browscap = extra\/browscap.ini/browscap = \/etc\/php\/$PHP_VER\/mods-available\/php_browscap.ini/g" "/etc/php/$PHP_VER/fpm/php.ini"
```

Changing this

```sh
[browscap]
; http://php.net/browscap
;browscap = extra/browscap.ini
```

To this 

```sh
[browscap]
; http://php.net/browscap
browscap = /etc/php/7.0/mods-available/php_browscap.ini
```

But when I reprovisioned nothing changed, so I tried manually and I got the permission denied notice.

So my guess is that I need to do this as root, but I'm not sure how would I do that when provisioning (sudo would ask for a password).

Any advice on how to proceed?

**Comment by tomjn** [comment]
provisioners run as root, but when you `vagrant ssh` you're not the root user, hence the permissions issue

Other than that, I'm speculating and grasping at straws right now. All I can suggest is try it and if it works it works, if it doesn't it doesn't

**Comment by dingo-d** [comment]
Yeah, I have been doing that - change few things and hit `vagrant reload --provision` :) I will place some more checks in place, and try with `sed`.

Thanks!

**Comment by dingo-d** [comment]
Ok, so I think this is working - the script is copied, and added in `php.ini` and on the site that is using `get_browser()` I see no errors so I think this is all good.

https://github.com/dingo-d/browscap-vvv-utility

Thanks for the help :)
