### ISSUE TITLE
chrome blocking vvv.dev

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#1384]
Using Window 10, 64 bit

The latest update to the chrome browser enforces their ownership of the .dev domain. 
And blocks any attempt to access localhost sites that use .dev
I've changed my vvv development sites to .com and can now access them in chrome.
But how do I change the home page:  vvv.dev  ?

**Comment by tomjn** [comment]
@shanebp we were made aware of this a while ago, all the dashboard URLs support `.test` and brand new installs were switched to `.test` domains.

Sadly, we can't auto-migrate sites built with `.dev` TLDs over, you'll need to do that manually via WP CLI. Luckily the VVV side of things is easy, adjust your provisioner files if necessary, and add the `.test` version of the domain to your sites hosts section, then reprovision

**Comment by tomjn** [comment]
As a sidenote, https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1377 prompts users who don't visit `.test` to switch over.

We also warn on every site listed that has a `.dev` domain, and swapped all the URLs in the provisioning output to `.test` as well as all the docs

**Comment by shanebp** [comment]
Thank you for the info. 
For other command-line novices, this was helpful:
https://wpbeaches.com/update-varying-vagrant-vagrants-vvv/
