### ISSUE TITLE
Migration Docs need Updating

### ISSUE THREAD

**Issue by stevenkword** [Varying-Vagrant-Vagrants/VVV#1389]
The instructions for migrating to the latest version of VVV found here need an update.
Found here:
https://varyingvagrantvagrants.org/blog/2017/11/08/varying-vagrant-vagrants-2-1-0.html

There is an error in the migrate docs from that blog post the wp cli instructions contain an error:

`cd /srv/www/wordpress-develop/`
 
should be

`cd /srv/www/wordpress-develop/public_html/`

**Comment by tomjn** [comment]
Fixed by https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/65 which also swaps the site url setting for a search replace, thanks for the headsup!

**Comment by tomjn** [comment]
Should be fixed, give it a minute or two to update
