### ISSUE TITLE
Shared folders do not work anymore in v2 (map plugins and themes to a single VVV site)

### ISSUE THREAD

**Issue by unfulvio** [Varying-Vagrant-Vagrants/VVV#1397]
## Expected Behavior

In VVV v1 I used a `Customfile` to map my projects (mostly individual plugins and themes) to the box corresponding path in `/srv/www/<sitename>/htdocs/wp-content/<plugins or theme folder>`

This worked flawlessly and with NFS shares it was fast and efficient.

All I had to do is specify lines such as the following in the `Customfile`:

```sh
config.vm.synced_folder "/my/local/path/plugin-development-repo", "/srv/www/mysite/htdocs/wp-content/plugins/plugin-development-repo", :nfs => true
```

This worked splendidly at each `vagrant up`.

What's the advantage of this? The biggest is that `"/my/local/path/plugin-development-repo"` is a git repository and at the same my IDE project working directory. I work on several plugins at one time (about 100), each has its own git repo; many of them need to be tested together, in different combinations. I can easily switch between branches, tagged versions, make changes, and these are immediately picked up by the VM so I can test them. This is priceless to me, a boon for productivity.

Another advantage is that I can keep these folders separate and the organization is very tidy and portable (all I had to have was a flexible Customfile that I could pass to colleagues as well, for example).

With VVV 2, these Customfile directives seems to be ignored. I noticed that the remote path had  changed from `htdocs` to `public_html`. So I changed my paths accordingly.

I've inspected the new Vagrantfile and noticed that the sites need to have a flag to let the Customfile to be taken into consideration. I don't think this is documented, but I figured this should be within the site arguments. So I've also enabled `allow_customfile` and set it to `true` in my `vvv-custom.yml` sites arg and I'm pretty sure it's picked up by the Vagrantfile (I've deliberately inserted errors to test). I could also see it takes more time to prepare NFS shares.

## Current Behavior

When I visit my site and check for the plugins admin screen, there are none shared there, unlike VVV v1 with the same configuration. The rest works.

I'm not sure why this is no longer working at this point. I've been forced to stay on V1 because of this for several months but wanted to check again if the issue had been resolved or the documentation was improved for this. Unfortunately I'm still lost. 

### Notes:

- Speaking of documentation, this link seems broken: https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-public_html/
- The reason I use NFS is that the standard file sharing system never worked well for me (and afaik it has some limitation when you need to share something like 100 paths)
- As noted by some maintainers here, NFS is faster as well and should be the default mode on Unix systems
- I'm aware that VVV 2 can now use repositories to spawn sites, and I guess that could include custom code, plugins, themes etc... It makes no point to use an entire installation / site just for each plugin, I need often to test those in combination and different branches of each. It's unpractical.
- I noticed that the remote site is mapped locally into `vvv/www/sitename/public/html...` - however I just symlinking my git repos there does not seem to work. If I manually add folders or files there, they will be synced, but I'd really not want to put any git repos there. If I could symlink my directories there, that would be a very acceptable solution. Alternatively, if these shares could be included inside a custom site configuration, that would be great too.

## Your Environment

* VVV version:  2.2.0
* VVV Git Branch: develop
* Vagrant version: 2.0.1
* VM Provider name: VirtualBox 
* VM Provider version: 5.1.30
* Operating System and version:  Linux / Ubuntu Gnome 17.04

**Comment by unfulvio** [comment]
It looks like I found a solution to this, which involved using NFS shares also for the directories specified in the main Vagrantfile. In other words I had to replace stuff like

```sh
config.vm.synced_folder "www/", "/srv/www/", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
```

with

```sh
config.vm.synced_folder "www/", "/srv/www/", :nfs => true
```
  
Would be nice if all this was mentioned in the docs.

**Comment by tomjn** [comment]
Shared folders were never supported to begin with, but they could be implemented via customfiles if you wanted to take that responsibility which is what you did for VVV 1

> Speaking of documentation, this link seems broken: https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-public_html/

Thanks, Jekyll is very finnicky, but try to keep to the 1 issue per issue rule, I've created a pull request at:

https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/68

All our docs are on GitHub as markdown files in that repo, it may take a few minutes to deploy now that it's been merged

>  - The reason I use NFS is that the standard file sharing system never worked well for me (and afaik it has some limitation when you need to share something like 100 paths)
> -  As noted by some maintainers here, NFS is faster as well and should be the default mode on Unix systems

IIRC it once did use NFS, but it was changed to fix issues several people were having. I don't remember the specifics

> I noticed that the remote site is mapped locally into vvv/www/sitename/public/html... - however I just symlinking my git repos there does not seem to work. If I manually add folders or files there, they will be synced, but I'd really not want to put any git repos there. If I could symlink my directories there, that would be a very acceptable solution. Alternatively, if these shares could be included inside a custom site configuration, that would be great too.

You'll run into more issues than VVV if you're trying to use Symlinks, WP itself made changes in the past that get in the way of this

> I'm aware that VVV 2 can now use repositories to spawn sites, and I guess that could include custom code, plugins, themes etc... It makes no point to use an entire installation / site just for each plugin, I need often to test those in combination and different branches of each. It's unpractical.

Modifying the custom site template to allow you to specify which plugins via `vvv-custom.yml` sounds like the appropriate path here. Eitherway it sounds like you're trying to optimise for disk space.

## A General Note on Custom Files

These let you do arbitrary and potentially dangerous things. The feature is there for those people who really know what they're doing. With that in mind we can't support those users here, and I know in my case they likely know more about working with Vagrant files than I do.

With that in mind, I can write a doc, but I very much doubt it will be helpful to you. It would explain that the custom files are dangerous, that we can't offer support, adding the flag to a site, and reiterating that we can't support them, as well as warnings that they can mess up their VVV instance in horrific ways.

In terms of mapping a specific subfolder such as a theme or a plugin, no, VVV doesn't support that out of the box, and I'm unaware of any plans to do so officially. It's also a little frustrating that people think VVV 1 supported it, it didn't support it out of the box either.

**Comment by unfulvio** [comment]
hey @tomjn thanks for getting back

> Modifying the custom site template to allow you to specify which plugins via vvv-custom.yml sounds like the appropriate path here. Eitherway it sounds like you're trying to optimise for disk space.

I'm not sure if we're on the same page. I don't want to optimise for disk space. It's all about workflow. Each of my plugins/themes has its own git repository. Each repository folder is also a project in my IDE. When I do edits in my IDE, they're picked up in git and vice versa. Sometimes I need to switch branches. Sometimes I need to test cross-plugin compatibility and need to work on different branches of each plugin, simultaneously. If each of these git repos is synced with the VM, this is great: in this way I can do edits in my IDE and, without moving a single file, I can test them in the browser and if it's good, I can commit them directly, again without moving files or opening others. It's a lot cleaner, simpler, better organized, automatic. This is how I use VVV. It saves me a lot of time and sanity.

So, speaking of shared folders, I see it in this way. VVV is a Vagrant project and Vagrant features include shared folders. 

It'd be a shame if no approach to share individual folders within individual sites is taken under consideration by the maintainers. Or better, that there seems to be merely a passive approach to what comes out of the box with Vagrant (no pun intended :)). I quite believe the setup I described is not rare within the VVV community. Especially considering, as you said, that many people since V1 thought this was supported. I believe they might be using shared folders in a similar manner as I do. It would make a lot of sense in plugin and theme development. 

In my case NFS required some extra work and to modify the main Vagrantfile, which I agree is not something you could or should support. Although I'd like to point out now that you could create a variable in the Vagrantfile that in turn reads an environment variable or a simple property in the yml file, and call it like `use_nfs`. Then, if `use_nfs` is true, replace certain vagrant configuration lines as mentioned in https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1397#issuecomment-354707309 or keep the existing ones if false. This would allow users to switch over NFS without having to edit the Vagrantfile.

Finally, as you said, you could also write a documentation page on how to add more synced folders (with or without NFS - in my case the standard filesharing never worked well even in V1, but it may be just my problem).

If you think these two things are acceptable in VVV I can help with both the Vagrantfile changes and the doc page.

Cheers and Happy New Year!

**Comment by tomjn** [comment]
I see 2 feature requests here:

 - A `use_nfs` flag in `vvv-custom.yml`
 - configurable subfolder mappings

Either should be possible without custom vagrant files if the feature is designed right

But as far as custom vagrant files are concerned, no, once you start using these files there's it's unreasonable to expect support. The potential scope explodes and we end up doing general Vagrant support. This isn't the Vagrant project, it's VVV, a local developer environment targeted towards WordPress users.

If either of those are features you'd be interested in, I recommend you open a new issue for both
