### ISSUE TITLE
bash: vagrant: command not found

### ISSUE THREAD

**Issue by invictusws** [Varying-Vagrant-Vagrants/VVV#1400]
## Expected Behavior

Vagrant up should work in my git installation folder, however upon doing vagrant up I am presented with this error:
bash: vagrant: command not found

Expected the vagrant up to correctly run and download the necessary files.

## Description of my Local Environment:

uname -r --> 4.9.0-5-amd64 (recently updated)

lsb_release:
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch
This is the Debian voyager OS (https://distrowatch.com/table.php?distribution=voyager)

echo $PATH:
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
(noticed that /usr/local/bin is owned by root if that makes a difference)

Terminal used:
Xcfe with bash

Vagrant location:
Installed in home directory ~/dev/vvv
files to vagrant were installed in the vvv directory using:
git clone -b master git://github.com/Varying-Vagrant-Vagrants/VVV.git ./

Virtualbox installed:
vboxmanage -version:
5.1.30r118389

Hyper-V: 
Turned off from the bios as instructed in (https://varyingvagrantvagrants.org/docs/en-US/installation/software-requirements/)

## Current Behavior

Running vagrant gives:
bash: vagrant: command not found
## Possible Solution

Maybe I have the incorrect Paths? or the update to 4.9.0-5-amd64 isn't compatible? 

I have a feeling it might be package dependencies, looking for possible solutions.

Please let me know if you have any ideas? I got a feeling its something stupid that I have overlooked

**Comment by tomjn** [comment]
> Vagrant location:
> Installed in home directory ~/dev/vvv
> files to vagrant were installed in the vvv directory using:
> git clone -b master git://github.com/Varying-Vagrant-Vagrants/VVV.git ./

VVV isn't vagrant, vagrant is soemthing VVV uses, you need to install vagrant separately


> Hyper-V:
> Turned off from the bios as instructed in (https://varyingvagrantvagrants.org/docs/en-US/installation/software-requirements/)

Hyper V is a windows setting, it doesn't appear in the BIOS, it looks like you've turned off virtualisation, meaning Virtualbox etc will be broken. You need to turn this back on

**Comment by tomjn** [comment]
It's been a while so I'm going to close this one out, but if you're still having issues let us know and I can reopen
