### ISSUE TITLE
vvv-init.sh doesn't seem to be executing

### ISSUE THREAD

**Issue by jshwlkr** [Varying-Vagrant-Vagrants/VVV#1409]
## Expected Behavior
vvv-init.sh installs (anything really) wordpress-importer and uses curl to pull test data

## Current Behavior
Nothing. The script doesn't seem to be executing.

## Vagrant.log
https://gist.github.com/jshwlkr/b9c0babbc2ea47226f0767fb37cabc1d

## Your Environment
* VVV version: v2.1.0-master
* Vagrant version: 2.0.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.6
* Operating System and version: OS X 10.11.6

**Comment by tomjn** [comment]
Hello @jshwlkr! I can't help but notice that there's no `vvv-init.sh` mentioned in your issue, and there's no information about which site is affected, or where `vvv-init.sh` is located. Based on the log provided, the only sites setup in your `vvv-custom.yml` are the default sites

Can you provide more information? In particular:

 - a copy of `vvv-custom.yml`
 - the name of the site in question, and its paths
 - a copy of `vvv-init.sh` as well as its location in the filesystem

**Comment by tomjn** [comment]
For reference, this question was opened on WP Stack Exchange:

https://wordpress.stackexchange.com/questions/292517/auto-importing-content-in-vvv?noredirect=1

> I'm trying to import test data into a VVV site either by vanilla VVV or VVV-Base via a bash script calling WP-CLI and the WordPress Importer plugin (and curl). (The goal being to create a standardized base environment to easily distribute around the office that people with varying degrees of technical knowledge might use.) Using vvv-init.sh is a little too complicated, unless I'm misunderstanding how to use it. Is there a step for doing this while provisioning that I'm overlooking or a way of automating this that's not occuring to me?

WordPress Stack Exchange is not a VVV support channel, there simply isn't enough information in this GH issue to determine the issue, please provide the details I asked for in my previous note, as well as any other information you've witheld that could be useful.

 - a copy of `vvv-custom.yml`
 - the name of the site in question
 = a copy of `vvv-init.sh` file you're using, as well as its location in the filesystem

**Comment by jshwlkr** [comment]
It may be that I just don't quite understand how to use vv-init or I'm misunderstanding it's purpose. I'm just using the default vvv-config.yml and copying it over to vvv.custom.yml. The vv-init.sh itself is in the provision folder and is
```
#!/bin/bash
wp plugin install wordpress-importer --activate
curl -OL https://github.com/poststatus/wptest/blob/master/wptest.xml
wp import wptest.xml --authors=create
rm wptest.xml
```

**Comment by tomjn** [comment]
VVV reads `vvv-custom.yml` to figure out which sites exist. If you don't add the site to it, the site doesn't exist.

That's why your `vvv-init.sh` is never ran, because VVV is unaware of it.

E.g. if you add this under the sites section:


```
  vvvtest:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - vvvtest.test
```

Then reprovision, it'll do a git clone of that repo, and create `www/vvvtest`, setup the hosts file, run all the provisioning scripts etc, then at the end you visit `vvvtest.test` and you see a full WP install.

**Comment by jshwlkr** [comment]
Thanks. I'm just trying to get a quick shell script to grab some plugins and preload some content, this doesn't see like the right way for doing that. I appreciate your help.

**Comment by tomjn** [comment]
Eh `vvv-init.sh` is the correct place to do it. Take a look at the script the custom site template uses, it has 2 sections, one for if the sites installed, and one for if it isn't. You'll want to put your import and plugin install code in the bit were it downloads and installs WP.
