### ISSUE TITLE
Grunt watch & compass / best practice?

### ISSUE THREAD

**Issue by ecurtis** [Varying-Vagrant-Vagrants/VVV#141]
Thank you for VVV. I have set it up and shared a project in by adding it to the WWW directory. I use grunt from scss compression and live reload but I have not been able to get them working with VVV.

I tracked the folder down on the vagrant machine and ran the grunt task but it spits out this error: 

Running "compass:dist" (compass) task
Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

Before I move forward and look to install ruby and compass on the VVV machine I wanted to check that I was not missing a better solution. Cheers.

**Comment by manifestcreative** [comment]
Any suggestions on getting this working while using an https connection with a self-signed certificate?
