### ISSUE TITLE
synced_folder creates empty folder

### ISSUE THREAD

**Issue by barcia** [Varying-Vagrant-Vagrants/VVV#1414]
## Expected Behavior
Hi, I am a new user of VVV (and vagrants) and I am trying to create a synced folder using the **Customfile**.

## Current Behavior
I see many internet links and I think that the config line is correct. Also when I run `vagrant up` it show up correctly when _Mounting shared folders…_. But when vagrant is up, **the destiny folder is empty** (Obviously, my origin folder has files 😅)

This is my config line in Customfile:
`config.vm.synced_folder "/Users/ivan/Developer/mytheme/dist", "/srv/www/wordpress/public_html/wp-content/themes/mytheme", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]`

## Possible Solution
I have no idea what is wrong. There is two closed Issues with the same proble: #556 and #751.

## My Environment

* VVV version: **2.1.0**
* VVV Git Branch: **master**
* Vagrant version: **2.0.1**
* VM Provider name: **VirtualBox**
* VM Provider version: **5.2.6 r120293**
* Operating System and version: **MacOS High Sierra 10.13.3**

**Comment by tomjn** [comment]
Keep in mind that vagrant custom files are a super advanced feature that presume the user has a good knowledge of Vagrant ( the kind were if given enough time you could have built VVV yourself ).

As such the support that can be given is somewhat limited, as this is less a VVV problem and more a general VagrantFile problem

**Comment by tomjn** [comment]
If I had to speculate, the `:mount_options => [ "dmode=775", "fmode=774" ]` part looks suspicious, should it not be `:mount_options => [ "dmode=777", "fmode=777" ]` ?

**Comment by barcia** [comment]
No, with "777" doesn't works either.

Yes, I try to ask in Vagrant community groups, but it seems that nobody is active there.

Is very frustrating, I am trying to develop my WordPress theme and test it but I don't found a good workflow to do it.

**Comment by barcia** [comment]
Oh! I think I found the "problem". 🙈 The folder is apparently empty in Finder, but if I go to the directory using _vagrant ssh_ all files are in his place (And WordPress detect it correctly).

The only problem is that Finder not show the files in the virtual folder, but I can work now without problem.

Thanks for your help @tomjn
