### ISSUE TITLE
Put GitHub Token in vvv-custom.yml

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1417]
There's an option for using a GitHub token in:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L339

It's undocumented, but it should be in `vvv-custom.yml`:

 - pull the token from the config
 - add a docs page under references

**Comment by Mte90** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1896
