### ISSUE TITLE
WP-cli Error: Error establishing a database connection.

### ISSUE THREAD

**Issue by kubarazny** [Varying-Vagrant-Vagrants/VVV#1420]
When I'm trying for example install new theme by wp-cli I get an error:

```
PHP Warning:  mysqli_real_connect(): (HY000/2002): No such file or directory in /home/qbek/projekty/monest-vagrant/www/monest/public_html/wp-includes/wp-db.php on line 1531
Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /home/qbek/projekty/monest-vagrant/www/monest/public_html/wp-includes/wp-db.php on line 1531
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
```

How to fix it?

**Comment by tomjn** [comment]
Where are you running the command? Inside the VM or outside on the host machine? That error message implies it's being ran on the host machine, not inside the VM.

Run `vagrant ssh` and navigate to `/srv/www/monest/public_html` and try again, and it should work

**Comment by kubarazny** [comment]
Thanks, I was running it on host machine, it was works great inside VM. I understand that it can't be run on the host machine in any way?

**Comment by tomjn** [comment]
I'm not aware of a way to do that, though I can't say it's impossible. If you figure out how, let us know

**Comment by 1naveengiri** [comment]
@kubarazny @tomjn 
It work for me without doing ssh when I change `WP-CLI Project Config`

https://wordpress.stackexchange.com/questions/305123/why-vvv-put-wpcli-yml-file-inside-each-project-folder

I didn't get what's the purpose of adding wp-cli.yml inside each project folder is custom-site-template 
It creating the issue. when I rename it, work all fine when 
`WP-CLI project config:	/Users/naveengiri/Documents/VVV/wp-cli.yml`
