### ISSUE TITLE
404 Forbidden error when adding new site.

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1425]
## Expected Behavior
I would like to add a new site to VVV, per the [Adding a New Site instructions](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) in the VVV documentation.

## Current Behavior
After following the instructions, I encounter a '403 Forbidden nginx' error when I try to access the URL in-question.

## Steps to Reproduce (for bugs)
Per the instructions, I carried out these steps:
1.  Create vvv-custom.yml and add the following lines:
```
 vvvtest:
    hosts:
      - vvvtest.com
```
2.  Create `provision` folder and add to it the files `vvv-init.sh` and `vvv-nginx.conf`.  The contents of these files are identical to those in the instructions ([vvv-nginx.conf](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) and [vvv-init-sh](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/setup-script/)).
3.  Run `vagrant reload --provision`.

[Here](https://gist.github.com/cagross/0c1e94f6ec756cb28b0acd6cd0fde0f7) is the end of the output of `vagrant reload --provision`.

## Context
I can open vvv.test without issue.  And when I do so, it does indeed indicate that my new site has been created at the specified URL ([screenshot](https://imgur.com/V2fBELa)). But when I click on it, I encounter the 403 Forbidden error.

I was unsure on the 'Copying In Site Files' step.  The instructions were to copy in an existing site, which I don't want to do.  I merely want to create a site with a blank, default WordPress installation.  So all I did during this step was to create a `public_html` directory.

## Your Environment

* VVV version:  2.1.0-73-g6a86225 
* VVV Git Branch:   master
* Vagrant version: 2.0.1
* VM Provider name:   VirtualBox
* VM Provider version:  5.2.2 r119230 (Qt5.6.2)
* Operating System and version:  Win `10, x64.

**Comment by tomjn** [comment]
You would likely get better results from the custom site template, there is an issue open for modifying the add new site instructions to use that as the primary recommended method, and move the existing docs to a more advanced page in #1416 

In the meantime, what does the `public_html` folder contain?

**Comment by cagross** [comment]
Thanks for the reply.

>> In the meantime, what does the public_html folder contain?

This might be my issue.  I wasn't sure whether I needed to first copy WordPress files into this folder or not, so I left it empty.  As part of the `vagrant reload --provision` process, the latest WordPress files were downloaded into the root directory--i.e. the folder containing the public_html folder--leaving the public_html empty.  Did I do something incorrectly there?

**Comment by tomjn** [comment]
hmmm, that isn't right, and I can see now why it might do that

Since these instructions are all basedon the custom site template, and the custom site template gives you exactly what you wanted, I'd recommend you use this instead:

```
  cagross:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - cagross.test
```

Or at the very least, take the `vvv-init.sh` that the custom site template uses

**Comment by cagross** [comment]
OK I can certainly give that new code a try.  But to be confirm, should I have a public_html folder already created?  And should it be empty?

**Comment by tomjn** [comment]
the custom site template doesn't have a pre-created `public_html` folder. All these instructions are based on the custom site template, so you should use that as the reference of what you should do

**Comment by cagross** [comment]
OK I added your code to `vvv-custom.yml' and reprovisioned. 
 The output is [here](https://gist.github.com/cagross/361b3f00d83416b2d4c0d27c4f73bc03
).  The results were that vvv.test does indeed recognize that a new site was created at cagross.test.  But it is in the `wordpress-develop` section ([screenshot](https://imgur.com/6XlzrBI))--I'm not sure how expected that is.  Also though, when I open the URL http://cagross.test, I am met with an error, "Problem: Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision." ([screenshot](https://imgur.com/YYJWn0G)).  Thoughts?  I guess I could try to reprovision.

**Comment by tomjn** [comment]
it sounds like a formatting error in `vvv-custom.yml`, specifically, things are not indented correctly, indenting is significant in YAML

**Comment by cagross** [comment]
OK thanks for that (I now see that warning in the .yml file).  I fixed the indentation issues, and all issues are gone.  After reprovisioning, the new site appears as expected, at the expected URL.  We can consider this closed then--thanks a bunch.

**Comment by tomjn** [comment]
Thanks! I didn't realise that if you made that mistake in the config file it would provision like that. The failed to provision message assumes the install script failed and it's loading the dashboard because it's the nginx default

**Comment by tomjn** [comment]
@cagross I've changed around the install instructions, can you give an opinion on https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/71 ? Would it have helped avoid the problems you encountered? Are there any parts that are still unclear or ambiguous? Things I might have missed? Any feedback would be helpful :)

**Comment by cagross** [comment]
@tomjn OK sure.  Give me a couple hours to read through and leave comments.  Do you want me to leave comments here in this thread?  Or should I leave comments in the "Review comments" section of the pull request you linked?

**Comment by tomjn** [comment]
If your comfortable doing a review of the PR then that's great else
comments on the PR work too, keeps everything together
