### ISSUE TITLE
Missing vvv-tight.png image on the dashboard

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1426]
When I go to vvv.test (dashboard) I can see the missing image 

![screen shot 2018-02-13 at 09 12 28](https://user-images.githubusercontent.com/8638515/36139510-0d2df8c0-109e-11e8-9e65-9576527fa2f8.png)

When I inspect it, it points to `//vvv.test/dashboard/vvv-tight.png`, but I see no image in the inspector.

## Your Environment

* VVV version: v2.1.0-develop (from vagrant ssh)
* VVV Git Branch: master
* Vagrant version: Vagrant 1.9.4
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22 r115126
* Operating System and version: MacOS High Sierra v 10.13.3

**Comment by tomjn** [comment]
This was fixed a while ago in 2.2, switch to the develop branch for the fix

**Comment by dingo-d** [comment]
Cool :+1:
