### ISSUE TITLE
Vagrant up and halt command is freezing

### ISSUE THREAD

**Issue by shvlv** [Varying-Vagrant-Vagrants/VVV#1431]
## Expected Behavior

Start virtual machine and run server.

## Current Behavior

When run `vagrant up` process go to point `==> default: Running provisioner: shell...
` and freeze.
When run `vagrant halt` to point `==> default: Attempting graceful shutdown of VM...
` and freeze.

When run with --debug key have 
```
D, [2018-02-19T22:22:31.507354 #21293] DEBUG -- net.ssh.authentication.methods.publickey[3fa32c5cb534]: publickey succeeded (22:89:9a:af:7b:13:c0:e1:2e:62:2b:7b:4d:a5:25:8b)

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
```
After that `DEBUG ssh: Sending SSH keep-alive...` repeat endless.

Debug log:
[https://gist.github.com/shvlv/c4722cfee92689434ed665364b08a8c8](https://gist.github.com/shvlv/c4722cfee92689434ed665364b08a8c8
)

## Context

Bug appeared when I add new site and domain go through [https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/).

## Your Environment

* VVV version: v2.1.0
* VVV Git Branch: master

* Vagrant version: 1.9.8
* VM Provider name: VirtualBox
* VM Provider version: 5.1.26
* Operating System and version: Ubuntu 16.04

**Comment by tomjn** [comment]
Hello!

Vagrant v2.0 rewrote and fixed a lot of the issues related to this. Can you uninstal Vagrant and install the 2.x version? At the very least it should output an actual error

**Comment by shvlv** [comment]
Update to Vagrant 2.0.2 fixed problem. Thanks!
