### ISSUE TITLE
Import db from git

### ISSUE THREAD

**Issue by AlfredJKwack** [Varying-Vagrant-Vagrants/VVV#1434]
Hi,

I'm looking to set up a provisioning script to test plugins and themes under development. I'd like to be in a position where I can quickly spin up an environment with a specific set of plugins, themes and accompanying database. The provisioning tools and extensions are great and quite flexible ([(VVV-base](https://github.com/JPry/vvv-base) for instance ). 

I'm looking for something specific with regards to database imports. Hopefully someone can either point me to an example or let me know what challenges I would encounter.

**What I imagine in terms of behavior:**
- The vvv-custom.yml file allows for defining a db source (eg. a git repo)
- During provisioning the script would check for the existence of a db backup
- if a backup exists continue as normal
- if no backup exists download it from git
- move the downloaded file in the backup folder and rename it to match what the backup restore scripts expect.

Ideally this process would be able to handle sql or xml formats but I'm not picky.

Is there somthing in this vein available somewhere or should this be a feature?

Appreciate the input.

**Comment by tomjn** [comment]
The custom site template doesn't support this, but you can do this in a fork of that by modifying `vvv-provision.sh`, I would note however this:

> if no backup exists download it from git

The git repo is already cloned into that folder, so no download is necessary

As for backups, look at the place vagrant triggers makes them, the VVV folder is mapped to `/vagrant`

**Comment by tomjn** [comment]
I can't comment as to other site templates though such as https://github.com/JPry/vvv-base, I'd recommend opening an issue there as they might already support that

**Comment by AlfredJKwack** [comment]
Thanks for the quick response. 

I get the general idea. Could you clarify where I should expect the `vvv-provision.sh` file to be located? Where under `~/VVV/...` would this be.

**Comment by tomjn** [comment]
it's in the `provision` subfolder of the site, be sure to fork the repository though, you don't want to encounter merge conflicts when VVV tries to pull down the latest official custom site template

**Comment by AlfredJKwack** [comment]
Thanks.
