### ISSUE TITLE
"Running triggers after up..." sits forever on vagrant up and vagrant halt

### ISSUE THREAD

**Issue by broskees** [Varying-Vagrant-Vagrants/VVV#1436]
## Expected Behavior
I believe it should finish provisioning.

## Current Behavior
Goes through all the vagrant up commands, then after reaching "Running triggers after up..." it sits forever.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Not sure how to reproduce on other's machines, but on mine, simply type `vagrant up --provision`, or `vagrant halt` or `vagrant up`

Provisioning log - Gist:
https://gist.github.com/broskees/71e05c91786d756558010201fe3020ac

## Context
Trying to set up a new client's install.

## Your Environment
* VVV version: 2.1.0
* VVV Git Branch: master
* Vagrant version: 2.0.2
* VM Provider name: VirtualBox
* VM Provider version: 5.2.6 r120293
* Operating System and version: Windows 10

**Comment by tomjn** [comment]
Hello!

Can you switch to the `develop` branch and retry?

I also see that there's no branch mentioned in the VVV splash:


```
  [38;5;196mVarying [38;5;118mVagrant [38;5;33mVagrants [38;5;129mv2.1.0-
  [0mDocs:       https://varyingvagrantvagrants.org/
```

I would expect to see:

```
  [38;5;196mVarying [38;5;118mVagrant [38;5;33mVagrants [38;5;129mv2.1.0-master
  [0mDocs:       https://varyingvagrantvagrants.org/
```

Is your git clone in a normal state? Let me know how a fresh provision goes with `develop`

**Comment by broskees** [comment]
Should I do a new `git pull` with the develop branch?

**Comment by tomjn** [comment]
Just a standard git switch branch

```
git checkout develop
git pull
```

**Comment by broskees** [comment]
Same behavior.
https://gist.github.com/broskees/33eddbaeee65556ece4ffd3a3e36673f

**Comment by tomjn** [comment]
Ruby/Vagrant control/direct the VM, but they're not responsible for the running of the VM. To force end the VM the way you're trying you need to enter VirtualBox, and use the VirtualBox control to stop the VM.

I noticed again that there is no branch mentioned in your VVV splash, which version of `git` are you using? As an aside, what's the output of `git rev-parse --abbrev-ref HEAD`?

Judging from that log output, VVV is running, it's just the final trigger that's frozen, in theory you should be able to just open a new terminal tab and pretend it finished succesfully

On that trigger, is a script that's designed to let users of custom files run scripts, do you have a custom vagrant file or custom scripts in the `config/home_bin` folder?

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/commit/454e20ec9f244749f232c671817c6e0dd7d3f5df now logs output if there are custom scripts present, if you `git pull` it should say so if this is the case

**Comment by broskees** [comment]
Here's the git version I'm running:
`git version 2.16.1.windows.1`

Here's the output of `git rev-parse --abbrev-ref HEAD`:
`develop`

So if I get pull, there should be an output mentioning that I have a custom script if so? Here's the output of `git pull`:
`git : From git://github.com/Varying-Vagrant-Vagrants/VVV`
`At line:1 char:1`
`+ git pull`
`+ ~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (From git://gith...nt-Vagrants/VVV:String `
`   ) [], RemoteException`
`    + FullyQualifiedErrorId : NativeCommandError`
 
`   aa357a8..14fe2a3  develop    -> origin/develop`
` * [new branch]      output_running_custom_script -> `
`origin/output_running_custom_script`
`Updating aa357a8..14fe2a3`
`Fast-forward`
` config/homebin/vagrant_destroy | 1 +`
` config/homebin/vagrant_halt    | 1 +`
` config/homebin/vagrant_suspend | 1 +`
` config/homebin/vagrant_up      | 1 +`
` 4 files changed, 4 insertions(+)`

**Comment by broskees** [comment]
I'm now getting a 500 internal server error on http://syracusesedationandfamilydentistry.com/

**Comment by tomjn** [comment]
> So if I git pull, there should be an output mentioning that I have a custom script if so? That code looks like it outputs on vagrant halt, vagrant up, vagrant suspend, and vagrant destroy. Anyways, here's the output of git pull:

Nope, when you `vagrant up`, if there's a post up script, it'll now say it's going to run it rather than just running it


> I'm now getting a 500 internal server error on http://syracusesedationandfamilydentistry.test/, dunno if it's related. But I removed that site initially from vagrant-local\www and had the provision recreate it. 

a 500 error indicates something went wrong, check the PHP logs to find out what it is, so look in the `logs` subfolder of that site to find out which it is

> Also, in vvv-custom.yml I have nginx_upstream: php71, which don't have in the yml file for the other sites. That site definitely needs to run php 7.

Did you add php71 to the utilities section? If you don't, VVV doesn't know to install it

**Comment by tomjn** [comment]
btw you can use triple back tick to start a code block, and again to end it

**Comment by tomjn** [comment]
> I hadn't added php71 to the utilites section. So that's obviously the source of these errors.
>
> So I reprovisioned. Everything is running correctly, and just like you said.

Awesome, it'd be good to have VVV check for that and warn, but I can't think of a way off the top of my head, any suggestions for the docs on making that clearer?

> I'm still trying to figure out why however it gets stuck on triggers. I wouldn't mind except I have to basically restart my machine everytime I want to reload, reprovision, or stop it because most of the time when stopping 'ruby' and 'vagrant' processes AND shutting down the VM via virtual box I still can't run any vagrant commands.

I'm curious, at any point did you upgrade straight from Vagrant 1.x to 2.x without uninstalling and installing afresh?

Also it might be a long shot, but try:

```
vagrant plugin repair
vagrant plugin update
```

In the meantime, this is unexpected vagrant output at the start:

```
vagrant : -f was unexpected at this time.
At line:1 char:1
+ vagrant halt
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (-f was unexpected at this time.:String)  
   [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Can you modify `` so that instead of:

```
if [[ -f /home/vagrant/bin/vagrant_halt_custom ]]; then
	echo "Executing vagrant_halt_custom"
	vagrant_halt_custom
else
	db_backup
fi
```

it's just:

```
db_backup
```

And see if `vagrant halt` still gives that notice at the top? Thanks for testing btw

**Comment by broskees** [comment]
Ran plugin repairand update. No problems.
```
PS C:\~\vagrant-local> vagrant plugin repair
Repairing currently installed plugins. This may take a few minutes...
Installed plugins successfully repaired!

PS C:\~\vagrant-local> vagrant plugin update
Updating installed plugins...
All plugins are up to date.
```

Next I updated `vagrant_halt` to the following:
```
#!/bin/bash
#
# This script is run whenever `vagrant halt` is used to power off
# the virtual machine. To customize this behavior, include a file
# in your local VVV/config/homebin directory: vagrant_halt_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
# if [[ -f /home/vagrant/bin/vagrant_halt_custom ]]; then
#	  echo "Executing vagrant_halt_custom"
#	  vagrant_halt_custom
# else
	db_backup
# fi
```

Same result with the `vagrant halt` command:
```
PS C:\~\vagrant-local> vagrant halt
vagrant : -f was unexpected at this time.
At line:1 char:1
+ vagrant halt
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (-f was unexpected at this time.:String)  
   [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[1;38;5;196m[38;5;9m__ [1;38;5;2m__ [38;5;4m__ __ 
[38;5;9m\ V[1;38;5;2m\ V[38;5;4m\ V / [38;5;9mVarying [1;38;5;2mVagrant [38;5;4mV
agrants
[38;5;9m \_/[1;38;5;2m\_/[38;5;4m\_/  [38;5;5mv2.2.0[0m-[38;5;6m
 
[0mDocs:       [4;38;5;3mhttps://varyingvagrantvagrants.org/
[0mContribute: [4;38;5;3mhttps://github.com/varying-vagrant-vagrants/vvv
[0mDashboard:  [4;38;5;3mhttp://vvv.test[0m

An action 'halt' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.
If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
```

FYI: PHP7 doesn't seem to be working. Trying to set up Sage 9 as on the php71 site, getting the following:
```
PS C:\~\vagrant-local\www\syracuse-sedation-and-family-dentistry\public_html\wp-content\themes\ssafd-theme> composer install
composer : Loading composer repositories with package information
At line:1 char:1
+ composer install
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Loading compose...age information:String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - This package requires php >=7 but your PHP version (5.6.24) does not satisfy 
that requirement.
  Problem 2
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by 
doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.24) does 
not satisfy that requirement.
  Problem 3
    - Installation request for roots/sage-lib 9.0.0-beta.4 -> satisfiable by 
roots/sage-lib[9.0.0-beta.4].
    - roots/sage-lib 9.0.0-beta.4 requires php >=7 -> your PHP version (5.6.24) does 
not satisfy that requirement.
  Problem 4
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.24) does 
not satisfy that requirement.
    - illuminate/support v5.4.27 requires doctrine/inflector ~1.0 -> satisfiable by 
doctrine/inflector[v1.2.0].
    - Installation request for illuminate/support v5.4.27 -> satisfiable by 
illuminate/support[v5.4.27].
```

**Comment by tomjn** [comment]
```
PS C:\~\vagrant-local\www\syracuse-sedation-and-family-dentistry\public_html\wp-content\themes\ssafd-theme> composer install
composer : Loading composer repositories with package information
At line:1 char:1
+ composer install
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Loading compose...age information:String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

This is being ran on the host machine, so it's not using VVV at all here, it's using the PHP in your path, which is v5.6. Instead, use `vagrant ssh` to enter the VM and run commands

Also, seeing this `NativeCommandError` stuff in an unrelated command suggests this is a general problem with your host machine, google suggests it's a powershell feature printing `stderr` and thus a red herring, and has nothing to do with what's happening.

At this point in time my line of thought would be to uninstall vagrant and do a fresh install on the assumption something went wrong somewhere.


```
PS C:\~\vagrant-local\www\syracuse-sedation-and-family-dentistry\public_html\wp-content\themes\ssafd-theme> composer install
```

My understanding of this is that `C:\~\vagrant-local` is not a valid path? `~` in the docs refers to your home directory

**Comment by broskees** [comment]
That's my actual path, haha.

**Comment by broskees** [comment]
Should I uninstall and reinstall virtualbox as well? (I've done this already, but I've provisioned since then).

**Comment by broskees** [comment]
Uninstalled then reinstalled vagrant, same result on provision.

Here's the output:
https://gist.github.com/broskees/062e6c86753e2d338ba0bfc76fb0ba9b

**Comment by broskees** [comment]
Turns out 'Windows Powershell ISE' has an issue with input prompts. Not sure why, but it functions correctly in 'Windows Powershell'.

**Comment by tomjn** [comment]
Glad you figured it out, do you know of any way we can detect Powershell ISE from vagrant and warn the user? I'll see to it that it's added to the troubleshooting section of the docs

**Comment by broskees** [comment]
I did a short bit of researching, couldn't find anything about detecting the CLI the user is using. So unfortunately no. The Docs will have to do for now.

**Comment by qbattersby** [comment]
Hi guys - hoping I may be able to get some advice/feedback on if there is a way to overcome this getting stuck on an input prompt in Hyper for Windows? Any modification I can make to prevent it from being held up? Would much prefer to not have to run git bash just to up vvv.. :(

Trying to finally make a switch from osx to win10 and this is definitely a sticking point.. help?

**Comment by tomjn** [comment]
@qbattersby only thing we have so far is that you need to run in an elevated priv shell, but it cannot be a powershell ISE. I know there are multiple methods of running a prompt on windows, and multiple shell environments, and no guarantee that Vagrant will work with all of them, so test out what does and doesn't work

Something I'd be curious to find out, is if the linux subsystem for Windows 10 works

**Comment by qbattersby** [comment]
@tomjn hmmm - I am running the subsystem which is awesome but I am not running vagrant there.  But in this case bash is my shell in Hyper, and I have symlinks to run vagrant.exe from bash. 

It works but hangs - so I have to go through and manually stop things which means no backups etc.

**Comment by tomjn** [comment]
Try other shells is all I can say, there doesn't seem.to be such a thing as
a standard command prompt on windows other than cmd.exe, so if you're using
any of those there's no guarantee this won't happen.

A bug will need raising with either vagrant triggers or Microsoft

**Comment by Hutoa** [comment]
I see this issue if running 'vagrant up' under PowerShell ISE (running forever but no output), if I use powershell command line (powershell.exe) it works fine.

**Comment by tomjn** [comment]
@Hutoa vagrant + powershell ISE will never work, no idea why. Don't use Powershell ISE
