### ISSUE TITLE
Allow defining custom plugin, theme & mu-plugin custom folder mapping.

### ISSUE THREAD

**Issue by danieliser** [Varying-Vagrant-Vagrants/VVV#1439]
## Expected Behavior
Adding the following to a site to allow vagrant style symlinking for each site to a global or other folder stored elsewhere outside the VVV/www directory.

## Current Behavior
Currently ever site has a standard wp-content folder.

## Possible Solution
I have some simple but effective code that allows this to occur easily via some extra site config args.

      site1:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        plugin_dir: /home/user/Documents/Projects/WordPress/plugins/
        theme_dir: /home/user/Documents/Projects/WordPress/themes/
        mu_plugin_dir: /home/user/Documents/Projects/WordPress/mu-plugins/
        hosts:
            - site1.test

      site2:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        plugin_dir: /home/user/Documents/Custom-Plugins/
        theme_dir: /home/user/Documents/Projects/WordPress/themes/
        mu_plugin_dir: /home/user/Documents/Projects/WordPress/mu-plugins/
        hosts:
            - site2.test

You will notice they both share mu-plugin & theme paths so no need to install or update each site separately.

Furthermore they both have unique externally mapped folders for easier plugin development.

Can submit a PR if there is interest in such a thing.

Something like this does the trick:

      vvv_config['sites'].each do |site, args|
        if args['local_dir'] != File.join(vagrant_dir, 'www', site) then
          if vagrant_version >= "1.3.0"
            config.vm.synced_folder args['local_dir'], args['vm_dir'], :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
          else
            config.vm.synced_folder args['local_dir'], args['vm_dir'], :owner => "www-data", :extra => 'dmode=775,fmode=774'
          end
        end

        # Custom directory mapping.
        if vagrant_version >= "1.3.0"
          if args['theme_dir'] != false
            config.vm.synced_folder args['theme_dir'], args['vm_dir'] + "/public_html/wp-content/themes", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
          end

          if args['plugin_dir'] != false
            config.vm.synced_folder args['plugin_dir'], args['vm_dir'] + "/public_html/wp-content/plugins", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
          end

          if args['mu_plugin_dir'] != false
            config.vm.synced_folder args['mu_plugin_dir'], args['vm_dir'] + "/public_html/wp-content/mu-plugins", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
          end

        else
          if args['theme_dir'] != false
            config.vm.synced_folder args['theme_dir'], args['vm_dir'] + "/public_html/wp-content/themes", :owner => "www-data", :extra => 'dmode=775,fmode=774'
          end

          if args['plugin_dir'] != false
            config.vm.synced_folder args['plugin_dir'], args['vm_dir'] + "/public_html/wp-content/plugins", :owner => "www-data", :extra => 'dmode=775,fmode=774'
          end

          if args['mu_plugin_dir'] != false
            config.vm.synced_folder args['mu_plugin_dir'], args['vm_dir'] + "/public_html/wp-content/mu-plugins", :owner => "www-data", :extra => 'dmode=775,fmode=774'
          end
        end
      end

**Comment by tomjn** [comment]
In principle yes... in practice it's a little more complicated.

The problem here is that it'll open things up to adding extra folders, and having a lot of hardcoded of items, so:

 - a generic way to specify these
 - a way to specify both the `local_dir` and `vm_dir` not jsut the `local_dir`

**Comment by tomjn** [comment]
Marking this as closed as it's an advanced topic, and mounting shares has a performance cost
