### ISSUE TITLE
Every newly added site says ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1443]
At first I thought that I did something wrong in the provisioning, but I literally copied a working directory, changed the provision scripts and nginx conf file, name and reprovisioned VVV and again I got the `ERR_NAME_NOT_RESOLVED` error. I have no idea why.

`vvv-custom.yml`

```yml
#############
  # Personal
  #############
  personal/wordpress-clients:
    hosts:
      - clients.wordpress.test

  personal/wordpress-test:
    hosts:
      - dev.wordpress.test
```

The `dev.wordpress.test` one works just fine, the `clients.wordpress.test` isn't.

`vvv-nginx.conf` looks like:

```sh
server {
    listen       80;
    listen       443 ssl;
    server_name  clients.wordpress.test *.clients.wordpress.test ~^clients\.wordpress\.\d+\.\d+\.\d+\.\d+\.xip\.io$;
    root         {vvv_path_to_site}/public_html;

    error_log    {vvv_path_to_site}/log/error.log;
    access_log   {vvv_path_to_site}/log/access.log;

    set          $upstream {upstream};

    include      /etc/nginx/nginx-wp-common.conf;
}
```

And the `vvv-init.sh` looks like:

```sh
#!/usr/bin/env bash
# Provision WordPress Stable

# Make a database, if we don't already have one
echo -e "\nCreating database 'wordpress_clients' (if it's not already there)"
mysql -u root --password=root -e "CREATE DATABASE IF NOT EXISTS wordpress_clients"
mysql -u root --password=root -e "GRANT ALL PRIVILEGES ON wordpress_clients.* TO wp@localhost IDENTIFIED BY 'wp';"
echo -e "\n DB operations done.\n\n"

# Nginx Logs
mkdir -p ${VVV_PATH_TO_SITE}/log
touch ${VVV_PATH_TO_SITE}/log/error.log
touch ${VVV_PATH_TO_SITE}/log/access.log

# Install and configure the latest stable version of WordPress
if [[ ! -d "${VVV_PATH_TO_SITE}/public_html" ]]; then

  echo "Downloading WordPress Stable, see http://wordpress.org/"
  cd ${VVV_PATH_TO_SITE}
  curl -L -O "https://wordpress.org/latest.tar.gz"
  noroot tar -xvf latest.tar.gz
  mv wordpress public_html
  rm latest.tar.gz
  cd ${VVV_PATH_TO_SITE}/public_html

  echo "Configuring WordPress Stable..."
  noroot wp core config --dbname=wordpress_clients --dbuser=wp --dbpass=wp --quiet --extra-php <<PHP
// Match any requests made via xip.io.
if ( isset( \$_SERVER['HTTP_HOST'] ) && preg_match('/^(clients.wordpress.)\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(.xip.io)\z/', \$_SERVER['HTTP_HOST'] ) ) {
    define( 'WP_HOME', 'http://' . \$_SERVER['HTTP_HOST'] );
    define( 'WP_SITEURL', 'http://' . \$_SERVER['HTTP_HOST'] );
}

define( 'WP_DEBUG', true );
PHP

  echo "Installing WordPress Stable..."
  noroot wp core install --url=clients.wordpress.test --quiet --title="Clients WordPress Dev" --admin_name=admin --admin_email="admin@local.test" --admin_password="password"

else

  echo "Updating WordPress Stable..."
  cd ${VVV_PATH_TO_SITE}/public_html
  noroot wp core update

fi
```

I don't know where to look what could be the culprit? All the other old sites are working just fine. 

## Your Environment

* VVV version: v2.1.0
* VVV Git Branch: develop
* Vagrant version: 2.0.2
* VM Provider name: VirtualBox
* VM Provider version: 5.2.6
* Operating System and version: MacOs High Sierra 10.13.3

**Comment by tomjn** [comment]
hmmm `personal/wordpress-clients:` is an unusual name, I did not expect that `/` was valid in YAML as a key, nor is it how this was envisione to work for subfolders. Is there a reason you didn't use the `local_dir` and `vm_dir` keys?

Can you verify that you have the vagrant-hostsupdater plugin installed, and that there are no applications interfering with the hosts file, such as gas mask etc? And that clients.wordpress.test appears in your hosts file?

Also are there any errors when provisioning? I notice there is no log of the `vagrant up --provision`

**Comment by tomjn** [comment]
Also does the custom site template work for a new site? It would be much simpler than manually recreating everything it does in folders

**Comment by dingo-d** [comment]
Yeah, the `/` worked, I needed to sort the mess I had in the `www` folder somehow. No special reason for not using `local_dir` and `vm_dir`. I'll try to set them up and reprovision and see how that goes.

I didn't have the hostsupdater plugin installed. Once I did and I reprovisioned the sites started to work, but the `clients.wordpress.test` site is redirecting to the `dev.wordpress.test` site for some reason.

I don't have any apps that should interfere with hosts file (it all worked before and I don't have any extra apps installed). The clients site is in the hosts file. And no errors, aside from warning not to run composer as a root.

I'll try rewriting the `vvv-custom.yml` file, just to see if all will work out as it should.

Thanks for the help!

**Comment by tomjn** [comment]
> I didn't have the hostsupdater plugin installed.

That's the problem, hosts updater and triggers are needed for all VVV functionality to work

> Once I did and I reprovisioned the sites started to work, but the clients.wordpress.test site is redirecting to the dev.wordpress.test site for some reason.

They both have the same `vvv-init.sh`, so they both install to the same DB. I'm going to take a wild guess and say that `dev.wordpress.test` got installed first.

I'd strongly recommend just using the custom site template as a base and forking it for any custom items you want

**Comment by dingo-d** [comment]
> I'd strongly recommend just using the custom site template as a base and forking it for any custom items you want

You mean storing it on a repo, and creating repo for each site or? The problem is that I use VVV for my local testing, my clients and for the company work, so I'm not sure that would work. Or just having empty repos that are used for sites creation?

**Comment by tomjn** [comment]
I mean literally copying/forking it and using it as a starting point, or just using it to create the site then having a theme or plugins git repo inside the site you work in, it's better than reinventing the wheel for every client.

Templates are intended to be reusable, think of them as a foundation you apply rather than an instance you use. All my sites on my local VVV instance are custom site template sites. Inside those folders I have other git repos for various packages and themes, and if I need a git repo that manages an entire site, I'll either fork the custom site repo, or have the repo track just wp-content and clone it into a custom site template. Rewriting the provisioner script and nginx from scratch is unnecessary
