### ISSUE TITLE
How to setup symlinks for theme files.

### ISSUE THREAD

**Issue by codytooker** [Varying-Vagrant-Vagrants/VVV#1444]
## Expected Behavior

Creating a symlink in ./public_html/wp-content/themes/my-theme to ./src directory should allow for theme development outside of public_html.

## Current Behavior

Wordpress does not recognize the symlinked theme directory

## Context

Is it possible to create a symlink to keep theme directory outside of the public_html route.? If symlinks are not possible is there another way in some sort of vagrant config?

**Comment by tomjn** [comment]
Does navigating in into the symlinked directory via `vagrant ssh` work as expected? Is there a particular reason that requires a `src` folder outside of `public_html`?

**Comment by codytooker** [comment]
accessing vagrant with SSH I can navigate to the themes directory and see the link listed.  when I try to cd into it, it simply says no file or directory.

Maybe an explanation of what I am trying to accomplish will be better suited.  I build custom sites for clients and I have a pretty robust default setup that I am trying to integrate with VVV instead of my old MAMP process.  

Keeping the theme outsite of public_html means I can .gitignore the public_html folder and only worry about my theme code and system that I am using for building the sites.  


I have found things on StackOverflow that are close but I am not sure how to set it up correctly or where to put code like this i my project with VVV2 because I am pretty sure it's in reference to VVV1

`if vagrant_version >= "1.3.0"
  config.vm.synced_folder "/Users/sudar/Dropbox/plugins/", "/srv/www/wordpress-default/wp-content/plugins", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
else
  config.vm.synced_folder "/Users/sudar/Dropbox/plugins/", "/srv/www/wordpress-default/wp-content/plugins", :owner => "www-data", :extra => 'dmode=775,fmode=774'
end`

**Comment by tomjn** [comment]
> or where to put code like this i my project with VVV2 because I am pretty sure it's in reference to VVV1

That would be custom vagrantfile code, if you're happy to use that then it's expected you know your way around Vagrant itself, well enough that you would be able to figure it out from reading VVV's vagrantfile

As an aside, have you considered a plugins and themes git repo that gets git cloned on provision?

Also, are you creating the symlinks on the host machine, or in the guest VM? Have you considered git ignoring `wp-admin`, `wp-content/uploads`, and `wp-includes` instead?

**Comment by codytooker** [comment]
The reason for not just ignoring those and working from within the theme folder is that in my vvv-init.sh file I am pulling a fresh install of wordpress using wp-cli.  

Ideally I would be able to 
1. Update my vvv-custom.yml file with a new site. (this pulls from a private bitbucket repo)
2. run composer isntall which installs my plugins
3. npm install which installs all dependencies
4. npm start to start my webpack / scripts.  

With this I can keep the theme I am developing decouple from the wordpress install that is inside public_html.

I was creating the symlink on my host machine.  I can try it onside Vagrant to see what happens

**Comment by tomjn** [comment]
For general development I would advise against symlinks, but it seems that symlinks in shared folders are disabled by default in VirtualBox + Vagrant for security reasons. Enabling it involves [Vagrant changes](https://stackoverflow.com/questions/24200333/symbolic-links-and-synced-folders-in-vagrant), I'd strongly advise against it

The solution here is more likely to involve process and workflow.

> The reason for not just ignoring those and working from within the theme folder is that in my vvv-init.sh file I am pulling a fresh install of wordpress using wp-cli.

I don't follow how this has an impact on things. The Custom Site Template uses WP CLI too, and it ignores the `public_html` folder, yet I'm still able to clone additional repos in `wp-content` and work with them.

You can install WP via CLI and still only gitignore the `wp-admin` `wp-includes` `wp-content/uploads` and root files. This seems like an extreme amount of effort to avoid having to copy paste multiple entries into `.gitignore`. `ls` in a fresh WP install should get you most of the entries

> Update my vvv-custom.yml file with a new site. (this pulls from a private bitbucket repo)

I see no issue here, key forwarding is enabled, if you can `git clone` on the host you should be able to `git clone` in the provisioner

> run composer install which installs my plugins

You can do this in `vvv-init.sh` too, `composer` should be present inside the VM

> npm install which installs all dependencies

Again, the WP dev template does this, I don't see the issue

> npm start to start my webpack / scripts.

Same as above


Aside from your initial build scripts `composer.json` and `package.json` etc themes and plugins should all be git repos anyway, so the gitignore should be irrelevant for them as they'll have their own gitignore files

**Comment by tomjn** [comment]
I'm going to mark this as closed for now, as symlinking isn't encouraged and alternative solutions to these problems exist. In addition, the vagrant docs suggest that symlink support on synced folders is inconsistent across platforms, and that while it attempts to make things play nice, this isn't always met with success:

https://www.vagrantup.com/docs/synced-folders/basic_usage.html#symbolic-links

But, if you're trying to take a folder that the VM can't access that isn't inside an already shared folder, then symlink it into one that is shared, I don't see why that would work. I would expect Vagrant to convert the symlink so that when the VM's OS looked at it, the locations would be changed around. Instead it probably sees a host path which is foreign to it and has no idea what to do with it, similar to the math problem "5 +5 + well I had a nice cup of tea - 3 = ?". Either that, or Vagrant itself picks up that it isn't possible to map it and stops trying
