### ISSUE TITLE
Enable `SCRIPT_DEBUG` by default

### ISSUE THREAD

**Issue by widoz** [Varying-Vagrant-Vagrants/VVV#1448]
Since the `WP_DEBUG` is set to `true` by default, there is a reason why not to set `SCRIPT_DEBUG` to `true` too?

I ask because plugins use that constant to know if they must enqueue or not minified version of javascript/css files.

See for example WooCommerce: https://plugins.trac.wordpress.org/browser/woocommerce/trunk/includes/class-wc-frontend-scripts.php#L168

**Comment by widoz** [comment]
Hi @tomjn thank for the suggestion.

All ready done:
https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/compare/master...widoz:patch-1

and 

https://github.com/Varying-Vagrant-Vagrants/custom-site-template/compare/master...widoz:patch-1

**Comment by tomjn** [comment]
awesome :D
