### ISSUE TITLE
Downloading file from vagrant using scp or?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1450]
I am playing with XDebug and profiling, and I can access webgrind just fine, but I'd like to download `cachegrind.out` files so that I can use `qcachegrind` on the local machine.

How do I download those files?

I tried with

```sh
scp 192.168.50.4:/tmp/cachegrind.out.1521537539 ~/Desktop
```

But I guess I need username for vagrant or I'm doing something completely wrong XD

**Comment by tomjn** [comment]
The root VVV folder is mounted at `/vagrant` inside the VM, just `vagrant ssh` then `cp /tmp/cachegrind.out.1521537539 /vagrant` and it'll appear in your VVV folder

**Comment by dingo-d** [comment]
Awesome! Thanks!
