### ISSUE TITLE
How to properly edit PHP options, e.g. upload_max_filesize?

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1451]
## Expected Behavior

I may want to edit certain PHP options, for example upload_max_filesize (and those in [this screenshot](https://imgur.com/8orKBBl)).  What is the proper way of doing so with VVV?  

When I edit these options on my web server, my web host (Go Daddy) requires that I make such changes through cpanel (which is where I obtained the screenshot).  But I know one can also set the same parameters in wp-config.php--will doing so be sufficient with VVV?  Or is there another method of doing so (e.g. .htaccess)?

In my case, the options I might want to change would be:

max_execution_time
upload_max_filesize
post_max_size

Thanks.

## Your Environment

* VVV version:  2.1.0-73-g6a86225 
* VVV Git Branch:   master
* Vagrant version: 2.0.1
* VM Provider name:   VirtualBox
* VM Provider version:  5.2.2 r119230 (Qt5.6.2)
* Operating System and version:  Win `10, x64.

**Comment by tomjn** [comment]
Note that htaccess is for Apache severs and VVV uses Nginx, have you tried setting those values from within PHP in `wp-config.php`? You shouldn't need to modify `php.ini`, but if you did it would impact all VVV sites

**Comment by cagross** [comment]
> Note that htaccess is for Apache severs and VVV uses Nginx, 

Got it, thanks for the reminder.

> have you tried setting those values from within PHP in wp-config.php? 

No, that's the thing--I have not tried that yet.  I was kind of hoping to determine the correct protocol now, while I have the time to kill, rather than at the time I need to implement these edits.  But give me a day or two and I can try to test this on my end.  I'll reply back here with results.

> You shouldn't need to modify php.ini, but if you did it would impact all VVV sites

Got it.  I would hope to avoid this situation.

**Comment by tomjn** [comment]
PHP is installed via a utility, I don't believe there's a way via `vvv-custom.yml` to replace the `php.ini`. Modifying it inside the VM will work but changes won't persist between provisions.

Keep in mind though that different versions of PHP will have different `php.ini` files, and modifying them will change it for all sites using that version of PHP. I don't foresee this changing even with a custom php.ini option.

For now I'd recommend using `ini_set` in `wp-config.php` for site specific changes -
 https://secure.php.net/manual/en/function.ini-set.php

**Comment by tomjn** [comment]
> which of the four changeable modes does that correspond to?

I don't know, you'd have to look it up on php.net, but the table on that page seems to have the answer so I don't understand. Eitherway that's not a VVV thing

**Comment by cagross** [comment]
OK.  We can consider this resolved.  But just to give some info, I actually wasn't able to change any of my parameters using `ini_set()`, nor could I get the example on the [man page](https://secure.php.net/manual/en/function.ini-set.php) to work.  This is a little out of my domain though, so there could definitely be some user error at play here.  Again though, I'm fine moving forward with the default values.
