### ISSUE TITLE
[Fixed] Persisting network issue. Could not resolve hosts.

### ISSUE THREAD

**Issue by makemagik** [Varying-Vagrant-Vagrants/VVV#1452]
Newbie alert probably. 

## Expected Behavior
SIte works. Not Could not resolve host issue in the console. 

## Current Behavior
Lots of network issues in console. Could not resolve host: github.com for example

## Possible Solution
No idea. I remove the vagrant machine. Updated vagrant. Deleted and updated virtualbox. Delete the box in VirtualBox to make sure to load a new box. 

Started from zero. Still no luck. I am thinking this is not a VVV related issue. I spent the whole day trying various fixes from github issues in this repo and others. I think there's a network issue since I've started from scratch but I have no idea how to troubleshoot. Any help would be appreciated.

Sometimes it will load without any problem from github.com, sometimes not. This not only happens on github. I couldn't even load the vagrant machine at first (network error)

`    default: Network connection not detected. Unable to reach google.com...`
`      default: No network connection available, skipping package installation`
`  ==> default: Running provisioner: utility-source-core (shell)...`
`      default: Running: /var/folders/yd/9_0wd_lx0pl6pcwxv2tlzzj00000gn/T/vagrant-shell20180320-2189-oswmye.sh`
`      default: Updating core resources...`
`      default: fatal: unable to access 'https://github.com/Varying-Vagrant-Vagrants/vvv-utilities.git/': `  `  Could not resolve host: github.com`
`      default: Already on 'master'`
`      default: Your branch is up to date with 'origin/master'.`

## Context
Just trying to setup back new site in Vagrant and couldn't.

## Your Environment
* VVV version: latest, 2.1.0
* VVV Git Branch: master
* Vagrant version: 2.03
* VM Provider name: VirtalBox
* VM Provider version: 5.2.8
* Operating System and version: MacOS 10.13.2

**Comment by tomjn** [comment]
Does this happen with the `develop` branch? Does a system reboot help?

**Comment by makemagik** [comment]
@tomjn I did try to reboot many times. Doesn't help. 

I haven't try the develop branch. should I give it a try?

**Comment by tomjn** [comment]
Yes, the next step would always be to see if it happens on the `develop` branch too.

Other things to note:

 - Do you have an unusual or non-standard network configuration? VPNs? Proxies
 - Have you ever had a working instance of a VirtualBox or Vagrant machine? VVV or otherwise?
 - Are there any other VMs running?
 - Do you have security software that might be blocking this? Such as Firewalls or antivirus?

> Could it be a wifi problem, or network setup on osx ?

Yes, but this is rare, and if that is what's happening then the amount of support that can be given over the internet isn't going to be very much. In these situations the problem is hyper specific to the person with the issue, either because of software installed, config options set long ago, or network security policies.

As for troubleshooting guides, there's what's on the main VVV docs site, but given that network errors happen immediately, none of VVV has even started yet.

My initial instinct would be to destroy and recreate the box, [see starting from fresh here](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/)

**Comment by makemagik** [comment]
Hey @tomjn, thank you so much for getting back to me. I understand this is a very particular issue and that I'm mostly on my own.

Do you have an unusual or non-standard network configuration? VPNs? Proxies
**Nope**
Have you ever had a working instance of a VirtualBox or Vagrant machine? VVV or otherwise?
**Yes, everything was working fine. I've done a setup last week and worked a few days on a local project. Yesterday I tried to add a new project and everything would fail. This is where my journey begins.**
Are there any other VMs running?
**Nope, not that I can see from VirtualBox GUI**
Do you have security software that might be blocking this? Such as Firewalls or antivirus?
**Nothing special around here. Maybe the MacOS firewall playing, but I've never had problems before.**

The old sites that I've setup last week are still working. The provisioning from the new sites didn't work.

==> default: Running triggers before halt...
Database ______ backed up...
Database ______ backed up...
Database ______ backed up...
Database wordpress_default backed up...
Database wordpress_develop backed up...
Connection to 127.0.0.1 closed.

I see 3 database of my old project being backed up, but none of the new sites I've created are showing.

Yesterday, I did follow this tutorial to start fresh. I'll give it another try on the develop branch.

**Comment by tomjn** [comment]
> The old sites that I've setup last week are still working. The provisioning from the new sites didn't work.

Ah so this is an existing VVV instance that has been working in the past? Let me know how it goes with the `develop` branch

**Comment by makemagik** [comment]
Yes it worked. 

Currently running the whole troubleshoot settings. At `vagrant up --provision`, starting to get these messages:

    default: Error: The site you have requested is not installed.
    default: Run `wp core install` to create database tables.
    default: Adding domains to the virtual machine's /etc/hosts file...
    default:  * Added local.wordpress.dev from /srv/www/cyber/provision/vvv-hosts
    default:  * Added local.wordpress.test from /srv/www/cyber/provision/vvv-hosts
    default:  * Added cyber.test from /vagrant/vvv-custom.yml
    default:  * Restarting nginx nginx

I was thinking the provision flag would create the DB if it wasn't created. It doesn't look like it's the case.. Should I `vagrant ssh` and try to fix it manually by running `wp core install `?

The provision just finished, my older sites still works. The sites that doesn't work are still listed on the vvv.test homepage. When I try to go to a site that doesn't work, I get this:

`Problem: Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision.
`
`Note, sometimes this is because provisioning hasn't finished yet, if it's still running, wait and refresh the page. If that doesn't fix the issue, see here for troubleshooting steps`

I'll try switching over to the develop branch and let you know.

Thanks again for your time, it's very appreciated.

**Comment by makemagik** [comment]
Another weird thing, when I do the vagrant destroy, I get that weird SSH error. I don't suppose it's normal?

```
vagrant destroy
==> default: Running triggers before destroy...
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.
```

**Comment by tomjn** [comment]
> Another weird thing, when I do the vagrant destroy, I get that weird SSH error. I don't suppose it's normal?

That's just triggers, I assume you halted the VM before running vagrant destroy?

> default: Error: The site you have requested is not installed.
> default: Run `wp core install` to create database tables.
> default: Adding domains to the virtual machine's /etc/hosts file...
> default:  * Added local.wordpress.dev from /srv/www/cyber/provision/vvv-hosts
> default:  * Added local.wordpress.test from /srv/www/cyber/provision/vvv-hosts
> default:  * Added cyber.test from /vagrant/vvv-custom.yml
> default:  * Restarting nginx nginx

I presume this is from the provisioning of `cyber.test`? It sounds like a previous attempt to run `vvv-init.sh` installed a copy of WordPress but didn't finish the setup step. I'm assuming `cyber.test` uses the custom site template? Deleting that site from the file system then reprovisioning should fix that, or manually installing

> Problem: Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision.
> Note, sometimes this is because provisioning hasn't finished yet, if it's still running, wait and refresh the page. If that doesn't fix the issue, see here for troubleshooting steps

The dashboard is the default thing nginx serves. If it's served on a different domain then this shows up, as its the dashboard that gets loaded if something doesn't provision, e.g. if something fails during the sites `vvv-init.sh` run. Probably related to your previous attempts to provision

**Comment by makemagik** [comment]
Yes I halted the VM before vagrant destroy. That make sense.

Alright, I deleted the `cyber` folder inside the `vagrant-local/www` folder.

Trying to `vagrant up --provision` as we speak. I'll let you know how it goes.

Here's my code inside `vvv-custom.yml` - do you see any issues?

```
  cyber:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    skip_provisioning: false
    hosts:
      - cyber.test

```

Thanks again,

**Comment by tomjn** [comment]
>     repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git

There's your problem, `vvv-wordpress-default` is legacy/deprecated. New installs use `custom-site-template`. This is because that repo only works for the default site, it isn't flexible enough to handle different URLs and setups

Follow the instructions here:

https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/

**Comment by makemagik** [comment]
Wait, you are totally right. I went ahead and deleted the files in `~/vagrant-local/www/`

Changed the template, and run provision again, and everything is fine. Wow. That was stupid.

I can't thank you enough for your time,

**Comment by tomjn** [comment]
No problem, what you did makes sense to do from first appearances, hopefully this kind of stuff can be flagged automatically by VVV, it's just figuring out how to do that
