### ISSUE TITLE
Does vvv support local ssl certs.

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1453]
This isn't relaly a support issue but rather a question if vvv supports local ssl certs to be used for WordPress.

**Comment by tomjn** [comment]
Yes, switch to the `develop` branch and [follow the instructions](https://varyingvagrantvagrants.org/docs/en-US/references/https/)

**Comment by benlumia007** [comment]
i think i should have asked is even if it supports ssl certs for https. does it turn into a green padock  I have seen other local environemtns allows you to do that.

**Comment by benlumia007** [comment]
no I am using vvv as a local development. i just never noticed that this was supported, so i try to follow the article but doesn't seem to take affect not sure what i did wrong just yet. till figuring itout.

**Comment by benlumia007** [comment]
after doing it tells me to do, do i need to install the ca.cert, or the dev.cert to the local machine..  or do i need even do that. Im on a windows 10 OS..

**Comment by tomjn** [comment]
You need to be on the `develop` branch, the certificate authority utility was only recently created

If you don't add the root certificate, it'll warn when you visit `https` URLs for the first time, but once dismissed it'll never pop up again, so that step is optional

Also, just because VVV can serve https doesn't mean WP knows to use it. You still have to migrate your sites over

**Comment by benlumia007** [comment]
sorry to keep bugging you on this, even if i did exactly what the instruction said and what you mention, but copying  for example trulyawesomeness.test cert to the trusted root certificate, it still won't let me get the padlock (green), so im not sure how you did it, but i probably am missing something or something rather. I think the article doesn't really explain on how to get it to work, it just expect us to know how. but i guess i understand why.  even if i add the root certificate not sure which one but its still says not secure.

Thanks anyways.

**Comment by tomjn** [comment]
> sorry to keep bugging you on this, even if i did exactly what the instruction said and what you mention, but copying for example trulyawesomeness.test cert to the trusted root certificate

Only the CA certificate can be copied over, copying the individual sites is insufficient, and isn't what the instructions say to do:

<img width="842" alt="screen shot 2018-03-21 at 23 09 21" src="https://user-images.githubusercontent.com/58855/37742290-ee1bb40a-2d5c-11e8-93ef-94d17a22d6fe.png">

All the site certificates are signed by the root certificate, hence accepting the certificate authority root certificate, not the site certificate. Adding the certificates in any of the other folders won't work, those are not root certificates.

> , it still won't let me get the padlock (green), so im not sure how you did it, but i probably am missing something or something rather. I think the article doesn't really explain on how to get it to work, it just expect us to know how. but i guess i understand why. even if i add the root certificate not sure which one but its still says not secure.

You didn't add the root certificate though, you added individual site certificates. But as I mentioned, adding the root certificate is 100% optional.

However, I suspect this has more to do with your browser:

 - Which browser are you using?
 - If you don't see what I saw in the screenshot above, what do you see?
 - What is the error message?
 - What does not having the green padlock prevent you from doing?

**Comment by tomjn** [comment]
The root certificate doesn't represent a site, it represents the certificate authority, and signs each site, it should be named `VVV INTERNAL CA`:

<img width="545" alt="screen shot 2018-03-21 at 23 14 46" src="https://user-images.githubusercontent.com/58855/37742509-d542f028-2d5d-11e8-9837-b9bcfef3be2e.png">

**Comment by tomjn** [comment]
<img width="367" alt="screen shot 2018-03-21 at 23 16 37" src="https://user-images.githubusercontent.com/58855/37742539-f01db05e-2d5d-11e8-8897-f683d348943e.png">

Which should result in the above once it's trusted. Note that I never told it to trust the `simon.test` certificate. My OS trusts the `VVV INTERNAL CA` root certificate. `simon.test` is trusted and gets the green padlock because its certificate is signed by the root certificate which I told my computer to trust. The exact steps for how to do this are operating system specific, you will need to consult google, and may differ from version to version.

If I don't tell me computer to trust the root certificate, it'll warn my the first time I visit `simon.test`, but only **once**. I can dismiss the warning and it will never appear again.

**Comment by tomjn** [comment]
Here's Firefox visiting `simon.test` for the first time:

<img width="1005" alt="screen shot 2018-03-21 at 23 20 53" src="https://user-images.githubusercontent.com/58855/37742701-96a71956-2d5e-11e8-9948-0f841d89c067.png">

Notice the error message, it's not complaining that the certificate is broken, it's complaining about the issuer. Firefox saw `VVV INTERNAL CA`, and went `who?! never heard of them`

I can add an exception, or I can go into settings and security and add the root certificate. In doing so, all certificates generated from it are trusted.

Keep in mind that if I do this, it looks different in the address bar:

<img width="354" alt="screen shot 2018-03-21 at 23 25 20" src="https://user-images.githubusercontent.com/58855/37742818-29f88ba4-2d5f-11e8-864b-a73a23602f7c.png">

But if I had added a security exception, I would still be able to do all the things necessary. So be specific, if you're not getting a green padlock, say what you do get, which browser, with screenshots, and what the error message is

Safari shows a padlock but it isn't green:

<img width="613" alt="screen shot 2018-03-21 at 23 28 51" src="https://user-images.githubusercontent.com/58855/37742936-aaa71e8c-2d5f-11e8-889f-e84be79a1293.png">

For that you'll need an extended validation certificate, and those are expensive. The TLS CA utility won't generate those:

<img width="601" alt="screen shot 2018-03-21 at 23 30 28" src="https://user-images.githubusercontent.com/58855/37742974-deff6658-2d5f-11e8-9157-52174f9f8358.png">

So be wary of relying on icons to indicate success

**Comment by tomjn** [comment]
Also keep in mind that only the `custom-site-template` was changed to support https. If you're using an older install that still uses `wordpress-default` and hasn't switched to the new custom site template, it won't pick up and serve the certificates VVV generates

**Comment by benlumia007** [comment]
@tomjn 
I want to thank you for taking time to help me out with this, it has been quite interesting with try and error type of the thing. I have found out that when installing the `ca.crt` for windows 10, apparently I cannot install it as  local machine, rather than the current user for the certificate to work properly for some reason, again, as the article says depends on the environment. 

When that was added, Edge, Google chrome and opera seems to work properly with the cert, but again with Mozilla, i think it needs to be set up in the security settings through the mozilla to work. 

I GOT IT TO WORK.. thanks

**Comment by benlumia007** [comment]
that was the first domain.test to get going, so if i were to create a new domain.test now, everything should work properly without need to copy crts again. since its only based on the type of the environment I am using.

**Comment by tomjn** [comment]
yay, I didn't know until I did above that firefox maintained its own list of trusted root authorities. I get the feeling the HTTPS subpage will probably need to be a sub-section

**Comment by tomjn** [comment]
> that was the first domain.test to get going, so if i were to create a new domain.test now, everything should work properly without need to copy crts again. since its only based on the type of the environment I am using.

Yes, once you've told your machine to trust the root certificate, all the site certificates generated from it are trusted. It's the classic `ah VVV INTERNAL CA vouched for this, the certificates all good`

**Comment by benlumia007** [comment]
@tomjn 
got a dumb question. well not really a dumb question. so i got everything to work with ssl and works great on Windows and Mac, do you know if this actually works on Ubuntu + Vagrant + VirtualBox. It seems like it doesn't create a sandbox folder inside of certificates when using Ubuntu, not sure if this is just something that's not working in Ubuntu or just no featured added.

**Comment by tomjn** [comment]
> got a dumb question. well not really a dumb question. so i got everything to work with ssl and works great on Windows and Mac, do you know if this actually works on Ubuntu + Vagrant + VirtualBox.

I'm not aware of any reason it wouldn't, This all runs inside the VVV machine, not on the host. Host operating system shouldn't be relevant

> It seems like it doesn't create a sandbox folder inside of certificates when using Ubuntu, not sure if this is just something that's not working in Ubuntu or just no featured added.

I'm not sure what you mean by the sandbox folder
