### ISSUE TITLE
inclusion of wimg's PHPCompatibility sniffs (or similar)

### ISSUE THREAD

**Issue by jshwlkr** [Varying-Vagrant-Vagrants/VVV#1455]
https://github.com/wimg/PHPCompatibility
https://make.wordpress.org/tide/2018/03/21/tide-chat-summary-march-20th/  
  
This may or may not be useful, but it seems to be finding its way into the recommended toolbox for WP developers.

**Comment by jshwlkr** [comment]
Sure.

**Comment by tomjn** [comment]
Thanks :D
