### ISSUE TITLE
My Vagrant box will not provision

### ISSUE THREAD

**Issue by danemorgan** [Varying-Vagrant-Vagrants/VVV#1457]
Two days ago while connected via SSH to my vagrant box, I noticed a message that there were updates available for Ubuntu and I typed the command to update. I suspect that was the wrong thing to do, and from that point, things went horribly wrong. I could no longer bring vagrant up.

I have been searching and trying to fix this for two days. I finally uninstalled VirtualBox, Vagrant and VVV, then reinstalled all three, but I'm still getting the same errors and can no longer start the vagrant box at all.

I'm not very good at Linux or server administration at all, and this is just beyond me. But I really need to get back to work. I have client work I need to do. I'm hoping someone can help me get this going again.

## Expected Behavior
Vagrant starts up and I get to work on my local websites.

## Current Behavior
Provisioning terminates with errors

## Steps to Reproduce (for bugs)
1. type vagrant up --provision

## Full provisioning log
https://gist.github.com/danemorgan/985488b25fe37783e418b0993f7dab94

## Your Environment

* VVV version:  2.1.0
* VVV Git Branch: master
* Vagrant version: 2.0.3
* VM Provider name: Virtual Box
* VM Provider version: 5.2.8
* Operating System and version: Windows 10

**Comment by tomjn** [comment]
> I noticed a message that there were updates available for Ubuntu and I typed the command to update. I suspect that was the wrong thing to do, and from that point, things went horribly wrong. I could no longer bring vagrant up.

Correct, VVV provisions on top of a base box. To update Ubuntu you update the base box and reprovision. Doing that isn't so simple though, and sometimes newer Ubuntu distributions have bugs that take a while to fix, help testing is needed. Additionally databases are stored inside the VM at the moment so recreating the VVV machine would eliminate those.

Best to keep things as is and let the provisioner handle things. Afterall VVV is intended as a local dev tool, and shouldn't be exposed to other computers or running on a realworld server

>  default: /tmp/vagrant-shell: line 47: git: command not found

There's your problem. You could SSH in and run `sudo apt-get install git`, then retry, retracing steps. But in your case I would recommend destroying the box and recreating it. Running the provisioner on a broken box won't fix things if you've messed up the underlying parts

```
vagrant destroy
vagrant up --provision
```

Keep in mind that this will destroy the VM completely, with all its contents. Your file system should be fine as that's mapped into the VM from the host machine, but your databases might not survive. VVV creates backups if you have triggers setup, so you might be good. If those don't exist, you can start SSH into the VM and manually retrieve them via CLI

**Comment by danemorgan** [comment]
Thanks tomjn. At this point I have destroyed and provisioned several times.

I've even completely uninstalled and reinstalled Virtual Box and Vagrant. And after that I am getting this error.

It seems to me that for some reason, Virtual Box isn't giving my Vagrant Box an internet connection, so the provision isn't installing any of the packages.

But I don't know why the Internet connection isn't there.

The first time I installed this I don't recall having to do anything in that regard, and I can't figure out what to do now.

**Comment by tomjn** [comment]
have you tried deleting all the cached vagrant boxes via the vagrant command? Sounds like it's an incomplete cleanout

**Comment by tomjn** [comment]
Also don't forget to reboot after installing/uninstalling, it may look optional, but it's mandatory if you want things to work correctly, especially where networking is concerned. ( even on a mac )

**Comment by danemorgan** [comment]
I have been rebooting after uninstalls and installs, but I have not tried clearing a Vagrant cache. I will look for the command.

Would that cache persist after an uninstall/reinstall?

**Comment by danemorgan** [comment]
`C:\Users\danea\vagrant-local\VVV (master -> origin)
λ vagrant global-status
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
-f was unexpected at this time.`


And I still get the same errors

**Comment by danemorgan** [comment]
Also it seems that I can't ssh in and apt-get git, because at this point the box is not running.

I think I'm going to give up on this and go back to an ampps workflow. I really like the idea of the virtual machine and the Linux, but I need to work on work, not on tools.

**Comment by danemorgan** [comment]
What I'm not understanding is, I uninstalled VirtualBox, Vagrant and VVV, then reinstalled them all from scratch and I can't even get it to provision from a clean slate.

**Comment by tomjn** [comment]
There's the VMs themselves but there's the boxes that get downloaded that
are used to create the VMs, vagrant boxes versus vagrant machines. It
sounds like you've been cleaning out the latter but not the former

**Comment by danemorgan** [comment]
Okay. How would I remove those? I found vagrant global-status --prune which I thought would be what you were suggesting.

**Comment by danemorgan** [comment]
I did `vagrant global-status` and got back this
`
id       name    provider   state   directory
------------------------------------------------------------------------
127ea48  default virtualbox running C:/Users/danea/vagrant-local/VVV

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
`
Then I did `vagrant destroy 127ea48` and got back
`
==> default: Running triggers before destroy...
bash: vagrant_destroy: command not found
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: [vagrant-hostsupdater] Removing hosts
-f was unexpected at this time.
`

Another `vagrant global-status` got
`
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
`

At this point my .vagrant.d\data\machine-index\index file has
'{"version":1,"machines":{}}'

I did `vagrant box list' and got back
`ubuntu/trusty64 (virtualbox, 20180315.0.0)`

Doing `vagrant box remove ubuntu/trusty64` got me
`
Removing box 'ubuntu/trusty64' (v20180315.0.0) with provider 'virtualbox'...
`
And another `vagrant box list' got me to
`There are no installed boxes! Use `vagrant box add` to add some.`

Next, I did a `vagrant up --provision'

And I got another failure.
https://gist.github.com/danemorgan/a36a2682ea2f64118d611879b6e03816

Can we please reopen this so that others might take a look? Or if there is a better place for me to seek support on this, where should I move to?

**Comment by danemorgan** [comment]
No. I use gitbash & cmder. I have them both set to run as administrator.

**Comment by tomjn** [comment]
I ask because your log starts with `-f was unexpected at this time.` which is powershell lingo related to `stderr` vs `stdout`, are you sure `cmder` isn't acting as a UI to a powershell environment?

Also can you check what the network adaptor settings are via VirtualBox? Mine look like this, though I've done nothing special to it:

<img width="641" alt="screen shot 2018-03-30 at 23 49 17" src="https://user-images.githubusercontent.com/58855/38156341-104cb1f4-3475-11e8-99af-ea6b93fe9bfa.png">
<img width="648" alt="screen shot 2018-03-30 at 23 49 21" src="https://user-images.githubusercontent.com/58855/38156342-1068105c-3475-11e8-8ed2-d148311be716.png">


Additionally, have you verified that the IP used by VVV isn't already present on the network?

```
defaults = Hash.new
defaults['memory'] = 2048
defaults['cores'] = 1
# This should rarely be overridden, so it's not included in the default vvv-config.yml file.
defaults['private_network_ip'] = '192.168.50.4'
```

**Comment by tomjn** [comment]
According to https://github.com/cmderdev/cmder cmder can emulate multiple varieties of shell, which one is yours set to use? I cannot vouch for vagrant running correctly on all of them, and I'm unfamiliar with the `cmder` application

**Comment by tomjn** [comment]
If it's an IP clash, changing this line:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L259

```
  config.vm.network :private_network, id: "vvv_primary", ip: vvv_config['vm_config']['private_network_ip']
```

to:

```
  config.vm.network :private_network, id: "vvv_primary",  type: "dhcp"
```

may correct that issue, but it's untested

**Comment by danemorgan** [comment]
> Additionally, have you verified that the IP used by VVV isn't already present on the network?

How do I do this?

**Comment by danemorgan** [comment]
I just tested it and I get the -f when I usr cmd.exe.

**Comment by danemorgan** [comment]
Well, I don't understand another thing now. My Vagrantfile is not the same as the one at https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile

I did a git pull master, and it says I am sync'd with master, but my file is different.

Line 259 was on lin 207 for me and it was 
```config.vm.network :private_network, id: "vvv_primary", ip: "192.168.50.4"```

**Comment by tomjn** [comment]
That's because you're using the master branch not the develop branch. Did
you try the dhcp change I mentioned? Update to the develop branch and see
if the change males a difference

As for checking for clashes, find out if there is something with that IP on
your local network already, how you'd do that is platform specific though

**Comment by danemorgan** [comment]
I reset my PC and reinstalled everything from scratch and still cannot get Vagrant to provision.

I genuinely appreciate your time and attention @tomjn But I've installed Docker and have sites up and running. I'm going to go that route for now.

**Comment by tomjn** [comment]
Sorry to hear, I'm going to close this out for now, if you ever look into it again or have different results, let us know
