### ISSUE TITLE
Vagrant Hosts Updater v1.1: hosts file never changes in Windows 10

### ISSUE THREAD

**Issue by AlexandroPerez** [Varying-Vagrant-Vagrants/VVV#1458]
VagrantBox `5.2.8`
Vagrant: `2.0.3`
Windows 10 `Version 1709 (OS Build 16299-309)`
vagrant-hostsupdater `(1.1.1)`
vagrant-triggers `(0.5.3)`
vagrant-vbguest `(0.15.1)`

So I have spend the last 2 days trying to get VVV to work, but I just couldn't. Then while writing a long list of failed attempts that included uninstalling, re-installing, upgrading, downgrading, restarting, issues #664 and #1390 😱😩💥 💢 ❗️ ❓... that I was going to post as an issue to ask for help, I realized the hosts file in Windows never changed.

So I opened my browser and went to http://192.168.50.4/, and there it was, access to the VM was there all along. So, I opened my hosts file, and added 
```
192.168.50.4 vvv.test
192.168.50.4 local.wordpress.test
```
and was able to finally access each site. So this means I have to manually change the hosts file for every site. 

BTW, I made sure to run 
```
cacls %SYSTEMROOT%\system32\drivers\etc\hosts /E /G %USERNAME%:W 
```
as instructed in https://github.com/cogitatio/vagrant-hostsupdater but that didn't change anything. Is this an issue coming from the vagrant-hostsupdater plugin?

**Comment by AlexandroPerez** [comment]
Also a suggestion: Wouldn't it be a good idea to add this sort of problem to the troubleshooting section? I would be willing to add it. It would say something among the lines of:

> If http://vvv.test is inaccessible, try `vagrant ssh` and if it works, now try http://192.168.50.4 in your browser. If accessible, your hosts file may need to be modified manually.

**Comment by tomjn** [comment]
I'm not aware of this issue, if hosts updater is installed correctly but
not working then that's a hosts updater issue, there's nothing that can be
done from the VVV side

**Comment by tomjn** [comment]
Also, do you have any software that might be interfering or restoring the hosts file? E.g. if you try to `vagrant up` while running gas mask on MacOS, Gas Mask overwrites the hosts updater changes. Security software such as a firewall or antivirus could be doing this, or custom DNS software

**Comment by tomjn** [comment]
And can you confirm that you're running in an admin/elevated privilege command prompt?

**Comment by exlame** [comment]
I got the same error with the new version of vagrant-hostsupdater.
Resolved with version 1.0.2
`vagrant plugin install vagrant-hostsupdater --plugin-version=1.0.2`

**Comment by AlexandroPerez** [comment]
@tomjn I can confirm I used `vagrant up` running both cmd and PowerShell as administrator, but neither worked. Also, I can confirm that downgrading to vagrant-hostsupdater version `1.0.2` works just @exlame 
 explains. The hosts file is being edited as necessary.

I can also confirm that by running the following command in an elevated command prompt:
```
cacls %SYSTEMROOT%\system32\drivers\etc\hosts /E /G %USERNAME%:W 
```
Allows me to run `vagrant up` in a regular command prompt.

**Comment by tomjn** [comment]
Interesting, in that case it's probably a vagrant hostsupdater issue then, we should look into getting that command into the docs along with extending the troubleshooting section

I'm going to mark this as closed for now

**Comment by exlame** [comment]
FYI
vagrant-hostsupdater released version "1.1" four days ago with 1 year of inactivity. So we might need to stay on 1.0 until they fix every bugs...

https://github.com/cogitatio/vagrant-hostsupdater/releases

**Comment by tomjn** [comment]
btw if someone with these issues can open a ticket on that repository so it gets fixed? I suspect the project maintainers are unawares

**Comment by tomjn** [comment]
Reopening to prevent duplicate issues, opened an issue with hostsupdater at https://github.com/cogitatio/vagrant-hostsupdater/issues/160

**Comment by tomjn** [comment]
Closing this as there's nothing we can do from the VVV side
