### ISSUE TITLE
Adding Redis to VVV - what is correct host? 

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1460]
I created a utility which adds Redis to my VVV ([link](https://github.com/dingo-d/redis-vvv-utility)).
And when I go to `vagrant ssh` I can run

```sh
redis-cli ping
```
And I get out `PONG` so Redis is up and running (\o/).

Next step was using `predis` so that I can use Redis inside my plugin.

I added it to my composer

```json
"require": {
    "predis/predis": "*"
  }
```
ran `composer update` and it was loaded. Next I went to my plugin and added

```php
<?php
/**
 * The Redis functionality
 *
 * @since   1.1.0
 * @package my_plugin
 */

namespace My_Plugin\Admin;

/**
 * Require Redis autoload
 */
require WP_PLUGIN_DIR . '/my-plugin/vendor/predis/predis/autoload.php';

\Predis\Autoloader::register();

try {
  $redis = new \Predis\Client();

  if ( ENV === 'staging' ) {
    $redis = new \Predis\Client( array(
        'scheme' => 'tcp',
        'host'   => '127.0.0.1',
        'port'   => 6379,
    ));
  } elseif ( ENV === 'production' ) {
    $redis = new \Predis\Client( array(
        'scheme' => 'tcp',
        'host'   => '127.0.0.1',
        'port'   => 6379,
    ));
  } else {
    $redis = new \Predis\Client( array(
        'scheme' => 'tcp',
        'host'   => '192.168.50.4',
        'port'   => 6379,
    ));
  }
} catch ( Exception $e ) {
  die( wp_kses_post( $e->getMessage() ) );
}

$redis_methods = new Redis( $redis );
```

But I got the error:

> PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://192.168.50.4:6379] in my-plugin/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 my-plugin/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 my-plugin/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://192.168.5...', 4)
#2 my-plugin/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#3 .../pub in my-plugin/vendor/predis/predis/src/Connection/AbstractConnection.php on line 155

So I guess the connection settings are not good. Port is ok, because the port in the VVV is 6379 (I think that's default). The difference is that when I type `redis-cli` inside VVV, I get

```sh
127.0.0.1:6379>
```
Now, it points to `127.0.0.1` because I'm inside VVV, but I thought that to the outside I should use the default IP address (`192.168.50.4`). But I'm not sure if this is correct. Also should the scheme be `tcp`, or something else? I also tried putting `10.0.2.15` but no luck.

## Your Environment

* VVV version: 2.1.0
* VVV Git Branch: develop
* Vagrant version: 2.0.2
* VM Provider name: VirtualBox
* VM Provider version: Version 5.2.6 r120293 (Qt5.6.3)
* Operating System and version: MacOS 10.13.3

**Comment by dingo-d** [comment]
Ok, it seems to be working when I put the `127.0.0.1` for the `host` O.o 

I'll close the issue, but if anyone has an explanation as to why feel free to answer...

**Comment by tomjn** [comment]
Note that the 192.168 IP you used is the external IP that gets exposed

**Comment by dingo-d** [comment]
Well, I thought, since the Redis is on a virtual machine, that I need to use that IP so that I can communicate with it.

**Comment by dingo-d** [comment]
Cool, didn't know that. :+1:
