### ISSUE TITLE
Slowish performance - any plans for adding Apache as a reverse proxy?

### ISSUE THREAD

**Issue by tomathyg** [Varying-Vagrant-Vagrants/VVV#1462]
This is more of a feature request/enquiry. I've read (and experienced) that using Nginx and Apache together in a reverse proxy config is optimal for Wordpress. Are there any plans to build this into the provisioning process in VVV?

**Comment by tomjn** [comment]
No, if you'd like to add it, adding it as a custom utility would be the method.

In the meantime, can you clarify what you mean by slowish performance? Is this page generation time? Disk performance? Network performance? DB issues?

> I've read (and experienced) that using Nginx and Apache together in a reverse proxy config is optimal for WordPress

VIP runs with Nginx+batcache and manages to serve billions of webpages with high performance, I'm unsure what benefit Apache would give that couldn't be accomplished via varnish/batcache/nginx caches. Also, keep in mind that VVV is not built to run in production. If you're running VVV on a public facing site you should take it down for security reasons ( we also won't offer support for VVV instances exposed to the open internet, it's intended as a local dev environment )

**Comment by tomathyg** [comment]
I'm using it for local dev, don't worry!

I just find the page loads are a bit slow given that it's a local VM, but perhaps I'm barking up the wrong tree or maybe my expectations are just too high. It's not really any quicker than editing the live site on my cloud server.

I suggested an Nginx / Apache reverse proxy combo because that's what my host (Cloudways) uses, apparently because Apache is quicker at processing PHP, whereas Nginx is quicker with static content.

I'm no expert when it comes to server config, but thought it was worth an ask!

Any tips for speeding up Wordpress on VVV? I'm already using NFS shared folders and have bumped the VM up to 2 cores and 2GB.

Tom

**Comment by tomjn** [comment]
I've never heard of such a performance difference, but if it exists, it's near meaningless with regards to WP performance. Try installing query monitor or going through the usual performance checks.

E.g. switching to Apache might shave 0.1ms off your page load time, but telling the main query to exclude all posts with a particular post meta value might add several seconds or dramatically reduce the sites scalability. This is assuming the Apache vs Nginx theory is correct

**Comment by tomathyg** [comment]
Got my facts slightly wrong there. To clarify, here's the article I read: https://www.hugeserver.com/kb/configure-nginx-reverse-proxy-apache-debian-ubuntu/

I may try to implement this config so that my Vagrant box matches my cloud server more closely (Cloudways have confirmed that this is the configuration they use for Wordpress and their service certainly is fast) as this may simplify things in other areas.

However, I'm sure you're right in suggesting that I need to be looking elsewhere for speed improvements in WP.

I have found VVV extremely useful, by the way. Please don't get me wrong!

**Comment by tomjn** [comment]
Nifty, something you might want to look into though is an obect cache. VVV comes with memcached so dropping the memcached object cache drop-in into your install should provide a significant boost to most sites performance. The same is generally true of most WP installs

**Comment by tomathyg** [comment]
Yeah, I've just discovered Redis (which is more or less equivalent, right?). Memcached is installed on my host too. Will have a good look into object caching. Thanks!
