### ISSUE TITLE
Remove Legacy TLS Certificate for default domains

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1482]
`provision.sh` tries to generate a certificate for vvv.test and the .dev domains that come bundled, but it generates an invalid certificate

Now that we have the TLS CA utility, we can generate usable certificates that way, so we should remove the old certificate code

**Comment by coderaaron** [comment]
Brand new clean install, on first `vagrant up` it fails with:

```
    default: Installing WordPress Stable...
    default: Error: 'wp-config.php' not found.
    default: Either create one manually or use `wp config create`.
    default: Adding domains to the virtual machine's /etc/hosts file...
    default:  * Added local.wordpress.test from /vagrant/vvv-config.yml
    default:  * Restarting nginx nginx
    default: nginx: [emerg] BIO_new_file("/etc/nginx/server-2.1.0.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/server-2.1.0.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
    default: nginx: configuration file /etc/nginx/nginx.conf test failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Looking through the commits on `provision.sh` I ran across d238521 that mentions this

**Comment by tomjn** [comment]
We need to swap this out at https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx.conf#L119 for the `vvv.test`

**Comment by tomjn** [comment]
Closing this for now as `wontfix` now that we've reverted the change, things should be working again for new users
