### ISSUE TITLE
Migrate from Mailcatcher to MailHog

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1485]
Actually the latest release of mailcatcher is of 2016 https://github.com/alexandresalome/mailcatcher/releases.
Mailhog seems more interesting with more stuff and no ruby requirement https://github.com/mailhog/MailHog.

**Comment by dingo-d** [comment]
This script seems to make it work when I run ti from within vagrant: 

```bash
#!/usr/bin/env bash

echo ">>> Installing Mailhog"

# Download binary from github
wget --quiet -O ~/mailhog https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64

# Make it executable
chmod +x ~/mailhog

# Make it start on reboot
sudo tee /etc/init/mailhog.conf <<EOL
description "Mailhog"
start on runlevel [2345]
stop on runlevel [!2345]
respawn
pre-start script
    exec su - vagrant -c "/usr/bin/env ~/mailhog > /dev/null 2>&1 &"
end script
EOL

# Start it now in the background
sudo service mailhog start
```

I found it here: https://gist.github.com/varghesejacob/68caf7aeee53305a1ffa#file-mailhog-bash-script

I can access it on `vvv.test:8025` port

I just need to test if the emails are caught when I send them from local WordPress.

**Comment by jonathanbossenger** [comment]
@dingo-d Are the mails actually sending from WordPres? I seem to recall this may be related to the nginx server name being set to _

**Comment by tomjn** [comment]
PHP configs need ammending to use `mhsendmail`. https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1543 installs Mailhog though it doesn't do the last part setting up the service yet

**Comment by tomjn** [comment]
See also https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/17

**Comment by jonathanbossenger** [comment]
Gotcha, I'll follow along and see if there's anywhere I can lend a hand.

**Comment by tomjn** [comment]
MailHog now replaces Mailcatcher in `develop`
