### ISSUE TITLE
Move MySQL storage back to a shared folder

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1497]
For VVV 3, storing the database files inside the VM will cause data loss every time `vagrant box update` is ran.

Since we'll be relying on prebuilt boxes this data needs to move back to a shared folder.

It would also be a nice to have if we could figure out migrating existing VVV users databases to a shared folder out of the VM, this would allow us to implement this in an earlier version such as v2.3 making it easier to move to VVV 3

**Comment by Mte90** [comment]
We need really this?
Actually for that part I am using the trigger plugin that on shutdown generate the dump of db and when I do a `vagrant destroy` this files are present.
Later on `vagrant up` this dumps are reimported on the new VM without problems. 
The only problems I see is with the WP develop site that seems not to be backupped.

**Comment by Mte90** [comment]
You are right with a box update the db will be a problem but right now we do a box update too and with the dump of the db reimported at every boot this problem is easily fixed.
So the mysql files are not very useful but the sql dump are very a lot that can be synced or edited easily in case.
