### ISSUE TITLE
After git pull on the develop branch I had an error saying the version of box I was using was not current enough, what followed was probably some forced errors on my part.

### ISSUE THREAD

**Issue by eno812** [Varying-Vagrant-Vagrants/VVV#1506]
## Expected Behavior

I performed a git pull and after that, I received an error message telling me my vagrant box was not a late enough version. 

I then tried to update the box with the vagrant box update but that command would not work. 

I then downloaded and installed the latest box from the vagrant site (Max OS Version) and installed which then led to another error telling me there was a conflict with the vagrant triggers plugin and told me to uninstall, which I did.

Now I get the errors described below.

## Current Behavior

**I get the following error messages when I use vagrant up:**

default: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
    default: 2018/05/15 00:46:26 [emerg] 9543#9543: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
    default: nginx: configuration file /etc/nginx/nginx.conf test failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what.

**These are the errors noted in the output:**

Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.34
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.1.34 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.34
Going on, assuming VBoxService is correct...

## Steps to Reproduce (for bugs)

1. vagrant up
2.
3.
4.

**Here is the output of provisioning:**

https://gist.github.com/eno812/71c5fbe7f927d451592740d569a1852a

## Context

I was just about to work on a clients site and I thought I would do a git pull on the develop branch first. This is when i started recieveing the errors outlined.
I have a fast approaching deadline for this clients site so I would like to get this fixed ASAP.

## Your Environment

* VVV version: 
v2.2.1-git
Mac OS 10.13.4

* VVV Git Branch: 
Develop Branch

* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:
This is what I get when I ssh into the box, 

Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-142-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue May 15 01:06:30 UTC 2018

  System load:  0.0               Processes:           89
  Usage of /:   6.5% of 39.34GB   Users logged in:     0
  Memory usage: 13%               IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.50.4

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

New release '16.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

**Comment by guyromellemagayano** [comment]
This was exactly my problem just few hours ago. But after the latest commit added by @LoreleiAurora in the `develop` branch, the problem was solved - at least in my case. I also have the following versions of the tools for the setup

- VVV version
v2.2.1

- VVV Branch Used
`develop`

- Vagrant Version
v2.1.1

- Current OS & Version
MacOS High Sierra 10.13.4

**Comment by guyromellemagayano** [comment]
Check this issue: #1500

**Comment by tomjn** [comment]
Indeed the issue was resolved in the recent commits to `develop`, it should be enough to:

```
git pull
vagrant halt
vagrant up --provision
```

---

As for boxes, yes, VVV uses an out of date vagrant box, this is expected. I would not recommend updating the box.

VVV 3 will fix this by building a new box with VVV pre-provisioned, so that only the site provisioners run. Updating VVV will involve a `git pull` and a `vagrant box update` followed by a provision. Until then, don't update the box on VVV 2, it might have unexpected consequences, and is untested

**Comment by tomjn** [comment]
Also note that you will need Vagrant 2.1+

**Comment by benlumia007** [comment]
i totally forgot about git pull haha, i keep deleting the develop and re-cloning it lol haah
