### ISSUE TITLE
WARNING! Your environment specifies an invalid locale after entering vagrant ssh

### ISSUE THREAD

**Issue by guyromellemagayano** [Varying-Vagrant-Vagrants/VVV#1507]
Hi again @tomjn. Thanks for the quick response earlier. I just want to raise a minor problem after setting up the latest `develop` branch of VVV. 

![2018-05-15_0922](https://user-images.githubusercontent.com/5119546/40031681-5dce9312-5823-11e8-97c6-282532015f81.png)

This problem came out of nowhere. I found a solution to this problem though by just following the instruction and type the following command: `sudo locale-gen UTF-8` and then i typed `exit` to close the ssh session and after that the error was gone. 

I thought this might be resolved in the next set of commits. It's kind of annoying the first time.

**Comment by tomjn** [comment]
That's certainly unexpected, have you at any point updated the box or done anything with `apt-get`? Or is this the first ssh into a newly provisioned VVV?

**Comment by guyromellemagayano** [comment]
@tomjn No, I haven't used `vagrant box update` after i reinstalled and provisioned VVV. The first time I ssh into the VM, I also didn't update the packages via `apt-get`.

**Comment by benlumia007** [comment]
this is what i get, 

```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-147-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue May 15 03:26:39 UTC 2018

  System load:  0.39              Processes:           106
  Usage of /:   6.0% of 39.34GB   Users logged in:     0
  Memory usage: 13%               IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.50.4

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

New release '16.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```
