### ISSUE TITLE
Newly added websites we're not properly generated by VVV (latest develop branch)

### ISSUE THREAD

**Issue by guyromellemagayano** [Varying-Vagrant-Vagrants/VVV#1513]
Hi @tomjn, I added a bunch of websites from my previous VVV setup via `vvv-custom.yml`, applied the command `vagrant up --provision` and I noticed that the setup itself didnt create the websites during the provisioning. I already installed the vagrant plugins, vagrant-vbguest and vagrant-hostsupdater. Below is the log of that process.

[vvv-provision-log.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/2007882/vvv-provision-log.txt)

Hope you can help me resolve this issue.

**Comment by Mte90** [comment]
Seems that the folders are not generated on the machine.
Are you using the `develop` branch?
An example of your `vvv-custom.yml` file?

**Comment by benlumia007** [comment]
Please use the latest develop #1512  this fixed the problem you are having

**Comment by guyromellemagayano** [comment]
@benlumia007 As it turns out, some workarounds had to be made for a site to be created successfully on my end. 

1.  I had installed `vv` by @bradp for initiating WP site creation. It added the vvv-hosts, vvv-init, wp-cli.yml in the created folder where `htdocs` folder is located. 
2. Before I end the `vv` site creation setup, I make sure to update the `vvv-custom.yml` with the site and its host URL. 

Then after the provisioning process - for some reason, I saw the site I created in the browser. No redirect to [http://vvv.test](url) nor a 404 or 403 error from nginx. At least it works now on my end already. But I had to tap the capabilities of `vv` for my setup to work.

**Comment by Mte90** [comment]
`vv` as I know is not working anymore with VVV 2.x.
Is not requried anymore a script because with the config file is more simple then before and create a lot of issues.

**Comment by tomjn** [comment]
@guyromellemagayano I'd strongly advise against using `vv`, so much so I'm tempted to have VVV detect `vv`'s presence and warn against it with uninstall instructions. `vv` is unmaintained and incompatible and causes lots of issues

**Comment by benlumia007** [comment]
@guyromellemagayano 
Sorry for the late response, i guess time difference, yea, if you told us that  you were using `vv`, i would strongly advise not to use `vv` when VVV 2.0 came out. it works very well in VVV.1.8.4ish, after that, vv didn't work to well and plus, since VVV 2.0, it does almost the same thing as vv

**Comment by tomjn** [comment]
Note that `vv` doesn't work with VVV as it was intended, which shows when upgrading, or when destroying and recreating the box

**Comment by benlumia007** [comment]
yup, i stop using it when VVV 2.0 came out and creating new sites easier enough to do. :)
