### ISSUE TITLE
Update WordPress Coding standard for issue on PHP 7.2

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1521]
since vvv is now using php 7.2 and there are some deprecated functions/features. the WPTRT team may have some fixes regarding the  WP Coding Standard..  if they make or pull a request a fix, does vvv automatically grabs that new update was well.

sorry, hope that make sense.

**Comment by Mte90** [comment]
You are talking about automatically update the coding standard installed inside VVV?
Because the title is not so clear.

**Comment by benjaminlu007** [comment]
yeah the one that's been install inside of vvv.

**Comment by benlumia007** [comment]
@Mte90 
yeah, the coding standard that's been installed inside of VVV. The theme sniffer for WPTRT gets an PHP Deprecated thing that kind of related to PHP 7.2 so yeah.

**Comment by Mte90** [comment]
Changed the title to be more explicative then before, i am not sure if with provision the coding standards are update autoamtically but seems yes https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L619

Are you sure that the coding standard has this issues already fixed? maybe is not a problem of VVV.

**Comment by benlumia007** [comment]
@Mte90 
that's what they are telling me, but i'm not sure if they merge that ticket yet

**Comment by tomjn** [comment]
Composer will update it on provision, if there are issues running the WP Coding standards under PHP 7.2, an issue should be raised over on their github repo
