### ISSUE TITLE
Errno::ENOENT: No such file or directory 

### ISSUE THREAD

**Issue by jeanzi** [Varying-Vagrant-Vagrants/VVV#1527]
## Current Behavior
C:\Users\Zibbin\VVV>vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/Zibbin/VVV/Vagrantfile
Line number: 34
Message: Errno::ENOENT: No such file or directory - git --git-dir="C:/Users/Zibbin/VVV/.git" --work-tree="C:/Users/Zibbin/VVV" rev-parse --abbrev-ref HEAD

## Steps to Reproduce (for bugs)
1. Installed Git with Admin mode
2. Installed VirtualBox with Admin mode
3. Installed Vergrant - Restarted the machine
4. Git - Bash configured username, email id
5. Zibbin@Jean-PC MINGW64 ~
$ git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git
Cloning into 'VVV'...
remote: Counting objects: 8532, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 8532 (delta 4), reused 3 (delta 0), pack-reused 8521
Receiving objects: 100% (8532/8532), 7.08 MiB | 224.00 KiB/s, done.
Resolving deltas: 100% (3610/3610), done.

6.  C:\Users\Zibbin\VVV>vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/Zibbin/VVV/Vagrantfile
Line number: 34
Message: Errno::ENOENT: No such file or directory - git --git-dir="C:/Users/Zibbin/VVV/.git" --work-tree="C:/Users/Zibbin/VVV" rev-parse --abbrev-ref HEAD

## Context
Trying to install Vagrant

## Your Environment
* VVV version: 2.2.2-develop
* VVV Git Branch: https://github.com/Varying-Vagrant-Vagrants/VVV.git
* Vagrant version: vagrant_2.1.1_x86_64
* VM Provider name:  VirtualBox
* VM Provider version: VirtualBox-5.2.12-122591-Win
* Operating System and version:  Windows 10 Pro, Version 1803

**Comment by tomjn** [comment]
When you installed, did you download a zip or did you `git clone`? I'd strongly recommend converting to a git rather than a zip based install, that should resolve the above issue

**Comment by tomjn** [comment]
hmmm strike that last message, is `git` available in your path?

**Comment by tomjn** [comment]
And what happens if you take the git command it failed on and run it directly in that same folder?

**Comment by jeanzi** [comment]
This is what I get
Zibbin@Jean-PC MINGW64 ~/VVV (develop)
$ git --git-dir="C:/Users/Zibbin/VVV/.git" --work-tree="C:/Users/Zibbin/VVV" rev-parse --abbrev-ref HEAD
develop
Zibbin@Jean-PC MINGW64 ~/VVV (develop)
$

**Comment by jeanzi** [comment]
It worked for me. 
I did two things before trying it again.
1. I reinstalled Git with "Use Git with Windows Command Prompt" option.
2. Instead of Git clone command, I directly downloaded the zip file from Github and unzipped inside the folder VVV as a subfolder(im not sure whether it is helping anyway).
Either one or both might have helped.

**Comment by jeanzi** [comment]
Thank you @tomjn for your suggestions.

**Comment by tomjn** [comment]
Unzipping inside as  a subfolder just creates a nested duplicate install, I'm keen to find the actual cause of this, in the future the hope is that all VVV installs are either `git` installs or installs that are just about to be automatically converted into `git` installs, so unless this issue is resolved, you may be seeing a message such as "VVV requires `git`, `git` not found on this system, please install it"
