### ISSUE TITLE
Run vagrant up from a subfolder of VVV

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1528]
## Expected Behavior
Enter the folder `/vvv/www` and `vagrant up` vagrant will start.
I usually do that but seems that with the latest updates now this is not working because there is no search of path based on `Vagrantfile` instead of the folder.

## Current Behavior
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/www/VVV/Vagrantfile
Line number: 21
Message: Errno::ENOENT: No such file or directory @ rb_sysopen - version
```

## Your Environment
* VVV version: last from github
* VVV Git Branch: develop
* Vagrant version: 2.1

**Comment by tomjn** [comment]
What's on line 21 of the vagrant file?

**Comment by Mte90** [comment]
Sorry forgot that: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L21

**Comment by tomjn** [comment]
Hmm if you prepends the string with the value of vagrant_dir to give an
absolute path, does that resolve the issue?

I'm in an airport at the moment so it's difficult to check today

**Comment by Mte90** [comment]
Ahahah no worry I will check later if fix the problem!

**Comment by benlumia007** [comment]
@Mte90 and @tomjn 
Was this issue fixed in one of the tickets. It seems like is working at the moment, but currently using the latest merge #1530. and did not have any issues with it when i have it as followed

`C:\WordPress\develop`

**Comment by tomjn** [comment]
Yeah https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1529 got merged, forgot to close this, thanks for reminding me :)
