### ISSUE TITLE
PHP v7.2 error on PHPMyAdmin

### ISSUE THREAD

**Issue by davidwolfpaw** [Varying-Vagrant-Vagrants/VVV#1535]
I installed a fresh version of VVV yesterday after ensuring that I had the latest version of VirtualBox and Vagrant.

VirtualBox: Version 5.2.12 r122591 (Qt5.6.3)
Vagrant: Version 2.1.1
macOS: Version 10.13.4 (17E202)
VVV: v2.2.1-git::master

As I already had a vagrant install before, I saved database backups and files before destroying it. I then provisioned new sites of the same names as the ones that I wanted to import. 

I opted to use PHPMyAdmin to reimport the database backups that I have. When I navigate to the Import page for any database I get the following notification:

```Some errors have been detected on the server!
Please look at the bottom of this window.```

With the following error:

```
Warning in ./libraries/plugin_interface.lib.php#551
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_import.lib.php#374: PMA_pluginGetOptions(
string 'Import',
array,
)
./libraries/display_import.lib.php#459: PMA_getHtmlForImportOptionsFormat(array)
./libraries/display_import.lib.php#694: PMA_getHtmlForImport(
string '5b0fe9b46da83',
string 'database',
string 'gutenberg',
string '',
integer 1073741824,
array,
NULL,
NULL,
string '',
)
./db_import.php#44: PMA_getImportDisplay(
string 'database',
string 'gutenberg',
string '',
integer 1073741824,
)```

As far as I am aware, I have not made any additional modifications to the install prior to attempting this import. Additionally, if I ignore this warning and import a SQL file, it appears to be working just fine.

This is a new warning implemented in PHP v7.2: http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

<img width="841" alt="screenshot 2018-05-31 08 29 04" src="https://user-images.githubusercontent.com/1971070/40782406-2e37c5e2-64ad-11e8-8e18-c28895b09e40.png">

**Comment by Mte90** [comment]
I can confirm that VVV has some problems with the actual combination of PHP 7.2 and phpmyadmin

**Comment by tomjn** [comment]
Has an issue been raised with PHPMyAdmin about this? I'm loathe to maintain a fork of PHPMyAdmin just for this

**Comment by Mte90** [comment]
https://stackoverflow.com/questions/47668550/error-in-phpmyadmin-after-updating-to-php-7-2-0
seems a common problem but fixed in the latest releases

**Comment by tomjn** [comment]
As an aside, if VVV detects database backups in the backup folder for databases that don't exist/empty it will try to restore them.

Given that PHPMyAdmin runs in a browser, it's not ideal for large SQL files anyway, I recommend using the `mysql` command inside the VM for a more reliable restore

**Comment by tomjn** [comment]
I've updated PHPMyAdmin pending further tests, ideally composer would grab it and it would always be the latest version, but this will do for now

**Comment by tomjn** [comment]
Now that the PR has been merged, delete copy of PHPMyAdmin VVV installs, and reprovision for the updated PHPMyAdmin
