### ISSUE TITLE
Vagrant up automatically destroys VM and associated drivers

### ISSUE THREAD

**Issue by AndyS12** [Varying-Vagrant-Vagrants/VVV#1537]
I am new to Vagrant. I wanted to contribute to WordPress so I needed to install wordpress meta environment. I am installing VVV using this link. I have already installed Oracle VM VirtualBox.

At first installation everything went fine and I was able to use the local.wordpress.test site. I made some tweaks and messed up this url. Unable to solve this, I decided to reiterate the entire installation of VVV. I ran "vagrant up" command, this time everything goes fine, until at last I receive this message
## Expected Behavior
--> Creation of new VM

## Current Behavior

--> After creation,  the VM and associated drivers are destroyed automatically

## Context

I wanted to contribute to WordPress so I needed to install wordpress meta environment. I am installing VVV using this link. I have already installed Oracle VM VirtualBox.

At first installation everything went fine and I was able to use the local.wordpress.test site. I made some tweaks and messed up this url. Unable to solve this, I decided to reiterate the entire installation of VVV. I ran "vagrant up" command, this time everything goes fine, until at last I receive this message
```
 ==> default: Running provisioner: shell...
    default: Running: inline script
    default:  * Restarting nginx nginx
    default:    ...done.
==> default: Running triggers after up...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
/home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/dsl.rb:90:in `method_missing': undefined method `name=' for #<VagrantPlugins::Triggers::DSL:0x0000000003911268> (NoMethodError)
    from /home/andys/vagrant-local/Vagrantfile:525:in `block (2 levels) in <top (required)>'
    from /home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/dsl.rb:11:in `instance_eval'
    from /home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/dsl.rb:11:in `fire!'
    from /home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:52:in `block in fire_triggers'
    from /home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:51:in `each'
    from /home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:51:in `fire_triggers'
    from /home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:18:in `call'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:239:in `action_raw'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:208:in `block in action'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:598:in `lock'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `call'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `action'
    from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
Everything gets created initially, I can see an entry in VM VirtualBox as well. But at last this appears on my terminal and every progress done so far is deleted. I am stuck with this a complete day. I tried many possibilities and couldn't find a solution. Please help me to prevent "vagrant up" from auto destroying the created VM user.

## Your Environment

* VVV version:  2.1.1
* VVV Git Branch:  master
* Vagrant version: 2.1.1
* VM Provider name:  VirtualBox
* VM Provider version: 5.x
* Operating System and version: linux mint Sylvia 18.3

**Comment by tomjn** [comment]
Have you tried running this on the latest VVV? 2.2.1 is the current version, but you're using 2.1.1. Additionally, if this happens on the `develop` branch, can you post a more complete provisioner log? Including the commands that triggered it?

In particular, you're also using the vagrant triggers plugin, a plugin that was deprecated in Vagrant 2.1 after its functionality was merged into core, so:

 - Uninstall the vagrant triggers plugin
 - Make sure you're using the most up to date version of VVV
 - Switch to the `develop` branch
 - Make sure you're using the most up to date version of Vagrant
 - reprovision, and if it fails, send over the full log and the commands used to produce it

**Comment by AndyS12** [comment]
I did exactly as you said............But still getting the same error log on terminal.

1. I cloned the repository.
2. Went into VVV-2.2.1 directory and ran "vagrant up" after uninstalling the vagrant triggers plugin.

As mentioned when I was freshly installing it for the first time, I was successful. But why do I keep getting errors there after. Does it have to do something with multiple installation of VVV??

**Comment by tomjn** [comment]
You should only have 1 install running at a time, just remember to halt your other installs before running `vagrant up`. Can you post a full provisioner log? **Your log is incomplete**

**Comment by AndyS12** [comment]
How can I post the full provisioner log here??........Is it stored in some file ??...........Or are u asking for all the things that are scripted on the terminal while installing??

**Comment by tomjn** [comment]
The full output, if you didn't pipe it to a file, you can copy paste it, use a [gist](https://gist.github.com) and copy the URL in here

**Comment by AndyS12** [comment]
Complete log [https://gist.github.com/AndyS12/199c3ef619c0521316fbad90f9a08001/revisions#diff-ff3f4dac572db811ceceb7ba795baeb7](url)

**Comment by AndyS12** [comment]
[https://gist.github.com/AndyS12/199c3ef619c0521316fbad90f9a08001/revisions#diff-ff3f4dac572db811ceceb7ba795baeb7](url)

**Comment by AndyS12** [comment]
https://gist.github.com/AndyS12/199c3ef619c0521316fbad90f9a08001

**Comment by tomjn** [comment]
Are you sure triggers has been uninstalled?

```
/home/andys/.vagrant.d/gems/2.4.4/gems/vagrant-triggers-0.5.3/
```

That folder does not exist on my machine. I'd also recommend switching to a `git` based install rather than a `zip` based install as it'll be easier to keep updated

This might help:

```
vagrant plugin uninstall vagrant-triggers
vagrant plugin expunge --reinstall --force
vagrant plugin repair
vagrant plugin update
```

**Comment by AndyS12** [comment]
It worked this time. Thanks a lot :). This is my log [https://gist.github.com/AndyS12/f7d1f58430482bb8b417ad723d67a61f](url)

vvv.test is working fine. But when I go to local.wordpress.test it shows me a page saying "Welcome to nginx". Do I still need to edit the vvv.custom.yml file to make that url show my real wordpress site?

**Comment by AndyS12** [comment]
It worked this time. Thanks a lot :). This is my log [https://gist.github.com/AndyS12/f7d1f58430482bb8b417ad723d67a61f](url)

vvv.test is working fine. But when I go to local.wordpress.test it shows me a page saying "Welcome to nginx". Do I still need to edit the vvv.custom.yml file to make that url show my real wordpress site?

**Comment by AndyS12** [comment]
https://gist.github.com/AndyS12/f7d1f58430482bb8b417ad723d67a61f

**Comment by AndyS12** [comment]
Everything worked like charm. A very big thanks to you!!!!. :) :) :+1:  :) :)

**Comment by tomjn** [comment]
@AndyS12 everything still ok?

**Comment by AndyS12** [comment]
Yes sir!!.......Everything is running fine :) :)
