### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by wpalchemist** [Varying-Vagrant-Vagrants/VVV#1538]
## Expected Behavior
After installing VVV and running `vagrant up`, I should be able to go to http://local.wordpress.test/ and see a site.

## Current Behavior
http://local.wordpress.test/ gives me a "server not found" error

## Steps to Reproduce (for bugs)
This is a brand new computer.  I followed the [installation instructions](https://varyingvagrantvagrants.org/docs/en-US/installation/) carefully.  I have destroyed and re-provisioned the machine a few times for good measure, and haven't seen any error messages.

Provisioning output can be seen here: [https://gist.github.com/wpalchemist/9fc3e2463da37e52ee77235c6ee3afc2](https://gist.github.com/wpalchemist/9fc3e2463da37e52ee77235c6ee3afc2)

## Context
I'm just trying to do an initial, out-of-the-box, totally normal installation.

## Your Environment
* VVV version: 2.2.1
* VVV Git Branch: master
* Vagrant version: 2.1.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.12
* Operating System and version: Windows 10

**Comment by tomjn** [comment]
This is because the entries in your hosts file aren't written. The very end of your provision is an error message:

```
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
C:/Users/morga/.vagrant.d/gems/2.4.4/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `initialize': Permission denied @ rb_sysopen - C:/WINDOWS/system32/drivers/etc/hosts (Errno::EACCES)
        from C:/Users/morga/.vagrant.d/gems/2.4.4/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `open'
etc...
```

Are you sure you ran it in a command prompt with elevated priviledges/as an administrator?

**Comment by benlumia007** [comment]
what you will need to do is for the hosts file in Windows 10, u need it to have full permission to be able to write it. 
`C:\Windows\System32\drivers\etc`

then right click on hosts file and go to properties and select Security, highlight Users and click on Edit and give full permission.

![image](https://user-images.githubusercontent.com/11844123/40867928-1478d78e-65bd-11e8-95e3-0f7aa0b6dbab.png)

**Comment by tomjn** [comment]
`vagrant up` will be enough for the very first time, but after that you'll need `--provision` any time you update or change the config/provisioner files

**Comment by wpalchemist** [comment]
Ah ha!  Thank you for the rapid response here! My response has been slow because I've been waiting for the machine to provision.....

Updating the permissions for the hosts file seems to have fixed it, although that really worries me from a security point of view.  I think that from now on, I will edit that manually.

Thanks so much for your help!  I think I still have a few wrinkles to smooth out, so I might be back with more questions.

**Comment by tomjn** [comment]
@wpalchemist out of curiosity, what kind of command prompt are you using? You shouldn't need to modify the permissions on the hosts file, though it might allow you to use non-elevated command prompts

**Comment by wpalchemist** [comment]
I'm using Git bash.

**Comment by tomjn** [comment]
You should be able to right click on git bash and "Run as administrator" which should resolve the issue without changing permissions on the hosts file

**Comment by wpalchemist** [comment]
Ah ha, good to know!  Thanks!

**Comment by benlumia007** [comment]
yeah that's one way, but for me, i tend to forget to run it as administrator, so i just give permission to users.

**Comment by tomjn** [comment]
Closing this out now we know what happened
