### ISSUE TITLE
Integrate Tideways with XHGui

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1540]
An idea for VVV 3.0 is to add more stuff for devs to create a better experience of this box.

Actually we have xDebug but it is missing something advanced for profiling (yes there are plugin and frameworks but they are not perfect).

An idea can be install [Tideways](https://github.com/tideways/php-profiler-extension) inside VVV with the ui from [xhgui](https://github.com/perftools/xhgui).

There are different guides about how to install on ubuntu like http://divyanshu-techbook.strikingly.com/blog/xhgui-for-ubuntu-with-php-7 (the first one I found).

I chosen tideways because is completely opensource (apart the SaaS service that has a better interface of course) and has a service that is not mandatory like for Blackfire.io (that has a free plan only for local developments environment).

I am not sure if vvv-utilities is better so this can be optionally added (maybe we can do the same for blackfire).

**Comment by tomjn** [comment]
It'd end up as a utility anyway, especially since it brings in mongodb requirements. If it ever made it into core VVV it'd be in the core utility

**Comment by Mte90** [comment]
I found this guide better because contain already all the commands https://akrabat.com/installing-xhgui-via-ansible/
There is a way to do the provision only of the utilities to speed up the process @tomjn?

**Comment by tomjn** [comment]
Yes, see the recent comment on the phpmyadmin issue for the command via
--provision-with

**Comment by Mte90** [comment]
this integration is waiting for testing :-)
