### ISSUE TITLE
Bindfs vagrant plugin

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1544]
We should explore the use of the bindfs vagrant plugin for improved performance on shared/mounted file system folders. Trellis/Roots uses it and it might help towards the issues with commands that 'watch' the file system

**Comment by LoreleiAurora** [comment]
agreed, but i wouldn't make this change in 2.X as there should probably only be 1 more release and it could be considered a breaking change.

**Comment by tomjn** [comment]
why would it be a breaking change?

**Comment by LoreleiAurora** [comment]
all shared folders need to be changed to `config.bindfs.bind_folder` in the vagrantfile and installs without the plugin will have no mounted folders.

**Comment by tomjn** [comment]
Or we could wrap that line in an if statement and only run it if the plugin is present?

**Comment by tomjn** [comment]
#1686 does this

**Comment by tomjn** [comment]
Closing this out, this plugin won't do much for performance
