### ISSUE TITLE
Issue with provisioning custom site

### ISSUE THREAD

**Issue by RoseanneC** [Varying-Vagrant-Vagrants/VVV#1545]
## Expected Behavior

I expect to see my site when I go to http://w4zadmin.test/  (I have also tried http://w4zadmin.test/ help.htm as there is not an index page in the root but this doesn't work either)

## Current Behavior

If I go to http://local.wordpress.test/ I can see the site. However if I go to my custom site http://w4zadmin.test/ I see a page with this error message:  "Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision."

I have tried reinstalling this and reprovisioning a number of times. I was assuming that it might be caused by the issues in the output from the provisioning but after a reply to a comment I left earlier about Mailcatcher in another thread - this might not be the case.. I do have another installation of vagrant on my machine and this works fine. I wanted to test this as a separate fresh install to make sure it is all working correctly.

## Steps to Reproduce (for bugs)
Gist showing vvv-custom.yml and provisioning output:
https://gist.github.com/RoseanneC/01dfae0a5fcaf442221baff9c0cc4509.js

## Context

I am not able to get these sites provisioned. I have organised a volunteer day for Wed (two days time) when a number of people will work on this project so I want it to be as easy/quick for everyone to set up as possible so we don't waste a lot of time for everyone.

There are two sites essentially - one is a wordpress install and the second is basically a bunch of php files. These live on a subdomain of the main site (admin.wellsforzoe.org) but it is essentially a standalone site. The admin site has a separate mysql database where we store data to manage the charities operations. But it should be possible to get to the login page without the database part working (so the fact that I haven't set that up yet should not cause an issue)
## Your Environment
* VVV version: fresh install yesterday (10 June 18)
* VVV Git Branch: cloned from here: master git://github.com/Varying-Vagrant-Vagrants/VVV.git
* Vagrant version: Vagrant 2.1.1
* VM Provider name: VirtualBox Version
* VM Provider version: VirtualBox Version 5.2.12
* Operating System and version: Mac OS High Sierra Version 10.13.5

**Comment by tomjn** [comment]
It looks like it's fetching your repository just fine, but I see no provisioner script of any kind gets ran.

Are you sure there's a `provision` folder? It's not enough to just give it a WP folder, it need a public html folder and a `provision` folder with Nginx configs and a script to setup the DB and run the WP installer

See the custom-site-template repo:

https://github.com/Varying-Vagrant-Vagrants/custom-site-template/tree/master/provision

There's a `provision` folder that tells VVV how to set up the site, and a `public_html` folder that gets created to contain the WP install.

Without these VVV won't know how to serve that site, and you'll get the default page which is the dashboard, which has a check on it to see if it's showing on a page that isn't the dashboard

**Comment by RoseanneC** [comment]
ok thank you for that - I was assuming the provisioning hadn't worked so hadn't read past that (although the fact that I could see the pages for the default sites meant provisioning had worked). I have been reading through the documentation but not quite there with understanding how the workflow will work

So for my custom (non-wordpress) site I would need to have the following:
```
w4zadmin:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    #repo: https://password@bitbucket.org/bitbucketpath/wellsforzoe_admin.git
    description: "Wells for Zoe admin site"
    skip_provisioning: false
    hosts:
      - w4zadmin.test
```

I did have our repo there so this just gave me a number of php files for that site - which were not in a folder called public_html. And as you say no provision folder. So on this [page on adding existing sites](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/adding-an-existing-site/) it says to use the custom site template and then just copy the existing files into it. So I would just check out the admin site elsewhere on my machine and then manually copy those files into `w4zadmin/public_html`? So would this need to be done each time the site is re-provisioned? Or can this repo be added in vvv-custom.yml config somehow? If I was to add it into `vvv-init.sh`, it would also get overwritten when re-provisioning right? Or is it recommended to add the provision folder into our wellsforzoe_admin.git repo and change the above back to pull from that repo?

Sorry for all the (basic) questions.

**Comment by tomjn** [comment]
I forget the name of the folder, probably `htdocs`

> So I would just check out the admin site elsewhere on my machine and then manually copy those files into w4zadmin/public_html?

Yes

> So would this need to be done each time the site is re-provisioned?

No, only once

> Or can this repo be added in vvv-custom.yml config somehow?

Not with the `custom-site-template`, the provisioner doesn't have a method for sub-folder git clones

> If I was to add it into vvv-init.sh, it would also get overwritten when re-provisioning right?

Probably, but it'd be better to fork the `custom-site-template` and make your own modifications to `vvv-init.sh`, and since you already have a private bitbucket setup, you could use that for the forked repo and use that in the `repo` field instead

> Or is it recommended to add the provision folder into our wellsforzoe_admin.git repo and change the above back to pull from that repo?

You could do that too, you'd need to move the existing files down into a subfolder so that there's a public html or htdocs folder

> Sorry for all the (basic) questions.

No need to apologise, this is helpful for when I revisit the docs to make things clearer

**Comment by RoseanneC** [comment]
k that is fantastic! I have a much better understanding of it now. It looks like the folder is public_html. So I ran vagrant up with the following config:

```
  w4zadmin:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    description: "Wells for Zoe admin site"
    skip_provisioning: false
    hosts:
      - w4zadmin.test
```

It created the log, provision and public_html folders. I went into public_html and deleted all of the wordpress files it had put in there. (Is there a way to specify not to add those?) Then I cloned our git rep into that directory and can see the page now in the browser :)  (I did see from the doc on [custom paths](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-paths-and-folders/) that I could have put the code elsewhere but makes sense for me to put it there seeing as this doesn't get overwritten when provisioning.

I like the idea of forking the custom site template and adding the provision folder into our repo with any customisations we need. Moving everything else into public_html should be fine too.

So last question hopefully - how do I access phpmyadmin? I presume it is a manual process of exporting the data from my production db and importing it locally? (Unless we do this in vvv-init.sh I guess)

And similarly for importing data into the wordpress install, I have read elsewhere that we'd need to use a plugin like All in One Migration to export it so that you can change the domain name to what it will be locally. Do you recommend this approach?

**Comment by tomjn** [comment]
> So last question hopefully - how do I access phpmyadmin?

There's a link on the dashboard in the sidebar, but you have other options if you prefer an alternative mysql client, just use the same details as `wp-config.php` but swap the host for the VVV machines IP

> I presume it is a manual process of exporting the data from my production db and importing it locally?

Correct

> That's correct (Unless we do this in vvv-init.sh I guess)

You could do that, but you'll need to write a check to make sure all your content doesn't get imported on every provision, only if it's necessary

> And similarly for importing data into the wordpress install, I have read elsewhere that we'd need to use a plugin like All in One Migration to export it so that you can change the domain name to what it will be locally. Do you recommend this approach?

If you're doing an SQL dump then WP CLI can search replace it once it's in the DB on VVV

There's also WP CLI for importing WXR files via the standard importer. I'm unfamiliar with All in One Migration

**Comment by tomjn** [comment]
You might be interested in the Contributor day USB generator repo:
