### ISSUE TITLE
SVN prompt during provisioning of custom-site-template-develop

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1549]
When provisioning, if there is an SVN conflict SVN prompts the user what to do, but this isn't possible during provisioning

**Comment by Mte90** [comment]
I tried right now and is not happened, maybe it is something that now with the git switch is not required anymore.

**Comment by tomjn** [comment]
did you have a conflict though?

**Comment by Mte90** [comment]
no conflicts on my tests, I got one about `package-lock.json` that was on my folder but wasn't involving svn at all.

**Comment by tomjn** [comment]
you'd need to replicate that issue, it happened during contributor days for some people that if provisioning failed, when they tried a second or third time there would be svn conflicts

**Comment by Mte90** [comment]
Right now https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/blob/master/provision/vvv-init.sh use svn only for very old installation of VVV with develop.

I think that we can suggest to erase this install of that provision and start with a new one that will use git.

**Comment by ntwb** [comment]
FYI: I had issues when setting up VVV with the _old_ BuddyPress, WordPress Trunk and Meta Environment sites, SVN would crash for some strange reason.

To fix it I tried SSH'ing into the repo and manually running `svn cleanup` and then `svn up` inside the VM but it would continue to crash every few files.

I resolved it by running `svn cleanup && svn up` in the paths required:

eg: 
• `vvv/www/wordpress-meta-environment/buddypressorg.test/public_html/wp-content/plugins`
• `vvv-meta-environment/www/wordpress-meta-environment/meta-repository/buddypress.org/public_html/wp-content/plugins/bbpress`

Pretty much `cd`ing into any SVN folder and running `svn cleanup && svn up`

**Comment by Mte90** [comment]
maybe there was something too old that created issue with the history, I had too an old installation of the meta environment and wordpress and got no issues.

**Comment by tomjn** [comment]
it's because it asks the user what to do with the conflict but because it's a headless process there's no way to get input so it waits until a timeout happens

**Comment by Mte90** [comment]
So right now we need a way to replicate the issue and find a way to alert the user during the process.

**Comment by Mte90** [comment]
I tried now with removing a folder or changing few files but running the provision will fix everything automatically with svn.
Someone has suggestions about how to create a conflict for the svn version?

**Comment by Mte90** [comment]
Closing for no feedback, we can reopening if the problem happens again.
