### ISSUE TITLE
Document requirement for WP_CACHE_KEY_SALT

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1560]
When using the object-cache.php drop-in, users will see unexpected behaviour (such as being redirected to site A when they attempt to load site B).

To avoid this, one must define `WP_CACHE_KEY_SALT` in `wp-config.php`.

It would be very helpful to put this in the VVV docs.

**Comment by tomjn** [comment]
It would be better to adjust `custom-site-template` to add such a salt to `wp-config.php`, but I don't believe that's something VVV should spend a lot of time documenting, since it's not VVV specific and applies to any WP install

**Comment by paulschreiber** [comment]
@tomjn Adding it automatically sounds even better.

I also filed a ticket requesting the WordPress.org salt service generate this:
https://core.trac.wordpress.org/ticket/44425

**Comment by tomjn** [comment]
@paulschreiber it looks like VVV doesn't do anything regarding salts, and the source of the existing salts is actually WP CLI, a WP CLI adjustment would be the appropriate fix

I've created a PR that should resolve this in a future WP CLI update. Once it's merged and released VVV will grab the update

https://github.com/wp-cli/config-command/pull/59
