### ISSUE TITLE
Can't get VVV 2.2.1 working on Windows 10

### ISSUE THREAD

**Issue by abrightclearweb** [Varying-Vagrant-Vagrants/VVV#1564]
## Expected Behavior
After installing VVV following https://varyingvagrantvagrants.org/docs/en-US/installation/, when I access http://vvv.test I should see the VVV dashboard. 

## Current Behavior
The correct entries are in the .hosts file but http://vvv.test does not load. Looking at my folder structure there is only a /default/ folder within /www/. That folder only contains index.php and a /phpinfo/ file.

## Possible Solution

I was hoping you could tell me. Not sure how to delete everything and start over.

## Steps to Reproduce (for bugs)

I have gone through the steps here: https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/

Latest log when attempting to provision:

```
$ vagrant up --provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.1-git::master

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.local
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.localhost
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.test
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: default (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-iu1zmg.sh
    default: Network connection not detected. Unable to reach google.com...
    default: No network connection available, skipping package installation
==> default: Running provisioner: dashboard (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-z4khxa.sh
    default: Downloading dashboard, see https://github.com/Varying-Vagrant-Vagrants/dashboard.git
    default: /tmp/vagrant-shell: line 11: git: command not found
    default: /tmp/vagrant-shell: line 12: cd: /srv/www/default/dashboard: No such file or directory
    default: /tmp/vagrant-shell: line 13: git: command not found
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-132x6p2.sh
    default: Downloading core resources, see https://github.com/Varying-Vagrant-Vagrants/vvv-utilities.git
    default: sudo: git: command not found
    default: /tmp/vagrant-shell: line 17: cd: /vagrant/provision/resources/core: No such file or directory
    default: sudo: git: command not found
==> default: Running provisioner: utility-core-memcached-admin (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-1a5mb8z.sh
==> default: Running provisioner: utility-core-opcache-status (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-fceiuz.sh
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-1n83pwn.sh
==> default: Running provisioner: utility-core-webgrind (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-psa3cm.sh
==> default: Running provisioner: utility-core-trusted-hosts (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-1yj3o9a.sh
==> default: Running provisioner: utility-core-tls-ca (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-149g3zr.sh
==> default: Running provisioner: site-wordpress-default (shell)...
    default: Running: C:/Users/Asus/AppData/Local/Temp/vagrant-shell20180627-19616-uavk0f.sh
    default: Downloading wordpress-default, see https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    default: sudo: git: command not found
    default: find:
    default: `/srv/www/wordpress-default'
    default: : No such file or directory
    default: nginx: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Context

Just trying to get it to work. :)

## Your Environment

* VVV version: 2.2.1
* VVV Git Branch: master
* Vagrant version: ? I'm prompted to upgrade to 2.1.2.
* VM Provider name: VirtualBox
* VM Provider version: Oracle VM v 5.2.4
* Operating System and version: Windows 10 64-bit

**Comment by tomjn** [comment]
Your VM has no network connection, the reason you don't see the dashboard is because on your VM there is no dashboard, it needed `git` to check it out, but couldn't install the `git` package

Can you update to the latest `develop` branch? Also `vagrant --version` will tell you your vagrant version. Additionally, has this ever worked on your machine before? Or is this the very first time you've tried to use VVV?

**Comment by abrightclearweb** [comment]
I have Vagrant 2.1.1.

How do I update to the latest `develop` branch?

Does the lack of network connection just mean that my wi-fi isn't strong enough?

**Comment by benlumia007** [comment]
if you need the latest develop, the best way is to use `git pull`

**Comment by benlumia007** [comment]
make sure that you are using virtualbox 5.2+ and vagrant 2.1+, the virtualbox virtual adapter should automatically create when you vagrant up and the IP for that adapter is 192.168.50.1, but the actual box is 192.168.50.4.

**Comment by abrightclearweb** [comment]
Another question, how do I switch branch? I'm on the master branch at the moment. `git pull` says Already up to date.

**Comment by tomjn** [comment]
standard git commands, pull down the latest changes with `git pull` then switch branch with `git checkout develop`

**Comment by tomjn** [comment]
> Does the lack of network connection just mean that my wi-fi isn't strong enough?

No, a poor wifi signal is still a signal, the log suggests there was no connection at all. Sometimes this is because you just installed VirtualBox and it hasn't had a chance to install the network adaptors on system restart. Sometimes it's being blocked by antivirus or a firewall

**Comment by abrightclearweb** [comment]
Thanks, I've switched branch and there's nothing to pull.

That's a thought, my Internet Security might be a blocker. I guess I'd need to whitelist something, but what?

**Comment by benlumia007** [comment]
which program are you using for antivirus or fire wall.  for the record, using the default Windows 10 antivirus program I think its called Windows Defender, works very well.

**Comment by abrightclearweb** [comment]
Kaspersky Internet Security. I think it's a bit over-zealous at detecting threats.

**Comment by tomjn** [comment]
hmmmm if that's the issue, can you confirm? It'd be good to get some more documentation, or even detecting that

**Comment by benlumia007** [comment]
I think the best way is to disable Kaspersky for like an hour or something and test to see if that causes the problem.

**Comment by tomjn** [comment]
#1565 got merged which improves the network check and gives much more information when it happens

**Comment by tomjn** [comment]
@abrightclearweb do you use an external device for network connectivity? A USB dongle etc? Something that isn't the default network adaptor or has an unusual name? This could be related to #1567 which has the same issue, but mentions using eternal wifi dongles to get around a nonfunctional unsupported main wireless adaptor

**Comment by abrightclearweb** [comment]
OK, a bit more progress.

I had to disable both Kaspersky and NordVPN before running `vagrant up --provision` successfully.

Now I can access http://vvv.test/ and http://local.wordpress.test/. I've re-enabled Kaspersky and they still work.

But I'm getting a 403 Forbidden with both http://src.wordpress-develop.test/ and http://src.wordpress-develop.test/.

What now? I can't post the full log here, it's too long.

**Comment by tomjn** [comment]
Progress! So can we lay the blame on the VPN? The `src` subdomain should give you a message from WP Core telling you to use the built version of WP not the src at `http://build.wordpress-develop.test`, can I see the `vvv-custom.yml` for that site? I assume it's using `custom-site-template-develop` rather than `wordpress-develop`?

**Comment by tomjn** [comment]
I've also created #1571 which addresses a similar issue reported around the same time re: network detection, and adds a note on VPNs

If you can post as a gist, that should do fine for posting the log

**Comment by abrightclearweb** [comment]
Log link: https://gist.github.com/abrightclearweb/eec6b613fdac07b25f1d32eefe75cc7d

`vvv-custom.yml` is below. I haven't changed it since copying `vvv-config.yml`.

```
---

# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 1
  # provider: vmware_workstation
```

**Comment by tomjn** [comment]
It looks like grunt isn't available for whatever reason. Note that unless you're doing work on WP core that site should be unnecessary, if you need an additional WP site to do work in you can add one like this:

```yaml
  newsite:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - newsite.test
```

Followed by a reprovision

**Comment by rtpHarry** [comment]
Hmm yeah, I have just had the same issue with the develop branch, NordVPN has been playing fine so far but won't let develop reach the internet.

**Comment by benlumia007** [comment]
any news regarding this, has anyone still have issues :D

**Comment by tomjn** [comment]
I'm going to close this out as we're on a new box, ubuntu, and major version
