### ISSUE TITLE
Network connection not detected. Unable to reach google.com on brand new VM

### ISSUE THREAD

**Issue by oscarssanchez** [Varying-Vagrant-Vagrants/VVV#1567]
Hi, 

Could you please take a look at this problem? i have installed VVV previously with no major problems whatsoever on another PC's, however, I'm running into a lot of trouble with a brand new laptop i recently bought. 

## Expected Behavior
My internet conection is working and VVV tells me there is no network connection.

## Current Behavior

The following message appears when trying to either `vagrant up --provision` or` vagrant up`:

```
default: Network connection not detected. Unable to reach google.com...
    default:  
    default: #################################################################
    default:  
    default: Problem:
    default: Provisioning needs a network connection but none was found.
    default: VVV tried to ping google.com, and got no response.
    default:  
    default: Make sure you have a working internet connection, that you 
    default: restarted after installing VirtualBox and Vagrant, and that they
    default: aren't blocked by a firewall. If you can load https://google.com
    default: in your browser, then VVV should be able to connect.
    default:  
    default: Additionally, if you're at a contributor day event, be kind,
    default: provisioning involves downloading things, a full provision may 
    default: ruin the wifi for everybody else :(
    default:  
    default: Network ifconfig output:
    default:  
    default: eth0      Link encap:Ethernet  HWaddr 08:00:27:d0:46:cc  
    default:           inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
    default:           inet6 addr: fe80::a00:27ff:fed0:46cc/64 Scope:Link
    default:           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
    default:           RX packets:1734 errors:0 dropped:0 overruns:0 frame:0
    default:           TX packets:1444 errors:0 dropped:0 overruns:0 carrier:0
    default:           collisions:0 txqueuelen:1000 
    default:           RX bytes:205424 (205.4 KB)  TX bytes:169876 (169.8 KB)
    default: 
    default: eth1      Link encap:Ethernet  HWaddr 08:00:27:05:fa:db  
    default:           inet addr:192.168.50.4  Bcast:192.168.50.255  Mask:255.255.255.0
    default:           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
    default:           RX packets:2 errors:0 dropped:0 overruns:0 frame:0
    default:           TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
    default:           collisions:0 txqueuelen:1000 
    default:           RX bytes:1180 (1.1 KB)  TX bytes:1282 (1.2 KB)
    default: 
    default: lo        Link encap:Local Loopback  
    default:           inet addr:127.0.0.1  Mask:255.0.0.0
    default:           inet6 addr: ::1/128 Scope:Host
    default:           UP LOOPBACK RUNNING  MTU:65536  Metric:1
    default:           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
    default:           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
    default:           collisions:0 txqueuelen:0 
    default:           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

## Context
For context:

The machine has been troublesome to use with Ubuntu. It has an unsupported built in wireless card and been using an external wifi adapter or ethernet cable to get around that. It also uses UEFI, so i had to disable secure boot in the BIOS. Maybe it is helpful to know that information. If needed, please let me know and I'll get the details you need

## Your Environment

* VVV version: 2.2.2
* VVV Git Branch: develop
* Vagrant version: 2.1.2
* VM Provider name: virtualbox
* VM Provider version: 5.2.12
* Operating System and version:
Ubuntu 18.04

Thank you very much for your time.

**Comment by tomjn** [comment]
hmmm I assume you're restarted your machine since setting up virtualbox and vagrant?

**Comment by oscarssanchez** [comment]
hi @tomjn 

That's right, I restarted the machine after vagrant and virtualbox installation. I also tried to provision on a clean install without restarting the machine before.

**Comment by tomjn** [comment]
do you have any kind of custom network configuration or security features? Do other vagrant systems have network connectivity?

**Comment by tomjn** [comment]
Additionally does this answer help? :
https://stackoverflow.com/questions/18457306/how-to-enable-internet-access-inside-vagrant#18457420

**Comment by tomjn** [comment]
Additionally, what does VirtualBox' UI say about the network adaptors?

**Comment by tomjn** [comment]
@oscarssanchez can you try the `tomjn-cable-connected-workaround` branch from PR #1568 ?

**Comment by tomjn** [comment]
are you able to ping `8.8.8.8`?

**Comment by oscarssanchez** [comment]
HI @tomjn,

Yes, I'm able to ping to 8.8.8.8 .

I solved the problem by going back to this hash: 80790558bcc32ebd67af5d3c4012130a28f47c38 . I just picked a month or so of difference, cause I did a provision just around that time.

The script is installing everything right now, unfortunately i was not able to solve the problem with the most up to date version.

I really appreciate your help, if I can help out providing more information so this problem is solved in the future, I'll be glad to do so, otherwise, should i close this issue?

**Comment by tomjn** [comment]
hmmmm can you pinpoint which commit it was that broke things?

**Comment by tomjn** [comment]
Also, does the network connection test still fail in your provision log, despite it continuing to provision on that commit hash?

**Comment by oscarssanchez** [comment]
@tomjn The lastest one didn't work for me: d110ab0c798d0b3fc70122b9ecbd98f92a75315f 
I'll try in my old laptop to see from which commit the problem starts.

No, the network connection didn't fail in my provision log with 80790558bcc32ebd67af5d3c4012130a28f47c38

**Comment by tomjn** [comment]
Then you should be able to use `git bisect` to figure out when things broke:

```
$ git bisect start
$ git bisect good 8079055
$ git bisect bad d110ab0
```

It will then do a search, asking you to check if it's good or bad each time. If it's good, run `git bisect good`, if it's bad run `git bisect bad`, eventually it'll hone in on 1 particular commit.

Once you're done `git bisect reset` will return you back to a normal working state. [See here for more detailed instructions based on Drupal usage](http://webchick.net/node/99)

**Comment by tomjn** [comment]
Also as an aside, on the latest commit, even with the issue, can you ping 8.8.8.8 if you run `vagrant ssh` and run it inside the VM?

**Comment by obilodeau** [comment]
Facing this problem right now trying to do a PR for #1569.

`vagrant ssh` then pinging google.com works just fine:

```
vagrant@vvv:~$ ping google.com
PING google.com (172.217.13.110) 56(84) bytes of data.
64 bytes from yul02s04-in-f14.1e100.net (172.217.13.110): icmp_seq=1 ttl=63 time=13.7 ms
64 bytes from yul02s04-in-f14.1e100.net (172.217.13.110): icmp_seq=2 ttl=63 time=14.5 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 13.784/14.185/14.586/0.401 ms
```

curl works too:

```
curl http://google.com/
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by obilodeau** [comment]
The isssue was introduced with commit https://github.com/Varying-Vagrant-Vagrants/VVV/commit/e385c88ff77751b37de153ea3d9d251f3b4121aa. 8.8.8.8 doesn't have an HTTP or HTTPS server so you can't assess network connectivity based on that. Don't know why the change was made in the first place so I won't intervene here.

**Comment by tomjn** [comment]
That makes sense, I'll switch it to https://google.com
