### ISSUE TITLE
git: command not found

### ISSUE THREAD

**Issue by guoyunhe** [Varying-Vagrant-Vagrants/VVV#1587]
## Expected Behavior

vagrant up should do the job.

## Current Behavior

vagrant up failed with "git: command not found"

## Steps to Reproduce (for bugs)

1. git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git
2. cd VVV
3. vagrant up
4. see output

![screenshot_20180714_170100](https://user-images.githubusercontent.com/5836790/42725164-c93a071a-8787-11e8-9622-437bb8a980f1.png)

## Your Environment

* VVV version:  master latest (2018-07-14)
* VVV Git Branch:  master
* Vagrant version: 2.2.1
* VM Provider name:  VirtualBox
* VM Provider version:
* Operating System and version: openSUSE Tumbleweed

**Comment by tomjn** [comment]
Can you run this under the develop branch? There are fixes and updates,
there's a very high chance the problem is either fixed or is in code that
no longer exist

**Comment by guoyunhe** [comment]
I think it has been fixed in develop branch.
