### ISSUE TITLE
ping google failed

### ISSUE THREAD

**Issue by guoyunhe** [Varying-Vagrant-Vagrants/VVV#1588]
## Expected Behavior

VVV should ping some site that it really depends on.

## Current Behavior

VVV pings Google. However, in China, Google is blocked and we cannot use VVV. But VVV doesn't need Google, right?

## Possible Solution

Ping some site where it downloads resources or communicates to.

## Steps to Reproduce (for bugs)

You cannot reproduce this bug out side of China.

## Your Environment

* VVV version:  develop branch latest
* VVV Git Branch:  develop
* Vagrant version: 2.2.1
* VM Provider name:  VirtualBox
* VM Provider version: 5.2.14
* Operating System and version: openSUSE Tumbleweed

**Comment by tomjn** [comment]
Can you ping `8.8.8.8`? Do you know of an alternative that will work both inside and outside China?

**Comment by guoyunhe** [comment]
I can ping google's `8.8.8.8` and `8.8.4.4` but they have 50% packet loss.

Cloudflare's `1.1.1.1` and `1.0.0.1` are faster and have no packet loss. I think they have good up-time, too. It is mainly a CDN service and doesn't provide any its own content. So it is unlikely to be blocked in future. However, Akamai was once blocked. Anything could happen.

I saw VVV using `wget` to fetch a web resource instead of ping. `wget https://example.org/` might be a good idea. This site doesn't contain any meaningful content and should not be blocked by any ISPs or governments.

**Comment by LoreleiAurora** [comment]
If this is going to be updated I think we should ping `ppa.launchpad.net` as this is where we download Git and PHP from.

**Comment by tomjn** [comment]
@guoyunhe can you test PR #1589 and see if that resolves the problem? It implements Loreleis suggestion

**Comment by guoyunhe** [comment]
Thanks! Now VVV works smoothly in China.

**Comment by No3x** [comment]
I had the same issue that the network connection was not detected due ping of google.com. Although I'm not in China and google.com should not be blocked. However, patching my vvv 2.2.1 with c87eba66cd6af4c0701074cf5c5270456d036572 fixed the issue for me.
