### ISSUE TITLE
Guest server time is lagging behind the host time?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1590]
I was testing some feature on my WordPress and I noticed that the server time is different than my host time

Server: `13:39:03   20/07/18`
Host:    `15:55:20   20/07/18`

I found [here](https://superuser.com/questions/463106/virtualbox-how-to-sync-host-and-guest-time) that DKMS (Dynamic Kernel Module Support) and Guest Additions should be added on the guest system.

Is this something that we should add as a utility or can this be added in the VVV from the get go so that we get synchronized times on our virtual server?

**Comment by Mte90** [comment]
guest additions is something that you can install in vagrant.
I am using this plugin for that https://github.com/dotless-de/vagrant-vbguest that automatically update in the VM.

**Comment by tomjn** [comment]
Guest additions come with the base box. Building our own base box would allow us to include more up to date versions, but recent tests did not pan out so well on that front. As @Mte90 said you can install a vagrant plugin that will try to update them for you.

Once the base box issues are eliminated though this won't be a problem, nor will it be an issue with VVV 3
