### ISSUE TITLE
r

### ISSUE THREAD

**Issue by pythianpedro** [Varying-Vagrant-Vagrants/VVV#1591]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version: 
* VVV Git Branch: 
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by tomjn** [comment]
@pythianpedro your issue has no content, can you edit it to include information? Right now the only thing is the letter `r`
