### ISSUE TITLE
Disable automatic database backups?

### ISSUE THREAD

**Issue by sahibalejandro** [Varying-Vagrant-Vagrants/VVV#1596]
Hi, I just installed a new VVV box and noted that when I run `vagrant halt` it does an automatic database backup, although this is a cool feature, in my case is a pain because my DB is 20GB big.

Is there a way to disable this feature? I did Google it but can't find anything. 

## Expected Behavior
Do not make automatic database backups when running`vagrant halt`

## Current Behavior
Automatic database backups 

## Possible Solution
An option to enable/disable automatic database backups

## Steps to Reproduce (for bugs)
Run `vagrant halt`

## Context
Database backups

## Your Environment
* VVV version: 2.2.1
* VVV Git Branch: develop
* Vagrant version: 2.1.2
* VM Provider name: VirtualBox
* VM Provider version: 5.2.16
* Operating System and version: macOS 10.13.5

**Comment by tomjn** [comment]
You can create `vagrant_halt_custom` and `vagrant_halt_custom`, `vagrant_destroy_custom`, and `vagrant_suspend_custom` scripts in the `config/homebin` folders then reprovision. Those scripts will be ran instead of `db_backup`

**Comment by tomjn** [comment]
Of note, you could use that to call a custom `db_backup_compressed` script, that does the same thing but gzips the database files, they should compress very well

**Comment by sahibalejandro** [comment]
Would be nice to have this in the official documentation. ☝🏼
On the note, I'm not worried about compressing or disk space, I was worried by the time it takes to dump the database. 😛

Thank you so much!
