### ISSUE TITLE
wordpress-develop wrong locations

### ISSUE THREAD

**Issue by No3x** [Varying-Vagrant-Vagrants/VVV#1597]
## Expected Behavior
1. When installing a plugin in http://src.wordpress-develop.test I assume the plugin is stored in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/
2. When accessing http://build.wordpress-develop.test The frontpage should show with the title build.wordpress-develop.test

## Current Behavior
1. When installing a plugin in http://src.wordpress-develop.test the plugin is stored in /srv/www/wordpress-develop/public_html/build/wp-content/plugins/
2. When accessing http://build.wordpress-develop.test The frontpage is shown with the title src.wordpress-develop.test
![bildschirmfoto 2018-08-03 um 13 40 37](https://user-images.githubusercontent.com/2690708/43641200-fb57e23a-9722-11e8-816e-c8d7ca59b416.png)

## Steps to Reproduce (for bugs)
- Download vvv 2.2.1 as zip from releases
- Apply c87eba66cd6af4c0701074cf5c5270456d036572 patch, if google.com can't be pinged
- vagrant up
- try the steps of current behavior and expected behavior

I don't know what's wrong and how to figure out. I executed vagrant destroy multiple times, deleted `www/wordpress-develop` and the according database in `database/backups`.
## Context
This prevents me from developing a plugin in src/wp-content/plugins/

## Your Environment

* VVV version: 2.2.1 + c87eba66cd6af4c0701074cf5c5270456d036572 patch
* VVV Git Branch: zip download
* Vagrant version: 2.1.1
* VM Provider name: parallels
* VM Provider version: on request
* Operating System and version: OSX El Capitan

**Comment by tomjn** [comment]
Which template is being used for that site? Note that if your `src.wordpress-develop.test` gives you a WP install, then something is terribly out of date. You're only meant to use the `build.wordpress-develop.test` URL in modern WP Core development.

> VVV version: 2.2.1 + c87eba6 patch
> VVV Git Branch: zip download

Can you switch to a git based install and use the latest version of the `develop` branch?

> When installing a plugin in http://src.wordpress-develop.test I assume the plugin is stored in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/

In modern core WP development, only the built version of WP can be accessed. If you try to use the src version, it runs `wp_die` and tells you that you need to build WP. Installing and using WP from the source folder should not be possible


> When accessing http://build.wordpress-develop.test The frontpage should show with the title build.wordpress-develop.test

I would suggest using:

```yaml
  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - wordpress-develop.test
```

Plugins and themes etc should go in the `build` folder, and modifications to core go in the `src` folder, and then get built into the `build` folder. I'd suggest running an npm watch on the host machine ( running it inside the VM is not recommended )

**Comment by No3x** [comment]
> Which template is being used for that site?

I'm using the default vvv-config.yml copied to vvv-custom.yml with the following changes:
![bildschirmfoto 2018-08-04 um 12 16 29](https://user-images.githubusercontent.com/2690708/43675195-52521fde-97e0-11e8-8e9b-53a3a30f69e9.png)

>  Note that if your src.wordpress-develop.test gives you a WP install, then something is terribly out of date.

Do you consider 2.2.1 out of date then?

> Can you switch to a git based install and use the latest version of the develop branch?

I will test this.

>  If you try to use the src version, it runs wp_die and tells you that you need to build WP.

I have never seen this since using VVV over 4 years.

I just need a working test environment to execute phpunit tests. I experiential found that the wordpress-develop dir is used when executing unittests and switched from developing in my mydev.test to wordpress-develop.
1. I don't want to contribute to the core. I just want to develop plugins. Can I remove all sites other that mydev in the vvv-custom.yml?
2. Should unittests also work with mydev.test only and no wordpress-develop?

Thanks for the clarification. Going to checkout the repository now and report back.

**Comment by tomjn** [comment]
> I'm using the default vvv-config.yml copied to vvv-custom.yml with the following changes:

All your previous notes implied you were using `wordpress-develop` and the WP Core dev site template. Your screenshot on the other hand indicates this is not the case

 - **Custom Site Template**: Generates a WP install
 - **Custom Site Template Develop**: Generates a WP Core development site, with a src and build folder for contributing to and testing core

> I have never seen this since using VVV over 4 years.

That's because it isn't a VVV thing, it's a WordPress thing. In the last few months, WP core development was restructured. You can no longer run WP out of the source folder, you have to run it out of the build folder. VVV just pulls down a copy of the WP Core dev repos.

Note that this is specific to the WP Core development, and does not happen on normal WP installs.

> I don't want to contribute to the core. I just want to develop plugins. Can I remove all sites other that mydev in the vvv-custom.yml?

Then just use the custom site template, rather than custom site template develop. The first installs WP, the latter installs a WP Core dev environment. None of the sites in VVV are required, they're just defaults. Do add at least 1 site though, I'm not sure how VVV will respond if zero sites are defined.

> I just need a working test environment to execute phpunit tests.

**You don't need a WP Core dev environment to do unit tests for plugin development, standard WP install will do** for that, follow all the standard PHPUnit setup instructions.

There's nothing VVV specific to be done here once you have a WP install. The only thing to note is that if you run `vagrant ssh` you'll have a copy of PHPUnit present. But beyond that, the question is how to do unit tests, and that's the same wether you're using VVV/MAMP/LAMP/Docker/XAMP/Local/etc

> Should unittests also work with mydev.test only and no wordpress-develop? (My guess is: when using custom-site-template-develop.git instead of custom-site-template.git it should work)

Only if you want to contribute to the WP Core unit tests. If you want to write unit tests for your own plugin, then all you need is your own plugin and PHPUnit. If you want to mock WP functions there are libraries and things for that, but you're going to have to google for those. None of it is VVV specific. There's nothing special about the develop custom site template that allows it to do basic unit tests that the others can't

**Comment by No3x** [comment]
> All your previous notes implied you were using wordpress-develop and the WP Core dev site template.

Yes, wordpress-develop is part of the vvv-config.yml. My screenshots shows a diff, of my changes or only additions in this case.

> You can no longer run WP out of the source folder, you have to run it out of the build folder.

That's something I did not recognize. Thanks for pointing out.

> Do add at least 1 site though, I'm not sure how VVV will respond if zero sites are defined.
Lol. What would be the benefit of using VVV without sites - no I will not try this.

> You don't need a WP Core dev environment to do unit tests for plugin development, standard WP install will do for that, follow all the standard PHPUnit setup instructions.

There was confusion because the popular install-wp-tests had always references to wordpress-develop paths. A quick look inside the script reveals it installs to `/srv/www/wordpress-develop/public_html/src/` by default on VVV. That's why I always thought there comes some magic from wordpress-develop dir - but it's actually all externalized and downloadable by the script.

One site seems sufficient indeed. Just for the record:
```
sites:
  mydev:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    skip_provisioning: false
    hosts:
      - mydev.test
    custom:
      wp_type: subdirectory
```
I'm able to run my plugin unit tests without any wordpress-develop site after executing the install-wp-tests script.

If I understood everything properly there is no issue. But there are two misleading things:
1. the [docs](https://varyingvagrantvagrants.org/docs/en-US/references/default-sites/) say put your plugin in `www/wordpress-develop/public_html/src`. As plugin developer I assume I have to access src.wordpress-develop.test then. I don't even know that I have to "compile" WordPress just to make my changes on the plugin effective.
2. when accessing build.wordpress-develop.test the title is src.wordpress-develop.test which tells me that I'm on the `src` version of WordPress but actually files are served from `build`. Your PR #1599 is good, because it eliminates this.

**Comment by tomjn** [comment]
I'm not familiar with the `install-wp-tests` script

> the docs say put your plugin in www/wordpress-develop/public_html/src. As plugin developer I assume I have to access src.wordpress-develop.test then.

Those will need changing. There's already a PR to change the URL in the default config to have neither `src` or `build`. Either way, even if you visit `src`, that template always loads the `build` folder, so the difference is purely the URL, it only serves the `build` folder.

The old legacy deprecated version will serve the `src` folder though, but don't use that, it's old and deprecated

For plugin development though, use a normal custom site template, using the develop version overcomplicates things massively for plugin development

> I don't even know that I have to "compile" WordPress just to make my changes on the plugin effective.

I don't know the specifics of how WP Core builds work, but I would use a normal WP site to test plugins

**Comment by tomjn** [comment]
I'm going to close this out due to inactivity, if there are still issues or questions feel free to comment and I'll reopen
