### ISSUE TITLE
`vagrant up --provision` results in "Main packages check and install failed, halting provision"

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1598]
I am trying to update VVV and all related components via the [Keeping Up To Date documentation page](https://varyingvagrantvagrants.org/docs/en-US/installation/keeping-up-to-date/
).  Steps 1-5 completed without issue, but step 6 (`vagrant up --provision`) resulted in an error:  `Main packages check and install failed, halting provision`.  The end of the output is below--full output can be seen [here](https://pastebin.com/W0X9KsYZ).  Have I done something wrong?

```
default: Unable to correct missing packages.
    default: E
    default: :
    default: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-readline_7.2.8-1+ubuntu14.04.1+deb.sury.org+1_amd64.deb  Connection failed
    default: E
    default: :
    default: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-imap_7.2.8-1+ubuntu14.04.1+deb.sury.org+1_amd64.deb  Connection failed
    default: E
    default: :
    default: Aborting install.
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version:  2.2.1-80-g448583f
* VVV Git Branch:   develop
* Vagrant version:  Vagrant 2.1.2
* VM Provider name:   VirtualBox
* VM Provider version:  Version 5.2.16 r123759 (Qt5.6.2)
* Operating System and version:  Win 10, x64

**Comment by tomjn** [comment]
This looks like it tried to download a bunch of things but one or two of them failed to connect. The most likely cause is network instability.

I'm going to recommend the classic turn it off and back on again routine, as clearly it managed to connect to launchpad for most of the packages. It just needs a retry

**Comment by cagross** [comment]
@tomjn Sorry for the delay, but I'm just getting back to this.  I wasn't able to try your suggestion at the time.  And since that time there has been an update to both Virtual Machine and Vagrant.  So I decided to re-start the [Keeping Up To Date](https://varyingvagrantvagrants.org/docs/en-US/installation/keeping-up-to-date/) instructions from the beginning.  I updated VM and Vagrant, and carried out all other steps without issue.  But `vagrant up` step failed again, with a different error:

```
default: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
default: 2018/09/17 17:14:00 [emerg] 16033#16033: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
default: nginx: configuration file /etc/nginx/nginx.conf test failed
```

Would you like me to open a new, separate issue for this?

**Comment by tomjn** [comment]
As an aside, on the `develop` branch, the splash output contains the vagrant version amongst other valuable pieces of info, hence the desire for the full log, amongst other reasons

**Comment by cagross** [comment]
No no, I can and will provide all of those relevant details.  What I'm asking you here is if I should do so in this issue, or create a new issue.

**Comment by tomjn** [comment]
The error provided implies this is an old error that was fixed in May

**Comment by tomjn** [comment]
@cagross we're already here, lets not confuse things by spanning multiple issues

**Comment by cagross** [comment]
OK thanks.

In an effort to provide the 'entire confection,' I just spent some time re-creating my steps.  Unsurprisingly, I found the issue:  user error.  Specifically, the last step in [the instructions](https://varyingvagrantvagrants.org/docs/en-US/installation/keeping-up-to-date/) clearly says to run `vagrant up --provision`.  But I previously ran only `vagrant up`.  This time, I ran `vagrant up --provision` and there was no error in the output--the process completed, seemingly without issue.  To test, I just logged in to my local WordPress sites and there appear to be no immediate issues.  So I guess we can consider this resolved?

For what it's worth, here were was the relevant information behind my issue, including the full error log at the time:

VVV version: 2.2.1-98-g1860077
VVV Git Branch: develop
Vagrant version: Vagrant 2.1.5
VM Provider name: VirtualBox
VM Provider version: Version 5.2.18 r124319 (Qt5.6.2)
Operating System and version: Win 10, x64
Full `vagrant up` output can be seen [here](https://pastebin.com/DqqMc1qM).

**Comment by SpencerCloud** [comment]
Hey I just wanted to comment in and say that I'm getting the same errors, but slightly different as I'm getting a "403 Forbidden" error for the packages instead of a "Connection Failed" error for the packages.

VVV version: 2.4.0
VVV Git Branch: master
Vagrant version: 2.2.0
VM Provider name: VirtualBox
VM Provider version: 5.2.20
Operating System and version: macOS Mojave 10.14.1

[I created a gist accessible here for the vagrant up --provision output](https://gist.github.com/SpencerCloud/b429627cd5a56f01684e3c35cf6af7e9)

Let me know if anything gets found on this issue. (Or if this should be created as a separate issue.)

**Comment by SpencerCloud** [comment]
It looks like this may have been a network issue for me... I was working at a café when I had these issues along with some other connection issues, but since I went home, vagrant up --provision worked perfectly for me.

**Comment by tomjn** [comment]
I'm going to close this out. The original issue seems to have been resolved by retrying, and the subsequent error is unrelated to the original problem ( most likely somebody deleted what was in the logs folder without recreating the files )

**Comment by cagross** [comment]
@tomjn   Sounds good.

**Comment by ajayghaghretiya** [comment]
We are facing the same issue. It seems try to download bunch of packages and return the error message that /var/cache/apt/ does not have enough space.
Vagrant 3.2
I am having 91gb space for this directory.

**Comment by tomjn** [comment]
Ajay can you share a full provisioner log along with the versions of all
the software you’re using including your operating system?

**Comment by tomjn** [comment]
Also can you open a new issue? I believe your issue is completely unrelated
to this one, it needs a new issue
