### ISSUE TITLE
Vagrant Cloud Providers with VVV

### ISSUE THREAD

**Issue by alexw23** [Varying-Vagrant-Vagrants/VVV#160]
Has anyone had experience and/or used VVV with the new AWS / Rackspace / Digital Ocean providers?

https://github.com/mitchellh/vagrant-aws
https://github.com/mitchellh/vagrant-rackspace
https://github.com/smdahlen/vagrant-digitalocean

Would be interested in seeing the experience so far.

**Comment by Hitman007** [comment]
I'd say at this time, AWS does NOT work. I wish it did! I guess what I'm going to do is install VirtualBox on an EC2 instance, which isn't ideal. I don't have the skill to do it, but there doesn't seem to be any reason that VVV couldn't deploy from AWS. I get this message: hitman007@Hitman007CPU:~/VVV$ vagrant up --provider=aws
Bringing machine 'default' up with 'aws' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: aws
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty64
Address: https://atlas.hashicorp.com/ubuntu/trusty64
Requested provider: [:aws]

**Comment by cfoellmann** [comment]
I dont say that I know a solution to your problem but you definitely need to look for a box compatible with AWS. That is your first hurdle you need to jump
