### ISSUE TITLE
Bash Prompt Not Wrapping Correctly

### ISSUE THREAD

**Issue by ivankristianto** [Varying-Vagrant-Vagrants/VVV#1602]
## Expected Behavior
Bash should wrap correctly if have more than 1 line script to run

## Current Behavior
I'm using iTerm2 on Mac OSX. When I ssh to vagrant box, I found the text wrapping is not correct.

## Possible Solution
In bash_profile file edit these lines:
```
red="\033[38;5;9m"
green="\033[01;32m"
blue="\033[38;5;4m"
yellow="\033[38;5;3m"
white="\033[00m"
PS1="${debian_chroot:+($debian_chroot)}${red}\u${green}@${blue}\h${white}:${yellow}\w$ \033[0m"
```

To this:
```
red="\[\033[38;5;9m\]"
green="\[\033[01;32m\]"
blue="\[\033[38;5;4m\]"
yellow="\[\033[38;5;3m\]"
white="\[\033[00m\]"
# PS1="${debian_chroot:+($debian_chroot)}${red}\u${green}@${blue}\h${white}:${yellow}\w$ \033[0m"
PS1="${debian_chroot:+($debian_chroot)}${red}\u${green}@${blue}\h${white}:${yellow}\w$ \[\033[0m\]"
```

**Comment by tomjn** [comment]
@ivankristianto can you create a PR against the `develop` branch for this? Do those changes work with the normal MacOS terminal app?

**Comment by ivankristianto** [comment]
@tomjn 
Sure, i'll open a PR.
here are screenshots what it solved in Mac terminal and iTerm2

<img width="485" alt="screen shot 2018-08-07 at 00 43 55" src="https://user-images.githubusercontent.com/656006/43732203-20df0e56-99db-11e8-959d-ecb30f647d77.png">

![screen shot 2018-08-07 at 00 44 23](https://user-images.githubusercontent.com/656006/43732209-2545ca16-99db-11e8-8273-d6cf59db0635.png)

**Comment by tomjn** [comment]
Awesome, I'm curious though, VVV tries to use the standard red/yellow/blue/green to colour the logos but make sure it still fits with the colour scheme in use, and I see the colours in iTerm aren't R/G/B but they do look different. Is that just your colour scheme?

**Comment by ivankristianto** [comment]
@tomjn yes it is my colour scheme.
And I did open a PR above for your review, thanks!
