### ISSUE TITLE
migration to git install documentation leaves git repo in detached HEAD state

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#1607]
## Expected Behavior

Documentation should guide you through to the end of the journey without leaving the git in a detached state

## Current Behavior

The documentation at https://varyingvagrantvagrants.org/docs/en-US/installation/convert-to-git/ appears to work but then leaves repo in a 'detached HEAD' state.

I typed in the git commands on the documentation:

```
git init
git remote add origin https://github.com/Varying-Vagrant-Vagrants/VVV.git
git fetch
git reset origin/master
git checkout -f origin/master
```

And this is what I've ended up with:

```
λ git checkout -f origin/master
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b7b51b7... Merge pull request #1519 from Varying-Vagrant-Vagrants/release-2.2.1
```
It would help to know what this means and what the next step is.

## Steps to Reproduce (for bugs)

1. Have a zip installed vvv
2. Follow steps in https://varyingvagrantvagrants.org/docs/en-US/installation/convert-to-git/
3. End up with detached HEAD

## Your Environment

* VVV version:  was v2.0.0 now 2.2.1
* VVV Git Branch:  zip download
* Vagrant version: 1.9.8 (I know I have to update this but its not relevant to the git issue as I haven't run anything other than the git commmands)
* VM Provider name:  VirtualBox
* VM Provider version:
* Operating System and version: Windows 10

**Comment by rtpHarry** [comment]
Seems to have worked:

![image](https://user-images.githubusercontent.com/1038062/43998868-6f2347be-9e2a-11e8-96dd-43eb475c32df.png)

I have some files waiting to be checked in which I had before so I think its changed over seamlessly.

![image](https://user-images.githubusercontent.com/1038062/43998864-5af817b0-9e2a-11e8-8b35-9d2047e9865a.png)

I guess this means the documentation needs updating. While I'm happy to do this I'm not sure if the correct edit is to just add this on to the list of commands or to replace the last command `git checkout -f origin/master` ?

**Comment by tomjn** [comment]
The docs folder was removed from VVV and moved to its own repo a very long time ago, I expect the majority of those changes can be eliminated ( only the changes you specifically made yourself are worth bothering with, assuming you want to keep them )

**Comment by rtpHarry** [comment]
Seems I'm not quite out of this yet. Just tried `git pull` and got this message:

```
D:\localdev (master -> origin)
λ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```

Following the advice in the error resolved the problem:

```
D:\localdev (master -> origin)
λ git branch --set-upstream-to=origin/master master
Branch 'master' set up to track remote branch 'master' from 'origin'.

D:\localdev (master -> origin)
λ git pull
Already up to date.
```

**Comment by rtpHarry** [comment]
Added the important bits to a PR for the docs.
