### ISSUE TITLE
documentation for vvv-config.yml needs reviewing

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#1608]
It looks like the vvv-config.yml documentation is slowly going out of date:

https://varyingvagrantvagrants.org/docs/en-US/vvv-config/

I'm not an expert in VVV but I can see that the default ram and the utilities are not reflecting the current defaults.

The simple solution seemed to be to remove that brittle section and replace it with a link to the actual yml file in the vvv repo, but its broken down into snippets further down in the documentation so it needs some attention from people in the know.

Another important solution to improve this in the future is to add a clear note at the top saying "This is documentation for the config file in VVV v2.2.1, newer versions may have changed these defaults."

Being able to rely on the documentation when you are troubleshooting is important.

**Comment by rtpHarry** [comment]
I have started this process with https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/101 and done all the low-hanging fruit.

It still needs a pro to review it and make sure that all the available options are correctly covered before a "This is documentation for the config file in VVV v2.2.1, newer versions may have changed these defaults." note can be added to the top.

**Comment by tomjn** [comment]
Good work so far :)

**Comment by rtpHarry** [comment]
Can anyone confirm if these specs are complete as of v2.2.1 so that the note can be added?

**Comment by tomjn** [comment]
@rtpHarry a lot of those code blocks were generated automatically by dumping the data structure in the vagrant file to the console

**Comment by Mte90** [comment]
As I can see right now the docs is complete, it is missing something?

**Comment by tomjn** [comment]
@Mte90 I don't know, it might be

**Comment by Mte90** [comment]
I checked all the parameters and seems good

**Comment by tomjn** [comment]
Lets close this for now then
