### ISSUE TITLE
troubleshooting - starting from fresh documentation doesn't work

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#1609]
## Issue 1
The documentation for [starting fresh](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/#starting-from-fresh) says do `vagrant halt` then `vagrant destroy` but that causes an error:

```
D:\localdev (master -> origin)
λ git pull
Already up to date.

D:\localdev (master -> origin)
λ vagrant halt

[trimmed normal vagrant halt output]

D:\localdev (master -> origin)
λ vagrant destroy
==> default: Running triggers before destroy ...
==> default: Running trigger: VVV Pre-Destroy...
Could not run remote script on default because its state is poweroff
```

I did a `vagrant up` then `vagrant destroy` and it worked.

## Issue 2
I followed through the rest of the items and now when I try to do a `vagrant up --provision` it fails with:

```
D:\localdev (master -> origin)
λ vagrant up --provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.1-git::master

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: localdev_306449ed646
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\name\VirtualBox VMs\ubuntu-cloudimg-trusty-vagrant-amd64_1534242157844_99798' to 'C:\Users\name\VirtualBox VMs\localdev_306449ed646' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3111 of file VBoxManageModifyVM.cpp
```

**Comment by rtpHarry** [comment]
Seems something has clung on in the VM folder:

![image](https://user-images.githubusercontent.com/1038062/44087916-7a947af6-9feb-11e8-9ba0-256d8b47f658.png)

![image](https://user-images.githubusercontent.com/1038062/44087942-961dad38-9feb-11e8-8625-ba19384dcd43.png)

I have deleted the folder and redone `vagrant up --provision` and its chugging along properly now.

Not sure if the second bit is an error with the documentation or if it was some glitch deleting the file as only the vbox was left.

For the first one I think I need to do a PR to replace `halt` with `up`.

Thoughts?

**Comment by tomjn** [comment]
Virtualbox can be a tad unreliable about cleanup. Your first issue also suggests that changes in the `develop` branch may be helpful, really we need to release 2.3 sooner rather than later

**Comment by rtpHarry** [comment]
This thread has solved this for me, and I've incorporated it into a pr for docs.
