### ISSUE TITLE
WordPress' built-in plugin editor doesn't work with VVV

### ISSUE THREAD

**Issue by mnelson4** [Varying-Vagrant-Vagrants/VVV#1612]
## Expected Behavior

Despite all the reports of the improved WP 4.9 plugin/theme editor not working for some people (eg https://wordpress.org/support/topic/cant-edit-main-theme-php-files-after-upgrading-to-4-9/) , I would expect it to work with VVV. 

## Current Behavior

But when I edit an active plugin on a WP site running VVV, I get the error message 

> Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP.

Does this work for anyone else with VVV out of the box?

## Possible Solution

Not sure what's going wrong. What's especially strange is that doing a CURL request still works:

eg if you open `wp-admin/includes/file.php` and inside `wp_edit_theme_plugin_file()` if you replace the TWO occurrences of 
```
$r = wp_remote_get( $url, compact( 'cookies', 'headers', 'timeout' ) );
$body = wp_remote_retrieve_body( $r );
```

with 

```
       $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_FRESH_CONNECT, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_VERBOSE, true);
        $body= curl_exec($ch);
        curl_close($ch);
```
(please note there are two reqeusts sent using `wp_remote_get` that you need to replace with direct CURL requests)

you'll see it works fine again. So there's some combined issue with how the site is setup and how `wp_remote_get()` is making the request that is causing the problem.

Note: adding `sslverify=>false` to the `wp_remote_request()` didn't fix it.

## Steps to Reproduce (for bugs)

1. Activate a plugin
2. Open up the WP built-in plugin editor
3. Try to edit that plugin
4. You'll get the error

## Context

One of our customers was reporting a bug with our plugin interfering with the WP plugin editor (see https://github.com/eventespresso/event-espresso-core/issues/394), but I can't test it directly because I can't get the plugin editor to even work without any other plugins active.

## Your Environment

* VVV version:   v2.1.0
* VVV Git Branch:  master
* Vagrant version: 2.1.2
* VM Provider name:  VIrtualbox
* VM Provider version: 5.1.32
* Operating System and version: Windows 7

This issue also has to do with something WP is doing, and it some changes to WP core OR the environment can fix this issue, which is why I thought I should report it here too.

**Comment by mnelson4** [comment]
right now, at least getting a confirmation that others using VVV are experiencing this too would be helpful.

**Comment by tomjn** [comment]
You sure this isn't the PHP fatal error protection kicking in? I've never experienced this

**Comment by tomjn** [comment]
Also I would note that the built in plugin editor is not worth bothering with in VVV because all the files are directly accessible on your file system. You would be better off just navigating to the folder in Finder/Windows Explorer and double clicking on the file, then using a real editor

**Comment by tomjn** [comment]
I'm unable to replicate this issue, I've modified Hello Dolly using the plugin editor interface in WP Admin succesfully:

<img width="603" alt="screen shot 2018-08-16 at 20 07 09" src="https://user-images.githubusercontent.com/58855/44229455-0a999500-a190-11e8-8fa2-5ce21875eb6d.png">

I would note that this is ill advised, it would be faster and easier to double click on `hello-dolly.php` in the filesystem and open it in Sublime Text or Atom or another editor and make the changes directly.

I'd also note that PHP 7.2 is what runs by default, it's very likely that what you're trying to save is invalid PHP. PHP linting would reveal this, which is supported by most free editors with package management

**Comment by mnelson4** [comment]
> You sure this isn't the PHP fatal error protection kicking in? I've never experienced this

I get this error when just added whitespace to a PHP comment (or the exact change you did there)

> Also I would note that the built in plugin editor is not worth bothering with in VVV because all the files are directly accessible on your file system. 

Right, I'm not using this to edit my files! I'm trying to reproduce an issue our users get when *they* WP's built-in editor on *their* sites. If I could reproduce it, it would help me in debugging.

But ok, so you're not experiencing this error. Maybe I've made some change to my php.ini settings that is causing this or something. But thanks for checking @tomjn. If you're not getting this, then I assume it must just be something weird with *my* setup, not VVV in general. So I think I'll close this issue.

If anyone else experiences it, feel free to resurrect the issue or something
