### ISSUE TITLE
Deprecate Providers

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1615]
At the moment we have provider support that's dependent on historic legacy implementations. This leads to a poor experience when users try to use those and it breaks because nobody has tested it in a long time.

These are also paid software providers, and so imo it's unreasonable to expect a free open project to support without a point person who has that software committing to maintaining and testing, something we do not have at the moment.

So, I propose we show a deprecation warning pushing users to virtualbox and warning that they proceed at their own risk.

We should support:

 - **HyperV** - should probably be kept as those with HyperV enabled for docker use are forced to use this provider
 - **VirtualBox** - should remain the recommended provider

We should deprecate:

 - **Parallels** - this probably works at the moment
 - **vmware_fusion** and **vmware_workstation** - these providers are an unknown, #1614 suggests they are broken. There are no resources or domain knowledge available to debug or diagnose issues with this provider that I'm aware of
 
I would not remove the existing code, and accept fixes if they arrive, but I don't believe we should encourage, advertise or actively support them

**Comment by Mte90** [comment]
I agree on support open source solution and for others, without someone that can test/use it is quite difficult to keep them.

**Comment by benlumia007** [comment]
if we can get hyperv to work, assuming that @LoreleiAurora is working on it. I am happy to test it on Windows 10 Hyper-V.

**Comment by tomjn** [comment]
@benlumia007 I thought it did work?

**Comment by benlumia007** [comment]
@tomjn 
Apparently it did work, now i've been trying to figure it out. right now. i can't mount the shared folders, and  it's giving me a username and password to mount i think. 
[mout.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/2304131/mout.txt)

**Comment by tomjn** [comment]
hmmm if it won't mount shared folders then it doesn't work

**Comment by tomjn** [comment]
Also:
```
Vagrant requires administrator access to create SMB shares and
may request access to complete setup of configured shares.
```

Can you run this with admin privileges?

**Comment by LoreleiAurora** [comment]
Parallels will not be removed any time soon as I continue to use it :)

**Comment by benlumia007** [comment]
@tomjn 
i actually did run git bash (git-scm.com) as administrator, but, it still asks me for the username and password no matter what.

**Comment by benlumia007** [comment]
hmm i have parallel for Mac too, but i think its an older version tho. but i can't find that license key sigh.

**Comment by benlumia007** [comment]
I may try parallel for mac soon too.

**Comment by tomjn** [comment]
@tannerchung did you do that in a shell/prompt with elevated admin priviledges? There are numerous reasons why Vagrant might require them even with permission changes to the hosts file

**Comment by tannerchung** [comment]
@tomjn yeah I opened my shell with Run as administrator

**Comment by boskiv** [comment]
Why you want to deprecate **Parallels** provider, I use it and i like it more than virtualbox.
Is it hard to support it ? May be I can help  ?

**Comment by tomjn** [comment]
> Why you want to deprecate Parallels provider, I use it and i like it more than virtualbox.

That's great, the problem is that if you ran into a problem and needed our help I don't know anybody who runs parallels, so it would be blind speculative debugging. It also means we've no way of testing things.

If you're happy to do that though, then you're more than welcome, I don't like the idea of having providers sit unmaintained, it's embarassing. Hyper-V is a particular edge case because of how it works, meaning anybody doing Docker on Windows needs it turned on, so it can't be dropped :/

**Comment by benlumia007** [comment]
I think that we should keep parallels, I now have a working parallels which will be my main provider for MacOS.

**Comment by benlumia007** [comment]
I believe we have support for VMware as well.

**Comment by tomjn** [comment]
Closing this for now
