### ISSUE TITLE
Deprecate and Redirect vvv.dev

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1623]
IMO we should make moves to remove `vvv.dev` and push people towards `vvv.test`, starting with a redirect in Nginx for any `vvv.dev` domains to their `.test` equivalents.

Thoughts?

**Comment by Mte90** [comment]
The problem is that `*.dev` got a redirect to https and we need to generate a certificate and auto generated certification open an alert inside the browser.

**Comment by tomjn** [comment]
We already handle that with the tls-ca authority don't we?

**Comment by Mte90** [comment]
You are right, I forgot that (I am not using it XD)

**Comment by benlumia007** [comment]
yup, we have already handled that

**Comment by Mte90** [comment]
We deprecated them right now so I think that we can close it

**Comment by tomjn** [comment]
Yep, this got shipped!
