### ISSUE TITLE
Cannot access sites

### ISSUE THREAD

**Issue by PinballWizzrobe** [Varying-Vagrant-Vagrants/VVV#1626]
## Expected Behavior
Accessing vvv.test or local.wordpress.test or any of the other provisioned hosts in vvv-custom.yml should allow access to the corresponding sites/data and show that the service is working.

## Current Behavior
None of the default sites nor my personal defined sites are accessible upon accessing their domains, despite multiple haltings and reloadings of the VM, running the Fresh Start steps in the documentation's troubleshooting section, and a reboot of the machine. No clear errors were given during the provisioning process, and it properly requests sudo password when getting to the hostfiles portion of up and halt.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
This is following a fresh install of Ubuntu with a hard drive upgrade, in which previously, no such errors were encountered despite following the same sequence of steps via the website documentation. I also noted that my previous install also had no issue regarding the .vagrant.d folder's permissions, whereas with the new install I had to go in and grant my home user permissions to get things working.

## Your Environment

* VVV version:  2.2.1
* VVV Git Branch:  master
* Vagrant version: 2.1.3
* VM Provider name:  Virtualbox
* VM Provider version: 5.2.10_Ubuntu r121806
* Operating System and version: Ubuntu 18.04 Bionic Beaver

**Comment by benlumia007** [comment]
Hello
Did you update the hosts file automatically by using the plugin `vagrant plugin install vagrant-hostsupdater` or manually edited the hosts file?

**Comment by benlumia007** [comment]
@tomjn 
Hey just a quick FYI.. vagrant 2.1.3 just got released and It seems like this version doesn't like hosts file it won't completely write the host file, just half for example

192.168.50.4  vvv  #xxxxxxxxxxxxxxxxxxxxx

and it didn't add the .test and new sites. 

but I also went back to 2.1.2 and it works and added the stuff properly. just in case if someone is using vagrant 2.1.3

**Comment by benlumia007** [comment]
vagrant 2.1.4 is out, maybe try that @PinballWizzrobe

**Comment by tomjn** [comment]
So `2.1.3` added support for project specific vagrant plugins:

https://github.com/hashicorp/vagrant/pull/10037

But it looks like it broke some things:

https://stackoverflow.com/questions/52093653/vagrant-2-1-3-doensnt-see-plugin-disksize

One of the changes in 2.1.4 looks to have addressed the issue here:

https://github.com/hashicorp/vagrant/commit/e4da39c011bf5476a1064afbb57904db35ce111f

> host/windows: Fix SMB list parsing when extra fields are included [GH-10156]

As well as hotfixes to plugin wrangling

I would update to `2.1.4`, and try again. If you have no luck, uninstall Vagrant with the uninstaller/uninstall script, then install `2.1.2`

**Comment by tomjn** [comment]
Specifically, in `2.1.3` it looks like once a plugin was loaded, the vagrant file needed reloading so that it could use the plugin, but that wasn't happening

**Comment by benlumia007** [comment]
yup, I just tested vagrant 2.1.4 without any issues. @PinballWizzrobe if you can, if you have time to upgrade to vagrant 2.1.4 and try it again if that solves your problem.

**Comment by PinballWizzrobe** [comment]
The update seemed to take care of it, the sites are up now! Thanks for keeping me posted. Good thing the update literally came same-day. :P
