### ISSUE TITLE
Site is not accessible after vagrant up --provision

### ISSUE THREAD

**Issue by Trekkarr** [Varying-Vagrant-Vagrants/VVV#1627]
Yes I'm on the develop branch

## Expected Behavior

After Vagrant Up --Provision the site is not accessible and I get the following message:

This site can’t be reached
myexamplesite.test’s server IP address could not be found.
Did you mean http://myexamplesite.net/?
Search Google for myexamplesite test
ERR_NAME_NOT_RESOLVED 

## Steps to Reproduce (for bugs)

1. vagrant up --provision
2.
3.
4.

## Your Environment

* VVV version: 
* VVV Git Branch: 
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by tomjn** [comment]
Did you update to Vagrant `2.1.3` prior to doing this? If so, update to `2.1.4`

**Comment by Trekkarr** [comment]
Do I need to state the version I am updating to? If so, how do I do that?

**Comment by tomjn** [comment]
If you run `vagrant --version` and it reports `2.1.3`, then you're running a botched vagrant release. They tried to introduce a new feature that broke vagrant plugins and released `2.1.4` shortly afterwards to address the issue.

`2.1.2` and `2.1.4` are known to work, so download 2.1.4 and install that

**Comment by tomjn** [comment]
I'm going to mark this as closed. The problem is that Vagrant plugins were broken in Vagrant v2.1.3, don't use v2.1.3.

Either update to 2.1.4 or downgrade to 2.1.2
