### ISSUE TITLE
Consolide folders into .vvv and move www up 1 level

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1629]
For a future release I think it would be good to move the `provision` and `config` folders into a `.vvv` subfolder, then move the default sites location up to the root folder, with some backwards compat code to check for `www/` sites that already exist.

Thus a VVV install might look like this:

 - `.vvv/`
 - `wordpress-default/`
 - `vvv-custom.yml`
 - `Vagrantfile`
 - `LICENSE` readme etc..

**Comment by Mte90** [comment]
uhm maybe can be difficult to do a gitignore with gitpull because there are changes not saved? 
I mean I move all the website folders in the root like that and on a git pull what will happen?

**Comment by tomjn** [comment]
hmmm is there no way around that so that only `.vvv` and a selection of root folder files are tracked?

**Comment by tomjn** [comment]
For the moment I've decided that moving `www` up one level can be done in the future once some things are figured out, since `/srv/www` gets mapped on to it, and that would go away if changed. Speaking with @LoreleiAurora though we need to map individual site folders rather than the entire folder

**Comment by tomjn** [comment]
closing this for now, we might revisit this in the future
