### ISSUE TITLE
Double Splash On Vagrant Up

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1631]
Is it just me or is this repeating twice when you vagrant up. was this like this before, cuz i didn't really pay attention

```
Platform:   darwin13.4.0 shell:/bin/bashCaseSensitiveFS 
Vagrant:    2.1.4
VirtualBox: 5.2.18r124319

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

__ __ __ __ 
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.2-develop-git::develop

Platform:   darwin13.4.0 shell:/bin/bashCaseSensitiveFS 
Vagrant:    2.1.4
VirtualBox: 5.2.18r124319

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test
```
didn't know what to label this as ;P,

**Comment by tomjn** [comment]
What was the command ran? You sure it wasn't just 2 vagrant commands `&&` together?

**Comment by benlumia007** [comment]
ha i wish, let me try something neat
![peek 2018-09-11 12-19](https://user-images.githubusercontent.com/11844123/45382408-01e48500-b5bd-11e8-8de6-9d803f0c7d08.gif)

**Comment by tomjn** [comment]
ooo what did you use for that? I can't replicate here, is it possible you have nested VVV installs?

**Comment by benlumia007** [comment]
**Mac**
GIPHY Capture

**Comment by tomjn** [comment]
@benlumia007 did this get resolved?

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1706/commits/efb3dcb6f2e315ef698420a8022703334dcabcf0 should help with diagnosing issues with custom vagrant files

**Comment by benlumia007** [comment]
@tomjn 

YUP, not sure if that fixed it, but i no longer getting that 

Thanks
