### ISSUE TITLE
Add more options on site template

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1632]
Talking with other devs can be handy to add more option on https://github.com/Varying-Vagrant-Vagrants/custom-site-template like to change the locale and define settings in the wp-config and also suite of plugins already available.

**Comment by Mte90** [comment]
I will try to work on that in the next days

**Comment by Mte90** [comment]
I think that we can integrate https://github.com/JPry/vvv-base or a little part

**Comment by tomjn** [comment]
So that templates provisioner uses PHP to do all its work. I think a lot of basic stuff could be done via WP CLI to replicate most of what it does. I'm not a big fan of the inline JSON in YAML though, I'd prefer to see things 100% YAML so that the file can be checked with a schema and validator

**Comment by Mte90** [comment]
Yes my idea is to replicate it many of them without PHP but pure bash using wp-cli.

**Comment by dingo-d** [comment]
Would it be a good idea to add a `branch` besides a `repo` field when creating sites using custom site template?

Use-case: 
Say you want to use the older version where you don't have Gutenberg installed. You have `custom-site-template.git` and in `master` branch you have latest WP, and you could add `4.9.8` branch where you'd set up that older version of WP is installed while provisioning.

That way you can reuse custom site template (one repo multiple branches).

**Comment by tomjn** [comment]
I'm pretty sure you can already do this

**Comment by dingo-d** [comment]
So if I understood correctly, in my `custom-site-template` I'd create a `4.6.4` branch, and in there in the provisioner, I'd set the wp version in the `provision.sh`, right? I was thinking of something like that, it's just that I wasn't aware of the `wp_type` and `wp_version` (couldn't find anything about it in the docs)

**Comment by tomjn** [comment]
No, git branches are completely unrelated to this, and you don't have
direct access to the custom site template provisioner repos anyway.

The repo and branch parameters are for the provisioner git repo, not
WordPress, hence the two custom values

Literally copy paste my example into your config and reprovision and you'll
get WordPress at the desired version

**Comment by Mte90** [comment]
Tadah https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/14
