### ISSUE TITLE
Adding new site with vagrant reload --provision is throwing errors

### ISSUE THREAD

**Issue by mitchelsliwa** [Varying-Vagrant-Vagrants/VVV#1634]
## Expected Behavior

It should create a new folder in my vagrant folder. It should allow me to view the new site from the dashboard.  

## Current Behavior

Problem: Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision.

## Steps to Reproduce (for bugs)

1. CD into my vagrant folder in terminal
2. Run vagrant up
3. Run vagrant reload --provision

https://gist.github.com/mitchelsliwa/44e7a88de1309112d50f5428f83ed910

## Context

I am trying to add a new site to VVV. 

## Your Environment

* VVV version: Newest

* Vagrant version:  2.1.2
* VM Provider name:  Virtual Box 
* VM Provider version: 5.2.18 r124319 (Qt5.6.3)
* Operating System and version:  Mac 10.13.6

**Comment by tomjn** [comment]
@mitchelsliwa which site did you add and what did you add to the config file? Thanks for the log, but without knowing what it was told to provision it has no context

Additionally, not sure why you did `vagrant up` then `vagrant reload --provision`. In future it's much easier to run `vagrant up --provision` or if it's already turned on `vagrant provision`

**Comment by tomjn** [comment]
Also, by newest, do you mean `2.2`, `master`, or `develop`?

**Comment by mitchelsliwa** [comment]
I dont know if its master or dev. How would I check? When I ran git
describe --tags it yielded "2.2.1-1-gb7b51b7"


Here is the custom.yml file. carouselinsider.test is the site I want to
provision.

---

# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten
when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no
exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo:
https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to
WordPress.
  wordpress-develop:
    repo:
https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  carousel:
    hosts:
      - carousel.test

  carouselinsider:
    hosts:
      - carouselinsider.test

  # The following commented out site configuration will create a standard
WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different
things

  #example-site:
  #  repo:
https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a
environment useful
  # for contributions to the WordPress meta team:

  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or
packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
 #   - trusted-hosts
 #   - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be
used to
# increase the memory given to VVV and the number of CPU cores. For WP core
development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within
Vagrant.
# Due to a limitation within Vagrant, the specified provider is only
respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 4096
  cores: 1
  # provider: vmware_workstation

**Comment by mitchelsliwa** [comment]
Also, how come on the VVV site, it says to run reload provision? 

**To add, remove, or change sites, modify vvv-custom.yml then reprovision using vagrant reload --provision**

**Comment by tomjn** [comment]
> Also, how come on the VVV site, it says to run reload provision?
> 
> To add, remove, or change sites, modify vvv-custom.yml then reprovision using vagrant reload --provision

I see, for reference it's not the wrong thing to do, it's just the difference between doing 2000 things and 2002 things. Don't think too much about it, both work, it was more that you ran `vagrant up` first, which was redundant, because the first thing `vagrant reload` then does is turn it off and on again. So just running `vagrant reload --provision` or `vagrant up --provision` would have halved the time it took

I can guess at what the issue is, but your email client has mangled the YAML file, can you share it as a gist or embed it directly via markdown, confirming it hasn't been mangled.

---

My suspicion is that you added a site but didn't add a site template, and then expected VVV to create the folder and fill it with things ( despite there being no template to do that ).

VVV creates the folder by doing a `git clone` of a site template. If you don't provide one, it doesn't create one, because there is no repo to clone.

So you're going to have to create that folder yourself, and then you'll need to manually recreate a site template inside that folder. VVV doesn't know what to tell Nginx, it needs a `provision/vvv-nginx.conf` that it can bundle.

If you're looking to create a new WP install, just use the custom site template

**Comment by mitchelsliwa** [comment]
I was following the instructions from the website. Has the process changed? It doesn't mention anything about needing a folder, or anything about a provision folder etc. Or am I on the wrong section? https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/

I was able to add the provision folder and it worked. I got the site running now.

**Comment by tomjn** [comment]
> I was following the instructions from the website. Has the process changed? It doesn't mention anything about needing a folder, or anything about a provision folder etc. Or am I on the wrong section? https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/

You're on the right section, but all those examples use a site template, whereas you didn't. The follow up articles mention the provisioner files, and the [add an existing site describes your exact scenario and explains why](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/adding-an-existing-site/)

**Comment by tomjn** [comment]
I've created https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1635 so that it's mentioned in the provisioner log if there's no nginx config, but I can't strongly enough recommend just using the custom site template

**Comment by mitchelsliwa** [comment]
Thank you very much!
