### ISSUE TITLE
Nginx config templating

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1643]
There's a few issues and PR's such as #1632 and https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/5, that add things to the nginx config via sed commands, it would make more sense to try and do a basic templating engine, so that the provisioner file only wrangles more complex things

Suggestions?

**Comment by Mte90** [comment]
I think that can be helpful also for that https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/18

Maybe we can think to add in the nginx config a placeholder like `#vvv` and the various script and template append what they need in a specific file and vvv automatically add that content.

Or to be more easyly we can create a new folder for every position we want that scripts can put the file that want are loaded in nginx in a specific folder following the nginx rules (with an include inside the nginx file).

**Comment by tomjn** [comment]
Extending this to utilities is not as easy, I wouldn't hold out hope ( and it isn't needed for that PR )

**Comment by Mte90** [comment]
If we do folders where put nginx configs that hook on the various part this can be used also from utilities.

**Comment by Mte90** [comment]
As today now there is a new folder for utilities but nothing for templates because right now is not clear what we need specifically.

**Comment by LoreleiAurora** [comment]
The [bash implementation of mustache](https://github.com/tests-always-included/mo) would be the way to go here as we are already using basic handlebar syntax with sed.

This will take all environment variables from the script and template them out.

**Comment by tomjn** [comment]
Note that this issue is primarily aimed at site templates for the moment, any utility would need to take the work done for site templates and translate it to whatever the utility needed since a utility may have wildly differing requirements whereas a site template is a much narrower use

**Comment by Mte90** [comment]
I think that we can close this now @tomjn, right now is possible to add a custom nginx file.

**Comment by Mte90** [comment]
I think that we can close this for https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2030

**Comment by tomjn** [comment]
Lets close it
