### ISSUE TITLE
How to delete (or reset) an existing database in VVV?

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1644]
## Current Behavior

I created a new site by adding the following to my vvv-custom.yml:

```
  sovis:
      repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
      hosts:
        - sovis.test
```

I then made changes to the database (and files) without issue (i.e. create new user, etc).  I then (after a `vagrant halt`) deleted all the files associated with this site, and removed the associated code in vvv-custom.yml.  I then ran a `vagrant up --provision`, then another `vagrant halt`. I then re-added a site with the same name, using the same code in vvv-custom.yml.  When I ran a `vagrant up --provision`, a site with the same name had been added to VVV, but the site connected to the *same* database that was previously in-use.  In other words, the site connected to the database that contained my previous modifications, instead of connecting to the default database (i.e. U/N:  admin, P/W:  password).  In a case like this, how would I best bring up this site again, but with a default database ?

## Possible Solution

 When I work with WordPress on my remote web server, the way I typically do this is to login to cpanel, delete the old database, create a new database, and ensure wp-config.php points to this database.  Can I do the same with VVV?  If so, how would I delete the old database and create a new database?

Alternatively, in the past I've used a plugin to reset the existing database for a site (e.g. [WordPress Reset](https://wordpress.org/plugins/wordpress-reset/)).  Would that be a suggested/preferred method in this case?

## Steps to Reproduce (for bugs)

1.  Add a new site to VVV by adding code to vvv-custom.yml.
2.  Run `vagrant up --provision`
3.  To the new site, modify the database by creating a new user.
4.  Run `vagrant halt`
5.  Delete the site files.
6.  Delete the custom code from vvv-custom.yml that adds the new site.
7.  Run `vagrant up --provision'
8.  Run `vagrant halt`
9.  Re-add same custom code to vvv-custom.yml to add the same new site to VVV.
10.  Run `vagrant up --provision`
11.  Open the WordPress site in-question.  The previously modified database will still be connected, rather than the default database.

## Your Environment

* VVV version:   2.2.1-98-g1860077
* VVV Git Branch:  develop
* Vagrant version:  Vagrant 2.1.5
* VM Provider name:    VirtualBox
* VM Provider version:  Version 5.2.18 r124319 (Qt5.6.2)
* Operating System and version:  Win 10, x64

**Comment by tomjn** [comment]
Currently VVV has no way to tie a database to a site, so the databases need
to be manually deleted

Additionally there's a difference between deleting a site, and not
provisioning it. If you remove a site from the config file, VVV won't
provision it as it is no longer aware of it. If it's no longer aware how
would it know to delete it? I'm also opposed to anything that would delete
data as that could lead to accidental data loss

For manually deleting the database, any standard mysql client will do this
though, PHPMyAdmin is bundled but you could use mysql workbench etc

**Comment by cagross** [comment]
OK understood on all.  I just used phpmyadmin and removed the database in-question.  We can consider this resolved, thanks.
