### ISSUE TITLE
Can't find `Auto site configuration` docs for VVV 2+

### ISSUE THREAD

**Issue by bruno-rodrigues** [Varying-Vagrant-Vagrants/VVV#1646]
## Expected Behavior
`Auto site configuration` link  [here](https://varyingvagrantvagrants.org/docs/en-US/references/default-sites/) should take me to a valid VVV 2+ part of docs.

## Current Behavior
The aforementioned link takes me to GitHub wiki page that states:
```
Note: These are old instructions for VVV 1, and will not work in VVV 2+. For the latest documentation see here
```
The `see here` link takes me back to the documentation homepage ( https://varyingvagrantvagrants.org/ ).

## Possible Solution
Pointing the link to a valid VV2 docus page (If this page exists)

**Comment by tomjn** [comment]
Those were set up via copy paste as a lot of the old docs don't have direct
1 to 1 mappings and we were in a rush to make sure they all lead to the new
docs after people would load up the VVV 1 Docs and get confused.

In all honesty I'd rather nuke the v1 docs than go through each page and
adjust the links

**Comment by bruno-rodrigues** [comment]
Do you already have started building the v2 docs? I might be able to help in this quest.

**Comment by tomjn** [comment]
varyingvagrantvagrants.org are the v2 docs, I didn't realise you'd linked to the VVV 2 docs not the github wiki. In which case the correct course of action is to remove the link, or point it to the adding a new sites chapter. That can be done via https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org

**Comment by tomjn** [comment]
I've removed the link int he docs and replaced it with a reference to the adding a new site chapter
