### ISSUE TITLE
403: Forbidden Error on http://wordpress-develop.test/

### ISSUE THREAD

**Issue by mrigankvallabh** [Varying-Vagrant-Vagrants/VVV#1648]
## Expected Behavior
http://wordpress-develop.test/ should be live on local machine

## Current Behavior
http://wordpress-develop.test/ leads to 403: forbidden error

## Possible Solution
Seems like checkout error. 

    default: A    /srv/www/wordpress-develop/public_html/wp-tests-config-sample.php
    default:  U   /srv/www/wordpress-develop/public_html
    default:
    default: Fetching external item into '/srv/www/wordpress-develop/public_html/tests/phpunit/data/plugins/wordpress-importer':
    default: A    /srv/www/wordpress-develop/public_html/tests/phpunit/data/plugins/wordpress-importer/parsers.php
    default: A    /srv/www/wordpress-develop/public_html/tests/phpunit/data/plugins/wordpress-importer/readme.txt
    default: A    /srv/www/wordpress-develop/public_html/tests/phpunit/data/plugins/wordpress-importer/wordpress-importer.php
    default: Checked out external at revision 1957296.
    default: Checked out revision 43733.
    default: npm
    default:
    default: WARN
    default:
    default: rollback
    default:  Rolling back abbrev@1.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/srv/www/wordpress-develop/public_html/node_modules/abbrev/package.json.670452883'
    default: npm
    default:
    default: WARN
    default:
    default: rollback
    default:  Rolling back acorn-dynamic-import@2.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/srv/www/wordpress-develop/public_html/node_modules/acorn-dynamic-import/package.json.1031854201'
    default: npm
    default:
    default: WARN
    default:
    default: rollback
    default:  Rolling back ajv-keywords@3.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/srv/www/wordpress-develop/public_html/node_modules/ajv-keywords/package.json.2780210239'

Full log
https://gist.github.com/mrigankvallabh/de5b1daec476dcfa30dbfb1a259673e0

## Your Environment
* VVV version: 2.3.1
* VVV Git Branch: develop
* Vagrant version: 2.1.5
* VM Provider name: VirtualBox
* VM Provider version: 5.2.18
* Operating System and version: Win 10

**Comment by Mte90** [comment]
Seems that there are issues with NPM on installing grunt.
Can you try with a `vagrant provision`?

**Comment by tomjn** [comment]
Also note that you don't need the WP develop install to do client work or plugin development. That site is intended for work on WP Core itself, contributor days, trac tickets etc.

A standard site template like the first site is more than enough for 99% of what needs doing, provisions faster, and gives you a standard install, rather than a core dev install

**Comment by mrigankvallabh** [comment]
Yes you are right. I do have a working wordpress environment in wordpress-default directory. I just raised this error for sake of completeness in installing. I will try the vagrant provision.

**Comment by mrigankvallabh** [comment]
Closing this issue as it is not affecting my wordpress development. The default wordpress env is available.
