### ISSUE TITLE
Add PHP 7.3 to the core utility

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1651]
Ondrej has started building PHP 7.3 packages upstream, we should add them as an option ASAP

**Comment by Mte90** [comment]
I done a provision yesterday and I got installed php7.3 in VVV and php command symlinked to php7.3 creating issues with WPCLI because WP right now doesn't support the 7.3.
So I manually removed the symlink and made a new one.

**Comment by tomjn** [comment]
are you sure that's not because Ondrej made a mistake yesterday for a few hours?

**Comment by Mte90** [comment]
maybe, I don't know right now
