### ISSUE TITLE
cannot add new sites modyfing custom.yml

### ISSUE THREAD

**Issue by JoeHell02** [Varying-Vagrant-Vagrants/VVV#1652]
Hi, I'm pretty new in vvv and in coding as well, im experiencing a problem adding new sites through custom.yml. The url doesn't work, my file is in the vagrant-local, plugins such as hostsupdater and vbguest are already installed and up to date. I can enter the url's in the config.yml but modifying the custom.yml and doing reload --provision I can't open the new websites and no new directories are created in www. The synthax in the custom.yml is correct

## Expected Behavior
Activation of a new website.test and creation of the new directory in www

## Current Behavior
doing reload --provision seems like vvv doesnt find the custom.yml or read properly its information

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version: 2.3.1
* VVV Git Branch: 
* Vagrant version: 2.1.5
* VM Provider name: 
* VM Provider version:
* Operating System and version: Windows 10

**Comment by tomjn** [comment]
@JoeHell02 can we see your `vvv-custom.yml`?

**Comment by JoeHell02** [comment]
---

# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    africome-test:    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    allow_customfile: true    hosts:     -africome.test    #- my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 1
  # provider: vmware_workstation

**Comment by JoeHell02** [comment]
![vvv-custom yml - blocco note 2018-10-17 16 08 52](https://user-images.githubusercontent.com/35630044/47092300-07ba2f80-d227-11e8-8d76-23b28da2985e.png)

**Comment by JoeHell02** [comment]
![log provision 1](https://user-images.githubusercontent.com/35630044/47092366-24566780-d227-11e8-81f4-edb5af87ee3c.png)
![log provision 2](https://user-images.githubusercontent.com/35630044/47092369-26b8c180-d227-11e8-95de-c79f3dc736bd.png)
![log provision 3](https://user-images.githubusercontent.com/35630044/47092370-27e9ee80-d227-11e8-9a72-de1070bab839.png)
![log provision 4](https://user-images.githubusercontent.com/35630044/47092375-29b3b200-d227-11e8-9339-29931bff1a79.png)
![log provision 5](https://user-images.githubusercontent.com/35630044/47092378-2ae4df00-d227-11e8-8901-85aee7824bfc.png)
![log provision 6](https://user-images.githubusercontent.com/35630044/47092381-2c160c00-d227-11e8-8f19-2a5b49cb7b16.png)
![log provision 7](https://user-images.githubusercontent.com/35630044/47092386-2d473900-d227-11e8-80e1-38388f600229.png)
![log provision 8](https://user-images.githubusercontent.com/35630044/47092390-2e786600-d227-11e8-8ffa-581099ca6f74.png)
![log provision 9](https://user-images.githubusercontent.com/35630044/47092391-2fa99300-d227-11e8-98f3-dd908e9f47ad.png)
![log provision 10](https://user-images.githubusercontent.com/35630044/47092396-320bed00-d227-11e8-8c19-c2bca6871cd0.png)

**Comment by tomjn** [comment]
@JoeHell02 can you post as a gist or in a code block? The photo of the config file isn't formatted or searchable

**Comment by JoeHell02** [comment]
---

# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    africome-test:    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    allow_customfile: true    hosts:     -africome.test    #- my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 1
  # provider: vmware_workstation

**Comment by JoeHell02** [comment]
sorry is a bit messy

**Comment by JoeHell02** [comment]
can you see the log ?

**Comment by tomjn** [comment]
The problem is here:

```yaml
  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    africome-test:    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    allow_customfile: true    hosts:     -africome.test    #- my-example-site.test
```

This isn't valid:

 - half the sites definition is smushed on to a single line that isn't indented correctly
 - the name of the site is commented out with a `#`
 - The site template repo is on the same line as the site name, and also commented out

In a YAML file, everything is significant, needs to be on its own line, and indented correctly. `#` is for commenting stuff out. I'd also advise against `allow_customfile`, custom vagrant files are a great way to break things, only use them if you absolutely know what you're doing ( aka you could have built VVV yourself but decided to save time )

it should look like this:

```yaml
  africome-test:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - africome.test
```

**Comment by JoeHell02** [comment]
@tomjn wich app should I use to modyfying and indenting correctly this file ?

**Comment by tomjn** [comment]
You should be able to do it in any app, as long as you stick to spaces and it follows standard YAML

**Comment by JoeHell02** [comment]
I think I indented in the wrong way using notepad...ok thanks, i'll try to modify it in another way, thanks!

**Comment by Mte90** [comment]
Maybe we need a check if the vvv-custom file is creating issue with yaml and block the process.

**Comment by tomjn** [comment]
In this case the YAML formatting was valid, but it wasn't a valid VVV config, we'd need a schema checker for that

@JoeHell02 you should find things easier with an editor such as Atom, VS Code, or Sublime. They'll indent automatically on new lines, and add syntax highlighting. Also they're good for taking notes :)

**Comment by JoeHell02** [comment]
What's wrong this time with the indenting ? I used notepad++
I also have to say that I tried using the working custom file of a friend and it doesnt work on my pc as well...maybe the problem is something else.

```yaml

---

# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  africome-test:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - africome.test
      
    

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 1
  # provider: vmware_workstation

**Comment by tomjn** [comment]
I don't see anything wrong with that `vvv-custom.yml`

Just to be clear, it's `vvv-custom.yml` not `vvv-config.yml` we're talking about right? `vvv-config.yml` is just the default

**Comment by JoeHell02** [comment]
yes, I didnt modified at all config.yml, i modified custom.yml

**Comment by JoeHell02** [comment]
should I install something in my PC to let vvv work properly ? Is a new pc, I only installed vagrant and virtual box

**Comment by tomjn** [comment]
does it show in the list on `vvv.test`? And does the folder get created?

**Comment by JoeHell02** [comment]
no isnt in the list on vvv.test...and no folder has been created inside www

**Comment by Mte90** [comment]
So if you try to open vvv.test on the browser what kind of error you get?
Because seems that everything is downloaded and configured.

**Comment by JoeHell02** [comment]
just tried, nothing changed

**Comment by Mte90** [comment]
Well you have to change the order and do a vagrant halt/up.
In the past I had a similar problem and this fixed for me, if the problem happen also with you we have a confirmed bug.

**Comment by JoeHell02** [comment]
what do you mean "change the order" ? what's the correct order in the custom file ?
also, is vagrant/halt the same of doing a reload, isn't it ?

**Comment by Mte90** [comment]
Move the setting block that now is the third one of your website to the first one.
Halt/up shutdown/restart the machine, reload is another thing.

**Comment by Mte90** [comment]
Problem resolved was using 2 different installation of vvv ed executing form the one where he wasn't doing changes.

**Comment by JoeHell02** [comment]
it's embarassing....I dont know why I had more than one installation actually...aniway let me try before to say is "solved" :P

**Comment by tomjn** [comment]
Reordering the sites in `vvv-custom.yml` won't do anything other than change the order they're provisioned in. It won't fix anything, and shouldn't make any difference.

If it does fix something, it's probably a syntax error that were accidentally fixed during re-ordering

**Comment by JoeHell02** [comment]
@tomjn thanks for the support....probably the first problem was the indenting, when I was trying to solve that I run another installation of vvv and I wasnt aware of this, I created some folders with same names but different address. Then I adjusted the indenting but I was in the wrong folder! Now It works...thanks for all

**Comment by JoeHell02** [comment]
thanks @Mte90 ! for the patience and the support
