### ISSUE TITLE
Support Vagrant 2.2.0 for autodownload plugins

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1654]
## Expected Behavior
Vagrant auto download the hosts plugin so is a step already done

## Current Behavior
Now is manually

## Possible Solution
https://www.hashicorp.com/blog/vagrant-2-2-0

Vagrant 2.2.0 support a new parameter where is possible to define the plugin and he will try to download and install automatically.

**Comment by tomjn** [comment]
Something similar can be done with vagrant2.1.4 it just require a little extra work ( it's what broke vagrant 2.1.3 ).

This would mean updating the vagrant requirement though
