### ISSUE TITLE
Upgrade NodeJS to 8.0

### ISSUE THREAD

**Issue by atimmer** [Varying-Vagrant-Vagrants/VVV#1661]
## Expected Behavior

I can use NodeJS 8 inside the VM.

## Current Behavior

NodeJS is on version 6

## Possible Solution

Use `nvm` or something else to set the NodeJS version to 8.

## Context

Building WordPress 5.0 requires NodeJS 8

**Comment by dingo-d** [comment]
Isn't [Node.js 10.x set to LTS](https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51?_branch_match_id=584332641895659471)? Why not updating to that version?

**Comment by tomjn** [comment]
@atimmer to future proof a little what's the newest Node version we can use?

**Comment by atimmer** [comment]
In that scenario I would recommend 10. People can quickly go back to 8 with `nvm` if they need to.

**Comment by tomjn** [comment]
so part of this is that we install node via `apt-get` [here](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L96) and Node 6 is the latest that Ubuntu 14 has to offer. An alternative method of installing, or an apt-source with the newer version will be needed

Updating the Ubuntu box itself to 16 or 18 is non-trivial and would involve forcing people to back up their dev environment and restore on to a clean slate

**Comment by tomjn** [comment]
We should be able to switch over to the nodesource PPA

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

https://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm#635469

**Comment by tomjn** [comment]
Something like this:


```
curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
sudo apt-add-repository "deb https://deb.nodesource.com/node_10.x $(lsb_release -sc) main"
sudo apt-get update
sudo apt-get install nodejs
```

I'm not sure if that will update existing VVV boxes to Node 10, or if they will remain on 6 though. Adding the apt repo should be easy as we have provisioner code to do that already, and it already tries to install that package

**Comment by tomjn** [comment]
Turns out we already do this for Node 6

**Comment by tomjn** [comment]
@atimmer can you verify all is well with #1662?
