### ISSUE TITLE
newly installed vvv, vagrant up but vvv.test - the page was not found

### ISSUE THREAD

**Issue by kosiew** [Varying-Vagrant-Vagrants/VVV#1670]
## Expected Behavior

After installing VVV and running vagrant up, I should be able to go to http://local.wordpress.test/ or http://vvv.test and see a site.

## Current Behavior

Both http://local.wordpress.test/ or http://vvv.test give me Page not found error.
http://cld.wthms.co/YbVnqm

## Steps to Reproduce (for bugs)

This is a brand new computer. I followed the installation instructions carefully.

Provisioning output can be seen here: 
https://gist.github.com/kosiew/1f24da32431d008092e098722fc8a316

## Context

I'm just trying to do an initial, out-of-the-box, totally normal installation.

## Your Environment

* VVV version:  2.4.0
* VVV Git Branch:  master
* Vagrant version: 2.2.0
* VM Provider name:  VirtualBox
* VM Provider version: 5.2.20r125813
* Operating System and version: mscOS 10.13.6

**Comment by kosiew** [comment]
@tomjn, Thanks for your prompt reply on a weekend !!

"the gist linked to is just for a vagrant up, there's no provisioning going on"
I was following these instructions on https://varyingvagrantvagrants.org/docs/en-US/installation/.

![screen shot on 2018-10-28 at 21-30-38](https://user-images.githubusercontent.com/29057562/47616528-f3b0e080-daf8-11e8-9367-870e9d3adc09.png)

At step 3, http://vvv.test is supposed to be available.

Can you tell me the correct way to start vvv ?

**Comment by tomjn** [comment]
The first time it's meant to provision automatically, so vagrant up is
correct. Are you absolutely sure that was the first time you ran vagrant up?

Run vagrant up --provision and try again

**Comment by tomjn** [comment]
but if I'm honest this looks like you forgot to install the hosts updater
plugin. Without that plugin your hosts updater file will not be updated and
you won't be able to use human readable URLs

**Comment by kosiew** [comment]
@tomjn, "this looks like you forgot to install the hosts updater"

Running "vagrant plugin install vagrant-hostsupdater" solved it.

Perhaps, add the above command as a common troubleshooting step to the documentation at https://varyingvagrantvagrants.org/docs/en-US/installation/ :-).

Thanks.

**Comment by tomjn** [comment]
Awesome, glad you got it sorted

**Comment by tomjn** [comment]
We do list hosts updater in the software requirements section, though in future a code check that forces VVV to abort if it isn't present might be desirable
