### ISSUE TITLE
Replace Docs examples with links

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1676]
The standard site template works well for this, we should switch to using it instead with links, and save having to manually update docs ( or forgetting to )

**Comment by Mte90** [comment]
We still needs this task?

**Comment by tomjn** [comment]
Yeah this still needs doing, otherwise we're maintaining 2 copies of everything, 1 in the template, the other in the docs

**Comment by Mte90** [comment]
For me is not quite clear what is task is related can you do an example about the changes that we have to do?

**Comment by tomjn** [comment]
So in our docs we’ll have a code block example of how to do a site
provisioner, which we then have to maintain. So why not just link to the
actual provisioner in the custom site template and save some time? Then we
don’t have to go back and update it

**Comment by Mte90** [comment]
AS you asked https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/134 :-)
