### ISSUE TITLE
Starting MariaDB database server mysqld

### ISSUE THREAD

**Issue by yaacine** [Varying-Vagrant-Vagrants/VVV#1678]
Hi, 
I am getting this error when running vagrant up  

```
Platform:   mingw32
Vagrant:    2.2.1
VirtualBox:

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
    default:  * Stopping MariaDB database server mysqld
    default:    ...fail!
    default:  * Starting MariaDB database server mysqld
    default:    ...fail!
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

any idea about the solution please ?

went wrong.

**Comment by Mte90** [comment]
I had the same problem, done a `vagrant destroy` and `vagrant up` and everything was fixed.
I think that something on provision fault in a bad way and this created issues.

**Comment by tomjn** [comment]
@yaacine  there's some super important information you left out ( there's a reason it's pre-filled in the new issue template ).

Without, diagnosing and figuring out the solution is 1000x more difficult and in a lot of cases impossible. Please include as was originally requested:

 - OS/Platform you're using
 - Provider ( HyperV? Parallels? VirtualBox? etc )
 - The version of said provider
 - The version of VVV being used

Also, is this a new VVV? An old VVV that's just been updated? A VVV that has just randomly stopped working? Have you tried turning it off and on again? Reprovisioning? Destroying and recreating?

Please respond with the answers to **all** the questions, even if the answer is _I don't know_

**Comment by tomjn** [comment]
I'm closing this out as the OP became unresponsive
