### ISSUE TITLE
fails to initialize - Vagrantfile undefined method line 511

### ISSUE THREAD

**Issue by bzkn** [Varying-Vagrant-Vagrants/VVV#1680]
## Context
I was trying to update VVV from 2.1.0 to 2.4.0.
I already updated Vagrant and VirtualBox and tried using the VVV develop branch.

When I do `vagrant up --provision` I get the following error:

```
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/username/vagrant-local/Vagrantfile
Line number: 511
Message: undefined method `[]'
```
The line 511 in Vagrantfile is ` vvv_config['dashboard']['repo'],`

php error log: https://gist.github.com/bzkn/19fd0ff2d07030b7ba5c2f1ec2a3e1a3

## Your Environment
* VVV version: 2.4.0
* VVV Git Branch: master
* Vagrant version: 2.2.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.22
* Operating System and version: MacOS Sierra (10.12.6)

**Comment by bzkn** [comment]
Can confirm nothing modified in Vagrantfile.
Here's the vvv-custom.yml https://gist.github.com/bzkn/51cffdf35cc6e2530cd910fb353818ac

**Comment by tomjn** [comment]
Hmm nothing unusual there

**Comment by bzkn** [comment]
This may not be relevant but during the update process, at first I did not update Vagrant and VirtualBox. It was only after I started getting plugin errors that I checked the VVV site and saw the requirements for VVV 2.4.0. To fix the plugin issue I did the `vagrant plugin expunge --reinstall` command.

**Comment by bzkn** [comment]
I fixed it. I removed the **Customfile** file from the **/vagrant-local/** directory since I did not see it in the repo. This file is what was giving me the double splash on vagrant up as reported in this [thread](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1631). I became suspicious that this was the culprit because the second splash was the old logo/version for 2.1.0.
