### ISSUE TITLE
Vagrant + Windows = 💩

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#1682]
## Expected Behavior
vagrant up -> working 💩 

## Current Behavior
I set up a new machine and just installed virtualbox (current version) + vagrant (current version) = not working as always

Now it is this error for any vagrant command I issue. `vagrant up` results in the same error.
```
PS C:\Windows\system32>  vagrant box update
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/hostsupdater
```
This error is the same with any vagrant plugin. ANY. So it is a vagrant issue I can not find in any search.

If I uninstall all plugins the provisioning fails this way: https://gist.github.com/cfoellmann/fed9172d56c7c6f764442bbc08f9140b

## Possible Solution

Nuke my system and install older Win build!? Not gonna happen.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Windows 10 Pro updated to the bad current release of __1809__!!
Running a AzureAD-connected user account.

If it was any other program than vagrant I would suspect a permissions issue. But with vagrant it might just be another bug nearly impossible to debug.

## Your Environment

* VVV version: develop
* VVV Git Branch: develop
* Vagrant version: 2.2.2
* VM Provider name: VB
* VM Provider version: 5.2.2
* Operating System and version: Win 10 Pro __1809__!!

**Comment by tomjn** [comment]
I'm not sure what you mean by the bad windows 10 Pro release can you be
more specific what you mean?

Additionally I'd recommend a clean vagrant install, and reinstall along
with the plugins. Any stack traces in logs that elad to vagrant files are
99% of the time vagrant bugs and should be in the vagrant GitHub issues

**Comment by cfoellmann** [comment]
The current Windows Semi-Annual Update __1809__. The rollout was canceled in october but I did a force install on my clean install.
Maybe it is an issue there.

I did clean installs of all kinds of vagrant versions. including removing `.vagrant.d` folder.

I know that it is likely a vagrant issue but was hoping someone here might have had a similar issue in the past.

If vagrant wasnt soooo hard to maintain I would automate the complete VVV install with a chocolatey package but all my tests resulted in issues like this.

**Comment by cfoellmann** [comment]
I found the error and it seems to work now.
It was a "bad" character in the path of my user account. I have an "umlaut" in my name and AzureAD seems to be sooo progressive that a German "ö" is not converted into "oe" anymore for the foldername.

If this fixes things I will finally create a chocolatey package to install VVV with one command on Windows.

**Comment by Mte90** [comment]
I can confirm this issue with another user with `totò` as username have the same issue.
This fix the issue https://github.com/hashicorp/vagrant/issues/2113#issuecomment-480650634 it is a workaround, I think that I will add something in the fag of vvv
