### ISSUE TITLE
SSH authentication failed on vagrant halt

### ISSUE THREAD

**Issue by harkor** [Varying-Vagrant-Vagrants/VVV#1688]
## Expected Behavior
When I execute vagrant halt, I have this message (on master or develop I have the same problem)

```
==> default: Running triggers before halt ...
==> default: Running trigger: VVV Pre-Halt...
==> default: Trigger run failed
==> default: SSH authentication failed! This is typically caused by the public/private
==> default: keypair for the SSH user not being properly set on the guest VM. Please
==> default: verify that the guest VM is setup with the proper public key, and that
==> default: the private key path for Vagrant is setup properly as well.
```

## Steps to Reproduce
0. Remove old VM is needed
1. git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git
2. cd vvv
3. vagrant up
4. vagrant halt

Full log when halt : https://gist.github.com/harkor/9ff5545d618f27817cacccd709e88b3a

## Your Environment
* VVV version: 2.4.0
* VVV Git Branch: master or develop same result
* Vagrant version: 2.2.2
* VM Provider name: VirtualBox
* VM Provider version: 5.2.22r126257
* Operating System and version: ArchLinux up to date

## What I tried
* Destroy VM
* Reboot computer
* Check my ssh configuration

**Comment by harkor** [comment]
When first start I see a lot of
`default: /tmp/vagrant-shell: line 377: xxx: command not found`

Replace xxx  by grunt or provision-network-functions.sh and other things. in vagrant-shell

**Comment by tomjn** [comment]
Is this a new issue on a new instance? Or is this a new issue on an old instance that previously worked? Have you recently updated vagrant or virtualbox?

**Comment by tomjn** [comment]
@harkor I think some clarification is needed:

 - Does this only happen on halt?
 - Was the VM running at the time, or was it suspended?
 - Is the VM functional when it's up?
 - Does this happen on `vagrant up`?

I also notice you tried to be helpful/concise and only show what you thought was relevant, but can you include an example with the output in its entirety, including the commands you used?

**Comment by harkor** [comment]
I tested 1 hour ago on another computer (ArchLinux too). The problem with SSH is away.
The problem with SSH on my computer is when I do "vagrant halt" and scripts for halt like backups of database is not triggered.

Except the halt, vvv is working fine, I can dev on websites.

The second "problem" (I don't know if it's a real problem), I can see it on a fresh install of VVV.

How can I give you entire log ? When VM is up I can't scroll to the begining.

**Comment by tomjn** [comment]
hmmm you should be able to copy paste from your terminal app, or at least pipe the result of the vagrant command into a file. Does it prevent you from halting the VM?

Note that on halt you can get a vagrant warning, there's a backup script that runs, but if the VM is in a suspended state or if you try to destroy a VM that's already been switched off, it can't run the backup trigger and complains. Sadly there's no option that lets us tell vagrant to only run it if the VM is up

**Comment by tomjn** [comment]
Closing this out due to inactivity. This will need replicating on the newer VVV 3.X
