### ISSUE TITLE
Vagrant Up

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1698]
This may not be a big problem, i just realized when you vagrant up for the first time, it will import the box and create a vm and it will rename the box to like WordPress_xxxxxxxx, I just realized that duing that process,  the box itself doesn't get moved to the new folder. 

This only seems to happen on Windows. 

ubuntu-cloudimg-trusty-vagrant-amd64
WordPress_xxxxxxx

It should delete the ubuntu-clouding after it gets rename.

**Comment by benjaminlu007** [comment]
![image](https://user-images.githubusercontent.com/34381548/50666787-2ea51980-0f6b-11e9-89f0-8a550cb3d823.png)

**Comment by benjaminlu007** [comment]
basically inside of the ubuntu-cloudimg... contains the box-disk.vmdk which was supposedly moved to the WordPress folder and the ubuntu-clouding gets removed/deleted.  

It just weird because my mac and linux doesn't happen so.

**Comment by benjaminlu007** [comment]
![image](https://user-images.githubusercontent.com/34381548/50669586-daa23100-0f7a-11e9-8a01-8a0fc8ae4053.png)
I'll see if i can report this with vagrant.

**Comment by tomjn** [comment]
ok, but even if we wanted to we have no control over those files. The closest we can do is change the vagrant provider and try to pass through configuration options. How VirtualBox manages the VMs themselves and where they're place is something else entirely
