### ISSUE TITLE
Provision Halted: Main packages check and install failed after GPG error and git-lfs authentication fail warning.

### ISSUE THREAD

**Issue by lidocaine** [Varying-Vagrant-Vagrants/VVV#1700]
## Expected Behavior
VM provisions and starts.

## Current Behavior
Provisioning fails after GPG error and `git-lfs`-related Warning.

## Steps to Reproduce (for bugs)
1. Clone VVV repo (master or dev, it doesn't seem to matter)
2. Create a `vvv-custom.yml` from `vvv-config.yml` creating only one site instead of the 3 defaults
3. Run `vagrant up` or `vagrant up --provision`

A copy of my `vvv-custom.yml` file can be found at:
https://gist.github.com/lidocaine/3afc0b27a1745c8d381a2e42ac0d9fb3

A copy of the provisioning output can be found at: https://gist.github.com/lidocaine/ad994defb0fb2749fb5d800f0c180a40

## Possible Solution
Probably related to Issue #1598 but the errors occurring during provision are not the same.

## Context
I'm attempting to set up a fresh VVV environment for a single site. Switching from VCCW.

## Your Environment
* VVV version: 2.4.0
* VVV Git Branch: master
* Also occurs on VVV v2.5.0-git::develop
* Vagrant version: 2.2.2
* VM Provider name: VirtualBox
* VM Provider version: 5.2.22r126460
* Operating System and version: MacOS 10.14.2

**Comment by tomjn** [comment]
2 options:

 - if at first you don't succeed, try again, reprovision and it might work
 - change `provision/provision.sh` to use `--force-yes` as well as `-y` in https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L266 and let me know how it goes

Eitherway, the `apt-get` part of provisioning happens on every VM provision and has seen little change over the years. If it fails, it's usually because it chose a mirror that's unreliable to grab the package, or because the local network/ISP is rubbish/temporary issues. There's only so much you can do to ward off network problems

**Comment by lidocaine** [comment]
> * if at first you don't succeed, try again, reprovision and it might work

I've reprovisioned, destroyed and provisioned, restarted the machine, changed from master to dev, etc etc... but the error(s) continued to plague my very existence.

> * change `provision/provision.sh` to use `--force-yes` as well as `-y` in https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L266 and let me know how it goes

This worked, thank you! I'm curious though; is this actually a bug that needs to be fixed? I found a [really old issue](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/78) that addressed the use of `--force-yes` but with no apparent resolution. It seems VVV used to use `-y --force-yes` at some point?

**Comment by tomjn** [comment]
I'm unsure why it's needed, or why authentication fails, but glad it works for you

**Comment by tomjn** [comment]
@lidocaine can you test https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1702 ? It contains a proper fix, Packagecloud.io changed their GPG keys and we were caught unawares

**Comment by colebennington** [comment]
@tomjn What places in these files do I need to put --force-yes and -y? I am having the same issue described here

**Comment by psaikali** [comment]
Thanks @tomjn, the `--force-yes` solution worked for me on a brand new VVV installation!

@colebennington : the line to edit looks like that:
```if ! apt-get --force-yes -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install --fix-missing --fix-broken ${apt_package_install_list[@]}; then```

**Comment by thomkitchen** [comment]
Just came in to say I had this issue as well and adding the --force-yes flag also fixed it for me

**Comment by lidocaine** [comment]
> @lidocaine can you test #1702 ? It contains a proper fix, Packagecloud.io changed their GPG keys and we were caught unawares

@tomjn Sure thing; I'll give it a test within the next hour or so and report back.

**Comment by tomjn** [comment]
#1702 has been merged, it doesn't contain the `--force-yes` flag, which shouldn't be necessary, though I'll be adding that in a separate PR just for the added robustness

**Comment by tomjn** [comment]
@lidocaine thanks, https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1703 follows up with the other robustness changes so that should the key change again in future it'll be less failure prone
