### ISSUE TITLE
During installation of vvv i got this issue ? The following packages cannot be authenticated!  git-lfs  

### ISSUE THREAD

**Issue by locougil** [Varying-Vagrant-Vagrants/VVV#1707]
Can someone help me please?
Thank you so much 

Here is what i got on the terminal : 
![terminal-screen](https://user-images.githubusercontent.com/46594787/51075382-dc5ea980-168a-11e9-9b04-6ccc367dbfe3.jpg)

**Comment by tomjn** [comment]
This is fixed in the develop branch

**Comment by SimonMayerhofer** [comment]
Switching to dev branch fixed it for me 👍

**Comment by tomjn** [comment]
Marking this as closed as it's fixed in `develop`, for those unsure they can run `git checkout develop` and `git pull` to switch over. Otherwise I'm aiming for a v2.5.1 release once a certain PR has gone through final testing
