### ISSUE TITLE
Bundle Query Monitor with the custom site template

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1716]
It would be good if the custom site template installed and activated query monitor by default so that debugging is easier

**Comment by benlumia007** [comment]
`wp plugin install query-monitor --activate` would do it during the vvv-init.sh install.

**Comment by Mte90** [comment]
yes but I think that this depend on #1632.
So with a flag will be possible to install plugins. I was studying yesterday how to add new fields in the yaml plugin to specify the plugins to download.

**Comment by benlumia007** [comment]
i actually figured how when you have fields in yaml that you want to add, after you add those fields,  the provision will use shyaml to get the value of the new custom field and use that to create or install a plugin.

**Comment by benlumia007** [comment]
`cat vvv-custom.yml | shyaml get-value sites.custom`

something like that.

**Comment by tomjn** [comment]
there's already a bash function for grabbing values from the config in the sites provisioner

**Comment by benlumia007** [comment]
maybe just extend it so it grabs `custom -> plugin-dev`

**Comment by Mte90** [comment]
Yes there is already, if @benlumia007 want to try to do a pull request to the template is not a problem.
I was only studing better for #1632 how to do everything :-)

**Comment by benlumia007** [comment]
is query monitor the only one we need for now before i continue a pull request

**Comment by tomjn** [comment]
for now yes, personally I think it should come with it by default, I'd suggest naming it something like `install_recommended_plugins` rather than `plugin-dev`

**Comment by tomjn** [comment]
or maybe even just `querymonitor`

**Comment by benlumia007** [comment]
i was going to suggest 
```
  custom:
    wp_type: subdirectory
    wp_version: 4.6.4
   wp_plugin: true
```
I was thinking wp_plugin if it is set is true, then we can install query monitor, if we need more then all we just need to do just add each plugin and activate. 

would this make more sense.

**Comment by tomjn** [comment]
I'm not so keen as it doesn't really indicate what it means and isn't self
documenting. It also implies that you can put a list of plugins in which
isn't how it works

**Comment by benlumia007** [comment]
im just throwing ideas here, instead of putting a custom field just for query monitor and since this is going to be a permanent plugin that will be install, would it be easier just to add 

`noroot wp plugin install query-monitor --activate` under the installation of wordpress in custom-site-template 

it would just go underneath
`  noroot wp core ${INSTALL_COMMAND} --url="${DOMAIN}" --quiet --title="${SITE_TITLE}" --admin_name=admin --admin_email="admin@local.test" --admin_password="password"`

**Comment by tomjn** [comment]
lets start with that, I think being able to disable it is important, we might also want to update it as well

**Comment by Mte90** [comment]
I was thinking that we can add a parameter `plugins:` so we can put the query monitor plugins and the users can use this also for others plugins.
So in the future we can add also other plugins like user-siwtcher or airplane-mode as example.

**Comment by Mte90** [comment]
I can work on that in the next days but I prefer to know about my other pr (tideways) or template(the one about wpcli) before add other stuff in queue that became old and create issue on manage them before approve.

**Comment by Mte90** [comment]
And this one add also support for custom plugin to install https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/14 but require to test it

**Comment by benlumia007** [comment]
is this done, if it is, we can closed this :D

**Comment by Mte90** [comment]
The pr is done but not yet merged so we cannot close it

**Comment by Mte90** [comment]
Done :-D
