### ISSUE TITLE
Update Check in Dashboard

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1717]
The dashboard should poke GitHub to figure out the latest release, and compare it to its own version to figure out if an update is available

**Comment by tomjn** [comment]
A bit of testing suggests we can do a request to the github api and figure out the latest release, then do a version compare against the current `version` files contents

https://api.github.com/repos/Varying-Vagrant-Vagrants/VVV/releases/latest

https://developer.github.com/v3/git/tags/

**Comment by msaggiorato** [comment]
Should this be addressed here https://github.com/Varying-Vagrant-Vagrants/dashboard/pull/1?

**Comment by tomjn** [comment]
No, that's more a rebuild of the dashboard in React, it needs a significant amount of work before it can be merged
