### ISSUE TITLE
xdebug not working for PHP 7.3

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#1721]
if I set

` nginx_upstream: php73 `

in vvv-custom.yml file for particular site setup for that then xdebug not working

**Comment by tomjn** [comment]
Right now there is no working PHP 7.3 + XDebug working combination available ( it's not just a VVV thing ), a PHP minor release should fix that

**Comment by debabratakarfa** [comment]
I thought, it have https://xdebug.org/updates.php

```
Fixed bug #1519: PHP 7.3 support (with a contribution by Christoph M. Becker)
```

**Comment by tomjn** [comment]
That's a beta release, I don't believe it becomes available via our install
method until a stable one is released

Otherwise we'd have to rewrite how xdebug gets installed then change it back

IIRC it's installed via the Ondrej PHP PPA

**Comment by Mte90** [comment]
I think that is not a problem anymore.

**Comment by benlumia007** [comment]
has this been tested and verified?

**Comment by Mte90** [comment]
xdebug right now support php 7.3 since the 2.7 release of march https://xdebug.org/updates.php

**Comment by benlumia007** [comment]
should we be closing this ticket.

**Comment by tomjn** [comment]
Yes, it was never really something within our power to solve without building PHP from scratch anyway
