### ISSUE TITLE
How to check if an nginx module is enabled (ngx_http_headers_module)?

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1722]
## Current Behavior

On my VVV site, a WordPress plugin ([Hummingbird](https://wordpress.org/plugins/hummingbird-performance/)) is indicating that my server may not have the "expires" module enabled ([ngx_http_headers_module](http://nginx.org/en/docs/http/ngx_http_headers_module.html) for NGINX).  See screenshot [here](https://imgur.com/PtUZlPv).  How would I go about checking if this module is enabled, and if not, enabling it?

At some point, would I need to edit the [VVV Nginx config file](https://varyingvagrantvagrants.org/docs/en-US/site-templates/nginx-configuration/)?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* VVV version:  2.4.0-28-g5938fde
* VVV Git Branch:  develop
* Vagrant version:  Vagrant 2.2.3
* VM Provider name:   VirtualBox
* VM Provider version:  Version 5.2.22 r126460 (Qt5.6.2)
* Operating System and version:  Windows 10

**Comment by Mte90** [comment]
The caching with nginx is on the server side so doesn't involve your database.
If your production server has that module this will gone on the other site without creating any other issue.

**Comment by cagross** [comment]
@Mte90 Here is how the plugin devs have described the situation to me.  My VVV site is on an nginx server and my live site is on an Apache server.  If I want to push my VVV database to my live site, and have browser caching enabled on my live site when that occurs, I first need to ensure browser caching is enabled--with no errors--on my VVV site.  Currently, browser caching is not enabled on my VVV site and the admin page is indicating an error.  So if I push this DB to the live site right now, the plugin on the live site will also think there is an error with browser caching.  It is only after I get browser caching working on the VVV site that the error will go away.  At that time, when I push the DB to the live site, browser caching will be enabled on the live site.  I hope that makes sense.

This is all described in the post I linked.  It doesn't sound like the smartest or most convenient way to do this.  But I'm trying to see it through.

**Comment by Mte90** [comment]
Well if you have a different web server this is a problem.
Anyway I don't think that is easy to customize the nginx rules of vvv and avoid thath the provisioning will change them.
That plugin doesn't offer a filter to shortcircuit this check?

**Comment by cagross** [comment]
>> That plugin doesn't offer a filter to shortcircuit this check?

It doesn't appear that way :-/

**Comment by Mte90** [comment]
I think that the best way to do it is that you do a PHP snippet that detect if it is the dev environment (maybe by url) and disable the plugin by code.
In this way will not affect your database/sites on production.
We cannot change that and force this module in all the VVV instance because create caching issues that a dev environment shouldn't have.
