### ISSUE TITLE
Reprovisioning overwrites vvv-nginx.conf. What am I doing wrong?

### ISSUE THREAD

**Issue by garykupczak** [Varying-Vagrant-Vagrants/VVV#1723]
I am trying to set up a local environment for an existing WordPress site.

Following the [Adding an Existing Site](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/adding-an-existing-site/) instructions, I have provisioned a new site using the [custom site template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git) then swapped it for our WordPress install and database.

I would like to change the web root and have attempted to do so following the [Custom public_html web roots](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-public_html/) instructions. 

## Expected Behavior

Re-provisioning should reload the VM with the new nginx.conf and I should be able to see the site.

## Current Behavior

vvv-nginx.conf gets overwritten with the default version from the custom site template (pointing to public_html/build).

What am I doing wrong here?

## Context

I'm trying to get a local environment set up for an existing WordPress site. I've been struggling with VVV for 2 weeks now (of which this is just the latest difficulty). I am not very experienced with either WordPress or Vagrant, so it's very likely I'm missing something obvious/not understanding something. But this has been one of the most frustrating environment setups I've had to deal with.

## Your Environment

* VVV version: 2.5.1
* VVV Git Branch: master
* Vagrant version: 2.1.5
* VM Provider name: VirtualBox
* VM Provider version: 5.2.22 r126460
* Operating System and version: macOS 10.13.6

**Comment by tomjn** [comment]
The reason the nginx config gets overwritten is because in the custom site template it's not the input, it's the output.

`vvv-init.sh` loads the template file `vvv-nginx.conf.tmpl`, swaps out some things, and writes the result to `vvv-nginx.conf` for VVV to then do it's thing.

I'd like to change that as it's no longer necessary, but that might break VVV for people on older versions.

So modify the template instead and reprovision

**Comment by garykupczak** [comment]
`vvv-nginx.conf.tmpl` got overwritten as well.

Is it possible it's going back to the [custom site template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git) repo every time I reprovision?

**Comment by tomjn** [comment]
hmmm I'm not sure

as an aside, are you trying to put a dev build of WP in there if `public_html/build` is what you're going for? It may be necessary for you to fork the custom site template in order to get this working

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L107-L111

Based on that I would assume yes, it's reverting back to the latest version of the custom site template on each reprovision. You'd need to fork it

**Comment by garykupczak** [comment]
Moving everything to `public_html/build` did the trick for now. Will look into forking the template the next time I need to set this up. Thanks!

**Comment by tomjn** [comment]
Can you be more specific on what you did? Did you move the provision
subfolder into the build folder?

**Comment by garykupczak** [comment]
I just manually copied the WP site I was trying to replicate into the build folder.
