### ISSUE TITLE
PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test)

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#1725]
Using latest VVV

Getting error of

`PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /srv/www/wordpress-develop/public_html/tests/phpunit/includes/phpunit6-compat.php on line 18`

**Comment by Mte90** [comment]
How you are getting that? are you using a specific command?

**Comment by debabratakarfa** [comment]
running `phpunit`

**Comment by Mte90** [comment]
From what folder? Inside the machine or outside?

**Comment by debabratakarfa** [comment]
I have run
`vagrant ssh`
then cd the plugin folder and then run 
`phpunit`

**Comment by Mte90** [comment]
It is something already discussed here at https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1446 it is a problem of the phpunit version used.
