### ISSUE TITLE
Chrome 71 Is Giving Me `NET::ERR_CERT_INVALID` Error On HTTPS

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#1728]
## Expected Behavior
Be able to use HTTPS on Chrome.

## Current Behavior
The [guide](https://varyingvagrantvagrants.org/docs/en-US/references/https/) says:

  > Visit your site with `https`, and you’ll notice that the first time it loads, the browser will complain about an invalid certificate authority.

However since Chrome updated I'm unable to do that now. I just get:

`NET::ERR_CERT_INVALID`

![image](https://user-images.githubusercontent.com/1038062/52269933-59eaa200-2937-11e9-87c6-7181f2999f20.png)

## Workaround
Using Firefox still lets me add a security exception to get access to the sites.

## Steps to Reproduce (for bugs)

1. Follow the guide linked above
2. Try to visit a https site in Chrome 71 or above
3. See the error

## Your Environment

* VVV version: #f95ea20
* VVV Git Branch: develop
* Vagrant version: 2.2.1
* VM Provider name: VirtualBox
* VM Provider version:
* Operating System and version: Win 10 64-Bit

**Comment by tomjn** [comment]
Can you try adding the root certificate from the certificates folder then
restart Chrome and try again? Which version of Chrome is this in? You might
need to do a reboot of Windows

**Comment by rtpHarry** [comment]
Yeahhh boiiii!

It got me back in the game, thank you.

I am still getting an error but I can click accept now and still access the site:

![image](https://user-images.githubusercontent.com/1038062/52410951-f8126f80-2ad1-11e9-8d1c-098798584d7a.png)

**Comment by tomjn** [comment]
hmmm if you've succesfully added the root certificate as a valid certificate authority it should just work without any warnings

**Comment by tomjn** [comment]
I'm going to close this out for now, but recheck how you added the root certificate
