### ISSUE TITLE
creating a new bash script, but gives me a error on windows

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1731]
if i were to create a new bash script, im working on, that allows me do custom stuff.

everything works on MacOS and Linux since the file is created under Unix itself, now as for windows since the file is created, but running on windows fail due to
/bin/bash^M bad interpreter.  

im going to assume that i have to use dos2unix/unix2dos feature. would this be something that i have to do prior when doing an initial vagrant up as well inside of the box.

**Comment by tomjn** [comment]
hmmm I don't know why it would throw up that kind of error, this is running **inside** the VM? Not on the host?

If you're trying to run this in DOS not bash then yes, you'll have to rewrite the script entirely, there'll be no way to make the same script run in bash and DOS. Either that or you would need to use the Windows linux Subsystem, but at that point you've deviated quite far from anything VVV or standard Windows

But tbh it would be easier to just do it inside the VM

**Comment by benlumia007** [comment]
it's a definitely a strange one, but the file itself was/is created in Linux and MacoS, so im puzzle when it just gives me bad interpreter under windows. but yes, everything is running in linux and VM. 

under windows, im using the git bash, so  it's not a big deal under windows since i was testing it to see if it works, i do like to know what's goin gon tho. my main computers are now linux and macOS.

**Comment by benlumia007** [comment]
going to closed this for now, i guess i'll do it inside of the VM. thanks.
