### ISSUE TITLE
Site Template to contribute to WP-CLI

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1732]
The idea is to create a new utility to contribute to wp-cli.org.
We can use https://github.com/wp-cli/wp-cli-dev this but we need to create a new folder and execute composer inside the machine not from the machine.

**Comment by tomjn** [comment]
hmmm I wonder if a site provisioner would do the job? Granted it would have a frontend but that could be as simple as instructions and a basic nginx config ( it needn't even use PHP )

**Comment by Mte90** [comment]
I am testing that right know manually from a new folder in www.
I will let you know but probably it is the best way.

**Comment by Mte90** [comment]
With this pr it will be possible https://github.com/wp-cli/wp-cli-dev/pull/2

**Comment by Mte90** [comment]
The only difference with the readme of that project is: `composer install --no-dev` running inside VVV.
So before to do the utility or siteprovisioner we need to wait that merge.

Anyway we need only to download that project, and execute that composer command and is ready.

**Comment by Mte90** [comment]
The pull request was approved.
Do you prefer that I do a site template on my github profile and later migrate to VVV organization?

**Comment by tomjn** [comment]
>  Do you prefer that I do a site template on my github profile and later migrate to VVV organization?

This sounds good, make it so

**Comment by Mte90** [comment]
I have to test it https://github.com/Mte90/template-wp-cli-develop

**Comment by Mte90** [comment]
I can confirm that works but a test from others will be not bad at all :-)

**Comment by Mte90** [comment]
I am not usre about what is the right way to get the path but now is working :-)

**Comment by Mte90** [comment]
Convert as utility so we can use the dev version and the brand new.
With a script like for xdebug to do the switch with an alias of the version to use it.

**Comment by tomjn** [comment]
I think we should have this in the core utility, have it put it in `/srv/wp-cli-dev` and alias the binary to `wpdev` so that both `wp` and the dev version are accessible everywhere

**Comment by Mte90** [comment]
So you mean as vvv-utilities to add manually or available as default?

**Comment by tomjn** [comment]
I forget how we decided we’d do this but a utility makes sense yes

**Comment by Mte90** [comment]
Started working on it https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/35

**Comment by tomjn** [comment]
This was merged yesterday ^_^
