### ISSUE TITLE
Composer folder has root ownership

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1737]
## Expected Behavior
If the `vagrant` user is the owner is not required to use always composer as root

## Current Behavior
```
Cannot create cache directory /home/vagrant/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/vagrant/.composer/cache/files/, or directory is not writable. Proceeding without cache
```

**Comment by Mte90** [comment]
It is a blocker for https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1732
with changing the permissions to `vagrant` and executing again now the tests are working.

**Comment by benlumia007** [comment]
i think composer was setup using root a the start when you vagrant up in the first place, i think using noroot would be better for this case?

**Comment by tomjn** [comment]
indeed composer commands should be ran with `noroot`, but I'm sure there's provisions for ownership of that folder already?

**Comment by Mte90** [comment]
Good question, I changed the ownership manually and fixed it but I didn't tested if a new VVV has this problem.
Looking on a new instance this doesn't happen, probably with my testing I changed it.
So I don't know why it's happened or if we want that the provision do this kind of check to avoid problems.

**Comment by Mte90** [comment]
I am closing because the problem was me that did a mess with that machine.
