### ISSUE TITLE
This site can’t be reached 

### ISSUE THREAD

**Issue by kevindavis338** [Varying-Vagrant-Vagrants/VVV#1739]
## Expected Behavior
I have added a new site and I added the site to the windows host file. 

## Current Behavior
I'm getting a site not found in Chrome. However, I'm able to pinig the site. 

* Operating System and version: Windows 10

**Comment by benlumia007** [comment]
hello @kevindavis338 

did you install the vagrant-hostsupdater plugin, if not, you can install by using vagrant plugin install vagrant-hostsupdater and make sure that the hosts file is writable usually you can right click on the hosts file and go to properties and security and make sure that the users have full permission. 

ping the IP is always work but ping the actual name of the site may not work if the hosts file is not updated.

**Comment by kevindavis338** [comment]
No, I haven't. Let me install it and I'll get back.

**Comment by tomjn** [comment]
Installing the hostsupdater is critical, we really should scream at users who don't install it more in the provisioner and figure out why this keeps happening

**Comment by tomjn** [comment]
#1735 means hostsupdater is a requirement in the `develop` branch now
