### ISSUE TITLE
Remove vagrant plugin install vagrant-triggers from Docs

### ISSUE THREAD

**Issue by colin-marshall** [Varying-Vagrant-Vagrants/VVV#1742]
In the docs on the [Troubleshooting](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/) page under **Starting from Fresh** you haven't removed the part that tells you to run the command `vagrant plugin install vagrant-triggers` since the update to VVV 2.2 where that changed.

**Comment by tomjn** [comment]
Thanks for the heads up, all the docs are markdown files in a git repo, that doc is here:

https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/blob/master/docs/en-US/troubleshooting/index.md
