### ISSUE TITLE
Add yamllint support

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1745]
## Expected Behavior
When your vvv-custom.yml is broken and you start the provision but you get an error that block to start it

## Current Behavior
RIght now if is broken is executed anyway and provisioning can be broken and is not easy to spot because the log is huge.

## Possible Solution
Add yamllint or another solution more light that check if it is good.

**Comment by benlumia007** [comment]
https://github.com/adrienverge/yamllint

**Comment by Mte90** [comment]
Looking at https://gist.github.com/xiii/96381e41f66e5cf6a72d we can do it without another tool but using ruby itself.
I will do some tests about it

**Comment by tomjn** [comment]
In addition to parsing it would be good to do a quick check of the top level sections, flag any that are missing, and any that are present but unrecognised

**Comment by Mte90** [comment]
PR: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1923
