### ISSUE TITLE
VVV phpcs path to file?

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#1748]
On Windows 10, using the latest VVV...

```
c:\vagrant-local>vagrant ssh

vagrant@vvv:~$ phpcs c:/vagrant-local/www/wordpress-one/public_html/wp-content/plugins/hello.php
ERROR: The file "c:/vagrant-local/www/wordpress-one/public_html/wp-content/plugins/hello.php" does not exist.

vagrant@vvv:~$ phpcs /vagrant-local/www/wordpress-one/public_html/wp-content/plugins/hello.php
ERROR: The file "/vagrant-local/www/wordpress-one/public_html/wp-content/plugins/hello.php" does not exist.
```
Mr Nowel sez: 
> keep in mind, when you run vagrant ssh, you're inside the VM and the VM is an Ubuntu linux VM, There is no C drive in Linux

Ok, then what is the ssh path to this file?  `www/wordpress-one/public_html/wp-content/plugins/hello.php`

The VirtualBox Manager says that the shared folder path for the VVV box is: `\\?\C:\vagrant-local\www`

**Comment by shanebp** [comment]
Answer:  `/srv/www/wordpress-one/public_html/wp-content/plugins/hello.php`

**Comment by tomjn** [comment]
Everything under the `www` folder is mapped on to `/srv/www` and the VVV folder itself is mapped on to `/vagrant/`
