### ISSUE TITLE
virtualbox_version()

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1753]
virtualbox_version()

In the Vagrantfile, the virtualbox_version does not display in windows, it will output unknown.  we should fix this. 

```
def virtualbox_version()
    vboxmanage = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe")
    if vboxmanage != nil
        s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
        return s.stdout.strip!
    else
        return 'unknown'
    end
end
```

**Comment by tomjn** [comment]
This looks good :D have you verified this works on Windows and MacOS? Can you do a pull request?

**Comment by benlumia007** [comment]
this probably not urgent, but it should look at,  since mac/linux can call out vboxmanage anywhere,  windows must be inside of the actual virtualbox folder that controls the .exe file. 

either we ask users to manually set environment variable or something or modify the code. 

I get this working and do a pull request.

**Comment by benlumia007** [comment]
i ahve verified mac and linux works, but windows would output unknown.

**Comment by tomjn** [comment]
hmm so it only works from 1 folder before and after on windows? On some windows machine vboxmanage is in path, but not in others. I'm ok with it just being a cleaner version of what's already there

**Comment by benlumia007** [comment]
@tomjn 

So on windows, when i tested on 3 of my workstation that has windows on it, without adding the `C:\Program Files\Oaracle\Virtuabox` in path, it won't show the version of virtualbox when you vagrant up. 

so most likely, the path to the virtualbox version must be set in windows.  i think virtualbox itself should have fixed this so that it works out of the box. sigh.

**Comment by benlumia007** [comment]
we should add a note somewhere that `C:\Program Files\Oaracle\VirtualBox` that needs to be added to path. this is why i hate windows :D

**Comment by tomjn** [comment]
I wouldn't do that. This seems to be the same what we already have but
cleaner.

Vagrant itself must figure this out some how

**Comment by benlumia007** [comment]
yeah somehow, i found solutions but doesn't work too well. it takes more time to setup than it should. I'll keep figuring this out.

**Comment by benlumia007** [comment]
is there a way to run a .bat file using vagrantfile

**Comment by benlumia007** [comment]
Solution 1
Set Environment Variable for VirtualBox is the easiest way and we don't need to edit VagrantFile

Solution 2
We need to figure out how to grab VBoxManage.exe, possible solution is 
```
cd C:\Program Files\Oaracle\VirtualBox
VBoxManage --version
```

**Comment by benlumia007** [comment]
```
def virtualbox_version()
    vboxmanage = Vagrant::Util::Which.which("VBoxManage")
    if vboxmanage == nil
      if Vagrant::Util::Platform.windows? then
        return 'windows information goes here'
      else
        s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
        return s.stdout.strip!
      end
    else
        return 'unknown'
    end
end
```
is what i have, no way to change directory to `C:\Program Files\Oaracle\VirtualBox` and then `VBoxManage.exe --version`

**Comment by tomjn** [comment]
Ah this is just the same snippet from the vagrant file. I did a little digging and found where Vagrant itself does it:

https://github.com/hashicorp/vagrant/blob/85acf0cac724ef4bfda593a66e0c17f7e4110da0/plugins/providers/virtualbox/driver/base.rb#L26

It:

 - first checks if it's windows/cygwin
    - if it's on path
    - if not is the env `VBOX_INSTALL_PATH` set?
    - if not, use `SYSTEMDRIVE` or `C:` to check the program files folders and test each one
  - if it's WSL it does some additional checking
 - Else it falls back to just vboxmanage

We should be able to copy most of that code, though I would like a reference to this issue and the original code in a comment so if updates are needed we know where to find them

**Comment by benlumia007** [comment]
ahhh, funny cuz i was just looking at hashicorp's github page for this and i found the exact same thing,  i'm pretty sure that we won't be using the environment variable VBOX_INSTALL_PATH since windows usually install application on its C:\Program Files\ or C:\Program (x86) Files)  systemdrive should be c:\windows\sysem32.

do we need to check all of it, or just grab the c:\

**Comment by tomjn** [comment]
@benlumia007 I've tried to fix this, I don't have a Windows machine handy just right now to confirm that though

**Comment by benlumia007** [comment]
@tomjn 
I just tested, after I removed the environment variable and restarted, It seems it's grabbing the correct information when I use your pull request that you created? :D

**Comment by tomjn** [comment]
in that case can you approve the PR, I'll merge

**Comment by benlumia007** [comment]
@tomjn 
I think we need to adjust this because, if i go back to the original
```
def virtualbox_version()
    vboxmanage = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe")
    if vboxmanage != nil
        s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
        return s.stdout.strip!
    else
        return 'unknown'
    end
end
```
and when I vagrant up on hyperv , it does not give me an error about the path for VBoxManage.

**Comment by benlumia007** [comment]
```
def virtualbox_path()
    @vboxmanage_path = nil
    if Vagrant::Util::Platform.windows? || Vagrant::Util::Platform.cygwin?
        @vboxmanage_path = Vagrant::Util::Which.which("VBoxManage")

        # On Windows, we use the VBOX_INSTALL_PATH environmental
        # variable to find VBoxManage.
        if !@vboxmanage_path && (ENV.key?("VBOX_INSTALL_PATH") ||
          ENV.key?("VBOX_MSI_INSTALL_PATH"))

          # Get the path.
          path = ENV["VBOX_INSTALL_PATH"] || ENV["VBOX_MSI_INSTALL_PATH"]

          # There can actually be multiple paths in here, so we need to
          # split by the separator ";" and see which is a good one.
          path.split(";").each do |single|
            # Make sure it ends with a \
            single += "\\" if !single.end_with?("\\")

            # If the executable exists, then set it as the main path
            # and break out
            vboxmanage = "#{single}VBoxManage.exe"
            if File.file?(vboxmanage)
              @vboxmanage_path = Vagrant::Util::Platform.cygwin_windows_path(vboxmanage)
              break
            end
          end
        end

        # If we still don't have one, try to find it using common locations
        drive = ENV["SYSTEMDRIVE"] || "C:"
        [
          "#{drive}/Program Files/Oracle/VirtualBox",
          "#{drive}/Program Files (x86)/Oracle/VirtualBox",
          "#{ENV["PROGRAMFILES"]}/Oracle/VirtualBox"
        ].each do |maybe|
          path = File.join(maybe, "VBoxManage.exe")
          if File.file?(path)
            @vboxmanage_path = path
            break
          end
        end
        elsif Vagrant::Util::Platform.wsl?
        if !Vagrant::Util::Platform.wsl_windows_access?
          raise Vagrant::Errors::WSLVirtualBoxWindowsAccessError
        end
        @vboxmanage_path = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe")
        if !@vboxmanage_path
          # If we still don't have one, try to find it using common locations
          drive = "/mnt/c"
          [
            "#{drive}/Program Files/Oracle/VirtualBox",
            "#{drive}/Program Files (x86)/Oracle/VirtualBox"
          ].each do |maybe|
            path = File.join(maybe, "VBoxManage.exe")
            if File.file?(path)
              @vboxmanage_path = path
              break
            end
          end
        end
    end

    # Fall back to hoping for the PATH to work out
    @vboxmanage_path ||= "VBoxManage"
    return @vboxmanage_path
end

def virtualbox_version()
    vboxmanage = virtualbox_path()
    s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
    return s.stdout.strip!
end
```
