### ISSUE TITLE
Typo in latest blog post - v2.5 / v2.4

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#1759]
In the latest blog post the headings are wrong.

Had a quick look but not sure where it is to do a PR so I'm just giving a quick heads up.

Both headings say "changes in v2.5" but the first one is for v2.4 changes.

https://varyingvagrantvagrants.org/blog/2019/03/31/vvv-2-4-0-2-5-0.html

![image](https://user-images.githubusercontent.com/1038062/55388237-7edd4900-5565-11e9-9744-56c15c1ce385.png)

**Comment by tomjn** [comment]
fixed! thanks for the headsup
