### ISSUE TITLE
Vagrant 1.3.4 Hosts

### ISSUE THREAD

**Issue by rickalee** [Varying-Vagrant-Vagrants/VVV#176]
Went thru the steps in ReadMe with great detail and even manually added to hosts file via sudo nano but no luck. No error when running vagrant up. Is anyone else having issues? local.wordpress.dev & etc simply don't come up.

**Comment by tnguyen14** [comment]
I am running into a similar issue to this - I downloaded VVV today, am running Vagrant 1.7.2 and VirtualBox 4.3.20. The provisioning step goes over fine, with these lines output at the end:

```
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 769 seconds
```

However, going to any of those urls return nothing. Pinging them shows that they're down. The only thing I can do is going to http://192.168.50.4/, which is available, but doesn't allow me to do any development whatsoever.

Am I missing something here?

**Comment by tnguyen14** [comment]
Turns out that after I installed Vagrant Hosts Updater plugin (https://github.com/varying-vagrant-vagrants/vvv/wiki/Auto-site-Setup#the-domains-for-your-site), I was able to access these hosts. Makes sense, but I wonder if this should be documented somewhere? Or perhaps it is and I just missed it.
