### ISSUE TITLE
Other improvements to Tideways utility

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1761]
After chatting a bit and promoting we have new ideas:

* Create documentation for VVV about Tideways and XHGui - https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/123
* Enable Tideways by pressing the button from the VVV Dashboard
* Enable Tideways by site on provision from `vvv-config`

**Comment by Mte90** [comment]
I was thinking that we can do that generate a file like `tideways` in `/srv/` that contain the various domain.
The provision will generate the content like also pressing the button in the dashboard.
In that way we can save that values and use the same data also for few things.

**Comment by tomjn** [comment]
A json file controlling which domains have it enabled that can be modified by PHP sounds good

**Comment by Mte90** [comment]
Ok we need to support also that :-D
https://github.com/perftools/xhgui/pull/265

**Comment by Mte90** [comment]
Started https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/25

**Comment by tomjn** [comment]
Closing now that the PR is merged
