### ISSUE TITLE
Run vagrant box update still showing to upgrate

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#1768]
I have run `vagrant box update` and then I run `vagrant reload --provision` but still display to update vagrant box.

## Context
<img width="874" alt="Screenshot 2019-04-29 at 6 48 00 PM" src="https://user-images.githubusercontent.com/2614495/56899104-41120880-6ab0-11e9-8993-af135e15984f.png">
<img width="887" alt="Screenshot 2019-04-29 at 6 48 12 PM" src="https://user-images.githubusercontent.com/2614495/56899113-4707e980-6ab0-11e9-91cf-9c40e397e812.png">

## Your Environment
* VVV version: 2.6.0
* VVV Git Branch: master
* Vagrant version: Vagrant 2.2.4
* VM Provider name: Virtual Box
* VM Provider version: 5.2.20r125813
* Operating System and version: MacOs and 10.14.2

**Comment by tomjn** [comment]
As the notice says, you have to destroy and recreate the machine to update
your VM with the new box. You only reprovisioned an existing VM,
reprovisions don't destroy and recreate

Either way I wouldn't worry and just keep using your current box. For the
moment we don't rely on box updates for VVV itself and we run our own
package update process

**Comment by debabratakarfa** [comment]
I run `vagrant box prune` and then now I am running `vagrant reload --provision` 
Let see what happen now

**Comment by tomjn** [comment]
Reload turns it off and on, to change your box you must run vagrant destroy
and delete your VM. Boxes are just starting points.

My advice is to ignore the Vagrant message about box updating, VVV just
uses a generic Ubuntu base box, we run our own apt updates

**Comment by debabratakarfa** [comment]
Thanks @tomjn :)

**Comment by benlumia007** [comment]
@debabratakarfa 
just wanted to follow up, did you end up getting your environment working :D

**Comment by tomjn** [comment]
I'm going to close this out, if there's any questions feel free to update the issue
