### ISSUE TITLE
Remove /vagrant mount

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1777]
By default Vagrant mounts the folder with the vagrant file on to `/vagrant` inside the guest VM. This is bad as we get overlapping shared folders, which causes problems.

We need to break this dependency and eliminate this shared folder, Number 1 priority

**Comment by sbrody** [comment]
Have tried to destroy and reprovision and am getting this when in master branch:
 
`default: E
    default: : 
    default: Unable to locate package php7.2-fpm
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-fpm'
    default: E
    default: : 
    default: Unable to locate package php7.2-cli
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-cli'
    default: E
    default: : 
    default: Unable to locate package php7.2-common
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-common'
    default: E
    default: : 
    default: Unable to locate package php7.2-dev
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-dev'
    default: E
    default: : 
    default: Unable to locate package php-imagick
    default: E
    default: : 
    default: Unable to locate package php-memcache
    default: E
    default: : 
    default: Unable to locate package php-memcached
    default: E
    default: : 
    default: Unable to locate package php-ssh2
    default: E
    default: : 
    default: Unable to locate package php-xdebug
    default: E
    default: : 
    default: Unable to locate package php7.2-bcmath
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-bcmath'
    default: E
    default: : 
    default: Unable to locate package php7.2-curl
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-curl'
    default: E
    default: : 
    default: Unable to locate package php7.2-gd
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-gd'
    default: E
    default: : 
    default: Unable to locate package php7.2-mbstring
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-mbstring'
    default: E
    default: : 
    default: Unable to locate package php7.2-mysql
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-mysql'
    default: E
    default: : 
    default: Unable to locate package php7.2-imap
    default: E
    default: : 
    default: Couldn't find any package by regex 'php7.2-imap'
    default: 
    default: E: Unable to locate package php7.2-json
    default: E: Couldn't find any package by regex 'php7.2-json'
    default: E: Unable to locate package php7.2-soap
    default: E: Couldn't find any package by regex 'php7.2-soap'
    default: E: Unable to locate package php7.2-xml
    default: E: Couldn't find any package by regex 'php7.2-xml'
    default: E: Unable to locate package php7.2-zip
    default: E: Couldn't find any package by regex 'php7.2-zip'
    default: Main packages check and install failed, halting provision
`
in develop branch I get a MariaDB error:

`default: ● mariadb.service - MariaDB 10.3.14 database server
    default:    Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
    default:   Drop-In: /etc/systemd/system/mariadb.service.d
    default:            └─migrated-from-my.cnf-settings.conf
    default:    Active: failed (Result: exit-code) since Wed 2019-05-08 15:10:18 UTC; 8ms ago
    default:      Docs: man:mysqld(8)
    default:            https://mariadb.com/kb/en/library/systemd/
    default:   Process: 6388 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
    default:   Process: 6237 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
    default:   Process: 6231 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
    default:   Process: 6210 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysq
`

**Comment by tomjn** [comment]
Does all work after a backup/destroy/update/reprovision?

---

I believe #1784 is ready for merge, just needs confirmation from another person

**Comment by tomjn** [comment]
GitHub is messing up the order of comments, just to clarify, there is no way to get `master` working until VVV 3 is released, you will need to switch to the `develop` branch

**Comment by sbrody** [comment]
As I mentioned above, I'm getting the MariaDB error when I destroy and reprovision in develop
