### ISSUE TITLE
provision sometimes fails because nginx is being restarted too rapidly

### ISSUE THREAD

**Issue by DrewAPicture** [Varying-Vagrant-Vagrants/VVV#1780]
## Expected Behavior
While provisioning on latest `develop` (3.0.0 at the time of writing) I expected with the new box/mariadb fixes that provisioning would complete without issue.

## Current Behavior
Everything was going great until the site provisioning step, where the script seemed to briefly proceed through provisioning the sites as expected but then just died after four or five sites have been provisioned.

Eventually it hangs and kills the script with:
```sh
default: nginx.service failed
default: See "systemctl status nginx.service" and "journalctl -xe" for details.
```

I retried provisioning several times, even commenting out sites in vvv-custom to see if a specific site was the culprit (there was no consistency).

## Possible Solution
After examining the syslog, it seems that the nginx service is being restarted _too quickly_. That led me to read up about `StartLimitIntervalSec` and `StartLimitBurst` and deciding whether to try to mess with them to prevent the throttling or do something else.

Ultimately, I decided to do something else: I just slapped a 3 second timeout before the `service nginx restart` at the end of provision-site.sh:
```sh
echo " * Restarting nginx"
sleep 3s
service nginx restart
```
And that delayed the restarts just enough where it wouldn't trigger the 5 restarts in 10s rule.

## Steps to Reproduce (for bugs)
I guess have a performant system with a lot of sites to provision? Not sure if there's a better way to overload the system than trying to provision a whole bunch of stuff as quickly as possible.

## Context
In terms of context, I can't really use vvv if it can't provision all the way? :-)

But with the timeout in place, I was able to fully provision nbd.

## Your Environment
* VVV version: 3.0.0
* VVV Git Branch: `develop`
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 5.2.28 r130011
* Operating System and version: MacOS 10.14.3

**Comment by tomjn** [comment]
Good to know, how do we use `StartLimitIntervalSec` though? Can you make the change you made via a PR?

**Comment by DrewAPicture** [comment]
I didn't mess with the `StartLimitIntervalSec` stuff, that's a bit out of my depth. I can put the `sleep 3s` I added in a PR if you want, but that seemed like kind of avoiding the problem 😉

**Comment by DrewAPicture** [comment]
Let me see what I can find out.

**Comment by DrewAPicture** [comment]
PR: #1781 uses reload instead of restart during site provisioning, which is not subject to the same burst limits.

**Comment by Lisa-Williams** [comment]
@DrewAPicture You might want to edit your ```#1781``` as it is linking to an issue right now.

**Comment by tomjn** [comment]
I've edited it to the PR URL, it's also been merged :)
