### ISSUE TITLE
File '/var/log/tallylog' has wrong world permissions due to vboxfs's 'fmode=0666' mount option

### ISSUE THREAD

**Issue by Lisa-Williams** [Varying-Vagrant-Vagrants/VVV#1781]
## Expected Behavior

During provisioning file ```/var/log/tallylog``` should have ```rw-rw-r--``` permissions.

This can be avoided by not using Guest Additions file sharing. This type of sharing was only meant for file exchange/transfer between the guest and the host. Its ```fmode``` and ```dmode``` are not OK where mixed/**variant** file and directory permissions are required. I have no alternative. Maybe share in fstab, or with nfs?

## Current Behavior

File ```/var/log/tallylog``` has wrong ```world``` permissions, causing a ```pam_tally2``` authentication error while resetting the tallylog of user ```mysql```.

Relevant part of provisioning during the very first ```vagrant up```:
```
==> default: Running provisioner: default (shell)...
    default: Running: /tmp/vagrant-shell20190507-13224-1imapey.sh
    default: Succesful Network connection to ppa.launchpad.net detected...
    default: Bash profile setup and directories.
    default:  * Copying /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default:  * Copying /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default:  * Copying /srv/config/vimrc                             to /home/vagrant/.vimrc
    default:  * Copying /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default:  * Copying /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default: Succesful Network connection to ppa.launchpad.net detected...
    default:  
    default: Main packages check and install.
    default: Adding ppa:git-core/ppa repository
    default: 
    default: Setup MySQL configuration file links...
    default: pam_tally2: /var/log/tallylog is either world writable or not a normal file
    default: pam_tally2: Authentication error
    default: useradd: failed to reset the tallylog entry of user "mysql"
    default:  * Copying /srv/config/mysql-config/vvv-core.cnf to /etc/mysql/conf.d/vvv-core.cnf
    default: Linked custom apt sources
    default: Applying NodeSource NodeJS signing key...
    default: OK
```
The file permissions are:
```
vagrant@vvv:~$ ls -hal /var/log/tallylog
-rw-rw-rw- 1 root syslog 0 May  7 17:48 /var/log/tallylog
```
And they refuse to change:
```
vagrant@vvv:~$ sudo chmod -v 664 /var/log/tallylog
mode of '/var/log/tallylog' changed from 0666 (rw-rw-rw-) to 0664 (rw-rw-r--)
vagrant@vvv:~$ ls -hal /var/log/tallylog
-rw-rw-rw- 1 root syslog 0 May  7 17:48 /var/log/tallylog
```
This is caused by the VirtualBox Guest Additions's ```fmode=0666``` file sharing option. ```fmode``` is immutable, which is fine for file exchange, but not for any other usage.:
```
vagrant@vvv:~$ sudo mount
..........>>> shortened
.
var_log on /var/log type vboxsf (rw,nodev,relatime,iocharset=utf8,uid=0,gid=106,dmode=0777,fmode=0666)
.
..........>>> shortened

```

## Possible Solution

I wouldn't know how to fix this. Like I mentioned earlier, stop using Virtualbox guest additions file sharing, and maybe share files and directories with nfs or a similar method.

## Steps to Reproduce (for bugs)

1. Clone the repo with the ```develop``` branch as current:
```
git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git ~/your_folder_path_here
cd !$
```
2. ```vagrant up```
3. After provisioning scroll back in your terminal and look for the following lines in red text. My ```~/.bash_history``` file has no limit set. If yours hasn't, you might not be able to scroll back far enough.
```
    default: Setup MySQL configuration file links...
    default: pam_tally2: /var/log/tallylog is either world writable or not a normal file
    default: pam_tally2: Authentication error
    default: useradd: failed to reset the tallylog entry of user "mysql"
```

## Context

First ever attempt to use VVV.

## Your Environment

* VVV version: v3.0.0-git::develop
* VVV Git Branch: develop
* Vagrant version: v2.2.4
* VM Provider name: VirtualBox
* VM Provider version: Oracle VM VirtualBox VM Selector v6.0.6
* Operating System and version: ```Linux bumblebee 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 12:05:41 EST 2019 x86_64 GNU/Linux```

**Comment by tomjn** [comment]
This shouldn't prevent VVV from provisioning, it's just noise in the provisioner log ( nice to remove noise albeit ).

Did your attempt to provision fail? Can you visit `vvv.test` and the built in copies of WP? Or do they fail? If they fail, can I see a full copy of you terminal output for the provision?

**Comment by Lisa-Williams** [comment]
No it didn't fail. I can visit ```vvv.test``` fine.
It's just that the pam_tally2 module is used to lock user accounts after certain number of failed ssh login attempts made. It keeps the count of attempted accesses and too many failed attempts. Not relevant during development.

**Comment by tomjn** [comment]
I did manage to get this working during my testing by changing the permissions set on that folder, it's changed since then so a different fmode/dmode can eliminate that message

**Comment by Lisa-Williams** [comment]
You are right, but that file mode would have to end with ``r--``. For example ```rw-rw-r--``` / ```664``` or even ```rw-r--r--` / ```644```. But that might open up a whole other can of worms with other logs/files in ```/var/log```. Now it seems to be just one file.

**Comment by tomjn** [comment]
This isn't an issue now that the `/var/log` folder isn't a shared folder, we only mount subdirectories now
