### ISSUE TITLE
Vagrant provision

### ISSUE THREAD

**Issue by gecanben** [Varying-Vagrant-Vagrants/VVV#1790]
## Current Behavior

Running vagrant up ends with following error:

    default: Reading package lists...
    default: Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E
    default: :
    default: Unable to locate package php7.2-fpm
    default: E
    default: :
    default: Couldn't find any package by regex 'php7.2-fpm'
    default: E
    default: :
    default: Unable to locate package php7.2-cli
    default: E
    default: :
    default: Couldn't find any package by regex 'php7.2-cli'
    default: E
    default: :
    default: Unable to locate package php7.2-common
    default: E
    default: :
    default: Couldn't find any package by regex 'php7.2-common'
    default: E
    default: :
    default: Unable to locate package php7.2-dev
    default: E
    default: :
    default: Couldn't find any package by regex 'php7.2-dev'
    default: E: Unable to locate package php-imagick
    default: E: Unable to locate package php-memcache
    default: E: Unable to locate package php-memcached
    default: E: Unable to locate package php-ssh2
    default: E: Unable to locate package php-xdebug
    default: E: Unable to locate package php7.2-bcmath
    default: E: Couldn't find any package by regex 'php7.2-bcmath'
    default: E: Unable to locate package php7.2-curl
    default: E: Couldn't find any package by regex 'php7.2-curl'
    default: E: Unable to locate package php7.2-gd
    default: E: Couldn't find any package by regex 'php7.2-gd'
    default: E: Unable to locate package php7.2-mbstring
    default: E: Couldn't find any package by regex 'php7.2-mbstring'
    default: E: Unable to locate package php7.2-mysql
    default: E: Couldn't find any package by regex 'php7.2-mysql'
    default: E: Unable to locate package php7.2-imap
    default: E: Couldn't find any package by regex 'php7.2-imap'
    default: E: Unable to locate package php7.2-json
    default: E: Couldn't find any package by regex 'php7.2-json'
    default: E: Unable to locate package php7.2-soap
    default: E: Couldn't find any package by regex 'php7.2-soap'
    default: E: Unable to locate package php7.2-xml
    default: E: Couldn't find any package by regex 'php7.2-xml'
    default: E: Unable to locate package php7.2-zip
    default: E: Couldn't find any package by regex 'php7.2-zip'
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
## Steps to Reproduce (for bugs)

1. Installed vvv through git.
2. Ran vagrant up
3.
4.

## Context

Tried in different directories with same result. Uninstalled and reinstalled Vagrant and Virtualbox with same result.

## Your Environment

* VVV version: 2.6.0
* VVV Git Branch: master
* Vagrant version: 2.2.4
* VM Provider name: Virtualbox
* VM Provider version: 6.0.6r130049
* Operating System and version: Windows 7 SP1
platform-mingw32 windows HasWinAdminPriv vagrant-hostsupdater

**Comment by tomjn** [comment]
The master branch does not work at the moment and there is no easy fix or
work around.

Instead, backup your database, switch to the develop branch and do a
vagrant destroy followed by a provision

**Comment by tsunamilx** [comment]
I am having this issue too, do you mind tell why is this happening? 

I was using vvv 2.1.0 and the provision was working, until today I updated vvv and provisioned, then this issue happened, and when I trying to get back to 2.1.0, and the error changed to "unable to locate php7.0-fpm", going crazy...

It doesn't look like a bug in your vagrant file, but more like something goes wrong in the apt repository.

**Comment by tomjn** [comment]
VVV 2.x uses an Ubuntu 14 box, and Ondrej PHP packages which was fine for a long time.

Last week, Ubuntu 14 reached end of support, and Ondrej deleted all the PHP packages for Ubuntu 14, he only keeps packages for supported versions. That's why the provisioner can't find them and fails.

We thought we'd mirrored all the packages to a VVV apt repo, but it turns out we're missing a handful of important ones which no longer exist 😢.

We're in the process of ironing out the kinks in VVV 3 on the `develop` branch, which uses an Ubuntu 18 LTS box, that should keep us covered until 2024. It's a big change so I don't want to merge it just yet, but I'm expecting to do so within the next day or two

To switch to VVV3, backup your database if you haven't already ( VVV does this for you when you run `vagrant halt` ), switch to the `develop` branch, and destroy+reprovision.

**Comment by tsunamilx** [comment]
Ah sad, thanks a lot and really appreciate your work, it's great work.

**Comment by gecanben** [comment]
Thank you very much.
