### ISSUE TITLE
Can't perform `db_backup`

### ISSUE THREAD

**Issue by benedicksahagun** [Varying-Vagrant-Vagrants/VVV#1791]
## Expected Behavior

Perform database backup.

## Current Behavior

`db_backup` command permission denied.

## Possible Solution

Fixing broken permissions maybe? (not sure which files to modify)

## Steps to Reproduce (for bugs)

1. vagrant ssh -c "db_backup"

https://gist.github.com/benedicksahagun/d3e1c19089df6cc137b446752192dfa4

## Context

Not able to backup my databases.

## Your Environment

* VVV version:  3.0.0 
* VVV Git Branch: develop 
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 5.2.28r13011
* Operating System and version: macOS Mojave 10.14.4

**Comment by tomjn** [comment]
Is this before or after a `vagrant destroy`? If you're backing up your database prior to updating to v3, you'd want to do it before doing `git pull`. Right now any previous database files you had would be innaccessible, it would use the `database/data` folder instead.

**Comment by benedicksahagun** [comment]
Looks like I'm doing something wrong trying to get my old sites prior v3. I decided to destroy to box and run provision again, now everything works fine. Thanks!

**Comment by tomjn** [comment]
Glad you got it working, I've updated one of the PRs with much better instructions on what to do if you try to provision with VVV 3 but using an Ubuntu 14 VM
