### ISSUE TITLE
VVV3 - Win10, VirtualBox 6, Vagrant 2.2.4

### ISSUE THREAD

**Issue by qbattersby** [Varying-Vagrant-Vagrants/VVV#1796]
Trying the develop branch, master didnt work. Alas, everything comes up fine but this appears to be a permissions problem with the MySQL datadir. 

## Expected Behavior
Databases should migrate properly using WP-Migrate-DB Pro or WP-Sync-DB.

## Current Behavior
Fails renaming tables, for example: 
WordPress database error: [Error on rename of './axonify/_mig_wp_alm' to './axonify/wp_alm' (errno: 168 "Unknown (generic) error from engine")]
RENAME TABLE `_mig_wp_alm` TO `wp_alm`

** Have also tried via ssh and mysql from cli.

## Possible Solution
Permissions of datadir?

## Steps to Reproduce (for bugs)
1. Try to pull a WP db from a site using WP-Sync-DB or WP-Migrate-DB Pro.

## Your Environment
* VVV version: Current Develop Branch release.
* VVV Git Branch: Develop
* Vagrant version: 2.2.4
* VM Provider name: Virtualbox
* VM Provider version: 6.0.6
* Operating System and version: Win10 1903

**Comment by tomjn** [comment]
You can't `chmod` a virtualbox share, the permissions are set by VirtualBox itself via the `fmode` and `dmode` parameters passed from the vagrantfile, and can't be changed from the guest VM.

As an aside, can you confirm that Hyper-V is turned off? As well as anything else that could turn on the windows hypervisor such as the linux subsystem or virtual machine services? VBox v6 will attempt to use HyperV if it's on without warning, but it's very slow and quite unreliable. 5.2 will outright tell you and abort in those scenarios

Finally, I'm unfamiliar with those plugins, and as they're premium plugins I'm unable to reproduce the problem. Can you replicate this using raw SQL?

**Comment by qbattersby** [comment]
Thanks for the quick reply. 

No HyperV is disabled entirely as I originally wanted to use HyperV due to using it on another machine but couldn't get it to successfully vagrant up. So I totally disabled the feature. 

I am using WSL on the machine but I am bringing vagrant up from elevated (admin) PowerShell.

As for raw SQL, just running this produces the same error:

RENAME TABLE _mig_wp_commentmeta TO wp_commentmeta;

**Comment by qbattersby** [comment]
Also I have tried earlier versions of MariaDB same result. I don't believe it is Foreign Key lock as some googling suggests.

It is super frustrating and would love a solution.

**Comment by tomjn** [comment]
> I am using WSL on the machine but I am bringing vagrant up from elevated (admin) PowerShell.

If you're using WSL then you have some form of Hyper-V turned on via indirect means. Turning on HyperV isn't the only way to activate the Windows hypervisor

**Comment by tomjn** [comment]
I tried to test this by renaming the `wp_links` table to `wp_links2` using the `root` user in PHPMyAdmin, and was unable to replicate, the table was succesfully renamed

**Comment by tomjn** [comment]
Also, can you clear your mysql logs just before doing that, then run the query? If it still fails I'd like to see the contents

**Comment by qbattersby** [comment]
Ok here is the log - I did the same thing from PHPMyAdmin

`2019-05-12 19:16:02 139799349282816 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: The InnoDB memory heap is disabled
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Compressed tables use zlib 1.2.11
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Using SSE crc32 instructions
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Completed initialization of buffer pool
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Highest supported file format is Barracuda.
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: 128 rollback segment(s) are active.
2019-05-12 19:16:02 139799349282816 [Note] InnoDB: Waiting for purge to start
2019-05-12 19:16:02 139799349282816 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.43-84.3 started; log sequence number 3834700
2019-05-12 19:16:02 139799349282816 [Note] Plugin 'FEEDBACK' is disabled.
2019-05-12 19:16:02 139798467573504 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-05-12 19:16:02 139799349282816 [Note] Server socket created on IP: '0.0.0.0'.
2019-05-12 19:16:02 139799349282816 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.40-MariaDB-1~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2019-05-12 19:17:02 7f25927fa700  InnoDB: Operating system error number 26 in a file operation.
InnoDB: Error number 26 means 'Text file busy'.
InnoDB: Some operating system error numbers are described at
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/operating-system-error-codes.html
2019-05-12 19:17:02 139799348356864 [ERROR] InnoDB: Cannot rename file './wordpressone/wp_comments.ibd' to './wordpressone/wp_comments2.ibd'
`

**Comment by qbattersby** [comment]
I raised file limit, still no go:

ulimit -n
1024000

**Comment by qbattersby** [comment]
Yea both those plugins didnt make a difference.

**Comment by tomjn** [comment]
they wouldn't, the bindfs plugin is a MacOS thing that requires FUSE be setup, and winnfsd wouldn't make a difference unless you modified the vagrant file to use NFS and then enabled NFS on your system.

Instead I believe permissions is a red herring. It never said it wasn't allowed to rename the file, just that it's busy. Do you have antivirus running that could be locking the file?

**Comment by tomjn** [comment]
I think you're most likely to get traction by playing with the ` innodb_flush_method` config option, some docker users imply that `O_DSYNC` may be a useful value for this, docs here:

https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_flush_method

How big exactly is the database you're trying to pull down and how many tables? It sounds like the way your database sync is working is the equivalent of eating too quickly and getting the hiccups for the database given its current configuration

**Comment by qbattersby** [comment]
In all those tests above - aside from initially I was just changing the default WordPress One install table - so no big data base etc - just the default WP table

**Comment by qbattersby** [comment]
Any other suggestions? I have been using VVV for many years and would hate for this to be thing that prevents me from continuing with it

**Comment by tomjn** [comment]
> In all those tests above - aside from initially I was just changing the default WordPress One install table - so no big data base etc - just the default WP table

What about the other side of the synchronisation? Did you try different values for `innodb_flush_method` in the mysql config?

**Comment by qbattersby** [comment]
I am open to trying whatever approach makes it work and I am open to suggestion. Strange thing is I got it working in Win10 before with Hyper-V, Vagrant version I would have to check and a version of VVV that I brought over from the other machine but it didnt work.  

Alas - not sure what to do - what would you recommend? 

I ran this script and Hyper-V is disabled. 

$hyperv = Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
# Check if Hyper-V is enabled
if($hyperv.State -eq "Enabled") {
    Write-Host "Hyper-V is enabled."
} else {
    Write-Host "Hyper-V is disabled."
}

**Comment by qbattersby** [comment]
Should I remove Vagrant and Virtualbox and install Virtualbox 5.2?

**Comment by tomjn** [comment]
That will say it's disabled even if a hyper visor is present but active for reasons other than the Hyper-V product. WSL uses a virtual machine so enabling it turns on a hypervisor. It's basically checking if the checkbox is checked but in code.

I don't believe it's possible to use the WSL without turning on some portion of Hyper-V. For example you can check the virtual machine platform feature but leave Hyper-V unchecked, and that activates the hyper visor. The main difference is that the Hyper-V product and APIs wouldn't be available unless the checkbox is checked. It might look like you don't have a hypervisor because Hyper-V is unchecked, but that's not true.

If you downgrade to VirtualBox 5.2 my expectation would be that you won't be able to create VirtualBox VMs, and that it would likely give either a Hyper-V, or a VT-x related error

Otherwise it's possible your previous experiences where with hyper-v boxes, or that VirtualBox may or may not have worked, I can only speculate

> Should I remove Vagrant and Virtualbox and install Virtualbox 5.2?

Give it a go, but there's no reason you would uninstall Vagrant, just VirtualBox

> I am open to trying whatever approach makes it work and I am open to suggestion. 

Did you try the innodb mysql config option from earlier? Also, you never answered my question about what you were trying to sync, just that the destination of the sync was the default site, it isn't clear what the data source being migrated was. Also, does a conventional migration work? The innodb option is the omgbbq priority 1 level part

**Comment by tomjn** [comment]
Re: hyper-v being silently enabled in the background by other windows features: https://github.com/Microsoft/WSL/issues/2850

**Comment by qbattersby** [comment]
> That will say it's disabled even if a hyper visor is present but active for reasons other than the Hyper-V product. WSL uses a virtual machine so enabling it turns on a hypervisor. It's basically checking if the checkbox is checked but in code.
> 
> I don't believe it's possible to use the WSL without turning on some portion of Hyper-V. For example you can check the virtual machine platform feature but leave Hyper-V unchecked, and that activates the hyper visor. The main difference is that the Hyper-V product and APIs wouldn't be available unless the checkbox is checked. It might look like you don't have a hypervisor because Hyper-V is unchecked, but that's not true.

Interesting...

> 
> If you downgrade to VirtualBox 5.2 my expectation would be that you won't be able to create VirtualBox VMs, and that it would likely give either a Hyper-V, or a VT-x related error
> 
> Otherwise it's possible your previous experiences where with hyper-v boxes, or that VirtualBox may or may not have worked, I can only speculate
> 
> > Should I remove Vagrant and Virtualbox and install Virtualbox 5.2?
> 
> Give it a go, but there's no reason you would uninstall Vagrant, just VirtualBox
> 
> > I am open to trying whatever approach makes it work and I am open to suggestion.
> 
> Did you try the innodb mysql config option from earlier? Also, you never answered my question about what you were trying to sync, just that the destination of the sync was the default site, it isn't clear what the data source being migrated was. Also, does a conventional migration work? The innodb option is the omgbbq priority 1 level part

I tried all the available options, of course restarting mysql each time - no change.

As for the migration, originally on another box which I destroyed since I was importing a large site yes but in all the testing we were doing above, I merely was opening the default Wordpress DB included in VVV in PHPMyAdmin and attempting to rename the wp_comments table to do our testing, same problem everytime on the tiny nearly empty table (whatever is there by default).

What I am saying is it is not related to the migration but rather just renaming any table in the database. Surely others will run into this problem as well if they ever attempt to pull a database from a live environment for example. So for me it makes VVV basically un-usable from a productivity standpoint. I dont want to have to dump my local database and than import a 100MB database and search and replace the whole thing every time I need to pull down live changes. 

Beyond that though just being able to rename a table in the DB is certainly important. I can DROP the table fine so not sure what is up with that but I am pretty stuck on the thought it relates to the datadir.

I am open to any suggestion really.

**Comment by tomjn** [comment]
I don't have any at the moment other than testing virtual box 5.2, I wasn't
able to reproduce the issue locally

**Comment by qbattersby** [comment]
Hmm too bad - I wonder what experience others who use this project are having on Win 10 with current versions of everything. Sadly I couldnt put any more time into resolving it (I didnt roll back to Virtualbox 5.2) and I moved onto another solution for local dev environment. If this ever gets sorted would be great to hear what the solution was.

Thanks for all your help in the meantime anyhow and consider me thankful for VVV as a long time user.

**Comment by rene-hermenau** [comment]
Same issue as this one: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1849
