### ISSUE TITLE
"Xhgui hit an error" on xhgui.vvv.test

### ISSUE THREAD

**Issue by janw-me** [Varying-Vagrant-Vagrants/VVV#1815]
I've upgraded to vvv3.0.0
I destroyed the box and after an `up --provision` I saw new shiny tool I wanted to check it out.

From the first view I got an error

Full error & screenshot: https://gist.github.com/janw-me/3f056d3d992c0cf4a48443b97ebf1ace

I did see it mentioned in the [release blog](https://varyingvagrantvagrants.org/blog/)
Nothing on the [utilities page](https://varyingvagrantvagrants.org/docs/en-US/utilities/)

If there is any more info I can provide let me know.

`vvv-custom.yml` utilities part:

```
# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - phpmyadmin # Web based database client
    - webgrind # PHP Debugging
    - trusted-hosts # GitHub etc
    - tls-ca # SSL/TLS certificates
    - mongodb # needed for Tideways/XHGui
    - tideways # PHP profiling tool, also installs xhgui
    #- php56
    #- php70
    #- php71
    - php72
    - php73
```

## Your Environment
* VVV version: 3.0.0
* VVV Git Branch: tag 3.0.0
* Vagrant version: 2.2.4
* VM Provider name: Virtual box 6.0.6
* Operating System and version: Ubuntu 19.04

Upgraded using: `vagrant halt && vagrant destroy && git fetch --tags && git checkout 3.0.0 && vagrant up --provion`

**Comment by Mte90** [comment]
Seems that mongo has some problems.
Did you tried `vagrant provision` because we updated few days ago for a problem with mongo.
You did the procedure to upgrade right, but I see in the command `vagrant up --provion` and `vagrant up --provision` so I am not sure if you provisioned.

PS: thanks for spotting the missing stuff in that page we will update it.

**Comment by janw-me** [comment]
I (re)create the box (and) upgraded about an hour before I created this ticket.

The `--provion` is just a type in the ticktet. It is correct in my bash histrory

**Comment by Mte90** [comment]
I am getting the same problem on my instance.
this https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/28 should fix the issue when will be approved and merged

**Comment by tomjn** [comment]
fix merged, @janw-me can you confirm all is good?

**Comment by janw-me** [comment]
Yes the error is gone on master branch
