### ISSUE TITLE
Backup databases to local folder and Google Drive (local)

### ISSUE THREAD

**Issue by alexanderscottgraham** [Varying-Vagrant-Vagrants/VVV#1816]
## Expected Behavior
Would love to save databases via cron job every half hour, both to `/database/backups` and a local Google Drive `/drive/backups/`. I have zero idea how to do this on my own.

## Current Behavior
Triggers saving the database on `vagrant halt`, not on cron job or multiple locations.

## Context
We're developing many Woocommerce websites right now and we're getting into some pretty significant, data-heavy development and testing. We'd like backups constantly and Drive allows for version history (like dropbox). If we make a change 4 hours ago and it breaks something, but we didn't notice it until 4 hours later, we'd like to be able to go through those backups.

## Your Environment
* VVV version: 2.5.2
* VVV Git Branch: master
* Vagrant version: 2.2.4
* VM Provider name: Virtualbox
* VM Provider version: 6.06r130049
* Operating System and version: Windows 10 Pro, 1809

**Comment by tomjn** [comment]
You can run the db_backup script to run the script the triggers run

As for Google drive, you could map the backup folder, but, that's more of a
Google drive question
