### ISSUE TITLE
one.wordpress.test not found

### ISSUE THREAD

**Issue by RickorDD** [Varying-Vagrant-Vagrants/VVV#1817]
i tested VVV3 and vvv.test is running  but one.wordpress.test shows this error.

<img width="1210" alt="Bildschirmfoto 2019-05-21 um 13 30 04" src="https://user-images.githubusercontent.com/6922544/58092551-a9926800-7bcc-11e9-921e-3b29cf3d3aa5.png">

**Comment by tomjn** [comment]
had provisioning completed when you visited the site? It's possible visit that site before it's been provisioned as the host entry gets added at the very start. **Without a provisioner log though it's difficult to say what happened, can you get me a copy?** A reprovision might get it working for you

**Comment by RickorDD** [comment]
with sudo vagrant up  --provision now running perfect

**Comment by tomjn** [comment]
@RickorDD you should never run `vagrant` commands with `sudo`

**Comment by RickorDD** [comment]
here my error without sudo. With sudo runs perfect.

$vagrant up --provision 
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.0.0-git::master

Platform:   platform-darwin13.4.0 shell:/bin/bash vagrant-hostsupdater shared_db_folder_disabled 
Vagrant:    v2.2.4,	VirtualBox: v6.0.8r130520
VVV Path:   "/Users/reikoweiss/WordPress/project/vagrant-dev"

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

The VirtualBox VM was created with a user that doesn't match the
current user running Vagrant. VirtualBox requires that the same user
be used to manage the VM that was created. Please re-run Vagrant with
that user. This is not a Vagrant issue.

The UID used to create the VM was: 0
Your UID is: 501

**Comment by tomjn** [comment]
Destroy your VM and recreate it without sudo. Never use sudo with vagrant
commands

If that doesn't work, uninstall and reinstall vagrant and destroy the VMs
using Virtualbox. Using sudo is very bad and will cause issues. Do not use
sudo with vagrant or VVV

You may also have to uninstall vagrant plugins with sudo then reinstall
them without sudo

**Comment by Mte90** [comment]
Any updates? Can we close that ticket?

**Comment by benlumia007** [comment]
i'm pretty sure it should be solved. we could reopen it
