### ISSUE TITLE
mongod have issue

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#1818]
## Context
Upgrade `vagrant box update` and then run `vagrant reload --provision`

## Your Environment
* VVV version: 2.6.0
* VVV Git Branch: master
* Vagrant version: Vagrant 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: VirtualBox: v5.2.20r125813
* Operating System and version: MacOs

default: Making sure mongodb service is enabled
    default: Auto-removing mongoDB records older than 2592000 seconds (30 days)
    default: Restarting mongod
    default: /vagrant/provision/resources/core/mongodb/provision.sh: line 66: systemctl: command not found
    default: /vagrant/provision/resources/core/mongodb/provision.sh: line 67: systemctl: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by jakemayfield** [comment]
I'm also experiencing this issue. Exact same specs.

**Comment by tomjn** [comment]
Both of you are using the unsupported VVV 2.x, you need to update to VVV 3

If you managed to fix this on VVV2, provisioning would still fail because
of the deleted PHP packages, that you got as far as mongodb is surprising

**Comment by jakemayfield** [comment]
Thanks, @tomjn !

Oops! I missed the update. 
That did the trick. Also, I found the article mentioning the update, for anyone else that might have missed it:
https://varyingvagrantvagrants.org/blog/2019/05/15/vvv-3-0-0.html

Do you happen to know if there's been any mention of listing the latest version in the README, and perhaps including instructions for upgrading?

**Comment by tomjn** [comment]
We used to list the latest version in the readme and for 90% of the time it was there it was the incorrect.

If you want the latest released version the answer is always `git checkout master` and `git pull`. Upgrade instructions are on varyingvagrantvagrants.com

**Comment by Mte90** [comment]
This problem is still happening? Can you check the develop branch?

**Comment by tomjn** [comment]
I'm going to close this out as it's a VVV 2 issue, and VVV 3 switched to Mongodb 4, feel free to reopen if you have this issue with VVV 3.1 or later
