### ISSUE TITLE
apt update

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1824]
Whenever we do a provision, it will always checked and update software. is this something that can be done only once when you do a vagrant up for the first time. 

I think if we can limit this once per VM, and have users do it themselve, then the provision will be even shorter. 

need feedback.

**Comment by Mte90** [comment]
It is part of the provision check the software installed if there are updates.
If we apply this rule we need to avoid also that stuff like npm or composer not execute updates.

The plan of VVV4 with a custom box will include already all the software preinstalled so there will be not anymore problems from this point of view.
