### ISSUE TITLE
Use site_title instead of name in dashboard

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1826]
since we have a feature to use a custom site_title

```
custom:
  site_title: A WordPress Theme
```
in the sites.php for the dashboard, it only displays `echo strip_tags( $name );`

i thought it would be cool that since we can use site_title.  we can take this even higher

```
            <?php
                if ( ! empty( $site['custom']['site_title'] ) ) {
                    $names = $site['custom']['site_title']; ?>
                    <span class="site-name"><?php echo strip_tags( $names ); ?></span>
                <?php } else { ?>
                    <span class="site-name"><?php echo strip_tags( $name ); ?></span>
                <?php }
            ?>
```

what does this do is if we use site_title in the .yml file,  it will display the site_title name that the user chosen. if site_title is not there, then it will fall to the default. 

just a thought.

**Comment by tomjn** [comment]
Sounds good, but I'd like the name to always be there even if it's in brackets

**Comment by benlumia007** [comment]
@tomjn 
this has been added to a new branch `benlumia007-site` in the dashboard repo.

**Comment by Mte90** [comment]
Ref: https://github.com/Varying-Vagrant-Vagrants/dashboard/pull/8
