### ISSUE TITLE
MariaDB not working 

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#1827]
## Expected Behavior
MariaDB should work

## Current Behavior
default: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    default: ERROR 2002 (HY000)

1. log on to vagrant via vagrant ssh
mariadb.service - MariaDB 10.3.15 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Tue 2019-05-28 07:26:51 UTC; 11s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 14518 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 14447 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-enviro
  Process: 14440 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 14429 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 14518 (code=exited, status=1/FAILURE)
   Status: "MariaDB server is down"
goto mark:
[1]+  Stopped                 systemctl status mariadb.service
...skipping...

* VVV version: 3.0.0
* VVV Git Branch:  master
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0.8rc
* Operating System and version: Ubuntu 18.04

**Comment by tomjn** [comment]
Hello!

I'm not sure what you did to get this error from your message, can you
provide clear instructions on what you did? Was it just "vagrant ssh" and
no other commands? And did you try reprovisioning or turning it off/on? Was
this an existing install that suddenly broke or a fresh new install?

**Comment by Mte90** [comment]
Can you try the develop branch version now?

**Comment by tomjn** [comment]
Closing this out due to lack of feedback,
