### ISSUE TITLE
Composer dependencies failing : Force vagrant-vbguest update

### ISSUE THREAD

**Issue by exlame** [Varying-Vagrant-Vagrants/VVV#1828]
Issue related : https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1799

## Expected Behavior

Some systems had problems with shared_folders and recent versions of VirtualBox. We should have access to configure a bit more from vvv-custom.yml. What I need is to set `config.vbguest.auto_update`

## Current Behavior

On VirtualBox6.0.8, composer can't install any package of type `composer-plugin` like `composer/installers` because of some shared_folder issues in VirtualBox 6.0.8. Downgrading to VirtualBox 5.30 can work but I needed to change `config.vbguest.auto_update` to `true` 

## Possible Solution

Be able to set `config.vbguest.auto_update` from vvv-custom.yml.

## Steps to Reproduce (for bugs)

All logs from git clone to resolved status : https://gist.github.com/exlame/9789a5e1f842b4e83a88fb96e8dba623

1. `vagrant up` -> composer require fails, it also failed on manual install with `vagrant ssh` in `/srv/www`
2.  change `config.vbguest.auto_update`  to true
3. `vagrant reload --provision`

## Your Environment

* VVV version: v3.0.0-git::develop 
* VVV Git Branch: develop
* Vagrant version:  v2.2.4
* VM Provider name: VirtualBox
* VM Provider version: v5.2.30r130521
* Operating System and version: Windows10 Home

**Comment by tomjn** [comment]
I explicitly disabled `config.vbguest.auto_update` as the vagrant guest updater plugin was crashing for a lot of users on Ubuntu 18. Guest additions can be updated from inside the VM without the need for a Vagrant plugin.

Also, the plugin can be ran directly, no VVV changes are necessary:

https://github.com/dotless-de/vagrant-vbguest
