### ISSUE TITLE
Windows 10 Pro ( Hyper-V )

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1831]
I have been playing around with Hyper-V and is not an easy thing to configure. One is the network, even if you use vagrant-hostsupdater with a static IP, it will not work due to limitations and how Hyper-V works. When you use vagrant-hostsupdater, it does not automatically create a network adapter like what VirtualBox do. It seems like when using hyper-v in general, the vagrant box must have two adapters, one for the default switch that the box uses and second is the static IP that will be using ( 192.168.50.4 ). I am still testing this and i don't see any other choices. During the actual build of the box, adapters should be already been set, if not, when you add a private network, you will have to enable it manually.

I have actually successfully got everything setup, please note that, since hyperv doesn't use mount_options like virtualbox.  you will have to use the vm's username ( vagrant ) to install WordPress since, there's no way to use chmod to set permission. if there is, i haven't found the solution for it. 

Since Hyper-V uses SMB to do shared folders, after testing my own environment, there is slightly a lag for a few seconds and it does get annoying. when you vagrant up, the sites doesn't get loaded, so i had to go to into the system using vagrant ssh and restart the apache2. The box i use is a custom box i created, and it should be the same situation if using bento or a custom box. 

for hyperv, permissions are strict, so using www-data won't work if you use wp-cli to install wordpress, so the config.vm.shared_folder should set to the vm user ( vagrant ) so it can properly install or else it will give you permission denied. 

HyperV wasn't meant for local development in such ways even if it can, it is mainly for deployments to production servers ( VPS ). 

the goal right now is to get it work... `working > correct`, so as long as it works, we can figure out on how to improve on how hyperv works. 

shared folder should be fix first, the rest will fall in place.

**Comment by benlumia007** [comment]
i have also managed to test it on my surface pro 4, and it's very slow. downloading a github repo takes forever :D.

**Comment by benlumia007** [comment]
@tomjn 

I manged to fix all permissions and mount shared folders, afterwards, it actually started the process and for some reason.. i got this error

```
    default: Errors were encountered while processing:
    default:  mariadb-server-10.3
    default:  mariadb-server
    default: E
    default: : Sub-process /usr/bin/dpkg returned an error code (1)
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by benlumia007** [comment]
```
    default: ● mariadb.service - MariaDB 10.3.15 database server
    default:    Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
    default:   Drop-In: /etc/systemd/system/mariadb.service.d
    default:            └─migrated-from-my.cnf-settings.conf
    default:    Active: failed (Result: exit-code) since Thu 2019-05-30 20:37:08 UTC; 7ms ago
    default:      Docs: man:mysqld(8)
    default:            https://mariadb.com/kb/en/library/systemd/
    default:   Process: 5893 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
    default:   Process: 5745 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
    default:   Process: 5738 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
```

**Comment by benlumia007** [comment]
you should be able to change the owner and group of the folder with the existing options: https://www.vagrantup.com/docs/synced-folders/basic_usage.html#group and https://www.vagrantup.com/docs/synced-folders/basic_usage.html#owner

Otherwise, it looks like you should actually be using file_mode and dir_mode: https://wiki.ubuntu.com/MountWindowsSharesPermanently

Vagrant simply passes those mount options along to the tool its using to sync folders, so I recommend reading up on SMB to figure out how to use it.

**Comment by benlumia007** [comment]
at the meantime, mariadb will fail and unable to complete the provision for now until we fix this somehow with the user/group.

Permissions should be ok now but can't verify due to MariaDB.

**Comment by tomjn** [comment]
The changes to the main provisioner and the vagrant file regarding user and group IDs might have resolved that, it'll need checking

**Comment by benlumia007** [comment]
got it, my surface pro is dead so i gotta test it out tonight. I'l let u know if that fixes it.

**Comment by benlumia007** [comment]
nope, still fails, but it still says
`unable to set password for MariaDB 'root' user`

**Comment by dingo-d** [comment]
My Windows provisioning also fails

<details>
<summary> Error log on Hyper</summary>
<pre><code>
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 782ms.
 ⚡ denis@DESKTOP-3JICV98  ~  D:
 ⚡ denis@DESKTOP-3JICV98  D:  cd .\vagrant-local\
 ⚡ denis@DESKTOP-3JICV98  D:\vagrant-local   develop ≣  vagrant up --provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.1.0-git::develop

Platform:   platform-mingw32 windows HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled 
Vagrant:    v2.2.4,     VirtualBox: v6.0.8r130520
VVV Path:   "D:/vagrant-local"

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20190624.0.0' is up to date...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 one.wordpress.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 two.wordpress.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 tideways.vvv.test 
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 xhgui.vvv.test    
==> default: Running provisioner: file...
    default: D:/vagrant-local/version => /home/vagrant/version
==> default: Running provisioner: file...
    default: D:/vagrant-local/vvv-custom.yml => /home/vagrant/vvv-custom.yml
==> default: Running provisioner: initial-setup (shell)...
    default: Running: inline script
==> default: Running provisioner: default (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-1bhwud6.sh
    default: /tmp/vagrant-shell: line 85: /srv/provision/provision-network-functions.sh: No such file or directory
    default: /tmp/vagrant-shell: line 834: network_check: command not found
    default: Bash profile setup and directories.
    default: cp: cannot stat '/srv/config/update-motd.d/00-vvv-bash-splash'
    default: : No such file or directory
    default: chmod: cannot access '/etc/update-motd.d/00-vvv-bash-splash'
    default: : No such file or directory
    default:  * Setting ownership of files in /home/vagrant to vagrant
    default:  * Copying /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default: cp: cannot stat '/srv/config/bash_profile': No such file or directory
    default:  * Copying /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default: cp: cannot stat '/srv/config/bash_aliases': No such file or directory
    default:  * Copying /srv/config/vimrc                             to /home/vagrant/.vimrc
    default: cp: cannot stat '/srv/config/vimrc': No such file or directory
    default:  * Copying /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default: cp: cannot stat '/srv/config/subversion-servers': No such file or directory
    default:  * Copying /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default: cp: cannot stat '/srv/config/subversion-config': No such file or directory
    default:  * Copying /srv/config/ssh_known_hosts to /etc/ssh/ssh_known_hosts
    default: cp: cannot stat '/srv/config/ssh_known_hosts': No such file or directory
    default: /tmp/vagrant-shell: line 840: network_check: command not found
    default:
    default: Main packages check and install.
    default:  * git-core/ppa already present, skipping
    default: 
    default:  * Setting up MySQL configuration file links...
    default:  * mysql group exists
    default:  * mysql user present and has uid 9001
    default: uid=9001(mysql) gid=9001(mysql) groups=9001(mysql),115(vboxsf)
    default:  * Copying /srv/config/mysql-config/vvv-core.cnf to /etc/mysql/conf.d/vvv-core.cnf
    default: cp: cannot stat '/srv/config/mysql-config/vvv-core.cnf': No such file or directory
    default:  * Copying custom apt sources
    default: cp: cannot stat '/srv/config/apt-source-append.list': No such file or directory
    default:  * Checking Apt Keys
    default: Applying NodeSource NodeJS signing key...
    default: gpg: can't open '/srv/config/apt-keys/nodesource.gpg.key': No such file or directory
    default: Applying Nginx signing key...
    default: gpg: can't open '/srv/config/apt-keys/nginx_signing.key': No such file or directory
    default: Applying the Ondřej PHP signing key...
    default: gpg: can't open '/srv/config/apt-keys/ondrej_keyserver_ubuntu.key': No such file or directory
    default: Applying the Varying Vagrant Vagrants mirror signing key...
    default: gpg: can't open '/srv/config/apt-keys/varying-vagrant-vagrants_keyserver_ubuntu.key': No such file or directory
    default: Applying the MariaDB signing key...
    default: gpg: can't open '/srv/config/apt-keys/mariadb.key': No such file or directory
    default: Applying the PackageCloud Git-LFS signing key...
    default: gpg: can't open '/srv/config/apt-keys/git-lfs.key': No such file or directory
    default: Running apt-get update...
    default: Ign:1 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 InRelease
    default: Hit:2 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release
    default: Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
    default: Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
    default: Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
    default: Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease
    default: Reading package lists...
    default: Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: 
    default: Reading state information...
    default: make is already the newest version (4.1-9.1ubuntu1).
    default: unzip is already the newest version (6.0-21ubuntu1).
    default: zip is already the newest version (3.0-11build1).
    default: colordiff is already the newest version (1.0.18-1).
    default: dos2unix is already the newest version (7.3.4-3).
    default: git-lfs is already the newest version (2.3.4-1).
    default: graphviz is already the newest version (2.40.1-2).
    default: ngrep is already the newest version (1.47+ds1-1).
    default: php-imagick is already the newest version (3.4.3~rc2-2ubuntu4).
    default: php-memcache is already the newest version (3.0.9~20160311.4991c2f-5build2).
    default: php-memcached is already the newest version (3.0.1+2.2.0-1build2).
    default: php-ssh2 is already the newest version (1.1.2+0.13-1build1).
    default: php-xdebug is already the newest version (2.6.0-0ubuntu1).
    default: php-yaml is already the newest version (2.0.0+1.3.0-2build2).
    default: subversion is already the newest version (1.9.7-4ubuntu1).
    default: curl is already the newest version (7.58.0-2ubuntu3.7).
    default: g++ is already the newest version (4:7.4.0-1ubuntu2.3).
    default: gettext is already the newest version (0.19.8.1-6ubuntu0.3).
    default: git is already the newest version (1:2.17.1-1ubuntu0.4).
    default: imagemagick is already the newest version (8:6.9.7.4+dfsg-16ubuntu6.7).
    default: memcached is already the newest version (1.5.6-0ubuntu1.1).
    default: nginx is already the newest version (1.14.0-0ubuntu1.2).
    default: php-pear is already the newest version (1:1.10.5+submodules+notgz-1ubuntu1.18.04.1).
    default: php7.2-cli is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-common is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-curl is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-dev is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-gd is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-json is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-mysql is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-xml is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: postfix is already the newest version (3.3.0-1ubuntu0.2).
    default: software-properties-common is already the newest version (0.96.24.32.9).
    default: vim is already the newest version (2:8.0.1453-1ubuntu1.1).
    default: git-svn is already the newest version (1:2.17.1-1ubuntu0.4).
    default: mariadb-server is already the newest version (1:10.1.40-0ubuntu0.18.04.1).
    default: nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
    default: ntp is already the newest version (1:4.2.8p10+dfsg-5ubuntu7.1).
    default: php7.2-bcmath is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-fpm is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-imap is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-mbstring is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-soap is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: php7.2-zip is already the newest version (7.2.19-0ubuntu0.18.04.1).
    default: python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
    default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    default: Removing unnecessary packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: 
    default: Reading state information...
    default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    default: Cleaning apt caches...
    default: sh: 0: Can't open /srv/config/homebin/xdebug_off
    default: Installing/updating npm...
    default: sudo: npm: command not found
    default: Installing/updating npm-check-updates...
    default: sudo: npm: command not found
    default: ack-grep already installed
    default: Updating Composer...
    default: You are already using composer version 1.8.6 (stable channel).
    default: Changed current directory to /usr/local/src/composer
    default: ./composer.json has been updated
    default: Changed current directory to /usr/local/src/composer
    default: Changed current directory to /usr/local/src/composer
    default: Loading composer repositories with package information
    default: Updating dependencies (including require-dev)
    default: Nothing to install or update
    default: Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
    default: Generating autoload files
    default: Installing Grunt CLI
    default: sudo: npm: command not found
    default: sudo: npm: command not found
    default: sudo: npm: command not found
    default: sudo: npm: command not found
    default: chown: cannot access '/usr/lib/node_modules/': No such file or directory
    default: Adding graphviz symlink for Webgrind...
    default: Installing Shyaml for bash provisioning..
    default: Requirement already satisfied: shyaml in /usr/local/lib/python2.7/dist-packages
    default: Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from shyaml)
    default: 
    default: Setup configuration files...
    default:  * Copying /srv/config/init/vvv-start.conf               to /etc/init/vvv-start.conf
    default: cp: cannot stat '/srv/config/init/vvv-start.conf': No such file or directory
    default:  * Copying /srv/config/nginx-config/nginx.conf           to /etc/nginx/nginx.conf
    default: cp: cannot stat '/srv/config/nginx-config/nginx.conf': No such file or directory
    default:  * Copying /srv/config/nginx-config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf
    default: cp: cannot stat '/srv/config/nginx-config/nginx-wp-common.conf': No such file or directory
    default:  * Copying /srv/config/nginx-config/php7.2-upstream.conf to /etc/nginx/upstreams/php72.conf
    default: cp: cannot stat '/srv/config/nginx-config/php7.2-upstream.conf': No such file or directory
    default:  * Rsync'ing /srv/config/nginx-config/sites/             to /etc/nginx/custom-sites
    default: sending incremental file list
    default: rsync: change_dir "/srv/config/nginx-config/sites" failed: No such file or directory (2)
    default: 
    default: sent 20 bytes  received 12 bytes  64.00 bytes/sec
    default: total size is 0  speedup is 0.00
    default: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
    default: Making sure the Nginx log files and folder exist
    default:  * Starting MailHog
    default:  * Copying /srv/config/php-config/php7.2-fpm.conf   to /etc/php/7.2/fpm/php-fpm.conf
    default: cp: cannot stat '/srv/config/php-config/php7.2-fpm.conf': No such file or directory
    default:  * Copying /srv/config/php-config/php7.2-www.conf   to /etc/php/7.2/fpm/pool.d/www.conf
    default: cp: cannot stat '/srv/config/php-config/php7.2-www.conf': No such file or directory
    default:  * Copying /srv/config/php-config/php7.2-custom.ini to /etc/php/7.2/fpm/conf.d/php-custom.ini
    default: cp: cannot stat '/srv/config/php-config/php7.2-custom.ini': No such file or directory
    default:  * Copying /srv/config/php-config/opcache.ini       to /etc/php/7.2/fpm/conf.d/opcache.ini
    default: cp: cannot stat '/srv/config/php-config/opcache.ini': No such file or directory
    default:  * Copying /srv/config/php-config/xdebug.ini        to /etc/php/7.2/mods-available/xdebug.ini
    default: cp: cannot stat '/srv/config/php-config/xdebug.ini': No such file or directory
    default:  * Copying /srv/config/php-config/mailhog.ini       to /etc/php/7.2/mods-available/mailhog.ini
    default: cp: cannot stat '/srv/config/php-config/mailhog.ini': No such file or directory
    default:  * Copying /srv/config/memcached-config/memcached.conf to /etc/memcached.conf and /etc/memcached_default.conf
    default: cp: cannot stat '/srv/config/memcached-config/memcached.conf': No such file or directory
    default: cp: cannot stat '/srv/config/memcached-config/memcached.conf': No such file or directory
    default:
    default: Restarting services...
    default: WARNING: Module mailhog ini file doesn't exist under /etc/php/7.2/mods-available
    default: WARNING: Module mailhog ini file doesn't exist under /etc/php/7.2/mods-available
    default: 
    default: Setup MySQL configuration file links...
    default: cp: cannot stat '/srv/config/mysql-config/my.cnf'
    default: : No such file or directory
    default: cp: cannot stat '/srv/config/mysql-config/root-my.cnf': No such file or directory
    default:  * Copied /srv/config/mysql-config/my.cnf               to /etc/mysql/my.cnf
    default:  * Copied /srv/config/mysql-config/root-my.cnf          to /home/vagrant/.my.cnf
    default: service mysql restart
    default: 
    default: No custom MySQL scripting found in database/init-custom.sql, skipping...
    default: /tmp/vagrant-shell: line 717: /srv/database/init.sql: No such file or directory
    default: Initial MySQL prep...
    default: /tmp/vagrant-shell: line 722: /srv/database/import-sql.sh: No such file or directory
    default: /tmp/vagrant-shell: line 858: network_check: command not found
    default:
    default: Installing/updating wp-cli and debugging tools
    default:
    default: Updating wp-cli...
    default: Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
    default: md5 hash verified: aa13dd27528be6be8c12a12acc190619
    default: New version works. Proceeding to replace.
    default: Success: Updated WP-CLI to the latest nightly release.
    default: 
    default: Install/Update PHP_CodeSniffer (phpcs), see https://github.com/squizlabs/PHP_CodeSniffer
    default:
    default: Install/Update WordPress-Coding-Standards, sniffs for PHP_CodeSniffer, see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    default: /tmp/vagrant-shell: line 781: cd: /srv/provision/phpcs: No such file or directory
    default: Composer could not find a composer.json file in /home/vagrant
    default: To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
    default: /tmp/vagrant-shell: line 790: phpcs: command not found
    default: /tmp/vagrant-shell: line 791: phpcs: command not found
    default: /tmp/vagrant-shell: line 792: phpcs: command not found
    default: /tmp/vagrant-shell: line 866: network_check: command not found
    default:
    default:  * Searching for SVN repositories that need upgrading
    default:
    default: Cleaning up Nginx configs
    default: Cleaning the virtual machine's /etc/hosts file...
    default: -----------------------------
    default: Provisioning complete in 11 seconds
    default: For further setup instructions, visit http://vvv.test
==> default: Running provisioner: dashboard (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-hue3lf.sh
    default: 
    default: Updating dashboard on the master branch...
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-125g5q5.sh
    default: Updating the "core" utility on the "master" branch...
==> default: Running provisioner: utility-core-memcached-admin (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-yfugor.sh
    default: Running utility provisioner for 'core/memcached-admin'
    default: phpMemcachedAdmin already installed.
==> default: Running provisioner: utility-core-opcache-status (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-1i7x9v8.sh
    default: Running utility provisioner for 'core/opcache-status'
    default:
    default: Updating Opcache Status
    default: From https://github.com/rlerdorf/opcache-status
    default:  * branch            master     -> FETCH_HEAD
    default: Already up to date.
    default: Current branch master is up to date.
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-1h2qf8i.sh
    default: Running utility provisioner for 'core/phpmyadmin'
    default: Checking phpMyAdmin
    default: PHPMyAdmin already installed.
==> default: Running provisioner: utility-core-webgrind (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-1l93dxc.sh
    default: Running utility provisioner for 'core/webgrind'
    default: Updating webgrind...
    default: From https://github.com/jokkedk/webgrind
    default:  * branch            master     -> FETCH_HEAD
    default: Already up to date.
    default: Current branch master is up to date.
==> default: Running provisioner: utility-core-tls-ca (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-fdawjg.sh
    default: Running utility provisioner for 'core/tls-ca'
==> default: Running provisioner: utility-core-mongodb (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-6l6ku6.sh
    default: Running utility provisioner for 'core/mongodb'
    default: Making sure mongodb service is enabled
    default: Auto-removing mongoDB records older than 2592000 seconds (30 days)
    default: Restarting mongod
==> default: Running provisioner: utility-core-tideways (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-1am0xck.sh
    default: Running utility provisioner for 'core/tideways'
    default: Making sure mongodb service is enabled
    default: Auto-removing mongoDB records older than 2592000 seconds (30 days)
    default: Restarting mongod
    default: Installing Tideways & XHgui
    default: Updating Tideways extension
    default: Installing Tideways for PHP 
    default: Copying tideways files for PHP 7.2
    default: 
    default: Updating xhgui...
    default: Restarting PHP-FPM server
    default: Restarting Nginx
    default: Tideways and xhgui installed
==> default: Running provisioner: site-wordpress-one (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-1en63gl.sh
    default: 
    default: Updating wordpress-one in /srv/www/wordpress-one...
    default:  * Custom site template provisioner - downloads and installs a copy of WP stable for testing, building client sites, etc
    default: 
    default: Creating database 'wordpressone' (if it's not already there)
    default:
    default: Granting the wp user priviledges to the 'wordpressone' database
    default: 
    default:  DB operations done.
    default:
    default:
    default: Setting up the log subfolder for Nginx logs
    default: mkdir: cannot create directory ‘/srv/www/wordpress-one/log’: Permission denied
    default: touch: cannot touch '/srv/www/wordpress-one/log/nginx-error.log': No such file or directory
    default: touch: cannot touch '/srv/www/wordpress-one/log/nginx-access.log'
    default: : No such file or directory
    default: Downloading WordPress...
    default: Error: Insufficient permission to create directory '/srv/www/wordpress-one/public_html/'.
    default: Configuring WordPress Stable...
    default: Error: This does not seem to be a WordPress installation.
    default: Pass --path=`path/to/wordpress` or run `wp core download`.
    default: Error: This does not seem to be a WordPress installation.
    default: Pass --path=`path/to/wordpress` or run `wp core download`.
    default: Installing WordPress Stable...
    default: Using a single site install
    default: Error: This does not seem to be a WordPress installation.
    default: Pass --path=`path/to/wordpress` or run `wp core download`.
    default: WordPress was installed, with the username 'admin', and the password 'password' at admin@local.test
    default: Copying the sites Nginx config template ( fork this site template to customise the template )
    default: Inserting the SSL key locations into the sites Nginx config
    default: Site Template provisioner script completed
    default: Adding domains to the virtual machine's /etc/hosts file...
    default: Adding hosts from the VVV config entry
    default:  * Added one.wordpress.test from /vagrant/vvv-custom.yml
    default: Reloading Nginx
==> default: Running provisioner: site-wordpress-two (shell)...
    default: Running: C:/Users/denis/AppData/Local/Temp/vagrant-shell20190626-2560-kbwgoh.sh
    default:
    default: Updating wordpress-two in /srv/www/wordpress-two...
    default:  * Custom site template provisioner - downloads and installs a copy of WP stable for testing, building client sites, etc
    default:
    default: Creating database 'wordpresstwo' (if it's not already there)
    default:
    default: Granting the wp user priviledges to the 'wordpresstwo' database
    default:
    default:  DB operations done.
    default:
    default:
    default: Setting up the log subfolder for Nginx logs
    default: mkdir: cannot create directory ‘/srv/www/wordpress-two/log’: Permission denied
    default: touch: cannot touch '/srv/www/wordpress-two/log/nginx-error.log': No such file or directory
    default: touch: cannot touch '/srv/www/wordpress-two/log/nginx-access.log': No such file or directory
    default: Downloading WordPress...
    default: Error: Insufficient permission to create directory '/srv/www/wordpress-two/public_html/'.
    default: Configuring WordPress Stable...
    default: Error: This does not seem to be a WordPress installation.
    default: Pass --path=`path/to/wordpress` or run `wp core download`.
    default: Error: This does not seem to be a WordPress installation.
    default: Pass --path=`path/to/wordpress` or run `wp core download`.
    default: Installing WordPress Stable...
    default: Using a single site install
    default: Error: This does not seem to be a WordPress installation.
    default: Pass --path=`path/to/wordpress` or run `wp core download`.
    default: WordPress was installed, with the username 'admin', and the password 'password' at admin@local.test
    default: Copying the sites Nginx config template ( fork this site template to customise the template )
    default: Inserting the SSL key locations into the sites Nginx config
    default: Site Template provisioner script completed
    default: Adding domains to the virtual machine's /etc/hosts file...
    default: Adding hosts from the VVV config entry
    default:  * Added two.wordpress.test from /vagrant/vvv-custom.yml
    default: Reloading Nginx
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 1: /srv/config/homebin/vagrant_up: No such file or directory
==> default: Trigger run failed
==> default: The SSH command responded with a non-zero exit status. Vagrant
==> default: assumes that this means the command failed. The output for this command
==> default: should be in the log above. Please read the output to determine what
==> default: went wrong.
</code>
</pre>
</details>

**Comment by benlumia007** [comment]
@tomjn 
I'm going to close this for now, until we get the rest sorted out and I can retest HyperV again later on.
