### ISSUE TITLE
Unable to Provision - Cannot clone Site Template

### ISSUE THREAD

**Issue by joecue** [Varying-Vagrant-Vagrants/VVV#1836]
## Expected Behavior

I just updated Vagrant, Virtualbox, and VVV to the current levels according to the 3.0 release blog post.  I followed all of the steps to update my VVV environment, and while everything worked on my desktop, it's failing on my laptop.

https://varyingvagrantvagrants.org/blog/2019/05/15/vvv-3-0-0.html

## Current Behavior

After running '<pre>vagrant destroy</pre>'

I then run '<pre>vagrant up --provision</pre>'

I then receive
<pre>
    default: Succesful Network connection to ppa.launchpad.net detected...
    default:
    default:  * Searching for SVN repositories that need upgrading
    default:
    default: Cleaning up Nginx configs
    default: Cleaning the virtual machine's /etc/hosts file...
    default: -----------------------------
    default: Provisioning complete in 519 seconds
    default: For further setup instructions, visit http://vvv.test
==> default: Running provisioner: dashboard (shell)...
    default: Running: C:/Users/jquerin/AppData/Local/Temp/vagrant-shell20190603-                           10632-14t123.sh
    default: fatal: destination path '/srv/www/default/dashboard' already exists                            and is not an empty directory.
    default:
    default: Downloading dashboard, see https://github.com/Varying-Vagrant-Vagra                           nts/dashboard.git
    default: fatal: not a git repository (or any parent up to mount point /srv)
    default: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM no                           t set).
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: C:/Users/jquerin/AppData/Local/Temp/vagrant-shell20190603-                           10632-1kj9n3g.sh
    default: Updating the "core" utility on the "master" branch...
==> default: Running provisioner: site-lorainccc (shell)...
    default: Running: C:/Users/jquerin/AppData/Local/Temp/vagrant-shell20190603-                           10632-9xzexa.sh
    default:
    default: Downloading lorainccc, git cloning from https://github.com/Varying-                           Vagrant-Vagrants/custom-site-template-develop
    default: Git failed to clone the site template for lorainccc. It tried to cl                           one the master of https://github.com/Varying-Vagrant-Vagrants/custom-site-templa                           te-develop into /srv/www/lorainccc
    default: VVV won't be able to provision lorainccc without the template. Chec                           k that you have permission to access the repo, and that the filesystem is writab                           le
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
</pre>

## Steps to Reproduce (for bugs)

1. Update Vagrant, VirtualBox and pull new VVV from github
2. vagrant destroy
3. vagrant up --provision
4.

## Context

Just trying to get my laptop updated before I speak at a WordCamp for WordPress 101 on the first day, thankfully it's two weeks out!

## Your Environment

* VVV version: 3.0.0
* VVV Git Branch: develop
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0.8
* Operating System and version: Windows 7 Pro SP1

**Comment by Mte90** [comment]
What is the content of your vvv-custom file? Seems that has issue on downloading the dashboard template.

**Comment by joecue** [comment]
I don't think it's anything out of the ordinary

<pre>
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  lorainccc:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - lorainccc.test
     custom:
       wp_type: subdirectory
       db_name: lorainccc
       wp_version: 4.9.8

  woo:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - woo.test
     custom:
       wp_type: single
       db_name: woo
       wp_version: 4.9.8
                            
  gutenberg:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - gutenberg.test
     custom:
       wp_type: single
       db_name: gutenberg
       wp_version: 4.9.8
                            
  joequerin:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - gutenberg.test
     custom:
       wp_type: single
       db_name: gutenberg
       wp_version: 4.9.8
                            
  themereview:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - themereview.test
     custom:
       wp_type: single
       db_name: themereview
       wp_version: 4.9.8 
                            
  threegreenbirds:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - threegreenbirds.test
     custom:
       wp_type: single
       db_name: threegreenbirds
       wp_version: 4.9.8 

  wpdemo:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - wpdemo.test
     custom:
       wp_type: single
       db_name: wpdemo
       wp_version: 4.9.8

  demo:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - demo.test
     custom:
       wp_type: single
       db_name: demo
       wp_version: 4.9.8

  wpmultisite:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - wpmultisite.test
     custom:
       wp_type: single
       db_name: wpmultisite
       wp_version: 4.9.8       
       
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.test
    custom:
      wp_type: single
      db_name: wordpress-default
      wp_version: latest

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test
    custom:
      wp_type: single
      db_name: wordpress-develop
      wp_version: latest
       
# The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git
</pre>

**Comment by joecue** [comment]
I don't think there is anything out of the ordinary there.

<pre>
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  lorainccc:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - lorainccc.test
     custom:
       wp_type: subdirectory
       db_name: lorainccc
       wp_version: 4.9.8

  woo:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - woo.test
     custom:
       wp_type: single
       db_name: woo
       wp_version: 4.9.8
                            
  gutenberg:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - gutenberg.test
     custom:
       wp_type: single
       db_name: gutenberg
       wp_version: 4.9.8
                            
  joequerin:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - gutenberg.test
     custom:
       wp_type: single
       db_name: gutenberg
       wp_version: 4.9.8
                            
  themereview:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - themereview.test
     custom:
       wp_type: single
       db_name: themereview
       wp_version: 4.9.8 

  wpdemo:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - wpdemo.test
     custom:
       wp_type: single
       db_name: wpdemo
       wp_version: 4.9.8

  demo:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - demo.test
     custom:
       wp_type: single
       db_name: demo
       wp_version: 4.9.8

  wpmultisite:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop
     hosts:
       - wpmultisite.test
     custom:
       wp_type: single
       db_name: wpmultisite
       wp_version: 4.9.8       
       
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.test
    custom:
      wp_type: single
      db_name: wordpress-default
      wp_version: latest

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test
    custom:
      wp_type: single
      db_name: wordpress-develop
      wp_version: latest
       
# The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git
</pre>

**Comment by tomjn** [comment]
@joecue I notice you're using the WP Core development site template rather than the standard WP template for a lot of websites, is there a particular reason for doing that? I can understand if you were dealing with lots of Trac tickets but I see you're also pinning them to old versions of WordPress

Instead, perhaps you should use the `custom-site-template`? `custom-site-template-develop` isn't intended for developing themes/sites/plugins but for developing WP Core itself. `custom-site-template` is both smaller, leaner, faster, and more stable, and provides you with a standard WordPress install

Additionally:

 - I see you're running Windows 7 SP1, you may want to disconnect your machine from a live internet connection until it's been updated to avoid security issues
 - Consider downgrading VirtualBox to v5.3.x
 - Can you share a full provisioner log? Your copy paste has a weird spacing artefact, and it's missing the VVV splash which contains a lot of useful debug information, as well as the output of the main provisioner
 - Finally, it failed on the `site-lorainccc` site, does the folder already exist for this site? Or was this a clean slate?

**Comment by joecue** [comment]
My laptop receives regular windows updates and is secure from what our network environment provides.

I'm trying to upgrade VVV to 3.0 like I did on my Windows 7 SP1 desktop workstation which worked fine.

I'll try changing the site-template.  I'm running the version of WordPress that I am, since as an institution we haven't moved our versions forward to 5.0 due to gutenberg.

I'll look for the provisioner log and post it when I find it.

What I don't understand is how I can everything identical between my two machines, yet one is successful and one fails.

**Comment by tomjn** [comment]
> I'll try changing the site-template. I'm running the version of WordPress that I am, since as an institution we haven't moved our versions forward to 5.0 due to gutenberg.

These sites, do their folders already exist? And if they do, do they have `.git` folders inside them? If you have a site that's literally just a folder ( no git ), add it to `vvv-custom.yml`, but specify a site template, I would expect you to have problems ( afterall there's nothing VVV could do that wouldn't involve destroying files anyway )

**Comment by joecue** [comment]
All of the folders already exist.  On my desktop they have the .git folder, but on my laptop they do not.

**Comment by tomjn** [comment]
Then that's the problem, because they aren't `.git` folders, VVV tries to do a `git clone` of the site template. Because the folder already exists `git` refuses and provisioning ends

In theory this PR will identify that situation: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1837

But for you, there are two options:

 - remove the `repo:` field
 - use git repos

I'm assuming the folders on your laptop were copied from your desktop? If so it appears that the copy was incomplete and dot folders were not copied over

**Comment by joecue** [comment]
They are separate installations, I keep my custom developed themes and plugins updated via git repos.

Am I better off to just move my content out of the www folder and let VVV reprovision and then set up my theme and plugin git repos?

**Comment by tomjn** [comment]
you could do that yes, provision the folders then copy the contents back in, but just eliminating the `repo:` line on each site will work too, assuming you have provisioner folders in there

**Comment by joecue** [comment]
Thanks @tomjn I'll move the www contents out and re-provision.  I'm trying to keep the two systems consistent.

**Comment by joecue** [comment]
moving the content and reprovisioning seems to have done the trick!

I thought of trying that this weekend, but couldn't figure out why it worked in one place and not the other.  Guess my two systems must have been slightly off to begin with.
