### ISSUE TITLE
Version 3.0 no longer outputs error logs in /vvv/log/

### ISSUE THREAD

**Issue by roykho** [Varying-Vagrant-Vagrants/VVV#1838]
## Expected Behavior
To see error logs in /vvv/log/

## Current Behavior
Error logs are now in /var/log/

## Steps to Reproduce (for bugs)

1. Make sure xdebug is enabled in VM. 
2. `error_log( 'test' );` in application
3. Go to /vvv/log/ and find no logging is done.

## Context

This is the same issue I had here https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1620

Was working with version 2.6.x. After updating to 3.0.0 this started happening like it did before.

## Your Environment

* VVV version: 3.0.0
* VVV Git Branch: develop
* Vagrant version: 2.2.4
* VM Provider name: Trusty Ubuntu 64
* VM Provider version:
* Operating System and version: MacOS

**Comment by Mte90** [comment]
Did you enabled `WP_DEBUG`? because in case the error should be at vvv/www/site/htdocs/wp-content/debug.log

**Comment by tomjn** [comment]
When you say VVV/logs can you be more specific? It's not clear if you're
referring to a folder inside or outside the VM

Have you checked the PHP sub folder?

**Comment by roykho** [comment]
VVV/logs meaning outside of the VM. Yes I know we can log to wp-content/debug.log but that is not very convenient for me and not how it worked pre 3.0.0.

**Comment by Mte90** [comment]
So you mean that the log in wp-content/debug.log is not working for you?
Or that you want all the log output of all the websites in the same file?

**Comment by roykho** [comment]
> So you mean that the log in wp-content/debug.log is not working for you?

No, that works.

> Or that you want all the log output of all the websites in the same file?

Correct and that's how it was working before. This way I don't need to keep open several log files to see the logs. I only need one log file open to see any of the individual sites I am working on.

**Comment by Mte90** [comment]
Uhm probably we changed in the PHP settings globally, anyway to  archive a multiple management of logs I am using `multitail` command.
We can see if support again a global log file.

**Comment by tomjn** [comment]
The PHP log is in `log/php/` where a log file for each version of PHP is present. It's the same as pre-3.0 but now in a `php` subfolder. e.g. `log/php/php7.2-fpm.log`. This is to avoid issues sharing the entire `/var/log` folder that prevented provisioning from working

If you're looking for site specific log file, those don't exist and never have done unless you used `WP_DEBUG` to redirect it. If you've any ideas on how Nginx can be configured to tell PHP FPM where to log to so it can be done on a per site basis that'd be awesome

**Comment by roykho** [comment]
> The PHP log is in log/php/ where a log file for each version of PHP is present.

I see the log file there but nothing new is logged there. The last statements I see in the log file is:

> [04-Jun-2019 04:32:54] NOTICE: fpm is running, pid 8371
[04-Jun-2019 04:32:54] NOTICE: ready to handle connections
[04-Jun-2019 04:32:54] NOTICE: systemd monitor interval set to 10000ms
[04-Jun-2019 04:33:56] NOTICE: Terminating ...
[04-Jun-2019 04:33:56] NOTICE: exiting, bye-bye!

**Comment by tomjn** [comment]
@roykho you should have 2 logs, the FPM log file, and the error log file

I created a `test.php` and put this inside it:

```php
<?php
trigger_error('bananas');
```

which gave me the following in `/Users/tarendai/dev/www/vvv/log/php/php7.2_errors.log`:

```
[05-Jun-2019 19:55:17 UTC] PHP Notice:  bananas in /srv/www/wordpress-one/public_html/test.php on line 3
```

**Comment by roykho** [comment]
Yeah I don't see any file generated for it. Another words no `php7.2_errors.log` in the `/www/vvv/log/php/` folder

**Comment by tomjn** [comment]
if you reprovision, does it complain about that file at all? And can you confirm `php.ini` has error logging turned on?

`config/php-config/php7.2-fpm.conf` sets the error log file on line 32 and the php 7.2 ini file has `error_reporting = E_ALL | E_STRICT`

**Comment by roykho** [comment]
Yeah everything seems to be normal. I didn't touch any of the PHP.ini configuration. Also as I mentioned, everything worked prior to the update.

At this point, I am just gonna deal with using `wp-content/debug.log` because it seems every time I update VVV, this happens.

Thanks for the help nonetheless!
