### ISSUE TITLE
VVV 3 and Duplicator plugin

### ISSUE THREAD

**Issue by csdev-nl** [Varying-Vagrant-Vagrants/VVV#1839]
Since I have updated to VVV 3, the WordPress plugin Duplicator (by Snapcreek) no longer works. I always use this plugin to transfer a site when (local) development is finished. 

The problem is that Duplicator does successfully generate the package(s), but once the package is downloaded, the file cannot be found (it seems VVV deletes the file just before it can be downloaded). Is there some (major) change in file management in VVV 3 that prevents Duplicator from working properly?

**Comment by tomjn** [comment]
Not that I'm aware of, VVV doesn't handle files itself, it sets up the
virtual machine so everything is working. What you do with it beyond that
is up to you, it's a standard Ububtu 18 VM so there's nothing in VVV that
would go on and delete files outside of a provision

Can you take a look at your php error log and see if anything is out of
place? Can you share the details from the issue template? OS/Virtualbox
version/vagrant version etc

Also are you sure the file actually gets created? Have you opened an issue
with duplicator support?

**Comment by csdev-nl** [comment]
Offtopic: wow, that's quick support - awesome!

The files do actually get created (I can find them in Finder), but it seems the files are not added to the archive. The log is found below. 

OS: Mac OS Mojave
Vagrant: v2.2.4,	
VirtualBox: v5.2.26r128414

[dup_39f6110e6146a802cce09fc0ffa70a29.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/3256387/dup_39f6110e6146a802cce09fc0ffa70a29.log)

**Comment by tomjn** [comment]
Hmm give me a bit to check through the log, but glad to hear the precursor
stuff gets created. It could be that it fails to archive them and you
either never get the zip file or it's 0 bytes in size, let's find out :)

**Comment by tomjn** [comment]
@csdev-nl I wasn't expecting a duplicator log, but a PHP error log.

The duplicator log indicates it successfully created zip files, but I'm unfamiliar with what the logs output means. Have you raised this with Duplicator support? They'll understand better what this means and what went wrong

As an aside, you don't need to download the file from the website running on VVV, remember it's a local dev environment, it's just sitting on your hard drive in the snapshots folder

**Comment by csdev-nl** [comment]
@tomjn thanks for your reply. Took me a while to get back to you (everyday business tends to get you caught up...). 

I have contacted the Duplicator support and a fix is not available (yet). I did find a workaround by compressing to a .daf archive rather than a .zip archive and grabbing the files manually from the wp-snapshots folder - which solves my problem for now. 

So I guess this thread can be closed.

**Comment by tomjn** [comment]
> I have contacted the Duplicator support and a fix is not available (yet). I did find a workaround by compressing to a .daf archive rather than a .zip archive and grabbing the files manually from the wp-snapshots folder - which solves my problem for now.

Good to know you found a work around, and thanks for getting back to us :D

We had an issue with corrupt page caches that prevented WP updates from working, and fixed it by switching boxes. In the process several other issues went away regarding renaming files in mysql, and I suspect that this issue too might have been resolved, so your workaround might not be necessary any more, *fingers crossed*, if you can confirm that it'd be a huge help :)

**Comment by csdev-nl** [comment]
> > I have contacted the Duplicator support and a fix is not available (yet). I did find a workaround by compressing to a .daf archive rather than a .zip archive and grabbing the files manually from the wp-snapshots folder - which solves my problem for now.
> 
> Good to know you found a work around, and thanks for getting back to us :D
> 
> We had an issue with corrupt page caches that prevented WP updates from working, and fixed it by switching boxes. In the process several other issues went away regarding renaming files in mysql, and I suspect that this issue too might have been resolved, so your workaround might not be necessary any more, _fingers crossed_, if you can confirm that it'd be a huge help :)

Thanks for the update. I will test it somewhere in coming 2 weeks (I'm away from work/keyboard for a while).

**Comment by csdev-nl** [comment]
Hi Tom, I just updated VVV and re-tested, but sadly, to no avail. 
Note: I only updated by pulling the latest version from the master branch, is that correct?

**Comment by tomjn** [comment]
No, test with the developer branch, that had the fixes we want to test,
always the developer branch. You will need to destroy your VM to test it
correctly
