### ISSUE TITLE
Nginx default HTML

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1846]
When first provisioning, the default Nginx HTML shows up before the dashboard is provisioned, the files are in `/usr/share/nginx/html` as `50x.html` and `index.html`

It would be nice to replace these or pre-seed them with VVV versions that just say provisioning hasn't finished yet, please be patient

**Comment by Mte90** [comment]
Pr: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2345
