### ISSUE TITLE
Error when provisioning: "failed to fetch .../galera-3/... Connection failed"

### ISSUE THREAD

**Issue by ryandoving** [Varying-Vagrant-Vagrants/VVV#1850]
## Expected Behavior

Provision should complete successfully.

## Current Behavior

Provision fails.

## Steps to Reproduce (for bugs)

1. Pull latest `develop` branch
2. `vagrant up`
3. Provisioning fails.

https://gist.github.com/ryandoving/dbdd19f1a6c3ed61be1e5917e926d23a

## Context

I cannot provision a new site.

## Your Environment

* VVV version: 3.0.0
* VVV Git Branch: develop
* Vagrant version: 2.2.4
* VM Provider name: Virtualbox
* VM Provider version: 6.0.4r128413
* Operating System and version: Windows 10 Pro

**Comment by tomjn** [comment]
```
 default: Failed to fetch http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu/pool/main/g/galera-3/galera-3_25.3.26-bionic_amd64.deb Connection failed [IP: 85.13.241.50 80]
```

That Apt mirror didn't work for you on that occasion. I'd recommend reprovisioning, but other than verifying that your internet connection, your networking hardware, and that all the hops on the chain between you and coreix.net are stable, and that there are no issues at coreix.net, there's nothing that can be done from our end to help. `apt` is a standard tool on a lot of Linux machines, it isn't something maintained by anybody here.

The unfortunate part is that you can probably ping coreix.net from your host, and it'll work fine, unless you continuously ping you won't have a good idea of their uptime for that specific part of the service `apt` requires. "But it's accessible from X" is a very reasonable but unhelpful thing to ask :(

Perhaps if you reprovision it will choose a different more reliable mirror. If it keeps happening contact your ISP

**Comment by tomjn** [comment]
For reference, the file is listed in http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu/pool/main/g/galera-3/ and I could download it from Firefox. This is either network instability at your end, packet loss of some kind at your ISP, or server troubles at coreix.net. It could even be something your ISP is doing to your connection after a lot of initial downloads and bandwidth, but I couldn't say

**Comment by ryandoving** [comment]
I tried provisioning multiple times and it always fails on the same file. I tried from two different internet connections but always had the same result. Finally, I tried the entire procedure from scratch on another computer and it provisioned successfully the first time. I don't know what caused the failure, but it seems to be an issue on my end. Thanks for the help!
