### ISSUE TITLE
php5.6-fpm.sock mysteriously gone

### ISSUE THREAD

**Issue by davidrhoderick** [Varying-Vagrant-Vagrants/VVV#1853]
## Expected Behavior

I have provisioned some sites to use PHP 5.6 to match the servers they are hosted on and they should work and have been until today, when I get a "502 Bad Gateway" error looking up those servers.

## Current Behavior

I haven't changed any settings nor updated anything (VVV, Vagrant, or the Ubuntu VM are all the same) and all of a sudden I'm getting a missing php5.6-fpm.socket file error in the nginx-access.log.  The default location is `/var/run/php5.6-fpm.socket` but when I SSH into the server, I can see that the file is no longer there but that a `php7.2-fpm.sock` and an empty `php/` directory exist there.

## Possible Solution

Adding the socket, or reinstalling PHP 5.6, should fix the issue but I'm wondering if that will require additional work to correctly link everything or if it'll just work if I install PHP 5.6.  Plus, the bigger issue to me is why that file is gone now and after not changing a thing.

Another potential solution (what I probably should do) is upgrade both sites and their live servers to PHP 7.2.  I may do this anyways but in the future, users may still want to select different PHP versions even if they aren't EOL.

## Steps to Reproduce (for bugs)
1.  I originally set up and accessed the server with PHP 5.6 4 days ago and it was working fine.
2.  The only change I made since then was to provision two new sites in my vvv-custom.yml.  I have since checked the vvv-custom.yml formatting, tried skipping provisioning on those new sites, and removed their entries completely.  None of those attempts to fix the problem have been successful.
3.  I returned to the site today and got the 502 Gateway error.

## Context

I was unable to make changes to a site that has only a live server (no staging server) set up therefore I had to hack together a solution on the live server that isn't appropriate for posterity.  Like I stated above, there may be needs to test PHP versions that are or are not EOL and if sockets go missing mysteriously, that may be impossible in a reliable way. 

## Your Environment

* VVV version: 2.6.0
* VVV Git Branch: master
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0.6
* Operating System and version: Pop!_OS 19.04

**Comment by tomjn** [comment]
@davidrhoderick can I see your `vvv-custom.yml`? If you specify the incorrect thing in Nginx upstream, or you ask it to use a PHP version but didn't add it to utilities, this can happen

**Comment by davidrhoderick** [comment]
Sure:

        ---

    # IMPORTANT !!!!!!!!!
    # Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


    # This file is a YAML formatted file. YAML indenting is done in spaces not
    # tabs, and whitespace is significant. If you don't stick to this, it will
    # fail on provision

    #
    # IMPORTANT, if you change this file, you have to reprovision,  no exceptions
    # vagrant reload --provision
    #

    # These are your websites, and their names map on to the folders they're
    # located in. See the docs for how to define these, and what all the keys
    # and options are
    sites:
      # frontitytestone
      frontitytestone:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - frontity.test

      # decibeldatabase
      decibeldatabase:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - decibeldatabase.test

      # iSectors
      isectors:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - isectors.test
          
      # Martha's Vineyard Museum
      mvm:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - marthasvineyardmuseum.test

      # Pine (for Verdant)
      pine:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        skip_provisioning: true
        hosts:
          - pine.test


      # Battle Harbour
      battleharbour:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - battleharbour.test

      # Inkwell Clothing
      inkwellclothing:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        nginx_upstream: php56
        hosts:
          - inkwellclothing.test

      # AcceptU
      acceptu:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - acceptu.test
        nginx_upstream: php56

      # Abundance Wealth Planning
      abundancewealthplanning:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - abundancewealthplanning.test

      # AbundanceWP
      abundancewp:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - abundancewp.test
          
      # The Exodus Institute
      theexodusinstitute:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - theexodusinstitute.test

      # Barry Stringfellow
      barrystringfellow:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - barrystringfellow.test

      # Martha's Vineyard Village at Home
      vvah:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - vvah.test

      # National Widowers' Organization
      nationalwidowers:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        hosts:
          - nationalwidowers.test

      # JHL Projects
      fluidsense:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        skip_provisioning: true
        hosts:
          - fluidsense.test
        nginx_upstream: php71

      ecobilge:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        skip_provisioning: true
        hosts:
          - ecobilge.test
        nginx_upstream: php71

      # NCHRA projects
      hrwest:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        skip_provisioning: true
        hosts:
          - hrwest.test

      nextconcepthrmagazine:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        skip_provisioning: true
        hosts:
          - nextconcepthrmagazine.test

      # Wedding theme
      wedding:
        repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
        skip_provisioning: true
        hosts:
          - wedding.test

    # Utilities are system level items rather than sites, that install tools or packages
    # the core utilities install tools such as phpmyadmin
    utilities:
      core:
        - php56
        - php71
        - memcached-admin
        - opcache-status
        - phpmyadmin
        - webgrind
        - trusted-hosts
        - tls-ca

    # vm_config controls how Vagrant provisions the virtual machine, and can be used to
    # increase the memory given to VVV and the number of CPU cores. For WP core development
    # we recommend at least 2GB ( 2048 )
    # It can also be used to override the default provider being used within Vagrant.
    # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
    # as Vagrant currently restricts you to one provider per machine
    # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
    vm_config:
      memory: 2048
      cores: 2
      # provider: vmware_workstation

**Comment by Mte90** [comment]
also you are using a not supported VVV version

**Comment by davidrhoderick** [comment]
@Mte90 Which versions of VVV are supported?  Where does one find this information?

**Comment by tomjn** [comment]
@davidrhoderick VVV 3 should work, if you're using VVV 2.x then you won't be able to successfully provision. The PHP packages it needs are no longer available.

To get VVV 2 to work, you're going to need to compile the PHP packages from scratch for Ubuntu 14, then publish the packages and add your mirror to the VVV provisioners in a fork. Suffice to say it's easier to move to Ubuntu 18, which is what we did in VVV 3. I would expect that if you were to send over a log of a reprovision, it would complain about missing PHP 5.6 and 7.1 packages

So as long as you're using VVV 2, you can't install additional PHP versions. The only reason you have PHP at all is because you set VVV2 up before Ubuntu 14 reached end of life. If you tried to recreate your VM it wouldn't work. You **need** to update to VVV 3, it's unavoidable.

So when you're ready to update:

 - back up your database
 - destroy your VM with a `vagrant destroy`
 - clean out the `.vagrant` folder
 - update your copy of VVV to the latest
 - do a `vagrant up --provision`
 - restore your backed up database

VVV should have backed up your database on each `vagrant halt` already, and put the result in the `database` folder under one of the subfolders as `sql` files

**Comment by davidrhoderick** [comment]
@tomjn Thanks for the information; I upgraded to VVV 3 and one of those PHP 5.6 sites is working (the other has a DB issue that is unrelated), so that is probably the issue.  In the future, is there somewhere I can sign up to get notified when these major VVV updates are pushed out?

**Comment by tomjn** [comment]
@davidrhoderick we have the main website, but it's best to just pull down the latest and greatest via `git pull` and stick to the `master` branch on a regular basis
