### ISSUE TITLE
Allow `db_backup` to be run manually when backup is disabled for halt/suspend/destroy

### ISSUE THREAD

**Issue by petertoi** [Varying-Vagrant-Vagrants/VVV#1859]
## Expected Behavior

I think the option to disable DB backups on halt/suspend/destroy is great but I would still like the ability to run the backups manually if desired without having to reprovision the box with the setting updated.

## Current Behavior

Currently, any calls to the `db_backup` shell script are aborted due to the conditional check in this script. The documentation for the flag in `vvv-config.yml` speaks only to whether or not the DBs should be backed up during vagrant box state changes so I believe this conditional check should be pulled up to the `vagrant_halt` shell script.

## Possible Solution

Pull the parsing of vvv-config.yml or vvv-custom-yml up to `vagrant_halt` and run the conditional checks there before calling `db_backup`.

## Steps to Reproduce (for bugs)

0. From a fresh install
1. Set `general.db_backup: false` in `vvv-config.yml`
2. `vagrant up --provision`
3. `vagrant ssh`
4. `db_backup`
5. Script runs but exits early

## Context

See above.

## Your Environment

* VVV version: v3.0.0
* VVV Git Branch: master
* Vagrant version: v2.2.4
* VM Provider name: VirtualBox
* VM Provider version: v6.0.8r130520
* Operating System and version: OS X Mojave 10.4

**Comment by tomjn** [comment]
You don't need to use that specific script to do the import, you can instead copy it and run your own script without the check, e.g. `vagrant ssh -c "petertol_db_backup"`

Otherwise, moving it to `vagrant_halt` makes sense, but the check would also need adding to `vagrant_destroy`

**Comment by tomjn** [comment]
I see you made the change in https://github.com/petertoi/VVV/commit/f7145186f9cb7fe25c7ff32bde03b3cb3403652c, can you make a pull request and include the change in `vagrant_destroy` and update the changelog?

**Comment by petertoi** [comment]
Hi @tomjn - you bet. PR is already underway. Cheers!

**Comment by petertoi** [comment]
PR: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1860
