### ISSUE TITLE
No Dashboard at http://vvv.test - default Nginx page - other WP sites load OK

### ISSUE THREAD

**Issue by palomnik** [Varying-Vagrant-Vagrants/VVV#1864]
Everything appears to load correctly.  one.wordpress.test and two.wordpress.test load OK.
ssh works using "vagrant ssh".

## Expected Behavior

I'm expecting to see some sort of page at vvv.test

## Current Behavior

when going to http://vvv.test, I get the default Nginx page as follows:

"Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx."

## Possible Solution

Not sure where to hunt for this problem.  The "default" directory is there, apparently with all of the files.  There is probably something wrong with the Nginx config, but I couldn't tell.

## Steps to Reproduce (for bugs)

Fresh install of vagrant
rebooted
Fresh install of the plugin
rebootted
Fresh install of VVV

## Your Environment

MacOSX Mojave (on MacBook Air) 10.14.4
Virtualbox Version 5.2.30 r130521 (Qt5.6.3)
Vagrant 2.2.4
VVV Version 3.0.0

**Comment by tomjn** [comment]
Hello!

Without seeing a full log of a provision there's very little that can be
done to help, can you get me that via a gist or paste bin?

**Comment by palomnik** [comment]
OK, I did a destroy and then up, which re-set everything up......and this time it worked.  I guess I can diff the logfiles to see what happened differently this time.  If I get time to do that I'll post it here.

**Comment by tomjn** [comment]
That's ok, lets close this out and reopen if it happens again :)
