### ISSUE TITLE
MariaDB installation creates errors in the log of a fresh installation

### ISSUE THREAD

**Issue by kmgalanakis** [Varying-Vagrant-Vagrants/VVV#1865]
@tomjn as per your request I'm creating a new ticket.

While making a fresh clone of the repo and executing `vagrant up --provision`, I'm getting the following output.

[vagrant.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/3303065/vagrant.log)

Notice that from line 1856 errors start to kick in. More errors are following this line.

Then, I halted the machine and run again `vagrant up --provision`. Here is the log 

[vagrant_2.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/3303085/vagrant_2.log)

After then, when loading `http://vvv.test`, I'm getting the default nginx page.

**Comment by benlumia007** [comment]
it failed, the provision never finished. can you diabled the shared_db_type: false, i think that's the name of it.

**Comment by kmgalanakis** [comment]
It's the `db_share_type` setting and yes, by switching it to `false` the issue is resolved.

But as per Tom's request, I gave the full logs for both cases.

**Comment by kmgalanakis** [comment]
What is really strange to me, though, is that on my other laptop, the VM can provision properly without the need of `db_share_type`. What could be the difference between the two? Is there a way we can debug this?

**Comment by benlumia007** [comment]
have u tried to git pull on the other one, it could be the version is different?

**Comment by kmgalanakis** [comment]
Yes, I got fresh clones for both instances!

**Comment by Mte90** [comment]
I think that was a problem with the db-share files on your machine that was conflicting someway, for that reason on disabling was working because there was a new generation of them.
Maybe if you remove the folder on `database/data/*` the provision will works.

**Comment by kmgalanakis** [comment]
This issue occurs even in fresh repo clones, so the problem is not the db-share files.

**Comment by tomjn** [comment]
Is this still an issue?

**Comment by kmgalanakis** [comment]
Not really. I'm closing this.
