### ISSUE TITLE
Contributor Guidelines missing styles

### ISSUE THREAD

**Issue by michaeltieso** [Varying-Vagrant-Vagrants/VVV#1878]
Small thing but the [contributor guidelines](https://varyingvagrantvagrants.org/docs/en-US/contributing/) are missing the docs styles, like the sidebar. Is there a way to contribute to the docs?

**Comment by Mte90** [comment]
Of course! You can do it on https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/
I am working on improving the docs so if you have any ideas for other stuff let me know!
