### ISSUE TITLE
Incorrect permissions in /vagrant

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1886]
## Expected Behavior
File `/vagrant/vvv-custom.yml` is readable by www user.

## Current Behavior
File `/vagrant/vvv-custom.yml` is readable only by root.

## Steps to Reproduce (for bugs)
```
vagrant@vvv:/vagrant$ ls -l
total 12
lrwxrwxrwx 1 root root   17 Jun 27 22:34 certificates -> /srv/certificates
-rw-r--r-- 1 root root   16 Jun 27 22:34 provisioned_at
-rw-r--r-- 1 root root    5 Jun 27 22:34 version
-rw------- 1 root root 1483 Jun 27 22:34 vvv-custom.yml
````

## Your Environment

* VVV version: git
* VVV Git Branch: develop
* Vagrant version: 2.2.5
* VM Provider name: VirtualBox
* VM Provider version: 6.0.8
* Operating System and version: macOS 10.14.5

**Comment by benlumia007** [comment]
those permissions are correct, when you are at /vagrant, these files don't get edited by the vagrant user, its provisioned beforehand. 

by default, the /vagrant is disabled in the vagrantfile and its re-created with root, along with the files above. u shouldn't be editing this inside of vm, rather than the host.

**Comment by paulschreiber** [comment]
This prevents the dashboard (https://vvv.test) from working correctly:
![image](https://user-images.githubusercontent.com/86784/60307802-17d8f180-9914-11e9-84ee-1240b0d6a750.png)

**Comment by benlumia007** [comment]
So, I just checked mine and have the same version as 3.1.0, It seems like I don't have that problem. 
![Screenshot from 2019-06-27 17-13-10](https://user-images.githubusercontent.com/11844123/60308682-e43f9c80-98fe-11e9-9819-e041c6ce8a4b.png)

looks fine to me.

**Comment by benlumia007** [comment]
maybe try a reload --provision and see if that fixes it. it could just be a bad provisioning

**Comment by tomjn** [comment]
Nope, it needs a `chown` to be done in a provisioner

**Comment by benlumia007** [comment]
`chown -R vagrant:vagrant /vagrant` should do it

**Comment by benlumia007** [comment]
@Mte90 
I can do this one if you up for it.

**Comment by Mte90** [comment]
ok, is not assigned to someone so you can do it and later we will test it

**Comment by benlumia007** [comment]
I'll work on this today

**Comment by benlumia007** [comment]
for some reason after creating a new branch locally and modify, I can't push my changes

```
ERROR: Permission to Varying-Vagrant-Vagrants/VVV.git denied to benlumia007.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tomjn** [comment]
That's expected, you'd have to fork and submit a PR that way

**Comment by benlumia007** [comment]
I have done and added a PR. 

Thanks

**Comment by benlumia007** [comment]
#1891 has been merged

**Comment by paulschreiber** [comment]
Still broken in 3.1:
```
vagrant@vvv:~$ ls -al
total 72
drwxr-xr-x 9 vagrant vagrant 4096 Aug  1 17:19 .
drwxr-xr-x 4 root    root    4096 Aug  1 15:50 ..
-rw------- 1 vagrant vagrant  282 Aug  1 15:50 .bash_aliases
-rw-r--r-- 1 vagrant vagrant  220 Jul 31 15:59 .bash_logout
-rw-r--r-- 1 vagrant vagrant 2214 Aug  1 15:50 .bash_profile
-rw-r--r-- 1 vagrant vagrant 3771 Jul 31 15:59 .bashrc
drwx------ 3 vagrant vagrant 4096 Aug  1 15:54 .cache
drwxr-xr-x 4 vagrant vagrant 4096 Aug  1 17:19 .config
drwx------ 3 vagrant vagrant 4096 Aug  1 15:50 .gnupg
drwxr-xr-x 3 vagrant vagrant 4096 Aug  1 15:54 .local
-rw------- 1 root    root     292 Aug  1 15:54 .my.cnf
drwxr-xr-x 4 vagrant vagrant 4096 Aug  1 17:20 .npm
-rw-r--r-- 1 vagrant vagrant  807 Jul 31 15:59 .profile
drwx------ 2 vagrant vagrant 4096 Jul 31 15:59 .ssh
drwxr-xr-x 3 vagrant vagrant 4096 Aug  1 15:54 .subversion
-rw-r--r-- 1 vagrant vagrant    5 Aug  1 15:50 version
-rw------- 1 vagrant vagrant 1016 Aug  1 15:50 .vimrc
-rw------- 1 vagrant vagrant 1507 Aug  1 15:50 vvv-custom.yml
```

**Comment by Mte90** [comment]
as other ticket, did you tried with a vagrant destroy

**Comment by paulschreiber** [comment]
Yes, I updated to 3.1.0 (`git co 3.1.0`), and then ran `vagrant destroy and vagrant up --provision`.

**Comment by tomjn** [comment]
So ownership is set appropriately here:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L525

But permissions doesn't change, it needs a `chmod`, what should the permissions be?

**Comment by benlumia007** [comment]
please note that this
`config.vm.provision "file", source: "#{vagrant_dir}/vvv-custom.yml", destination: "/home/vagrant/vvv-custom.yml"`
gets copy from source to destination `/home/vagrant/`, then, it gets copy to the /vagrant folder

```
# cleanup
rm -rf /vagrant/* 
mkdir -p /vagrant
cp -f /home/vagrant/vvv-custom.yml /vagrant
```
chown -R should relace root with vagrant inside of /vagrant folder.

**Comment by tomjn** [comment]
The ownership is correct it’s the file permissions that are the problem

**Comment by benlumia007** [comment]
similar to grunt issue, if some users' environment works fine with these settings and works every time, great, but the problem, we don't know who else has this is a problem and so far is only been, one user. if there were more users, we be hearing about it. 

i have managed to test with root and vagrant without chmod and it works fine.

**Comment by tomjn** [comment]
Yes but what’s the ownership and file permissions on your machine? It’s
clearly not working for Paul, so we need to know what those permissions
should be

**Comment by benlumia007** [comment]
I'll give you that information shortly.

**Comment by benlumia007** [comment]
```
drwxr-xr-x 9 vagrant vagrant 4096 Aug  2 15:28 .
drwxr-xr-x 4 root    root    4096 Aug  2 15:12 ..
-rwxr-xr-x 1 vagrant vagrant  282 Aug  2 15:13 .bash_aliases
-rw-r--r-- 1 vagrant vagrant  220 Aug  1 16:28 .bash_logout
-rwxr-xr-x 1 vagrant vagrant 2214 Aug  2 15:13 .bash_profile
-rw-r--r-- 1 vagrant vagrant 3771 Aug  1 16:28 .bashrc
drwx------ 3 vagrant vagrant 4096 Aug  2 15:23 .cache
drwxr-xr-x 3 vagrant vagrant 4096 Aug  2 15:23 .config
drwx------ 3 vagrant vagrant 4096 Aug  2 15:13 .gnupg
drwxr-xr-x 3 vagrant vagrant 4096 Aug  2 15:23 .local
-rwxr-xr-x 1 root    root     292 Aug  2 15:25 .my.cnf
-rw-r--r-- 1 vagrant vagrant  807 Aug  1 16:28 .profile
drwx------ 2 vagrant vagrant 4096 Aug  1 16:28 .ssh
drwxr-xr-x 3 vagrant vagrant 4096 Aug  2 15:23 .subversion
-rwxr-xr-x 1 vagrant vagrant 1016 Aug  2 15:13 .vimrc
drwxr-xr-x 3 vagrant vagrant 4096 Aug  2 15:28 .wp-cli
-rw-rw-r-- 1 vagrant vagrant    5 Aug  2 15:13 version
-rw-rw-r-- 1 vagrant vagrant 3430 Aug  2 15:13 vvv-custom.yml
```

**Comment by benlumia007** [comment]
looks like is 664

**Comment by benlumia007** [comment]
plese check /vagrant folder too

```
drwxr-xr-x  2 vagrant vagrant 4096 Aug  2 15:13 .
drwxr-xr-x 24 root    root    4096 Aug  2 15:13 ..
lrwxrwxrwx  1 vagrant vagrant   17 Aug  2 15:13 certificates -> /srv/certificates
-rw-r--r--  1 vagrant vagrant   16 Aug  2 15:13 provisioned_at
-rw-r--r--  1 vagrant vagrant    5 Aug  2 15:13 version
-rw-r--r--  1 vagrant vagrant 3430 Aug  2 15:13 vvv-custom.yml
```

**Comment by benlumia007** [comment]
I would suggest vagrant destroy, back up the folder, reclone the project and try again.

**Comment by tomjn** [comment]
That’sa pretty destructive way to do things, we should chmod instead and
then it only needs a git pull and a reprovision

**Comment by benlumia007** [comment]
I have check macOS, Windows, and Linux, all have the same permissions for both folders and files.

**Comment by benlumia007** [comment]
im not saying in a way to be destructive, of course we need to change it with chmod. i was just saying that, way without using chmod, because we don't have the problem.  but yes, we would need to chmod.

**Comment by benlumia007** [comment]
we should only change the vvv-custom.yml in /vagrant instead since that's where the shyaml and provision gets the information.

**Comment by tomjn** [comment]
In 3.2 I think we should move these config files to `/srv/config` or `/srv/provision` to avoid the file copy in the first place.

But in the meantime, we need to run `chmod` on `/vagrant/vvv-custom.yml`

**Comment by benlumia007** [comment]
what's the purpose of not using /vagrant in the first place.

**Comment by tomjn** [comment]
Anything involving `/vagrant` is only there for backwards compatibility reasons. Because we no longer mount that folder, there was no way to read the config file, so it was copied into place to keep the dashboard etc working
