### ISSUE TITLE
Newly Created Sites Don't Show In www Folder

### ISSUE THREAD

**Issue by darrylmorley** [Varying-Vagrant-Vagrants/VVV#1888]
No

## Expected Behavior

On creation of a new site, the root folder should be locate under */VVV/www
## Current Behavior

The folder is not visible and does not display under hidden items. However can be seen when searched for in File Explorer using the search bar, and can be seen using CMD.

## Context

I am unable to edit the files located in the folders..

## Your Environment

* VVV version:  3.1.0
* VVV Git Branch:  master
* Vagrant version: 2.2.5
* VM Provider name: 
* VM Provider version: Virtual Box 6.0
* Operating System and version: Windows 10 1903
![Capture1](https://user-images.githubusercontent.com/20406137/60329165-b94d5b00-9987-11e9-8439-2ea2503cc8b7.PNG)
![Capture2](https://user-images.githubusercontent.com/20406137/60329170-bc484b80-9987-11e9-85c5-0fe0dafc5d4a.PNG)

**Comment by darrylmorley** [comment]
Me being stupid :)

**Comment by tomjn** [comment]
@darrylmorley what happened?

**Comment by darrylmorley** [comment]
@tomjn I had two VVV folders at seperate locations. I was trying to work on the wrong one.

**Comment by tomjn** [comment]
oh dear, keep in mind you can keep everything in the one VM so you should only need a single install
