### ISSUE TITLE
SSH in vvv-init: Host Key verification failed

### ISSUE THREAD

**Issue by mrmadhat** [Varying-Vagrant-Vagrants/VVV#1890]
## Expected Behavior

I'm creating a custom site template, I want to use ssh in vvv-init.sh to connect to another server, make a backup then use scp to download that backup.

I would like to run a command by ssh and the command execute e.g 

```
#!/usr/bin/env bash

ssh user@url "pwd" -P 2020
```

would return `/home/user/public_html` (just an example)

## Current Behavior

Running the above gives me an error "Host Key verification failed"

If I run the command on my local machine it works, if I log into vagrant via `vagrant ssh` and run the command it works. 

## Steps to Reproduce (for bugs)

1. Create a custom site template by forking the example vvv site template
2. Delete everything in the vvv-init.sh file except `#!/usr/bin/env bash`
3. Add `ssh user@url "pwd" -P 2020` to vvv-init.sh using details of a private key you already have setup on your local machine (I also created a second key on the vagrant machine itself in an attempt to get this to work but I'm not sure that's needed)
4. Provision vvv 

https://gist.github.com/mrmadhat/d5b8a1bb07af689ed2cada7a6a9dcaab

## Context

I use vvv for all local development. I want an easy/automated way to take a live site and copy it to my local machine. This would allow me to delete a site from my local machine when no development is happening (freeing up disk space on my mac) and just provision the site when it is needed again.

## Your Environment

* VVV version:  v3.1.0
* VVV Git Branch:  develop
* Vagrant version: 2.2.5
* VM Provider name: Virtualbox 
* VM Provider version: 5.2.20
* Operating System and version: Mac Mojave 10.14

**Comment by Mte90** [comment]
Usually connect for the first time do a new domain require a confirmation for the hosts in ssh.
Like at https://www.thegeekdiary.com/how-to-fix-the-error-host-key-verification-failed/

**Comment by mrmadhat** [comment]
I did think that this could be the issue but in /home/vagrant/.ssh/config I've disabled hostkey checking:

```
Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```

**Comment by tomjn** [comment]
If you've never connected to a host before you had to accept and verify the signature the first time, after which it's added to the known hosts file. Your problem is that this has never happened for that host, so it can't ask you to verify the authenticity

This isn't really a VVV issue as it impacts all SSH systems, even MacOS, and it's how it's supposed to work. A google suggests this article might help:

https://www.techrepublic.com/article/how-to-easily-add-an-ssh-fingerprint-to-your-knownhosts-file-in-linux/

**Comment by benlumia007** [comment]
sometimes deleting the known_hosts file on any operating systems can help too.

**Comment by mrmadhat** [comment]
Thanks for the quick responses and help, @tomjn your suggestion worked 😄 

I'm still having an issue, running `vagrant reload --provision`  everything works as expected but if I run `vagrant reload --provision-with=site-sitename` I'm getting the following error:

```
default: Reloading Nginx
default: nginx.service is not active, cannot reload.

The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.
```

**Comment by tomjn** [comment]
You should only run --provision-with on a vagrant provision, if you do it
on a reload then things won't be set up for provisioners to run

**Comment by mrmadhat** [comment]
I was having issues with ssh-keyscan refusing the connection to the server, it turns out that the port needs to be specified when not using the default 22:

ssh-keyscan -p ${SSH_PORT} -H ${SSH_HOST} >> ~/.ssh/known_hosts

Adding this here as a reminder to myself and for anyone else who may have the same issue.
