### ISSUE TITLE
Passing array to vvv-init.sh from vvv-custom.yml

### ISSUE THREAD

**Issue by mrmadhat** [Varying-Vagrant-Vagrants/VVV#1893]
I'm creating a custom provision script for VVV. One of the tasks in the vvv-init.sh file is to login to a remote server via ssh and take a backup of the contents of that server.

I would like to give users the option to exclude certain directories from the backup via the vvv-custom.yml file.

I've tried the following:

### vvv-custom.yml

```
test-site:
    # omitted for brevity
    custom:
      tar_excludes:
        - wp-content/infinitewp
        - staging
```

### vvv-init.sh

```
TAR_EXCLUDES=`get_config_value 'tar_excludes' 'false'`

echo ${TAR_EXCLUDES}

# - wp-content/infinitewp - staging

# I want to use the value of TAR_EXCLUDES here instead of hardcoding
exec_ssh_cmd "tar -jcvf ${TAR_NAME} ${WP_PATH}/* --exclude=\"${WP_PATH}/staging\" --exclude=\"${WP_PATH}/wp-content/infinitewp\" --exclude=\"*.tar\" --exclude=\"*.tar.gz\" --exclude=\"*.zip\" --exclude=\"*.tmp\" --totals; exit;"
```
I've tried using:

```
IFS='- ' read -ra ADDR <<< "$TAR_EXCLUDES"
for i in "${ADDR[@]}"; do
    echo $i
done
```
from this [question](https://stackoverflow.com/questions/918886/how-do-i-split-a-string-on-a-delimiter-in-bash) but it doesn't work, it produces:

```
wp
content/infinitewp
staging
```

When searching how to include spaces I've read it's not a good idea to use IFS/string splitting.

How can I use a variable from vvv-custom with multiple values in vvv-init.sh?

**Comment by tomjn** [comment]
🤔 

If it helps, `get_config_value` is a wrapper around `shyaml`, so you could do it that way,

```
cat test.yaml | shyaml get-values subvalue.things
```

Which returns a list of items on newlines, so something like this:


```
cat vvv-custom.yml | shyaml get-values sites.test-site.custom.tar_excludes
```

Which should give output like this:

```
wp-content/infinitewp
staging
```

You might need to wrap the first one in strings so it's parsed correctly, then instead of `echo`, append it to a variable:

s="${s}test2"

```
excludes=""
IFS='- ' read -ra ADDR <<< "$TAR_EXCLUDES"
for i in "${ADDR[@]}"; do
    excludes="${excludes} --exclude=\"${i}\""
done
```

At this point though, could you pass a comma separated list instead of multiple `--exclude` options? If you're creating a tarball to download, it might be more efficient to do an `rsync` command and sync down

**Comment by mrmadhat** [comment]
> At this point though, could you pass a comma separated list instead of multiple --exclude options? If you're creating a tarball to download, it might be more efficient to do an rsync command and sync down

`rsync` is perfect for what I'm looking to do, I knew it could sync one folder to another but didn't realise it could do it from remote to local and vice versa. From what I can see `rsync` doesn't allow a comma separated list for `--exclude` but for my use accepting a comma separated list from the user via the vvv-custom file works.

### vvv-custom.yml

``` 
testsite:
    custom:
        backup_exclude: wp-content/infinitewp,staging
```

### vvv-init.sh

```
EXCLUDES=`get_config_value 'backup_exclude' 'false'`

backup_excludes=""

if [ $EXCLUDES ]; then
    IFS=',' read -ra ADDR <<< "$EXCLUDES"
        for i in "${ADDR[@]}"; do
            backup_excludes="${backup_excludes} --exclude=\"${i}\""
        done
fi

rsync -azvhu ${backup_excludes} ${SSH_USER}@${SSH_HOST}:${WP_PATH} ./public_html
```

Thanks again for all your help @tomjn
