### ISSUE TITLE
Problem updating Wordpress

### ISSUE THREAD

**Issue by fabri01** [Varying-Vagrant-Vagrants/VVV#1895]
When I try to update the wordpress installation i get this error 

Parse error: syntax error, unexpected '}', expecting end of file in /srv/www/innov8studio/public_html/wp-admin/includes/file.php on line 2652

Sometimes I solved this by editing file.php by removing the "}" and the paste it again.
But is not very practical because I've to do that every time I update wordpress or plugin.

I don't know if is related but I also  get this error:

Parse error: syntax error, unexpected 'action' (T_STRING) in /srv/www/myblog-test/public_html/wp-login.php on line 1172

Any ideas? Thanks in advance!
## Environment

* VVV version: 3.0.0
* VVV Git Branch:  master
* Vagrant version: 2.2.5
* VM Provider name:  VirtualBox
* VM Provider version: 5.2
* Operating System and version: Mac OS Mojave

**Comment by Mte90** [comment]
It is something that we already saw, if you turn off and on VVV, the problem will disappear.
The next version, that we are working on, will fix the problem.

**Comment by Gemfruit** [comment]
Just wanted to verify that the above quick fix works - I experienced the exact issue, and found the same solution.

**Comment by fabri01** [comment]
Yes, at the moment turn off and of VVV is enough.

**Comment by rodrigoprimo** [comment]
For future reference, more details and workaround for this issue in #1819

**Comment by tomjn** [comment]
Both `master` and `develop` are using a different base box now that doesn't have this bug. If you encounter it, backup your database, `vagrant destroy`, pull down the latest version of VVV, and reprovision
