### ISSUE TITLE
Missing box for vmware provider - puphpet/ubuntu1804-x64

### ISSUE THREAD

**Issue by tomathyg** [Varying-Vagrant-Vagrants/VVV#1899]
## Current Behavior
The box 'puphpet/ubuntu1804-x64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/puphpet/ubuntu1804-x64"]
Error: The requested URL returned error: 404 Not Found

## Possible Solution
Alternative box

I've tried /puphpet/ubuntu1604-x64, however, it produces this error:

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount | grep " /mnt/vagrant-mounts/1000-33 "
if test $? -ne 0; then
mkdir -p '/mnt/vagrant-mounts/1000-33'
chmod 700 '/mnt/vagrant-mounts'
vmhgfs-fuse -o allow_other,default_permissions,uid=1000,gid=33,dmode=775,fmode=774 .host:/ '/mnt/vagrant-mounts/1000-33'
fi

Stdout from the command:

Stderr from the command:

fuse: unknown option `dmode=775'

## Steps to Reproduce (for bugs)
vagrant up --provider=vmware_fusion

## Context
I want to use VMWare rather than Virtualbox as it has always worked well, I use it for other machines, and Virtualbox keeps crashing (VBoxHeadless)

## Your Environment
* VVV version: 3.0.0
* VVV Git Branch: master
* Vagrant version: 2.2.5
* VM Provider name: WMWare
* VM Provider version: 10.1.6
* Operating System and version: Mac OSX 10.13.6 (High Sierra)

**Comment by tomjn** [comment]
That's unfortunate, the replacement must be running Ubuntu 18.04 in order to work, 16.x won't do

**Comment by tomathyg** [comment]
Ok, is there an alternative 18.04 box that you'd suggest or recommend?

**Comment by benlumia007** [comment]
i have checked, no one has vm_fusion for 18.04 at the moment. but some has it for vmware_desktop, but im going to assume that vm_fusion is for MacOS.

**Comment by tomjn** [comment]
all our provisioners are set up for 18.04, if you use another version of Ubuntu there's an extremely high chance of issues. For example, we add PPAs for a number of packages, but we add the 18.04 PPAs, using another version of the distribution would mean those packages can't be installed

I'd suggest asking PuPHPet why they removed their box

**Comment by tomjn** [comment]
https://github.com/puphpet/puphpet/issues/2832 looks like the Ubuntu 18.04 effort was abandoned due to lack of resources

**Comment by tomathyg** [comment]
Ok, so where does this leave support for VMware?

I've tried a couple of 18.04 boxes tagged as having vmware_fusion providers (darrenpmeyer/ubuntu-bionic64-mini and tcataldo/bionic) but they both fail with the same error I mentioned - fuse: unknown option `dmode=775'.

I was previously using the puphpet/ubuntu1404-x64 box, which is only tagged as vmware_desktop. Is there any real difference here, in terms of providers?

Perhaps reverting to an older version of VVV and using puphpet/ubuntu1604-x64 is the best approach, if I want to use VMware?

**Comment by tomjn** [comment]
You can’t mix and match Ubuntu versions, it MUST be 18.04 to work with VVV.
If you went to 16 you would be missing packages. If you went to 14 you
wouldn’t have PHP as it’s end of support and Ondrej deleted them.

Otherwise you have these options:

1. Fork VVV and maintain it manually
2. Build an Ubuntu 18.04 box and upload it to vagrant cloud
3. Switch provider

The reason we lost VMware as supported is because every time we try to drop
it somebody pops up saying it’s super mission critical, and Lorelei says
she has a license so she can sort it if it breaks, but given she’s super
busy with non-VVV things, and none of the other contributors tests VMWare
or have licenses, we have no idea if it’s broken until someone raises an
issue, and then we’re speculating on fixes

I’m sure with a few tweaks I could eliminate the fmode dmode thing, but
it’ll probably introduce another issue, and I know for a fact that the
provisioned will fail unless it’s Ubuntu 18.04

**Comment by tomathyg** [comment]
Sorry, I understand that. I meant using an earlier version of VVV, not VVV 3. Looks like it'd have to be VVV 2.6 with puphpet/ubuntu1404-x64, if going with puphpet.

With VVV 3, I've found that the fmode dmode issue can be avoided by using NFS for all shared folders, which I want to do anyway (obviously this won't be an option for everyone). By the way, I noticed that you're thinking of adding a shared folder type option to the vvv-config - this would be very handy!

I very nearly got there with generic/ubuntu1804 and xcoo/bionic64 but both fail with:

default: Errors were encountered while processing:
default:  nginx
default:  mariadb-server-10.3
default:  mariadb-server

Currently trying to sort this but any suggestions welcome :)

I'd be happy to use Virtualbox if I wasn't getting kernel panics. It also sounds like I may continue to encounter issues as a result of using Vbox and VMware, sometimes simultaneously.

**Comment by tomjn** [comment]
> Looks like it'd have to be VVV 2.6 with puphpet/ubuntu1404-x64, if going with puphpet.

This would fail with missing package errors. We used Ondrej for PHP packages, but Ubuntu 14 reached end of support, so Ondrej deleted the Ubuntu 14 PHP packages.

To get VVV 2.x working, you're going to need to compile PHP from scratch. That's why we moved to 18.

VVV 2 is a dead-end and a red herring. You can make it work with **extreme** effort, but it's much easier to just switch to 3.


> I very nearly got there with generic/ubuntu1804 and xcoo/bionic64 but both fail with:
> 
> default: Errors were encountered while processing:
> default: nginx
> default: mariadb-server-10.3
> default: mariadb-server

With Virtualbox? I don't have a lot of context to comment on here, a separate issue with more information and a full log of the `vagrant up --provision` output would be needed, otherwise it's the equivalent of a 500 HTTP code, it tells you nothing about what went wrong, just that it went wrong :(

Eitherway switching boxes shouldn't be necessary.

> I'd be happy to use Virtualbox if I wasn't getting kernel panics.

Have you tried updating MacOS? The latest available stable is v10.14.5 Mojave

**Comment by tomathyg** [comment]
Ok, VVV 3.x it is.

I've just run a new vagrant up after vagrant destroy and MacBook reboot - will post the full output on a new issue. Got to the same point although only mariadb-server-10.3 and mariadb-server now causing issues, not nginx.

Would you say that a generic 1804 box should work?

Haven't tried updating to Mojave yet. Perhaps that should be my next port of call, whether or not I stick with VMware.

**Comment by tomathyg** [comment]
I managed to get VVV 3.0 working on VMware Fusion using the bento/ubuntu-18.04 box (specified for HyperV but that also has the vmware provider/s). I had to use db_share_type: false in vvv-custom.yml. I haven't tried it without NFS.

Pretty much everything works fine apart from, weirdly, the sites won't load in Chrome or Opera. Fine in Safari and Firefox. What could be the reason for this?

I also have to use https, otherwise the sites won't load.

One last thing, the sites don't load the first time I try. It takes two attempts to load a site (including vvv.test), after that they load fine every time. This is an issue I had previously on VVV 2.6 using VMware.

Any help is much appreciated and I hope this is helpful to others looking to use VMware.

**Comment by tomjn** [comment]
when it fails to load a site the first time, what's the reported reason? Is it a timeout? Refused connection? 🤔 Thanks for the updated log!

**Comment by tomathyg** [comment]
No probs!

Error is:

'This site can’t be reached'

ERR_ADDRESS_UNREACHABLE

In both Chrome and Opera.

**Comment by tomathyg** [comment]
Sorted - it was just my hosts file.

I changed the IP of this test system to 192.168.60.4 so as to not interfere with my other vagrant VM. The other hosts were still listed in /etc/hosts so I removed them.

Now everything works perfectly, first time :)

Will let you know if I have any more issues. Can also test without NFS.

Thanks for your help and very speedy responses!

**Comment by Mte90** [comment]
Maybe we can do a doc page about vmware for VVV with this trick for the box using the new parameter to define it in vvv-config.yml, what do you think @tomjn?

**Comment by tomathyg** [comment]
FYI: I get the same fmode dmode error using the standard shared folders with the bento/ubuntu-18.04.

Am now using the develop branch.

**Comment by tomathyg** [comment]
I think the issues I was having with nginx and/or mariadb-server-10.3 / mariadb-server may have been to do with me having changed the IP address. It's working fine for me on both the master and develop branches as long as I use the default IP.

It also turns out (in case you weren't aware) that Hashicorp got round to updating their VMware plugin last year (free upgrade). It's now called vagrant-vmware-desktop and encompasses fusion and workstation. So, in my Vagrantfile, I'm using the following:

config.vm.provider :vmware_desktop do |v|
    v.vmx["memsize"] = vvv_config['vm_config']['memory']
    v.vmx["numvcpus"] = vvv_config['vm_config']['cores']
  end

config.vm.provider :vmware_desktop do |v, override|
    override.vm.box = "bento/ubuntu-18.04"
    v.gui = false
  end

**Comment by tomjn** [comment]
Can you do a pull request for that? Thinking about the fmode/dmode stuff, if you remove those parts does the problem go away? It looks more like a warning than an error, but it'd be good to eliminate it

**Comment by tomathyg** [comment]
Yes, was thinking of doing a pull request.

I'll try without fmode and dmode.

**Comment by benlumia007** [comment]
virtualbox uses `mount_options => [ "dmode=775", "fmode=774"]` 
hyperv `mount_options => [ "dir_mode=0775", "file_mode=0774"]`, 
parallels `mount_options => []`
vmware should be the same as parallels if not then its virtualbox

**Comment by tomathyg** [comment]
Yes, it works fine without the fmode and mode settings.

**Comment by Mte90** [comment]
so we can improve the vagrantfile, can you do a pull request?

**Comment by tomathyg** [comment]
Am doing, sorry, never done one before so not quite sure what the best approach is. Fork first?

**Comment by tomjn** [comment]
if you go to edit the vagrant file on this repo it'll give you the option to submit changes via a PR which will create a fork

**Comment by tomathyg** [comment]
Ok, done. Thanks :)

I've just suggested the provider changes, not the dmode and fmode settings.

**Comment by tomjn** [comment]
Closing this out as we no longer use this box, thanks @tomathyg for the help/changes :)
