### ISSUE TITLE
BoxBuilder use specific binary for packer

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1900]
I was trying to get running https://github.com/Varying-Vagrant-Vagrants/BoxBuilder
I am on linux 64bit and I was getting this:
```
make -C ubuntu-18.04
make[1]: ingresso nella directory "/media/disk3part1/BoxBuilder/ubuntu-18.04"
rm -rf "/media/disk3part1/BoxBuilder/builds/ubuntu-18.04-virtualbox"
rm -f "/media/disk3part1/BoxBuilder/builds/ubuntu-18.04-virtualbox.box"
../bin/packer build -var "name=ubuntu-18.04" -var "output=/media/disk3part1/BoxBuilder/builds/ubuntu-18.04" ./packer.json
/bin/sh: 1: ../bin/packer: Exec format error
make[1]: *** [../_common/common.mk:18: build] Error 2
make[1]: uscita dalla directory "/media/disk3part1/BoxBuilder/ubuntu-18.04"
make: *** [Makefile:10: ubuntu-18.04] Error 2
```
I saw in https://github.com/Varying-Vagrant-Vagrants/BoxBuilder/blob/master/_common/common.mk#L18 that use a specific binary but I installed packer from my debian repo, so I changed that line to use the global version available.

**Comment by Mte90** [comment]
I get also:
```
/bin/sh: 1: pushd: not found
make[1]: *** [../_common/common.mk:21: test] Error 127
make[1]: uscita dalla directory "/media/disk3part1/BoxBuilder/ubuntu-18.04"
```
Seems that pushd is not available because is a bash bultin and not a command

**Comment by tomjn** [comment]
It was built and tested using MacOS so it doesn't surprise me that it fails on a different OS

**Comment by Mte90** [comment]
ok so if I improve to do works also on linux is not so bad :-D
Also because is working apart this errors on linux.

**Comment by Mte90** [comment]
Few changes to use local packer https://github.com/Varying-Vagrant-Vagrants/BoxBuilder/pull/2

**Comment by Mte90** [comment]
The pr fix everything issue I have.
