### ISSUE TITLE
Database is re-provisioned after removal.

### ISSUE THREAD

**Issue by darrylmorley** [Varying-Vagrant-Vagrants/VVV#1906]
## Expected Behavior

I expect the databse not to be created after removal and commenting out in custom.yaml.

## Current Behavior

On vagrant up --provision the site is not recreated in the dashboard and folders are not recreated, but the database is.

## Steps to Reproduce (for bugs)

1. Create new site.
2. Provision
3. Comment out new site in custom.yaml
4. Delete database and folders.
5. vagrant halt && vagrant up --provision

## Your Environment

* VVV version: 
* VVV Git Branch: 
* Vagrant version: 3.1.0
* VM Provider name: 
* VM Provider version: VirtualBox 6.0
* Operating System and version: Windows 10, 1903

**Comment by tomjn** [comment]
The database might have been recreated from the backups folder, but without a copy of the output from provisioning I can only speculate

**Comment by darrylmorley** [comment]
Thanks, I'll give it a try, I wasn't aware of the backup.

**Comment by benlumia007** [comment]
the backup ( db_restore and db_backup ) variables are in vvv-custom.yml and its set to true when you vagrant halt, vagrant destroy.
