### ISSUE TITLE
Question on db_share_type setting

### ISSUE THREAD

**Issue by atomtigerzoo** [Varying-Vagrant-Vagrants/VVV#1909]
Does setting `db_share_type` to `false` have any implications on database backups or anything related? 
The documentation is a bit vague for me on this point :/ Thank you for hints!

**Comment by tomjn** [comment]
The `db_restore` and `db_backup` use `mysql` cli commands, they have no knowledge of how MariaDB stores things internally.

`db_share_type` changes wether the internal database files are stored on a mounted synced folder, or inside the VM. I don't see any way this could be relevant to CLI or PHP use. The purpose of the flag is to fix provisioning for people who can't provision MariaDB with the option turned on

**Comment by atomtigerzoo** [comment]
Thank you for the answer what it does.
But in my case it also seems to fix an issue with `truncate` as seen in another ticket - I had to switch it to false because I could not use `truncate` anywhere (phpmyadmin, php, cli).

**Comment by Mte90** [comment]
What is not clear to you in the documentation? We can improve it.

**Comment by tomjn** [comment]
We don’t really document that option

As for why truncate does or doesn’t work, we’d have to delve into the
arcane rituals of virtual box shares and your hosts file system. I’d be
lying if I said I could give a simple answer to that :(
