### ISSUE TITLE
Profiling with tideways isn't working as stated in the documentation

### ISSUE THREAD

**Issue by kmgalanakis** [Varying-Vagrant-Vagrants/VVV#1911]
In [this documentation page](https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/), it is stated that in order to profile a page, you just need to add `?enable-tideways` to your URL and then head to `http://xhgui.vvv.test/` to view the profiling results.

This didn't work for me as, by following @tomjn advice, I had to add `?enable-tideways=1` to my URL instead.

If this is the way it is supposed to work I can provide a PR with this documentation change, while also fixing a typo and also adding a note that in order to use tideways profiling, you also need to have `xdebug_off`.

![image](https://user-images.githubusercontent.com/1268089/61937364-5a373200-af97-11e9-8651-599106344de8.png)

Otherwise, if `?enable-tideways` is also supposed to work, then this needs to be fixed here.

What do you think?

**Comment by Mte90** [comment]
I checked now with running `xdebug_on` (required since 3.1, we will update the doc when will be released), adding that parameter in url worked for me.
Maybe the website that are you using is with php 5.6?

**Comment by tomjn** [comment]
Would it make sense to add a HTTP header signifying it’s on in the preload?
Or would that cause issues. Then there’d be no doubt as to wether it was
running or not
