### ISSUE TITLE
The SSH command responded with a non-zero exit status. On the current develop branch.

### ISSUE THREAD

**Issue by patilswapnilv** [Varying-Vagrant-Vagrants/VVV#1913]
Hey, 👋

Thank you for maintaining such an awesome tool.  🙏
I have been following the recent issues after the updates on the weekend. VVV has been an integral part of my work precess since 1.6, I really can't explain how uneasy I am feeling since this isn't working 😦  It has been the first time I got into something like this. 

So here is what happened, after the update, I was not able to get my local dev env. up and running. I have tried 
✅Pulling from `develop branch`, 
✅Started over again once, 
✅On the previous setup I had similar issues reported here https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1773, but unfortunately none of the solution worked for me. 
So I tried a new setup. 

Here is a gist with the result I see after running `vagrant up --provision --debug`
https://gist.github.com/patilswapnilv/209f1183cfe9cc0b9be750f170e2935b

## Expected Behavior

I expected to get it up and running, at least after starting over again. 

## Current Behavior

```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
💀

## Possible Solution

Please suggest a solution, I am out of ideas. ☹

## Steps to Reproduce (for bugs)

1. A fresh git pull from the `develop` branch
2. Added the `vvv-custom.yml`
3. run `vagrant up --provision --debug`

## Context

I am trying to get the environment up and running after it broke post update. I was assuming that even if the previous setup does not work; I can roll a fresh one, since I have backup for the DB's and the files. But unfortunately the fresh install too did not work for me. ☹

Should I be trying with different version of Vagrant or Virtual Machine?

## Your Environment

* VVV version: v3.1.0-git::develop
* VVV Git Branch: develop
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0.10 r132072 (Qt5.6.3)
* Operating System and version: Mac OS Mojave v10.14.5

__ __ __ __
```
Varying Vagrant Vagrants
v3.1.0-git::develop

Platform:   platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater shared_db_folder_disabled
Vagrant:    v2.2.4,	VirtualBox: v6.0.10r132072
```

**Comment by tomjn** [comment]
Hello!

Thanks for the log but do you have a normal version? The debug version has
everything we’d need but it’s so massive and has so much information it’d
take hours to find what normally takes a minute :(

**Comment by patilswapnilv** [comment]
Hey @tomjn 
Thank you for looking into this. Here is a gist with the output, when I am not using `--debug`; I have used `vagrant up --provision`

https://gist.github.com/patilswapnilv/a951083c34d6f6a4585f23c5c6f30b81

I hope this helps. Let me know if I can provide any more information regarding this. 


<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/patilswapnilv/a951083c34d6f6a4585f23c5c6f30b81">vagrant up --provision on a fresh git pull on develop branch</a></strong></div><div>vagrant up --provision on a fresh git pull on develop branch - debug.log</div></blockquote>

**Comment by tomjn** [comment]
Is that on the brand new fresh checkout? Or is that an existing VM after a reprovision?

**Comment by tomjn** [comment]
>         default: /var/lib/mysql => /Users/swapnil/vagrant-local/database/data

There's your problem, you need to disable the shared database folder. We changed this to be disabled by default in `vvv-config.yml`, but if you already have an existing `vvv-custom.yml` then you need to update it. Look at `vvv-config.yml` for the option

**Comment by patilswapnilv** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1913#issuecomment-516363784
Yes, a fresh checkout. 



> Is that on the brand new fresh checkout? Or is that an existing VM after a reprovision?

Yes, a fresh checkout.

**Comment by patilswapnilv** [comment]
> > ```
> >     default: /var/lib/mysql => /Users/swapnil/vagrant-local/database/data
> > ```
> 
> There's your problem, you need to disable the shared database folder. We changed this to be disabled by default in `vvv-config.yml`, but if you already have an existing `vvv-custom.yml` then you need to update it. Look at `vvv-config.yml` for the option
> 
> Can I see the `general` section of your vvv-custom to confirm?

Yes, that was the issue; I had not added the `general` section in the `vvv-custom.yml`. 
➡I added the general section from the `vvv-config.yml`
➡Did a `vagrant destroy` 
➡Then did a `vagrant up --provision`

As a result the provision work perfectly well 🎉
Until I tried `vvv.test` on the browser, I get the `Welcome to nginx!` message. Not the dashboard. 

Did I miss something?

Thank you again for taking time to help me with this. 🙏

**Comment by tomjn** [comment]
@patilswapnilv if you can get a copy of that last provision that gave you the nginx message, then reprovision? The reprovision will very likely resolve that problem

**Comment by patilswapnilv** [comment]
@tomjn Thank you very much; That resolved the issue. 

Should we be expecting any bumps when updating to the next planned version? We could document this, I would be more than happy to help with it.

**Comment by tomjn** [comment]
moving from 3.1 to 3.2 should be straight forward without bumps

**Comment by patilswapnilv** [comment]
Awesome🎉
