### ISSUE TITLE
v3.2

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1922]
I'd like to invetigate making the following changes for 3.2:

 - **Improve log files**, right now they're `.log` files which is a pain in the arse on MacOS, lets make them `.txt` files so they open in a nicer app by default. Also, right now they're all separate files, but it'd be great to have an extra file that just has the entire log
 - **Move `vvv-config.yml` and `vvv-custom.yml`**, I would like to move these into the `config` folder so they're back in a mapped folder. It would be good to de-emphasise `vvv-config.yml` too
 - **Dashboard update notification** (#1333), we have an issue for this already, but a JS snippet that pokes the GH releases API and checks the value of `/vagrant/version` against the newest, and if they don't match, put a banner in the dashboard
 - ~**Reload Nginx in the core site provisioner**, this way site templates don't need to, and we can make future optimisations~
 - **Put a standardised log message with colour at the start of each provisioner**, our provisioner output is a bit blank now :( lets reintroduce colours and make it easier to read

I think this should make a nice solid 3.2 release, focusing on polish and quality of life, what does everybody think? @Mte90 @benlumia007 @LoreleiAurora

**Comment by Mte90** [comment]
* I don't see very good to do a big file with all the log that can be difficult to read, maybe we can integrate something that publish automatically on pastebin instead as various files.
* I think that we can move `vvv-config.yml` to config itself so people is not interested on altering it. I am not sure about `vvv-custom.yml`

For the other points let's do it!

My other proposals:

* Integrate in the dashboard the enabling of the tideways provisioner and also of xdebug. So people will be not required to access to ssh (this open also the floor to the other script that we offer).
* Move on the documentation starting with finish https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/126
* Integrate yamllint https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1745
* Webpack output to custom log file https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1868
* Integrate the WP-CLI provisioner https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1732

**Comment by tomjn** [comment]
> I don't see very good to do a big file with all the log that can be difficult to read, maybe we can integrate something that publish automatically on pastebin instead as various files.

It makes it easier for users to send us the entire thing or put it in a gist, especially for Windows users. In particular I'd really like to see the splash screen info in there

> I think that we can move vvv-config.yml to config itself so people is not interested on altering it. I am not sure about vvv-custom.yml

Indeed, renaming the file might be good to, e.g. `config/default-config.yml`. By moving `vvv-custom.yml` we gain the ability to modify it from inside the VM via the dashboard

As for the other points, those don't need a 3.2 release, the dashboard/docs site/etc are all on async continuous release cycles. The Yamllint issue though is definitely something we can add in, I'll flag it as 3.2

**Comment by benlumia007** [comment]
if the config/default-config.yml doesn't get edit,  does it still get copied and renamed to vvv-custom.yml, and where will this vvv-custom.yml be located at.  it sounds like the only way to modify is inside the VM via the dashboard.... ?

**Comment by tomjn** [comment]
> Reload Nginx in the core site provisioner, this way site templates don't need to, and we can make future optimisations

It seems we already do this!

> if the config/default-config.yml, does it still get copied and renamed to vvv-custom.yml, and where will this vvv-custom.yml be located at. it sounds like the only way to modify is inside the VM via the dashboard.... ?

We're just renaming and moving the files, nothing else changes, and they're still used the same way. Just their locations change

So `vvv-config.yml`. -> `vvv-custom.yml` turns into `config/default-config.yml` -> `config/vvv-custom.yml`

**Comment by msaggiorato** [comment]
I'm taking a shot at this

**Comment by tomjn** [comment]
hmmm might make more sense to have `config/config.yml`

**Comment by msaggiorato** [comment]
Yeah, i'm considering this, there's no point in calling it `config/vvv-custom.yml` anymore

**Comment by tomjn** [comment]
Done done and done
