### ISSUE TITLE
Undefined index: HTTP_HOST in /srv/tideways-header.php

### ISSUE THREAD

**Issue by janw-me** [Varying-Vagrant-Vagrants/VVV#1924]
On a freshly installed vvv running on tag/commit [`3.1.1`](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/b77afc550130f1aefc737913e3a81baa03fbfc96).

Pretty much every php cli command that is run _inside_ the vvv will give the notice:   
`PHP Notice:  Undefined index: HTTP_HOST in /srv/tideways-header.php on line 4`
Especially commands that call a find. See the screenshot for a use case.
The culprit line is:

    if ( strpos( $_SERVER['HTTP_HOST'], 'vvv.test' ) == false ) {

The simple fix is

    if ( isset( $_SERVER['HTTP_HOST'] ) && strpos( $_SERVER['HTTP_HOST'], 'vvv.test' ) == false ) {

I could not find this file in the repo.

![vvv_notice](https://user-images.githubusercontent.com/1026882/63006933-f8743480-be7f-11e9-8676-192d1d622c3c.png)

This was not a notice I saw in 3.0.0 (I completely reinstalled my local machine last week)

**Comment by tomjn** [comment]
Thanks for the fix! The file is in the VVV utilities repo under the
tideways folder in this org, utilities are a separate repo so we can update
them without needing a full release of VVV. Can you make a PR? It should be
fixed for everybody once merged on their next provision

**Comment by Mte90** [comment]
I did a patch for that, when I did the tests I forgot to check the CLI.

**Comment by janw-me** [comment]
@tomjn did not know it was a seperate repo. Good to know.

**Comment by tomjn** [comment]
@janw-me repo updated, this should be fixed now, thanks for the headsup!
