### ISSUE TITLE
Error After Windows 10 updated - Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).

### ISSUE THREAD

**Issue by CreativeTransmissions** [Varying-Vagrant-Vagrants/VVV#1926]
Hi there,

I'm using VVV with VirtualBox-6.0.10 on Windows 10, had just installed the latest VVV and it was working perfectly.

Yesterday windows installed Feature update to Windows 10, version 1903

Now when running vagrant up as admin in powershell I get the error below.

I have tried:
- vagrant destroy
- uninstalling and reinstalling virtualbox
- disabling windows defender and antivirus

Has anyone else experienced this problem?

Many thanks,
Andrew.

Ignoring ed25519-1.2.4 because its extensions are not built. Try: gem pristine ed25519 --version 1.2.4
Ignoring unf_ext-0.0.7.6 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.6
Ignoring wdm-0.1.1 because its extensions are not built. Try: gem pristine wdm --version 0.1.1
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.1.0-git::master

Platform:   platform-mingw32 windows HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled
Vagrant:    v2.2.5,     VirtualBox: v6.0.10r132072
VVV Path:   "C:/vagrant"

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20190814.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "459dd87a-cb56-4fa7-b9fa-42b0b1ffb254", "--type", "headless"]

Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
PS C:\vagrant>

**Comment by Mte90** [comment]
This seems more are an error of virtualbox then VVV.
I suggest to check if there are any updates or if you need to reinstall it.

**Comment by tomjn** [comment]
Agreed, googling suggests it’s Virtualbox with various work arounds, take a
look at this one:

https://caffinc.github.io/2015/11/fix-vbox-network/

I’m not a windows user myself but I expect you’ll get the same results with
any VirtualBox VM not just VVV and Vagrant VMs

**Comment by CreativeTransmissions** [comment]
Thanks for pointing me in the right direction.

After uninstalling and reinstalling everything twice I am back up and running.

**Comment by vasia123** [comment]
https://www.howtoforge.com/setup-a-local-wordpress-development-environment-with-vagrant/ in section "Note for Windows 8/10 Users" have exactly instruction how to fix this issue.
