### ISSUE TITLE
cURL error... again

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1934]
## Expected Behavior
I should be able to upload plugins from the admin

## Current Behavior
When I go to plugins admin page and try to add new one (or update a theme), I get errors like in the images:

![Screenshot 2019-08-24 at 10 22 13](https://user-images.githubusercontent.com/8638515/63634643-b2765800-c659-11e9-8fdf-0f9d2b8cc25c.png)
![Screenshot 2019-08-24 at 10 22 22](https://user-images.githubusercontent.com/8638515/63634644-b30eee80-c659-11e9-87f4-e9711fdbbe7c.png)

This time the cURL is not made towards the 3rd party API, it's wordpress.org API calls that are failing.

This happens on all environments that I have. I've recently updated to bionic provider, so not sure if this is the issue.

## Your Environment

VVV: 3.1.1 (develop branch)
Platform:   platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater shared_db_folder_disabled
Vagrant:    v2.2.5,	VirtualBox: v6.0.8r130520

I tried to re provision, but the screen just halts so not sure what's the issue with this.

**Comment by tomjn** [comment]
Are you sure this is a curl error and not just the DNS server for wordpress.org having downtime? Curl is just the internal library used with PHP to make HTTP requests, it's not a VVV component, and it's not something we configure. We literally install it as is and do no further configuration.

I did see this issue the other day though, but it was on a live production website, and I couldn't load wordpress.org in the browser either, but the problem went away shortly afterwards. No VVV/Vagrant/VirtualBox was present on the machine, it was just an attendees site running on paid hosting.

I fired up a site on VVV to test but was unable to replicate the problem locally, so:

 - this isn't a curl or VVV issue, curl is just a part of the PHP/WP toolchain, similar to how not being able to drive to the store isn't BMWs fault if Walmart is closed
 - if it is a curl issue, there's little to nothing that can be done with VVV
 - the error message you got describes the problem exactly, .org was either down or unreachable
 - Query Monitor gave some more information in your screenshots, reporting there was a timeout resolving DNS for that domain, which is what was happening at the local user group

For future testing, you'll need to do the following to confirm it actually is a curl issue:

 - replicate the issue using a `curl` command
 - demonstrate it working on the host machine outside of VVV, but not working inside the VM
 - show that it's not just wordpress.org, but all domains
 - show that it works when using an alternative to curl

This is what I suggest you do next:

 - open wordpress.org in a browser to confirm you can access it
 - retry contacting .org on the site
 - try another wifi network

You can test the DNS lookup with `nslookup wordpress.org` on both the host and guest

**Comment by dingo-d** [comment]
> Are you sure this is a curl error and not just the DNS server for wordpress.org having downtime? 

Nope, because on my live site I can preview plugins just fine. From the screenshot you can see that there is no plugin loaded at all on VVV.

I restarted my computer, made `vagrant up`, my VVV went up successfully

<details><summary>Provisioning log</summary>
<pre><code>
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.1.1
-git::develop

Platform:   platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater shared_db_folder_disabled
Vagrant:    v2.2.5, VirtualBox: v6.0.10r132072
VVV Path:   "/Users/infinum-denis/vagrant-local"

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20190813.1.0' is up to date...
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20190813.1.0'. The latest is version
==> default: '20190822.0.0'. Run `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.2.8_KernelUbuntu r120774
    default: VirtualBox Version: 6.0
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.50.4  vvv  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  vvv.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  madebydenis.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  clients.wordpress.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  dev.wordpress.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  plugin.wordpress.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  internal.wordpress.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  gutenberg.wordpress.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  plugins-testing.environment.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater]   192.168.50.4  wp-boilerplate.test  # VAGRANT: fd57c0d586cac581e11e7c0dc1476c06 (default) / b0927337-7c03-4cc3-aa7c-1461cd90cb39
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
Password:
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /srv/www => /Users/infinum-denis/vagrant-local/www
    default: /srv/config => /Users/infinum-denis/vagrant-local/config
    default: /var/log/php => /Users/infinum-denis/vagrant-local/log/php
    default: /srv/database => /Users/infinum-denis/vagrant-local/database/sql
    default: /var/log/nginx => /Users/infinum-denis/vagrant-local/log/nginx
    default: /srv/provision => /Users/infinum-denis/vagrant-local/provision
    default: /srv/certificates => /Users/infinum-denis/vagrant-local/certificates
    default: /var/log/memcached => /Users/infinum-denis/vagrant-local/log/memcached
    default: /var/log/provisioners => /Users/infinum-denis/vagrant-local/log/provisioners
    default: /srv/www/personal/madebydenis => /Users/infinum-denis/vagrant-local/www/personal/madebydenis
    default: /srv/www/infinum/wp-boilerplate => /Users/infinum-denis/vagrant-local/www/infinum/wp-boilerplate
    default: /srv/www/personal/wordpress-test => /Users/infinum-denis/vagrant-local/www/personal/wordpress-test
    default: /srv/www/personal/private-plugins => /Users/infinum-denis/vagrant-local/www/personal/private-plugins
    default: /srv/www/personal/wordpress-plugin => /Users/infinum-denis/vagrant-local/www/personal/wordpress-plugin
    default: /srv/www/personal/wordpress-clients => /Users/infinum-denis/vagrant-local/www/personal/wordpress-clients
    default: /srv/www/personal/wordpress-internal => /Users/infinum-denis/vagrant-local/www/personal/wordpress-internal
    default: /srv/www/personal/wordpress-gutenberg => /Users/infinum-denis/vagrant-local/www/personal/wordpress-gutenberg
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default: Post Vagrant up script
    default: Restarting Nginx and MySQL
    default:          yay
    default:    ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄                __ __ __ __
    default:    █▒▒░░░░░░░░░▒▒█    Thanks for  \ V\ V\ V /
    default:     █░░█░░░░░█░░█     using        \_/\_/\_/
    default:  ▄▄  █░░░▀█▀░░░█  ▄▄
    default: █░░█ ▀▄░░░░░░░▄▀ █░░█ Vagrant Up has finished! Visit http://vvv.test
    default:
 infinum-denis@Denis-MacBook-Pro  wp-content/plugins/simple-linked-variations-for-woocommerce   develop 
</code></pre>
</details>

I can log in, but still cannot access the plugins.

When I go to 
`https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[page]=1&request[per_page]=36&request[locale]=en_US&request[browse]=featured&request[wp_version]=5.2`

The response is there.

Locally, on my mac, when I do

```bash
curl -X GET https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request%5Bpage%5D=1&request%5Bper_page%5D=36&request%5Blocale%5D=en_US&request%5Bbrowse%5D=featured&request%5Bwp_version%5D=5.2
```

I also get results (json).

I tried to do the same when I ssh to vagrant and I got

```bash
[1] 8986
[2] 8987
[3] 8988
[4] 8989
[5] 8990
request%5Blocale%5D=en_US: command not found
request%5Bwp_version%5D=5.2: command not found
request%5Bper_page%5D=36: command not found
[4]-  Exit 127                request%5Blocale%5D=en_US
vagrant@vvv:~$ request%5Bpage%5D=1: command not found
request%5Bbrowse%5D=featured: command not found

json list of plugins

:"https:\/\/s.w.org\/plugins\/geopattern-icon\/limit-login-attempts.svg"}}]}
[1]   Done                    curl -X GET https://api.wordpress.org/plugins/info/1.2/?action=query_plugins
[2]   Exit 127                request%5Bpage%5D=1
[3]-  Exit 127                request%5Bper_page%5D=36
[5]+  Exit 127                request%5Bbrowse%5D=featured
```

I tried `cURL`ing google locally and inside VVV and I got the same results (just HTML).

I tried with wget, and the same thing happens inside ssh, I get the errors (only for the plugins API)

```bash
vagrant@vvv:~$ wget -qO- https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request%5Bpage%5D=1&request%5Bper_page%5D=36&request%5Blocale%5D=en_US&request%5Bbrowse%5D=featured&request%5Bwp_version%5D=5.2
[1] 9277
[2] 9278
[3] 9279
[4] 9280
[5] 9281

Redirecting output to ‘wget-log.1’.
request%5Blocale%5D=en_US: command not found
request%5Bbrowse%5D=featured: command not found
request%5Bwp_version%5D=5.2: command not found
[4]-  Exit 127                request%5Blocale%5D=en_US
[5]+  Exit 127                request%5Bbrowse%5D=featured
vagrant@vvv:~$ request%5Bpage%5D=1: command not found
request%5Bper_page%5D=36: command not found
{"info":{"page":1,"pages":2540,"results":60960},"plugins"
...
tempts.svg"}}]}
[1]   Done                    wget -qO- https://api.wordpress.org/plugins/info/1.2/?action=query_plugins
[2]-  Exit 127                request%5Bpage%5D=1
[3]+  Exit 127                request%5Bper_page%5D=36
```

Outside on my local machine I get the correct output.

Also the `wget` of `example.com` works ok in and outside of VVV.

Inside vvv for `nslookup` I get

```bash
nslookup wordpress.org
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	wordpress.org
Address: 198.143.164.252
** server can't find wordpress.org: NXDOMAIN
```

Outside I get 

```bash
Server:		198.54.117.10
Address:	198.54.117.10#53

Non-authoritative answer:
Name:	wordpress.org
Address: 198.143.164.252
```

**Comment by tomjn** [comment]
`wget` doesn't use `curl`, they share no common heritage to my knowledge.

For the `wget` command, the references to `request%5Blocale%5D=en_US: command not found` are because of the way the command was formatted, the URL wasn't escaped so bash interpreted it as an additional command

If I run this command from inside the VVV VM:

```sh
wget -qO- "https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request%5Bpage%5D=1&request%5Bper_page%5D=36&request%5Blocale%5D=en_US&request%5Bbrowse%5D=featured&request%5Bwp_version%5D=5.2"
```

I get a large JSON blob in my terminal

As for `nslookup`, those results look fine, though all uses of `nslookup` inside the VM give the NXDOMAIN messages regardless, even for known good values such as `vvv.test`, so this doesn't seem to be the problem

Since it's just the plugins API that's giving you grief, I'd contact the .org support forums

**Comment by dingo-d** [comment]
I'll see if there is something odd in the .org API, I just refreshed the page and it works. Bizarre.

Well, thanks for helping out :+1:
