### ISSUE TITLE
[Trivial] add Mac OS icons to .gitignore

### ISSUE THREAD

**Issue by ironicmoka** [Varying-Vagrant-Vagrants/VVV#1936]
**Is your feature request related to a problem? Please describe.**
It's _very_ trivial, but I have customized some icons inside the vagrant folder to quick recognize it as shortcuts on my dock and I'd like to filter Mac OS icons as well in the .gitignore file, in order to have clean git statuses on my machine.

**Describe the solution you'd like**

```
Icon?
Icon\r
Icon\r\r
```
works well to filter out the icons on my machine, but I don't know if it could create problems (without any file extension to be declared for it should be safe, I guess).

**Comment by tomjn** [comment]
Looks sensible to me, can you make a pull request?
