### ISSUE TITLE
Improve docs for local dev: multisite

### ISSUE THREAD

**Issue by lovestulip** [Varying-Vagrant-Vagrants/VVV#1941]
Could you please update the [VVV documentation](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) for setting up a new multisite installation?

I've seen a number of people run into trouble with this. One client kindly pointed out that this [external documentation ](https://www.exove.com/blog/developing-wordpress-part-5-multisite-vvv/) provides some guidelines on what the exact steps are to set up the multisite, namely that you need to add the additional subdomains under the initial site in the hosts list in vvv-custom.yml. 

If you could share this insight more clearly in your documentation, I think it would be helpful!

Thanks so much.

**Comment by Mte90** [comment]
Added some stuff on https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/138 but the readme of the github repo include all the documentation
