### ISSUE TITLE
A fresh installation doesn't support npm run grunt patch for core

### ISSUE THREAD

**Issue by johnbillion** [Varying-Vagrant-Vagrants/VVV#1943]
## Expected Behavior

*Note:* I'm not sure whether this is a VVV bug or a bug with https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator. Needs investigating.

Installing VVV anew during a WordPress Contributor Day should result in all of its npm commands being available for patching core.

## Current Behavior

```
vagrant ssh
cd /srv/www/wordpress-develop/public_html
npm install
npm run grunt patch:12345
```

The above results in the following error:

```
Error: Cannot find module 'grunt-cli/bin/grunt'
```

## Possible Solution

Completely reinstalling out `node_modules` with `rm -rf node_modules && npm i` fixes the problem

## Steps to Reproduce (for bugs)

1. Provision a brand new VVV following the contributor day instructions generated by https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator
2. `vagrant ssh`
3. `cd /srv/www/wordpress-develop/public_html`
4. `npm install`
5. `npm run grunt patch:12345`

Observe the above error.

## Your Environment

macOS 10.14.5

**Comment by Mte90** [comment]
We had issues with grunt in VVV but we fixed it, we need to check if this works https://github.com/Varying-Vagrant-Vagrants/VVV/blob/7a46ceebc64f1e273c3e71aacf776be00631dab3/provision/provision.sh#L516

**Comment by Mte90** [comment]
I confirm this issue with the develop template

**Comment by Mte90** [comment]
This fix https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/15 the problem.

Basically if npm install has errors clean the folder and try again.

**Comment by Mte90** [comment]
changes merged with the workaround
