### ISSUE TITLE
Update documentation to reflect which sites are auto provisioned

### ISSUE THREAD

**Issue by joedolson** [Varying-Vagrant-Vagrants/VVV#1944]
The documentation at https://varyingvagrantvagrants.org/docs/en-US/references/default-sites/ includes trunk.wordpress.test as an automatically provisioned site. However, it is no longer a default site provisioned, and is only provisioned if vvv-custom.yml is edited. 

Please update the documentation to reflect behavior more accurately. I think that having a listing of default sites and a listing of default but disabled sites would be useful, including instructions how to enable the disabled sites.

**Comment by Mte90** [comment]
As I can see that website is still available as default https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/vvv-config.yml#L63

**Comment by joedolson** [comment]
Skip provisioning is set to true, so it is not provisioned by default.

**Comment by Mte90** [comment]
Ok I can fix that statement, I misunderstood the point.
