### ISSUE TITLE
There are two labeler actions

### ISSUE THREAD

**Issue by JJ** [Varying-Vagrant-Vagrants/VVV#1950]
There are two labeler actions, one in .github and another in .github/workflows. Do both of them work?

**Comment by tomjn** [comment]
I think one is intended for pull request, the other for issues? Eitherway the actions failing and it doesn't do what it needs to do so I'm inclined to remove it entirely

**Comment by JJ** [comment]
The one in "workflow" is an action, and is the one that you can check from the Actions menu. I'm not sure the one in .github is firing now?

**Comment by tomjn** [comment]
`.github/labeller.yml` is just a config file for the action to tell it how to label things

**Comment by JJ** [comment]
[Right](https://github.com/actions/labeler)
