### ISSUE TITLE
Mailhog config not copied to custom PHP upstreams

### ISSUE THREAD

**Issue by av3nger** [Varying-Vagrant-Vagrants/VVV#1953]
## Expected Behavior
When setting nginx_upstream in vvv config, MailHog ini file is not created for the selected PHP version.

## Possible Solution
Add the MailHog configuration to /srv/php/<nginx_upstream php version>/fpm/conf.d/20-mailhog.ini
Would passing nginx_upstream php version as an argument to provision.sh and using the version as a variable in the script be a solution? 

## Steps to Reproduce (for bugs)
1. Add `nginx_upstream: php73` to any site in vvv-custom.yml
2. Reprovision
3. Try sending an email with wp_mail
4. Email is not caught by MailHog

**Comment by Mte90** [comment]
Looking a the code we need to bump all the various tools that need to be activated for the default php version https://github.com/Varying-Vagrant-Vagrants/VVV/blob/9b87be7d67828ba49f23020fb1814b161732b4a8/provision/provision.sh#L650
