### ISSUE TITLE
Add PHP 7.4

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1959]
With https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/34#issuecomment-540586415 we will add the php 7.4 support.
We need to do after the merge:

* Add that php version in the various utilities 
* Add that php version in VVV checks (if needed)
* Add an alert inside `xdebug_on` about xdebug <= 2.7 don't support yet

**Comment by Mte90** [comment]
We need also to update the vvv-config file.

**Comment by tomjn** [comment]
Closed by #1960
