### ISSUE TITLE
Cleanup provision/resources folder

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1961]
In the past VVV provisioned utilities to `provision/resources`, but in VVV 3 this got changed to `provision/utilities`. Longterm users still have this `provision/resources` folder though, so we should clean it up and save some disk space

should be a simple `rm -r /srv/provision/utilities` or something like that in `provision/provision.sh`

**Comment by msaggiorato** [comment]
Should there be any check for custom utilities (not sure if it's possible)? Isn't it potentially problematic to just remove this?

**Comment by tomjn** [comment]
All utilities are cloned into the `utilities` folder, the `resources` folder is a holdover from earlier versions that isn't used any more. If someone was using a custom utility, it'd have been cloned into the `utilities` folder

**Comment by msaggiorato** [comment]
Ok I'll just make this PR then. Sounds simple.
