### ISSUE TITLE
Add a secure vagrant command

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1962]
Used like so:

```sh
vagrant vvv secure
```

To install the TLS CA certificate on MacOS and Windows

**Comment by Mte90** [comment]
Maybe we can add a new script that download https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/tree/master/tls-ca, add it to `config.yml` in case is not available and a new provision.

**Comment by tomjn** [comment]
I don't think we should use subcommands going forward, this would be a separate CLI command
