### ISSUE TITLE
Generate wpcli.yml during provisions

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1968]
The idea is to do a command like `vagrant vvv wp` and pass the various parameters for wp cli.
We need also to pass the website and automatically the script will execute in the right folder.
We can do the same for the wpcli-dev utilities that now is WIP https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/35

**Comment by tomjn** [comment]
If we generate `wpcli.yml` appropriately, we can do this without a `vagrant` command, e.g.:

```bash
wp @mysite info
```

It just needs the appropriate things in the config

**Comment by Mte90** [comment]
but this will run the local wp inside VVV or the one inside VVV?

My question is also for the dev version

**Comment by tomjn** [comment]
That'll allow WP CLI running on the host, to talk to WP running on the guest

**Comment by Mte90** [comment]
So this doesn't work for the dev version but I think that is something we can see after the integration of the utility.
