### ISSUE TITLE
How to create a single site in a subdirectory?

### ISSUE THREAD

**Issue by unfulvio** [Varying-Vagrant-Vagrants/VVV#1971]
I need to test a scenario where a single-site (_not_ multisite) install needs to live in a subdirectory below the `public_html` root path.

The documentation mentions how to change the root path name or how to point the local folder to somewhere else outside the vvv directory, but not the specific case I am looking for.

I believe the nginx conf needs additional instructions to support a subdirectory install. I haven't quite figure out how to achieve that. I tried to copy some nginx instructions such as https://www.digitalocean.com/community/questions/nginx-wordpress-in-a-sub-directory but that didn't work (I've restarted nginx as well, re-provisioning would destroy the changes). I also made sure to have moved WordPress into a subdir as well, and so on. None of this worked.

Is this supported in VVV at all? If yes, do you mind including some pointers in the docs? If not, that's ok! Then you could mention that as well.

Thank you!

**Comment by tomjn** [comment]
Yes and no, there’s nothing preventing you from doing this, but you can’t
just flick a switch and have VVV automatically do it without making
modifications or manual steps

**Comment by Mte90** [comment]
Yes you need to modify the provisioner https://github.com/Varying-Vagrant-Vagrants/custom-site-template or maybe add a new feature to this one to achieve what you need.

**Comment by unfulvio** [comment]
thanks for the quick replies - would it suffice to modify the `vvv- nginx.conf.tmpl` file in `<site_name>/provision` after the site has been created?

I've tried adding

```

 location / {
                try_files $uri /wordpress/index.php?q=$uri&$args;
 }

 location /wordpress {
                index index.php index.html index.htm;
                try_files $uri $uri/ /index.php?q=$uri&$args;
 }
```

but it didn't quite do the trick... (my subdir folder is `wordpress`)

**Comment by tomjn** [comment]
The problem you'll get from modifying `vvv-nginx.conf.tmpl` is that any changes will be undone on provision. That file is there mostly as a hack to get around a problem we had, it's not needed any more though so it's on our TODO list to eliminate it

Instead, you'll need to fork the site template, or wait 30 minutes for me to do a PR for a `vvv-nginx-custom.conf` feature

**Comment by tomjn** [comment]
I've a PR here: https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/26

It'll let you put a `provision/vvv-nginx-custom.conf`, at which point you can adjust the root directory, then replace the include for WP common. Copy paste the entirety of the file in there and modify all the paths to match your subdirectory

**Comment by tomjn** [comment]
You can test by adding this to the sites entry in `vvv-custom.yml`:

```yaml
    branch: "feature/nginx-custom"
```

Then reprovisioning. Once the PR is merged you can remove that line

**Comment by Mte90** [comment]
Pr tested, fixed and approved so a new provision will handle that :-)

**Comment by tomjn** [comment]
Hmm so WP doesn’t know it’s URL is in a sub directory, at this point it’s a
classic change URL step, WP CLI search replace can do the job

For the rules, even if you don’t get permalinks working it should work with
them turned off until that’s figured out

@mte90 do we support setting the final URL? We can’t mess with the Nginx WP
common file but we should be able to account for the URL? Or does this need
a new parameter?

**Comment by Mte90** [comment]
The settings are only for the host and not for a full path, we need probably a new parameter

**Comment by unfulvio** [comment]
Thanks for your help guys. I made sure to replace references to the standard root to `/wordpress` and updated posts GUIDs as well. In the ends it's a blank website, there's not much there. I removed permalinks as recommended and that seemed to help a bit.

With the nginx directives I mentioned in my previous comment here, it looks like VVV is able to serve WordPress to `/wordpress`. All my URLs redirect there. However, wp-admin seems broken. Both admin and theme assets are still trying to load those assuming `/` root and not `/wordpress`. So there's probably something missing in the nginx conf file or perhaps something that conflicts with the common rules included in VVV.

**Comment by Mte90** [comment]
So `yoursite/wordpress/wp-admin` is a blank page?

**Comment by Mte90** [comment]
Seems really a nginx issue of redirect folders

**Comment by tomjn** [comment]
Are you absolutely sure that WP knows it's in a subdirectory? Or does it still think its main URL is `/` not `/wordpress`? Or are you trying to put a website at `/` with WordPress in a subdirectory?

Please provide too much detail, e.g. if scripts and styles are broken, how are they broken? Do they load the wrong thing? Do they not load at all? What URL does it use? How is it different to what it's meant to use? To save back and forth and guesswork, overload us with every possible detail you can summon up.

Additionally, you made a number of changes to the nginx configs, but didn't share them, can you post them up as a gist so we can look at them? Right now we're kind of making stabs in the dark guessing what was changed at your end, we need specifics :(

**Comment by unfulvio** [comment]
hey @tomjn you are right and you've been very kind for helping - sorry for the response delay

So, the `public_html` has only a `wordpress` folder; inside `wordpress` there are the WordPress files you'd normally expect to find in `public_html`; instead, in `public_html` I've added an index.php file that contains:

```php
require( dirname( __FILE__ ) . '/wordpress/wp-blog-header.php' );
```

_but adding or removing this doesn't make a difference_

Please note I have to move the files into `public_html/wordpress` manually as the provisioner would try to reinstall WordPress into `public_html`; it doesn't delete `wordpress` though so it's not that big of a deal; I make sure there are not two copies of WordPress inside `public_html` tohugh.

The current `vvv-nginx-custom` looks like this:

```
server {
    listen       80;
    listen       443 ssl http2;
    server_name  {vvv_hosts};
    root         {vvv_path_to_site}/public_html;

    # Nginx logs
    error_log    {vvv_path_to_site}/log/nginx-error.log;
    access_log   {vvv_path_to_site}/log/nginx-access.log;

    # This is needed to set the PHP being used
    set          $upstream {upstream};

    # Enable server push if SSL/HTTP2 is being used for link preload headers
    http2_push_preload on;

    {vvv_tls_cert}
    {vvv_tls_key}

    # Nginx rules for WordPress, rewrite rules, permalinks, etc
    include      /etc/nginx/nginx-wp-common.conf;

    location /wordpress {
                 root {vvv_path_to_site}/public_html/wordpress/;
                 index index.php index.html;
                 try_files $uri $uri/ /wordpress/index.php?$args /wordpress/index.php?q=$uri&$args;
    }
}
```

This is correctly parsed by `vvv-nginx` upon provisioning.

I've tried with other nginx configuration statements as found in https://www.digitalocean.com/community/questions/nginx-wordpress-in-a-sub-directory and that's pretty much it. For example, I tried switching the `try_files with `try_files $uri $uri/ /index.php?q=$uri&$args;`. I admit not having a big knowledge of nginx to fully understand these statements. I got a bit busy yesterday and today so I couldn't invest more time in it. If you think VVV is fine to support subdirectory installs I can try this again later.

In WordPress I've made sure that the site url points to the subdirectory `http://mysite.test/wordpress`. The database is new so there aren't many references, however I did update the few I found, ensuring GUIDs and such point to `/wordpress`.

Script and styles load the `/` homepage, even if they point to .css or .js files, for example `http://mysite.test/wordpress/wp-includes/js/jquery/jquery.js/?ver=1.12.4-wp` points to `http://mysite.test/`

I tried removing ` try_files $uri $uri/ /wordpress/index.php?$args /wordpress/index.php?q=$uri&$args;`, then assets would simply 404, and `/wordpress` would not work (404).

There are no PHP fatal errors.

**Comment by tomjn** [comment]
```
include      /etc/nginx/nginx-wp-common.conf;
```

There's your problem, we mentioned that the rules in this file all assume `/`. Because you didn't replace this with the contents of that file and adjust the rules, they're all still intact and using `/`. That last location block isn't necessary

**Comment by tomjn** [comment]
Looking at https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx-wp-common.conf, nothing in there should be causing a blank white page. Even in the worst case scenario you should get some sort of HTTP response.

Can you tell us more about this blank page? The specific URL you used, and the HTTP response code it gave?

Also are you sure you're setting this up right? I set `wp_type` to `none` on a site so it won't install WP, and just sets up the nginx rules, then manually do the 5 minute install? It even creates the database but leaves it empty

I added this site to `vvv-custom.yml`:

```yaml
  wordpress-four:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      wp_type: none
    hosts:
      - four.wordpress.test
```

Then created a `public_html/wordpress` folder, and dropped a standard WP installation in there. I put this in `public_html/index.php`:

```php
<?php
/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define( 'WP_USE_THEMES', true );

/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wordpress/wp-blog-header.php' );
```

Note that your version doesn't include `WP_USE_THEMES`.

I then visited https://four.wordpress.test and did the standard WP installation, and got a WP install served from a subdirectory, no Nginx config changes of any kind needed

**Comment by unfulvio** [comment]
hey thanks @tomjn works like charm - no need to add custom nginx provision file after all... lol I was really overcomplicating this; thanks for taking the opportunity to add that feature, you never know when it's coming handy I guess

At this point you can close the issue. Maybe you could add a short note in the docs for posterity, with the steps you described above, that should do it.

Please let me know if you have further questions for me as well. 

Cheers
