### ISSUE TITLE
Theme install on provision via custom-site-template

### ISSUE THREAD

**Issue by ironicmoka** [Varying-Vagrant-Vagrants/VVV#1982]
there is any plan to add `wp theme install` support on `custom-site-template`?

I don't know if would be easy-peasy as

```
WP_THEMES=`get_config_value 'install_themes' ''`
if [ ! -z "${WP_THEMES}" ]; then
    for theme in ${WP_THEMES//- /$'\n'}; do
        noroot wp theme install "${theme}" --activate
    done
fi
```

or more complex work, I honestly don't have a clue: I just read the `vvv-init.sh` file to figure out how wp-cli plugin installation is handled on provision but I don't know nothing about how provisioning works.

**Comment by tomjn** [comment]
Actually I think your example is probably 80% of the way there! If you do a
PR we can test and merge :)

**Comment by tomjn** [comment]
Closing this out due to the merge of the PR, thanks for the contributions :D 🎉
