### ISSUE TITLE
Share global var also in utilities

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1984]
Right now VVV define some variables like VVV_CONFIG but is not shared in the utilities.

Do that can help on consistency and simplify the development.

**Comment by tomjn** [comment]
Closed by #1983

**Comment by Mte90** [comment]
Perfect :-D but we are not removing the code specific in tideways and TLS-Ca so maybe is better to reopen the ticket to do that in the next months.
