### ISSUE TITLE
Error on request to repo

### ISSUE THREAD

**Issue by Lepelaar** [Varying-Vagrant-Vagrants/VVV#1991]
## What was The Command Used To Provision?

```shell
vargrant up -provision
```

## What Kind of VVV Provision Was This?

This was a fresh install

## Logs/What Broke?

I found this error:

```
default: The following packages will be upgraded:
    default:   libpcre3 libssl1.1
    default: 2 upgraded, 262 newly installed, 0 to remove and 10 not upgraded.
    default: Need to get 171 MB of archives.
    default: After this operation, 716 MB of additional disk space will be used.
    default: Get:1 http://nginx.org/packages/mainline/ubuntu bionic/nginx amd64 nginx amd64 1.17.5-1~bionic [854 kB]
    default: Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-dejavu-core all 2.37-1 [1041 kB]
    default: Get:3 http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu bionic/main amd64 mysql-common all 1:10.3.18+maria~bionic [5580 B]     
    default: Err:4 http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu bionic/main amd64 mariadb-common all 1:10.3.18+maria~bionic
    default:   400  Bad Request [IP: 85.13.241.50 80]
    default: Get:5 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libssl1.1 amd64 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 [1523 kB]
```

and at the end:

```
default: Fetched 171 MB in 35s (4936 kB/s)
    default: Unable to correct missing packages.
    default: E
    default: :
    default: Failed to fetch http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-common_10.3.18+maria~bionic_all.deb  400  Bad Request [IP: 85.13.241.50 80]
    default:
    default: E: Aborting install.
    default:  * Installing apt-get packages returned a failure code, cleaning up apt caches then exiting
    default: \033[38;5;9m ! Main packages check and install failed, halting provision\033[0m
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I tried several times (also with master) on different days. I have no idea if this is the right place to post this or that the problem is with the repo

## Your Environment

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::develop

Platform: platform-mingw32 windows HyperV-Admin HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled , VVV Path: "C:/vagrant-dev"
Vagrant: v2.2.6, VirtualBox: vN/A
```

Thanx in advance

**Comment by tomjn** [comment]
@Lepelaar I notice those are `http` URLs, which surprises me. So, I checked the Apt source list and noticed some were `http` not `https`, I don't know if this needs to be that way though, but I created a branch to test.

Can you switch to the `tomjn/apt-https` branch with `git checkout origin tomjn/apt-https` then reprovision with a `vagrant up --provision`? Let me know if that works, if it doesn't can you get me a full copy of the output?

**Comment by Lepelaar** [comment]
Hi  Tom, thanks for the fast reply.

My virtualbox version is 6.0.14.
I am on a new machine with windows 10. I have been working with VVV for a few months on an older windows 7 machine.
Yesterday I tried to get the same setup and ran in this problem (with a fresh install of Virtualbox, VVV ,git and VSC).
Because of other issues I have been installing all as admin. This also made the hyper-V think come up which I did not look into yet, because I have no clue about that ;-) I just know it was not showing in the VVV header when I did an install as normal user on this machine.

Also my git knowledge is very limited; I could not get that test branch checked out.
( "git checkout origin tomjn/apt-https" gave me path error).
Could you please give me some pointers how to do that.
Can I do an new "clone" in a fresh location instead?

On your first approach: 
All other resources from that server appear to download fine over http; would it not be strange if the https was the problem?
I could download the specific file (http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-common_10.3.18+maria~bionic_all.deb) but maybe it is corrupted?

**Comment by tomjn** [comment]
Ah sorry can you run it again but remove the word origin?

git pull
git checkout tomjn/tomjn/apt-https

**Comment by Lepelaar** [comment]
It kinda worked... that is: the provisioning finished with some isues (not installing some plugins I put in my config,yml and stuff like that) but no more request error on the repo. WP and vvv.test are working.
So that seems to be fixed with the changes in your branch.

But the strange thing is that with "vagrant status" I get:

PS C:\vagrant-test> vagrant status
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::tomjn/apt-https

Platform: platform-mingw32 windows HyperV-Admin HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled , VVV Path: "C:/vagrant-test"
Vagrant: v2.2.6, VirtualBox: vN/A

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test
Current machine states:

default                   poweroff (virtualbox)

The VM is powered off. To restart the VM, simply run `vagrant up`
PS C:\vagrant-test> vagrant up
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::tomjn/apt-https

Platform: platform-mingw32 windows HyperV-Admin HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled , VVV Path: "C:/vagrant-test"
Vagrant: v2.2.6, VirtualBox: vN/A

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20191030.0.0' is up to date...
A VirtualBox machine with the name 'vagrant-test_92ef48d352c' already exists.
Please use another name or delete the machine with the existing
name, and try again.

VM's are no longer stored in my user dir, but in the locat admin dir. and it seems that vagrant does not know where to find them. Is this the Hyper-V thing playing up? Something really got messed up here :-(
