### ISSUE TITLE
Problem installing at latest develop branch

### ISSUE THREAD

**Issue by robertwt7** [Varying-Vagrant-Vagrants/VVV#1998]
## Expected Behavior

I installed on both, my macbook pro and iMac, both of them have latest macos mojave with fresh installation of the box (I have homestead at both machine too)

## Current Behavior
Problem when installing MariaDB

## Possible Solution
I tried to destroy + reprovision multiple times, also I checked that `db_share_type` is false as well

## Steps to Reproduce (for bugs)
First installation with `vagrant up --provision`

Link to log: https://gist.github.com/robertwt7/1681a153112470fa4985f1c3166b2ce9

## Your Environment

__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::develop

Platform: platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater shared_db_folder_disabled , VVV Path: "/Users/roberttirtasentana/Documents/OneDrive/Macbook/Documents/Career/BlueFit/Dev/VBox/VVV"
Vagrant: v2.2.5, VirtualBox: vN/A

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

YML is not customised at all, used the default from latest develop branch

Weirdly it works on my other machine  though, i'm pretty sure it has the same setups as my macbook (iMac)

**Comment by robertwt7** [comment]
ah sorry, weirdly after I re-do `vagrant up --provision` on my macbook it works. But installing it from fresh does not work on my mac, any idea why?

Thanks

**Comment by ironicmoka** [comment]
Something similar happened to me few hours ago:

no problem on iMac (Catalina, behind 3 commit on develop, but keep working so far and I have not destroyed today).

I'm unable to provision properly on macbook (High Sierra) after a git pull, box update and provision tonight: I get a functional vvv.test page but I keep getting 502 error on provisioned sites urls.

No problem with maria db repo here, I have instead problems with **ppa.launchpad.net/ondrej** and I am unable to provision any utility-core for php versions:

https://gist.github.com/ironicmoka/99d60a081de153eca60728e2384a29de

**Comment by robertwt7** [comment]
hmmm it has a problem with me when installing fresh on both MariaDB and Nginx, however when I re provision it went okay. Previously I destroyed and re-install multiple times and the issue remains

**Comment by tomjn** [comment]
Is this on the latest develop branch? We encountered this and switched to a
different mirror yesterday, you shouldn’t be seeing core ix as a package
source

**Comment by tomjn** [comment]
Also somebody at launchpad messed up their certificates, pap.launchpad has
the SSL certificate for https://private-ppa.launchpad. There’s nothing that
can be done at our end other than to report the problem

**Comment by tomjn** [comment]
Here's the commit, we changed from the coreix mirror to the herrbischoff mirror:

https://github.com/Varying-Vagrant-Vagrants/VVV/commit/45f9227c8048c03e0713bc7cd4e448983e4e834e#diff-4f72a073f9a023e6d4957228f433b0e9

**Comment by robertwt7** [comment]
Right that's odd, yeah that URL was me switching to master. So I did destroy and re-create vagrant 2 times on develop before switching to master and getting the same error. Either way, its all good after re-provisioned. I'm not planning to destroy it anytime soon, want to try to play around first. If anyone has the same issue during installation feel free to open it up again.

Thanks for the help!

**Comment by ironicmoka** [comment]
Keep updating here 'cause it's develop provisioning related:

Now on both machines reprovisioning on develop go wrong: box update, pull, destroy, provision.
Still getting problems with ppa.launchpad and utility core packages

I just tried reprovision one on develop and the other switched on master, and everything works fine on master.

I believed both master and develop shared most of packages but looks like some on develop are causing errors, at least here on macs (High Sierra and Catalina).


Here's the gists:

Fail on develop
https://gist.github.com/ironicmoka/c8ec8320fa2768a1565afe36c41d79d7

Ok on master
https://gist.github.com/ironicmoka/a8eafb246968ac03593d71f18451c0ca
