### ISSUE TITLE
Problem provisioning on develop

### ISSUE THREAD

**Issue by ironicmoka** [Varying-Vagrant-Vagrants/VVV#1999]
## What was The Command Used To Provision?

```shell
vagrant box update
vagrant destroy
vagrant up --provision
```

## What Kind of VVV Provision Was This?

This was a reprovision of an already working VVV after a git pull

## Logs/What Broke?

As already mentioned on #1998 i keep getting problems on reprovision on develop branch.

On both machines (iMac and Macbook) reprovisioning on develop go wrong: box update, pull, destroy, provision.

Still getting problems with ppa.launchpad and utility core packages

I just tried reprovision one on develop and the other switched on master, and everything works fine on master.

I believed both master and develop shared most of packages but looks like some on develop are causing errors, at least here on macs (High Sierra and Catalina).

## Gists

Here's the gists:

Fail on develop
https://gist.github.com/ironicmoka/c8ec8320fa2768a1565afe36c41d79d7

Ok on master
https://gist.github.com/ironicmoka/a8eafb246968ac03593d71f18451c0ca

**Comment by tomjn** [comment]
@ironicmoka can you retest with `develop`? We just reverted a change to apt repository URLs that should fix this

**Comment by ironicmoka** [comment]
yep, fixed!
