### ISSUE TITLE
System date incorrect after sleep/wake

### ISSUE THREAD

**Issue by ChrisHardie** [Varying-Vagrant-Vagrants/VVV#2006]
Expected Behavior: when I sleep and then wake my host system (macOS), the system date/time on the Vagrant machine should reflect the current time.

Current Behavior: when I sleep and then wake my host system, the system date/time on the Vagrant machine reflects the time when the host system was put to sleep.

Possible Solution: include and run ntpdate on the Vagrant machine

Steps to Reproduce (for bugs)
1. Confirm that the Vagrant system time matches the current host system time
2. Sleep the host system for several hours
3. Wake the host system
4. Confirm that the Vagrant system time is off by several hours

Your Environment: VVV 3.2.0 on macOS 10.14.6

**Comment by tomjn** [comment]
hmmm I think there have been references in the past to NTP, how familiar are you with setting that up? Is it just a  package to install?

**Comment by ChrisHardie** [comment]
Today I ran

```
$ sudo apt install ntpdate
$ sudo apt install ntpsec-ntpdate
$ sudo service ntp start
```

and that got the system time back on track. A one-time command to update the clock would be something like `$ sudo ntpdate pool.ntp.org`.

**Comment by tomjn** [comment]
So it looks like we've been install the `ntp` package to resolve this issue

**Comment by tomjn** [comment]
I've started on https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2007 but it might be that the service is already there and isn't running, and the additional packages aren't necessary
