### ISSUE TITLE
MongoDB not working with PHP 7.3 or PHP 7.4

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#2008]
If I set-upstream, nginx_upstream: php73 or nginx_upstream: php74 
then MongoDB not working for those sites.

**Comment by Mte90** [comment]
Seems a problem on xhgui that require a composer update for the dependencies.
There are new releases of the library that support php 7.4 https://github.com/alcaeus/mongo-php-adapter/releases

So I think that should be enough to remove `/VVV/www/default/xhgui/` and do a new provision so will be updated.
Anyway what errors are you getting?

**Comment by Mte90** [comment]
In the mean time I changed the provisioner https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/42

**Comment by tomjn** [comment]
The mongodb provisioner never attempts 7.4, unsure of 7.3

I don’t believe this is related to the tideways provisioner

**Comment by Mte90** [comment]
Well in my investigation we need to update the composer dependence of xhgui to support php 7.4

**Comment by debabratakarfa** [comment]
Any update on it?

**Comment by Mte90** [comment]
If https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/43 didn't fixed
We have a patch but no one that can test it https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/42

**Comment by tomjn** [comment]
@debabratakarfa we'd need to know if the changes in https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/43 had any effect, can you retest but with the latest `develop` branch and reprovision?

**Comment by debabratakarfa** [comment]
If any particular site if set  `nginx_upstream: php73` / `nginx_upstream: php74` and if I check `<?php phpinfo(); ?>` then I am not able to found MongoDB where in  `nginx_upstream: php72` I can see MongoDB support enabled.

**Comment by tomjn** [comment]
So it seems this prevents the fix from being applied to existing installs:

```sh
if [[ ! $(command -v mongo) ]]; then
    install_mongodb
fi
```

**Comment by tomjn** [comment]
@debabratakarfa can you test https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/51 ? There's instructions on the PR on how to test it out, you may need to delete your `provision/utilities/core` folder before reprovisioning

**Comment by Mte90** [comment]
@debabratakarfa can you test now with a new provision?

**Comment by Mte90** [comment]
Just another ping for @debabratakarfa

**Comment by debabratakarfa** [comment]
Hi @Mte90 
Sorry, I was busy. I will do test, and update you.
Ty.

**Comment by Mte90** [comment]
any updates?

**Comment by tomjn** [comment]
I'm going to close this out, but if this is still an issue let us know and we'll reopen
