### ISSUE TITLE
Documentation about config needs updating

### ISSUE THREAD

**Issue by timichango** [Varying-Vagrant-Vagrants/VVV#2010]
Per the release notes for 3.2.0: "The biggest change is that we no longer use vvv-custom.yml, we’ve moved to config/config.yml."

The new site setup documentation here: _https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/_ still makes reference to the old `vvv-custom.yml` file setup, which is more than a bit confusing.

Sooo I feel like I now need some clarification: in the old setup (`vvv-config.yml` + `vvv-custom.yml`), the ostensible purpose of vvv-custom.yml was to prevent it from inadvertently being overwritten by pulling a VVV update, right?  In the new setup, however, there's only the one `config.yml` — no custom.  Is it safe to assume that the intention is that this file (derived from `default-config.yml`) will also not be overwritten in the future? Can we treat `config.yml` as functionally equivalent to `vvv-custom.yml`?

**Comment by Mte90** [comment]
We missed that reference on our search. Now the only file is `config/config.yml`.
The default is like the default skeleton that on runtime is replace with your custom .
We will update asap :-)

**Comment by timichango** [comment]
Thanks @Mte90 !

**Comment by tomjn** [comment]
I've updated most references to `vvv-custom.yml` to `config/config.yml` where I could find them via githubs search
