### ISSUE TITLE
VBoxManage Error at "Booting VM" stage 

### ISSUE THREAD

**Issue by anthonyalvarez** [Varying-Vagrant-Vagrants/VVV#2011]
## What was The Command Used To Provision?

```shell
vagrant up
```

## What Kind of VVV Provision Was This?

This was a fresh install

## Logs/What Broke?
Hello,

Getting a horific VBoxManage error while at `Booting VM` stage.
Wondering where to find help for this situation.
Do not know where to look for help.
Is this a Vagrant or VirtualBox issue?
Which forum should this question be sent too?

Meanwhile, successfully installed [another random vagrant box](https://app.vagrantup.com/laravel/boxes/homestead-7) and was able to successfully run both `vagrant up` and `vagrant ssh` commands on that box,
It seems like vagrant is setup properly.

My goal is to setup [Varying Vagrant Vagrants (VVV) Wordpress Local Developmet](https://varyingvagrantvagrants.org/) server.

Any clues appreciated.
Thank you.

# Output of VVV listed below.
=====================

```
(antho@DESKTOP-LHRUNLM MINGW64 ~/Documents/vagrant/vvv (master)
$ vagrant up
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::master

Platform: platform-mingw32 windows vagrant-hostsupdater NoColour shared_db_folder_disabled , VVV Path: "C:/Users/antho/Documents/vagrant/vvv"
Vagrant: v2.2.6, VirtualBox: vN/A

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20191125.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "d8aa572a-8e94-4e0c-80af-8bc51a667875", "--type", "headless"]

Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole)
```
 

## Steps to Reproduce (for bugs)

1. git clone -b master git://github.com/Varying-Vagrant-Vagrants/VVV.git ~/Documents/vagrant/vvv
2. cd ~/Documents/vagrant/vvv
3. vagrant up

## Your Environment

    - Operating System: Win10x64
    - Vagrant Version: 2.2.6
    - Virtual Box Version: 6.0.14 r133895 (Qt5.6.2)

**Comment by Mte90** [comment]
It seems a virtualbox bug on windows 10 https://www.virtualbox.org/ticket/14832 we cannot do so much for that problem.

**Comment by tomjn** [comment]
Reading from the link, it looks like you need to disable and enable the
network interface. I’d weigh in on that ticket to show you’re having
problems, and if doing that helps. There’s not much of anything that can be
done from the VVV end

**Comment by anthonyalvarez** [comment]
Thanks for reply.

Can anyone provide advise as to which prior version of VirtualBox works best with Windows 10 and VVV?

Does anyone know the procedure to  disable and enable the VirtualBox network interface?


Already tried two other solutions listed below but ironically each of them is failing at exactly the same way, which is "Booting VM" stage.

1. [Seravo](https://github.com/Seravo/wordpress)
2. [VCCW](http://vccw.cc/)

Thank you @Mte90 and @tomjn ! Your comments are on the right track. 
There might be something wrong with my PC's VirtualBox network setup.
How can Windows 10 networking for Virtualbox be reset to factory defaults?
I remember changing Win10 networking while doing [Hyper-V testing](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) on a prior project.
Have a good weekend.

**Comment by tomjn** [comment]
It’s a virtualbox bug, and it appears disabling and enabling is a Windows
network thing, I’m a MacOS user but any generic guide on renaming and
disabling Network adapter in windows should work

**Comment by Mte90** [comment]
I'm closing because it is a problem that is not from VVV
