### ISSUE TITLE
Site provision - vvv_hosts is not populated as expected

### ISSUE THREAD

**Issue by mathieuhays** [Varying-Vagrant-Vagrants/VVV#2019]
I'm using the develop branch, I've pulled the latest changes. The provision used to work before I pulled the latest changes.

## Expected Behavior

Generate nginx config file with the server_name line filled-in correctly.

## Current Behavior

The server_name variable in the nginx config file is empty.

## Your Environment
```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.3.0-git::develop

Platform: platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater vagrant-disksize shared_db_folder_disabled , VVV Path: "/Users/math/Projects/VVV"
Vagrant: v2.2.5, VirtualBox: v5.2.30r130521
```

## Logs

vvv-nginx.conf in my provision folder:
```
server {
    listen       80;
    listen       443 ssl;
    server_name  {vvv_hosts};
    root         {vvv_path_to_site}/public_html;

    # Nginx logs
    error_log    {vvv_path_to_site}/log/error.log;
    access_log   {vvv_path_to_site}/log/access.log;

    # This is needed to set the PHP being used
    set          $upstream {upstream};

    ssl_certificate /vagrant/certificates/www.mathieuhays.co.uk/dev.crt;
    ssl_certificate_key /vagrant/certificates/www.mathieuhays.co.uk/dev.key;

    # Nginx rules for WordPress, rewrite rules, permalinks, etc
    include      /etc/nginx/nginx-wp-common.conf;
}
```

generated config file in `/etc/nginx/custom-sites`
```
server {
    listen       80;
    listen       443 ssl;
    server_name  ;
    root         /srv/www/www.mathieuhays.co.uk/public_html;

    # Nginx logs
    error_log    /srv/www/www.mathieuhays.co.uk/log/error.log;
    access_log   /srv/www/www.mathieuhays.co.uk/log/access.log;

    # This is needed to set the PHP being used
    set          $upstream php;

    ssl_certificate /vagrant/certificates/www.mathieuhays.co.uk/dev.crt;
    ssl_certificate_key /vagrant/certificates/www.mathieuhays.co.uk/dev.key;

    # Nginx rules for WordPress, rewrite rules, permalinks, etc
    include      /etc/nginx/nginx-wp-common.conf;
}
```

site configuration in `config/config.yml`
```
sites:
  www.mathieuhays.co.uk:
    hosts:
      - www.mathieuhays.test
```

Provisioner log during `vagrant reload --provision`
```
==> default: Running provisioner: site-www.mathieuhays.co.uk (shell)...
    default: Running: /var/folders/69/frvhz12n0fq19q6twr1njfk00000gn/T/vagrant-shell20191205-36707-sptj6g.sh
    default:  * Running provisioner for site www.mathieuhays.co.uk
    default:  * The site: 'www.mathieuhays.co.uk' does not have a site template, assuming custom provision/vvv-init.sh and provision/vvv-nginx.conf
    default:  * Searching for a site template provisioner, vvv-init.sh
    default:  * Found vvv-init.sh at /srv/www/www.mathieuhays.co.uk/provision/vvv-init.sh
    default:  * Script output will be logged to: log/provisioners/20191205-164144/provisioner-site-www.mathieuhays.co.uk.log
    default:  * Site provisioner script finished successfully
    default:  * Adding domains to the virtual machine's /etc/hosts file...
    default:  * Adding hosts from the VVV config entry
    default:  * Reloading Nginx
    default:  * www.mathieuhays.co.uk provisioning finished in 1 seconds
```

The custom domain name `www.mathieuhays.test` was properly added to `/etc/hosts` on the host during provision.

**Comment by mathieuhays** [comment]
## Potential solution
Change the following line in `provision-site.sh`:
```
SITE_ESCAPED=$(echo "${SITE}" | sed 's/\./\\\\./g')
```

to:
```
SITE_ESCAPED=$(echo "${SITE}" | sed 's/\./\\./g')
```

This fixed it for me but I'm not sure if it could break other things.

`SITE_ESCAPED` was returning something like this: `www\\.my-site\\.test`, with the fix `www\.my-site\.test`.

**Comment by tomjn** [comment]
I’m not entirely sure which characters are being escaped but Codacy wants
to change it for a bash substitution instead as it’ll be faster/cleaner

**Comment by tomjn** [comment]
Also `vvv_hosts` is maintained for legacy purposes, try to move away from it at the earliest opportunity ( did you know that on the first provision, there is no `vvv_hosts` file to load the hosts from as the site hasn't been cloned yet? So sites need a double provision for `vvv_hosts` to work if it's a fresh checkout )

**Comment by mathieuhays** [comment]
What would you recommend using instead? I based my own config on the default [custom-site-template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template) which seems to be using `vvv_hosts` as well.

**Comment by tomjn** [comment]
It doesn't use `vvv_hosts` at the moment, perhaps it did in the distant past. I think at one point it tried to auto-generate that file for subdomain multisites. The preferred method is to specify the hosts in your config file. That's the most performant and the optimal way, it also makes the sites show up in the dashboard.

`vvv_hosts` files usually require the provisioners to do a folder search which can be costly. There are optimisations to explicitly check particular locations to avoid this though. I'd have liked to have deprecated them in VVV 3, and that was the plan for VVV 2, but they were so widespread it would have been needlessly painful for users.

**Comment by tomjn** [comment]
As for testing this issue:

```shell
❯ echo "test" | sed 's/\./\\\\./g'
test
❯ echo "test.com" | sed 's/\./\\\\./g'
test\\.com
```

Can you send over a copy of your main provisioner script? It may just be that you need to update it to match the current latest and greatest ( if it's as old as I think it is, you might be missing out on a feature or two such as HTTPS support )

**Comment by mathieuhays** [comment]
I think I didn't explain the issue properly, the `vvv_hosts` I'm referring to is the variable populated by `provision/provision-site.sh`, not the file you would put in your provision folder.

in provision-site.sh the `get_hosts` function comes back empty because of the double escaping done on the `SITE_ESCAPED` variable.

**Comment by tomjn** [comment]
hmmm I don't see how that has anything at all to do with `vvv_hosts`, thanks for the clarification, those are 2 unconnected systems, entirely independent of eachother

**Comment by tomjn** [comment]
I'm testing with `SITE_ESCAPED=${"${SITE}"//./\\.}`

**Comment by tomjn** [comment]
I can confirm this issue has nothing to do with `vvv_hosts`, the problem is escaping dots

For an explanation of what's happening for those reading, let say we want to grab the site test from the config via shyaml:

```
sites:
  test:
    hosts:
       - test.test
```

We can use `shyaml get-values "sites.test.hosts"`, but if we use a value that has full stops in it, we need to escape the value somehow:

`shyaml get-values "sites.www.bananas.test.hosts"` is looking for:

```yaml
sites:
  www:
    bananas:
      test:
        hosts:
          - etc..
```

**Comment by tomjn** [comment]
I had success with `SITE_ESCAPED="${SITE//./\\.}"`

**Comment by tomjn** [comment]
@mathieuhays can you update to the latest `develop` and test it out? You might need to provision a fresh site, my local test ended up provisioning WP with a site url of `www.banana.test.test` because of the way the bug worked

**Comment by mathieuhays** [comment]
It's working now! Thanks @tomjn
