### ISSUE TITLE
SQL backups are imported with './' prepended to the database name

### ISSUE THREAD

**Issue by mathieuhays** [Varying-Vagrant-Vagrants/VVV#2021]
## Expected Behavior

backup files in `/database/sql/backups` are automatically imported when the corresponding database doesn't exist using the name of the file without the extension.

## Current Behavior

For a given file `mybackup.sql` in the backups folder, the data is imported into a database called `./mybackup` instead of `mybackup`.

## Steps to Reproduce (for bugs)

1. have a backup sql file in `database/sql/backups`
2. provision VVV

## Your Environment
```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.3.0-git::develop

Platform: platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater vagrant-disksize shared_db_folder_disabled , VVV Path: "/Users/math/Projects/VVV"
Vagrant: v2.2.5, VirtualBox: v5.2.30r130521
```

## Logs
As seen during provision:
```
    default:  * Creating the ./wwwmathieuhayscouk table if it doesn't already exist, and granting the wp user access
    default: mysql -u root -proot ./wwwmathieuhayscouk < ./wwwmathieuhayscouk.sql
```

**Comment by mathieuhays** [comment]
I just realised that the log says "Creating the *** table" but I believe in reality it should say "Create the *** database"

**Comment by tomjn** [comment]
Can you give the `tomjn/fix-sql-import` branch a test? I believe I fixed the issue

**Comment by mathieuhays** [comment]
I'm getting a few errors. The database in question already exists if that makes a difference.

```
default:  * Creating the `` database if it doesn't already exist, and granting the wp user access
    default: ERROR
    default:  1102 (42000)
    default:  at line 1
    default: : Incorrect database name ''
    default: ERROR
    default:  1049 (42000)
    default:  at line 1
    default: : Unknown database './wwwmathieuhayscouk'
    default:  * Error - Create `` database via init-custom.sql before attempting import
```

**Comment by tomjn** [comment]
@mathieuhays fixed in  https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2022/commits/79dc4ac7dbdb9d3e4f426d7e5492fd50a0424090 I missed an underscore in a variable name

**Comment by mathieuhays** [comment]
@tomjn All fixed indeed. Thanks again!
