### ISSUE TITLE
Validate Nginx Upstream values

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2028]
At the moment you can specify a different version of PHP like this:

```yaml
nginx_upstream: php73
```

But there's nothing validating that `php73` actually exists, and a user could put in nonsensical values such as:

```yaml
nginx_upstream: banana
```

The end result is a provision failure without any explanation

**Comment by tomjn** [comment]
This can be done  by checking for the associated config file in `/etc/nginx/upstreams`:

```yaml
vagrant@vvv:/etc/nginx$ ls upstreams/
php56.conf  php70.conf  php71.conf  php72.conf  php73.conf  php74.conf
```

**Comment by Mte90** [comment]
Just as reference the line involved where we need this validation is https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L9

**Comment by tomjn** [comment]
I would place it in `vvv_provision_site_nginx` before https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L79

If the upstream value doesn't exist, it should fallback to 7.2 and then say so in the log, then list all the currently valid options. Doing that should just be a matter of listing the files in `/etc/nginx/upstreams` without the `.conf` part
