### ISSUE TITLE
Why is VVV's configuration done as one massive file rather than modularized?

### ISSUE THREAD

**Issue by davidshq** [Varying-Vagrant-Vagrants/VVV#2029]
I'm curious - did the VVV Vagrantfile evolve over time as one large configuration file or was it a design decision?

I ask because I'm used to splitting code across multiple files -- and the Vagrantfile for VVV feels a bit difficult to navigate. If this is the preferred method for VVV, great. If it is something that came about by chance, I'd be interested in helping modularize* it.

I can see two places in particular where modularization might be useful:
- Logic related to Vagrant 1.x - this could be called from a separate file only if necessary.
- Provider related logic - each provider could be split out into a separate file.

From my limited perspective it seems like doing this would make it easier for folks to customize VVV. If they are running VirtualBox they don't need to even open the files for Hyper-V, Parallels, etc. - and vice versa.

One could split it out further with perhaps the sections most likely to be edited having their own file. I'm not sure what parts those are other than perhaps folder mappings...

* This appears to be possible: https://stackoverflow.com/questions/46460383/is-it-possible-to-load-a-vagrantfile-config-from-within-another-vagrantfile

**Comment by tomjn** [comment]
> I'm curious - did the VVV Vagrantfile evolve over time as one large configuration file or was it a design decision?

Historic reasons, @LoreleiAurora started work on modularising things but lost the work when she wiped a machine ( not much was lost ). Modularising the vagrant file would be good, I'm keen to simplify it though.

> Logic related to Vagrant 1.x - this could be called from a separate file only if necessary.

This can all go, We require Vagrant 2.x at the top of the file, anybody trying to use v1 should upgrade.

> Provider related logic - each provider could be split out into a separate file.

I had in my mind a base class that could be overriden for each provider, overriding things for each provider is where most repetition comes from at the moment. Putting the splash screen stuff in a separate file would be nice too. I'd be happy if just those 2 things happened.

As for editing the Vagrant File, I'd prefer that new functionality isn't put in there unless there's no other way to implement it. I'd like to be able to run the provisioners in Docker or a test environment without having to rely on VirtualBox/Vagrant in the future, and Vagrant itself isn't that fast. It also prevents us running code inside the VM if we have to fire up a Vagrant command on the host.

E.g. provisioning a site from the dashboard, the hosts part is the only bit that really needs the vagrant commands involvement

**Comment by davidshq** [comment]
Thanks Tom! I'll play around with the Vagrantfile and see what I can come up with.

**Comment by Mte90** [comment]
I hope that this https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/160 will help with this task.
Do you have any updates @davidshq?

**Comment by davidshq** [comment]
@Mte90 - Unfortunately,  I haven't had much opportunity to work on this...and am not seeing an opening in the near future...

**Comment by davidshq** [comment]
@tomjn Looking at the Vagrantfile, here is the section which may refer to 1.x, but I'm a little unclear on whether it refers only to converting 1.x or if it is also used for configuring 2.x?

```
 # Configurations from 1.0.x can be placed in Vagrant 1.1.x specs like the following.
  config.vm.provider :virtualbox do |v|
    # Move the ubuntu-bionic-18.04-cloudimg-console.log file to log directory.
    v.customize ["modifyvm", :id, "--uartmode1", "file", File.join(vagrant_dir, "log/ubuntu-bionic-18.04-cloudimg-console.log")]

    v.customize ["modifyvm", :id, "--memory", vvv_config['vm_config']['memory']]
    v.customize ["modifyvm", :id, "--cpus", vvv_config['vm_config']['cores']]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # see https://github.com/hashicorp/vagrant/issues/7648
    v.customize ['modifyvm', :id, '--cableconnected1', 'on']

    v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    v.customize ["modifyvm", :id, "--audio", "none"]
    v.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//srv/www", "1"]
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//srv/config", "1"]

    # Set the box name in VirtualBox to match the working directory.
    vvv_pwd = Dir.pwd
    v.name = File.basename(vagrant_dir) + "_" + (Digest::SHA256.hexdigest vagrant_dir)[0..10]
  end
```

**Comment by tomjn** [comment]
@davidshq I'm unsure, it's definitely used in Vagrant 2, but it may be using a backwards compatible  format. I would strongly question the value/validity of that comment as it currently stands

**Comment by Mte90** [comment]
@msaggiorato started a refactoring to the whole VVV code and simplified a bit also the vagrantfile.
Maybe we can close this ticket?
