### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT when trying to hit vvv dashboard while connected to WiFi

### ISSUE THREAD

**Issue by trevasco** [Varying-Vagrant-Vagrants/VVV#2037]
macOS Sierra 10.12.6

VVV 3.2.0
branch: master

Vagrant 2.2.6
VirtualBox 5.2.34

If I disconnect from WiFi I am then able to hit vvv.test

I've tried following steps, but did not work.
```
vagrant halt
vagrant destroy
vagrant box update
vagrant plugin update
vagrant up --provision
```

full output from provision:
https://gist.github.com/trevasco/50f177494e7c2f9de0a94291f2d06ab9

VirtualBox settings after running above commands:
<img width="865" alt="Screen Shot 2019-12-23 at 11 08 09 AM" src="https://user-images.githubusercontent.com/6633534/71375913-97b6e000-2574-11ea-9db1-df132765af24.png">
<img width="650" alt="Screen Shot 2019-12-23 at 11 08 27 AM" src="https://user-images.githubusercontent.com/6633534/71375919-9e455780-2574-11ea-8017-092d372cdd86.png">
<img width="650" alt="Screen Shot 2019-12-23 at 11 08 34 AM" src="https://user-images.githubusercontent.com/6633534/71375922-a1404800-2574-11ea-836f-00331c2c2363.png">

**Comment by trevasco** [comment]
Created a new issue in main Vagrant repo, as it seems more suitable for there. Feel free to close and use that.

https://github.com/hashicorp/vagrant/issues/11283

**Comment by tomjn** [comment]
@trevasco I see you're using VirtualBox v5.2.34, can you update to v6.0.14? ( note that at the time of writing, Vagrant 2.2.7 hasn't been released yet which is needed for Vbox 6.1 compatibility, so use v6.0.14 )

**Comment by tomjn** [comment]
Also if you can connect when wifi is off, but not when it is on, this implies networking adapter issue. Reprovisioning should have zero effect on this unless you change your underlying software versions, or the network adapter settings are changed, but eitherway this is extremely unusual, and  other than updating vagrant and virtualbox, and rebooting, I have no suggestions or indications that could help

**Comment by tomjn** [comment]
Except, have you tried the `develop` branch? It's a longshot

**Comment by tomjn** [comment]
Also, is it possible that you have security software or corporate DNS/proxy Antivirus software that might mess with the networking?

**Comment by trevasco** [comment]
thanks @tomjn, updating VirtualBox to v6.0.14 seemed to do the trick
