### ISSUE TITLE
Problem provisioning with Vagrant 2.2.6, VirtualBox 6.1.0 on Fedora 31 (unmet dependencies)

### ISSUE THREAD

**Issue by unfulvio** [Varying-Vagrant-Vagrants/VVV#2039]
I've recently upgraded from Fedora 30 to Fedora 31 and unfortunately Varying Vagrant Vagrants stopped working.

The first thing I noticed is an [incompatibility between Vagrant 2.2.6 and VirtualBox 6.1](https://github.com/hashicorp/vagrant/issues/11249) - but this can be addressed with a [workaround](https://github.com/oracle/vagrant-boxes/issues/178#issue-536720633). And the upcoming version 2.2.7 of Vagrant should fix that.

The second problem which I was unable to fix appears having to do with `vagrant-hostsupdater`. 

I can't install anymore this plugin required by VVV, and the following error is thrown by Vagrant when I try to install it:

```shell
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies listen (~> 3.0.0) and listen (= 3.1.5)
  Activated listen-3.1.5
  which does not match conflicting dependency (~> 3.0.0)

  Conflicting dependency chains:
    listen (= 3.1.5), 3.1.5 activated

  versus:
    middleman-core (= 4.2.1), 4.2.1 activated, depends on
    listen (~> 3.0.0)
```

Mine is a Fedora vanilla install with only Vagrant, Ruby, Virtualbox. 

I tried uninstalling all of these, and also starting fresh with VVV, but while I can do something about VirtualBox, I can't seem to get around the vagrant plugins failure.

Unfortunately I'm not sufficiently knowledgeable of the Ruby environment/language to address the issue.

Any suggestions?

Thanks, and happy new year

**Comment by unfulvio** [comment]
never mind looks like I found a workaround also for the 2nd issue by running the flag to ignore dependencies:

```shell
VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-hostsupdater
```

thanks

**Comment by tomjn** [comment]
Ah thanks for the work around, sorry I didn’t get to you in time. Can you
post the work around and the error for the plugin in the vagrant hosts
updater Github so they know? Would be good not to need to the workaround

In the meantime I wonder if we can get this into the troubleshooting page

**Comment by unfulvio** [comment]
workaround for lack of VB 6.1 support in Vagrant:

workaround for hostsupdater, just remove/expunge old plugin, then run from command line:

```shell
VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-hostsupdater
```

I found out you can run vagrant commands with this variable from the command line and it will ignore strict checks on dependencies

I will file also a ticket on the plugin repo so they are informed about it, good idea

**Comment by unfulvio** [comment]
for your reference: https://github.com/cogitatio/vagrant-hostsupdater/issues/185
