### ISSUE TITLE
is_utility_installed not available inside provisioners

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2041]
I did a quick update to latest `develop` and reprovisioned, the latest version of the core dev template gave me this in the terminal output:

```
    default: /tmp/vagrant-shell: line 76: is_utility_installed: command not found
```

**Comment by Mte90** [comment]
Uhm we added the path in https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/bash_profile#L65, maybe doesnt' have execution permission?

**Comment by tomjn** [comment]
That’s not the issue, it works as expected in shells.  Note that we never
call just “xdebug_on” etc we call the full path version

**Comment by tomjn** [comment]
I don’t believe we can rely on path adjustments in the bash profile file in
vagrant provisions. More importantly, we don’t have to

**Comment by Mte90** [comment]
So bash scripts cannot find the command in this cases https://github.com/Varying-Vagrant-Vagrants/VVV/search?q=is_utility_installed&unscoped_q=is_utility_installed
If we use the full path should works, maybe during provision the `$PATH` variable is not defined and the error happens, instead running them has that variable.

**Comment by tomjn** [comment]
PATH is ammended in `bash_profile` at https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/bash_profile#L65

I don't believe `bash_profile` is executed in a vagrant provisioner, especially since that's the `bash_profile` for the vagrant user and provisioners run as root.

If you SSH in and run `sudo su` you'll see it has a different bash profile file, prompt, and commands such as `xdebug_on` no longer work
