### ISSUE TITLE
Vagrant send email from inside box to outside world

### ISSUE THREAD

**Issue by janw-me** [Varying-Vagrant-Vagrants/VVV#2048]
This is a weird problem that I also don't fully understand.

Last week I set up a new site synced the database and reset all users (a couple 1000) passwords to _123_.  It makes testing easy, it's a thing I've been doing for at least a year. Never a problem, including for this site.

But this time we were getting a few support emails from people saying the password was reset.
**Some way emails send in the vagrant where arriving out in world.**

Example email headers I got in support:
![2020-01-19_20-44](https://user-images.githubusercontent.com/1026882/72687288-aacdb900-3afc-11ea-9273-6896e23e7229.png)

The rest of the day was cleaning up after this, and trying a few things. It was _not_ a fun day, to keep it professional.....

Details
-------------

- I destroyed the box, pretty much immediately to make sure there wasn't some invisible queue.
- There was no SMTP used, it was vvv.
- I have not been able to get an other real email out into the world after this incident.
- There is no record how many emails have been send.
- Most likely it was just a vanilla box V3.2.0, I'm like 90% sure.
- I am 100% sure I've never (un)installed/tweaked anything regarding mailhog/email/ect inside the box.

The core of the script I ran was pretty much this:  
wp-cli:  `wp eval-file  reset-password.php` >>

		$userQ = new \WP_User_Query(array());
		foreach ( $userQ->get_results() as $user ) {
			$user->user_pass = '123';
			wp_update_user( $user );
		}

Steps to reproduce
------------------------
This will not send out a real email into the world. But will bypass mailhog.
I think this is the main issue to fix.

1 create a fully new vagrant, everything default
2. login in one.wordpress.test/wp-admin
3. create new user
4. check mailhog, success
5. `vagrant ssh `
6. `cd /srv/www/wordpress-one/public_html/`
7. `wp user create test2 me+test2@janw.me --send-email`
8. check mailhog, no email

Some command I found out while trying to debug this.

 - `sudo cat /var/log/mail.log`
 - `sudo mailq`
 - `cat /var/mail/vagrant` This shuld be the email itself

This problem exists in [develop](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/985cb6b7042206b4bfc6be1f9cd5aa595203ca73) and [master](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/d0eeb9f55919f8112f4355363148ae43915fae65) but not [3.1.0](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/c727e91c4c5c3ec86db80a11ec1571a085f83854) and [3.0.0](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/c9d33ff5a7831432d4988f981548d7fbd8c27734) 

Requested solution
-------------------------

Make wp-cli/commands send email to mailhog again

If there is anything I can do to help let me know.

**Comment by Mte90** [comment]
Well VVV sends email to the world like any development environment, if they are not catched by mailhog it is another problem.

**Comment by janw-me** [comment]
All email was catched by mailhog in 3.1.0 and below.
So something broke  after that. That's also why I suggest to fix mailhog to catch commands agian.

**Comment by tomjn** [comment]
MailHog etc are installed via the utilities repo, they follow a separate release cycle from VVV itself. I'm surprised that the email wasn't rejected outright by spam filters.

Does this happen on a fresh provision, and if so, can you share some information about your environment? What does the provisioner log for MailHog look like?

**Comment by Mte90** [comment]
I tested now mailhog and catch the emails without issue and I am using the develop branch.
You destroyed your box now but I am using also the last box.

**Comment by janw-me** [comment]
I tested this yesterday on 4 version, develop, master, 3.0.0 and 3.1.0.
For each version I destroyed the box, switched branch/tag, and vagrant up.

@Mte90 Did you test it with a cli command like for example how I described in step 5-8 ?
Creating a user in the interface wp-admin did work.

**Comment by Mte90** [comment]
I tested also with your command and worked.

![immagine](https://user-images.githubusercontent.com/403283/72721910-61717e00-3b7d-11ea-8c9d-f758b41d2130.png)

Maybe you didn't run a `vagrant provision` some some time?

**Comment by janw-me** [comment]
@Mte90 you ran this against the develop branch?
Yesterday I tested this with a newly freshly installed box. So a provision should not be an issue with a new box right?
I'll give it another try later this evening.

**Comment by Mte90** [comment]
Yes with the develop branch, with a provision before (I didn't have mailhog installed).
Maybe you are using a different php version for php-cli? AS default is configured for php7.2 https://github.com/Varying-Vagrant-Vagrants/VVV/blob/2539dd8b9424484b3c79a87bd0f5658ac2e33352/provision/provision.sh#L685 and latest vvv 3.2 version added that support for all the php version with a new utility `php`

**Comment by janw-me** [comment]
I tweaked nothing, for the 4 test I did I cloned a new box, and just upped.
So no tweaks in `vvv-custom/yml` or `confog/config.yml` (depending on the version.)

**Comment by tomjn** [comment]
In the current `develop` branch I used `wp shell` to run `wp_mail` manually, and it was caught by mailhog:

```php
vagrant@vvv:/srv/www/wordpress-one$ wp shell
wp> wp_mail( 'test@tomjn.com', 'vvv test', 'testing testing 123' );
PHP Notice:  Undefined index: SERVER_NAME in /srv/www/wordpress-one/public_html/wp-includes/pluggable.php on line 330
Notice: Undefined index: SERVER_NAME in /srv/www/wordpress-one/public_html/wp-includes/pluggable.php on line 330
=> bool(true)
wp> 
```

Note the undefined index warnings are unrelated.

My only thoughts are that MailHog might not have provisioned correctly when it first provisioned, but this isn't something you could check for by sending emails, but rather by checking the installation itself.

It would be **extremely** useful to see the MailHog provisioning from the terminal, it's in the main provisioner step. It may not be possible to resolve this issue without that information.

Here's where the code that installs MailHog is located:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L699

**Notice that it hasn't been changed in at least a year**

Unanswered questions:

 - Is MHSendmail installed?
 - Is the MailHog service running?
 - What does your `config/config.yml` look like?
 - We're still missing the information requested in the original issue template, which I've asked for twice now :( OS/Vagrant/VirtualBox versions
 - We're missing the provisioner log for MailHog, there may be a really obvious message indicating the issue
 - Is this a vanilla WP with default plugins/themes?

**Comment by tomjn** [comment]
Of particular note, I'd like to know what the PHP config value for `sendmail_path` is in CLI on your system. You can get it from the browser via PHP info which can be accessed from the dashboard, for CLI you can run the following:

```shell
php -i | grep sendmail_path
```

<img width="800" alt="Screenshot 2020-01-20 at 12 32 53" src="https://user-images.githubusercontent.com/58855/72726755-15283d00-3b81-11ea-9041-612a5e71264d.png">
<img width="984" alt="Screenshot 2020-01-20 at 12 33 04" src="https://user-images.githubusercontent.com/58855/72726756-15c0d380-3b81-11ea-9424-b2c42e13b032.png">

**Comment by janw-me** [comment]
I'll try to capture these things when I try again.

**Comment by janw-me** [comment]
Okay, another fresh box with a butt-load more details.
Again the browser will send to mailhog, cli will not.

```
git clone git@github.com:Varying-Vagrant-Vagrants/VVV.git vagrant-development
cd vagrant-development/
vagrant plugin install vagrant-hostsupdater --local
vagrant up --provision #full log below
vagrant ssh
sudo service mailhog status   #it's active

cd /srv/www/wordpress-one
wp shell
wp> wp_mail( 'test@tomjn.com', 'vvv test', 'testing testing 123' );
ctrl+d

php -v  #7.2.26
php -i | grep sendmail_path  #sendmail_path => /usr/sbin/sendmail -t -i  => /usr/sbin/sendmail -t -i
# no email in mailhog, some debug info in screenshot below.
exit  #leave vagrant
```

- Go to http://one.wordpress.test/wp-admin/
- Login default provisioned: admin + password
- Add new user
- Get email in mailhog



All of the below is checked with this new box installed.

- **Is MHSendmail installed?**
      `whereis mhsendmail
	mhsendmail: /usr/local/bin/mhsendmail`
- **Is the MailHog service running?**
  `sudo service mailhog status`
   Yes it's active, I checked this before doing my test today.
- **What does your config/config.yml look like?**
  didn't change a single character, extra checked it's exactly the same as the [default](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/default-config.yml)
- **Where can I find a full copy of the reset-password.php script you ran?**
  Sorry but I can't give it. It's company IP and also quite long.
  But I can replicate emails not arriving in mailhog. Let's nog get hungup on the email getting out in the wild.
- **Have you confirmed MailHog catches emails sent via the browser interface?**
  Yes, creating a new user will be caught by mailhog
- **We're still missing the information requested in the original issue template, which I've asked for twice now :( OS/Vagrant/VirtualBox versions**
  Sorry, I should have earlier
  `vagrant --version # Vagrant 2.2.6`
  `vboxmanage --version    # 6.0.14_Ubuntur132055`
- **We're missing the provisioner log for MailHog, there may be a really obvious message indicating the issue**
  complete log for [vagrant up --provision](https://github.com/Varying-Vagrant-Vagrants/VVV/files/4087641/provision.log)

- **Is this a vanilla WP with default plugins/themes?**
  Just default installed _http://one.wordpress.test_ nothing changed, not even the admin passwords


**sendmail_path info**
![sendmail_path cli](https://user-images.githubusercontent.com/1026882/72754328-cbaf1080-3bc7-11ea-82e5-f9297b40df9e.png)
![sendmail_path browser](https://user-images.githubusercontent.com/1026882/72754330-cc47a700-3bc7-11ea-9068-428150c86460.png)


**Other**
![wp shell sendmail](https://user-images.githubusercontent.com/1026882/72754366-df5a7700-3bc7-11ea-95e4-a4630552af60.png)
![mail debug info](https://user-images.githubusercontent.com/1026882/72754367-df5a7700-3bc7-11ea-85bb-7bbe823c659e.png)

**Comment by Mte90** [comment]
The log is clean, the only issue I see that is printing the content of the mailhog desktop file but is not the source of the problem because the service is running.
The php version is the default one and mailhog is configured for that version.
Maybe we can do a symlink to mailhog sendmail instead the machine one?

Like if mailhog is installed sendmail package is removed and there is a symlink to that command.

**Comment by tomjn** [comment]
I suspect removing sendmail would cause issues elsewhere, I'd like to know why `php` doesn't list `mhsendmail` as the sendmail value in CLI though 🤔

**Comment by tomjn** [comment]
So I managed to reproduce it, and fixed it by running `sudo phpenmod mailhog`

Specifically, the mailhog ini file was present in mods-available, and for PHP FPM but not for the CLI conf.d folder

**Comment by tomjn** [comment]
PR #2050 should resolve this

**Comment by janw-me** [comment]
Great to hear.
Looking back, is it logical that it did work in 3.1.0 and before?
