### ISSUE TITLE
Q: Change WP CLI update method?

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2053]
At the moment we never update WP CLI, rather, we always delete it and download the latest nightly regardless.

Instead, perhaps we should install the latest stable, and use `wp cli update`?

**Comment by tomjn** [comment]
@Mte90 thoughts?

**Comment by Mte90** [comment]
The provision download the latest nightly at every run so it is always the latest version, right?

**Comment by tomjn** [comment]
true, but would it make more sense to let WP CLI manage its own update mechanism and use the stable version? Afterall users can grab the WP CLI dev thing you wrote if they want to use bleeding edge

**Comment by Mte90** [comment]
This is also true, maybe can speed up the provision because there will be downloaded a new version every day.

**Comment by tomjn** [comment]
Looks like we already do this check
