### ISSUE TITLE
Version 2.2.6 won't install with Virtualbox v6.1

### ISSUE THREAD

**Issue by alifeinbinary** [Varying-Vagrant-Vagrants/VVV#2055]
## Expected Behavior

After cloning the repo and using `vagrant up`, you would expect the installation to complete, however, there's a flag in the install script that won't allow the installation to continue with a version of Virtualbox >6.0

## Current Behavior

I'm installing VVV on Arch Linux with the most recent version of Virtualbox installed 6.1. Running `vagrant up` reports these errors.

```
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/kernel_v2/config/vm.rb:354: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/kernel_v2/config/vm_provisioner.rb:92: warning: The called method `add_config' is defined here
(eval):3: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/ui.rb:223: warning: The called method `say' is defined here
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```

## Possible Solution

I'm trying to find where that flag is in the install scripts so that I can try bypassing it or adding '6.1' to the list of accepted versions but I can't find the right spot. 

## Steps to Reproduce (for bugs)

1. git clone 2.2.6 repo 
2. Install latest version of virtualbox 6.1 from AUR
3. vagrant up from repo

## Your Environment
i7-4790k, 16GB RAM running Manjaro (arch) Linux 5.5 kernel.

**Comment by alifeinbinary** [comment]
I was able to fix this by adding and modifying the following files

File: /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta.rb

Line 67 add
`"6.1" => Version_6_1,`

In the same folder, duplicate the file "version_6_0.rb" and rename it "version_6_1.rb". Do a string replace on all instances of 6_0 to 6_1 in the newly created file. 

File: /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/plugin.rb

Line 62 add 
`autoload :Version_6_1, File.expand_path("../driver/version_6_1", __FILE__)`

Run `vagrant up` again and it should work

**Comment by tomjn** [comment]
@alifeinbinary this isn't the vagrant Github repo, it's the VVV repo, maybe you want to go to https://github.com/hashicorp/vagrant/? There is no VVV V2.2.6

**Comment by alifeinbinary** [comment]
@tomjn I'm out of my head today, silly me. I'll repost over there.
