### ISSUE TITLE
How do I add an existing wordpress website with varying vagrant vagrants?

### ISSUE THREAD

**Issue by NeoBlack12** [Varying-Vagrant-Vagrants/VVV#2056]
How do I add an existing wordpress website with varying vagrant vagrants?
Thank again for using VVV, and helping out!! -->

**Comment by tomjn** [comment]
Several options, but if you go through the instructions to add a WP site and reprovision, you can replace the contents of the `public_html` folder with your own sites files, and the contents of the database with your own database

**Comment by Mte90** [comment]
https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/ there is a section with also explaining about how to import a database, you will need probably to change the domain in the dump to use a locally one.
