### ISSUE TITLE
connect() to unix:/var/run/php7.2-fpm.sock failed

### ISSUE THREAD

**Issue by CdrMarks** [Varying-Vagrant-Vagrants/VVV#2059]
## Expected Behavior
Browse to http://local.wordpress.test/ and see the site's home page.

## Current Behavior
I see a 502 Bad Gateway.  When I review /srv/www/wordpress-default/log/error.log, I see the following:
`2020/02/01 18:56:48 [crit] 19673#19673: *4 connect() to unix:/var/run/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.50.1, server: local.wordpress.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.2-fpm.sock:", host: "local.wordpress.test"`

## Possible Solution
Ran these two commands while ssh'ed into the vagrant box.
```
cd /var/run
ln -s php7.0-fpm.sock php7.2-fpm.sock
```
Then was able to refresh the site and I see the home page without error.

## Steps to Reproduce (for bugs)

1. vagrant up
2. Browse to http://local.wordpress.test/

## Your Environment
Windows 10
Virtual Box 6.1.2 r135662 (Qt5.6.2)
ubuntu/trusty64 20190514.0.0
VVV 2.1.0-

## Logs
Provision log: https://gist.github.com/CdrMarks/ce517c500fbad474a9c5c7962250ef42
vvv-custom.yml: https://gist.github.com/CdrMarks/158ba98e55f961232802e33b822b7b87

**Comment by tomjn** [comment]
VVV 2.1.0 is extremely old, please upgrade to the current master or develop
branches on the v3.2.x versions, and try again. You’ll need to backup your
database and destroy the VM then provision

Note that symlinking PHP 7.2 to 7.0 might cause breakage

**Comment by CdrMarks** [comment]
I was curious why the bug template said I could copy and paste the splash screen to include all of the important details about my environment, but I only saw it included the VVV version.   My database has been backed up, once manually and once when I ran vagrant destroy.

Thank you for your help @tomjn.
