### ISSUE TITLE
502 Error after "Starting from Fresh"

### ISSUE THREAD

**Issue by youandyouglow** [Varying-Vagrant-Vagrants/VVV#2064]
After successfully following the "Starting from Fresh" directions at the bottom of this page of instructions:
https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/

...I am getting a "502 Bad Gateway nginx" error when I visit http://vvv.test/database-admin/index.php

It looks like all my backups and config.yml files are in place.  The problem persists when I replace the contents of my custom config.yml file with the default contents.

Vagrants successfully provisions but I can't access the database or view any of my sites.

I did some edits to some other config files "config/nginx-config/sites/default.conf" and "config/php-config/php7.2-www.conf" earlier in the day to try and fix a provisioning error.  I thought doing a Start from Fresh would get rid of my edits and replace them with the default files but perhaps I'm mistaken?  In any case I got rid of my edits and still I get the 502 error.

I have tried shutting down my computer and reprovisioning vvv but still no joy.

I am running VVV version 3.2.0

Any suggestions on where to go from here to get this working again?

**Comment by Mte90** [comment]
did you saw the ticket #2061? 
@tomjn fixed the issue today so you need to do a new provision.
