### ISSUE TITLE
Root Username/Password for VVV VM Doesn't Work

### ISSUE THREAD

**Issue by davidshq** [Varying-Vagrant-Vagrants/VVV#2070]
Attempting to connect to a VM, either from SSH on the local host or via the VirtualBox UI does not work with the documentation's stated username of root and password of vagrant. Can this be updated?

**Comment by Mte90** [comment]
it is enough to run `vagrant ssh` to enter via ssh inside the machine without use ssh itself.

**Comment by davidshq** [comment]
In most cases, vagrant ssh is sufficient - but there are occasions where having access to console level access can be useful.

For example, if something was malfunctioning in the boot process it would be difficult to troubleshoot since vagrant ssh doesn't provide access until the system has been booted.

I know, theoretically, one should just blow away the vm and do it again...

If it is a scenario that isn't supported, that's okay (though I, personally, strongly prefer having access to my systems from power on...call it a habit from working with numerous servers over the years and desperately needing that access to get a system back into production)...but if that is the case then the documentation should be updated to note that VVV no longer supports direct login...

And if it is supported, then there is a bug (most likely a different username/password) in VVV.

**Comment by tomjn** [comment]
If something went wrong during the boot process then something has gone seriously wrong. In that situation the VM should be discarded and rebuilt. This isn't a production server, and if it's being used as one then you have major security issues to contend with

Additionally, you should SSH in as the `vagrant` user, and use `sudo` or `sudo su`.  You can also dump an SSH config using the standard vagrant commands so you can use raw `ssh` 

> Attempting to connect to a VM, either from SSH on the local host or via the VirtualBox UI does not work with the documentation's stated username of root and password of vagrant.

Do we document the system root user password? I believe we document the `root` mysql user, as for updating it, the docs are all markdown files in the https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org repo

**Comment by davidshq** [comment]
I've submitted https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/163 to update documentation regarding this and a few other minor changes.

**Comment by tomjn** [comment]
I can confirm this, it seems that `PermitRootLogin` is not enabled, so it doesn't matter what the password is, it'll never work. Generally, SSH'ing  in as root is ill advised, and a security concern:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/8f7600697cda972cde68bb38b0bac1e6c5d2efb8/config/sshd_config#L32

and

https://github.com/Varying-Vagrant-Vagrants/VVV/commit/9c01f6268e9e2d5ba1cdc772c13f49646d445e7d

The shadow file says the  password hash is `*` which indicates the user is locked down.

**Comment by tomjn** [comment]
I've updated the docs to indicate what to do if you need to run commands via SSH as `root`
