### ISSUE TITLE
Cant Vagrant Provision: The box failed to unpackage properly.

### ISSUE THREAD

**Issue by J-DEV1** [Varying-Vagrant-Vagrants/VVV#2071]
After experiencing the same bug in issue #2061 I completely reinstalled vagrant, VirtualBox, and VVV. 
Now i am getting the following error on vagrant up / vagrant up --provision.

\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.3.0-git::develop

Platform: platform-mingw32 windows HasWinAdminPriv vagrant-hostsupdater vagrant-vbguest NoColour shared_db_folder_disabled , VVV Path: "C:/vvv"
Vagrant: v2.2.7, VirtualBox: v6.1.2r135662

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/bionic64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/bionic64'
    default: URL: https://vagrantcloud.com/ubuntu/bionic64
==> default: Adding box 'ubuntu/bionic64' (v20200210.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20200210.0.0/providers/virtualbox.box
    default: Download redirected to host: cloud-images.ubuntu.com
    default:
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x box.ovf
x Vagrantfile
x metadata.json
x ubuntu-bionic-18.04-cloudimg.mf
x ubuntu-bionic-18.04-cloudimg.vmdk: Truncated tar archive
bsdtar.EXE: Error exit delayed from previous errors.

**Comment by tomjn** [comment]
see https://bugs.launchpad.net/cloud-images/+bug/1862837 it seems Canonical/Ubuntu broke their vagrant box images. There's very little that can be done at the VVV end other than to subscribe to the issue with launchpad accounts so it gets more attention

**Comment by tomjn** [comment]
As a sidenote, this has no connection to #2061

**Comment by davidshq** [comment]
I'd also submitted a bug report: https://bugs.launchpad.net/cloud-images/+bug/1862700

Myself and several others have posted some workarounds for the issue until this is fixed by Ubuntu.

What worked for me was:
1. Download an older box manually:
https://cloud-images.ubuntu.com/bionic/20200206/bionic-server-cloudimg-amd64-vagrant.box
2. Add it manually: vagrant box add bionic-server-cloudimg-amd64-vagrant.box --name=ubuntu/bionic64

**Comment by J-DEV1** [comment]
Looks like they updated the file.  Working properly now, thanks!
