### ISSUE TITLE
Ensure root user has the default credentials in MariaDB

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2076]
As:

* https://varyingvagrantvagrants.org/docs/en-US/default-credentials/
* https://varyingvagrantvagrants.org/docs/en-US/references/sql-client/

We need to switch to wp/wp after https://mariadb.com/kb/en/authentication-from-mariadb-104/ where root/root is not available on MariaDB

**Comment by tomjn** [comment]
There are issues remaining with the fix to this, reopening

Specifically, this works the first time but fails the following attempts. In order to resolve this, I believe we need to test the root user/pass, and if it doesn't work then set it, otherwise, leave it alone

**Comment by Mte90** [comment]
It is required to do a sql query https://dba.stackexchange.com/a/685 to check if the user exists inside mysql.
We want to add a check like that?

**Comment by tomjn** [comment]
root should always exist, it’s the password we need to check

**Comment by Mte90** [comment]
This is the flow to change the root password https://www.a2hosting.com/kb/developer-corner/mysql/reset-mysql-root-password and I don't like to kill mysql server to start just for this.
Maybe we can do an alert in the log to see if the password is changed and suggest for a vagrant destroy to set the right one.

**Comment by tomjn** [comment]
I  don't like the idea of recommending a `vagrant destroy`, that should be considered an absolute last-ditch attempt to fix something given it has the chance of data loss and can take a long time on some computers.

Instead:

```
if attempt to use default user/pass fails
     try to set the password to root via mysqladmin
     if that fails
        output a message linking to instructions
     else
        declare success
```
