### ISSUE TITLE
Print Log to the terminal when Site Provisioners fail

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2096]
Right now if a site provisioner fails, it tells you that it failed and to look at the log. Instead, it should print out the log so it appears in the terminal, then abort. The same goes for `grunt` in the custom site template for WP Core development

This way, when things are good, we get a nice clean terminal output, but when things go bad, it's output to the terminal and the user can see what went wrong.

Otherwise, we have the equivalent of a HTTP 500 error report. It's good to know something went wrong, but `500` means literally nothing to us. Lets cut out the first step of asking for these logs in support routes and just print them to the terminal

**Comment by Mte90** [comment]
AS I can remember you implemented that

**Comment by Mte90** [comment]
Right now just print the log file path on begin https://github.com/Varying-Vagrant-Vagrants/VVV/commit/6b5988d789ab3f6f8704cb7059f16ee6bb492c20

**Comment by Mte90** [comment]
Just a ping for this.
In case how I can replicate the issue?

**Comment by tomjn** [comment]
Make the site provisioner fail, be it a command that fails, a command that doesn't exist, basically anything that makes it not work.

At the moment when a provisioner fails it says it failed, the user then has to dig through the log folder to find out why. If we know the path to the log file then we should just output the last 10 lines of it.

Otherwise the user will complain on here there's an error, and when we go to see the error, it'll say "XYZ provisioner failed, see the log" with no more information. Then we have to type up a message asking them to look in the log, then they only give us an error message at the end that they think is useful and we have to get them to send the log in full because they missed out the bit we actually needed

Or instead VVV can just print the log in full to the terminal on failure or show the last 10 lines

**Comment by Mte90** [comment]
I did some testing for this, if I print the full log on error it is broken as for the ascii terminal characters broken (I read the whole file and printing).
The first 2 for every line are missing, so my idea was to write the path on the hosts of that log folder.

What do you think @tomjn?

**Comment by tomjn** [comment]
I think there's a solution to that but I do not know it off the top of my head. We already print out the path of the log folder. We also don't know the location of VVV on the host inside provisioners, that information is not shared with the VM.

**Comment by Mte90** [comment]
So another option can be save all the log output in a variable so we can print it and not need to read the log file.
In that way we should have also the colors and other things.

**Comment by tomjn** [comment]
@Mte90 if you run `cat` on the log files they show with all the relevant colours, stripping out the formatting codes isn't needed:

<img width="541" alt="Screenshot 2021-02-22 at 14 47 11" src="https://user-images.githubusercontent.com/58855/108724124-e5363080-751c-11eb-86b1-008c25db53d8.png">

Storing it as a bash variable would just add a tonne of complexity

**Comment by Mte90** [comment]
Probably my issue was using `echo`?
I will look into that soon.

**Comment by Mte90** [comment]
I did a pr but require testing
