### ISSUE TITLE
Auto-site setup all the things

### ISSUE THREAD

**Issue by simonwheatley** [Varying-Vagrant-Vagrants/VVV#210]
![43272801](https://f.cloud.github.com/assets/233434/1609507/75a3bc2a-5548-11e3-867f-1fb68274dc93.jpg)

Should we move all the sites in the `www` directory to use the auto-site setup method? Dog fooding, and all that. Plus it'd give handy built in examples for people.

Should we even consider moving some of those sites out into their own repos, allowing VVV to lose a little bloat (so we don't have `wordpress-default` and `wordpress-develop` and `wordpress-trunk`)?

**Comment by jeremyfelt** [comment]
The dream has been realized in #980! :taco:
