### ISSUE TITLE
HTTP timeout error in VVV environments

### ISSUE THREAD

**Issue by thomasgriffin** [Varying-Vagrant-Vagrants/VVV#211]
First off, I'm digging VVV. I love its ease of use and flexibility. :-)

I'm running into an issue where I cannot connect to any external environments via the HTTP API. Here is an example error:

Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /srv/www/wordpress-default/wp-includes/update.php on line 259

It is a timeout error. There are more errors, such as for the Dashboard RSS feed widgets: RSS Error: WP HTTP Error: name lookup timed out

Has this been reported before? If not, any idea of why this may be occurring? I haven't looked into it too closely, but it sounds like a potential hosts file conflict?

**Comment by f4bsch** [comment]
I sometimes get a timeout on cold starts (VM not even responding on pings), for some reason pinging from the VM to the host system fixes it:
`vagrant ssh`
`ping 192.168.50.1`
