### ISSUE TITLE
502 Bad Gateway error after updating vagrant box

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2111]
I forgot to restore some php-config files. 
Everything is fine. 
Please delete this ticket.

**Comment by tomjn** [comment]
I know it's all been edited out, but the reason you got a bad gateway error is because those sites were set to use PHP 7.3, but 7.3 wasn't installed in `config.yml`

Rather than deleting the issue, I'd suggest restoring your original edit so that other people with the same issue can find the solution

**Comment by shanebp** [comment]
You mean this line in config.yml: `#- php73`
Should be `- php73`  ?

It is still commented out in config.yml, but everything is working now. 
For some sites, I use this option:  `nginx_upstream: php73`

Before I learned about  `nginx_upstream:`
I was messing with php-config files and renamed these two files. 
Once I restored the proper file names, the gateway errors went away. 

```
default: cannot stat '/srv/config/php-config/php7.2-www.conf': No such file or directory
default: cp: cannot stat '/srv/config/php-config/php7.2-custom.ini': No such file or directory
```

**Comment by tomjn** [comment]
Yes, the `php73` utility installs PHP 7.3, that's where the valid values for `nginx_upstream` come from, here's the doc on switching PHP versions:

https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/changing-php-version/

Here's where the upstream value gets swapped out:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L76

Here's the script that installs and maintains PHP 7.3:

https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/php73/provision.sh

Note the folder name `php73` matches what was in `config/config.yml`, that's how it knows which `provision.sh` to run

And here's the Nginx config that it copies in to place to define the `php73` upstream:

https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/php73/php7.3-upstream.conf

This way, you can `vagrant destroy` and it'll install PHP 7.3.

You can also declare `php` in that utilities section, and it'll go through each version and install them 1 by 1.

Generally, you can make manual changes inside the VM if you want, but, the way packages are meant to be done is that you create a repo and add it as a utility, aka a repo with subfolders that contain `provision.sh` scripts. You then tell it which subfolders you want it to provision, and those scripts do all the installing and updating.

This way the only thing inside the VM we really need to worry about losing is the database, everything else is either stored on the host or reproducible from the config

**Comment by shanebp** [comment]
Thanks, appreciate all the info.
