### ISSUE TITLE
Microsoft Edge ( New Version )

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#2117]
Can we have some users who are using Windows 10 and update their Microsoft Edge to the new Microsoft Edge from https://www.microsoft.com/en-us/edge/ 

I started this  as a new beginning to see if people are having issues. I have tested the Newer Edge and it seems to working fine with no configuration. 

Can someone linked #1523, apparently I don't know how lol

**Comment by benlumia007** [comment]
#1523

**Comment by benlumia007** [comment]
Please also note that Microsoft Edge is currently available in MacOS, so that's something that we can also test

**Comment by tomjn** [comment]
Edge works fine on MacOS, although it seems to be blocking Google Fonts by default:

<img width="1440" alt="Screenshot 2020-04-14 at 10 21 56" src="https://user-images.githubusercontent.com/58855/79208478-0082da80-7e3a-11ea-81a6-4dbc2226cc5d.png">


I'm happy to close this out and stick with asking in #1523 if the issue persists
