### ISSUE TITLE
http://vvv.test will not resolve

### ISSUE THREAD

**Issue by plusco** [Varying-Vagrant-Vagrants/VVV#2123]
I think I set up correctly. However, vvv.test will not resolve.  Attached is my provision log and host file.  I am using vmware-desktop instead of VirtualBox, but after updating provider: vmware_desktop in the config.yml file, everything seems in order.  
 
Any assistance would be appreciated.  I am about to give up.  Thanks,  Phillip

Windows 10, vmware_desktop, vmware licensed for vagrant,
d:\Vagrant\VVV-develop>vagrant -v
Vagrant 2.2.7

[vagrant reload --provision.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/4498382/vagrant.reload.--provision.txt)

[hosts.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/4498388/hosts.txt)

[config.yml.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/4498389/config.yml.txt)

**Comment by tomjn** [comment]
I notice your hosts file has the entries needed, but they're commented out with a `#`, did you do that?

My understanding is that hosts updater will see the IDs in those comments and declare _"We've already done this, we don't need to do anything, the entries are already there"_

Keep in mind that you can always add the entries manually, hostsupdater makes life easier, it's not a necessary tool, but it does make life a lot easier

**Comment by plusco** [comment]
Thank you tomjn.  The host # were default to Windows10 installation.  The host file attached was updated by hostsupdater.  Seems to work fine.  Everything seems to work except launching of vvv.test.  Must be a VMWare issue.  Otherwise I suspect everything looks correct?

**Comment by tomjn** [comment]
I'm not sure what you mean by _The host # were default to Windows10 installation_, can you reword/rephrase?

I would recommend halting the VM, deleting those lines in the host file, then running `vagrant up`, there should not be `#` characters at the start of those lines

**Comment by plusco** [comment]
Thank you tomjn.  I removed all comments from the host and retried.  The hostupdater added the entries correctly, but vvv.test still did not start.  

Reference to Windows 10 default host "https://support.microsoft.com/en-us/help/972034/how-to-reset-the-hosts-file-back-to-the-default" select Windows 10.  This was what I was referencing as default host entry items commented out #.  

About to give up.  Any other suggestions other to wipe and try virtualbox or hyper-v?  Which would you suggest?

**Comment by tomjn** [comment]
> The hostupdater added the entries correctly, but vvv.test still did not start.

If the entries begin with a `#` then hostupdater was not successful. If you can share the hosts file again, and every time it's updated.

I doubt it will have much of a difference, but if you can attempt VirtualBox/Hyper-V that would be helpful. Otherwise, if hostsupdater keeps putting a `#` in front of its entries, then it's a hostsupdater issue.

The only other thing I can think of, is that you have security software that's interfering.

**Also, as I said before, you can just manually put the entries in yourself. You don't need to use a vagrant plugin to manage hosts.**

**Comment by tomjn** [comment]
@plusco did Hyper-V or VirtualBox work for you?

**Comment by Mte90** [comment]
can we close it @plusco?

**Comment by tomjn** [comment]
I'm going to close this out, we can always reopen
