### ISSUE TITLE
issue with wordpress

### ISSUE THREAD

**Issue by deelip1** [Varying-Vagrant-Vagrants/VVV#2127]
i have a issue regarding database in wordpress while in my hosting account i have 
Your Account

Usage, logs and statistics

• View more
Disk Space 
1.8 GB / 7.32 GB

WordPress database error Disk full (/tmp/#sql_4abf_0.MAI); waiting for someone to free some space... (errno: 28 "No space left on device") for query SELECT wpposts.* FROM wpposts INNER JOIN wppostmeta ON ( wpposts.ID = wppostmeta.post_id ) WHERE 1=1 AND (
( wppostmeta.meta_key = '_wp_attachment_is_custom_header' AND wppostmeta.meta_value = 'newsup-child' )
) AND wpposts.post_type = 'attachment' AND ((wpposts.post_status = 'inherit')) GROUP BY wpposts.ID made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/newsup/search.php'), get_header, locate_template, load_template, require_once('/themes/newsup/header.php'), has_header_image, get_header_image, get_random_header_image, _get_random_header_data, get_uploaded_header_images, get_posts, WP_Query->query, WP_Query->get_posts

**Comment by Mte90** [comment]
Hi @deelip1 I don't understand this is an issue with VVV or with your wordpress instance on your hosting?
Anyway it is clearly an issue of not enough space in the tmp folder that use the ram and not disk space.

**Comment by tomjn** [comment]
@deelip1 can you explain some more? I don't understand the problem. I also saw you didn't fill out the needed information in the issue template, such as which OS you're running VVV on ( windows? Mac? ) which version of VVV you're using? What does your config look like?

I also don't see how to reproduce this error, or how you got there. Try to include as much information as possible, even if you don't think it's necessary, include it. Overload us with information.

**Comment by tomjn** [comment]
Since there is no screen in VVV that has usage logs and statistics, and the VM allocates 10GB not 7GB, I'm assuming this is actually an issue with a host in a data centre, not a VVV problem. Please update the issue and we can reopen if it is a VVV issue
