### ISSUE TITLE
How to disable access to the internet for a site

### ISSUE THREAD

**Issue by Ryvix** [Varying-Vagrant-Vagrants/VVV#2128]
Hey,

I'm having trouble figuring out how to disable access to the internet for a site.

Everything works fine, I can ssh in and access vvv.test and everything. But I want to disable a website's access to the internet so that it doesn't send out a bunch of emails or something else unexpected.

If I set the NAT to disabled or unplugged then I can't access the site anymore. Is there a proper way to do this?

Thanks!

**Comment by Mte90** [comment]
Well the machine needs internet connection, the only things that you can do is install plugins that disable a wordpress website to communicate.
With this plugin you can https://github.com/norcross/airplane-mode disable all the http calls, instead for email https://it.wordpress.org/plugins/disable-emails/
Anyway this is not a VVV task, is something wordpress side that you can achieve on your own.

**Comment by Ryvix** [comment]
Awesome, thanks!

Here is something I just found that might also work in case anyone ever finds this:
https://www.cyberciti.biz/tips/block-outgoing-network-access-for-a-single-user-from-my-server-using-iptables.html

If I run this then the www-data user (33 in my case) can't send outgoing connections on the NAT interface (enp0s3).

`iptables -A OUTPUT -o enp0s3 -m owner --uid-owner 33 -j `DROP`
