### ISSUE TITLE
vagrant-hostmanager and provisioning

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#2134]
this may be a problem whereas if you already have done the first vagrant up ( new ) and if you add a new site afterwards. the hostmanager will not update the new hosts to the hosts file because it seems like it only applies to vagrant up and vagrant destroy. 

sorry, please note that it will not update if you use vagrant reload --provision.

**Comment by tomjn** [comment]
oh dear, I thought hostsmanager would add new sites

**Comment by Mte90** [comment]
Looking at the code hostsmanager doesn't have provision support:

* https://github.com/devopsgroup-io/vagrant-hostmanager/blob/2b75b7f00f4b929023c7d6e3cd70d75b334c560b/lib/vagrant-hostmanager/plugin.rb
* https://github.com/cogitatio/vagrant-hostsupdater/blob/52dcfd1271e58a391c8f731f291961c8ab21aaaa/lib/vagrant-hostsupdater/plugin.rb

Hostsupdater has a lot of hooks but not hostsupdater. I think that we can do a pr but the project seems abandoned.
As a pr also for adding support on halt command https://github.com/devopsgroup-io/vagrant-hostmanager/pull/217

**Comment by tomjn** [comment]
> I think that we can do a pr but the project seems abandoned.

All the plugins I found seem to be either abandoned or in a state of limbo :/ Even if people are willing to contribute

**Comment by tomjn** [comment]
Closing this as we've moved to goodhosts
