### ISSUE TITLE
Can't install Wordpress plugin (neither wp-admin nor just via FS)

### ISSUE THREAD

**Issue by adambreen** [Varying-Vagrant-Vagrants/VVV#2143]
Hey guys, I just got VVV running on Mac OS Catalina, using the Parallels provider.
I can't seem to add a plugin normally, via wp-admin. Here's what I got initially when I clicked Install for the Class Editor plugin, in https://one.wordpress.test/wp-admin/plugin-install.php (the default one.wordpress.test site)...
![image](https://user-images.githubusercontent.com/905928/81145898-d55b5900-8fa9-11ea-89f2-d8968f6fc1b1.jpeg)

I've added define('FS_METHOD','direct'); to wp-config.php, and that got one step further in wp-admin. Now it says "Installation failed: could not create directory", when I click the Install button for the Classic Editor plugin. 

![Screen Shot 2020-05-06 at 2 58 20 pm](https://user-images.githubusercontent.com/905928/81146179-574b8200-8faa-11ea-983b-a9a60346dee6.jpg)

I've also tried copying a plugin folder from my main code folder into ~/vagrant-local/www/wordpress-one/public_html/wp-content/plugins/ (in this case, the plugin I'm working on, gravity-forms-sfdc). Surprisingly, it doesn't even appear in the list of plugins for the site, at https://one.wordpress.test/wp-admin/plugins.php. I even tried vagrant reload after copying the folder across. The file permissions seem to be correct.

![Screen Shot 2020-05-06 at 3 04 36 pm](https://user-images.githubusercontent.com/905928/81146563-1b64ec80-8fab-11ea-9125-2715be1eeb19.jpg)

I'm confused/stuck. Please help?

**Comment by assertzero** [comment]
I have the same issue, same setup (macOS Catalina, provider Parallels). Did not have it on macOS Mojave.

**Comment by Mte90** [comment]
We fixed on slack there was some host setting issues.
