### ISSUE TITLE
My vagrant-local file doesn't contain "vvv-config-yml" file what seems to be the error?

### ISSUE THREAD

**Issue by jovanie07** [Varying-Vagrant-Vagrants/VVV#2145]
## What was The Command Used To Provision

```Acer@JST MINGW64 ~
$ git clone -b master git://github.com/Varying-Vagrant-Vagrants/VVV.git ~/vagrant-local
Cloning into 'C:/Users/Acer/vagrant-local'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12196 (delta 2), reused 2 (delta 0), pack-reused 12187
Receiving objects: 100% (12196/12196), 8.13 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (5960/5960), done.

Acer@JST MINGW64 ~
$ vagrant status
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

## What Kind of VVV Provision Was This

Im trying to install with the VVV and stock up with this error, I'm missing with the **"vvv-config-yml"** on the installation folder in my local system. Please see print screen shot [https://prnt.sc/sd9a8m]

What might be the error? 

Kindly Help me.

Thank you!

**Comment by Mte90** [comment]
Looking at the error you need to run `vagrant up`, status is to see if the machine is installed but you just download VVV.

**Comment by tomjn** [comment]
VVV hasn't used `vvv-config.yml` in a while, we switched to `config/config.yml`.

Both files get automatically created on the very first use of a vagrant command, you won't find them in the repo. `config/config.yml` is created by copying https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/default-config.yml

**Comment by tomjn** [comment]
```
Acer@JST MINGW64 ~
$ vagrant status
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

Looking at this, it looked like you cloned VVV, but then didn't change into VVV's folder, and ran `vagrant status` on your home directory instead. Vagrant quite rightly looked for a vagrant file, but did not find one ( because you weren't in the VVV folder ).

You needed to run the command in `C:/Users/Acer/vagrant-local` but you ran it in `C:/Users/Acer`

**Comment by jovanie07** [comment]
> VVV hasn't used `vvv-config.yml` in a while, we switched to `config/config.yml`.
> 
> Both files get automatically created on the very first use of a vagrant command, you won't find them in the repo. `config/config.yml` is created by copying https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/default-config.yml
> 
> If you had a `vvv-config.yml` it would get moved to `config/config.yml` automatically.
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/6468170?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Varying-Vagrant-Vagrants/VVV](https://github.com/Varying-Vagrant-Vagrants/VVV)**An open source Vagrant configuration for developing with WordPress - Varying-Vagrant-Vagrants/VVV
> 
> Can I ask what instructions you were following?

Hi Tomjn, thank you for the helping, Im following instruction from youtube (https://www.youtube.com/watch?v=w4yQ_4Btu_g)

**Comment by jovanie07** [comment]
> Looking at the error you need to run `vagrant up`, status is to see if the machine is installed but you just download VVV.
