### ISSUE TITLE
Wordpress user not recognized

### ISSUE THREAD

**Issue by nadavatar** [Varying-Vagrant-Vagrants/VVV#2146]
Hi,

I use Manjaro Linux and installed the newest VVV today from Github with VirtualBox and Vagrant. 
I have logged into the one.wordpress.test/wp-admin section where there is a Wordpress login page.
I have registered to Wordpress.org and activated my email and password and successfully logged into their website but when I try connecting with that same user to one.wordpress.test/wp-admin it says the username is not recognized and also did not recognize my mail. 

thanks in advance.

**Comment by Mte90** [comment]
WordPress.org is another website, is not the local one you have on VVV.
WordPress is a cms that you can download and install it, VVV does it automatically for you.
