### ISSUE TITLE
Migrate opcache-status to opcache-gui

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2149]
Right now the opcache dashboard is https://github.com/rlerdorf/opcache-status and last update is from 2015. Also it is compatible with php 5.5 so it maybe in the future can have problems.

A solution is to migrate to https://github.com/amnuts/opcache-gui that is simple to install like this other one and includes more features and is maintained.

The vvv-utilities provision code is here: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/opcache-status/provision.sh

**Comment by tomjn** [comment]
I think this looks good, but we should add an `opcache-gui` utility, and mark `opcache-status` as deprecated with a message
