### ISSUE TITLE
Unable to acquire the dpkg frontend lock

### ISSUE THREAD

**Issue by macgraphic** [Varying-Vagrant-Vagrants/VVV#2150]
## What was The Command Used To Provision

vagrant up --provision

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Steps to Reproduce (for bugs)
1.   The issue seems to happen each morning, after a fresh boot of the system (iMac)
2.  If the system has been running for 30mins+ and I run a Vagrant Up, it usually works fine.
3.  Have previously tried a clear-out of VVV, Vagrant & VB & re-install (around time of 3.2.0 relase)
4. 

Linked above

## Your Environment

Linked above

**Comment by macgraphic** [comment]
Seems the links in above have been removed. Re-adding them here (hope they work)
Provision: https://gist.github.com/macgraphic/3674bba848b66868bfd1580d350b9f99
Provisioner-main.log: https://gist.github.com/macgraphic/2e0044fe3bd32b719c6134579ddd8d6d
config_config.yml: https://gist.github.com/macgraphic/b277a8beb3654d7634a8f8b55535237b

**Comment by Mte90** [comment]
It is a problem that was happening also to me and I was thinking that was my fault.
I think that we can implement something to avoid it.

**Comment by Mte90** [comment]
I did a pr with the fix but need some testing https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2151
