### ISSUE TITLE
The default dashboard suggests using "switch_php_debugmod", which is not on the current release

### ISSUE THREAD

**Issue by DeadDuck** [Varying-Vagrant-Vagrants/VVV#2152]
The default dashboard at `http://vvv.test/` suggests the usage of `switch_php_debugmod` to switch php debuggers. However the script has not yet been merged to the current release v3.3.0.

**From the dashboard**

> To switch between debug extensions, use vagrant ssh to enter the VM, then use switch_php_debugmod followed by the extension you prefer. For example switch_php_debugmod xdebug. Use switch_php_debugmod none to disable them. On older versions of VVV you would need to use xdebug_on or xdebug_off.

The users of 3.3.0 should just use the existing method (eg. xdebug_on). Just writing here to prevent any more confussion.

**Comment by Mte90** [comment]
Yes because the dashboard is a different repo that is updated also on old VVV instances.
We are late on our schedule to release a new version of VVV.

**Comment by tomjn** [comment]
If you switch to the `develop` branch it's there, the branch is ready for a release it just needs the changelog updating
