### ISSUE TITLE
Include MariaDB 10.4.x

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#2154]
VVV 3.3 currently include MariaDB 10.3.x. Including MariaDB 10.4.x will provide support for `utf8mb4_0900_ai_ci`, which MySQL 8 uses as a default collation

Instructions:
https://downloads.mariadb.org/mariadb/repositories/#distro=Ubuntu&distro_release=bionic--ubuntu_bionic&mirror=digitalocean-ams&version=10.4

```
sudo apt-get install software-properties-common
sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic main'
```

**Comment by Mte90** [comment]
We already did in the develop branch as you can see in the changelog https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/CHANGELOG.md
