### ISSUE TITLE
curl fails to recognize vvv-signed certificates

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#2155]
## Expected Behavior
WordPress Health Check plugin reports no errors.

## Related Issues
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1820
https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/31

## Current Behavior
The following tests fail:
* The REST API encountered an error
* Background updates are not working as expected
* Your site could not complete a loopback request

```
Error: [] cURL error 60: SSL certificate problem: unable to get local issuer certificate
```

## Steps to Reproduce (for bugs)

1. vagrant destroy
2. vagrant box up
3. Go to https://mysite.test/wp-admin/tools.php?page=health-check

## Your Environment

Host: macOS 10.14.6
Vagrant: v2.2.9
VirtualBox: v6.0.20r137117
VVV: `develop` branch (updates 7 May 2020)
box: ubuntu/bionic64 20200514.0.0

Here's what curl shows from the command line:
```
$ vagrant ssh
$ curl -i -vvv  https://mysite.test/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to mysite.test (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

**Comment by Mte90** [comment]
@tomjn do you any hints for that?

**Comment by tomjn** [comment]
Not specifically, I remember us encountering this a while ago and the solution was to install the certificates in the VM on the TLS CA provisioner, but I believe we did that already. We'd need to check for a regression

**Comment by tomjn** [comment]
Resolved by https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/65
