### ISSUE TITLE
Compress database backups

### ISSUE THREAD

**Issue by mathieuhays** [Varying-Vagrant-Vagrants/VVV#2156]
One of my colleagues had a good suggestion that I'm now echoing here: Would it be possible to compress database backups?

I currently have 3.1Gb worth of database backups attached to my VVV instance. I did a quick test by compressing each sql file individually in the backup folder and ended up reducing that footprint to 615Mb.

**Comment by Mte90** [comment]
I think that we can implement it but the problem is performance, probably will take a while on every vagrant halt.
Maybe we can add an option for it.

**Comment by tomjn** [comment]
This might work great for some people but not so much for others,
especially those with mechanical drives. Perhaps it can be compressed as
it’s written? This does mean though that the backup and restore scripts
would need to be rewritten though
