### ISSUE TITLE
installing phpspreadsheet

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2162]
What is the best way to install this package? 

[https://github.com/PHPOffice/PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet)

Terminal call: `composer require phpoffice/phpspreadsheet`

Can I install it for use on just a single site? 
Or is it a utility available to all sites? 

Eventually I will need to upload the installed package to a public server on which I do not have ssh access.

**Comment by tomjn** [comment]
Utilities are for operating system level software such as MySQL, drivers,
etc

This is just a PHP library however, you’d install it the same way on any
server or environment. There’s no VVV specific stuff here, it’s just a case
of using it in your project and that doesn’t require any VVV knowledge.

Id look into how to use composer libraries in WordPress plugins, and how
the composer tool works. This is more like downloading a folder of PHP
files and unzipping them in your plugins subfolder then including them.
Only you’re doing it with a tool called composer.

As an aside, the composer tool is installed inside the VM already if you
SSH into it, but I think the important piece of information you’re missing
is that composer is a folder/project level package manager like npm, not an
OS/system level package manager like apt/homebrew/yum

**Comment by shanebp** [comment]
Thank you.
