### ISSUE TITLE
provision to delete sites 

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#2170]
when you remove a site from custom.yml file, it should not be exists, therefore it would make sense when u remove a site and provision.  it should delete everything related. 

so i created a script that does that and maybe it should be a feature in the future.

```
#!/usr/bin/env bash

config="../.global/docker-custom.yml"

get_sites() {
    local value=`cat ${config} | shyaml keys sites 2> /dev/null`
    echo ${value:-$@}
}

cd sites
for domain in $( ls ); do
    if ! grep -q ${domain} ${config}; then
        if [[ "dashboard" != ${domain} ]]; then 
            rm -rf ${domain}
            rm -rf ../certificates/${domain}
            rm -rf ../config/nginx/${domain}.conf

            if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
                if grep -q "${domain}.test" /mnt/c/Windows/System32/drivers/etc/hosts; then
                    sed -i "/${domain}.test/d" /mnt/c/Windows/System32/drivers/etc/hosts
                fi
            else
                if grep -q "${domain}.test" /etc/hosts; then
                    sed -i "/${domain}.test/d" /etc/hosts
                fi
            fi
        fi
    fi

done
```
what you guys think!

**Comment by tomjn** [comment]
If we remove sites when you remove them from the yaml file automatically, then that would lead to data loss.

For example, if I make a mistake in my YAML file, such as indenting the first site using tabs and the rest with spaces, then technically there is only 1 site, and the rest would get deleted.

We also can't delete the database as we don't know which databases belong to which sites.


> config="../.global/docker-custom.yml"

Is this VVV?

**Comment by benlumia007** [comment]
No, this isn't VVV yet. This was done with my WSL2/Docker environment, The way I set this up is similar to VVV. 

I aslo done it with my own vagrant setup which also similar to VVV. 

The way I did it, as I went into the sites folder, and create a script to see how many folders that have the same name as the config.yml file and do a comparison, If the name has been remove from the config.yml, then delete the sites/name, certificates/name, the config file for the name and probably the database. 

when u provision the sites for VVV, isn't the database name the same as the hostname that gets generated.  

I've done it, and it works fine.

**Comment by benlumia007** [comment]
What I am saying this feature is possible and I have done it from spending a lot of thoughts about it and it may not be what we want now. but i'm sure that this feature would be handy in the future.

**Comment by Mte90** [comment]
I agree with Tom as it is now means a lot of issues and stuff to develop. Also check in the config is not enough expose a lot of problems as example a typo will remove the full websites and all the files in this way.
Right now the best solution is a vagrant destroy in this way everything is reset so can be uploaded the right websites.

**Comment by benlumia007** [comment]
right, vagrant destroy works and resets, but you still need to remove the unwanted sites in the custom.yml file before you vagrant up again. to me still doesn't make sense overall.

honestly, it took me like an hour or two to get it right. is not that hard to develop.  

well anyways, i think my inputs are not gonna go anywhere. so I'm just gonna closed this ticket.
