### ISSUE TITLE
Test Shyaml Check Change

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2171]
I've had this tab open a while and there's a question asked that we need to test and answer:

https://github.com/0k/shyaml/issues/57

**Comment by Mte90** [comment]
Reading the thread for me we need to test the snippet shared in the ticket and see if fix the issue.
Otherwise we cannot move on the discussion.

**Comment by Mte90** [comment]
We still needs this?

**Comment by tomjn** [comment]
I tested this recently, it can be closed
