### ISSUE TITLE
VVV upgrade on Windows 10 - requiring an old version of 'vagrant-hostsupdater' v1.1.1.160

### ISSUE THREAD

**Issue by nicholasvad** [Varying-Vagrant-Vagrants/VVV#2176]
## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was an attempt to upgrade to a new version of VVV
After some complications, I deleted all the vvv Vagrant files and cloned from GitHub.

## What Broke

I had been receiving errors described [on the Vagrant plugins issue](https://github.com/hashicorp/vagrant/issues/8054) under Actual behavior, except that my error line had been:
```
Error message giving during initialization: Unable to resolve dependency: user requested 'vagrant-hostsupdater (= 1.1.1.160)'
```
I followed the three steps there and updated the `vagrant-hostsupdater` plugin.  The latest version was `v1.8.9`.

After deleting all the VVV Vagrant files, cloning the files from the VVV repository, and starting `vagrant up --provision`, the provisioning failed with the message that the project
```
requested 'vagrant-hostsupdater (= 1.1.1.160)'
```
The message gave me the command to run, and it updated the correct version of the hostsupdater (even though I already had `v1.8.9` installed).  I'm afraid that I didn't make a note of the command, but it worked.  It was probably related to
```
vagrant plugin install vagrant-hostmanager
```

## Possible Solution

I think it would be worth checking to see if somewhere in the code it requests the `vagrant-hostsupdater (= 1.1.1.160)`.  If so, it might be possible to check that the call isn't for the version `1.1.1.160`, which has now been superseded.

It's working for me now, but it might help some other people.

## Steps to Reproduce (for bugs)

You might reproduce this if deleted all the VVV Vagrant files and ran
```
vagrant delete
```
That might not reproduce the problem.  I had also been updating from Vagrant v1.9.0 and I hadn't updated my VVV Vagrant files properly first time after the upgrade to Vagrant v2.2.7.

## Your Environment

Operating System: Windows 10
VirtualBox 5.2.2
Vagrant v2.2.7

**Comment by tomjn** [comment]
Can I take a look at your terminal output? It probably was hostmanager, it works in situations hostsupdater doesn't on windows. We're actually working on a new plugin `vagrant-goodhosts` which is in the testing phase at the moment. Feel free to uninstall hostsupdater if hostmanager is working for you

**Comment by nicholasvad** [comment]
I don't have the error message terminal, but I just added the wordpress-trunk site and so re-provisioned.  Here's the terminal output from that:
[terminal.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/4732856/terminal.txt)

It does seem to be using `vagrant-hostsupdater` and it worked, apart from a couple of npm issues right at the end.  I'm happy to leave it. I can always transition to `vagrant-goodhosts` in due course.

I really just wanted to let you know that somehow it tried to old an older `vagrant-hostsupdater` for me.  It may be an edge case.

**Comment by tomjn** [comment]
I'm closing this out as the `develop` branch now uses the `vagrant-goodhosts` plugin instead of hostsupdater
