### ISSUE TITLE
Why is NVM removed on provision if it exists?

### ISSUE THREAD

**Issue by coolamit** [Varying-Vagrant-Vagrants/VVV#2177]
I was looking to update the provision script to install NVM if it does not exist and then I came across this snippet in `provision/provision.sh`

```bash
  if [[ -f ~/.nvm ]]; then
    echo " * .nvm folder found, switching to system node, and removing NVM folders"
    nvm use system
    rm -rf ~/.nvm ~/.npm ~/.bower /srv/config/nvm
    echo " * NVM folders removed"
  fi
```

It seems that if anyone installs NVM manually via terminal after provisioning VVV, it will be removed next time VVV is re-provisioned which is bound to happen if a new domain/site is to be added or existing one is to be removed.

Seems kinda odd/weird.

Any idea why this was done?

I find NVM a useful tool as different projects could have different Node.js requirements based on when they were set up and upgrading to latest version right away might not be feasible for them for any number of reasons including lack of time, incompatibility of some sorts, etc. In such cases NVM allows to have more than one version of Node.js available which can be switched from project to project as per requirements.

I can submit a PR for `provision/provision.sh` to install NVM if this is something you guys are ok with having in VVV. In my opinion VVV should have NVM.

**Comment by tomjn** [comment]
We used to have nvm but removed it, this code tries to clean up after old
versions. Happy for it to be removed or adjusted.

Perhaps it only runs if nvm isn’t installed?

**Comment by Mte90** [comment]
Maybe this is part of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2135 ?

**Comment by tomjn** [comment]
Also happy for nvm to be added to the core utilities though I can’t
maintain it myself so it’ll need clear test instructions

**Comment by coolamit** [comment]
> Perhaps it only runs if nvm isn’t installed?

It runs if NVM is installed because it looks for install directory which by default is created at `~/.nvm` and that code removes it if its found.

**Comment by Mte90** [comment]
One idea can be create a flag in config.yml that disable the removal of old stuff like this one.
Our provision has a lot of checks to remove tools and files of old versions, can be helpful also for our plans of testing include something similar.

**Comment by coolamit** [comment]
> Maybe this is part of #2135 ?

If it were to be, I think it would be more suited as part of utilities than packages. However that is a pretty neat idea. :)

> Also happy for nvm to be added to the core utilities

Imo since Node.js isn't a part of Utilities and is installed by default, I think this should be installed by default as well. By default (on first provision/when NVM is installed) the Node.js version can be set to what VVV is installing.

NVM has its own installer and just requires Git to be available and following to be run

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```

Once that's done, the provision script can run `nvm use system` to set default to the one installed by provision script.

**Comment by tomjn** [comment]
I don't think a config value is needed, it just needs to only cleanup if it's not installed

> Imo since Node.js isn't a part of Utilities and is installed by default, I think this should be installed by default as well. By default (on first provision/when NVM is installed) the Node.js version can be set to what VVV is installing.

I want VVV core to be leaner not heavier, getting Node working in the first place with Core build scripts was **_painful_**, adding `nvm` back in by default and dealing with a complicated matrix of VVV versions that do use it and don't use it and use it again, and making sure the site template and utility scripts all account for it and work across all of them sounds like more and more pain. No.

**Comment by coolamit** [comment]
> adding nvm back in by default and dealing with a complicated matrix of VVV versions that do use it and don't use it and use it again, and making sure the site template and utility scripts all account for it and work across all of them sounds like more and more pain. No.

I'm curious - what issues did you come across by installing NVM on provision?

Imo there shouldn't be any issues by installing NVM since it does not interfere with working of Node etc. You just switch which Node version you want to use and once that is done, NVM is out of the picture till the next time you want to switch Node version.

**Comment by tomjn** [comment]
We had  a lot of issues generally with Node, commands not working unless ran as `sudo`, command that wouldn't work if ran as `sudo`, various versioning issues. `nvm` was introduced in order to try and simplify things but was removed later.

> Imo there shouldn't be any issues by installing NVM since it does not interfere with working of Node etc. You just switch which Node version you want to use and once that is done, NVM is out of the picture till the next time you want to switch Node version.

In theory yes, but this is an area I do not want to investigate personally. The goal is to lighten VVV not make it heavier. As I said, I would rather remove `node` from VVV core than add `nvm`. Add it as a core utility and maintain it, but it will not be added to VVV itself.

**Comment by coolamit** [comment]
> If you put that curl command in the provisioner, it means it's not possible to run provisioners without a network connection.

Well provisioner does other things which need internet connection (check for APT packages), clone Git repo for the site template etc.

> If I'm doing VVV stuff and on an airplane and want to re-run a site provisioner, it'll fail because curl can't download the install script.

It would install `nvm` when VVV is originally provisioned. Once `nvm` is installed, there's no point in running it again & again every time a site is (un) provisioned.

On my VVV install, I have this in `provision.sh` (instead of current nvm removal code block)

```bash
echo " * Checking for NVM"
if [[ -d ~/.nvm && -f ~/.nvm/nvm.sh ]]
then
  echo " * NVM found, skipping NVM installation"
else
  if [[ -d ~/.nvm && ! -f ~/.nvm/nvm.sh ]]
  then
    # clean up if remnants are left
    echo " * NVM found in unusable state, cleaning up now"
    rm -rf ~/.nvm
  fi

  # lets install the thing now
  echo " * NVM installation starting now"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  echo " * NVM installed"
  nvm alias default system
  echo " * NVM default set to system default"
fi
```
**This does not interfere with Node 10 installed by VVV in any way. Infact when this code installs `nvm`, it sets the default Node to the one installed by VVV.**

And this works alright. I've tested this a few times including by removing `nvm` and it works. If `nvm` is not installed then it installs it but if its already installed then it skips installation. So when I provision VVV to add a new site or remove a site, it doesn't run since `nvm` is already installed.

> Add it as a core utility and maintain it, but it will not be added to VVV itself.

Fair enough!

> As for node 10, it can't just be removed, that would be a breaking change requiring us to bump to 4.0, and while it can be moved to a utility, requiring it be added that way means users would need to add it to their config/config.yml which would be a breaking change too, so it needs further thought, but that's outside of this issues scope

I never said Node 10 should be removed from VVV. All this discussion (atleast from my end) was to advocate for addition of `nvm` to make working with different Node versions easier out of the box, not to remove Node.

**Comment by tomjn** [comment]
> I never said Node 10 should be removed from VVV. All this discussion (atleast from my end) was to advocate for addition of nvm to make working with different Node versions easier out of the box, not to remove Node.

I was talking about my own desire to move `node` out of VVV core so it becomes an option rather than a requirement.

Anyway, if you want to remove or change the cleanup code, happy for you to do that.

**Comment by Mte90** [comment]
I was investigating the code maybe to detect NVM instead to look for the NVM folder we can try with `~/.bower` that is unused and is also deprecated for other package managers.

**Comment by tomjn** [comment]
@Mte90 I think the code snippet @coolamit wrote will do the trick, just needs a PR to remove the original, and add the above to an `nvm/provision.sh` file in the core utility repo on this org

**Comment by coolamit** [comment]
Here's the PRs

- https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2185
- https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/67
