### ISSUE TITLE
PHP intl extension is not installed

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#2178]
## Expected Behavior
PHP `intl` extension is installed.

## Current Behavior
PHP `intl` extension is not installed.

## Your Environment
VVV 3.4.0 (develop branch)

**Comment by Mte90** [comment]
The fun part is that I had a bug in one of my plugin in case there was this module. As I was using the fallback the problem wasn't appearing.
If the pr was a week before maybe I had spotted first 😂
