### ISSUE TITLE
The master branch

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2184]
I'm not keen on having a `master` branch, it has.. connotations. I'd much prefer a branch name such as `stable`, `current` or `lts`.

How can we move to a new stable branch without leaving people behind or causing problems for users?

**Comment by Mte90** [comment]
I agree that a better name can avoid a lot of issues.
As I now change the branch name is like creating a new one and removing the old, so all the previous users will not switch automatically.
Maybe it is the case to add a warning in VVV (dashboard and vagrantfile) that the branch master is not used anymore and is not updated.

**Comment by tomjn** [comment]
We now have a `stable` branch on the main VVV repo, we should look at updating as many docs as possible

**Comment by tomjn** [comment]
Based on githubs renaming effort, I think we can hold off on this for now, and instead focus on improving VVV's support for default branches. That way we can let GitHub do the heavy lifting and gain redirects of `master` to `main`.

Right now VVV assumes `master` is the default for other repos, which we need to fix

**Comment by tomjn** [comment]
@Mte90 do you think deleting the `master` branch now that we have `stable` and `develop` would make sense? Anybody who tries to upgrade would be forced to switch branches?

Or should we treat `master` as a special case and make it refuse to provision and give out instructions on how to switch instead?

**Comment by Mte90** [comment]
I think that as today after 2 years is fine.

If someone tries to update using master it will write anyway for support and will discover the branch changing.

**Comment by tomjn** [comment]
closing this as VVV core `master` branch now short circuits and tells you to switch to `stable`
