### ISSUE TITLE
WordPress in a subdirectory but I don't want the domain to point to it

### ISSUE THREAD

**Issue by pnpetroff** [Varying-Vagrant-Vagrants/VVV#2187]
I'm trying to install WordPress in a subfolder - renamed `public_html` to `wp` in `vvv-init.sh` and it worked great.

However, I want to have `index.php` file in the main dir, e.g. the `www/project-name` to be opened when visiting the domain, instead of the `wp/index.php` one.

This is how my `vvv-nginx.conf` and `vvv-nginx-custom.conf` files in the provisioning folder look like:

```
server {
    listen       80;
    listen       443 ssl http2;
    server_name  {vvv_hosts};
    root         {vvv_path_to_site};

    # Nginx logs
    error_log    {vvv_path_to_site}/log/nginx-error.log;
    access_log   {vvv_path_to_site}/log/nginx-access.log;

    # This is needed to set the PHP being used
    set          $upstream {upstream};

    # Enable server push if SSL/HTTP2 is being used for link preload headers
    http2_push_preload on;

    {vvv_tls_cert}
    {vvv_tls_key}

    # Nginx rules for WordPress, rewrite rules, permalinks, etc
    include      /etc/nginx/nginx-wp-common.conf;

    location ~* \.(css|eot|gif|ico|jpeg|jpg|js|png|svg|tiff|tiff|ttf|webp|woff|woff2)$ {
        expires 100d;
    }

    location / {
        index ./index.php ./index.html;
    }
}
```

Tried putting `./index.php` and ../index.php in the `location` block but provisioning still gives:
```
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```
Provisioning completes without that part but it doesn't achieve my goal that way. Any help is greatly appreciated.

**Comment by tomjn** [comment]
> vvv-init.php

Is this `vvv-init.sh` or are you using a different site template? I ask because there is a 3rd party site template that uses PHP files rather than bash scripts to do its provisioning

Are you trying to take a git repo that just contains a WP site and retrofit it so it contains VVV provisioners?

**Comment by pnpetroff** [comment]
> Is this `vvv-init.sh` or are you using a different site template?

Sorry, it's the `vvv-init.sh` file. I just found and replaced all instances of `public_html` with `wp` by using a copy of the `vvv-init.sh` file from the wordpress-one example installation.


> Are you trying to take a git repo that just contains a WP site and retrofit it so it contains VVV provisioners?

The repo looks like this:
![image](https://user-images.githubusercontent.com/1108563/84893583-23cf3d80-b0a8-11ea-8150-dacd4019a4a7.png)
It's because I want VVV to install the Wordpress installation in a `wp` subdirectory but still use the themes and plugins in `wp-content` in the main dir by loading them with the `index.php` in the main dir:

```php
define('WP_USE_THEMES', true);
/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wp/wp-blog-header.php' );
```

**Comment by tomjn** [comment]
I see, it's just that in the process of trying to do a WP subfolder install, you've also accidentally hoisted everything up 1 folder unnecessarily.

Usually on a webhost you've got your folder, which iis the equivalent of `/srv/www/wordpress-one`, then the folder that has WP and is exposed to the internet `/srv/www/wordpress-one/public_html`, but by moving everything up 1 folder nginx changes are required.

If instead, you kept everything in `public_html` as originally intended, no Nginx changes would be required to achieve this.

**Comment by tomjn** [comment]
For git clones, it should do them from first to last, and if a git repo already exists at that location it should skip it with a message and let the developer handle version control from that point forward, rather than resetting the branch etc If the folder already exists but has no `.git` folder, delete it and clone its replacement
