### ISSUE TITLE
Utility: Elastic Search

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2189]
I'd like us to have an elastic search utility.

 - It will need a version configuration via `config/config.yml` to set the version
 - It'll need to install java, this might mean a JDK/Java utility, but right now I think to leave this to the discretion of the author
   - we set precedent with monogdb, but I think that's a little different as you can use mongodb for object caching in WP and other things, so it's more useful
 - I saw someone using VVV 1.3 had made a site provisioner just to install ES and ElasticHQ here: https://github.com/rooftopcms/vvv-elasticsearch/blob/master/vvv-init.sh there'll be better ways to provision than this though
 - Elastic HQ as a utility might be useful and easy to add, it will require updating the dashboard to add the button for it

**Comment by Mte90** [comment]
Just a thought, instead of elasticsearch that is huge maybe we can integrate that is an alternative https://github.com/valeriansaliou/sonic

But I didn't test both so it's just a thought.

**Comment by tomjn** [comment]
That might be interesting for it’s own sake but there are a lot of VVV
users who have elastic search in production. I know a good few people who
use chassis over VVV specifically because they need elastic to reproduce
production environments and fix issues that require ES to reproduce

**Comment by Mte90** [comment]
done https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/92
