### ISSUE TITLE
Deprecate Dashboard settiings

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2198]
A dashboard is just a site that acts as a dashboard, so why do we need dedicated options? We should deprecate those options, and change dashboard provisioning so it's a lot closer if not the same as site provisioning.

For future plans, we want to have an app and an API, and that breaks with custom dashboards at vvv.test. There is nothing preventing users from putting in their dashboard repos a `provision/vvv-nginx.conf` and adding it to the sites section with the site name `dashboard` and `dashboard.test` as the host.

**Comment by evertiro** [comment]
This appears to be a duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1946, unless I'm missing something.

**Comment by tomjn** [comment]
Good catch
