### ISSUE TITLE
install_themes in config.yml does not behave as expected

### ISSUE THREAD

**Issue by arturbruno** [Varying-Vagrant-Vagrants/VVV#2203]
Hello. On one of my sites on VVV I decided to use the option `install_themes `as described in https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/git-and-ssh-keys/. When adding the list of themes in my config.yml file and executing the `vagrant reload --provision` command the restart of the virtual machine and changes made to the config.yml file occur normally. However, themes that are not in the official WordPress theme directory (
https://wordpress.org/themes/) end up not being installed on my website, when inserting a theme that is stored in a GitHub directory I am always returned with **Error: No themes installed** and **Warning: <URL theme> theme could not be found**

Apparently the error was only happening with private directories on GitHub, but when testing with a public directory, the output on my GitBash was the same.

**I used the same themes described in:**
https://github.com/Varying-Vagrant-Vagrants/custom-site-template

- understrap
- https://github.com/understrap/understrap-child.git

and

- I also added my theme in install_themes which is stored in a private GitHub directory

**Note**: all SSH settings have already been performed on my computer:

- The SSH key has already been generated
- I already connected it to my GitHub
- I followed all the steps described in: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
- I followed all the steps described at: https://help.github.com/en/enterprise/2.15/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh- agent
- I followed all the steps described in: https://help.github.com/en/enterprise/2.15/user/articles/working-with-ssh-key-passphrases
- I have already tested the install_themes option on other sites, the error persists

**My settings:**
Operating System: Windows 10
Vagrant: 2.2.9
VirtualBox: 6.1.8
VVV: 3.4.1

I appreciate any feedback on the issue

![code1](https://user-images.githubusercontent.com/29176582/85406844-c409e400-b538-11ea-91d0-468527e66541.png)

![out1](https://user-images.githubusercontent.com/29176582/85406865-ccfab580-b538-11ea-9453-6633e395900a.png)

**Comment by tomjn** [comment]
The plugin and theme options are passed directly into WP CLI, IIRC WP cli
expects either a zip file or a .org hosted theme. You can’t pass in URLs or
git repos
