### ISSUE TITLE
wp dates are wrong

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2204]
WP dates were fine. 

Just started showing:
`Universal time is 2020-07-02 06:11:04. Local time is 2020-07-01 23:11:04.`

But the local time is: `2020-07-03 14:25:04`
This issue is consistent across all our vagrant sites. 

Windows 10 64 bit - shows the correct time on desktop.

**Comment by tomjn** [comment]
Hello! Which version of VVV/Vagrant/Vbox are you using?

**Comment by shanebp** [comment]
Just updated to:
VVV: 3.1.4
Vagrant: 2.2.5
VirtualBox-6.1.10-138449-Win

On provision, there is a problem on restart nginx
```
    default:  * Restarting Nginx and MySQL
    default: Job for nginx.service failed because the control process exited with error code.
    default: See "systemctl status nginx.service" and "journalctl -xe" for details.
```

Full Log: 
[https://gist.github.com/shanebp/b22da4fd7d30d9a49ae171b820dc06dd](https://gist.github.com/shanebp/b22da4fd7d30d9a49ae171b820dc06dd)

**Comment by tomjn** [comment]
I'm seeing this in the provision log a lot:

```
    default: sed: -e expression #1, char 19: unknown option to `s'
```

Are those sites using the standard custom site template? Or something else? Can I see the log file for one of those sites? If you updated to v3.4.1, what were you on previously?

**Comment by shanebp** [comment]
I believe I was on that last version of VVV, but am not sure. 
All the sites use:
     repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
Except  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git

> Can I see the log file for one of those sites?
Sorry, but you need to be explicit about log file - where?

I don't know what I'm doing re nginx, but maybe this helps:
```
vagrant@vvv:~$ nginx -t
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:9
nginx: [emerg] unexpected "{" in /etc/nginx/custom-sites/vvv-auto-atrium-provision-c2817417a7a6700c8682608cdca5649f.conf:18
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by tomjn** [comment]
> Sorry, but you need to be explicit about log file - where?

Each provisioner creates a log file in the main logs folder, each site will have a provisioner log, that's why you only see a little snippet of output even though there's output from WP CLI etc. As for which one, any of them will do as they all exhibit the same issue. Look in `logs/provisioners` for logs from provisioners.

**Comment by shanebp** [comment]
Thanks for instructions. Here is a provisioner log:

[38;5;2m ▷ Running the 'site-atrium' provisioner...[0m
 * Updating atrium in /srv/www/atrium...
 * Adding domains to the virtual machine's /etc/hosts file...
 * Adding hosts from the VVV config entry
   - Added local.atrium.test from /vagrant/config.yml
 * Searching for a site template provisioner, vvv-init.sh
 * Found vvv-init.sh at /srv/www/atrium/provision/vvv-init.sh
 * Custom site template provisioner atrium - downloads and installs a copy of WP stable for testing, building client sites, etc
 * Creating database 'atrium' (if it's not already there)
 * Granting the wp user priviledges to the 'atrium' database
 * DB operations done.
 * Setting up the log subfolder for Nginx logs
 * Creating public_html folder if it doesn't exist already
 * Install type is 'single'
 * Updating WordPress 'latest'
Success: WordPress is up to date.
 * Copying the sites Nginx config template
 * Using the default vvv-nginx-default.conf, to customize, create a vvv-nginx-custom.conf
 * Site Template provisioner script completed for atrium
sed: -e expression #1, char 19: unknown option to `s'
 * Reloading Nginx
[38;5;2m ✔ The 'site-atrium' provisioner completed in 7 seconds.[0m

**Comment by shanebp** [comment]
Every provision log has this line:
`sed: -e expression #1, char 19: unknown option to `s'`

**Comment by shanebp** [comment]
I've updated the gist to include the `config.yml`

**Comment by tomjn** [comment]
hmm nothing looks bad there, aside from the same error, that implies it doesn't happen in the site provisioner but in VVV cores `provision/provision-site.sh`.

Can you try this on the `develop` branch and confirm if the behaviour is the same? And if possible  could you get me a copy of the final Nginx file for one of those sites?  Any of the files in `/etc/nginx/custom-sites` that start with `vvv-auto` e.g. I have a `vvv-auto-wordpress-one-provision-60730e707ede8a21f013860b6fc556e1.conf` in mine. That would give me a clue as to which `sed` call that error is coming from. Do this before switching to the `develop` branch though

**Comment by shanebp** [comment]
Sorry about the need for handholding... 

What is the full path to: `/etc/nginx/custom-sites` ?

Re develop branch - once I have the nginx file, do this ?
`git clone -b develop git://github.com/Varying-Vagrant-Vagrants/VVV.git ~/vagrant-local`

**Comment by tomjn** [comment]
It’s already the full path, SSH into the VM and cd into
/etc/nginx/custom-sites

You can copy the file into /srv/www which is mapped to www in your VVV
folder

It’s 1am here so I’ll need to sleep but I can circle back in the morning

>

**Comment by shanebp** [comment]
Here is the `vvv-auto-atrium.dev1-provision-d5f40fb69449aa85e881f1b199a0d29a.conf
`
```
server {
    listen       80;
    listen       443 ssl http2;
    server_name  local.atrium.dev1;
    root         /srv/www/atrium.dev1/public_html;

    # Nginx logs
    error_log    /srv/www/atrium.dev1/log/nginx-error.log;
    access_log   /srv/www/atrium.dev1/log/nginx-access.log;

    # This is needed to set the PHP being used
    set          $upstream php;

    # Enable server push if SSL/HTTP2 is being used for link preload headers
    http2_push_preload on;

    # TLS cert not included as the core tls-ca is not installed
    {vvv_tls_key}

    # Nginx rules for WordPress, rewrite rules, permalinks, etc
    include      /etc/nginx/nginx-wp-common.conf;

    

    location ~* \.(css|eot|gif|ico|jpeg|jpg|js|png|svg|tiff|tiff|ttf|webp|woff|woff2)$ {
        expires 100d;
    }
}
```

**Comment by shanebp** [comment]
I tried to test the develop branch. Here is the log:

```
c:\vagrant-local\~>cd vagrant-local

c:\vagrant-local\~\vagrant-local>vagrant up -provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.5.0-git::develop

Copying config/default-config.yml to config/config.yml
IMPORTANT NOTE: Make all modifications to config/config.yml in future so that they are not lost when VVV updates.

Platform: platform-mingw32 windows  HasWinAdminPriv  vagrant-hostsupdater NoColour shared_db_folder_disabled, VVV Path: "c:/vagrant-local/~/vagrant-local"
Vagrant: v2.2.9, VirtualBox: v6.1.10r138449

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Vagrant has detected project local plugins configured for this
project which are not installed.

  vagrant-goodhosts
Install local plugins (Y/N) [N]: y
Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Fetching vagrant-goodhosts-1.0.1.gem
Installed the plugin 'vagrant-goodhosts (1.0.1)'!

Vagrant has completed installing local plugins for the current Vagrant
project directory. Please run the requested command again.

c:\vagrant-local\~\vagrant-local>vagrant up -provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.5.0-git::develop

Platform: platform-mingw32 windows  HasWinAdminPriv  vagrant-hostsupdater NoColour shared_db_folder_disabled, VVV Path: "c:/vagrant-local/~/vagrant-local"
Vagrant: v2.2.9, VirtualBox: v6.1.10r138449

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Traceback (most recent call last):
        4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:205:in `<main>'
        3: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:290:in `cli'
        2: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/cli.rb:67:in `execute'
        1: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/commands/up/command.rb:54:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/v2/command.rb:62:in `parse_options': invalid option: p (OptionParser::InvalidOption)
        4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:205:in `<main>'
        3: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:290:in `cli'
        2: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/cli.rb:67:in `execute'
        1: from C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/commands/up/command.rb:54:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/v2/command.rb:62:in `parse_options': ambiguous option: -provision (OptionParser::AmbiguousOption)
```

**Comment by tomjn** [comment]
2 things:

```nginx
    # TLS cert not included as the core tls-ca is not installed
    {vvv_tls_key}
```

This is the part that failed to get replaced, and I notice for some reason the `tls-ca` utility is not enabled in your `config.yml` file. Can you enable it?

As for why `develop` doesn't work, it's because you used `-provision` instead of `--provision`. You should open an issue reporting that it crashes `vagrant` on their github when only a single hypen is used. Hopefully it can be resolved in Vagrant 2.3.0 if it's done quickly enough.

In the meantime Use `vagrant up --provision` with 2 `-`'s.

**Comment by shanebp** [comment]
I enabled `tls-ca` utility in `config.yml` and restarted using `master`.
It stared cleanly and **the date issue is resolved**.

>open an issue reporting that it crashes vagrant on their github when only a single hypen is used

Done. [https://github.com/hashicorp/vagrant/issues/11743](https://github.com/hashicorp/vagrant/issues/11743)

Once again - thank you for walking me past such a basic error.

**Comment by tomjn** [comment]
No thankyou :) While I'd expect `tls-ca` to be present, **its absence should not cause this**, you were right to open the issue

**Comment by tomjn** [comment]
I'm closing this out now that #2205 is merged into `develop`
