### ISSUE TITLE
Mismatched Apt Hashes Preventing Provisioning When The User is Unlucky and provisions while the package repo is updating.

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2208]
Due to the way `apt` mirrors work, there's the chance of a race condition. If you try to update apt and install a package while the mirror is updating it can lead to mismatched hashes. This prevents apt installation.

Simply reprovisioning does not fix this, and the VM is left in a limbo state until the problem is manually fixed, or the VM is destroyed and recreated

Googling suggests the fix is to `sudo rm -rf /var/lib/apt/lists/*` when cleaning so that the next `sudo apt-get update` can fetch valid lists

**Comment by tomjn** [comment]
i've asked @mattorourke to SSH into the VM and run:

```
sudo apt-get clean -y
sudo rm -rf /var/lib/apt/lists/*
sudo apt-key update -y
sudo apt-get update -y
sudo apt-get upgrade -y
```

It's all the commands from various answers taken from https://stackoverflow.com/questions/15505775/debian-apt-packages-hash-sum-mismatch

There's a suggestion by one answer to add an apt config file, but I suspect that's centred around proxy issues

**Comment by Mte90** [comment]
Can we consider this fixed?

**Comment by tomjn** [comment]
It's not happened in a while and we've put mitigation in place. If it happens again feel free to reopen by commenting or a new issue
