### ISSUE TITLE
Bundle WP-CLI SSH with VVV?

### ISSUE THREAD

**Issue by westonruter** [Varying-Vagrant-Vagrants/VVV#221]
This is to open a discussion about bundling [WP-CLI SSH](https://github.com/x-team/wp-cli-ssh) with VVV. If the user's `wp` invokes the WP-CLI provisioned by VVV, then they would have the `ssh` command available. They would then be able to do `wp ssh --host=vagrant command subcommand…` to connect to WP-CLI inside of Vagrant.

There are a couple outstanding issues that I think need to be addressed first (https://github.com/x-team/wp-cli-ssh/issues/3 and https://github.com/x-team/wp-cli-ssh/issues/10), but I wanted to open an issue to start a conversation.

**Comment by jeremyfelt** [comment]
@westonruter I'm walking through ooooold issues. :) Any updates on the WP-CLI SSH front?

**Comment by westonruter** [comment]
Not lately :smile:
