### ISSUE TITLE
Prevent use of sudo vagrant up

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2215]
Some users are typing `sudo vagrant up`, this is very bad! Once this is done it's possible to have 2 VMs occupying the same folder, and it leads to a non-trivial cleanup process.

We need to prevent this from happening, no VVV user should be using `sudo` to start the VM. VVV should check super early in the vagrantfile if the user is running as `root` on non-Windows environments, and exit early if that's the case, displaying an appropriate message indicating the seriousness of this mistake, and linking to this issue.

**Comment by Mte90** [comment]
https://stackoverflow.com/a/52747608/1902215 this code should do what we need
