### ISSUE TITLE
Update time on provision

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2217]
A few users have arrived at odd VM time/date situations for unknown reasons via various paths, it would be useful to run an ntp date sync at the beginning of provision in the main provisioner

```shell
ntpdate ntp.ubuntu.com
```

**Comment by tomjn** [comment]
I realise there's a potential complication here, if the time is wrong, then this will mean the provisioner will give incorrect timings, so the time update has to happen before the initial time is acquired, or we just ignore that particular discrepancy. Or, we discount the time it took to run ntp and use the difference between the before and after to adjust for the shift.

I'm also not sure if this command comes with the vagrant box or if it's installed via apt

**Comment by Mte90** [comment]
That command should be part of any linux distro as it is part of the standard.

**Comment by Mte90** [comment]
Seems that is something that can be achieved Vagrnat side:

```
vb.customize [ “guestproperty”, “set”, :id, “/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold”, 10000 ]
```

I will investigate a bit

**Comment by Mte90** [comment]
I tried this one and doesn't work.
I think that guestadditions doesn't works good as the box we are using is still using the one for virtualbox 5.1.

So I was thinking to try https://github.com/tmatilai/vagrant-timezone and see if it works

**Comment by tomjn** [comment]
there's always updating guest additions, I'm not a fan of relying on more vagrant plugins. A solution inside the VM might be as simple as running the ntp update on a cron job

**Comment by Mte90** [comment]
But is not aligning the time with the host machine.
As example to me is to hours behind so it is not just UTC time but the right timezone.

**Comment by Mte90** [comment]
The plugin works and set the right timezone from the host machine, i can do a pr.
In a way that is not mandatory but we support it.

**Comment by Mte90** [comment]
So we need ntp sync command on https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/vagrant_up 

And see if we can sync timezone between the machines https://github.com/tmatilai/vagrant-timezone/blob/master/lib/vagrant-timezone/cap/linux.rb

**Comment by tomjn** [comment]
`vagrant-timezone` won't solve this as that just sets the timezone, it doesn't fix incorrect time

We can run the time/clock sync/update command in https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/vagrant_up

**Comment by tomjn** [comment]
Just to clarify, the goal is not to have the same timezone as the host, or the same time, but for the time inside the VM to be accurate. The problem is the clock has missed out and fallen behind, or is wildly incorrect by hours/days/months causing certificates checks to fail and provisioning to break

**Comment by Mte90** [comment]
Ok for the timezone of the host require some ruby code https://github.com/tmatilai/vagrant-timezone/blob/master/lib/vagrant-timezone/cap/debian.rb

So I think that we can add a parameter in the `config.yml` field that write the timezone inside the machine.
