### ISSUE TITLE
Wrap top level commands in provision.provision.sh

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2218]
There are a number of top level commands at the beginning of `provision/provision.sh` that do things like fix the bash profile, chmod files, etc. These should be put inside a bash function then called so that the file is cleaner and easier to work with

**Comment by msaggiorato** [comment]
This is related to #2230 I'd say. There's still some things at the top there, which could be moved, but first would need refactor (like removing /vagrant).

Just mentioning this so that the reference is listed.

**Comment by tomjn** [comment]
Happy to close this thanks to that work, good job!
