### ISSUE TITLE
Custom Site Template Requires Master Branch

### ISSUE THREAD

**Issue by davidwolfpaw** [Varying-Vagrant-Vagrants/VVV#2219]
## Expected Behavior

I now use `main` as my default branch for repos, likely for similar reasons as https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2184

I would like to be able to provision new sites from a branch other than `master` for my own site template repo.

## Current Behavior

Running `vagrant up --provision` on a new or existing VVV install with a branch other than `master` for the site template repo in my `config.yml` file yields the following error:

```
==> default: Running provisioner: site-testbuild (shell)...
    default: Running: /var/folders/n0/yt1tss9x2d51v4qzblb_vytc0000gn/T/vagrant-shell20200718-17360-1f7kxnr.sh
    default:  ▷ Running the 'site-testbuild' provisioner...
    default: fatal: Remote branch master not found in upstream origin
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

When I create a branch named `master`, the provision succeeds, even when that branch is not default.

```

    default: /tmp/vagrant-shell: line 244: return: can only `return' from a function or sourced script
    default:  ✔ The 'site-testbuild' provisioner completed in 111 seconds.
==> default: Running action triggers after reload ...
==> default: Running trigger: VVV Post-Reload...
    default: Running: inline script
    default:  * Restarting Nginx and MySQL
    default:
    default:          yay
```

## Possible Solution

I would like to see the provisioning script look for the default branch of a repo, not specifically for one named `master`.

## Steps to Reproduce (for bugs)

1. Create a site template repository that does not include a `master` branch
2. Attempt to run `vagrant up` on first install, or `vagrant up --provision` or 'vagrant reload --provision` on an existing install of VVV
3. Note the error `fatal: Remote branch master not found in upstream origin`
4.

## Your Environment

OS: MacOS Catalina 10.15.6
Virtualbox v6.1.12 r139181 (Qt5.6.3)
Vagrant v2.2.9
VVV v3.4.1

**Comment by tomjn** [comment]
You need to tell it the branch to use, VVV always specifies the branch name, defaulting to `master`. Changing that default value would cripple non-official site templates unless they all switched too ( and switched to the same value ).

In order to support non-master default branches other changes will be needed so this isn't an quickfix.

However, for you specifically, the fix is trivial: `branch: main`

**Comment by tomjn** [comment]
To support arbitrary default branches when the `branch` parameter is not specified we would need to adjust this code:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L132-L151

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L180

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L207

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L218

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L224

**Comment by tomjn** [comment]
@davidwolfpaw did specifying the `branch` parameter work for you?

**Comment by davidwolfpaw** [comment]
I didn't realize that I could specify a separate branch. Thanks for pointing that out!
