### ISSUE TITLE
vvv not backing up my custom site databases - 

### ISSUE THREAD

**Issue by Pezzab** [Varying-Vagrant-Vagrants/VVV#2220]
When I manually run a database backup (or do `vagrant halt`) only the default sites are backed up.

What do I have to do to ensure my custom sites defined in `vvv.custom.yml` are backed up too?

```
$ vagrant ssh -c "db_backup"
 ⚠ ! Running additional Vagrant code in Customfile located at C:/Users/user.name/vvv-dev/Customfile
 ⚠ ! Official support is not provided for this feature, it is assumed you are proficient with vagrant

 ⚠ ! Finished running Customfile, resuming normal vagrantfile execution

 * Performing Database Backups
   - Backing up "wordpress-one" to database/backups/wordpress-one.sql
   - Backing up "wordpress-two" to database/backups/wordpress-two.sql
 * Finished backing up databases
Connection to 127.0.0.1 closed.
```

BTW this is on a clean install of VVV 3 not an upgrade.

**Comment by tomjn** [comment]
What are your custom databases called? Could this be related ot #2213 and #2212 ? Can you test that PR too see if it changes this?

```
 ⚠ ! Running additional Vagrant code in Customfile located at C:/Users/user.name/vvv-dev/Customfile
 ⚠ ! Official support is not provided for this feature, it is assumed you are proficient with vagrant

 ⚠ ! Finished running Customfile, resuming normal vagrantfile execution
```

😱 keep in mind that anything said here may be totally irrelevant to you or may not apply as a result of loading additional vagrant code. We don't offer support for `Customfile`'s it's a use at your own risk feature. Can I ask what you use it for?

**Comment by tomjn** [comment]
Looks like that PR got merged, can you check this is still an issue on the `develop` branch?

**Comment by Pezzab** [comment]
Hi @tomjn,

The databases are named qualsafe-academy-test and fos-test.

I use Customfile to import my themes and plugins from an external directory.

**Comment by tomjn** [comment]
@Pezzab does the latest `develop` work? If not can I see the output?

Also, we explicitly enable symlink support for the `www` and `config` folders, you should be able to symlink in those folders without needing to add a VM mount. You also don't have to store a site in the `www` folder, you can move the entire things elsewhere by specifying `local_dir` and `vm_dir` in thats sites options in `config.yml` and it will mount it separately, letting you put it anywhere on your machine ( just avoid mapping to network shares )

**Comment by Pezzab** [comment]
Thanks Tom,

I've been using vvv this way for so long now (and it's worked OK) that I haven't really investigated other options but I will look into these right away.

Which output do you need sorry?

**Comment by tomjn** [comment]
Same as your original post, `vagrant ssh -c "db_backup"`, I'm assuming then that the changes merged a few hours ago did not work for you?

**Comment by Pezzab** [comment]
I'm definitely on the develop track. Here's output after vagrant halt:

```
$ vagrant halt
 ⚠ ! Running additional Vagrant code in Customfile located at C:/Users/perry.bonewell/vvv-dev/Customfile
 ⚠ ! Official support is not provided for this feature, it is assumed you are proficient with vagrant

 ⚠ ! Finished running Customfile, resuming normal vagrantfile execution

==> default: Running action triggers before halt ...
==> default: Running trigger: VVV Pre-Halt...
    default: Running: inline script
    default:  * Performing Database Backups
    default:    - Backing up "wordpress-one" to database/backups/wordpress-one.sql
    default:    - Backing up "wordpress-two" to database/backups/wordpress-two.sql
    default:  * Finished backing up databases
    default:    .  ★         ☁           ★          .
    default: Z        ☽    ★         .        ☁
    default:  Z ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄   ★            __★__ __ __
    default: ☁ z█▒▒░░░░░░░░░▒▒█    Sleep tight \ V\ V\ V /
    default:  ★  █░░▁░░░░░▁░░█  ★               \_/\_/\_/
    default:    . █░░░▀█▀░░░█ .          ★
    default:  ★   ▀▄░░░░░░░▄▀  ★     .
    default:
==> default: Attempting graceful shutdown of VM...
==> default: [vagrant-goodhosts] Removing hosts
==> default: [vagrant-goodhosts] Warning: The vagrant-hostsupdater plugin is installed, hostsupdater always adds the VM name even if the VagrantFile says not to. This shouldn't cause issues, but if it does, uninstall hostsupdater
==> default: [vagrant-goodhosts] - remove entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater] Removing hosts
```

And if I run the backup manually:

```
user.name@laptop029 MINGW64 ~/vvv-dev (develop)
$ vagrant ssh -c "db_backup"
 ⚠ ! Running additional Vagrant code in Customfile located at C:/Users/user.name/vvv-dev/Customfile
 ⚠ ! Official support is not provided for this feature, it is assumed you are proficient with vagrant

 ⚠ ! Finished running Customfile, resuming normal vagrantfile execution

 * Performing Database Backups
   - Backing up "wordpress-one" to database/backups/wordpress-one.sql
   - Backing up "wordpress-two" to database/backups/wordpress-two.sql
 * Finished backing up databases
Connection to 127.0.0.1 closed.
```

**Comment by tomjn** [comment]
> I'm definitely on the develop track. 

And you definitely have the changes merged several hours ago?

```sh
mysql --user="root" --password="root" -e 'show databases' | \
grep -v -F "^information_schema$" | \
grep -v -F "^performance_schema$" | \
grep -v -F "^mysql$" | \
grep -v -F "^test$" | \
grep -v -F "Database" | \
```

Note the `^` and `$`, they should be present in your `db_backup` script in `config/homebin/db_backup`

**Comment by Pezzab** [comment]
That was the issue - ran git pull and now the backups are running. Sorry for the false alarm I'm not sure how I missed that.

**Comment by tomjn** [comment]
Awesome :D a big thanks to @paulschreiber who fixed the issue!
