### ISSUE TITLE
vvv.test’s server IP address could not be found.

### ISSUE THREAD

**Issue by ineffable-92** [Varying-Vagrant-Vagrants/VVV#2222]
I have freshly Installed VVV on my Windows 10 64-bit. The Installation process was successful but the vvv.test page shows vvv.test’s server IP address could not be found. I don't find any valid reason for that.

Vagrant: v2.2.9, VirtualBox: v6.1.12r139181

The Output for vagrant up:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20200717.0.0' is up to date...
==> default: [vagrant-goodhosts] Checking for host entries
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 one.wordpress.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 two.wordpress.test
==> default: [vagrant-goodhosts] Issue executing goodhosts CLI: Host file not writable. Try running with elevated privileges.
==> default: [vagrant-goodhosts] Cli path: D:/Vagrants/VVV/.vagrant/plugins/gems/2.6.6/gems/vagrant-goodhosts-1.0.1/lib/vagrant-goodhosts/bundle/cli.exe
==> default: [vagrant-goodhosts] Check the readme at https://github.com/goodhosts/vagrant#passwordless-sudo
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default:  * Restarting Nginx and MySQL
    default: 
    default:          yay
    default:  ✧ ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄ ✧              __ __ __ __
    default:   ✧█▒▒░░░░░░░░░▒▒█    Thanks for  \ V\ V\ V /
    default: ✧   █░░█░░░░░█░░█ ✧   using        \_/\_/\_/
    default:  ▄▄  █░░░▀█▀░░░█  ▄▄✧
    default: █░░█ ▀▄░░░░░░░▄▀ █░░█ Vagrant Up has finished! Visit http://vvv.test
    default:
```

Could You please suggest and help me with this issue of not being able to access the dashboard (vvv.test)

Thank again for using VVV, and helping out!! -->

**Comment by Mte90** [comment]
As I can understand the issue is that on the browser the page is not found like with a nginx error.
Can you try a vagrant provision? Usually this fix everything like a wrong shutdown of the VM as example (I do in that way when there are this issue).

**Comment by ineffable-92** [comment]
Yeah Tried
It works fine with Command Prompt. But the webpage is not available

**Comment by tomjn** [comment]
```
 ==> default: [vagrant-goodhosts] Issue executing goodhosts CLI: Host file not writable. Try running with elevated privileges.
```

**Did you run this in an elevated command prompt?** Or a normal one? You need to use an elevated prompt, usually by right clicking and selecting Run as Administrator.

If you do not, then the hosts file cannot be modified, and there is no way to tell Windows where `vvv.test` can be found.

**Comment by ineffable-92** [comment]
ThankYou For your kind Support. I wanted to know how to provision wordpress-trunk and wordpress-meta-environment.

**Comment by tomjn** [comment]
@ineffable-92 lets take this one step at a time, did you manage to run `vagrant up --provision` in an admin command prompt and visit `vvv.test` succesfully? You should be able to follow the documentation and tutorials that exist, it's just this one single mistake of running it in a normal command prompt rather than an elevated/admin command prompt

**Comment by ineffable-92** [comment]
Thankyou for you support.  The sites and the dashboard are there, live and available except wordpress-trunk and wordpress-meta-environment.

**Comment by tomjn** [comment]
> Thankyou for you support. The sites and the dashboard are there, live and available except wordpress-trunk and wordpress-meta-environment.

Awesome! Now lets get those environments working for you :)

In `config/config.yml` you'll find 2 sites, 1 for meta and 1 for working on WP core. What you're looking for are these lines:

```yaml
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
```

Not everybody uses the meta/trunk sites, so we skip them to save time for new users. They take some time to provision, but you can turn them back on by changing `true` to `false`, then reprovisioning with `vagrant up --provision`. This will reprovision VVV, and it'll see the new sites and start downloading/installing. Go make a cup of coffee/tea as it takes a while the first time.

If you're just after a way to do client work, building themes, plugins, or testing beta versions of WordPress, then the existing custom-site-template will do fine, e.g. `one.wordpress.test`.

`wordpress-trunk` is for testing patches and bleeding edge WP core development.

The meta environment is for things like WordCamps and work on .org itself

**Comment by ineffable-92** [comment]
Thankyou For solving my issue.
