### ISSUE TITLE
The specified host network collides with a non-hostonly network!

### ISSUE THREAD

**Issue by tedgeving** [Varying-Vagrant-Vagrants/VVV#2227]
Hi, not sure if this an VVV3 issue. t

The following error is displayed when running 'vagrant up' for the first time.  Host updater plugin is installed.  Any help would be appreciated.

> The specified host network collides with a non-hostonly network!
> This will cause your specified IP to be inaccessible. Please change
> the IP or name of your host only network so that it no longer matches that of
> a bridged or non-hostonly network.
> 
> Bridged Network Address: '192.168.50.0'
> Host-only Network 'en0: Wi-Fi (AirPort)': '192.168.50.0'

Additionally I changed the ip address in the Vagrant file in to:  defaults['private_network_ip'] = '192.168.50.14'

Thanks

**Comment by tomjn** [comment]
> Additionally I changed the ip address in the Vagrant file in to: defaults['private_network_ip'] = '192.168.50.14'

Did this resolve the issue?

The VM has its own IP and network adapter, the message is from `vagrant` indicating that the desired IP for the network adapter is already in use or already mapped on to another adapter that already exists ( your wifi network adapter )

**Comment by tedgeving** [comment]
Hey Tom, 
Changing the IP address did not resolve it.

Are you referring to changing this file? `vagrant-local/config/config.yml`

**Comment by tomjn** [comment]
Yes, you should never need to modify the `vagrantfile`. All I can suggest is that you do what the error message suggests. You need to make sure they do not overlap. **Clearly the new IP you set still overlaps. Try new ones.**

**Comment by tedgeving** [comment]
Turns out my host file had duplicate entires in it for the default sites.  Removing the entries and then adding a different ip address to the config.yaml file resolved the issue.

Host File
`## vagrant-hostmanager-start id: b06aeb41-da66-41d6-b4c7-58ca7dd903b6
192.168.50.14	vvv
192.168.50.14	vvv.test
192.168.50.14	one.wordpress.test
192.168.50.14	two.wordpress.test
## vagrant-hostmanager-end


## vagrant-hostmanager-start id: 4af8d565-4f13-480d-b835-b55a3559cb1f
192.167.50.50	vvv
192.167.50.50	vvv.test
192.167.50.50	one.wordpress.test
192.167.50.50	two.wordpress.test
## vagrant-hostmanager-end`

Thanks
