### ISSUE TITLE
Mute apt keys update

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2240]
Now the output is:

```
    default:  * Updating apt keys
    default: gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
    default: gpg: key 3B4FE6ACC0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" not changed
    default: gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
    default: gpg: key D94AA3F0EFE21092: "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" not changed
    default: gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
    default: gpg: key 871920D1991BC93C: "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>" not changed
    default: gpg: Total number processed: 3
    default: gpg:              unchanged: 3
    default:  * Running apt-get update...
    default: Get:1 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:2 https://deb.nodesource.com/node_10.x bionic InRelease [4584 B]
    default: Get:3 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main Sources [1746 B]
```

It should be enough https://github.com/Varying-Vagrant-Vagrants/VVV/blob/20d305109c88f5037cb623fe617f924ec8b8b548/provision/provision-helpers.sh#L281 add in that line `2> /dev/null`

**Comment by tomjn** [comment]
wouldn't it be better to fix the problem than mute it?

**Comment by Mte90** [comment]
In my experience this happens because there are old keys not valid anymore so there are no issues.
The only would be remove all of them or a `vagrant destroy` so ignore that warning is not a problem.

**Comment by tomjn** [comment]
the problem with muting is that if something goes horribly wrong, we'll have no idea as it'll be in neither the terminal output or the log file. I'd prefer we piped the output to the log file and didn't show it in the terminal, rather than pretending there was no output. Same goes for all the commands that currently use `/dev/null`, we should be moving away from it not towards it

**Comment by tomjn** [comment]
We'll take the same approach we use for site templates and utilities, everything goes in the log, but errors and progress messages go to the terminal. Hiding stuff just makes it impossible to debug when things go wrong
