### ISSUE TITLE
How to change PHP variable max_input_vars 

### ISSUE THREAD

**Issue by mostafaabd** [Varying-Vagrant-Vagrants/VVV#2242]
Varying Vagrant Vagrants v3.4.1
using PHP 7.4.9

I need changes the default PHP variables
memory_limit: 128
PHP time limit: 30
PHP max input vars: 1000

**Comment by tomjn** [comment]
What are you doing that needs this? Do the standard generic PHP ini overrides in `wp-config.php` not work?

**Comment by mostafaabd** [comment]
Hi,
The solution I found it.
@tomathyg thanks, but add PHP max_input_vars doesn't work in wp-config.php

I am using PHP 7.4.9 inside VVV.

What I do
I Edit this file vvv > provision > utilities > core > php74 > php7.4-custom.ini
then
$ vagrant reload --provision
