### ISSUE TITLE
Typo "immediatley" / "immediately" on `xdebug_on`.

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#2248]
I'm still on vvv 3.2.0. I haven't updated as everything works and in my experience, I very quickly realise I don't know as much as I thought I did about managing servers, and lose half a day, when I try to update :) 

Has this been fixed? Typo "immediatley" / "immediately" on `xdebug_on`.

I can't find where xdebug comes into play, but searching for the typo in this repo, vvv-utils, and the actual xdebug one came up with nothing. Thought I might find the code or a pr fixing it.

![image](https://user-images.githubusercontent.com/1038062/94315308-2fb97e00-ff7a-11ea-886f-e0d8e189b2fe.png)

**Comment by tomjn** [comment]
Fixed in https://github.com/Varying-Vagrant-Vagrants/VVV/commit/5f1efce1afd1c0ca2b7c7157f2055ab4acdb68ed

> I thought I did about managing servers, and lose half a day, when I try to update :)

It should be enough to do this:

```
git pull
vagrant up --provision
```

If that's not the case, you **must** tell us.
