### ISSUE TITLE
XHGUI: Move the collector reporting away from PDO

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2251]
Related to https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/69/ we currently use the PDO storage mechanism, but it's been mentioned by people more knowledgeable that we shouldn't interact directly with XHGUI's database.

Instead we should switch to either URL or cron+file based storage. My personal preference is URLs as it's more immediate

See here for the discussion that raised this https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/69/files#r483165833

**Comment by glensc** [comment]
You may want to use stack saver as default one:
- https://github.com/perftools/php-profiler/pull/35

Example (WIP currently):
- https://github.com/eventum/eventum/pull/955
