### ISSUE TITLE
Provisioning fails on Windows 10

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#2255]
I'm trying to setup VVV on my Windows 10 machine, and I got two failures. The first one was before I updated the WSL Linux kernel (https://docs.microsoft.com/en-gb/windows/wsl/wsl2-kernel), this one was the hash mismatch issue (https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2153 this basically).

I tried ssh-ing and clearing apt-cache, and destroying the box and provisioning again, but that didn't work. Then (because docker bugged me) I went and installed that patch for the WSL and now I get this when I try to provision

```bash
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.5.0-git::develop

Platform: platform-mingw32 windows  HyperV-Admin  HasWinAdminPriv  vagrant-goodhosts NoColour shared_db_folder_disabled, VVV Path: "D:/vagrant-local"
Vagrant: v2.2.10, VirtualBox: v6.1.14r140239

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20201007.0.0' is up to date...
==> default: [vagrant-goodhosts] Checking for host entries
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 developer-portal.test
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
==> default: Trigger run failed
==> default: An error occurred in the underlying SSH library that Vagrant uses.
==> default: The error message is shown below. In many cases, errors from this
==> default: library are caused by ssh-agent issues. Try disabling your SSH
==> default: agent or removing some keys and try again.
==> default:
==> default: If the problem persists, please report a bug to the net-ssh project.
==> default:
==> default: Net::SSH::ConnectionTimeout
```

### Environment details:

VirtualBox Version 6.1.14 r140239 (Qt5.6.2)
Vagrant version is 2.2.0
Windows 10
Using Powershell via Windows Terminal (not from WSL)

**Comment by Mte90** [comment]
Strange we are not using docker.
Looking on internet this is a vagrant error and not from VVV, on internet they suggests or a new `vagrant provision` or a `vagrant destroy && vagrant up`.

**Comment by tomjn** [comment]
Here's your problem:

```
Platform: platform-mingw32 windows  HyperV-Admin 
```

```
Bringing machine 'default' up with 'virtualbox' provider...
```

You have Hyper-V turned on, but you're using a VirtualBox provider. Even if this works, it would be sub-optimal. You need to switch to the Hyper-V provider

Note that Hyper-V is needed/turned on when you active WSL, if you're using VirtualBox 6.x it will pretend it works then try too use Hyper-V behind the scenes, but Oracles Hyper-V support is awful. That's why we suggest VirtualBox 5.x for WIndows as it will just exit and tell you Hyper-V is enabled.

**Comment by dingo-d** [comment]
Oh, that makes sense. I had to turn Hyper-V on because of Docker as well. Will try downgrading the VirtualBox and see what happens 👍

**Comment by tomjn** [comment]
If you downgrade virtual box to 5.x it’ll tell you hyper v is turned on and
abort

You need to switch to the hyper v provider, virtual box is not viable in
your situation

**Comment by dingo-d** [comment]
Yeah, I've disabled the hyper-v and it worked. Will try to change the provider to hyper-v and reprovision.

**Comment by tomjn** [comment]
You’ll need to destroy the VM and set hyper V as the provider beforehand,
ensuring hyper V is turned on, then create a new VM. The new one will use
hyper V rather than virtual box
