### ISSUE TITLE
Hi, i need help width libvir provider

### ISSUE THREAD

**Issue by lordvalor** [Varying-Vagrant-Vagrants/VVV#2259]
I want to use vvv with virt-manager and kvm

i'm using the following command
` vagrant up --provider=libvirt` 

but i cant run vvv

this show  a message
` ` ` 
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.4.1-git::master

Vagrant failed to initialize at a very early stage:

The executable 'VBoxManage' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
` ` `

I don't want to use Virtualbox for run vvv.

Regrats

**Comment by tomjn** [comment]
This will require some work, and may not be possible, it's definitely unsupported by us.

You'll need to:

 - specify the provider
 - specify the box in `config.yml`, our Vagrantfile doesn't do this for libvirt
 - we specify overrides for shared folders specific to Hyper-V, VMWare etc, some may be needed for this new provider

You can use a vagrant customfile for any changes to the Vagrantfile you need to make, but as far as support goes you're on your own. Nobody on the team uses libvirt or knows how to use it, if things don't work or you run into an issue getting libvirt working we can't help. If you do have fixes though we can integrate them to make life easier in the future
