### ISSUE TITLE
Default Nginx config

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2279]
When a site doesn't provide an Nginx config, we should fallback to a generic Nginx config in the sites provisioner

**Comment by Mte90** [comment]
I am just thinking how to fix this issue.
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L86
Looking here I think that the point is to check here if the file exists, otherwise pick the files from `/srv/provision/core/nginx/config/nginx.conf`.

**Comment by tomjn** [comment]
we would have a copy of the file and code to set it up in VVV core. We wouldn't support the custom options though, just hosts and TLS
