### ISSUE TITLE
sites whose names differ from hosts are no longer accessible, Regression introduced by #2267

### ISSUE THREAD

**Issue by skorasaurus** [Varying-Vagrant-Vagrants/VVV#2284]
Sites whose names are different than that of the hosts are not accessible; I believe may be a regression related to https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2267

After working with @tomjn this afternoon; I had deleted one of my sites (named [wordpress-default in my config file](https://gist.github.com/skorasaurus/230d4d9457e9b6d1718d3c8cb673f174)); and was to recreate it from scratch using the https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git ; so I deleted the site's folder in www; 
and issued `vagrant up --provision` ; vagrant loaded as expected.
my other websites (which all have single names like 'fse' 'zach.test') loaded as expected in my browser. 

However [`local.wordpress.test`](https://gist.github.com/skorasaurus/230d4d9457e9b6d1718d3c8cb673f174#file-config-yml-L24) was not loading for me; specifically when visiting local.wordpress.test; I would receive (This site can’t be reached local.wordpress.test’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN)

I issued `vagrant halt` and created a brand new site in my config.yml - named [test-case](https://gist.github.com/skorasaurus/230d4d9457e9b6d1718d3c8cb673f174#file-config-yml-L26) - and set the host to be `case.wordpress.test` also using the https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git 

After issuing `vagrant up --provision` again; I noticed a couple lines in the terminal output - 
```
entry => default: [vagrant-goodhosts] - found entry for: 192.168.50.4 wordpress-default.test
entry => default: [vagrant-goodhosts] - found entry for: 192.168.50.4 test-case.test
```
Both sites, `local.wordpress.test` and `case.wordpress.test` were not accessible in the browser, returning the DNS_PROBE_FINISHED_NXDOMAIN mentioned above. 

When I visited wordpress-default.test, I was redirected a page very similar to the vvv dashboard (I didn't save the exact error message) with a notice on top stating the site did not finish provisioning? 

Knowing that I was on the develop branch (most recent commit - https://github.com/Varying-Vagrant-Vagrants/VVV/commit/10f8b2dd3f856dddbc870b9cb6f75e288b37c7b6) and seeing there were several host related commits within the past week (from #2267 , I issued `git checkout f9e04da83083a815f14f0cf3991e37c994fcb105` which was shortly before #2267 and ran `vagrant up --provision` again; 

I now noticed that the output from vagrant in the terminal now had:
```
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 local.wordpress.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 case.wordpress.test
```
which is the corrects hosts for those websites and I'm now able to access both local.wordpress.test and case.wordpress.test in the browser. 

## Steps to Reproduce (for bugs)

1. add an entry to your config.yml where the site name differs from the hosts. - [example](https://gist.github.com/skorasaurus/230d4d9457e9b6d1718d3c8cb673f174#file-config-yml-L26)
2. reprovision
3.
4.

## Expected Behavior
the site is 

## Your Environment

Platform: platform-linux-gnu shell:/bin/bash systemd  vagrant-hostsupdater vagrant-goodhosts vagrant-vbguest CaseSensitiveFS shared_db_folder_disabled, VVV Path: "/home/myusername/vvv"
Vagrant: v2.2.10, VirtualBox: v6.1.14r140239

(I had issued `vagrant plugin uninstall vagrant-hostupdater` and it said `The plugin 'hostsupdater' is not currently installed.`

**Comment by Mte90** [comment]
We landed a bugfix for this issue, can you try it after a git pull?

**Comment by skorasaurus** [comment]
Thank you for the prompt fix! Yes, this fixes it :)
