### ISSUE TITLE
Fresh install of Tideways results in broken XHGUI

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2290]
Adding the tideways utility and installing for the first time, then visiting `xhgui.vvv.test` results in this PHP fatal error:

```
Fatal error: Uncaught Error: Class 'XHGui\Config' not found in /srv/www/default/xhgui/src/bootstrap.php:16 Stack trace: #0 /srv/www/default/xhgui/webroot/index.php(5): require() #1 {main} thrown in /srv/www/default/xhgui/src/bootstrap.php on line 16
```

**Comment by Mte90** [comment]
Seems that composer wasn't executed...

**Comment by tomjn** [comment]
Running `composer install` manually fixed it, noting that there was already a lock file so looking for the lock file won't work

**Comment by Mte90** [comment]
Maybe this happened because of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2288 ?

**Comment by tomjn** [comment]
Possibly, but at least we have a record of why it failed now. Ideally in the situation in #2288 it would exit the utility with a failure code rather than saying it succeeded
