### ISSUE TITLE
Getting "Payment Required" error when trying to run `vagrant up --provision`

### ISSUE THREAD

**Issue by anekola** [Varying-Vagrant-Vagrants/VVV#2295]
## Expected Behavior

I'm just trying to to an update of VVV running `vagrant up --provision` and I'm getting this error:

## Current Behavior

`default: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/pool/bionic/main/g/git-lfs/git-lfs_2.12.0_amd64.deb  402  Payment Required [IP: 54.193.34.251 443]`

default:  ! Main packages check and install failed, halting provision
default:  ! The 'main' provisioner ran into problems, check the full log for more details! It completed in 3784 seconds.

## Possible Solution

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/9229f195e5c69a77d905b33a2344b655e0ea4445/provision/core/git/sources.list#L2

I'm not 100% familiar with this, but could it be that whomever hosts this file on packagecloud.io is past due paying their account? 🤷‍♂️ Regardless, I cannot complete the provision due to this error.

## Your Environment

\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.4.1-git::master

Platform: platform-darwin19.2.0 shell:/bin/bash vagrant-hostsupdater shared_db_folder_disabled, VVV Path: "/Users/anekola/vagrant-local"
Vagrant: v2.2.10, VirtualBox: v6.1.16r140961

**Comment by tomjn** [comment]
Is it working now? I tried those URLs and they worked. Otherwise your hunch is right, I'm guessing the Git LFS maintainers paid their bill late

**Comment by anekola** [comment]
Hah - it works now! I don't update often.. what are the odds?
