### ISSUE TITLE
502 Bad Gateway on clean install

### ISSUE THREAD

**Issue by GuiSCI** [Varying-Vagrant-Vagrants/VVV#2308]
Hi guys,

I did a clean install from the default branch (develop). It looked like everything went smooth, (no single error) but vvv.test and both default domains give me a 502 bad gateway. Also after installing the CA certificate, same happened on https://

System:  ubuntu 20.04 on i7
Vagrant: v2.2.9, VirtualBox: v6.1.10r138449

I installed the new vagrant-goodhosts plugin and deinstalled the old vagrant-hostsupdater. Also went on ssh and tried manually restarting nginx. Neither did help.

Any ideas?

**Comment by Mte90** [comment]
A 502 is something on VVV side so doesn't involve the hosts file.
Maybe something in the `vagrant up` didn't worked well, can you try it with a `vagrant provision`?

**Comment by GuiSCI** [comment]
Already tried that. (started from scratch twice)

**Comment by GuiSCI** [comment]
First run I did with a modified config.yml and thought I messed something up. Then I did a complete new install with everything default. Same result. I have 2 other VMs with VVV installed on this system, without any trouble.

**Comment by Mte90** [comment]
Can you share the logs?

**Comment by GuiSCI** [comment]
A specific one, or all? Here are the nginx logs to start with...
[access.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604563/access.log)
[error.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604564/error.log)

**Comment by GuiSCI** [comment]
These are the log of the first vagrant-up (provisioning)
[provisioner-dashboard.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604569/provisioner-dashboard.log)
[provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604570/provisioner-main.log)
[provisioner-site-wordpress-one.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604571/provisioner-site-wordpress-one.log)
[provisioner-site-wordpress-two.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604572/provisioner-site-wordpress-two.log)
[provisioner-utility-core-phpmyadmin.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604573/provisioner-utility-core-phpmyadmin.log)
[provisioner-utility-core-tls-ca.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604574/provisioner-utility-core-tls-ca.log)
[provisioner-utility-source-core.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5604575/provisioner-utility-source-core.log)

**Comment by tomjn** [comment]
The terminal output and a copy of the config file you used

**Comment by GuiSCI** [comment]
Could not attach the config.yml (filetype not supported) but it is the same as in the git repo (as is the Vagrantfile, it that is the one you meant)


gui@gui-XPS-8700:~/vvv04$ vagrant provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.5.0-git::develop

Platform: platform-linux-gnu shell:/bin/bash systemd  vagrant-goodhosts CaseSensitiveFS shared_db_folder_disabled, VVV Path: "/home/gui/vvv04"
Vagrant: v2.2.9, VirtualBox: v6.1.10r138449

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

==> default: Running action triggers before provision ...
==> default: Running trigger: VVV Pre-Provision...
==> default: 
==> default: ༼ つ ◕_◕ ༽つ A full provision can take a little while!
==> default:              Go make a cup of tea and sit back.
==> default:              If you only wanted to turn VVV on, use vagrant up
==> default: 
==> default: [vagrant-goodhosts] Checking for host entries
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 one.wordpress.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 two.wordpress.test
[sudo] password for gui: 
==> default: Running provisioner: file...
    default: /home/gui/vvv04/version => /home/vagrant/version
==> default: Running provisioner: default (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-1kk7tq9.sh
    default:  ▷ Running the 'main' provisioner...
    default:  * Bash profile setup and directories.
    default:  * Setting ownership of files in /home/vagrant to vagrant
    default:  * Copying /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default:  * Copying /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default:  * Copying /srv/config/bash_aliases                      to /root/.bash_aliases
    default:  * Copying /srv/config/vimrc                             to /home/vagrant/.vimrc
    default:  * Copying /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default:  * Copying /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default:  * Copying /srv/config/ssh_known_hosts                   to /etc/ssh/ssh_known_hosts
    default:  * Copying /srv/config/sshd_config                       to /etc/ssh/sshd_config
    default:  * Reloading SSH Daemon
    default:  * Testing network connection to https://ppa.launchpad.net
    default:  * Successful Network connection to https://ppa.launchpad.net detected
    default:  * Testing network connection to https://wordpress.org
    default:  * Successful Network connection to https://wordpress.org detected
    default:  * Testing network connection to https://github.com
    default:  * Successful Network connection to https://github.com detected
    default:  * Testing network connection to https://raw.githubusercontent.com
    default:  * Successful Network connection to https://raw.githubusercontent.com detected
    default:  * Testing network connection to https://getcomposer.org
    default:  * Successful Network connection to https://getcomposer.org detected
    default:  * Testing network connection to http://ams2.mirrors.digitalocean.com
    default:  * Successful Network connection to http://ams2.mirrors.digitalocean.com detected
    default:  * Network checks succeeded
    default:  * git-core/ppa already present, skipping
    default: 
    default:  * Setting up MySQL configuration file links...
    default:  * mysql group exists
    default:  * mysql user present and has uid 9001
    default:  * Copying /srv/config/mysql-config/vvv-core.cnf to /etc/mysql/conf.d/vvv-core.cnf
    default:  
    default:  * Main packages check and install.
    default:  * Cleaning up dpkg lock file
    default:  * Updating apt keys
    default: gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
    default: gpg: key 3B4FE6ACC0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" not changed
    default: gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
    default: gpg: key D94AA3F0EFE21092: "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" not changed
    default: gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
    default: gpg: key 871920D1991BC93C: "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>" not changed
    default: gpg: Total number processed: 3
    default: gpg:              unchanged: 3
    default:  * Running apt-get update...
    default: Get:1 http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:2 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:3 https://deb.nodesource.com/node_10.x bionic InRelease [4584 B]
    default: Get:4 http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main Sources [1736 B]
    default: Get:5 https://nginx.org/packages/mainline/ubuntu bionic InRelease [2862 B]
    default: Get:6 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:7 http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main ppc64el Packages [15.7 kB]
    default: Get:8 http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main amd64 Packages [16.2 kB]
    default: Get:9 http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main arm64 Packages [15.8 kB]
    default: Get:10 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main Sources [1736 B]
    default: Get:11 https://deb.nodesource.com/node_10.x bionic/main amd64 Packages [769 B]
    default: Get:12 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main ppc64el Packages [15.7 kB]
    default: Get:13 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main amd64 Packages [16.2 kB]
    default: Get:14 http://mirrors.piconets.webwerks.in/mariadb-mirror/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:15 https://nginx.org/packages/mainline/ubuntu bionic/nginx Sources [59.0 kB]
    default: Get:16 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main arm64 Packages [15.8 kB]
    default: Get:17 https://nginx.org/packages/mainline/ubuntu bionic/nginx amd64 Packages [59.9 kB]
    default: Get:18 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease [20.8 kB]
    default: Get:19 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
    default: Get:20 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease [20.8 kB]
    default: Get:21 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main Sources [1736 B]
    default: Get:22 http://ppa.launchpad.net/varying-vagrant-vagrants/php/ubuntu bionic InRelease [15.9 kB]
    default: Get:23 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
    default: Get:24 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    default: Get:25 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main amd64 Packages [16.2 kB]
    default: Get:26 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
    default: Get:27 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main arm64 Packages [15.8 kB]
    default: Get:28 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic/main amd64 Packages [3048 B]
    default: Get:29 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic/main Translation-en [2252 B]
    default: Get:30 http://mirrors.piconets.webwerks.in/mariadb-mirror/repo/10.4/ubuntu bionic/main Sources [1740 B]
    default: Get:31 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic/main ppc64el Packages [15.7 kB]
    default: Get:32 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main Sources [29.4 kB]
    default: Get:34 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages [80.3 kB]
    default: Get:35 http://mirrors.piconets.webwerks.in/mariadb-mirror/repo/10.4/ubuntu bionic/main amd64 Packages [16.2 kB]
    default: Get:36 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main Translation-en [31.3 kB]
    default: Get:37 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1019 kB]
    default: Get:38 http://ppa.launchpad.net/varying-vagrant-vagrants/php/ubuntu bionic/main Sources [15.1 kB]
    default: Get:39 http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:40 http://ppa.launchpad.net/varying-vagrant-vagrants/php/ubuntu bionic/main amd64 Packages [41.0 kB]
    default: Get:41 http://archive.ubuntu.com/ubuntu bionic/main Translation-en [516 kB]
    default: Get:42 http://ppa.launchpad.net/varying-vagrant-vagrants/php/ubuntu bionic/main Translation-en [11.5 kB]
    default: Get:43 http://mirrors.piconets.webwerks.in/mariadb-mirror/repo/10.4/ubuntu bionic/main ppc64el Packages [15.8 kB]
    default: Get:44 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [9184 B]
    default: Get:45 http://archive.ubuntu.com/ubuntu bionic/restricted Translation-en [3584 B]
    default: Get:46 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [8570 kB]
    default: Get:47 http://mirrors.piconets.webwerks.in/mariadb-mirror/repo/10.4/ubuntu bionic/main arm64 Packages [15.8 kB]
    default: Get:48 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1425 kB]
    default: Get:33 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease [23.2 kB]
    default: Get:49 http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/ubuntu bionic InRelease [6265 B]
    default: Get:50 http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.4/ubuntu bionic/main Sources [1736 B]
    default: Get:51 http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/ubuntu bionic/main Sources [1736 B]
    default: Get:52 http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/ubuntu bionic/main amd64 Packages [16.2 kB]
    default: Get:53 http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.4/ubuntu bionic/main ppc64el Packages [15.7 kB]
    default: Get:54 http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/ubuntu bionic/main arm64 Packages [15.8 kB]
    default: Get:55 http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/ubuntu bionic/main ppc64el Packages [15.7 kB]
    default: Get:56 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [280 kB]
    default: Get:57 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [173 kB]
    default: Get:58 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [22.7 kB]
    default: Get:59 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1089 kB]
    default: Get:61 http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.4/ubuntu bionic/main amd64 Packages [16.2 kB]
    default: Get:62 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [243 kB]
    default: Get:63 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [13.3 kB]
    default: Get:64 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2996 B]
    default: Get:65 http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.4/ubuntu bionic/main arm64 Packages [15.8 kB]
    default: Get:60 https://packagecloud.io/github/git-lfs/ubuntu bionic/main amd64 Packages [3784 B]
    default: Get:66 http://archive.ubuntu.com/ubuntu bionic/universe Translation-en [4941 kB]
    default: Get:67 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [151 kB]
    default: Get:68 http://archive.ubuntu.com/ubuntu bionic/multiverse Translation-en [108 kB]
    default: Get:69 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1761 kB]
    default: Get:70 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [373 kB]
    default: Get:71 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [196 kB]
    default: Get:72 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [26.3 kB]
    default: Get:73 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1693 kB]
    default: Get:74 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [356 kB]
    default: Get:75 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [36.1 kB]
    default: Get:76 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [7308 B]
    default: Get:77 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [10.0 kB]
    default: Get:78 http://archive.ubuntu.com/ubuntu bionic-backports/main Translation-en [4764 B]
    default: Get:79 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [10.3 kB]
    default: Get:80 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [4588 B]
    default: Fetched 24.3 MB in 6s (4186 kB/s)
    default: Reading package lists...
    default:  * Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: make is already the newest version (4.1-9.1ubuntu1).
    default: python-setuptools is already the newest version (39.0.1-2).
    default: unzip is already the newest version (6.0-21ubuntu1).
    default: zip is already the newest version (3.0-11build1).
    default: colordiff is already the newest version (1.0.18-1).
    default: dos2unix is already the newest version (7.3.4-3).
    default: ngrep is already the newest version (1.47+ds1-1).
    default: subversion is already the newest version (1.9.7-4ubuntu1).
    default: curl is already the newest version (7.58.0-2ubuntu3.10).
    default: g++ is already the newest version (4:7.4.0-1ubuntu2.3).
    default: gettext is already the newest version (0.19.8.1-6ubuntu0.3).
    default: imagemagick is already the newest version (8:6.9.7.4+dfsg-16ubuntu6.8).
    default: lftp is already the newest version (4.8.1-1ubuntu0.2).
    default: memcached is already the newest version (1.5.6-0ubuntu1.2).
    default: postfix is already the newest version (3.3.0-1ubuntu0.3).
    default: software-properties-common is already the newest version (0.96.24.32.14).
    default: vim is already the newest version (2:8.0.1453-1ubuntu1.4).
    default: ntp is already the newest version (1:4.2.8p10+dfsg-5ubuntu7.3).
    default: ntpdate is already the newest version (1:4.2.8p10+dfsg-5ubuntu7.3).
    default: python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.4).
    default: git is already the newest version (1:2.29.2-0ppa1~ubuntu18.04.1).
    default: git-svn is already the newest version (1:2.29.2-0ppa1~ubuntu18.04.1).
    default: git-lfs is already the newest version (2.12.1).
    default: mariadb-server is already the newest version (1:10.4.17+maria~bionic).
    default: nginx is already the newest version (1.19.5-1~bionic).
    default: nodejs is already the newest version (10.23.0-1nodesource1).
    default: php-pcov is already the newest version (1.0.6-3+ubuntu18.04.1+deb.sury.org+1).
    default: php-pear is already the newest version (1:1.10.12+submodules+notgz-1+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-bcmath is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-cli is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-common is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-curl is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-dev is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-fpm is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-gd is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-imagick is already the newest version (3.4.4-10+ubuntu18.04.1+deb.sury.org+4).
    default: php7.3-imap is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-intl is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-json is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-mbstring is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-memcache is already the newest version (4.0.5.2+3.0.9~20170802.e702b5f9-2+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-memcached is already the newest version (3.1.5+2.2.0-4+ubuntu18.04.1+deb.sury.org+4).
    default: php7.3-mysql is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-soap is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-ssh2 is already the newest version (1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-xdebug is already the newest version (2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-xml is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-yaml is already the newest version (2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1).
    default: php7.3-zip is already the newest version (7.3.24-3+ubuntu18.04.1+deb.sury.org+1).
    default: 0 upgraded, 0 newly installed, 0 to remove and 120 not upgraded.
    default:  * Removing unnecessary apt packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: 
    default: Reading state information...
    default: 0 upgraded, 0 newly installed, 0 to remove and 120 not upgraded.
    default:  * Cleaning apt caches...
    default:  * Running tools_install
    default:  * Installing Shyaml for bash provisioning..
    default: Requirement already satisfied: wheel in /usr/local/lib/python2.7/dist-packages
    default: Requirement already satisfied: shyaml in /usr/local/lib/python2.7/dist-packages
    default: Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from shyaml)
    default:  * Turning off XDebug to avoid Composer performance issues
    default:  * Disabling active debug PHP mods
    default:  * Disabling if present: 'xdebug, xhgui, tideways_xhprof, pcov'
    default:  * Restarting PHP FPM's so the change takes effect
    default: Job for php7.3-fpm.service failed because the control process exited with error code.
    default: See "systemctl status php7.3-fpm.service" and "journalctl -xe" for details.
    default:  * Making sure the composer cache is not owned by root
    default:  * Checking Composer is installed
    default:  * Updating Composer...
    default: Changed current directory to /usr/local/src/composer
    default: A new stable major version of Composer is available (2.0.7), run "composer self-update --2" to update to it. See also https://getcomposer.org/2
    default: You are already using composer version 1.10.17 (1.x channel).
    default:  * Making sure the PHPUnit 7.5 package is available...
    default: Changed current directory to /usr/local/src/composer
    default: ./composer.json has been updated
    default:  * Updating global composer packages...
    default: Changed current directory to /usr/local/src/composer
    default: Loading composer repositories with package information
    default: Updating dependencies (including require-dev)
    default: Nothing to install or update
    default: Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
    default: Generating autoload files
    default: 4 packages you are using are looking for funding.
    default: Use the `composer fund` command to find out more!
    default:  * Global composer package update completed
    default: 
    default:  * Install/Update PHP_CodeSniffer (phpcs), see https://github.com/squizlabs/PHP_CodeSniffer
    default: 
    default:  * Install/Update WordPress-Coding-Standards, sniffs for PHP_CodeSniffer, see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    default: Loading composer repositories with package information
                                                      
    default: Updating dependencies (including require-dev)
    default: Nothing to install or update
    default: 1 package you are using is looking for funding.
    default: Use the `composer fund` command to find out more!
    default: Using config file: /srv/www/phpcs/CodeSniffer.conf
    default: 
    default: Config value "installed_paths" updated successfully; old value was "./CodeSniffer/Standards/WordPress/,./CodeSniffer/Standards/VIP-Coding-Standards/,./CodeSniffer/Standards/PHPCompatibility/,./CodeSniffer/Standards/PHPCompatibilityParagonie/,./CodeSniffer/Standards/PHPCompatibilityWP/"
    default: Using config file: /srv/www/phpcs/CodeSniffer.conf
    default: 
    default: Config value "default_standard" updated successfully; old value was "WordPress-Core"
    default: The installed coding standards are PSR1, MySource, PEAR, PSR12, PSR2, Zend, Squiz, WordPress-Docs, WordPress-Core, WordPress, WordPress-Extra, WordPressVIPMinimum, WordPress-VIP-Go, PHPCompatibility, PHPCompatibilityParagonieRandomCompat, PHPCompatibilityParagonieSodiumCompat and PHPCompatibilityWP
    default:  * Installing/updating npm...
    default: /usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
    default: /usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
    default: + npm@6.14.9
    default: updated 1 package in 4.882s
    default:  * Installing/updating npm-check-updates...
    default: /usr/bin/npm-check-updates -> /usr/lib/node_modules/npm-check-updates/bin/cli.js
    default: /usr/bin/ncu -> /usr/lib/node_modules/npm-check-updates/bin/cli.js
    default: + npm-check-updates@10.2.2
    default: updated 1 package in 5.953s
    default:  * Updating Grunt CLI
    default:  * Updated Grunt CLI
    default:  * Enabling MailHog Service
    default:  * Starting MailHog Service
    default:  
    default:  * Installing/updating WP-CLI
    default:  * Updating wp-cli...
    default: Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
    default: md5 hash verified: 47292fdd2af91d1b553580c42494ce35
    default: New version works. Proceeding to replace.
    default: Success: Updated WP-CLI to the latest nightly release.
    default: Installing package wp-cli/doctor-command (dev-master)
    default: Updating /root/.wp-cli/packages/composer.json to require the package...
    default: Registering git@github.com:wp-cli/doctor-command.git as a VCS repository...
    default: Using Composer to install the package...
    default: ---
    default: Loading composer repositories with package information
    default: Updating dependencies
    default: Generating rules
    default: Resolving dependencies through SAT
    default: Looking at all rules.
    default: Something's changed, looking at all rules again (pass #1)
    default: Dependency resolution completed in 0.002 seconds
    default: Analyzed 184 packages to resolve dependencies
    default: Analyzed 227 rules to resolve dependencies
    default: Lock file operations: 0 installs, 0 updates, 0 removals
    default: Installing dependencies from lock file
    default: Nothing to install, update or remove
    default: Generating autoload files
    default: 1 package you are using is looking for funding.
    default: Use the `composer fund` command to find out more!
    default: ---
    default: Success: Package installed.
    default: 
    default:  * Setting up database configuration file links...
    default:  * Copied /srv/config/mysql-config/my.cnf               to /etc/mysql/my.cnf
    default:  * Copied /srv/config/mysql-config/root-my.cnf          to /home/vagrant/.my.cnf
    default:  * Checking the root user password is root
    default:  * The root password is the expected value
    default:  * Restarting mysql service
    default: 
    default:  * No custom MySQL scripting found in database/init-custom.sql, skipping...
    default:  * Initial MySQL prep...
    default:  * Starting MariaDB Database Import
    default:  * No custom databases to import
    default:  * Setup configuration files...
    default:  * Copying /srv/config/nginx-config/nginx.conf           to /etc/nginx/nginx.conf
    default:  * Copying /srv/config/nginx-config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf
    default:  * Copying /srv/config/php-config/upstream.conf to /etc/nginx/upstreams/php73.conf
    default:  * Rsync'ing /srv/config/nginx-config/sites/             to /etc/nginx/custom-sites
    default: sending incremental file list
    default: deleting vvv-auto-wordpress-two-provision-b0bc8489c53c6b96847837cbb5a3ac4a.conf
    default: deleting vvv-auto-wordpress-one-provision-60730e707ede8a21f013860b6fc556e1.conf
    default: default.conf
    default: local-nginx-example.conf-sample
    default: 
    default: sent 1.92K bytes  received 202 bytes  4.24K bytes/sec
    default: total size is 4.08K  speedup is 1.93
    default:  * Making sure the Nginx log files and folder exist
    default:  * Copying /srv/config/php-config/php-fpm.conf   to /etc/php/7.3/fpm/php-fpm.conf
    default:  * Copying /srv/config/php-config/php-www.conf   to /etc/php/7.3/fpm/pool.d/www.conf
    default:  * Copying /srv/config/php-config/php-custom.ini to /etc/php/7.3/fpm/conf.d/php-custom.ini
    default:  * Copying /srv/config/php-config/opcache.ini       to /etc/php/7.3/fpm/conf.d/opcache.ini
    default:  * Copying /srv/config/php-config/xdebug.ini        to /etc/php/7.3/mods-available/xdebug.ini
    default:  * Copying /srv/config/php-config/mailhog.ini       to /etc/php/7.3/mods-available/mailhog.ini
    default:  * Copying /srv/config/memcached-config/memcached.conf to /etc/memcached.conf and /etc/memcached_default.conf
    default:  * Finalizing
    default:  
    default:  * Cleaning up Nginx configs
    default:  * Disabling XDebug PHP extension
    default:  * Enabling MailHog for PHP
    default:  
    default:  * Cleaning the virtual machine's /etc/hosts file...
    default: 
    default:  * Restarting services...
    default: Job for php7.3-fpm.service failed because the control process exited with error code.
    default: See "systemctl status php7.3-fpm.service" and "journalctl -xe" for details.
    default:  ✔ The 'main' provisioner completed in 53 seconds.
==> default: Running provisioner: dashboard (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-7q9oqv.sh
    default:  ▷ Running the 'dashboard' provisioner...
    default:  ✔ The 'dashboard' provisioner completed in 1 seconds.
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-8ha3sc.sh
    default:  ▷ Running the 'utility-source-core' provisioner...
    default:  ✔ The 'utility-source-core' provisioner completed in 1 seconds.
==> default: Running provisioner: utility-core-tls-ca (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-1dhag0s.sh
    default:  ▷ Running the 'utility-core-tls-ca' provisioner...
    default:  ✔ The 'utility-core-tls-ca' provisioner completed in 2 seconds.
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-19ykmy8.sh
    default:  ▷ Running the 'utility-core-phpmyadmin' provisioner...
    default:  ✔ The 'utility-core-phpmyadmin' provisioner completed in 0 seconds.
==> default: Running provisioner: site-wordpress-one (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-sd27pg.sh
    default:  ▷ Running the 'site-wordpress-one' provisioner...
    default:  ✔ The 'site-wordpress-one' provisioner completed in 4 seconds.
==> default: Running provisioner: site-wordpress-two (shell)...
    default: Running: /tmp/vagrant-shell20201126-258576-1c2v39q.sh
    default:  ▷ Running the 'site-wordpress-two' provisioner...
    default: Warning: query-monitor: Plugin already installed.
    default: Warning: Plugin 'query-monitor' is already active.
    default:  ✔ The 'site-wordpress-two' provisioner completed in 7 seconds.
==> default: Running action triggers after provision ...
==> default: Running trigger: VVV provisioning has reached the end...
    default: Running: inline script
    default: Post Vagrant provision script
    default: Restarting Nginx and MySQL
    default: 
    default:          yay  
    default:    ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄                __ __ __ __
    default:    █▒▒░░░░░░░░░▒▒█    Thanks for  \ V\ V\ V /
    default:     █░░█░░░░░█░░█     using        \_/\_/\_/
    default:  ▄▄  █░░░▀█▀░░░█  ▄▄ 
    default: █░░█ ▀▄░░░░░░░▄▀ █░░█ Provisioning has finished! Visit http://vvv.test

**Comment by GuiSCI** [comment]
Whats more is that my older VVV install (that was still working earlier today) now gives the same problem :-(
(had to re-install vagrant-hostsupdater) 
I am absolutely clueless what is going on.

**Comment by tomjn** [comment]
@GuiSCI I'd recommend against having multiple VVV installs unless you plan to work on VVV itself

> (had to re-install vagrant-hostsupdater)

On the `develop` branch you should not use hostsupdater, i've seen no evidence that the hosts file is in any way related to your issues. If it was, you would not be getting a bad gateway, you would be getting a Chrome or Firefox DNS message about not being able to locate the domain.

Use goodhosts, uninstall hostsupdater, and stop messing about with the hosts file updating. It is not the cause of your issues, and you're making things worse by changing things.

**Comment by tomjn** [comment]
>     default:  * Restarting services...
>    default: Job for php7.3-fpm.service failed because the control process exited with error code.
>    default: See "systemctl status php7.3-fpm.service" and "journalctl -xe" for details.

This is the problem

**Comment by tomjn** [comment]
@GuiSCI the problem was the recent change to make PHP 7.3 the default, a `git pull` and a reprovision should resolve the problem. If you can do that and confirm here that all is working?

**Comment by GuiSCI** [comment]
Yes! that worked!
Thank you very much :-))
