### ISSUE TITLE
Internal utility to set the PHP version of VVV

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2309]
The idea behind this is to avoid issues when we change the internal default php version.
AS we need to change various files and version in a lot of files, something that does this for us automatically can save a lot of time.

**Comment by tomjn** [comment]
It will need to:

 - read in from the config file what the preferred default PHP should be
 - check that it's available
    - This means it will need to run after the utilities have run else we could declare we want 7.0 to be the default and it would not find it because it hasn't been installed yet
 - The dashboard/XHGUI/PHPinfo/etc currently use `php` upstream, but these should be changed instead to an internal upstream that uses our preferred default so that changing the default doesn't break these


The last item can be spun off into a new ticket

**Comment by Mte90** [comment]
Reading now the ticket seems that we need as always that in VVV define a PHP default version in case the one in the config is not available.

**Comment by Mte90** [comment]
So as today we have https://github.com/Varying-Vagrant-Vagrants/VVV/blob/4a22238a555b939076bb41b5f73a699b94afb8a2/provision/core/php/provision.sh#L5 this variable that is set as `7.4` we can think to a new config:
```
general:
  default_php_version: 8.0
```

So the code as wrote https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2309#issuecomment-734812688 require some check. 

Instead how this change can affect utilities (apart the php version running as default for the webserver for them):

* https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/webgrind/provision.sh#L22 - use composer
* https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/opcache-gui/provision.sh#L7 - user composer
* https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/tideways/provision.sh#L106 - we use php 7.4 that is enforced so we can ignore it, also if it is composer used later
* https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/wpcli-dev/provision.sh#L38 - use composer
* https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/mongodb/provision.sh#L15 - we use pecl but there is a loop that install it to any php version

So a solution is to enforce the VVV's php default version as minimum for web server and also for cli.
This can open to:

```
general:
  default_php_version_cli: 8.0
  default_php_version_nginx: 7.4
```

In this way we can have both the solution or another solution that add a lot of entropy is to define a php version for provisioner used for cli/nginx.

**Comment by tomjn** [comment]
I'm heavily opposed to setting a default version, there are other solutions to that problem that are superior. I've explained elsewhere that this will cause lots of problems, while never actually solving the problems that people are using this to solve.

This is an X Y problem, this is not the solution to the problem, this is the solution to implementing a proposed solution that does not actually solve the real problem.

The real solution is to allow a site to specify the PHP version, not the nginx upstream, then set that version in the provisioner:


```yaml
sites:
  wordpress-one:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    php: 8.0
    hosts:
      - one.wordpress.test
```

This avoids a lot of problems that what you're proposing would introduce

IMO this should be closed in favor of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2367
