### ISSUE TITLE
Make life harder for sudo diehards

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2311]
Users are still using `sudo`, they should not be using `sudo`. So we should make this clearer, with bigger warnings, more warnings, and hints that it will get harder ( and more annoying ) in the future

 - make the warning bigger
 - show the warning at the end of provisioning too
 - warn users they will have to take extraordinary measures in the future

Future mitigations may include:

 - requiring config options be set to enable `sudo`
 - automatically removing that config option so it has to be added every, single, time
 - disabling the dashboard with a red page that has a big warning
 - only running the main provisioner and skipping all site provisioning ( VVV under `sudo` is only for data recovery purposes )
 - a very unhappy teddy bear

**Comment by tomjn** [comment]
Things should be a lot louder for people who try to use `sudo vagrant up`:

<img width="468" alt="Screenshot 2020-12-04 at 18 36 57" src="https://user-images.githubusercontent.com/58855/101202636-6fc76c00-3661-11eb-9ef2-4fa65375e790.png">
<img width="1440" alt="Screenshot 2020-12-04 at 18 43 49" src="https://user-images.githubusercontent.com/58855/101202642-70f89900-3661-11eb-86eb-c70d77b90f3f.png">
<img width="737" alt="Screenshot 2020-12-04 at 17 05 28" src="https://user-images.githubusercontent.com/58855/101202661-76ee7a00-3661-11eb-84f9-043cfba04a25.png">
<img width="514" alt="Screenshot 2020-12-04 at 18 50 10" src="https://user-images.githubusercontent.com/58855/101202727-91285800-3661-11eb-9e69-792bdb1b99ae.png">

**Comment by Mte90** [comment]
As today what is missing for this?

**Comment by tomjn** [comment]
Closing this for now
