### ISSUE TITLE
Possible Typo on "Minimum System Requirements"

### ISSUE THREAD

**Issue by jigth** [Varying-Vagrant-Vagrants/VVV#2314]
Hello. I came here from wordpress.org, reading that this is a viable option for setting up a cross platform, easily reproducible virtual environment.

Reading the readme.md I think I found an error in what you say in the **Minimum System requirements** section, currently it's as follows:

**Minimum System requirements**
* Vagrant 2.2.7 or **below**.
* Virtualbox 6.1.x or **below**.

Shouldn't it be "or **above**" in both cases? Or for example, ***VVV*** wouldn't work with Vagrant version 2.2.8 in this moment of time?

**Comment by tomjn** [comment]
I agree! I've removed those details in favor of a link to the official doc site which has a much better explainer in https://github.com/Varying-Vagrant-Vagrants/VVV/commit/b1a823629403a18cfe03acd8a19bff89843495bb
