### ISSUE TITLE
Provisioning the latest version of VVV (3.4.1) installs latest version of Xdebug (3.0.1) - Doesn't Work

### ISSUE THREAD

**Issue by cooms13** [Varying-Vagrant-Vagrants/VVV#2315]
## What was The Command Used To Provision
```shell
vagrant up
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke
VVV 3.4.1, Vagrant 2.2.7, VirtualBox 6.1.16

We provisioned and everything worked properly except debugging. As we dug into it and viewed phpinfo(), we saw that in the Xdebug section, there were a whole bunch of Xdebug settings/options that showed as not configured properly due to the latest version of Xdebug having breaking changes to it. Our hunch is that the latest version of VVV doesn't work currently with the latest version of Xdebug. (Of course, we could be wrong) 

## Possible Solution
We forced a downgrade of Xdebug to the version that we had prior to 2.7 and debugging works again.

## Steps to Reproduce (for bugs)
1. Start from scratch with provisioning VVV with the versions of VVV, Vagrant, and VirtualBox above.
2. Create a PHP file which outputs phpinfo() and view it
3. Look at the XDEBUG section and notice a whole bunch of the properties have an error message speaking about the upgrade path for Xdebug 3.

## Your Environment
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/2623946/101947372-5d4bb600-3bbe-11eb-9012-c403ba959da5.png">

**Comment by tomjn** [comment]
Update to the latest `stable` branch for 3.5.1 which has XDebug 3 changes!

I was able to get it working with VSCode using this `launch.json` and the PHP Debug extension:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for XDebug",
			"type": "php",
			"request": "launch",
			"port": 9000,
			"pathMappings": {
				"/srv/www": "/Users/tarendai/dev/vvv/www"
			}
		}
	]
}
```

Adjust your `pathMappings` accordingly

**Comment by Mte90** [comment]
any updates from @cooms13?

**Comment by tomjn** [comment]
`develop` branch/v3.6.0 has some further improvements, 3.4.1 is no longer the current version

**Comment by Mte90** [comment]
Closing as no replies since a month.
