### ISSUE TITLE
Add bash docs to code

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2319]
Add bash comments to the files so we can generate the code docs: https://github.com/reconquest/shdoc

**Comment by Mte90** [comment]
Can we consider this close @tomjn?

**Comment by tomjn** [comment]
I don't believe we've documented all provisioners yet

**Comment by tomjn** [comment]
Closing this, we can create issues for specific files rather than a catch all ticket
