### ISSUE TITLE
Not reliable is installed check for themes and plugins

### ISSUE THREAD

**Issue by mnap00** [Varying-Vagrant-Vagrants/VVV#2323]
The check introduced in https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/44 is not reliable for plugins and themes declared as an url of a zip archive.

## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was an attempt to upgrade to a new version of VVV - from 3.4.1 to 3.5.1

## Logs/What Broke

`wp theme install` or `wp plugin install` allows url of a zip archive as an argument. `wp theme is-installed` or `wp plugin is-installed` allows only theme or plugin slug.
E.g. declaring:
```yaml
    install_themes: # Various way to install a theme
         - https://github.com/understrap/understrap/archive/master.zip
```
runs OK if there is no such theme installed and installation runs with `wp theme install https://github.com/understrap/understrap/archive/master.zip`. But if theme is installed it fails with:
```
    default: Warning: The 'https://github.com/understrap/understrap/archive/master.zip' theme could not be found.                                                                           
    default: Error: No themes installed.
```
because `wp theme is-installed` with an url as an argument returns `1`.

For 3.4.1 provisioner is running even if the error occurs. For 3.5.1 version provisioner breaks at this error and does not finish site's setup. 

## Possible Solution

Remove `wp theme is-installed` and `wp plugin is-installed` check or revert error handling in 3.5.1 for this case.

## Steps to Reproduce (for bugs)

1. Install 3.4.1 or 3.5.1 VVV.
2. Declare url in your config/config.yml file (e.g. for wordpress-one site):
```yaml
    install_themes: # Various way to install a theme
         - https://github.com/understrap/understrap/archive/master.zip
```
3. Run `vagrant up --provision` twice - first to install theme, second to run provisioner with existing theme.

## Your Environment

\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.4.1-git::HEAD

Platform: platform-linux-gnu shell:/bin/bash systemd  CaseSensitiveFS shared_db_folder_disabled, VVV Path: "/srv/vagrant/vvv"
Vagrant: v2.2.9, VirtualBox: v6.1.16_Debianr140961

**Comment by tomjn** [comment]
If we did what you suggested, existing sites may fail to provision because WP CLI would say the theme is already installed triggering the same problem you're having but for the opposite reason.

We could add a check to test if it's a URL, and if it is, don't check `is-installed`, but now we've swapped your problem for a new problem, now WP CLI will download that zip on every single provision, then trigger a failure because the theme is already installed.

Because we don't know what the contents of the zip are until we've downloaded it, I don't see a way to fix `is-installed` so it works with random zip files.

However:

 - Understrap is on wp.org so you don't need to pass a zip URL
 - If your goal is to keep a pristine up to date copy of understrap in your site, it would be much better too tell VVV to clone it into that folder with the `folders` functionality that came with v3.5

**Comment by tomjn** [comment]
For example:

```yaml
  understrap:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - understrap.test
    folders:
      public_html/wp-content/themes/understrap:
        git:
          repo: https://github.com/understrap/understrap.git
```

**Comment by mnap00** [comment]
Well, Understrap was only a test example. I use many plugins and themes from Github.
Indeed `folders` look like what I need. Where is it documented? Sorry to bother, but I cannot find it in the docs on the website.

**Comment by tomjn** [comment]
It’s quite new, added in 3.5, the PR has examples.

Honestly it was never anticipated that this feature would be used the way
you’re using it. I’m inclined to deprecate and remove in favour of better
options as I don’t see a way to make the experience here good with this
method

**Comment by mnap00** [comment]
I see. So, maybe docs should discourage users using a zip archives as a theme source? This part of documentation ('Examples' part of the https://varyingvagrantvagrants.org/docs/en-US/site-templates/custom-site-template-parameters/; BTW, here you are `folders` example!) is wrong anyways. WP CLI does not accept git repository as an argument:
```
    install_themes: # Various way to install a theme
         - understrap
         - https://github.com/understrap/understrap-child.git
```
and fails.
`folders` seem better alternative.

**Comment by tomjn** [comment]
Eliminated in https://github.com/Varying-Vagrant-Vagrants/custom-site-template/commit/7a57d96fbfbdcc9fa49c690c655931b3f529d061

**Comment by tomjn** [comment]
Folders document WIP at https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/blob/main/docs/en-US/adding-a-new-site/folders.md

**Comment by tomjn** [comment]
https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/folders-and-custom-git/

**Comment by mnap00** [comment]
How about adding this simple check in vvv-init.sh?
If a user sets any path or url to a zip file it will break this iteration of the loop. The provisioner will continue without error and the user will get a hint in logs.
This check allows only valid slug characters.

```sh
install_plugins() {                                                                                                                                                                                     
  WP_PLUGINS=$(get_config_value 'install_plugins' '')                            
  if [ ! -z "${WP_PLUGINS}" ]; then                                              
    for plugin in ${WP_PLUGINS//- /$'\n'}; do                                    
      case "${plugin}" in                                                        
        *[!_a-z0-9-]*)                                                           
          echo " * Skipping plugin: '${plugin}'"                                 
          echo "Warning: Only plugin slugs are supported as an input."           
          echo "Failed: Plugin not installed."                                   
          continue                                                               
          ;;                                                                     
        *)                                                                       
          ;;                                                                     
      esac                                                                       
      if [ ! $(noroot wp plugin is-installed "${plugin}") ]; then                
        echo " * Installing and activating plugin: '${plugin}'"                  
        noroot wp plugin install "${plugin}" --activate                          
      else                                                                       
        echo " * The ${plugin} plugin is already installed."                     
      fi                                                                         
    done                                                                         
  fi                                                                             
}                                                                                
                                                                                 
install_themes() {                                                               
  WP_THEMES=$(get_config_value 'install_themes' '')                              
  if [ ! -z "${WP_THEMES}" ]; then                                               
    for theme in ${WP_THEMES//- /$'\n'}; do                                      
      case "${theme}" in                                                         
        *[!_a-z0-9-]*)                                                           
          echo " * Skipping theme: '${theme}'"                                   
          echo "Warning: Only theme slugs are supported as an input."            
          echo "Failed: Theme not installed."                                    
          continue                                                               
          ;;                                                                     
        *)                                                                       
          ;;                                                                     
      esac                                                                       
      if [ ! $(noroot wp theme is-installed "${theme}") ]; then                  
        echo " * Installing theme: '${theme}'"                                   
        noroot wp theme install "${theme}"                                       
      else                                                                       
        echo " * The ${theme} theme is already installed."                       
      fi                                                                         
    done                                                                         
  fi                                                                             
}

**Comment by tomjn** [comment]
The problem there is that there are people already using this functionality that would be left with no alternative.

Perhaps instead a way to apply this test to avoid the `is-installed` check would be better? Really this needs a `config.yml` parameter containing something to check for, and options such as download and overwrite etc

**Comment by mnap00** [comment]
Yes and I am myself such a person who used this functionality. Let me write some random thoughts.

From my perspective the problem is that this setting is already broken (from version 3.5.1) and I agree with second paragraph that it has to be decided how to handle that.

I was also surprised that there was no issues reported considering this problem. Version 3.5.1 breaks present configurations, if you use this functionality. Maybe people are not using this functionality or are not upgrading? Very unlikely (also version 3.4.1 was broken, but it worked because error was not returned to the shell).

As a workaround one can comment out this setting after first installation, but you have to remember that. And if you forget, it is quite annoying when you are dropped to the shell with error at the end of a lengthy process. It is also not good that you have to remember that the same setting has other effect depending what time you apply it.

The `is-installed` check is irrelevant actually. It always returns false and moves to installation. The only easy and fast fix are skipping installation or adding the `--force` flag to `wp plugin install` / `wp theme install` (might be only for zip files). The former breaks functionality, but there is `folders` functionality. The latter overwrites installed plugins/themes, but I don't know if other users are OK with it (I myself do not care because I treat all what was set by vagrant as disposable).

A `config.yml` parameter would be perfect but it does not solve problem. There has to be some assumption for when there is no such parameter set in config (previous paragraph).

The solution that is on my mind and will not throw an error is:
1. check if it is a .zip file;
2. if yes, install it and overwrite present plugin/theme;
3. if not, assume it is a slug;
4. check if plugin/theme is installed;
5. if yes, skip it;
6. if not, install it.
That behavior is not consistent for zips and slugs, but it not breaks the provisioner.

Maybe we should reopen this issue, set some title that better describes the problem (any ideas?) and ask what others think? I am wondering how people are using this functionality and what is a 'standard use case'. If it is any.

**Comment by tomjn** [comment]
hmmm I think checking for the slug might be the best idea then, `--force` might cause overwriting of changes for some people. We should also look into checking for the presence of a URL via `http`/`https:` in case the user accidentally adds another character to a slug, e.g. `"query monitor"`.

**Comment by mnap00** [comment]
Oh wait... Just made some tests and WP CLI install accepts not only slugs but also names. Lower, upper and mixed case. But is-installed or delete will not find nor delete plugin if it is called by name. Only slugs are allowed in all WP CLI commands.

Maybe the user should be forced to use proper slug - lowercase, underscores and dashes? Otherwise the behavior of the script is peculiar. `"query monitor"` will install Query Monitor. At the next run it will report `is-installed` that the plugin is not installed and report `installed` that the plugin is installed. I have no idea if it is downloading the plugin again.
```
vagrant@vvv:/srv/www/wordpress-local/www$ wp plugin install 'query monitor'
Installing Query Monitor (3.6.5)
Downloading installation package from https://downloads.wordpress.org/plugin/query-monitor.3.6.5.zip...
Using cached file '/home/vagrant/.wp-cli/cache/plugin/query-monitor-3.6.5.zip'...
The authenticity of query-monitor.3.6.5.zip could not be verified as no signature was found.
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Warning: The 'query monitor' plugin could not be found.
Success: Installed 1 of 1 plugins.
vagrant@vvv:/srv/www/wordpress-local/www$ wp plugin is-installed 'query monitor'
vagrant@vvv:/srv/www/wordpress-local/www$ echo $?
1
vagrant@vvv:/srv/www/wordpress-local/www$ wp plugin install 'query monitor'
Warning: query monitor: Plugin already installed.
Warning: The 'query monitor' plugin could not be found.
Success: Plugin already installed.
```
It does not throw an error, so it should be safe. But I wouldn't call it future proof. Using names is not documented in WP CLI.

I think `http` / `https:` check is not required. WP CLI accepts also local paths. Checking for `*.zip*` pattern should be sufficient.

**Comment by tomjn** [comment]
If we tell WP CLI to install `master.zip` it has no idea what's inside, could be Yoast SEO or Query monitor or a theme. So `is-installed` can't work. So any check would need to test for URLs instead. We also can't test for `.zip` on the end because not all URLs will have the extension, and there's `.tar.gz` and other formats too

**Comment by tomjn** [comment]
@mnap00 this PR may help you https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/51 if you could test it that'd be super helpful, just add a `branch: "modify/is-installed-check"` to that sites config and reprovision

**Comment by mnap00** [comment]
> If we tell WP CLI to install master.zip it has no idea what's inside, could be Yoast SEO or Query monitor or a theme.

Yes. This is how WP CLI works (not ideal, I know).

> So `is-installed` can't work.

Yes. This command works only with slugs as per documentation: https://developer.wordpress.org/cli/commands/theme/is-installed/ (actually it accepts names that are printed with `wp theme list` / `wp plugin list`).

> We also can't test for .zip on the end because not all URLs will have the extension, and there's .tar.gz and other formats too

Only .zip is supported: https://developer.wordpress.org/cli/commands/theme/install/ 
> <theme|zip|url>…
>    One or more themes to install. Accepts a theme slug, the path to a local zip file, or a URL to a remote zip file.
(earlier in this thread I checked that it works with names, but it is not documented).

If you try to install .tar.gz:
```
vagrant@vvv:/srv/www/wordpress-local/www$ wp theme install ./master.tar.gz
Warning: ./master.tar.gz: Theme not found
Warning: The './master.tar.gz' theme could not be found.
Error: No themes installed.
```

> @mnap00 this PR may help you Varying-Vagrant-Vagrants/custom-site-template#51 if you could test it that'd be super helpful, just add a branch: "modify/is-installed-check" to that sites config and reprovision

It does not work. Is installed check is only part of a problem. For zips in paths and urls it returns only false so it is good that it is skipped. But then (in the second run) it will try to install a plugin/theme over existing installation and this will only succeed with the `--force` flag. Without this flag the provisioner still fails:
```
    default: Warning: Destination folder already exists. "/srv/www/wordpress-local/www/wp-content/themes/gutenberg-starter-theme/"
    default: Warning: The 'https://github.com/WordPress/gutenberg-starter-theme/archive/master.zip' theme could not be found.
    default: Error: No themes installed.
```
(frankly speaking, you could leave is installed check and add the `--force` flag to the script and it will pass; though it will overwrite installed plugin/theme which might be not desired)

**Comment by tomjn** [comment]
I think then I'll add the `--force` and a warning

**Comment by tomjn** [comment]
@mnap00  Can you recheck the PR?

**Comment by mnap00** [comment]
Yes, it works. The provisioner does not fail with error.
But there is another bug in regex check I believe. Even slugs are recognized as URLs.
```
 ! Warning, a URL was found for this theme, attempting install of twentytwenty with --force set                                                                                                         
Installing Twenty Twenty (1.6)                                                                                                                                                                          
Downloading installation package from https://downloads.wordpress.org/theme/twentytwenty.1.6.zip...                                                                                                     
The authenticity of twentytwenty.1.6.zip could not be verified as no signature was found.                                                                                                               
Unpacking the package...                                                                                                                                                                                
Installing the theme...                                                                                                                                                                                 
Removing the old version of the theme...                                                                                                                                                                
Theme updated successfully.                                                                                                                                                                             
Success: Installed 1 of 1 themes.                                                                                                                                                                       
 ! Warning, a URL was found for this theme, attempting install of https://github.com/WordPress/gutenberg-starter-theme/archive/master.zip with --force set                                              
Downloading installation package from https://github.com/WordPress/gutenberg-starter-theme/archive/master.zip...                                                                                        
Unpacking the package...                                                                                                                                                                                
Installing the theme...                                                                                                                                                                                 
Renamed Github-based project from 'gutenberg-starter-theme-master' to 'gutenberg-starter-theme'.                                                                                                        
Removing the old version of the theme...                                                                                                                                                                
Theme updated successfully.                                                                                                                                                                             
Success: Installed 1 of 1 themes.
```
I'll try to dig it tomorrow.

**Comment by mnap00** [comment]
OK, got it. One bug was because of my typo in script so forget about previous post.
Second bug is `if ... else ...` order. The script checks if a string is a URL, but runs actions for a slug.

Regex scares me, but if it have to be there, maybe something simpler is enough? It could be a check for valid slug characters. The URL check did not allowed for local paths anyways. 

For themes it would be:
```sh
install_themes() {                                                                   
  WP_THEMES=$(get_config_value 'install_themes' '')                                  
  if [ ! -z "${WP_THEMES}" ]; then                                                   
      isslug='^[a-z0-9_-]+$'                                                         
      for theme in ${WP_THEMES//- /$'\n'}; do                                        
        if [[ "${theme}" =~ $isslug ]]; then                                         
          if noroot wp theme is-installed "${theme}"; then                           
            echo " * The ${theme} theme is already installed."                                                                                                                                          
          else                                                                       
            echo " * Installing theme: '${theme}'"                                   
            noroot wp theme install "${theme}"                                       
          fi                                                                         
        else                                                                         
          echo " ! Warning, a URL, path or local file was found for this theme, attempting install of ${theme} with --force set"
          noroot wp theme install --force "${theme}"                                 
        fi                                                                           
      done                                                                           
  fi                                                                                 
}
```

**Comment by tomjn** [comment]
I reversed the logic to fix that, I believe underscores is a valid character. I also don't believe local paths will work, since it'll be a path inside the VM, so there's no way to get it to provision on the first `vagrant up --provision` without forking the site template

**Comment by mnap00** [comment]
You're right. I've made my tests from mapped folders. A standard installation have no Customfile.
It is OK now. The script finishes without errors.
Thanks.

**Comment by mnap00** [comment]
Fixed: https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/51
