### ISSUE TITLE
Webgrind looks for cachegrind files in the wrong location

### ISSUE THREAD

**Issue by Jason-Murray** [Varying-Vagrant-Vagrants/VVV#2335]
## Expected Behavior

Webgrind should show the cachegrind files output by the xdebug 3 profiler to `/tmp` in its dropdown.

## Current Behavior

Webgrind is looking for the files in `/` instead of `/tmp` resulting in no files available for analysis.

## Possible Solution

I think the reason for this is that Webgrind is still looking for the xdebug config var `xdebug.profiler_output_dir` which is now deprecated. I was able to get webgrind to look at the correct folder by reinstating this var alongside `xdebug.output_dir`.

I thought about injecting the webgrind config vars mentioned here https://github.com/jokkedk/webgrind/wiki/Installation#configuration but they are ignored if xdebug is present.

## Steps to Reproduce (for bugs)

1. Create some profiler output
2. Open webgrind

## Your Environment

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.0-git::develop

Platform: platform-darwin19.2.0 shell:/usr/local/bin/zsh vagrant-hostsupdater vagrant-goodhosts vagrant-vbguest vagrant-disksize shared_db_folder_disabled, VVV Path: "/Users/jasonmurray/development/wordpress/build/VVV"
Vagrant: v2.2.14, VirtualBox: v6.1.16r140961

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test
```

**Comment by tomjn** [comment]
I don't believe there is anything that can be done from the VVV end, webgrind themselves need to add proper Xdebug 3 support https://github.com/jokkedk/webgrind/issues/129

Note that if we add the deprecated Xdebug parameter, we'll fill the PHP error logs with deprecation warnings from Xdebug.

There appears to be several issues dancing around but not directly identifying the problem, as well as several pull requests that try to fix Xdebug 3 problems:

 - https://github.com/jokkedk/webgrind/pull/136
 - https://github.com/jokkedk/webgrind/pull/131

Looks like the authors made the PR's, changes were requested, but nobody came back to make the changes.

**Comment by tomjn** [comment]
Eitherway, closing this as it isn't a VVV issue, it needs to be raised and solved with the webgrind project. Once they've updated a reprovision will pull down the latest version

**Comment by tomjn** [comment]
I've opened my own PR to try and fix things https://github.com/jokkedk/webgrind/pull/137
