### ISSUE TITLE
403 Forbidden on vbox 6.1.18 ubuntu 20.10

### ISSUE THREAD

**Issue by raylance** [Varying-Vagrant-Vagrants/VVV#2344]

**Comment by tomjn** [comment]
@raylance can you give us more details? None of the issue template was filled out, no provisioner logs, no indication of what was going on. E.g. where is the 403 forbidden message? Which version of VVV were you using? Was this a first install? An update? Or were you adding a new site?

Let us know the answer to all of those questions, even if the answer is that you do not know. Right now it's not possible to identify the actual problem, just that an Ubuntu 20 user is having an unknown issue :(

**Comment by raylance** [comment]
VVV stopped working after upgrade to ubuntu 20.10, just noticed now. My research pointed to the guest bionic retaining 5.2 guest additions.  Now, after upgrading virtualbox to 6.1.18, the Virtual Media Manager front view (Ctrl-D) shows optical disk of VboxGuestAdditions.iso, but the SHOW button, devices, Insert Guest Additions CD Image says it can't be inserted because there is no optical drive.  Attempts to add a CD are denied by ghosting the add function, even after removing the iso from the front view of the optical disk.  Attached are the host vbox log files and the vagrant config.yml.
[vboxlogs.zip](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5879958/vboxlogs.zip)
[config.yml.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5879974/config.yml.txt)

**Comment by raylance** [comment]
Let me know how I can fix this, and what else you might need to analyze?

**Comment by Mte90** [comment]
Well you need to use the latest version of virtualbox and vagrant.
What version do you have?

**Comment by raylance** [comment]
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.5.1-git::stable

Platform: platform-linux-gnu shell:/bin/bash systemd  vagrant-hostmanager vagrant-hostsupdater vagrant-goodhosts CaseSensitiveFS shared_db_folder_disabled, VVV Path: "/home/ray/vagrant-local"
Vagrant: v2.2.9, VirtualBox: v6.1.18r142142

**Comment by Mte90** [comment]
Ok you don't have the latest vagrant version.
Apart that you tried `vagran provision`? also on what pages you are getting a 403?

**Comment by raylance** [comment]
yes, it does a full provision after I purged the previous vbox and installed the 6.1.18 deb.

The 403 Forbidden obtains from any of the sites, like vvv.test

I just noticed the vboxwebservice is failed and not running -- is that related?

**Comment by Mte90** [comment]
well if you get a 403 this means that the machine is working but the web server on it is not configured probably.
can you share the log of vagrant provision?

**Comment by raylance** [comment]
I thought a git.fetch would guarantee the latest version.  How can I get the latest?

**Comment by raylance** [comment]
The logs were provided in the vboxlogs.zip.  Here they are again, and the yml.txt
[config.yml.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5880112/config.yml.txt)
[vboxlogs.zip](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5880115/vboxlogs.zip)

**Comment by Mte90** [comment]
VVV is not vagrant, vagrant is another tool that let interface VVV with virtualbox.
Those are not the VVV logs but virtualbox logs, check https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/cant-find-vvv.test/

I invite you to join us on Slack so we can offer a better support https://varyingvagrantvagrants.org/docs/en-US/slack/

**Comment by tomjn** [comment]
After some discussion in slack it was discovered  that `www/default/index.php` had been deleted, we don't know the reason though
