### ISSUE TITLE
trouble setting up xdebug on vscode

### ISSUE THREAD

**Issue by premsurana** [Varying-Vagrant-Vagrants/VVV#2355]
I'm unable to setup xdebug on vscode this is my launch.json

```
{
	"version": "0.2.0",
	"configurations": [
	{
            "name": "VVV Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "pathMappings": {
                "/srv/www/wordpress-three/public_html/wp-content/plugins/wpadcenter": "${workspaceFolder}"
            },
        }
	]
}
```

in my log file php7.3_errors.log i also get this error
```
[05-Feb-2021 09:17:02 UTC] Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 192.168.50.1:9003 (from REMOTE_ADDR HTTP header), 192.168.50.1:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
[05-Feb-2021 09:17:25 UTC] Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 192.168.50.1:9003 (from REMOTE_ADDR HTTP header), 192.168.50.1:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
```
am i doing anything wrong?

**Comment by Mte90** [comment]
The ip address is 192.168.50.4 not .1

**Comment by premsurana** [comment]
> The ip address is 192.168.50.4 not .1

hi, thanks for replying where do i change the address? im new to VVV and idk which xdebug.ini to look at, also change for both remote_host and client_host to 192.168.50.4?

**Comment by Mte90** [comment]
I don't use vscode so I think that you should see in their documentation how to set the xdebug ip address and not just the port.
You need just for the remote as it is a VM.

**Comment by premsurana** [comment]
okay, i've solved this issue by changing `xdebug.client_host=10.0.2.2`(gateway) in vagrant-local/config/php-config/xdebug.ini
and ran `vagrant up --provision` its working fine

**Comment by Mte90** [comment]
this is a problem as when you will update VVV this file will be overwritten.
Did you tried to set the remote host in your vs code instead that altering the VVV settings?

**Comment by tomjn** [comment]
@premsurana is this on `stable` or is this on `develop`?

@Mte90 the 192 address is for connecting to the guest, and only on certain operating systems. E.g. Hyper-V provides no control over the IP used

Also, Xdebug connects to the debugger, not the other way around, so there should not be a location to set the IP in VSCode, that's ot how Xdebug works

**Comment by premsurana** [comment]
@tomjn hi, so i switched branch to develop and its working fine, thanks! but i still get this warning in my logs `
[Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 192.168.50.1:9003 (from REMOTE_ADDR HTTP header), 10.0.2.2:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
`

**Comment by tomjn** [comment]
But despite this it still connects to VSCode okay without problems? Xdebug
prints these messages to try and help new users so if you haven’t started
the debug session yet it’ll spam these messages. There’s an issue on Xdebug
mantis trying to get a flag to turn it off, but if the xdebug section of
PHP info says all is good and VSCode is happy then you’re good to go!

**Comment by premsurana** [comment]
yes it does connect with VSCode without any problems, thanks!
