### ISSUE TITLE
Adjust Profiling All Pages On A Site Tideways doc to clarify reprovisioning

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2358]
The `Profiling All Pages On A Site` section of the docs site at https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/ indicates that you can use `tideways: true` to auto-profile a site.

I was speaking with a colleague who was switching back and forth between Xdebug and Tideways, and was under the impression `tideways: true` would require them to reprovision each time. This is not the case.

We should adjust the docs to avoid this confusion

**Comment by Mte90** [comment]
I was looking at this ticket, so the `tideyways.json` is generated on provision.

https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/tideways/provision.sh#L128

Maybe we can create a command that run `php "${DIR}/by-site.php" "${VVV_CONFIG}"` so it is not required to provision every time but just run this command so it is updated. Or add `?enable-tideways=true` in the url.

**Comment by Mte90** [comment]
Just a ping for this about how to proceed further

**Comment by tomjn** [comment]
Currently that issue is blocked by yourself, your PR did the opposite of
what was requested

**Comment by Mte90** [comment]
Uhm seems that PR is for https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2364 I forgot completely the purpose of the pr after an year.
PR update as suggested.
