### ISSUE TITLE
CLI Tideways profiling

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2359]
**Is your feature request related to a problem? Please describe.**

Currently https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/tideways/tideways-header.php doesn't account for CLI, and there is no way to use Tideways and XHGUI with a CLI command

**Describe the solution you'd like**

Some way to activate tideways for CLI commands, or for it to always run when Tideways is active

**Comment by Mte90** [comment]
Maybe we can create a parameter to enable it by CLI?

**Comment by tomjn** [comment]
Someone suggested an environment variable might do the trick

**Comment by Mte90** [comment]
Probably yes is better.

**Comment by tomjn** [comment]
if we do go the environment variable route, that would open up the possibility of a dedicated command similar to `noroot`

**Comment by Mte90** [comment]
Looking at the readme it is possible to do in this way https://github.com/perftools/xhgui/#profiling-a-web-request-or-cli-script

Maybe we can create a command and avoid that php code? I will do some tests
