### ISSUE TITLE
Tideways the changes default version of PHP

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2363]
After provisioning with Tideways PHP 7.2 not 7.3 was the default PHP on CLI. The Tideways should restore the original PHP defaults after provisioning

**Comment by Mte90** [comment]
Also this one was fixed https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/commit/9650cb7c9192b31f3fbd11e3433608f8412e0a5e
