### ISSUE TITLE
Support profiler.enable in Xhgui php profiler  config

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2364]
We can move most of the code in `tideways-header.php` into the `profiler.enable` option:

https://github.com/perftools/php-profiler#configure-profiling-rate

**Comment by Mte90** [comment]
I don't know if it is the best case.
In this way the config file is just config.

**Comment by tomjn** [comment]
That sounds good to me, we stick as close to the xhgui documentation as we can

**Comment by Mte90** [comment]
As context for this pr now is this: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/tideways/config.php-profiler.php#L39
And the code we need to move is on https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/tideways/tideways-header.php

**Comment by tomjn** [comment]
@Mte90 I think the goal was to move it there, not remove it from there
