### ISSUE TITLE
Adjust Splash When unpriviledged on Windows

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2372]
When running on Windows in an elevated prompt we add the `HasWinAdminPriv` token to the splash screen.

We should add a warning when the user is not using an elevated prompt

**Comment by Mte90** [comment]
Just as reference to work on that: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L306

An example of warning in the vagrantfile https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L708

**Comment by Mte90** [comment]
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2383
