### ISSUE TITLE
Error when installing goodhost

### ISSUE THREAD

**Issue by deimidis** [Varying-Vagrant-Vagrants/VVV#2376]
In a new vagrant installation, I cloned this repo and following instructions, I tried to install goodhosts plugin.

`Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5) and net-ssh (= 6.2.0.rc1)
  Activated net-ssh-6.2.0.rc1
  which does not match conflicting dependency (>= 2.6.5)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc1), 6.2.0.rc1 activated

  versus:
    net-scp (= 1.2.1), 1.2.1 activated, depends on
    net-ssh (>= 2.6.5)

  Gems matching net-ssh (>= 2.6.5):
    net-ssh-6.2.0.rc1`

My system is Manjaro on testing branch. It worked some time ago on another Manjaro testing. If I understand, maybe I need to install net-ssh 2.6.5, but my system is trying to install a newer version.

Manjaro Testing branch
Vagrant vagrant-2.2.14-1
vvv: I just clone the repo today

**Comment by tomjn** [comment]
Hello!

This github repo is for issues with VVV, for help with `vagrant-goodhosts` you should go to https://github.com/goodhosts/vagrant

Before you do that, uninstall and reinstall to make sure it's not just vagrants copy of bundler getting confused
