### ISSUE TITLE
Alert the user when space is over

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2380]
**Is your feature request related to a problem? Please describe.**

Sometimes we get users that reports errors on using VVV because they don't have anymore space in the host or in the VM.
We can add some alerts to inform the users so they can handle without reach the support.

**Describe the solution you'd like**

The idea can be an alert in the dashboard or during the start of the machine.

**Comment by tomjn** [comment]
I think a disk space sidebar box with a progress bar, space used/total, and a link to how to increase the size of the VM drive is what's needed

**Comment by tomjn** [comment]
a note that files in shared folders don't count would be useful too

**Comment by Mte90** [comment]
Indeed like cpanel or plesk it will be better. I don't know if this create slowness, cpanel/plesk have a cache and a cron for that so maybe something in js so it is async can be an alternative.
