### ISSUE TITLE
Xdebug info button in dashboard

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2382]
Right now our PHP Info page calls `xdebug_info()` at the bottom if xdebug is active, however, this lead to some confusion when a user ran the `php_info()` function in their own file and did not see the Xdebug output, and assumed Xdebug was not active.

So, if Xdebug is active, we should add a button leading to a file that runs `xdebug_info()` instead of putting it at the bottom of `php_info()`

**Comment by evertiro** [comment]
Ok, I don't know how you handle issues, but since this is merged is the issue closable @tomjn?
