### ISSUE TITLE
xdebug not working

### ISSUE THREAD

**Issue by lxbdr** [Varying-Vagrant-Vagrants/VVV#2384]
Hi, I'm having troubles getting xdebug to work. It worked just fine until recently, I don't know what changed.

I get the following error when running any php command / trying to run `xdebug_on`

```
PHP Warning:  Failed loading Zend extension 'xdebug.so' (tried: /usr/lib/php/20180731/xdebug.so (/usr/lib/php/20180731/xdebug.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/xdebug.so.so (/usr/lib/php/20180731/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.3.27-9+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:10:08) ( NTS )
```

Also I just followed the instructions for a fresh start https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/#starting-from-fresh but without success

**Comment by tomjn** [comment]
@lxbdr are you using the latest version of the `develop` branch? If not, update and reprovision, this is a known and fixed bug

**Comment by tomjn** [comment]
Specifically, 6 days ago in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2377

**Comment by lxbdr** [comment]
@tomjn Thanks, that worked! I was on the stable branch so you might want to consider updating that branch as well as it is mentioned in the docs

**Comment by tomjn** [comment]
We're pretty close too a v3.6 release https://github.com/Varying-Vagrant-Vagrants/VVV/milestone/37
