### ISSUE TITLE
Support for Apple Silicon devices - Parallels

### ISSUE THREAD

**Issue by evertiro** [Varying-Vagrant-Vagrants/VVV#2385]
**Is your feature request related to a problem? Please describe.**

Currently, VVV only officially supports the use of VirtualBox and Hyper-V. Vagrant, however, supports VMWare and Parallels as well, both of which have at least a work-in-progress build for Silicon devices. As of now, the only reason Silicon devices can't be used with VVV is that nobody on the dev team has one. I have one. I want to use VVV on it. I'm going to see what we have to do to make it happen.

**Describe the solution you'd like**

I want to make VVV work on Silicon devices.

**Describe alternatives you've considered**

Please don't make me rehash the long debate on remote environments I just had on Slack...

**Additional context**

This ticket is being opened so that a) I have a place to track my progress on this little project, and b) so that other users who have access to Silicon-based devices have a point of reference on where VVV currently stands with Silicon support. Please note that this is (for now) my personal "pet project" and not an officially supported feature by VVV.

**Comment by tomjn** [comment]
Notes:

 - VMWare and Parallels have technical previews based on using the Apple hypervisor
 - VMWare requires a $199 yearly license as well as purchasing the vagrant plugin from Hashicorp at $79.99 for a grand total of **$279.98**
 - Parallels provides a free plugin and has a $79.99 yearly license for the Business/Pro version required

Parallels is significantly cheaper

We'd need to use an Arm64 box, as well as test that our provisioners work with Arm64 packages. A raspberry Pi should be capable of testing most of this by running the provisioners directly in an Ubuntu 18 type OS

It also looks like there are people attempting to use Parallels for vagrant work on M1 macs:

https://github.com/Parallels/vagrant-parallels/issues/382

Albeit with various issues

**Comment by tomjn** [comment]
Free options so far seem to be to hope VirtualBox adds Arm64 support ( extremely unlikely ), or that we containerize VVV and use docker ( already a longterm goal )

**Comment by evertiro** [comment]
I'm going to read up on the issues present on Parallels and hopefully start there given the price difference. I'd like to eventually be able to green flag both options as working with VVV.

Also... I want to know more about your docker goals. That may get added to my todo list too. I already use Docker a fair bit in my day-to-day work.

**Comment by evertiro** [comment]
Note: I've moved VMWare support to a separate issue (#2393). Now that I have a Parallels-based VVV installation working, the stated purpose of this issue has been technically resolved. While this issue probably isn't closable yet, it shouldn't be held open due to lack of VMWare support.

**Comment by tomjn** [comment]
@evertiro do you think this is closable now?

**Comment by evertiro** [comment]
Yes, I've been running on `develop` for the last week with zero issues.

**Comment by evertiro** [comment]
Note for anyone else who finds their way here: The remaining linked open issues are upstream issues that we're already dealing with internally. If you have questions, please feel free to ping me on Slack.
