### ISSUE TITLE
Update to support Ubuntu 20.04

### ISSUE THREAD

**Issue by evertiro** [Varying-Vagrant-Vagrants/VVV#2386]
**Is your feature request related to a problem? Please describe.**

VVV is currently built around Ubuntu 18.04. Ubuntu 18.04 is getting close to ESM updates only, and 20.04 is the current LTS.

**Describe the solution you'd like**

We should start looking at making VVV work with 20.04 with the goal of switching over completely in the near future.

**Tested working on M1:**
- [x] Dashboard
- [x] MailHog
- [x] Memcached
- [x] Opcache
- [x] PCov
- [x] PHP Info
- [x] phpMyAdmin
- [x] Webgrind
- [x] WP-CLI
- [x] Xdebug

**Not working on M1:**
- [ ] Tideways (`mongodb` install fails)

**Comment by evertiro** [comment]
@tomjn You might as well just assume this is my ticket. Since the existing ARM64 boxes are all 20.04+ I'm going to have to figure out what changes are necessary for 20.04 anyway unless I want to build my own box for 18.04... which seems counterintuitive given its support window. I'll just tackle this first, then move on to dealing with Silicon once this is a bit better tested.

**Comment by evertiro** [comment]
Note, the VVV PPA needs to be updated for focal

**Comment by evertiro** [comment]
Previous comment is erroneous; caching issue. However...

```
default:  ▷ Running after_packages hook
default:  * Installing Shyaml for bash provisioning..
default: sudo: pip: command not found
```

**Comment by evertiro** [comment]
Ubuntu dropped default python2 support in 20.04. Switching to python3/pip3 fixes the above issue.

**Comment by evertiro** [comment]
Now getting the following:

```
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.1): Loading from cache
 Extracting archivePlugin installation failed (include(/srv/www/phpcs/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php): failed to open stream: No such file or directory), rolling back
  - Removing dealerdirect/phpcodesniffer-composer-installer (v0.7.1)

Installation failed, reverting ./composer.json to its original content.

                                                                               
  [ErrorException]                                                             
  include(/srv/www/phpcs/vendor/dealerdirect/phpcodesniffer-composer-installe  
  r/src/Plugin.php): failed to open stream: No such file or directory          
                                                                               

Exception trace:
 () at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 include() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 Composer\Autoload\includeFile() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:322
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at n/a:n/a
 class_exists() at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:204
 Composer\Plugin\PluginManager->registerPackage() at phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php:62
 Composer\Installer\PluginInstaller->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:611
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:248
 Composer\Command\RequireCommand->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:205
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:281
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24
```

**Comment by evertiro** [comment]
This appears to be due to Xdebug.

**Comment by evertiro** [comment]
At the moment, I'm at a loss... I'd appreciate any thoughts anyone else has

**Comment by tomjn** [comment]
@evertiro can you share your changes? If there was a pull request I could test it out and offer help

**Comment by evertiro** [comment]
@tomjn As requested.

**Comment by evertiro** [comment]
Note that while the GH action passed, I can't reproduce that locally on a machine running 20.10 through VirtualBox. Still getting the error mentioned [here](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2386#issuecomment-794504223).

**Comment by evertiro** [comment]
With the linked issue branch for #2385, I now have technically been using a 20.04-based build of VVV for the last 24 hours with no issues. Since I'm on an M1 at the moment, someone running on Intel hardware will have to verify that it also works on their side of the fence.

**Comment by evertiro** [comment]
Note the failure is because this is _only_ the things specific to 20.04 at the point. GH actions require a different issue being merged to pass at this point.
