### ISSUE TITLE
Use COMPOSER_RUNTIME_ENV

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2404]
Composer has added `COMPOSER_RUNTIME_ENV` in the latest unreleased versions, setting this ENV variable to `vagrant` should enable some filesystem fixes

**Comment by evertiro** [comment]
Since this is merged, can it be closed? (What is the VVV official policy on when issues can be closed?)

**Comment by Mte90** [comment]
If the pull request is merged the task can be closed, basically.

**Comment by tomjn** [comment]
I'm surprised GitHub didn't do it automatically

**Comment by evertiro** [comment]
I was as well

**Comment by Mte90** [comment]
Github does if it is able to correlate them, so usually a way is to mention in the first comment the ticket or in the title (in my experience)
