### ISSUE TITLE
Turn off box update check

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2433]
Unless you're destroying and recreating your VM updating the box doesn't change existing VMs. So we should remove this check. I know there are people who will religiously update thinking it helps when it does not, and it might confuse users who think updating their box is updating VVV, who then stay on super old versions of VVV

**Comment by evertiro** [comment]
Which update check?

**Comment by tomjn** [comment]
`vagrant` will check to see if a newer version of the box is available, and tell you so
