### ISSUE TITLE
nginx fails when site names contain spaces

### ISSUE THREAD

**Issue by quentin-th** [Varying-Vagrant-Vagrants/VVV#2459]
## Current Behavior
Hello,

I did the last update of vvv (3.6.2), following those steps : https://varyingvagrantvagrants.org/docs/en-US/installation/keeping-up-to-date/#major-versions, but now I'm not able to access to http://vvv.test/ ( error : ERR_CONNECTION_REFUSED )

Since this update, when I'm running "vagrant up", the end of output is : 

```
==> default: Machine already provisioned. Run 'vagrant provision' or use the '--provision'
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default:  * Restarting Nginx
    default: Job for nginx.service failed because the control process exited with error code.
    default: See "systemctl status nginx.service" and "journalctl -xe" for details.
==> default: Trigger run failed
==> default: The SSH command responded with a non-zero exit status. Vagrant
==> default: assumes that this means the command failed. The output for this command
==> default: should be in the log above. Please read the output to determine what
==> default: went wrong.
```
The provisioning seems ok (no errors while provisioning) and vagrant ssh is working.

I tried a fresh install following those steps: https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/#starting-from-fresh but the problem is still here (I also tried with the develop branch but no commits differences with stable for now)

I tried some solution posted here : https://github.com/hashicorp/vagrant/issues/1659#issuecomment-537515553 but the problem persists

## Your Environment
Windows 10
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.2-git::stable(62c5796)

Platform: platform-mingw32 windows  HasWinAdminPriv  vagrant-hostsupdater vagrant-goodhosts vagrant-vbguest monochrome-terminal shared_db_folder_disabled, VVV Path: "C:/dev/vagrant-local"
Vagrant: v2.2.10, VirtualBox: v6.1.12r139181

Can you help me ? 

Thanks

**Comment by Mte90** [comment]
Did you run `vagrant provision`? There is a nginx issue and without the logs is difficult to see if.
You can see those errors with `vagrant ssh` and `systemctl status nginx.service"`.

**Comment by tomjn** [comment]
@quentin-th we're going to need your `config.yml` and the full output of the provision command you used

**Comment by quentin-th** [comment]
Thank you for your responses.

@Mte90 
Yes I did a vagrant provision but the problem persists.
I did those commands, it seems there is a problem with nginx yes, here is the output : 
```
● nginx.service - nginx - high performance web server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-05-06 12:18:20 UTC; 11min ago
     Docs: https://nginx.org/en/docs/
  Process: 11715 ExecStop=/bin/sh -c /bin/kill -s TERM $(/bin/cat /var/run/nginx.pid) (code=exited, status=0/SUCCESS)
  Process: 11618 ExecReload=/bin/sh -c /bin/kill -s HUP $(/bin/cat /var/run/nginx.pid) (code=exited, status=0/SUCCESS)
  Process: 11992 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
 Main PID: 7974 (code=exited, status=0/SUCCESS)
```


@tomjn 
here is the full outupt : https://gist.github.com/quentin-th/037985595695098db02c4a9c515cc796
and my config.yml: https://gist.github.com/quentin-th/7fec6395e22988080f04e6591f3f2564

Thanks !

**Comment by tomjn** [comment]
when you said you updated, what version did you update from? And have you tried turning it off then on again? What is the output of `vagrant ssh -c "sudo nginx -t"`?

**Comment by quentin-th** [comment]
Ok, I fixed the problem thanks to your ssh cmd output !!
On my config.yml file I forgot to put a dash between one of the site name... I did it, and now everything is working ! 

Thank you for leading me in the right direction :)

**Comment by tomjn** [comment]
A space, although unorthodox, is something that can and should be handled, that YAML file was valid, so I can only presume that the Nginx config processing can't handle spaces. I suspect wrapping folder paths in quotes will fix the issue

**Comment by quentin-th** [comment]
Hello,

if it can helps, here the output from `vagrant ssh -c "sudo nginx -t"` : (space was between christian and delecluse)

```
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:84
nginx: [emerg] invalid number of arguments in "root" directive in /etc/nginx/custom-sites/vvv-auto-christian delecluse-provision-fc5b89db8e5a384b5af273281a9bc350.conf:5
nginx: configuration file /etc/nginx/nginx.conf test failed
Connection to 127.0.0.1 closed.
```

**Comment by tomjn** [comment]
So tests show that the PR works, but that other changes are needed. I've merged it but these changes will be needed to:

 - The TLS CA utility doesn't handle certificates correctly, each word is its own folder with its own certificate which is incorrect
 - The `provision-site.sh` script needs adjusting so the TLS section is wrapped in quotes

There may be other locations with issues, but commenting out the certificate directives and reloading Nginx resulted in the expected WP site, so we aren't far off supporting spaces in site names

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/commit/62d4de57ca0aa8574499d2200de53db342e08285 fixes the issue in the TLS CA, bash considered the space a seperator and split `christian decleuse` into `christian` and `decleuse`

**Comment by tomjn** [comment]
With https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2461 the original site name without a space should work, I've tested it locally, all looks good, it just needs someone to confirm it works for them

Here's the site to add to `config.yml`:

```yaml
  christian delecluse:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - cdelecluse.test
```
