### ISSUE TITLE
The box 'ubuntu/bionic64' could not be found or...

### ISSUE THREAD

**Issue by knighthawk0811** [Varying-Vagrant-Vagrants/VVV#2475]
## What was The Command Used To Provision
vagrant up --provision
vagrant up
vagrant box update

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke
```
C:\Users\joseph.neathawk\vvv-local>vagrant up
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.2-git::stable(62c5796)

Platform: platform-mingw32 windows  missingWinAdminPriv  vagrant-goodhosts monochrome-terminal shared_db_folder_disabled, VVV Path: "C:/Users/joseph.neathawk/vvv-local"
Vagrant: v2.2.16, VirtualBox: v6.1.22r144080

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: [vagrant-goodhosts] Checking for host entries
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 one.wordpress.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 two.wordpress.test
==> default: Box 'ubuntu/bionic64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/bionic64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/ubuntu/bionic64"]
Error: The requested URL returned error: 403
```
## Possible Solution

was there a change at vagrantcloud that might explain the 403 error?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

Operating System: Windows

**Comment by Mte90** [comment]
I see that is available on https://app.vagrantup.com/ubuntu/boxes/bionic64 did you tried again the command?

**Comment by tomjn** [comment]
https://twitter.com/haheap/status/1397184578683559949

Hashichorp may be having issues, eitherway this isn't something within our control, the box hasn't been taken down so it looks like there's an outage of some kind

**Comment by tomjn** [comment]
https://github.com/hashicorp/vagrant/issues/12390#issuecomment-848039375

wait a little bit and try again 🤞🏻

**Comment by knighthawk0811** [comment]
Thanks! An outage is fine. Maybe not ideal, but it means I probably wasn't doing anything wrong myself.

Will try again later and update this thread either way.

**Comment by knighthawk0811** [comment]
It was just an outage. Everything worked fine after I waited until it was back up.

**Comment by ahmedsadman** [comment]
If someone is still facing the issue locally, please turn off your antivirus protection and run `vagrant up` again. That should do the trick.

**Comment by tomjn** [comment]
@ahmedsadman we do not use that box, we use `bento/ubuntu-20.04` on virtualbox, it sounds like you're using a very old version, you should update VVV

**Comment by zorke2000** [comment]
Thanks for the useful tip @ahmedsadman ! Worked for me :)

**Comment by NU-OnE** [comment]
vagrant box add --insecure ubuntu/bionic64

**Comment by tomjn** [comment]
VVV doesn’t use bionic anymore, you should update, or back up your database
and destroy then reprovision
