### ISSUE TITLE
Provision Failure "systemctl status nginx.service" and "journalctl -xe" for details.

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2490]
I did `vagrant reload --provision`. 
And now I get this error on `vagrant up`:
```
    default:  * Restarting Nginx and MySQL
    default: Job for nginx.service failed because the control process exited with error code.
    default: See "systemctl status nginx.service" and "journalctl -xe" for details.
```
[This is the provision log.](https://gist.github.com/shanebp/2e7283254020aab318180f64ab041372)

Everything work properly before the --provision.

**Comment by benlumia007** [comment]
can you also provide your config.yml. I see there's an error 
```
 default: sed: -e expression #1, char 19: unknown option to `s'
 ```

**Comment by tomjn** [comment]
3.4.1 is quite an old version of VVV, please upgrade and reprovision, preferably to the current `develop` branch which is 3.7.0.

It's extremely likely that the issue has either been fixed, or that a much more informative error message will show up

**Comment by benlumia007** [comment]
ohh i didn't see that, yah, try the develop branch.

**Comment by shanebp** [comment]
Will upgrading wipe out any of my www sites or databases?

If not, I should just follow these directions for Windows?
https://varyingvagrantvagrants.org/docs/en-US/installation/
```
git clone -b stable https://github.com/Varying-Vagrant-Vagrants/VVV.git %systemdrive%%homepath%/vvv-local
cd %systemdrive%%homepath%/vvv-local
vagrant plugin install --local
```

**Comment by benlumia007** [comment]
it will not wipe your data, `git checkout develop` and `vagrant up --provision` should do it.

**Comment by shanebp** [comment]
I did `git checkout develop` and `vagrant up --provision`
It installed  `v3.5.0-git::develop` and now runs without errors. 
Thanks guys.

**Comment by tomjn** [comment]
@shanebp 3.5 is still quite out of date, you should do a `git pull`

> Will upgrading wipe out any of my www sites or databases?

Only if you destroy the VM with `vagrant destroy` then manually delete your `www` folder in windows explorer.

**Comment by shanebp** [comment]
I did the pull and now have 3.7
But on the provision, as a windows administrator, it ended with this error.
 `    default: Error: /usr/local/bin/wp is not writable by current user.
    default:  ! The 'main' provisioner ran into problems, the full log is available at '/var/log/provisioners/2021.06.18_19-11-57/provisioner-main.log'. It completed in 417 seconds.`

[Here is that log.](https://gist.github.com/shanebp/b07838e3849ced4eed2366103aa1bc49)

**Comment by tomjn** [comment]
@shanebp can you pull again and reprovision?

**Comment by shanebp** [comment]
That worked, thanks.

**Comment by benlumia007** [comment]
i was gonna mention that to check for updates using `git pull` once awhile to grab the latest fix even if you're not in the latest branch or not.

**Comment by shanebp** [comment]
Thanks for the advice.
