### ISSUE TITLE
Cannot open any local site. Chrome only.

### ISSUE THREAD

**Issue by m-pokrovskii** [Varying-Vagrant-Vagrants/VVV#2491]
Cannot open any local site. Chrome only.
OSX Catalina. Updated to the last vvv commit. Certificate for vvv.test installed and trusted.
![A4AFDBB5-6D71-4E94-B17A-48ACF00257D8](https://user-images.githubusercontent.com/246029/122667239-7f9c3d00-d1ba-11eb-9bc2-df25877d24a1.png)

**Comment by tomjn** [comment]
Looks like you don't have entries in your host file for vvv.test, did you forget to install the vagrant plugin that sets those up?

If the issue only happens in Chrome but the site loads in Firefox/Safari/etc, then it isn't a VVV problem, it's possible Chrome hasn't been restarted in a long time or that you have a security extension that is interfering

**Comment by m-pokrovskii** [comment]
You are correct about the extension. Thanks for giving me a direction.
