### ISSUE TITLE
Vagrant goodhosts plugin version

### ISSUE THREAD

**Issue by csdev-nl** [Varying-Vagrant-Vagrants/VVV#2495]
Hi guys,

I recently updated my vagrant-goodhosts plugin and all went well. However, it does break VVV. It seems VVV is looking for version 1.0.15 whereas the most recent version is 1.0.17. I reverted back to 1.0.15 and now my issue is cleared. Just to be sure I repeated the process and the same thing happened. So for now I have reverted to 1.0.15.

**Comment by tomjn** [comment]
Is this on the `develop` branch?

**Comment by csdev-nl** [comment]
Wow Tom, that is super-mega quick ;-). Thanks.
No, this is on the master branch (version 3.6.2) and the latest Vagrant version (v2.2.17). 

Sorry for not sharing that info.

**Comment by Mte90** [comment]
I don't understand what issue are you facing.
Without any information about the problem I cannot say if it is something in the plugin.

**Comment by csdev-nl** [comment]
> I don't understand what issue are you facing.
> Without any information about the problem I cannot say if it is something in the plugin.

The issue that arises is that the VM doesn't boot and shows the following error message (this is when using vagrant-goodhosts 1.0.17): 

`Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-goodhosts (= 1.0.15)'
`

After reverting back to vagrant-goodhosts 1.0.15 all is well. Hope this is a bit more clear.

**Comment by tomjn** [comment]
@csdev-nl can you switch to the `develop` branch? It has a lot of changes and fixes, and we don't know if the issue exists unless it can be replicated on `develop`.

I'd also advise against the `master` branch. It's maintained only because people are still using it and we don't want them stuck on ancient versions, or at least until we find a good way to nuke it from orbit. Use the `stable` branch ( or even better  `develop` )

**Comment by tomjn** [comment]
> The issue that arises is that the VM doesn't boot and shows the following error message (this is when using vagrant-goodhosts 1.0.17):

This kind of output is usually caused by an update to vagrant itself. There's a high chance this has nothing to do with VVV or goodhosts and you just need to do what the message says

**Comment by tomjn** [comment]
In particular, the error message contains both an explanation of why it happened, as well as the solution:

> If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:
> 
> vagrant plugin expunge --reinstall

**Comment by csdev-nl** [comment]
> @csdev-nl can you switch to the `develop` branch? It has a lot of changes and fixes, and we don't know if the issue exists unless it can be replicated on `develop`.
> 
> I'd also advise against the `master` branch. It's maintained only because people are still using it and we don't want them stuck on ancient versions, or at least until we find a good way to nuke it from orbit. Use the `stable` branch ( or even better `develop` )

Allright, that sounds like a plan. I switch to the development branch instead!

**Comment by csdev-nl** [comment]
> In particular, the error message contains both an explanation of why it happened, as well as the solution:
> 
> > If Vagrant was recently updated, this error may be due to incompatible
> > versions of dependencies. To fix this problem please remove and re-install
> > all plugins. Vagrant can attempt to do this automatically by running:
> > vagrant plugin expunge --reinstall

The solution does not work however. Obviously that was step 1 for me.

**Comment by tomjn** [comment]
Do you have the output of that command if it did not work? I'm still trying to figure out where the conclusion that VVV requires a specific version comes from

**Comment by csdev-nl** [comment]
> Do you have the output of that command if it did not work? I'm still trying to figure out where the conclusion that VVV requires a specific version comes from

Me too.. The output of the command is below:

```
Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Fetching vagrant-goodhosts-1.0.17.gem
Installed the plugin 'vagrant-goodhosts (1.0.17)'!
```

Btw: I just switched to the development branch, if I `git pull`, it says I'm already up to date - is that correct?

**Comment by tomjn** [comment]
hmmm are you confusing local and non-local plugins? You haven't included the command you used to generate that output, I can't tell if you used `vagrant plugin repair` or `vagrant plugin repair --local`

**Comment by csdev-nl** [comment]
> hmmm are you confusing local and non-local plugins? You haven't included the command you used to generate that output, I can't tell if you used `vagrant plugin repair` or `vagrant plugin repair --local`

Sorry for not being clearer. I did not use the --local parameter (I don't have any local plugins installed). See below:

```
vagrant plugin list
vagrant-goodhosts (1.0.17, global)
```

**Comment by tomjn** [comment]
if you add  `--local` to that command does that change though?

**Comment by tomjn** [comment]
`vagrant plugin list` is a global plugin command, it won't , list project specific plugins, the same with all the other vagrant plugin commands. If you repaired and expunged without `--local` it won't repair and expunge local plugins

**Comment by csdev-nl** [comment]
> `vagrant plugin list` is a global plugin command, it won't list project specific plugins, the same with all the other vagrant plugin commands. If you repaired and expunged without `--local` it won't repair and expunge local plugins

Bloody hell, you're right. After running `vagrant plugin --expunge --local` all is well. Okay, that's a lesson learned for me. Thanks for your quick and accurate support @tomjn!

**Comment by tomjn** [comment]
Glad it's working, I'd get rid of the global plugin and append `--local` on all plugin commands to try and avoid future confusion, it's not the greatest choice of parameters

**Comment by Mte90** [comment]
> > The issue that arises is that the VM doesn't boot and shows the following error message (this is when using vagrant-goodhosts 1.0.17):
> 
> This kind of output is usually caused by an update to vagrant itself. There's a high chance this has nothing to do with VVV or goodhosts and you just need to do what the message says

Yes those errors are bot by the plugin vagrant updates or changes on the instance that with some command is easy to fix.
