### ISSUE TITLE
Q: How to allocate more resources to combat "Warning: mysqli_query(): (HY000/1021): Disk full"

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#2501]
A few times recently I have been getting this error come up:

![image](https://user-images.githubusercontent.com/1038062/127178684-5e829583-70c1-4c06-9ec2-515fa676ef9b.png)

`Warning: mysqli_query(): (HY000/1021): Disk full (/tmp/#sql_2d3e_0.MAI); waiting for someone to free some space... (errno: 28 &quot;No space left on device&quot;) in /srv/www/thepharmco/public_html/wp-includes/wp-db.php on line 2024`

It's happened on two separate sites so I'm thinking its a server level setting I need to change?

The laptop has 1.54tb free on it.

I'm running:

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.2-git::stable(62c5796)

Platform: platform-darwin19.2.0 shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled, VVV Path: "/Users/matthewharris/rtp/rtpDesign/localDev"
Vagrant: v2.2.16, VirtualBox: v6.1.22r144080
```

**Comment by tomjn** [comment]
The best fix for this is to update VVV, this issue is usually caused by several bugs that we fixed months ago. Turn it off then on again, pull down v3.7.1, and reprovision.

**Comment by tomjn** [comment]
Otherwise, the disk space plugin can increase the size of the disk, but it might (probably) need you to recreate the VM from scratch.

If the cause of the issue is the known already fixed bugs though, then it will just consume the extra space and you'll be back where you started ( until you update to 3.7.1 or newer )

**Comment by rtpHarry** [comment]
Thanks for the prompt reply, I did realise I had committed the sin of not updating to the latest version after I posted this, sorry.

I'm still working on that because at the moment the plugin update is broken:

```
❯ vagrant plugin update --local
Updating installed plugins...
/opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:441:in `realpath': No such file or directory @ realpath_rec - /Users/matthewharris/rtp/rtpDesign/localDev/.vagrant/plugins (Errno::ENOENT)
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:441:in `realpath'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:441:in `block in clean'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:440:in `delete_if'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:440:in `clean'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/manager.rb:257:in `update_plugins'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/action/update_gems.rb:23:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/update.rb:28:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
```

**Comment by rtpHarry** [comment]
If anyone else finds themselves in this situation, I had to use finder, then press `cmd+shift+.` to show hidden files, navigate into the path and delete the folders, then use `vagrant plugin expunge --reinstall` to clear out the system.

I only had `vagrant-goodhosts` installed so I just reinstalled that.

**Comment by rtpHarry** [comment]
I always have the worse luck with this updating process, which is why I try not to touch it because it always collapses on me when i mess with it. I remember having a conversation with you once saying that I should always keep up to date and post on here if I have any issues beyond just doing a git pull and reprovision... well, you would never get any peace if I did that haha

Now `vagrant up --provision` is breaking with:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp
```

**Comment by tomjn** [comment]
To update VVV:

```
git pull
vagrant up --provision
```

Updating vagrant and virtualbox is completely optional but unnecessary

**Comment by tomjn** [comment]
For vagrant plugins, expunge/nuke/uninstall+reinstall

```
vagrant plugin expunge --local
```

Sometimes necessary after updating `vagrant`. If `vagrant` works for you there's no reason to update it

> well, you would never get any peace if I did that haha

We can't fix things if you don't!

> Now vagrant up --provision is breaking with:

This may be related to deleting that folder in Finder, or updating VirtualBox ( I assume you restarted your machine after updating VirtualBox? Kernel extensions need reloading too, it's not just Windows users ).

First power cycle your Mac.

If that doesn't work, try this answer:

https://stackoverflow.com/a/21363356/57482

If that doesn't work, uninstall VirtualBox and reinstall it.

And remember, VVV is not vagrant, just update VVV next time, `git pull && vagrant up --provision`. It's nice to have newer versions of virtualbox or vagrant but if it isn't broken don't fix it.

**Comment by rtpHarry** [comment]
Thanks for the detailed answers. I wasn't actually updating vagrant or vbox but I am halfway through this now.

All of the errors posted above was just attempting to go through the "minor updates" process listed at https://varyingvagrantvagrants.org/docs/en-US/installation/keeping-up-to-date/

```
git pull # update to latest git version
vagrant plugin update --local # update vagrant plugins
vagrant up --provision # launch the VM
```

**Comment by rtpHarry** [comment]
```
    default:    ✧ ✔ Success!       ✧    ✔              ✧    ✔ 
    default:  ✔ ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄ ✧           ✧       ✧         
    default:   ✧█▒▒░░░░░░░░░▒▒█  ✔    ✧           ✔       ✧   
    default: ✧   █░░█░░░░░█░░█ ✧        ✔      ✧      ✧       
    default:  ▄▄  █░░░▀█▀░░░█  ▄▄✧ ✔ Provisioning has finished!
    default: █░░█ ▀▄░░░░░░░▄▀ █░░█   Visit http://vvv.test
```

got there in the end, thanks for the support
