### ISSUE TITLE
Add backward compatible for db_backup option 

### ISSUE THREAD

**Issue by emgk** [Varying-Vagrant-Vagrants/VVV#2502]
Did we intentionally extended `db_backup` option here https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2478 _(couldn't find  useful doc related to this change)_, pulling these changes to the local setup can break the purpose of db_backup, because its configured in an old way `db_backup: false` in vvv/config.yml file, can we add backward compatibility in following files? 

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/b4d2655bf01120e32cdfc6251af26a2c009eeccc/config/homebin/vagrant_destroy#L21
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/b4d2655bf01120e32cdfc6251af26a2c009eeccc/config/homebin/vagrant_halt#L21
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/b4d2655bf01120e32cdfc6251af26a2c009eeccc/config/homebin/vagrant_suspend#L21 

Thanks :pray:

**Comment by Mte90** [comment]
So you mean add a code that check the previous parameter for old VVV instance that didn't updated the settings?
If yes , it is something that we need to do.

**Comment by tomjn** [comment]
@Mte90 this was a part of the original spec, we can't break things for existing users, it should never have been merged if it that wasn't the case

**Comment by tomjn** [comment]
@Mte90 I'm labelling this OMGWTFBBQ level high priority

**Comment by tomjn** [comment]
@emgk that PR isn't related to this, it fixes a YAML syntax error

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2346 is the PR that implemented this

Based on the what the OP says It looks like nobody did the testing I asked for:

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2346#issuecomment-821257734

**Comment by Mte90** [comment]
I did a pr but require some testings.
