### ISSUE TITLE
Windows SSH Agent Investigation

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2505]
***If any provisioners run, even if they fail or misbehave, then this issue does not affect you***

---

Sometimes Windows users can't provision because `vagrant` uses `net-ssh` to communicate with the VM, and `net-ssh` needs an SSH Agent. If a compatible SSH Agent isn't available, it will time out. This is necessary for the vagrant insecure generated key to work.

Additionally, `net-ssh` is only capable of interfacing with a small number of SSH Agent + unix sockets emulators on Windows:

 - Pageant
 - Git Bash
 - Cygwin

Because Unix sockets aren't a thing on Windows, socket emulation layers are used to bridge the divide.

WSL is an unknown quantity given that it uses a form of virtualisation that is not hyper-v, and the form this takes depends on which version of WSL is being used. V2 uses the Appx userspace virtualisation technology that docker is eventually moving to, unlike the VirtualBox hypervisor or the Hyper-V hypervisor

The OpenSSH service that comes with Windows is _not_ compatible.

Notes:

## Windows Command Prompt/Powershell

 - If the user spins up a powershell or command prompt the `ssh` commands _they get come from the OpenSSH service that is incompatible_
 - If the user tries to start the ssh agent with `ssh-agent` it will try to use the incompatible Windows OpenSSH service and fail with `unable to start ssh-agent service, error :1058`
 - `ssh-add -l` will fail with this error:
```
C:\Users\Tiger>ssh-add -l
Error connecting to agent: No such file or directory
```
 - paegant does not change this
 - however, `vagrant up` runs if pageant is open

## Git Bash

This uses its own Socket emulation layer

`SSH_AUTH_SOCK=/tmp/ssh-yYDAby6pXEyQ/agent.154; export SSH_AUTH_SOCK;`

## Git Shell

I'm not sure what git shell does but it opens a powershell prompt and immediately asks for an SSH key password. I could not use `ssh -v` to identify the version of SSH, and the `where` command wouldn't locate the ssh executable for me.

## Windows Terminal

It depends which sub-shell you use, refer to the above titles, you can identify the shell you're using from the tab title

# The Big Compatibility Graph ( Hyper-V )

Will `vagrant up`? Each row is a shell/prompt, each column is an SSH Agent provider

| Can the shell use:                | No SSH Agent | Windows OpenSSH Service | GitBash SSH Agent | Cygwin SSH Agent | Pageant | GitHub Desktop App |
|-----------------|--------------|-------------------------|-------------------|------------------|---------|--------------------|
| cmd.exe         |              | ❌                       | ?                 | ?                | ?       |                    |
| cmd.exe/clink | Maybe | ❌                       |                   |                  | ✔       |                    |
| Powershell      | Maybe | ❌                       |                   |                  |         |                    |
| Git Bash        | ✔            | ❌                       |                   |                  |         |                    |
| Git Shell       |              | ❌                       |                   |                  |         |                    |
| Cygwin          |              | ❌                       |                   |                  |         |                    |
| WSL v1          |              | ❌                       |                   |                  |         |                    |
| WSL v2          |              | ❌                       |                   |                  |         |                    |

**Comment by jd4u** [comment]
[Note: With Git Bash, `where ssh` results two places... Git and OpenSSH folders.]

With VVV 3.7.2, the first `vagrant up --provision` command works. But once the machine is halted and started with the `vagrant up` command, the machine give timeout error after printing `default: SSH auth method: private key`. [ Error suggested : you may want to increase the timeout ("config.vm.boot_timeout") value. ] The timeout happens nearly after 1 minutes.

I destroyed machine twice. And now I found this issue as bug.
(In VVV 3.4.1, it was all working. But after upgrading to 3.7.2, this issue is coming)

What are the options at this stage....to fix or workaround....? 

Appreciate guidance here.

**Comment by tomjn** [comment]
Hello!

The issue template has some imprint questions you missed out such as which
operating system, a copy paste of the VVV splash logo and debug
information, virtualbox version etc

Can you include that information?

**Comment by jd4u** [comment]
OS: Windows 10
VirtualBox: 6.1.28 (Right now downgrading to 6.1.24)
Log: 
[provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/7492396/provisioner-main.log)

No debug logging found in VVV/log folder.

Another try with following is doing now. I will update.

**Comment by tomjn** [comment]
@jd4u you need a compatible SSH agent:

 - msysgit/git for windows console
 - cygwin

If you are able to run any of the provisioners then this problem does not apply to you. **_As you were able to get the main provisioner to run this is not your issue and has nothing to do with you._**

**Comment by tomjn** [comment]
For now I have these recommendations:

 - use Git Bash to run `vagrant` commands on Windows
 - If using VirtualBox, use at least VirtualBox 7 or higher
 - Ensure the SSH Agent is running by using the command `eval "$(ssh-agent -s)"`

**Comment by tomjn** [comment]
This is now in https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/windows/

<blockquote><img src="https://varyingvagrantvagrants.org/images/vvv.png" width="48" align="right"><div><img src="/images/vvv.png" height="14"> VVV</div><div><strong><a href="https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/windows/">Windows</a></strong></div><div>Windows issues.</div></blockquote>
