### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by davidwolfpaw** [Varying-Vagrant-Vagrants/VVV#2507]
## Current Behavior

It appears that #2506 dc3633aa8c7cfec83ae2ce2a6f36b0dd68f44553 causes an issue for running `vagrant up`. I'm attaching the error that I got:

```
$ vagrant up
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/Users/david/vagrant-local/Vagrantfile:697: can't find string "HTM" anywhere before EOF
/Users/david/vagrant-local/Vagrantfile:697: syntax error, unexpected end-of-input, expecting `end'
```

For the moment I've reverted to the prior Vagrantfile and successfully run `vagrant up`.

**Comment by tomjn** [comment]
Does https://github.com/Varying-Vagrant-Vagrants/VVV/commit/ccc620eeccafb408faf9be04148c5bd9af043602 fix this for you?

**Comment by davidwolfpaw** [comment]
> Does [ccc620e](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/ccc620eeccafb408faf9be04148c5bd9af043602) fix this for you?

Confirming that ccc620eeccafb408faf9be04148c5bd9af043602 does solve the problem

**Comment by tomjn** [comment]
Thanks :)
