### ISSUE TITLE
FYI: varyingvagrantvagrants.org cert expiration and resolution

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#2508]
👋🏻 Just a general FYI ticket that can be closed right away.

_Someone_ let the cert expire on varyingvagrantvagrants.org and it's various flavors today because _someone_ was still running an Acme v1 client to manage certs.

The VVV website was probably unreachable with an SSL error for several hours. I just configured new certs and everything is back in order as of a few minutes ago.

Carry on! :)

**Comment by Mte90** [comment]
Thanks to let us know :-)
