### ISSUE TITLE
Webgrind install fails with composer v2

### ISSUE THREAD

**Issue by ssnepenthe** [Varying-Vagrant-Vagrants/VVV#2524]
I think I manually upgraded composer to v2 (2.1.6 currently) but it looks like the develop branch installs composer v2 as well so this should be relevant going forward.

## What was The Command Used To Provision

```shell
vagrant provision --provision-with="utility-core-webgrind"
```

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Logs/What Broke

```shell
==> default: Running provisioner: utility-core-webgrind (shell)...
    default: Running: /var/folders/8t/0wr196_d7kx1rgth39mbykjm0000gn/T/vagrant-shell20210909-66461-16gl1t0.sh
    default:  ▷ Running the 'utility-core-webgrind' provisioner...
    default: Loading composer repositories with package information
    default: Updating dependencies
    default: Your requirements could not be resolved to an installable set of packages.
    default: 
    default:   Problem 1
    default:     - oomphinc/composer-installers-extender[v1.1, ..., v1.1.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    default:     - Root composer.json requires oomphinc/composer-installers-extender ^1.1 -> satisfiable by oomphinc/composer-installers-extender[v1.1, v1.1.1, v1.1.2].
    default: 
    default:  ✔ The 'utility-core-webgrind' provisioner completed in 2 seconds.
```

## Possible Solution

v2 of the composer installers extender package supports composer v2. Manually bumping the version constraint for oomphinc/composer-installers-extender to ^2.0 worked just fine for me. I didn't make a PR on the vvv-utilities repo because I'm not sure if it needs to still support ^1.1 for any sort of BC reason.

## Steps to Reproduce (for bugs)

1. Either checkout develop branch or manually upgrade composer to v2
2. Update config/config.yml to enable webgrind
3. Provision

**Comment by tomjn** [comment]
>  I didn't make a PR on the vvv-utilities repo because I'm not sure if it needs to still support ^1.1 for any sort of BC reason.

Feel free to go ahead and make the change, you can do something like `^1.0 || ^2.0` if  remember right to keep composer 1 support

**Comment by tomjn** [comment]
Also webgrind may not be that useful with xdebug 3 changes and turning of grind output ( the files were excessive and filling up lots of peoples VMs, and webgrind wouldn't read them anyway, no idea why )

**Comment by ssnepenthe** [comment]
I noticed webgrind was looking for profile files in the wrong directory right after submitting this issue.

Looks like you submitted a pr to fix it back in january. No releases since then though, so for my own use I also changed the webgrind version constraint to dev-master - Probably not ideal for VVV.

Otherwise it seems to be working alright (albeit with only a few minutes of use) with the exception of https://github.com/jokkedk/webgrind/issues/132.

**Comment by tomjn** [comment]
@ssnepenthe  Is this still an issue? The composer.json has the 2.0 version at:

https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/webgrind/composer.json#L5

I believe i fixed this in:

https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/commit/105a9aedd10aea85e4ff29a608a557b61ed1794a

Can you confirm all is good now?

**Comment by Mte90** [comment]
Ping to @ssnepenthe

**Comment by ssnepenthe** [comment]
Sorry about the delay... It seems like this is fixed, thanks!
