### ISSUE TITLE
Bug: Base box can no longer be resized by vagrantdisksize plugin

### ISSUE THREAD

**Issue by Jason-Murray** [Varying-Vagrant-Vagrants/VVV#2528]
## Expected Behavior

Disk can be resized to a larger size.

## Current Behavior

Bento base box's partitions do not resize inside guest.

**Comment by tomjn** [comment]
We don't maintain `vagrant-disksize`, we just pass the value in the config to the plugin and let it do its thing. Also base boxes are just starting points used to create a new VM, they have nothing to do with vagrantdisksize. You should raise this issue with their github.

Boxes are like cookie cutters, they're used to make cookies but once they've been used they're no longer involved in the baking/eating process.

**Comment by tomjn** [comment]
and include the output when you open the issue on their github, they'll need much more information
