### ISSUE TITLE
Using VVV PHPUnit WP tests from PHPStorm 'Run' dialog?

### ISSUE THREAD

**Issue by channeleaton** [Varying-Vagrant-Vagrants/VVV#254]
I'm just trying to find out if someone has done this, or if it's even possible. I've tried setting up the Vagrant box as a mounted folder and SFTP and it fails each time with 404.

It looks like PHPStorm is hitting a url `/_intellij_phpunit_launcher...` but that doesn't exist.

**Comment by dwainm** [comment]
+1 it is really hard to get phpStorm working with PHPUnit on the remote vagrant server.

**Comment by rhurling** [comment]
Hi, after searching for a while and testing a lot I found this tutorial to run WP Tests:
http://andowebsit.es/blog/noteslog.com/post/how-to-run-wordpress-tests-in-vvv-using-phpstorm-8/

And this for a Plugin:
http://andowebsit.es/blog/noteslog.com/post/how-to-run-wordpress-tests-in-vvv-using-wp-cli-and-phpstorm-8/

Using these I can run tests both for a plugin and WP itself.
Hope it helps!

**Comment by jeremyfelt** [comment]
@rhurling thanks for sharing those articles, that did the trick!

I ran into some differences with PHPStorm 9 and my configuration, so I [wrote them up here](https://jeremyfelt.com/2015/07/19/running-phpunit-on-vvv-from-phpstorm-9/). I'm going to close this issue out with the knowledge that it's possible. :+1:
