### ISSUE TITLE
vagrant-goodhosts stalls when the /etc/hosts file has too many entries. 

### ISSUE THREAD

**Issue by conradolandia** [Varying-Vagrant-Vagrants/VVV#2541]
## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

I block malware sites and ads from the internet using a large `hosts` file (600.000+ lines), redirecting all these bad hosts to 0.0.0.0. When I try to install, `vagrant-goodhosts` just freezes and the install process won't go on. If I remove most of the entries form /etc/hosts, the process completes without problems. 

## Possible Solution
Make a backup of the big `hosts` file, make a new one with only the basic entries, run the installer, copy VVV generated address to the big file, move it again as the system `hosts` file.

## Steps to Reproduce (for bugs)
1. Create a very big hosts file, using a tool like https://github.com/StevenBlack/hosts
2. Try to run the installer. 

## Your Environment

```shell
__ __ __ __
\ V\ V\ V / v3.7.2 Path:"/home/vantta/vvv-local"
 \_/\_/\_/  git::develop(95af544)

Platform: linux shell:/bin/zsh systemd  vagrant-goodhosts CaseSensitiveFS shared_db_folder_disabled
Vagrant: v2.2.18, virtualbox: v6.1.26

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Current machine states:

default                   running (virtualbox)
```

**Comment by tomjn** [comment]
be sure to include the version you used off the plugin, you'll also want to figure out if it's goodhosts itself or the vagrant plugin ( the plugin makes DNS requests to avoid updating the hosts file and asking for a root pass if no changes are necessary )
