### ISSUE TITLE
default wordpress sites don't respond with HTTP 404

### ISSUE THREAD

**Issue by bkalish** [Varying-Vagrant-Vagrants/VVV#2543]
Both of the default Wordpress sites (one.wordpress.test and two.wordpress.test) failed to load the 404.php template in these when they should, instead they show the index page.

For example http://two.wordpress.test/adsfadsfads/ should give 404, but does not.

I'm not sure if this is a bug or a deliberate configuration issue, but I'd love to get real 404s so that I can test the 404.php in my theme!

OS: macOS 11.6
Vagrant: 2.2.18
VVV: v3.7.2

**Comment by bkalish** [comment]
That worked, thanks!

**Comment by benlumia007** [comment]
closing the ticket...
