### ISSUE TITLE
VirtualBox v6.1.28 issues, All sites timing out

### ISSUE THREAD

**Issue by ollybowman** [Varying-Vagrant-Vagrants/VVV#2549]
All sites are timing out when I try to view them in the browser.

I've just updated vagrant, vvv and virtualbox and it was all working fine beforehand.

I've checked the hosts file and the dns entries are there.

There doesn't appear to be any issues when provisioning. 

The VM is definitely running because I can SSH into it. 

I've destroyed the box, updated it and re-provisioned.

Not really sure why this isn't working, does anyone know what's going on? 

Here's the log file [provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/7437007/provisioner-main.log)

**Comment by chrisjimallen** [comment]
I am on 6.1.29 on Arch. Oddly I have also tried it on Manjaro with the same version as @ollybowman (6.1.28) and it works fine.

**Comment by tomjn** [comment]
Closing this as it's not a VVV issue, it's a VirtualBox issue.

If you have this issue:

 - downgrade to VirtualBox 6.1.24 ( you will need to uninstall VirtualBox and reboot first, the restart is necessary )
 - or wait for a newer version of VirtualBox in hopes they fixed the problem
 - or use a different provider, e.g. Parallels
