### ISSUE TITLE
vagrant up fails on Parallels and Apple M1

### ISSUE THREAD

**Issue by av3nger** [Varying-Vagrant-Vagrants/VVV#2551]
### Are you using the latest stable or develop branch version of VVV?

Yes (develop)

### Is it a new VVV or an existing VVV that used to work?

Existing, worked but now broken

### Whats the problem?

Parallels Desktop 17.1.0
Vagrant 2.2.18 with vagrant-parallels (2.2.4) plugin

Updating Parallels Tools on the guest system breaks the VM.

Setting `v.update_guest_tools` to `false` in Vagrantfile fixes the issue.

### How do we reproduce it?

- Provision a VM with Parallels
- Halt/start the VM a few times to trigger the guest tools to update on the host

### VVV Status screen

```shell
Vagrant was unable to mount Parallels Desktop shared folders. This is usually
because the filesystem "prl_fs" is not available. This filesystem is
made available via the Parallels Tools and kernel module.
Please verify that these guest tools are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t prl_fs -o share,uid=1000,gid=33,_netdev srv_www /srv/www
```

### Which Operating System are you using?

Apple MacOS

### Which provider are you using?

Parallels

**Comment by tomjn** [comment]
@av3nger do you have the full output?

Also:

 - was this a fresh provision in a fresh folder?
 - did you try to copy a VVV folder from an Intel Mac?
 - Which MacOS? 12.01? 11?
 - Do you have the parallels vagrant plugin installed?
 - Is this using the `develop` branch or the `stable` branch?

**Comment by tomjn** [comment]
Also congrats! You were the first person to use the fancy new issue template thing with the UI controls, any feedback on the questions it asked or the options is welcome

**Comment by av3nger** [comment]
@tomjn ,

Which log file do you need for the output?

> was this a fresh provision in a fresh folder?
Yes

> did you try to copy a VVV folder from an Intel Mac?
Don't think so. I was testing a default setup with only 1 site. And I can replicate this after doing `vagrant destroy` and following the replication steps.

> Which MacOS? 12.01? 11?
12.0.1

> Is this using the develop branch or the stable branch?
develop (I am a few commits behind though)

> Also congrats! You were the first person to use the fancy new issue template thing with the UI controls, any feedback on the questions it asked or the options is welcome
Thanks. It was super easy. I'd add the M1 architecture to the OS list. And add a field (or a note) to list the OS, vagrant, plugins versions.

**Comment by av3nger** [comment]
I might have jumped to conclusions in my initial bug report. I wanted to get the full `vagrant up` output log, so I updated the guest tools, reloaded vagrant... and it didn't break. But I found another way to break it, consistently this time.

`uname -r
5.4.0-65-generic`

`apt update && apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  distro-info libjcat1 linux-image-5.4.0-90-generic linux-modules-5.4.0-90-generic linux-modules-extra-5.4.0-90-generic
The following packages have been kept back:
  fwupd fwupd-signed
The following packages will be upgraded:
  libargon2-1 libfwupd2 libfwupdplugin1 libidn2-0 libpcre3 libxml2 libzstd1 linux-image-generic ubuntu-advantage-tools
9 upgraded, 5 newly installed, 0 to remove and 2 not upgraded.
Need to get 70.6 MB of archives.
After this operation, 349 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 libpcre3 arm64 2:8.44-2+ubuntu20.04.1+deb.sury.org+1 [217 kB]
Get:2 http://tw.ports.ubuntu.com/ubuntu-ports focal/main arm64 distro-info arm64 0.23ubuntu1 [16.7 kB]
Get:3 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 ubuntu-advantage-tools arm64 27.3~20.04.1 [778 kB]
Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 libidn2-0 arm64 2.3.0-1+ubuntu20.04.1+deb.sury.org+2 [68.0 kB]
Get:5 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libjcat1 arm64 0.1.3-2~ubuntu20.04.1 [24.2 kB]
Get:6 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libfwupd2 arm64 1.5.11-0ubuntu1~20.04.2 [74.2 kB]
Get:7 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 libzstd1 arm64 1.4.8+dfsg-2+ubuntu20.04.1+deb.sury.org+4 [283 kB]
Get:8 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libfwupdplugin1 arm64 1.5.11-0ubuntu1~20.04.2 [116 kB]
Get:9 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 linux-modules-5.4.0-90-generic arm64 5.4.0-90.101 [15.2 MB]
Get:10 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 libargon2-1 arm64 0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1 [18.6 kB]
Get:11 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 libxml2 arm64 2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1 [636 kB]                 
Get:12 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 linux-image-5.4.0-90-generic arm64 5.4.0-90.101 [10.6 MB]                    
Get:13 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 linux-modules-extra-5.4.0-90-generic arm64 5.4.0-90.101 [42.6 MB]            
Get:14 http://tw.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 linux-image-generic arm64 5.4.0.90.94 [2,556 B]                              
Fetched 70.6 MB in 17s (4,227 kB/s)                                                                                                                  
Preconfiguring packages ...
(Reading database ... 87701 files and directories currently installed.)
Preparing to unpack .../libpcre3_2%3a8.44-2+ubuntu20.04.1+deb.sury.org+1_arm64.deb ...
Unpacking libpcre3:arm64 (2:8.44-2+ubuntu20.04.1+deb.sury.org+1) over (2:8.39-12build1) ...
Setting up libpcre3:arm64 (2:8.44-2+ubuntu20.04.1+deb.sury.org+1) ...
(Reading database ... 87701 files and directories currently installed.)
Preparing to unpack .../libidn2-0_2.3.0-1+ubuntu20.04.1+deb.sury.org+2_arm64.deb ...
Unpacking libidn2-0:arm64 (2.3.0-1+ubuntu20.04.1+deb.sury.org+2) over (2.2.0-2) ...
Setting up libidn2-0:arm64 (2.3.0-1+ubuntu20.04.1+deb.sury.org+2) ...
(Reading database ... 87724 files and directories currently installed.)
Preparing to unpack .../libzstd1_1.4.8+dfsg-2+ubuntu20.04.1+deb.sury.org+4_arm64.deb ...
Unpacking libzstd1:arm64 (1.4.8+dfsg-2+ubuntu20.04.1+deb.sury.org+4) over (1.4.4+dfsg-3ubuntu0.1) ...
Setting up libzstd1:arm64 (1.4.8+dfsg-2+ubuntu20.04.1+deb.sury.org+4) ...
Selecting previously unselected package distro-info.
(Reading database ... 87724 files and directories currently installed.)
Preparing to unpack .../00-distro-info_0.23ubuntu1_arm64.deb ...
Unpacking distro-info (0.23ubuntu1) ...
Preparing to unpack .../01-ubuntu-advantage-tools_27.3~20.04.1_arm64.deb ...
Unpacking ubuntu-advantage-tools (27.3~20.04.1) over (20.3) ...
Preparing to unpack .../02-libargon2-1_0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1_arm64.deb ...
Unpacking libargon2-1:arm64 (0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1) over (0~20171227-0.2) ...
Selecting previously unselected package libjcat1:arm64.
Preparing to unpack .../03-libjcat1_0.1.3-2~ubuntu20.04.1_arm64.deb ...
Unpacking libjcat1:arm64 (0.1.3-2~ubuntu20.04.1) ...
Preparing to unpack .../04-libfwupd2_1.5.11-0ubuntu1~20.04.2_arm64.deb ...
Unpacking libfwupd2:arm64 (1.5.11-0ubuntu1~20.04.2) over (1.3.11-1~focal1) ...
Preparing to unpack .../05-libfwupdplugin1_1.5.11-0ubuntu1~20.04.2_arm64.deb ...
Unpacking libfwupdplugin1:arm64 (1.5.11-0ubuntu1~20.04.2) over (1.3.11-1~focal1) ...
Preparing to unpack .../06-libxml2_2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1_arm64.deb ...
Unpacking libxml2:arm64 (2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1) over (2.9.10+dfsg-5ubuntu0.20.04.1) ...
Selecting previously unselected package linux-modules-5.4.0-90-generic.
Preparing to unpack .../07-linux-modules-5.4.0-90-generic_5.4.0-90.101_arm64.deb ...
Unpacking linux-modules-5.4.0-90-generic (5.4.0-90.101) ...
Selecting previously unselected package linux-image-5.4.0-90-generic.
Preparing to unpack .../08-linux-image-5.4.0-90-generic_5.4.0-90.101_arm64.deb ...
Unpacking linux-image-5.4.0-90-generic (5.4.0-90.101) ...
Selecting previously unselected package linux-modules-extra-5.4.0-90-generic.
Preparing to unpack .../09-linux-modules-extra-5.4.0-90-generic_5.4.0-90.101_arm64.deb ...
Unpacking linux-modules-extra-5.4.0-90-generic (5.4.0-90.101) ...
Preparing to unpack .../10-linux-image-generic_5.4.0.90.94_arm64.deb ...
Unpacking linux-image-generic (5.4.0.90.94) over (5.4.0.65.68) ...
Setting up distro-info (0.23ubuntu1) ...
Setting up linux-modules-5.4.0-90-generic (5.4.0-90.101) ...
Setting up libargon2-1:arm64 (0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1) ...
Setting up linux-image-5.4.0-90-generic (5.4.0-90.101) ...
I: /boot/vmlinuz is now a symlink to vmlinuz-5.4.0-90-generic
I: /boot/initrd.img is now a symlink to initrd.img-5.4.0-90-generic
Setting up libjcat1:arm64 (0.1.3-2~ubuntu20.04.1) ...
Setting up ubuntu-advantage-tools (27.3~20.04.1) ...
Installing new version of config file /etc/logrotate.d/ubuntu-advantage-tools ...
Installing new version of config file /etc/ubuntu-advantage/uaclient.conf ...
Created symlink /etc/systemd/system/multi-user.target.wants/ua-reboot-cmds.service → /lib/systemd/system/ua-reboot-cmds.service.
Created symlink /etc/systemd/system/timers.target.wants/ua-timer.timer → /lib/systemd/system/ua-timer.timer.
Created symlink /etc/systemd/system/multi-user.target.wants/ua-license-check.path → /lib/systemd/system/ua-license-check.path.
Setting up libxml2:arm64 (2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1) ...
Setting up linux-modules-extra-5.4.0-90-generic (5.4.0-90.101) ...
Setting up libfwupd2:arm64 (1.5.11-0ubuntu1~20.04.2) ...
Setting up libfwupdplugin1:arm64 (1.5.11-0ubuntu1~20.04.2) ...
Setting up linux-image-generic (5.4.0.90.94) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for linux-image-5.4.0-90-generic (5.4.0-90.101) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.4.0-90-generic
Error! Your kernel headers for kernel 5.4.0-90-generic cannot be found.
Please install the linux-headers-5.4.0-90-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.4.0-90-generic
flash-kernel: deferring update (trigger activated)
/etc/kernel/postinst.d/zz-flash-kernel:
flash-kernel: deferring update (trigger activated)
/etc/kernel/postinst.d/zz-update-grub:
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.4.0-90-generic
Found initrd image: /boot/initrd.img-5.4.0-90-generic
Found linux image: /boot/vmlinuz-5.4.0-65-generic
Found initrd image: /boot/initrd.img-5.4.0-65-generic
Adding boot menu entry for UEFI Firmware Settings
done
Processing triggers for flash-kernel (3.103ubuntu1~20.04.3) ...
Unsupported platform on EFI system, doing nothing.`

`vagrant reload
__ __ __ __
\ V\ V\ V / v3.7.2 Path:"/Users/vanyukov/vagrant-local"
 \_/\_/\_/  git::develop(69d6f31)

Platform: darwin19 shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.2.18, parallels: v17.1.0

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

 ⚠ ! Running additional Vagrant code in Customfile located at /Users/vanyukov/vagrant-local/Customfile
 ⚠ ! Official support is not provided for this feature, it is assumed you are proficient with vagrant

 ⚠ ! Finished running Customfile, resuming normal vagrantfile execution

==> default: Running action triggers before reload ...
==> default: Running trigger: VVV Pre-Reload...
    default: Running: inline script
    default:    .  ★         ☁           ★          .
    default: Z        ☽    ★         .        ☁
    default:  Z ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄   ★            __★__ __ __
    default: ☁ z█▒▒░░░░░░░░░▒▒█    Sleep tight \ V\ V\ V /
    default:  ★  █░░▁░░░░░▁░░█  ★               \_/\_/\_/
    default:    . █░░░▀█▀░░░█ .          ★
    default:  ★   ▀▄░░░░░░░▄▀  ★     .
    default: 
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 wp.test
==> default: [vagrant-goodhosts] Checking for host entries
==> default: Attempting graceful shutdown of VM...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
    default: Adapter 1: hostonly
==> default: Clearing any previously set network interfaces...
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.6:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools were not detected on this VM! They are required
==> default: for shared folders, time sync and more. If shared folders are not
==> default: working on this machine, please install Parallels Tools within the
==> default: virtual machine and reload your VM.
==> default: Installing the proper version of Parallels Tools. This may take a few minutes...
==> default: Parallels Tools have been installed. Rebooting the VM...
==> default: Attempting graceful shutdown of VM...
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: Warning: Connection refused. Retrying...
==> default: Machine booted and ready!
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /srv/www => /Users/vanyukov/vagrant-local/www
Vagrant was unable to mount Parallels Desktop shared folders. This is usually
because the filesystem "prl_fs" is not available. This filesystem is
made available via the Parallels Tools and kernel module.
Please verify that these guest tools are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t prl_fs -o share,uid=1000,gid=33,_netdev srv_www /srv/www

The error output from the command was:

mount: /srv/www: unknown filesystem type 'prl_fs'.`

I am still able to SSH to the VM.
`uname -r
5.4.0-90-generic`

I guess it has something to do with the new kernel?

**Comment by tomjn** [comment]
> Which log file do you need for the output?

Full output of the vagrant command that failed in the `terminal` with no omissions, a lot of the "fluff" actually has debug data in it

```
 ⚠ ! Running additional Vagrant code in Customfile located at /Users/vanyukov/vagrant-local/Customfile
 ⚠ ! Official support is not provided for this feature, it is assumed you are proficient with vagrant

 ⚠ ! Finished running Customfile, resuming normal vagrantfile execution
```

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

What's probably happened is that the customfile contains code that only works on VirtualBox. Parallels shares require different parameters. Someone else in the VVV slack had this when they tried to setup an environment that had additional shared folders via a customfile on an M1 machine only for it to fail mounting folders as no Parallels overrides were in place

**Comment by av3nger** [comment]
@tomjn , it's not the Customfile. I can replicate without the Customfile and the steps I outlined above (updating the packages).

**Comment by tomjn** [comment]
Technically I should close this as `wontfix` because of the customfile, but that files contents are definitely significant even if you remove it and reprovision, please share the files contents

**Comment by av3nger** [comment]
Sure, here's the content of Customfile:
```
config.vm.synced_folder '/dev/plugin', '/srv/www/wordpress/public_html/wp-content/plugins/plugin', owner: 'vagrant', group: 'www-data', mount_options: [ 'share' ]
```
But, like I said, you can replicate it without the Customfile

**Comment by tomjn** [comment]
and `v.update_guest_tools` set to `false` still reliably fixes it? @evertiro have you encountered this? Should we just make the change?

**Comment by av3nger** [comment]
No, it doesn't fix the problem, unfortunately. Now that I've been debugging this, I think the problem has something to do with the kernel update and the guest tools, specifically this:
```
Processing triggers for linux-image-5.4.0-90-generic (5.4.0-90.101) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.4.0-90-generic
Error! Your kernel headers for kernel 5.4.0-90-generic cannot be found.
Please install the linux-headers-5.4.0-90-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located
   ...done.
```
Even though the parallel tools seem to have been upgraded:
```
tail /var/log/parallels-tools-install.log
update-initramfs: Generating /boot/initrd.img-5.4.0-65-generic
installer:%80.000000
Send installed Parallels Tools version to dispatcher.
installer:%90.000000
>>> Postinstall
Writing OS version and Xorg version
Enabling PRL_GL
Starting prltoolsd service:
installer:%100.000000
Parallels Guest Tools were upgraded successfully!
```
And:
```
prlctl list -i `cat .vagrant/machines/default/parallels/id` | grep GuestTools
GuestTools: state=possibly_installed version=17.1.0-51516
```
I don't think they actually have been updated properly. Because I am not able to mount anything on the system:
```
sudo mount -t prl_fs -o share,uid=1000,gid=33,_netdev srv_www /srv/www
mount: /srv/www: unknown filesystem type 'prl_fs'.
```
It also doesn't look like the linux-headers-5.4.0-90-generic package is installed. If I install it manually then manually upgrade the guest tools, it starts to work again.

**Comment by tomjn** [comment]
hmm I'm not super familiar with Parallels kernel extensions but is there a way to check they're loaded and compiled in to the new kernel the same way `kextload` on MacOS does?

**Comment by tomjn** [comment]
There's also a longshot of trying this box instead:

https://app.vagrantup.com/mpasternak/boxes/focal64-arm

Using the box parameter in `config.yml` will do it, but you'll need to destroy the VM and the `.vagrant` folder first, no guarantee that box will behave. When we went with `rueian/ubuntu20-m1` it didn't have alternatives but that's not quite the case anymore

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2552 may or may not be helpful

**Comment by av3nger** [comment]
@tomjn , I ran some more tests and I was able to fix by adding `linux-headers-generic` to `VVV_PACKAGE_LIST` in file `provision/core/vvv/provision.sh`.

That is not optimal, because for me it pulled in at least three extra packages: `linux-headers-5.4.0-90-generic`, `linux-headers-5.4.0-90` and `linux-headers-generic` (not even sure why it's pulling in the 5.4.0-90 headers for 5.4.0-65 kernel). Is there, maybe, a way to check for the parallels vm provider inside the `provision.sh` file and conditionally add the package? Or even better - detect updates to the parallels guest tools and check for the specific package there?

**Comment by tomjn** [comment]
@av3nger does the new box also need the package adding?

**Comment by evertiro** [comment]
I haven't seen that issue yet, but I've also been waiting for the official inclusion of an M1 build image (it's supposed to be happening) before running updates. I can take a look though

**Comment by av3nger** [comment]
@tomjn , the new box does not require the package adding. So far everything I've done on it, including package updates - no issues at all

**Comment by evertiro** [comment]
Note, the ticket tracking official support for M1 is https://github.com/chef/bento/pull/1374. The update has been merged, but not pushed to the cloud as of yet.

**Comment by tomjn** [comment]
@av3nger if I can get an approval on the PR then I'm happy to merge it, just so we're explicit that my changes work before they're merged and there's nothing silly like typos

**Comment by av3nger** [comment]
@tomjn , I didn't test the part with
`if Etc.uname[:version].include? 'ARM64'`
But the new vm box definitely works without any issues for me

**Comment by evertiro** [comment]
Is there an actual PR for this? It's not linked anywhere in the ticket I'm seeing (I could totally be blind though).

**Comment by av3nger** [comment]
@evertiro, it's already merged to develop branch
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2552

**Comment by tomjn** [comment]
unless you meant for the bento box? I'm goin to close this out for now a things got merged
