### ISSUE TITLE
Digital Ocean MariaDB Mirrors

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2553]
They broke them, and I've removed them for now but this leaves us with a single apt mirror for MariaDB in Japan which is.. suboptimal

**Comment by tomjn** [comment]
also if you're on `stable` and having issues with this, switch to `develop`

**Comment by thomasdebruin** [comment]
@tomjn thnx! (a lot) latest develop branch with the singe mirror seems the solution

**Comment by rtpHarry** [comment]
I think this is what I've just been experiencing:

```
    default: Reading package lists...
    default: E: The repository 'http://ams2.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal Release' does not have a Release file.
    default: E: The repository 'http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.5/ubuntu focal Release' does not have a Release file.
    default: E: The repository 'http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal Release' does not have a Release file.
    default: E: The repository 'http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal Release' does not have a Release file.
    default:  ! The 'main' provisioner ran into problems, the full log is available at '/var/log/provisioners/2021.11.11_00-35-40/provisioner-main.log'. It completed in 16 seconds.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I just switched to develop and then tried `vagrant up --provision` but i'm still getting the same issue:

![image](https://user-images.githubusercontent.com/1038062/141290674-b7ffa91d-35c8-4f75-b7b4-03b6ec3d9e96.png)

How do I flush the system?

I've double checked I've got the latest version:

![image](https://user-images.githubusercontent.com/1038062/141291001-ba3d3c93-8a50-42e9-94bf-0d201b1bc83b.png)

**Comment by rtpHarry** [comment]
I've also just tried rebooting but that hasn't improved things. It's still trying to load the commented out mirrors.

**Comment by tomjn** [comment]
@rtpHarry how old is your VVV environment? We haven't used ukfast in a long time

**Comment by tomjn** [comment]
it's likely there was an older apt source file or other modifications but we can't debug that now the VM has been destroyed

**Comment by tomjn** [comment]
Most userss should be fine with:

```sh
git checkout develop
git pull
vagrant up --provision
```

**Comment by rtpHarry** [comment]
Ahh yeah it was old, originally when I started looking into the bug it was still on `Ubuntu 18.04.6 LTS (Bionic Beaver)`.

I always end up losing about half a day or more whenever I touch anything related to this so if it works, I leave it alone :)

Thanks for your prompt support as always.

**Comment by rafaelcalero** [comment]
@tomjn the mirror http://ftp.yz.yamagata-u.ac.jp is down right now :(

**Comment by tomjn** [comment]
You are using an out of date version of VVV, upgrade to 3.8

**Comment by rafaelcalero** [comment]
Yes, sorry, I updated git but I forgot to clean and update plugins before provision. My fault :-)

**Comment by tomjn** [comment]
I'm going to close this out now as both develop/stable use the rackspace mirror instead of digital ocean or the Japanese university
