### ISSUE TITLE
Sites Inaccessible - Just Timing Out

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#2554]
## What was The Command Used To Provision

```shell
vagrant destroy
vagrant up
```

## What Kind of VVV Provision Was This

This was an attempt to upgrade to a new version of VVV

## Logs/What Broke
The system broke on the Monterey update. 

I've updated to the latest versions of everything, and switched to develop branch for the mariadb issue, but now all of my wp sites are broken and none of the domains are even responding, they are just timing out.

Looking in the logs I can see this, for every wordpress site it is attempting to provision:

```
    default:  ▷ Running the 'site-emprocom' provisioner...
    default:  * Pulling down the master branch of https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    default: From https://github.com/Varying-Vagrant-Vagrants/custom-site-template
    default:  * branch            master     -> FETCH_HEAD
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
    default: sudo: wp: command not found
```

I've switched back to stable branch, commented out the mirrors myself, and reprovisioned. The provision doesn't have that error any more.

However, I cannot access any of the sites still, they just time out.

If I run it with the default configuration, it complains about the ip:

```
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.

  Address: 192.168.50.4
  Ranges: 192.168.56.0/21

Valid ranges can be modified in the /etc/vbox/networks.conf file. For
more information including valid format see:

  https://www.virtualbox.org/manual/ch06.html#network_hostonly
```

So I've added this to the config.yaml:

```yaml
vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 12288
  # CPU cores:
  cores: 12

  # custom tweak by matthew
  # https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1605
  private_network_ip: 192.168.56.0
```

And it appears to load, but nothing is accessible. For example trying http://vvv.test gives:

```
This site can’t be reached
vvv.test took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT
```

I don't know what else to try.

I am cursed with this development setup, literally every time I touch anything I lose a day of development. I'm trying to learn but it just takes hours and hours every time.

Does anyone have any ideas as to what this could be?

## Your Environment

```
__ __ __ __
\ V\ V\ V / v3.7.2 Path:"/Users/matthewharris/rtp/rtpDesign/localDev"
 \_/\_/\_/  git::stable(fe4a401)

Platform: darwin19 shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.2.19, virtualbox: v6.1.29
```

**Comment by tomjn** [comment]
> The system broke on the Monterey update.

This is a known issue with VirtualBox + Monterey, and also happens irregularly in v6.1.26 and v6.1.28.

 - feedback that this is happening on the virtualbox ticket ( I get the feeling that the one person who it gets fixed for is being taken as everybody gets it fixed, when actually it still impacts a lot of people )
 - then either wait for newer 6.1.29 test releases or downgrade to Big Sur, or use an alternative provider such as Parallels or VMWare

Right now there is no known good configuration for MacOS 12, proceed with Monterey with caution, here be dragons. There is nothing that can be done from the VVV side of things

**Comment by tomjn** [comment]
At this point, aside from reporting to VirtualBox that it's still an issue with the latest .29 release, I'd suggest downgrading back to Big Sur

**Comment by rtpHarry** [comment]
OMG I BEAT THE DRAGONS!

OK so these are the steps should anyone else foolishly update to Monterey.

Firstly you need to be on the .29 release, or you will have the headless issue which is being discussed [in many places](url).

It's not out yet but it can be found here:

  - https://www.virtualbox.org/ticket/20636#comment:23
  - https://www.virtualbox.org/download/testcase/VirtualBox-6.1.29r148140.dmg

(You must use this version as its a special one that has been notarized. Otherwise you will have another issue where you will have to [manually load the kext each time you boot](https://www.virtualbox.org/ticket/20636#comment:18))

Secondly, since .26 there was a [change to how the hosts works](https://www.virtualbox.org/ticket/20626#comment:3). 

It wants you to set it within an IP range, which I posted my error above.

I tried setting it to the requested IP range but I think there is some other bug that isn't mapping it properly.

However, you can create a `/etc/vbox/networks.conf` to let you go back to the original IP default range:

  - https://www.virtualbox.org/manual/ch06.html#network_hostonly

(I had to create the vbox folder and the conf file)

I put in the following contents:

```
* 0.0.0.0/0 ::/0
```

After that I did:

```
vagrant halt
vagrant up
```

And everything started working finally!

**Comment by tomjn** [comment]
hmmm re: IPs what should we do? Modifying that file isn't feasible for 99% of users going forward, does vagrant 2.2.19 fix this or does it throw up a warning about it? We don't set an IP unless the config specifies it right now

**Comment by rtpHarry** [comment]
I don't know, but there was some discussion here about the "why" of it:

https://www.virtualbox.org/ticket/20626#comment:8

It seems like letting the setting be internal is considered a bad practice:

> To answer the reasonable request for explaining the purpose: It moves the system wide network config powers back under the control of the administrator where it always should have been. In quite a few organization there is strict control over network resources, and in a way the VirtualBox users have become used to getting some "whole OS visible" network config power without needing administrator privileges.
>
> The "edit a file in /etc" solution might not be elegant, but it does the job and it is actually in my opinion much more "KISS" then having some separate (because VirtualBox overall does not need admin privileges) GUI utility which allows configuring this after authenticating as administrator. Especially if all you want is giving any VirtualBox user the permission to create arbitrary host-only configs. The documentation provides examples what to do.

I don't know what it means for automating setup though.

Like I said above, I believe that it should honor the `private_network_ip` setting, to move the system over to the IP address it now deems acceptable, but there seems to be a bug?

I'm out of my depth here really, because I don't know what the baseline correct behaviour even should be, so I don't know what has changed, and what isn't working as it should.

**Comment by tomjn** [comment]
@rtpHarry the latest vagrants error message gives better clues, I've changed `develop` to use `56` rather than `50` for the IP which might resolve that issue without needing to update system files

**Comment by tssmitty** [comment]
@rtpHarry Thanks for this!
