### ISSUE TITLE
VVV stopped working after updating to VVV 3.8.1 and Vagrant 2.2.19

### ISSUE THREAD

**Issue by csdev-nl** [Varying-Vagrant-Vagrants/VVV#2558]
### Are you using the latest stable or develop branch version of VVV?

Yes (develop)

### Is it a new VVV or an existing VVV that used to work?

Existing, worked but now broken

### Whats the problem?

I can't run my VVV setup anymore after I have updated to VVV 3.8.1 and Vagrant 2.2.19. When updating the local plugins, I get the following error message:

`
from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:441:in 'realpath'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:441:in 'realpath': No such file or directory @ rb_check_realpath_internal - /Users/####/Development/vagrant/.vagrant/plugins/gems/2.7.4 (Errno::ENOENT)
`

### How do we reproduce it?

Update to VVV 3.8.1 and Vagrant 2.2.19.

### VVV Status screen

```shell
__ __ __ __
\ V\ V\ V / v3.8.1 Path:"/Users/####/Development/vagrant"
 \_/\_/\_/  git::develop(0a2accc)

Platform: darwin19 shell:/bin/bash vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.2.19, virtualbox: v6.1.16
```

### Which Operating System are you using?

Apple MacOS (Big Sur)

### Which provider are you using?

VirtualBox

**Comment by csdev-nl** [comment]
Update: I ran `vagrant plugin repair --local` and I can now update the plugins (obviously it is only vagrant-goodhosts). However, my VM still won't run. I get a `ERR_CONNECTION_TIMED_OUT` message in Chrome, which would imply some DNS mismatch. The VM is running fine, but is not reachable.

**Comment by csdev-nl** [comment]
Update 2: right, so I found the problem: in my hosts file there were references to `192.168.50.4` and `192.168.56.4`. When I removed the reference to `192.168.50.4` everything started working again.

**Comment by tomjn** [comment]
looks like your VM was still running when you updated, so the old IP was never removed

**Comment by tomjn** [comment]
I'm closing this, if there are any updates or changes feel free to reopen.

Otherwise, if you have this issue, open your hosts file and remove the VVV entries then `vagrant halt && vagrant up`
