### ISSUE TITLE
Bug: vagrant up --provider=parallels

### ISSUE THREAD

**Issue by sverdier** [Varying-Vagrant-Vagrants/VVV#2559]
### Are you using the latest stable or develop branch version of VVV?

Yes (develop)

### Is it a new VVV or an existing VVV that used to work?

New fresh install

### Whats the problem?

vagrant up --provider=parallels =>

Vagrant failed to initialize at a very early stage:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

### How do we reproduce it?

vagrant up --provider=parallels

### VVV Status screen

```shell
vagrant up --provider=parallels
__ __ __ __
\ V\ V\ V / v3.8.1 Path:"/Users/sverdier/Documents/data/sites/azeoo/VVV-develop 2"
 \_/\_/\_/  zip-no-vcs

Vagrant failed to initialize at a very early stage:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

### Which Operating System are you using?

Apple MacOS

### Which provider are you using?

Parallels

**Comment by tomjn** [comment]
Hello!

> `zip-no-vcs`

Brave!! Installing this by downloading a zip will make it 100x harder to upgrade VVV if there are updates and bug-fixes. We recommend using the `git` command because it's easy and you can copy paste the command without knowing anything about it. You appear to have chosen the ultra hard mode difficulty option.

MacOS should come with a copy of git you can install it the recommended way by copy pasting the command. You've saved yourself maybe a minute of time in exchange for many hours of pain in the future when something breaks and you can't copy paste `git pull && vagrant up --provision` into the terminal and have it automagically works.


> `--provider=parallels`

Did you install the vagrant parallels provider? I'm assuming you're on an M1 Mac but I notice you haven't mentioned this in your issue?

**Comment by tomjn** [comment]
Can you send me the output of `vagrant plugin list --local`? as well as `uname -m`?

**Comment by webinista** [comment]
I'm having the same issue, also with a fresh install.

- I installed using git, using the stable branch.
- I'm using the latest version of Parallels and Vagrant. 
- I installed the `vagrant-parallels` plugin (I've tried installing it globally and locally).
- M1 Mac; VirtualBox is not an option.

Output of `vagrant plugin list --local`:

```
vagrant-goodhosts (1.1.1, local)
vagrant-parallels (2.2.4, local)
```

Output of `uname -m`:

`arm64`

**Comment by tomjn** [comment]
@webinista if you set the provider to parallels in `config.yml` does that help? Or is the output still the same as what the OP posted?

**Comment by webinista** [comment]
@tomjn Yes! Thank you.

As a how-to for anyone else who reads this, and also doesn't know much about Vagrant and VVV configuration, set the provider by removing the # from the line that contains `provider: parallels`. It's around line 125 of `config/config.yml`.

Also if you receive the message below, you need to purchase a Pro or Business license first.

```
Vagrant failed to initialize at a very early stage:

translation missing: en.vagrant_parallels.errors.parallels_unsupported_edition
```

**Comment by tomjn** [comment]
@sverdier @webinista can you check #2560? With that change in theory you can provision without `--provider=parallels` and without the change to `config.yml`

**Comment by webinista** [comment]
@tomjn It works!

**Comment by adamwoodnz** [comment]
> Also if you receive the message below, you need to purchase a Pro or Business license first.

Or activate the free trial
