### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by av3nger** [Varying-Vagrant-Vagrants/VVV#2572]
Having PHP 8.1 support would be great.

**Comment by tomjn** [comment]
@av3nger can you try out https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/94 and leave some feedback?

**Comment by av3nger** [comment]
Seems to be working without issues. At least, nothing stands out so far

**Comment by tomjn** [comment]
Awesome, closing this out now it's merged
