### ISSUE TITLE
VVV Doc site deployment is broken

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2578]
Our build and deployment steps used the old travis CI .org but that service ended in June 2021. No new doc site updates have occurred since then.

A migration to a new CI deployment process is now necessary, and @jeremyfelt is needed as it's his AWS bucket and domain that serves the site.

Case in point, the empty site example is broken and a fix from August of last year has yet to be deployed because of this.

**Comment by tomjn** [comment]
The easiest route would be to switch to the .com version of Travis but this would mean purchasing credits, and would probably require a new set of secrets and a github application connection

**Comment by tomjn** [comment]
We only stuck with Travis because you set it up and it worked, after all if it's not broke don't fix it. Happy to jettison Travis CI in favor of Github actions, whatever is easiest/cheapest for you :)

**Comment by jeremyfelt** [comment]
Okay. Deployments are "working" after https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/204, https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/commit/5b974718e37d2457c4db7b0ad2921797003524a6 and https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/commit/77a234707b43859dd3c26ba49236890561c294b7

But, I also decided to switch the server it was deploying to, so it will be just a bit while I configure nginx, DNS, and get a cert. Timer starts... now!

**Comment by jeremyfelt** [comment]
And we're a go. DNS propagated very quickly. 😅 

I've removed AWS from the equation because it'd be nice to remove an unnecessary step. I had a proxy setup in nginx, but the cache was only for a few minutes.

If for some reason we ever get slammed with traffic in a surprising way, we can put things behind Cloudflare or something. But for now, deploy away!

Let me know if anything looks broken. 🍻

**Comment by Mte90** [comment]
I see the website working I think that we can wait for a @tomjn approval and close the ticket :-)

**Comment by tomjn** [comment]
Looking good :) thanks for the quick turn around!!
