### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mastef** [Varying-Vagrant-Vagrants/VVV#258]
Oh I just realized I posted this to a fork. It would possibly make more sense to use Docker? ( And Vagrant still as a wrapper for non-unix clients of course )

See the full case for it at : https://github.com/ericmann/vvv-apache/issues/1

**Comment by tannerchung** [comment]
Was getting interested in trying to use docker with VVV and was excitedly reading this comment archive and found that the http://github.com/varying-vagrant-vagrants/vvv-docker is dead. Was this project shut down?
