### ISSUE TITLE
Q: database backup and restore

### ISSUE THREAD

**Issue by JairoJL** [Varying-Vagrant-Vagrants/VVV#2611]
I am trying to update to new version of vagrant like from 2 to 3 but i read it requires like the update that removes everything. is there instructions on how to back up my sites cause i read you need to backup database but i cant find anywhere how and what the command to backup and then restore is i would really like to know! thanks in advance!

**Comment by Mte90** [comment]
So you have an old VVV version or vagrant? I think that in VVV 2 there was already the backup script for the database and that on halt it was generating them.

Otherwsie you can do the old school way, open phpmyadmin and export manually the various databases.

**Comment by JairoJL** [comment]
So how do i export them back after updating to vvv 3? After the whole like removing it to update? Does it auto bring the database or do i have to go in phpadmin and import them?

**Comment by Mte90** [comment]
After updating you need to do a provision so the DB will be created and import again in phpmyadmin.

I don't know what is the VVV version are you using, but consider that VVV has an automatic DB export on halt and on provision if the DB doesn't exists will import them.

**Comment by JairoJL** [comment]
when i try to update to new version and do get pull it gives me error that i cant connect to it
![image](https://user-images.githubusercontent.com/71436058/173145943-6fa63175-4fa2-48bd-93cf-a5bdd14ce774.png)

**Comment by tomjn** [comment]
> when i try to update to new version and do get pull it gives me error that i cant connect to it

@JairoJL we don't maintain `git` or github.com, so there's very little if anything at all that can be done from the VVV end to resolve this. It's likely an issue with your local git setup, such as a bad SSH key, firewall and security software, or a very very out of date copy of `git`

**Comment by tomjn** [comment]
As for the database, stop thinking of VVV as some special case that requires special steps to do this.

If you were moving a site from GoDaddy to WPEngine you would do exactly the same steps. Export the database, then take that export and import it. There are hundreds of ways to do this, plugins, scripts, tools, manual instructions, etc

**Comment by JairoJL** [comment]
okay thank you ive managed to get throught these things
but my problem now is when i try provisioning it gives me this error
![image](https://user-images.githubusercontent.com/71436058/173159755-6afbc567-8aa6-42ca-9d8b-9817bb7287ff.png)

**Comment by JairoJL** [comment]
and i tried searching it but i cant get anywhere with how to fix this

**Comment by tomjn** [comment]
Your screenshot cuts off most of the error but it’s something that was
fixed in VVV 3.9, you need to use the latest stable or develop branches

**Comment by tomjn** [comment]
Closing this as there's been no response in several months. Feel free to reopen if you encounter this again though
