### ISSUE TITLE
Is VVV a good choice for pushing any type of change made on a dev env to a production env ?

### ISSUE THREAD

**Issue by aymeric75** [Varying-Vagrant-Vagrants/VVV#2612]
Hello,

I have a simple question:

On VVV site home page it's said that "VVV is ideal for developing themes and plugins as well as for WordPress core".

But, I want to have a local development version of my client Wordpress Site and when I make **any change** **(even only installing a plugin**, or changing some css file, any change), I want to be able to push it to the production environment (on a remote server).

So is VVV a good fit if we want to push other things than manually modified files ? I.e if we want to push the installation/configuration of a plugin/theme on the Wordpress dev environment ?

Thank you

Aymeric

**Comment by Mte90** [comment]
VVV is just a tool to develop locally it's on you  this kind of things. This alert is to avoid that someone use VVV to run officially their website on a server.

**Comment by tomjn** [comment]
@aymeric75 are you talking about pushing content and other things stored in the database? VVV just sets up a server locally on the machine in front of you, it doesn't provide any kind of synchronisation system.

I think you're approaching this wrong, what you're looking for isn't a feature of a local development environment, and would be no different if VVV was a web host you were using to test content on a copy of your site.

> when I make any change (even only installing a plugin, or changing some css file, any change)

If the goal is when _**files**_ change you want it to go to the server, then your question has nothing to do with VVV, that's a solved problem. **Use a git repo. and a webhost that uses git.** Most managed WordPress hosts offer this, and enterprise grade hosting normally depends on it. Make your changes, commit them and push them up, your host auto-deploys the changes. None of this is specific or requires VVV, and can be done without any local host at all.

If you want it to install a plugin on production when you click install locally without any extra steps, then you'd have to build that yourself no matter which local setup you use.

If you're wanting to do this for content in the database, then you will need to find a migration solution, migrating from one server to another, except one of those servers is the computer in front of you. This is true of all local development setups, not just VVV. Plugins have been built to tackle this.

So if you're looking for a local dev setup that perfectly implements what you wanted to do, it does not exist.

**Comment by aymeric75** [comment]
It's more clear now, thanks!
