### ISSUE TITLE
It hasn't worked, I'm getting: Error code: ERR_CONNECTION_REFUSED in Chrome

### ISSUE THREAD

**Issue by jacklenox** [Varying-Vagrant-Vagrants/VVV#262]
I've followed the steps to the letter, when I try to access any of the URLs I'm getting connection refused - this webpage is not available. The hosts records have been added and it otherwise all seems to be working (vagrant ssh etc all fine).

Bit stumped. I've tried halting and re-upping, restarting machine etc. On Mac OS X Mavericks.

**Comment by joelworsham** [comment]
@thisislawatts Thanks!! I had the same issue, and this fixed it.

Though this has been happening more frequently and I'm wondering why it's happening at all.
