### ISSUE TITLE
Bump mariadb 10.5 to mariadb 10.7

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2623]
We need to bump the numbers in the *list files (https://github.com/Varying-Vagrant-Vagrants/VVV/blob/e95f4b70d6eada0486b1d77ed91fa01027e56c6a/provision/core/mariadb/sources-ubuntu-focal.list) and in the provision https://github.com/Varying-Vagrant-Vagrants/VVV/blob/0000e5d0818c55f4cae5427ff9b874fe178cc397/provision/core/mariadb/provision.sh#L11

**Comment by tomjn** [comment]
What's our plan for upgrading those still on 10.5 and 10.4 without breaking things? If we just bump the source to 10.7 it'll break for anyone trying to upgrade on 10.5/4

**Comment by Mte90** [comment]
I see in the past we just changed the repositories https://github.com/Varying-Vagrant-Vagrants/VVV/commit/8d3e208b068a6c77e75cdfbff0d43b86efabc4e0

If we change the package to `mariadb-server` it will always use the latest mariadb version available instead to defining the version and as we are defining the repository for the latest version we want I think that we fix everything.

**Comment by tomjn** [comment]
that's because this is an active outstanding bug that has not been resolved

**Comment by tomjn** [comment]
@Mte90 switching to `mariadb-server` should be a simple swap out though? Even if it doesn't touch this issue it should make upgrades simpler right?

**Comment by Mte90** [comment]
on my experience it is a solution that just works with no problems also with other packages.

**Comment by tomjn** [comment]
now 10.8, as for the problem, we know it happens because people have encountered it and raised issues, no fix was ever implemented for it

**Comment by Mte90** [comment]
I didn't got problems on upgrading the mariadb version so I am not sure about the issues we have right now.

**Comment by tomjn** [comment]
Closing this as the latest `develop` branch uses 10.11 now
