### ISSUE TITLE
Running vagrant up --provision results in 'tools' provisioner running into problems

### ISSUE THREAD

**Issue by jenSadler** [Varying-Vagrant-Vagrants/VVV#2624]
## What was The Command Used To Provision

```vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke
[Gist with config and log](https://gist.github.com/jenSadler/b3bb5be4ed1b5e3f4ae99e64b925e55c )

I've been working on this for a couple of days. I'm not sure what is going on. I have been using fresh installs of vvv, with just the default config files, and I can't get it running. I thought the issue might be due to ssh key issues, but I followed the instructions here: https://stackoverflow.com/questions/22922891/vagrant-ssh-authentication-failure and I believe the ssh keys are working correctly.  

## Possible Solution
My best guess is that there is an issue with versions of the phpcodesniffer plugin. However the file PluginManager.php is referenced and I can't even find that file. I'm not sure what to change to make sure the correct versions are used and I don't get this error.

## Steps to Reproduce (for bugs)

1. Download a fresh copy of virtual box, vagrant and vvv
2. install the local goodhosts plugin
3. vagrant up --provision
4.recieve error

(Gist above

## Your Environment

v3.9.1 Path:"/Users/jennifersadler/vvv-local"
 \_/\_/\_/  git::stable(fabccb8e)

Platform: darwin19 shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.2.19, virtualbox: v6.1.34

(on an imac running  MacOS monterey 12.4)

**Comment by Mte90** [comment]
It is a bug already fixed in `develop` branch from yesterday https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2620

**Comment by shanebp** [comment]
Please specify the steps needed to fix this bug.
For example - start from scratch? 
Or how to run --provision to get the `develop` branch

**Comment by jenSadler** [comment]
I was able to fix it by following these steps: https://varyingvagrantvagrants.org/docs/en-US/installation/ but instead of 

`git clone -b stable https://github.com/Varying-Vagrant-Vagrants/VVV.git ~/vvv-local`

I used:

`git clone -b develop https://github.com/Varying-Vagrant-Vagrants/VVV.git ~/vvv-local`

I made sure there were no running machines on virtual box and then I followed the rest of the steps, ending with 

`vagrant up --provision`

**Comment by tomjn** [comment]
Switch to the develop branch then provision, standard git commands such as
git checkout and git pull will suffice

A complete reinstall from scratch is unnecessary and a last resort, a
thermonuclear option

**Comment by shanebp** [comment]
Thanks all - just finished doing exactly what Jen did.  
Hope the fix gets pushed to stable soon.

**Comment by tomjn** [comment]
3.10.1 is now on `stable` and has the composer fixes as well as others, this should no longer be an issue.
