### ISSUE TITLE
Q: Installation Error

### ISSUE THREAD

**Issue by DatTrannn** [Varying-Vagrant-Vagrants/VVV#2627]
My first installation of Vagrant broke up when I run `vagrant up` for a while. It displayed an error that I have to check in log file
![image](https://user-images.githubusercontent.com/49610104/185823868-2ebcf913-885f-4674-bff0-0532bf4e749d.png)
![image](https://user-images.githubusercontent.com/49610104/185823688-a337ffae-e2c1-4952-b5fc-cc09a537d959.png)
Can you help me to figure it out. 
Thanks

**Comment by tomjn** [comment]
This is a known issue that was fixed on the main `develop` branch months ago

**Comment by tomjn** [comment]
Also, the `%systemdrive%` stuff etc is meant to be swapped out for `C:\` etc so that you'd end up with `C:\Users\ASUS\vvv-local`. You also forgot to include the VVV splash screen which has all the debugging information needed to diagnose problems
