### ISSUE TITLE
Can I instal VVV somewhere besides my home  directory on the system drive? 

### ISSUE THREAD

**Issue by smaction** [Varying-Vagrant-Vagrants/VVV#2629]
My C; drive on a Windows machine  is full. I need to install VVV on my D: drive. Is this possible?

Thanks,

Scott

**Comment by smaction** [comment]
Windows 10 and Vagrant 2.30

**Comment by Mte90** [comment]
It should be enough to move the folder and start again vagrant.

I am not sure anyway where vagrant will place the VM image for caching and also virtualbox.

**Comment by tomjn** [comment]
You can use any folder for VVV but as Daniele says VVV doesn’t determine
the location of the VM itself, you’ll need to configure VirtualBox itself
to use your D drive which is not something we can help you with

**Comment by tomjn** [comment]
The same would be true of Hyper-V if you’re using that as a provider
instead of VirtualBox

**Comment by smaction** [comment]
Thank you to both of you.
