### ISSUE TITLE
Please use secured PPA provisioning

### ISSUE THREAD

**Issue by tlartaud** [Varying-Vagrant-Vagrants/VVV#2631]
Hi there,

VVV is fetching from http://ppa.launchpad.net which is insecure and should fetch from this domain instead: https://ppa.launchpadcontent.net/

I've contacted launchpad to ask them for SSL support for the domain and this is what they answered:
> We can't add HTTPS support to [ppa.launchpad.net](http://ppa.launchpad.net/) due to session cookie security issues on [launchpad.net](http://launchpad.net/), but a while back we added [ppa.launchpadcontent.net](http://ppa.launchpadcontent.net/) which serves the same content and has HTTPS support.  Please use that instead, and/or advise authors of scripts that use [ppa.launchpad.net](http://ppa.launchpad.net/) to switch to the new domain.
> https://blog.launchpad.net/ppa/new-domain-names-for-ppas

Would really appreciate a simple update there :)

Regards.

**Comment by Mte90** [comment]
What version are you using? Because we already did it https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2586

**Comment by tomjn** [comment]
This was resolved in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2607 are you on the `develop` branch?

**Comment by tomjn** [comment]
Closing as 3.10.1 is released and the request has already been fulfilled.

**Comment by tomjn** [comment]
hmm, we can change more places if you can point them out in code, the git ppa is certainly useful to know. Adding firewall restrictions could cause issues for users who add their own extensions, as well as in other places.

VVV isn't a production ready environment or a staging environment, it's a local only environment. We already disable public networking so it can't be accessed via the network.

**Comment by tomjn** [comment]
@tlartaud 

I took a look at the git source you mentioned:

```sh
  if [ "${OSID}" == "Ubuntu" ]; then
    if ! vvv_src_list_has "git-core/ppa"; then
      # Add ppa repo.
      vvv_info " * Adding ppa:git-core/ppa repository"
      add-apt-repository -y ppa:git-core/ppa
      vvv_success " * git-core/ppa added"
    else
      vvv_info " * git-core/ppa already present, skipping"
    fi
  fi
```

There are no references to http://ppa.launchpad.net in the VVV codebase, and it's also worth noting that some of the errors you're getting are for other sources. HTTPS is not the only security measure that prevents MITM attacks here either.

**Comment by tomjn** [comment]
The only place we have http sources at the moment are in the Nodesource provisioner that was disabled and is due for removal. Many of the firewall induced errors you're seeing are from Ubuntu itself

**Comment by tlartaud** [comment]
> HTTPS is not the only security measure that prevents MITM attacks here either

100% agree xD I suffer from this for months, I completely confirm ^^ HTTP requests are all blocked i'm still getting MITM attacked 📦 

> Many of the firewall induced errors you're seeing are from Ubuntu itself
that's what I thought :( I checked the code too and didn't find any http request from VVV. I probably need to point that somewhere else.

Thank you for the fast replies.

**Comment by tomjn** [comment]
it strikes me as odd that adding a ppa would use a http, do you know if there's a way to add it and force the new launchpad HTTPS urls without resorting to manual additions?

Also a longterm compatibility goal is proper debian support so that we have more flexibility with providers and platform support, so we need to keep that in mind.

> 100% agree xD I suffer from this for months, I completely confirm ^^ HTTP requests are all blocked on my computer but i'm still getting MITM attacked 📦

I'm not 100% sure on its maintenance but the vagrant-cachier plugin may be useful to you to grab packages on a known safe connection then cache them later. Are you working over a university/government line? I know some ISP's proxy to cache packages and that's caused issues for some users in India ( connectivity validation and corruption issues )

**Comment by tomjn** [comment]
Also what steps are you taking to adjust VVV's firewall rules? I'd be curious to see
