### ISSUE TITLE
Q: Unable to boot or provision

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#2637]
I've been trying to get my pre-existing vvv setup to start up and have not been able to.

I ended up starting from scratch, but I still get the same type of error seen below:

```
Platform: darwin19 shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.3.2, virtualbox: v7.0.2

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-20.04'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vvv_ae18a058ed7
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp
```

**Comment by tomjn** [comment]
which version of VVV is this? Have you tried rebooting your machine? A missing `vboxnetclt` implies a VBox issue:

 - that VirtualBox has been upgraded but the system hasn't rebooted
 - the kernel extensions for VirtualBox aren't active
 - the VirtualBox install is corrupted somehow

**Comment by tomjn** [comment]
I'm also assuming this is an Intel Mac

**Comment by tomjn** [comment]
This SO answer may also be helpful: https://stackoverflow.com/a/47652517/57482, and the second answer is a good debugging step: https://stackoverflow.com/a/19492976/57482

This may resolve the issue:

```
sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart
```

https://stackoverflow.com/a/69825124/57482

And this might reload the kernel extensions:

```
sudo kmutil load -b org.virtualbox.kext.VBoxUSB
sudo kmutil load -b org.virtualbox.kext.VBoxNetFlt
sudo kmutil load -b org.virtualbox.kext.VBoxNetAdp
sudo kmutil load -b org.virtualbox.kext.VBoxDrv
```

You might need to reboot MacOS. It's frustrating that it requires a reboot even on Windows but never actually tells you.

**Comment by desrosj** [comment]
I've tried using both the `stable` and `develop` branches of VVV.

I'm running
- MacOS 12.15.1 with an Intel chip.
- VirtualBox 7.0.2.
- Vagrant 2.3.2

I've uninstalled and reinstalled VirtualBox and Vagrant. I use homebrew to manage this.

`sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart` I get "command not found" for this command.

The `sudo kmutil` commands and restarting also don't seem to work.

**Comment by desrosj** [comment]
There are a handful of different variations of these commands on that SO question, but they all seem to give the command not found issue.

**Comment by desrosj** [comment]
I uninstalled VirtualBox and reinstalled it using the DMG for 6.1.x from the VirtualBox site this time, but getting the same issue. When I run `kextstat | grep -v com.apple`, I get an empty list. Going to keep trying.

**Comment by tomjn** [comment]
nothing in your system preferences security panel?

**Comment by desrosj** [comment]
Nope. But, I think I have it! No idea what's different, but I uninstalled and reinstalled twice more and after the second time it now works. 🤷🏼‍♂️ It's provisioning now. Will check back when it finishes.

**Comment by desrosj** [comment]
Looks like everything is working as expected now. I'm not really sure what happened or why, but it's working!

Thanks for helping to troubleshoot!
