### ISSUE TITLE
How to use php80 

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2645]
I cannot use php80 for any site. It is loaded during provision, but all sites use PHP Version 7.4.33.
[The log](https://gist.github.com/shanebp/bad7c3617c0f0db1456d1382b850fcf2)
The [config.yml](https://gist.github.com/shanebp/aba1e04a0863d9b5f370b45071c0b755)

**Comment by tomjn** [comment]
Can you re share those gists? It just leads to your main gist page with a
404

**Comment by shanebp** [comment]
Sorry, deleted them because I solved this myself for once.  Please delete this issue.

**Comment by tomjn** [comment]
on the latest VVV it should be as simple as making sure PHP 8 is installed in the extensions section, then adding `php: 8.0` to the site you want to run with PHP 8 and reprovisioning

**Comment by shanebp** [comment]
Thanks for the info.  I was using nginx upstream.
