### ISSUE TITLE
Q: How can I do a clean install and provision with PHP8.0?

### ISSUE THREAD

**Issue by GuiSCI** [Varying-Vagrant-Vagrants/VVV#2663]
I have been trying to set up a new VVV but want it to run PHP8.0 (not PHP7.4) 
In the config.yml I added `php: 8.0` in the sites section and `php80` in the extensions section, as mentioned here:
[https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/changing-php-version/](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/changing-php-version/)
But no luck; the sites are still using PHP7.4 after provisioning. How can I make it work with 8.0?
Thank you!
Gui

**Comment by tomjn** [comment]
did you try this using the stable branch or the develop branch? The information in the bug report and in the placeholder was really important for this!

But also this is a really really common problem that happens a lot and the answer is always the same, this is fixed on the develop branch

**Comment by GuiSCI** [comment]
I copy/pasted from https://varyingvagrantvagrants.org/docs/en-US/installation/ and didn't realize I still had to use the develop branch, sorry. Also there was no bug report; it all worked fine, just was not using PHP8.0.
Anyway, I redid everything with the develop branch and it working now :-)
Thanks again.

<blockquote><img src="https://varyingvagrantvagrants.org/images/vvv.png" width="48" align="right"><div><img src="/images/vvv.png" height="14"> VVV</div><div><strong><a href="https://varyingvagrantvagrants.org/docs/en-US/installation/">Installation</a></strong></div><div>VVV can be installed with git by cloning the main VVV repo into a local directory or by downloading a zip file. Start VVV with ‘vagrant up’.</div></blockquote>

**Comment by tomjn** [comment]
`develop` got merged into `stable` last night! But if you have issues in the future, it's best practice to checkout `develop` to check it hasn't already been fixed
