### ISSUE TITLE
Apple M2 chip compatibility

### ISSUE THREAD

**Issue by columbian-chris** [Varying-Vagrant-Vagrants/VVV#2667]
I'm looking into getting a new MacBook that runs on an M2 chip.  I am a regular VVV user and was wondering if it would work on a machine running that processor?

**Comment by ghost** [comment]
the best way for you to use VVV if you do get a M1/M2 is that you might need to purchase Parallels Desktop Pro since VirtualBox 7.0 does have support M1/M2 but is under dev mode and I don't think it'll work fully with VirtualBox apparently.

**Comment by tomjn** [comment]
You’ll need a copy of parallels pro or business to run VVV on an M1/2 chip.
There are no free options available at the moment to replace virtualbox

Also don’t be fooled by the virtualbox technical preview for Arm, it
struggles to run basic Linux from the 90’s and is years away from being
remotely usable.

As for alternatives that are free we need help, either with vagrant tart or
docker support. Monolithic docker VVV needs help with setting up traefik,
there’s a PR but it relies on a nonstandard network setup that doesn’t work
for me ( M1 Pro )

**Comment by columbian-chris** [comment]
Great information, thank you!

I found [this article](https://www.unixarena.com/2022/09/virtual-machine-on-apple-mac-chip-m1-m2-fusion-vagrant.html/) that suggests you can use VMware Fusion Tech Preview.  Does that sound like a legit option to you guys?

**Comment by ghost** [comment]
Technically you can but VVV is not compatible with ARM processor for VMware Fusion for M1/M2, only Parallels Pro or business at the moment,

**Comment by columbian-chris** [comment]
Alright, I really appreciate the information.

**Comment by ghost** [comment]
sure thing, sorry for the inconvenience

**Comment by tomjn** [comment]
@columbian-chris nobody here has tried VMWare, it might work but you'll need to source an Ubuntu 20 Arm64 box. If you go this route let us know but keep in mind nobody who regularly commits has access to VMWare, VMWare support is only kept because when we try to remove it people come out of the woodwork telling us they still use it
