### ISSUE TITLE
Syntax Error while installing Virtual box in Vagrantfile

### ISSUE THREAD

**Issue by BabaYanga** [Varying-Vagrant-Vagrants/VVV#2673]
Hello,

I am a newbie using Linux. 

I encountered a syntax error while trying to run Vagrant up command 

MACBOOK ubuntu % vagrant up
Vagrant failed to initialize at a very early stage:

This was a fresh install

## Logs/What Broke

I could not run the Vagrant Up command on Mac Terminal due to syntax error related to Network/Proxy settings

## Possible Solution
I hope to input the correct codes to install the vagrant box
Or, to help with network settings  or config. to enable vagrant to run on the Mac terminal

## Your Environment

<CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/ff/2gmtkw4s4_x581s8ljy1vzwh0000gn/T/
XPC_FLAGS=0x0
LaunchInstanceID=5C83E845-E266-4DC7-8072-87FAA3A16801
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.3XbRogu09G/Listeners
SECURITYSESSIONID=186b2
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=443
TERM_SESSION_ID=99C49909-FDE7-4262-9A1B-30BAB72004B8
SHELL=/bin/zsh
HOME=/Users/oluwafemiyanga
LOGNAME=oluwafemiyanga
USER=oluwafemiyanga
PATH=/opt/homebrew/opt/openjdk@11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public
SHLVL=1
PWD=/Users/oluwafemiyanga/Desktop/vms/ubuntu
OLDPWD=/Users/oluwafemiyanga
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
<img width="844" alt="Screen Shot 2023-06-20 at 6 04 49 AM" src="https://github.com/Varying-Vagrant-Vagrants/VVV/assets/136135697/ca18bd2d-8dc2-44de-a666-7e634512997c">

INFOPATH=/opt/homebrew/share/info:
LANG=en_US.UTF-8
_=/usr/bin/env

**Comment by Mte90** [comment]
I am sorry but that Vagrantfile is not the one from VVV.
This isn't Vagrant support you should reach their forum for that.

**Comment by tomjn** [comment]
@BabaYanga I'm curious what made you post here of all places? Where you directed/sent here? Was it a misleading link?

This repo/org is for the VVV local dev environment project, this isn't and never has been a place to get help with personal vagrant files or ask general vagrant questions, and I'd like to prevent these kinds of situations in the future
