### ISSUE TITLE
Q: Vagrant up failure

### ISSUE THREAD

**Issue by mcyzyk** [Varying-Vagrant-Vagrants/VVV#2685]
```
vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-goodhosts (= 1.1.4)'
```

My vagrant-goodhosts plugin has been upgraded to the latest version 1.1.6, but no matter what I do Vagrant is looking for a specific version, the old version, 1.1.4.

Not sure how to remedy!

Mark

**Comment by tomjn** [comment]
Add `--local` to the end of the command, the commands you ran affect globally installed vagrant plugins, but we use `--local` so you don't have to type out the names of all the plugins VVV needs.

Here's the issue and the PR to fix it by mentioning `--local` in the command over at vagrant but they've kind of stalled for some reason:

https://github.com/hashicorp/vagrant/pull/13030

https://github.com/hashicorp/vagrant/issues/13029

**Comment by tomjn** [comment]
The `vagrant plugin expunge --reinstall` command aka `vagrant plugin expunge --reinstall --local`

**Comment by mcyzyk** [comment]
All of the sudden, I'm getting dependency errors with Vagrant plugins.  Realizing this happened a while back, I looked up this Ticket.  Based on it, I run:

`vagrant plugin expunge --reinstall --local`

But no matter what I do, I keep getting the dependency error:

```
Install local plugins (Y/N) [N]: y
Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Vagrant failed to initialize at a very early stage:

Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0
```

Not sure how to remedy if `vagrant plugin expunge --reinstall --local` does not work.

**Comment by mcyzyk** [comment]
All of the sudden, I'm getting dependency errors with Vagrant plugins.  Realizing this happened a while back, I looked up this Ticket.  Based on it, I run:

`vagrant plugin expunge --reinstall --local`

But no matter what I do, I keep getting the dependency error:

```
Install local plugins (Y/N) [N]: y
Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Vagrant failed to initialize at a very early stage:

Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0
```

Not sure how to remedy if `vagrant plugin expunge --reinstall --local` does not work.

**Comment by mcyzyk** [comment]
Same problem, with suggested, temporary solution:
https://github.com/hashicorp/vagrant/issues/13534

`export VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1`

**Comment by tomjn** [comment]
@mcyzyk have you recently updated vagrant? @Mte90 is this a simple bundle update to fix in goodhosts? Or would that fix it for the new version and break it for older versions of vagrant?

**Comment by Mte90** [comment]
What is the plugin issue that creates the issue?
Because our plugin has just `os` has dependency https://github.com/goodhosts/vagrant/blob/main/vagrant-goodhosts.gemspec

<blockquote><img src="https://opengraph.githubassets.com/9472f7ce46cdaa8c25699bb870c9ac3ac43f78747974670c699b209bda582b6f/goodhosts/vagrant" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/goodhosts/vagrant/blob/main/vagrant-goodhosts.gemspec">vagrant/vagrant-goodhosts.gemspec at main · goodhosts/vagrant</a></strong></div><div>Vagrant plugin that use goodhosts to manipulate hosts files - goodhosts/vagrant</div></blockquote>

**Comment by tomjn** [comment]
Don't we have a vagrant dependency? https://github.com/goodhosts/vagrant/blob/main/Gemfile#L5

<blockquote><img src="https://opengraph.githubassets.com/9472f7ce46cdaa8c25699bb870c9ac3ac43f78747974670c699b209bda582b6f/goodhosts/vagrant" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/goodhosts/vagrant/blob/main/Gemfile">vagrant/Gemfile at main · goodhosts/vagrant</a></strong></div><div>Vagrant plugin that use goodhosts to manipulate hosts files - goodhosts/vagrant</div></blockquote>

**Comment by Mte90** [comment]
I think that is only for development, downloading the last gem https://github.com/goodhosts/vagrant/releases/tag/1.1.7 and checking the metadata I don't find any reference to that dependency.
Infact on https://rubygems.org/gems/vagrant-goodhosts mention only the so dependency.

I think that the user is using an old version of vagrant or the plugin.

<blockquote><img src="https://opengraph.githubassets.com/0750de45ff47fe5db7d6c1f3ae8720cf4f3a9b311c455c6d75a0fa764fe981e0/goodhosts/vagrant/releases/tag/1.1.7" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/goodhosts/vagrant/releases/tag/1.1.7">Release 1.1.7 · goodhosts/vagrant</a></strong></div><div>Updated goodhosts bundle to latest 1.1.2 release</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://rubygems.org/gems/vagrant-goodhosts">vagrant-goodhosts | RubyGems.org | your community gem host</a></strong></div></blockquote>

**Comment by mcyzyk** [comment]
FYI, I am running Vagrant version 2.4.2-1 here.

**Comment by Mte90** [comment]
I have the same issue with the vagrant 2.4.2 and the plugin 1.1.7 release (also just packaged).

It seems a bug in vagrant https://github.com/hashicorp/vagrant/issues/13527 and the fix was aalready merged so we need just to wait for the next release.
