### ISSUE TITLE
Q: PHP version

### ISSUE THREAD

**Issue by mcyzyk** [Varying-Vagrant-Vagrants/VVV#2694]
I have set PHP 8.0 in my config.yml and have provisioned.  The VVV dashboard indicates that PHP 8.0 is active for my site.

BUT from inside the site, Health Check is reporting that PHP 7.4.33 is what's active.  (please see attached screenshot.)

No fair!

How to remedy?

Mark

![snapshot1](https://github.com/Varying-Vagrant-Vagrants/VVV/assets/7024933/0d1f08c7-bac1-4093-b0e2-0193212c0797)

**Comment by tomjn** [comment]
which version of VVV are you using? Did you add PHP 8.0 to the extensions section? If you request e.g. PHP 8.1 it will only use 8.1 if it's installed and instead fallback to the default.

The dashboard is showing 8.0 because that's what you requested, not because that's what it's using

**Comment by mcyzyk** [comment]
Thanks, Tom!

Very helpful.  I'm now up and running with PHP 8.0.

Appreciatively,

Mark
