### ISSUE TITLE
phpMyAdmin - 413 Request Entity Too Large

### ISSUE THREAD

**Issue by shaneholloman** [Varying-Vagrant-Vagrants/VVV#273]
Can someone possibly help me out and mention where and what I need to edit to allow a 60MB data import into my VVV setup

Cheers in advance!

**Comment by joelworsham** [comment]
I've changed all memory limit and such values in my conf files, and I still get this error... and I have no idea how to import via cli

**Comment by onlyskyguy** [comment]
Also having this issue. Set everything super high, trying to upload a 35MB file.

**Comment by jeremyfelt** [comment]
See #599 for related/duplicate. We're going to bump the upload limit there.

**Comment by amiashraf** [comment]
if there is not configuration 
client_max_body_size XXM; 
at the file  /etc/nginx/nginx.conf
please add 
`client_max_body_size 50M;`
under
```
http {
 client_max_body_size 50M;
}
```
and run the command 
`sudo service nginx restart`

**Comment by tomjn** [comment]
That change would be lost the moment the VM is destroyed or reprovisioned, a change to the main provisioner would be better
