### ISSUE TITLE
phpMyAdmin - error when visiting vvv/database-admin/

### ISSUE THREAD

**Issue by berberich** [Varying-Vagrant-Vagrants/VVV#276]
When I visit http://vvv/database-admin/ in my browser, I get the following error message:

phpMyAdmin - Error
Wrong permissions on configuration file, should not be world writable!

I'm using Vagrant and VVV on Windows.

The first search result for this error points to [this](http://blog.elijaa.org/index.php?post/2013/02/19/Solve-Wrong-permissions-on-configuration-file%2C-should-not-be-world-writable!-error-on-phpMyAdmin) page, which references running a linux VM that mounts a Windows folder containing the phpMyAdmin files. I tried both suggestions there, but neither resolved the error:

```
chmod 0755 config.inc.php
```

```
$cfg['CheckConfigurationPermissions'] = false;
```

**Comment by Streenjw** [comment]
Hi, same problem here, using the vmware provider though but I think it's not the issue here. Everything in ls -lrt /srv/www/default/database-admin/ have permissions: rwxrwxrwx so 777...

**Comment by Streenjw** [comment]
Ended up commenting out the line 580 in www/default/database-admin/libraries/common.inc.php that makes the check: $GLOBALS['PMA_Config']->checkPermissions();

It's working now for me.
