### ISSUE TITLE
What is the method for using Multisite and subdomains

### ISSUE THREAD

**Issue by shaneholloman** [Varying-Vagrant-Vagrants/VVV#284]
@jeremyfelt do you have a multisite version of VVV already made in a Gist possibly that allows for subdomains?

Or a resource that could help me understand the method to construct this?

Many thanks VVV has been very useful indeed!

**Comment by jancbeck** [comment]
The repo @cfoellmann linked to is gone.

**Comment by cfoellmann** [comment]
Sorry.
SEE: https://github.com/cfoellmann/vvv-sites
SEE: https://github.com/Varying-Vagrant-Vagrants/vvv-multisite
