### ISSUE TITLE
provision phpmyadmin via composer?

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#286]
Maybe provisioning phpmyadmin via composer would save us updating every version by hand?

**Comment by jeremyfelt** [comment]
This may deserve another look. After poking at #1012, which I'm going to close in a minute, there are a couple things we should answer before proceeding:

1. Will `composer create-project phpmyadmin/phpmyadmin:4.6.* database-admin --repository-url=https://www.phpmyadmin.net/packages.json --no-dev` work when there's an existing `database-admin/` directory?
2. How can this be configured to update whenever `vagrant provision` is run?

Once we have some conclusions on that approach, then the PR will need to be created against the [VVV Utilities](https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/) repository, which is part of the new provisioning process.

**Comment by Mte90** [comment]
I am studying what to do but seems that with composer is not possible to download a package with all the locales.

**Comment by benlumia007** [comment]
is this still doable, if not, then we shouldn't need to worried bout this if we can't install phpmyadmin using composer ?

**Comment by tomjn** [comment]
I'm not too worried about this now, I think we can close this out
