### ISSUE TITLE
vagrant share with auto site setup

### ISSUE THREAD

**Issue by jonathan-dejong** [Varying-Vagrant-Vagrants/VVV#306]
Hi!

Been trying to figure out how to use the auto site setup with vagrant share.. 
or vagrant share at all for that matter.. 

Trying to run vagrant share on the VVV vagranfile results in a 502 bad gateway ngix page. I'm honestly not that good at servers, protocols etc. so I can't figure out what needs to be done to it! 

Possibly a feature to add to VVV?

**Comment by jeremyfelt** [comment]
Going to close this out with a pointer to #820.
