### ISSUE TITLE
Ability to disable installation of default WP sites

### ISSUE THREAD

**Issue by thewebists** [Varying-Vagrant-Vagrants/VVV#313]
As much as I like the idea of having quick and easy access to the different versions of WP installed by default with VVV, in practice this is only rarely useful for me personally, while making the vagrant provision process take longer.

I would like to propose two things:
1) The ability to disable the installation of the default WP sites (by commenting out a block in the Vagrantfile).

2) Split off the WP provisioning scripts into a separate file. This would help with the above, make it easier to customize/hack the provision.sh file and give the option of running the script independently of the provision process to add the WP site manually.

**Comment by Mte90** [comment]
any news?

**Comment by jeremyfelt** [comment]
It is now possible to disable the provisioning of sites after the merge of #980. :tada:
