### ISSUE TITLE
Getting error net::ERR_INCOMPLETE_CHUNKED_ENCODING - Is this to do with NGINX?

### ISSUE THREAD

**Issue by henscu** [Varying-Vagrant-Vagrants/VVV#324]
Using VVV (see setup below), when I try to use certain options in my Dynamik Website Builder WordPress theme below (specifically Dynamik Design and Dynamik Custom pages), I get the following error in Chrome and Safari. The symptom is that my browser just locks up. I can use the BACK button to go to the previous page and continue:

**net::ERR_INCOMPLETE_CHUNKED_ENCODING**

In Firefox more of these pages are rendered correctly but the error still occurs, just a bit later...

Is this to do with an NGINX setting that I can modify? I found a reference to NGINX Chunking at:

http://wiki.nginx.org/HttpChunkinModule

My setup is:

- VVV on Macbook Pro running Mavericks
- Mark Jaquith's WP-SKELETON https://github.com/markjaquith/WordPress-Skeleton
- Wordpress Theme: CobaltApps Dynamik Website Builder (http://cobaltapps.com/) running with Studiopress Genesis (http://www.studiopress.com/)

**Comment by alexsancho** [comment]
if anone is having this issue, another setting to tweak on nginx.conf "sendfile off;" this solved the problem for me

**Comment by fulicat** [comment]
@alexsancho  thank u,

**Comment by cfoellmann** [comment]
we have `sendfile off` in the current version (1.2.x). Is there anything else we need to do?
If not, CLOSE

**Comment by henscu** [comment]
I'm using Desktop Server for my development at the moment, so fine to close it if others say it's fixed.

I will update and test with latest VVV again to check it's resolved. If not, will get back to you.

**Comment by elminson** [comment]
I fixed using this post 
https://stackoverflow.com/questions/29789268/neterr-incomplete-chunked-encoding-nginx

Adding to nginx config and restart nginx 
```
server {
    ...

    location / {
        ...
        proxy_buffers 8 1024k;  
        proxy_buffer_size 1024k;
    }
}
```

**Comment by tomjn** [comment]
@elminson can you do a PR against the `develop` branch with that change? It'll need doing to https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx-wp-common.conf otherwise those changes will be removed on your next provision

**Comment by elminson** [comment]
@tomjn Sure!

**Comment by elminson** [comment]
@tomjn Done! you can review it!

**Comment by tomjn** [comment]
Awesome, it got merged and will be in the next release
