### ISSUE TITLE
Enabling xdebug by default via vvv-init.sh

### ISSUE THREAD

**Issue by sc0ttkclark** [Varying-Vagrant-Vagrants/VVV#332]
I'd like to enable xdebug by default, but adding something like `vagrant ssh -c xdebug_on` won't work, is there a way that someone knows how to do that easily?

**Comment by Mte90** [comment]
for me this line in Customfile not work.
I use this command for launch vvv and xdebug:
```vagrant up; vagrant ssh -c xdebug_on```
