### ISSUE TITLE
Mailcatcher?

### ISSUE THREAD

**Issue by pmgarman** [Varying-Vagrant-Vagrants/VVV#337]
I'm setting up VVV after not using it a while and I've gotten used to using [Mailcatcher](mailcatcher.me) during development. I am up to building this into VVV but wanted to see if this is something that others would want as well. I saw in the provision.sh Postfix is already getting setup and some may WANT emails to actually be sent out rather than catching them.

**Comment by DrewAPicture** [comment]
:+1: Attached commit works exactly as advertised.

**Comment by jonathanbardo** [comment]
What about using mailhog instead of mailcatcher. It's honestly way easier to install as it doesn't have any dependencies.

**Comment by EHLOVader** [comment]
Looks nice but as I understand it Mail hog still requires configuration in
the application. Sometimes that is more complicated than letting it use the
internal sendmail which is what mailcatcher provides.

Provide a fork. Would love to see the differences though.

**Comment by zamoose** [comment]
Also:
Docker + Mongo?

--
Doug Stewart

**Comment by jonathanbardo** [comment]
@zamoose I'm not sure I follow you... What has docker and mongo have to do with catching emails?

**Comment by zamoose** [comment]
That's what Mailhog seems to require -- MongoDB running on top of a Docker instance. I was pointing out that adding such greatly increases complexity. 

--
Doug Stewart

**Comment by pmgarman** [comment]
I get the same impression out of MailHog, and seems adding a gem is minimal vs something running in docker.

**Comment by jonathanbardo** [comment]
You don't need docker and mongodb at all! All you need is download the binaries for the platform and run: `mailhog`. If you want to run it in the background (without having supervisord or upstart) all you need is: `nohup mailhog > /dev/null 2>&1 &`.

It's honestly the simplest thing to install ever. It listen to SMTP port 1025 and it has a admin available at port 8025 by default. There is a lot of environnement configuration to overrides those port if we want to.

**Comment by zamoose** [comment]
We *are* talking about this, right?

https://github.com/mailhog/MailHog

--
Doug Stewart

**Comment by zamoose** [comment]
Ahhh, I see my error. The MH docs talk about Docker on the front end but get to other install methods further down. 'Twould help if I read all the way to the bottom. 

It seems to be written in Go, unless I'm missing something again. 

--
Doug Stewart

**Comment by jonathanbardo** [comment]
It's indeed written in go, but it really doesn't matter what language it is written in because the release is compiled and run as binaries. For VVV we would use the MailHog_linux_amd64 release.

**Comment by EHLOVader** [comment]
@jonathanbardo Sounds great. I suggest you (or anyone with an equal passion for mailhog) fork VVV with a complete implementation on a branch and I am sure they would love to use that instead if it works better. I was weary about the RVM dependency myself since the APT distribution is out of date and requires extra work to use. Mailhog also does seem to have some added benefits. (I actually like the idea of mongodb, mailcatcher has no persistent storage yet) And it may provide a smooth and clear upgrade path into docker which is in the VVV future it seems.

But afaict right now this is working.

**Comment by EHLOVader** [comment]
Looks like mailhog might need ssmtp to add proper support for system mail functions. Still not horrible. I often take peeks at other provisioning systems to ensure I had the formula right. https://github.com/geerlingguy/ansible-role-mailhog is one I saw ssmtp setup for it.

**Comment by jdevalk** [comment]
Hmm this would be fixed by #464
