### ISSUE TITLE
Add varnish?

### ISSUE THREAD

**Issue by kiriaze** [Varying-Vagrant-Vagrants/VVV#348]
Wondering how to include/setup varnish with VVV, or if there are plans to include it?

**Comment by collegeman** [comment]
Link no longer available. Could someone please repost?

**Comment by khromov** [comment]
+1 @collegeman New link to Varnish example in VVV would be nice @TheLastCicada

**Comment by TheLastCicada** [comment]
I'd love to help, but I have no recollection of what was ever at that link or this conversation :)
