### ISSUE TITLE
Pre-add GitHub as SSH known_host and persist SSH agent through user switch

### ISSUE THREAD

**Issue by westonruter** [Varying-Vagrant-Vagrants/VVV#360]
There's this dreaded issue I've seen come up over and over again when the (non-TTY) provisioner tries to connect to private GitHub repos, but either fails because it doesn't have the proper SSH agent or because it is connecting to an un-`known_host`, and since it is not a TTY the user can't manually verify the authenticity of the host. 

I found that SSH agent can be made to persist after user switches via addomg `Defaults  env_keep+=SSH_AUTH_SOCK` to `/etc/sudoers`:

``` bash
# Make sure SSH agent forwarding persists across switching users (so that GitHub is added to known hosts)
if ! grep -sq -E 'Defaults  *env_keep+=SSH_AUTH_SOCK' /etc/sudoers; then
    echo "Add SSH_AUTH_SOCK to sudoers config"
    # TODO: We're supposed to use visudo to modify this file?
    echo 'Defaults  env_keep+=SSH_AUTH_SOCK' >> /etc/sudoers
fi
```

The other problem is harder, and I haven't found a solution to the ol':

```
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

I've tried the following two approaches, but both without success:

``` bash
# Attempt to prevent non-TTY failure to connect to GitHub since user cannot accept to add host to known_hosts
if ! grep -sq 'Host 192.30.252.*' /etc/ssh/ssh_config; then
    echo "Add GitHub IP whitelist to global ssh_config"
    echo -e '\nHost 192.30.252.*\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null' >> /etc/ssh/ssh_config
fi

# Manually add GitHub's public key for all IPs in range
host_key='ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
for i in {0..255}; do
    known_host_line="192.30.252.$i $host_key"
    if ! grep -sq "$known_host_line" /etc/ssh/ssh_known_hosts; then
        echo "Add known_host 192.30.252.$i"
        echo "$known_host_line" >> /etc/ssh/ssh_known_hosts
    fi
done
```

I'm specifically targeting GitHub repos here, but it would be great to add recognition for popular hosts out of the box.

**Comment by felixarntz** [comment]
+1 for this. I just ran into the same problem, I used the approach suggested in https://github.com/mitchellh/vagrant/issues/1303#issue-9781811 to fix it.

**Comment by felixarntz** [comment]
@LoreleiAurora and I discussed this yesterday and decided it would probably make sense to create a `known_hosts` file somewhere in the `config` directory that would by default be prepopulated with the host keys for github, bitbucket and gitlab. It would be possible for it to be modified manually though.

Then the provisioner should move these into the relevant locations in the VM (`/root/.ssh/known_hosts` and `~/.ssh/known_hosts`).

**Comment by LoreleiAurora** [comment]
Now available by adding `trusted-hosts` as a utility 
Will be made part of the main provisioner in the next release
