### ISSUE TITLE
"failed to create symbolic link ‘/usr/bin/node’" complaint if symlink exists

### ISSUE THREAD

**Issue by pglewis** [Varying-Vagrant-Vagrants/VVV#374]
Mostly cosmetic as this is merely a warning: 

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/b7edaa/provision/provision.sh#L119

This line unconditionally attempts to create the symlink.  There are two other occurrences of `ln` in the provision file and both use `-sf` to force removing an existing link first.  

A second option would be to check for the existence of the link before creating it.

**Comment by cfoellmann** [comment]
the line has been dropped.
Let's CLOSE
