### ISSUE TITLE
Changing details in General settings gives "Corrupted Content Error"

### ISSUE THREAD

**Issue by Pezzab** [Varying-Vagrant-Vagrants/VVV#380]
Whilst working on local.wordpress.dev I've found that whenever I have tried to change the blog title or the even the strap line that the install gets messed up and (in Firefox) I get the following error message:

"*Corrupted Content Error*

The page you are trying to view cannot be shown because an error in the data transmission was detected."

The test site becomes unreachable from that point onwards, though I can get into admin. Trying to change things back has no effect.

Perhaps there is a way to rescue the install but I always end up deleting wordpress_default in phpMyAdmin altogether, creating it anew then reinstalling WP on that domain.

Edit: I just discovered that if I change the fields directly in phpMyAdmin that I don't get the error. By the way I'm using Codekit, in case this has any bearing

**Comment by cfoellmann** [comment]
I am sorry you never got a reply. Did you solve the problem?
