### ISSUE TITLE
SSL read: error

### ISSUE THREAD

**Issue by AlyssonNeto** [Varying-Vagrant-Vagrants/VVV#401]
I'm getting the following error when i run vagrant up

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://vagrantcloud.com/ubuntu/trusty64
==> default: Adding box 'ubuntu/trusty64' (v14.04) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 50

**Comment by AnnaFu** [comment]
Hi, my computer is ASUS X42D. I keep getting "SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054" when trying to add vagrant box. In Laravel they said to hardware virtualization (VT-x), but I can't find it in my BIOS. Any help please?

**Comment by xasos** [comment]
+1

**Comment by jdmcd12** [comment]
+1

**Comment by aroget** [comment]
+1

**Comment by jllucas** [comment]
+1

**Comment by gdbtek** [comment]
I had the same issue and I host `.vbox` at AWS S3. The errors are:

```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 60
```

After I swtich from S3 `https` to `http`, it works.

**Comment by komarnicki** [comment]
@gdbtek, I have the same problem with adding vagrant add box laravel/homestead (http://bit.ly/1WQNcIN). Could you tell me how exactly did you solved this problem? How to switch from https to http?

**Comment by Anahkiasen** [comment]
Same issue here, with Homestead as well

**Comment by zouchao** [comment]
@komarnicki @Anahkiasen 
```shell
vagrant box add laravel/homestead http://atlas.hashicorp.com/laravel/boxes/homestead
```

**Comment by komarnicki** [comment]
@zouchao, this fixed my problem: http://slick.pl/kb/software/vagrant-fix-for-error-60-ssl-read/

**Comment by hdra** [comment]
I'm having trouble updating a box as well, although in my case the error message is a bit different:

```
SSL read: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac, errno 0
```

**Comment by ChinW** [comment]
use 
```
vagrant box add laravel/homestead -c
```
may works

**Comment by snsmurf** [comment]
> use
> `vagrant box add laravel/homestead -c`
> may works

This made it work for me!

**Comment by privatebox** [comment]
We found this worked for us - 
vagrant box add --insecure -c laravel/homestead http://atlas.hashicorp.com/laravel/boxes/homestead

**Comment by SaifurRahmanMohsin** [comment]
I get this on a MacBook Pro Retina 2013. It happened last time when I updated homestead and again now. This needs a proper fix than a workaround... Any solutions?

**Comment by duhaime** [comment]
I also received this error on OSX simply because my shell had lost its internet connection halfway through the download. 

After installing VirtualBox and Vagrant, I ran the command `vagrant init hashicorp/precise64`, then `vagrant up`. Halfway through the latter command, I walked away from my machine (which went inactive and required me to submit my credentials to log back in) and when I came back I had the error message above `SSL read: error:00000000:lib(0):func(0):reason(0), errno 54`. I issued another `vagrant up` command and continued working with the laptop rather than walk away, and the command finished without error status.

**Comment by ahgardner** [comment]
On OS/X, I repeated the "vagrant up" command after the error, and the process resumed and completed.

**Comment by kyawsithu** [comment]
Uploaded a mirror to Google Drive. Download and add it manually. https://drive.google.com/file/d/0BxiUDyf4p8pdZHpPUGhwVkJ2VWc/view?usp=sharing

**Comment by Shkeats** [comment]
Experiencing this too with Vagrant 1.9.1. @jeremyfelt Could you reopen?

**Comment by mcandre** [comment]
[Caffeine](http://lightheadsw.com/caffeine/) + `vagrant destroy -f; vagrant box remove -f <image>; rm -rf .vagrant; vagrant init <image> && vagrant up` worked for me.

**Comment by jeremyfelt** [comment]
@Shkeats I'm not sure that this is a bug in VVV. From reading through the discussion here it seems like there can sometimes be an issue on the host machine or with the network connection. If it seems like something we can fix in VVV, please open a new issue with a clear list of steps to reproduce. Thanks!

**Comment by juniorgarcia** [comment]
`vagrant box update --insecure` should avoid this.

**Comment by ryancwalsh** [comment]
+1 for me on Windows 10 just now. The download never completes. 

I keep trying again and again, and I've even tried https://github.com/Varying-Vagrant-Vagrants/VVV/issues/401#issuecomment-166156672.

I'm trying to install a specific older version of Homestead (downgrading because of https://github.com/laravel/homestead/issues/510 since the latest version of VirtualBox seems to have a bug).

**Comment by angel1995j** [comment]
The problem was solved by running the windows updates

**Comment by moodgalal** [comment]
@angel1995j 

Unfortunatley it wasn't ... Today i downloaded all the windows updates and still got this problem, Tried every solution here and it didn't work for me also after i updated virtualbox and vagrant

**Comment by angel1995j** [comment]
@moodgalal  
The other you can do is check the php.ini file located in the root of your site and see the lines of ssl and see if there are any commented.

**Comment by DJviolin** [comment]
I'm using Windows 10 and replacing curl with the following one solved it for me:
[Win64 x86_64 | 7zip | 7.54.1 | binary | SSL | SSH](https://bintray.com/artifact/download/vszakats/generic/curl-7.54.1-win64-mingw.7z)
[Original source](https://curl.haxx.se/download.html)

Although the download speed still all over the place (first few seconds normal speed, than drops), this was the only binary which was able to keep-alive the connection (I don't know is it important that it includes the certificates or not). Even the MSYS2 mingw curl's are not finished the download.

**Comment by Helg18** [comment]
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

**Comment by JaLover** [comment]
For those of you who has this problem
see the solution here
http://slick.pl/kb/software/vagrant-fix-for-error-60-ssl-read/
that's weird it's been years and the problem remains!

**Comment by parvez40** [comment]
1. Install virtualbox 5.1 and make sure that hardware virtualization is enabled in BIOS
2. Create a folder in your directory e.g. C:/vagrant
3. Run Command in vagrant folder: vagrant init
4. Run Command in vagrant folder: vagrant box add --insecure laravel/homestead

Then It worked for me 👍

**Comment by arieltoledo** [comment]
I was having the same error on  Ubuntu 16.04. After reading all the posts, and what @simonwheatley and @jeremyfelt says, I re-generate my public ssh key "ssh-keygen -t rsa" adding a new passphrase, and everything works like a charm. Hope it helps.

**Comment by alfeuduran** [comment]
Im using just vagrant reload and try again. It works for me!

**Comment by yosmangel** [comment]
Well, I have the same error.

My OS is Wondows 10

Windows is update 

But my error is the connection time to download.

![image](https://user-images.githubusercontent.com/13854308/37718538-4da871e2-2cf9-11e8-9dec-06eaacd4eda8.png)


What happen?

**Comment by yosmangel** [comment]
@DJviolin Where you paste curl file? In php folder?

**Comment by DJviolin** [comment]
@yosmangel No, I replaced it system-wise. I using MSYS2 with Mingw64 on windows, So I think the path was: `C:\msys64\mingw64\bin`, but there's also a curl under `C:\msys64\usr\bin`. I think the best bet if you open your console where you running Vagrant and type in: `whereis curl`.

**Comment by tomjn** [comment]
@yosmangel that's not the same issue, that isn't even a VVV box, you should open a new issue over at Laravel Homestead, this is the VVV project

**Comment by yosmangel** [comment]
@tomjn My issue was the same, SSL read error, But, In my case, I solved my problem with the modem and call of my home telephone. Sorry

**Comment by zigmasdirigeant** [comment]
Just a quick up... (Maybe not the most secure way 🤷🏻‍♂️) I fixed the problem by running the command as Sudo.

**Comment by tomjn** [comment]
@zigmasdirigeant do you mean `sudo vagrant up`? You should never run the vagrant commands with `sudo`, it will cause issues as all subsequent vagrant commands will require `sudo` too, and it wasn't built to be ran that way

**Comment by DJviolin** [comment]
Just a quick update: with the latest Vagrant version tested, third-party curl is not required. Just use the one that shipped with Vagrant (at least I don't need to use the monkey patching now).

**Comment by alphaVariable** [comment]
> ```
> vagrant box add laravel/homestead -c
> ```

This fixed it

**Comment by Samiys** [comment]
> @komarnicki @Anahkiasen
> 
> ```shell
> vagrant box add laravel/homestead http://atlas.hashicorp.com/laravel/boxes/homestead
> ```

This worked !! Thanks 👍

**Comment by tomjn** [comment]
A reminder, **this is not a support avenue for Laravel Homestead**, this is the VVV project
