### ISSUE TITLE
Too many database backups

### ISSUE THREAD

**Issue by simonwheatley** [Varying-Vagrant-Vagrants/VVV#407]
I've finally got around to installing the triggers on my VVV, and wondered why `up`s and `halt`s were taking so long… it's the database backups. So many database backups. Some quite large. Some I don't need.

This ticket is a place to wonder "if we have auto site setup, to create sites and associated databases, how do we remember to remove the databases we no longer need?"

I have no answer. Just a lot of database backups.

**Comment by tomjn** [comment]
Adding a  `no_backup: true` or `backup: false` in `vvv-config.yml` makes sense here

**Comment by ivankristianto** [comment]
Agree to @tomjn, I have 1.3 GB of mysql database. And it take long time to backup.
I don't need to be backup everytime i vagrant halt.
Or can I skip vagrant halt to not running the database backup?

**Comment by tomjn** [comment]
@LoreleiAurora do you have any notes on how this would be implemented? Is it as simple as a conditional around the check? Or is the triggers backup just doing DB tables?

**Comment by mariadanieldeepak** [comment]
> Adding a no_backup: true or backup: false in vvv-config.yml makes sense here

Could anyone tell me if the above feature has been implemented?

**Comment by tomjn** [comment]
@mariadanieldeepak no it hasn't, there's the problem that given a database it's not possible to determine which site it came from, so adding a `no_backup` key isn't straight forward

**Comment by tomjn** [comment]
So in the custom site template we have:

`DB_NAME=`get_config_value 'db_name' "${VVV_SITE_NAME}"``

Which could be used to figure out the database in those sites, assuming it hasn't been changed. In that case, I think if `db_name` is defined, then the `no_backup` key could be used. I would need to test this in the vagrant file though, and I don't have the time this week to try it out

**Comment by mariadanieldeepak** [comment]
@tomjn Thank you for getting back me to on this. Meanwhile, I've used `vagrant_halt_custom` I actually hardcoded the DB name, to skip it for now.

**Comment by tomjn** [comment]
@mariadanieldeepak can you post that in a gist and link here for reference?

**Comment by mariadanieldeepak** [comment]
@tomjn,

I've both the `vagrant_halt_custom` and `db_backup_custom` scripts [here](https://stackoverflow.com/a/47536337/5569979).

**Comment by tomjn** [comment]
@simonwheatley you'll be glad to know there are now toggles in the `develop` branch for database backup and restore thanks to https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1705

Modifying a `vagrant_halt_custom` and `db_backup_custom` file should no longer be necessary

**Comment by simonwheatley** [comment]
Yay!
