### ISSUE TITLE
Add documentation on using vvv for core contribution

### ISSUE THREAD

**Issue by lgedeon** [Varying-Vagrant-Vagrants/VVV#409]
I am starting to use wordpress-develop instead of my old hacked together way of doing things, and it appears to me that there is no documentation yet on what type of changes require using the build system, and where to make changes, what folder to svn up from and how to make a good diff/patch. There are of course many resources on contribution in general, but documentation focused on the specific set-up in vvv's wordpress-develop would be great.

I can make a first pass at this, if you can recommend where to put the documentation, or maybe you can point me to notes I have not yet discovered.

**Comment by jeremyfelt** [comment]
1.5 years later... agreed. :)

The best way to keep up to date documentation on core development is to point to core's docs, which we do in the README. In the future, it may be nice to have more detailed documentation on how to use some of the debugging tools provided by VVV as part of the process.
