### ISSUE TITLE
Memcached failing to store values

### ISSUE THREAD

**Issue by westonruter** [Varying-Vagrant-Vagrants/VVV#423]
I've been noticing that my Memcached Object Cache is increasingly failing in VVV. Sometimes the site will just start crawling, and when I look into it I find that Memcached isn't storing any new values.  So I have to restart Memcached every time this happens:

```
$ wp cache set food bard
Error: Could not add object 'food' in group ''.
$ sudo service memcached restart
Restarting memcached: memcached.
$ wp cache set food bard
Success: Set object 'food' in group ''.
```

Anyone else come across this problem?

**Comment by westonruter** [comment]
BTW, this issue happens periodically on VIP Quickstart as well.

**Comment by johnjamesjacoby** [comment]
Possibly related to missing PECL Memcached?

![screen shot 2016-02-02 at 10 04 09 am](https://cloud.githubusercontent.com/assets/88951/12755280/69d5cbf0-c994-11e5-856c-34507aea6568.png)

**Comment by jeremyfelt** [comment]
I've never tried adding a Memcached log, but it looks like it can be done with the `OPTIONS` flag by piping verbose output to a log file. That could be worth it to see what it thinks is going on.

**Comment by johnjamesjacoby** [comment]
Maybe updating Memcached will help?

VVV uses `v1.4.14` and current stable from memcached.org is `v1.4.25`.

**Comment by jeremyfelt** [comment]
Hey look, it's been a year. :)

> VVV uses v1.4.14 and current stable from memcached.org is v1.4.25.

This may be a good idea. I'd at least feel comfortable closing out this issue then. :)

Unfortunately, the official Ubuntu PPAs max out at 1.4.14 for 14.04 Trusty. There is an [unofficial PPA](https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/packages) that provides the latest version of memcached.

That's probably worth some testing for a bit before merging, so I'm not going to push for it in 2.0.0.

**Comment by tomjn** [comment]
Closing this out due to inactivity, and noting that by default an object cache isn't installed in the custom site template
