### ISSUE TITLE
Connecting to sites using vagrant-share

### ISSUE THREAD

**Issue by iparr** [Varying-Vagrant-Vagrants/VVV#425]
I'm using vvv-site-wizard to create WordPress installs for VVV and it's great.

I have sites like thisdomain.dev setup and I can access them in another VM by altering that machines hosts file.

What I want to do is test such domains on mobile devices elsewhere on the office network.

I use `vagrant share` and it creates me a domain to visit and this will take you to the vvv.dev 'dashboard'.

What I want is for that to connect to one of my other WordPress installs instead, like thisdomain.dev

I'm looking into changing the default folder from 'default', to 'thisdomain' instead, so that when you visit the url that `vagrant share` generates you are taken to that WordPress install, but I'm struggling to see how.

Any pointer on this or, if I'm going down the wrong road, any other technique you'd recommend to facilitate mobile device testing?

**Comment by rtpHarry** [comment]
@iparr thanks for that tip! Couple of notes from a vagrant-newbie Windows-based user:

1. If you used the vvv-site-wizard script to add your extra domains the path will likely have htdocs on the end so: `/srv/www/whateveryourlocalvvvdomainis/htdocs`
2. After you have finished editing in nano you press `CTRL-O` (letter) then press enter to save and then `CTRL-X` to exit nano.

**Comment by morganhi** [comment]
Thank's guys, works like a charm.

**Comment by jeremyfelt** [comment]
Another Vagrant share ticket - #820.

**Comment by andreferreira-me** [comment]
Thank you! Works here too.. There is any better solution?
