### ISSUE TITLE
Upgrade and test PHP 5.6

### ISSUE THREAD

**Issue by jonathanbardo** [Varying-Vagrant-Vagrants/VVV#436]
Did anyone tried playing with VVV and PHP 5.6?

**Comment by cfoellmann** [comment]
you can use phpbrew to run php 5.6
See #586 or https://github.com/Varying-Vagrant-Vagrants/VVV/tree/feature/phpbrew . Testing it would help us evaluate the state of the feature.

**Comment by colin-marshall** [comment]
How would one go about installing the phpbrew branch of VVV? Can I pull the branch from an existing install or would I have to do a clean one, and if so how?

**Comment by itsazzad** [comment]
@cfoellmann what are the differences in the installation procedure?
I can see that both are using the same [master](git://github.com/Varying-Vagrant-Vagrants/VVV.git) repository. Isn't it?

**Comment by jeremyfelt** [comment]
Closing this and deferring to #834 for a decision between 5.6 and 7.

**Comment by zzuga** [comment]
WordPress recommends a minimum of PHP 5.6
https://wordpress.org/about/requirements/

I use PHP 5.6 in my VVV by running these commands after provisioning
sudo add-apt-repository ppa:ondrej/php5-5.6
sudo apt-get update
sudo apt-get install php5

Being so easy, I think it should be included while you discuss (and implement) phpbrew
