### ISSUE TITLE
A small utility to create sites & DB

### ISSUE THREAD

**Issue by iamntz** [Varying-Vagrant-Vagrants/VVV#444]
Hi guys, i have no idea where to put this, so, here it is:

https://gist.github.com/iamntz/690cc13fde8e6529c898

What it does? You just need  to run `node make-vvv.js X Y` (where X = client name, Y = project name) and it will create database file & nginx config in one quick step.

Hope it helps :)

**Comment by jeremyfelt** [comment]
Way late thanks for this. :) I've created a tools label to track issues like it.
