### ISSUE TITLE
updating php-custom.ini (specifically upload_max_filesize)

### ISSUE THREAD

**Issue by jacobwise** [Varying-Vagrant-Vagrants/VVV#454]
I am new to Vagrant, VVV and OS X. I spun up a project and want to upload the database but it exceeds the default 50M. Not sure if I am missing something but after I update the php-custom.ini file I run Vagrant halt and Vagrant up, I am not seeing the changes reflected in the phpinfo() file. Any ideas what might be going on?

**Comment by eteubert** [comment]
Just in case someone stumbles over this: You need to update php ini _and_ nginx config `client_max_body_size`, see https://rtcamp.com/tutorials/php/increase-file-upload-size-limit/

**Comment by jeremyfelt** [comment]
#599 will also help this at some point.
