### ISSUE TITLE
Update VM with security releases on any provision

### ISSUE THREAD

**Issue by enejb** [Varying-Vagrant-Vagrants/VVV#457]
More info can be found here. http://www.bbc.com/news/technology-29361794

running `vagrant ssh` and then 
`env x='() { :;}; echo vulnerable' bash -c 'echo hello'` I get back 
vulnerable
hello

Which confirms the vulnerability. 
I fixed it on my virtual box by running 
`sudo apt-get update` and then `sudo apt-get --only-upgrade install bash` 
After the two commands I ran 
`env x='() { :;}; echo vulnerable' bash -c 'echo hello'` and got back
hello

**Comment by jeremyfelt** [comment]
I'm going to hijack the original title for this and make it a feature request. :wind_chime:

**Comment by Mte90** [comment]
We have our custom box right now so I don't think that we have to worry about it.
Yes the update of the box is still manual but is better for the user that don't want a new provision with a waiting to load everything.

**Comment by tomjn** [comment]
Closing this out as anybody can run these commands to do it:

```
vagrant halt
vagrant destroy
vagrant box update
vagrant up --provision
```
