### ISSUE TITLE
host routing randomly stops working.

### ISSUE THREAD

**Issue by Tidal-Wave** [Varying-Vagrant-Vagrants/VVV#468]
Recently, like in the past 48 hours, I've started to experience a very odd issue. I've used VVV several times in the past with loads of success, but now all the sudden on a new project Ive had the host routing just... stop. Randomly Ill be presented with the default nginx Welcome page and it refuses to go away. The host file is still intact, but everything stops working. Halts, Reloads, Suspend/Up, none of this works. Twice today this has happened to me, and the only way i've found to fix it is to completely destroy the VVV instance with vagrant destroy and rebuild with vagrant up. 

Mac 10.9.4 is being used, issue present on all browsers once it happens. Any ideas? Need any more info? This is baffling to me and HUGE damper on using VVV.

**Comment by cfoellmann** [comment]
@Tidal-Wave did your issue get resolved?

**Comment by Tidal-Wave** [comment]
It seemed to resolve itself after fresh reinstall.
