### ISSUE TITLE
Allow selecting which sites to make active

### ISSUE THREAD

**Issue by tnorthcutt** [Varying-Vagrant-Vagrants/VVV#474]
I keep a number of sites (~20 right now) on one VVV install. Most of those, however, are only around for the rare instance when I need to work on them, and 90%+ of the time, I don't need them available. To speed up `destroy`, `halt`, `up`, `provision`, etc. it would be great to have a way to indicate which sites should be loaded at any given time. Perhaps a simple text file that `provision.sh` can look for, and if found, would then use to load only the sites explicitly defined?

I'm not sure if that's the best approach (and if it is, how exactly to implement that), but if given some direction, I'd be happy to submit a PR to implement this functionality.

**Comment by jeremyfelt** [comment]
It is now possible to selectively enable and disable sites through a YAML config file after the merge of #980. :tada:
