### ISSUE TITLE
Extremely slow load times with large db

### ISSUE THREAD

**Issue by joeguilmette** [Varying-Vagrant-Vagrants/VVV#476]
I have recently started working on a WP site that has a very large (350+mb) database. It has brought WordPress to a crawl, even on the default installations.

***The site with the large db loads very slowly.***
![big site](https://cloud.githubusercontent.com/assets/6581316/4628887/6224e738-539d-11e4-8fd5-7c57a2d33286.jpg)

***Even local.wordpress.dev loads like molasses. Similar performance on all default installs.***
![local-wordpress-dev](https://cloud.githubusercontent.com/assets/6581316/4628888/6d9b98f0-539d-11e4-9c27-8833939c9d3c.jpg)

I have tried increasing the VM memory from 1024mb to 2048mb in the Vagrantfile via:

```
  # Configurations from 1.0.x can be placed in Vagrant 1.1.x specs like the following.
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
```

Running `$ vagrant reload` and checking in VirtualBox that the VM has more memory available. This did not change performance at all.

The site is huge, and it is clearly choking the VM.

Any ideas?

**Comment by jdevalk** [comment]
@jeremyfelt the article you link to says it:

> If you have the option to use NFS, use it. Again, the read performance is far more valuable than the write performance.

Why don't we?

**Comment by jeremyfelt** [comment]
> Also - be cautious of NFS due to some file caching issues.

I think this is the primary reason, though it's been a long while since I played with anything or tried to get it working. I'd want some good testing done on OSX, Windows, and Linux host machines to make sure NFS does not cause any issues.

**Comment by joeguilmette** [comment]
I've been running my VVV servers with NFS enabled and... There are indeed some 'ghost in the machine' caching errors with files. I've since solved some underlying memory based issues I was having with my MacBook and things now run swimmingly without NFS.

The strange issues I'd run in to were related to NFS caching. Changes to files not being seen by Vagrant, which can lead to some strange behavior, especially because it never happens consistently.
