### ISSUE TITLE
VVV and public network

### ISSUE THREAD

**Issue by panvagenas** [Varying-Vagrant-Vagrants/VVV#478]
Hey guys. I set up VVV with a local network address so the WP instances will be visible from other network users. 
Is it posible to have WP instances outside www/default dir and make them visible over the local network? 
I suppose this could be done by adding hosts to other network computers, but this is time consuming and inconvinient. Is there another way?

**Comment by jeremyfelt** [comment]
I think we've made a few things easier in docs. I wrote-up this as a compilation, though we may need a better place in the VVV docs for it. https://jeremyfelt.com/2015/01/31/various-networking-configurations-vvv/
