### ISSUE TITLE
Resolve npm install/update redundancy

### ISSUE THREAD

**Issue by TobiasBg** [Varying-Vagrant-Vagrants/VVV#485]
From what I understand, [npm update](https://www.npmjs.org/doc/cli/npm-update.html) will install a package if it's missing.
Could we therefore shorten

``` sh
if [[ "$(grunt --version)" ]]; then
    echo "Updating Grunt CLI"
    npm update -g grunt-cli &>/dev/null
    npm update -g grunt-sass &>/dev/null
    npm update -g grunt-cssjanus &>/dev/null
else
    echo "Installing Grunt CLI"
    npm install -g grunt-cli &>/dev/null
    npm install -g grunt-sass &>/dev/null
    npm install -g grunt-cssjanus &>/dev/null
fi
```

in provision.js to

``` sh
echo "Updating/Installing Grunt CLI"
npm update -g grunt-cli &>/dev/null
npm update -g grunt-sass &>/dev/null
npm update -g grunt-cssjanus &>/dev/null
```

to make things more compact?
Could/should we also change

``` sh
npm install &>/dev/null
```

to

``` sh
npm update &>/dev/null
```

when updating `wordpress-develop`?

What confuses me is that the npm FAQ [recommends](https://www.npmjs.org/doc/misc/npm-faq.html#how-do-i-update-npm-) to use `npm install` for updating `npm` itself -- even though there's no mention of updating in the [npm install docs](https://www.npmjs.org/doc/cli/npm-install.html).
This [comparison](http://stackoverflow.com/questions/12478679/npm-install-vs-update-whats-the-difference) only adds to the confusion.

@jorbin, what do you think? Thanks!

**Comment by cfoellmann** [comment]
I am totally with you on this!
