### ISSUE TITLE
Ability to force DB restore from .sql files

### ISSUE THREAD

**Issue by sc0ttkclark** [Varying-Vagrant-Vagrants/VVV#489]
In relation to #488, it'd be great to pass an argument to `db_restore` which passes to `import-sql.sh` that can allow .sql to still run. The `DROP IF EXISTS` is already present in the .sql, so it'll just "work".

**Comment by Mte90** [comment]
I think that we can close it

**Comment by tomjn** [comment]
I actually think this is a good idea :) Should be somewhat easy to do as well, it does mean that `import-sql.sh` will need to be passed any parameters, `db_restore` is just a proxy to run that script
