### ISSUE TITLE
Add support for a log viewer

### ISSUE THREAD

**Issue by EHLOVader** [Varying-Vagrant-Vagrants/VVV#490]
I think it would be useful for monitoring logs while working to have a utility that allows users to quickly access the logs and search them. Many options exist but I think that https://github.com/potsky/PimpMyLog may be my own preference. 

I am looking into integrating this with the core since there is also not any great way to provide "plugins" of this nature.

**Comment by cfoellmann** [comment]
I have started a pimpmylog install https://github.com/cfoellmann/vvv-sites/tree/master/logviewer
Input please!

**Comment by EHLOVader** [comment]
Awesome, Looks perfect.

In the local one I was trailing for PimpMyLogs I only cloned the repo and served it.

Yours looks much better.

**Comment by cfoellmann** [comment]
Problem is that we need to find some standard on how to add logs to the config.
I modified the config to look for these `logs.cfg` file which could be included in the auto config of a site

**Comment by EHLOVader** [comment]
Look into the user configs directory setting. `/config.user.d/` appears to be the default but it can be changed using the [USER_CONFIGURATION_DIR](http://pimpmylog.com/documentation/configuration.html)

They appear to offer the ability to split out each error config into individual jsons

**Comment by EHLOVader** [comment]
Tested the install, everything ran fine. :ok_hand:
I like the more organized logs you configure initially.
They make more sense than the ones handled previously.

**Comment by tomjn** [comment]
I'm closing this, anybody could copy the `custom-site-template` and make it install pimp my logs instead of WP, and add it to `vvv-custom.yml`. Additionally, they could add extra logs to view from `vvv-custom.yml`

**Comment by tomjn** [comment]
Done: https://github.com/tomjn/vvv-pimp-my-logs
