### ISSUE TITLE
Very slow intermittently

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/VVV#506]
Most of the time Vagrant runs super fast. I've added the lines of code from [this article](http://www.stefanwrobel.com/how-to-make-vagrant-performance-not-suck), and that makes it run great. But sometimes, for an hour or so at a time, Vagrant will run slow. Very slow. The "waiting for ***.dev" message is what hangs, and it hangs for between 20 seconds and 2 minutes sometimes.

This only happens sometimes, but no matter what I do, it doesn't go away until it decides it's time to... Even restarting and provisioning doesn't help. I don't understand. Is there something on my computer that could potentially conflict? I'm running the latest OSx on a macbook pro. 16gb memory and an i7 processor, I know it's not my computer at fault.

Any advice?

**Comment by immanence** [comment]
@joelworsham Did you ever resolve this? Exactly like you, intermittently, I get the same. One of the reasons I'm on Vagrant was because MAMP was slower than a remote server. I was very happy when first using it, but the slowdowns kinda spoil the party.

**Comment by joeguilmette** [comment]
I enabled NFS, installed Memory Clean in OSX, and created a couple
different vagrants. I think the slowdown is related to ram and mysql, but
can't be sure. It's only an issue these days on really huge, shitty sites.

**Comment by joelworsham** [comment]
I have found that sometimes it runs slowly with a bad internet connection (sometimes WP will wait and wait for external recourses), and also I always turn off xDebug when I"m not using it.

**Comment by swiffysmith** [comment]
I had the same problem and by telling wordpress to block all http request, I've no more slow-down. 
Just need to insert this line in wp-config : 
`define('WP_HTTP_BLOCK_EXTERNAL', true);`
It's possible to allow some urls with :
`define( 'WP_ACCESSIBLE_HOSTS', 'api.wordpress.org,*.github.com' );` 
Wish it can help.
