### ISSUE TITLE
Mysql root password changes on provision "Access denied for user 'root'@'localhost'"

### ISSUE THREAD

**Issue by hilja** [Varying-Vagrant-Vagrants/VVV#515]
I just provisioned my VVV box and now I can't access mysql anymore, it just gives an error:

```
Access denied for user 'root'@'localhost'
```

Same thing when trying to login PHPmyadmin:

```
#1045 Cannot log in to the MySQL server
```

I can't change the mysql password cause the old password (root) isn't valid anymore.

This happened twice now, only thing that helps is to destroy the Vagrant and build new.

[Here's][1] the output of the `vagrant reload --provision` in all it's glory.

[1]: http://pastebin.com/6RgV6Y0w

**Comment by jeremyfelt** [comment]
@hilja are things still going good with the DBs?
