### ISSUE TITLE
https for wordpress develop repo

### ISSUE THREAD

**Issue by willenglishiv** [Varying-Vagrant-Vagrants/VVV#531]
I saw recently that there was an update to provision.sh in the 1.2 update to turn all the git:// urls to https:// which was awesome.  For the longest time I just made the switch in a provision-custom file for my firewall here in the office.

The only repo that seemed to missed the cut was for the wordpress-develop.  I switched the repo to @xwp wordpress-develop, as it seems to be a mirror of the private git repo from WP.  Is there any official mirror or resource we can use? Is it kosher to PR the other repo in for HTTPS or just keep it custom until WP changes it's mind?

**Comment by jeremyfelt** [comment]
I'm going to close this out now that the `wordpress-develop` config for VVV has been moved to its own repo in #980. I don't think we're going to see HTTPS on this repo for a while. It should be easier at this point to setup a config that pulls a cloned copy of the develop.wordpress repo instead.

See also: https://meta.trac.wordpress.org/ticket/633
