### ISSUE TITLE
Ability to access any WordPress version

### ISSUE THREAD

**Issue by johnbillion** [Varying-Vagrant-Vagrants/VVV#533]
For a while now I've had a rather funky setup for my WordPress development environment which allows me to access any WordPress version simply by changing the domain name. For example, to access the 3.9.1 tag I visit `391.wp`. To access the 4.0 branch I visit `40.wp`.

I access Multisite variants by prepending `m` to the domain, such as `m381.wp` for Multisite on 3.8.1. I can also access the built version by prepending `b`, such as `b40.wp` for the built version of the 4.0 branch.

The reason it's done with domain names instead of just using `example.wp/branches/4.0` is to avoid cookie clashes when working with Multisite, and the ability to quickly view and clear cookies by domain.

This is incredibly handy when testing if issues reported against core exist in previous versions.

Is this something that could be useful in VVV? I'd be willing to do some work on it if so.

**Comment by jeremyfelt** [comment]
This would be very useful! I'm thinking we should get configuration in order first so that one can easily pick and choose what sites they want to bring up.

Would this make sense as additional VVV repositories, similar to @cfoellmann's multisite one? https://github.com/Varying-Vagrant-Vagrants/vvv-multisite

**Comment by jeremyfelt** [comment]
I think something like this becomes a lot easier now that #980 has been merged. We could setup an additional vvv-wp-versions repo or similar that provides the nginx config and all of the various WP versions as needed.

**Comment by tomjn** [comment]
This is implemented in https://github.com/Varying-Vagrant-Vagrants/custom-site-template via the `wp_version` custom flag
