### ISSUE TITLE
Provide "unstable" branches

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#534]
@jeremyfelt what do you think about creating branches with unstable/testing features and changes? e.g.
- `1.3` - everything for the next release
  - `1.3/featureXY` - testing new features for merge in the next release
- `2.0` - major "breaking" changes (like the box-name feature)
  - `2.0/featureXY` - testing a new feature for inclusion
This way we can keep the `master` branch stable

**Comment by jeremyfelt** [comment]
I have been thinking about going to a `develop` branch workflow where `master` is always stable. I'd still like to keep things pretty lean though. I'm definitely open for feature branches in general.

**Comment by michaelbeil** [comment]
It'd be great to add a develop branch where further testing can take place before being merged into master.

**Comment by jeremyfelt** [comment]
More +1 on this. :) I'm going to move to `develop` as the default branch and leave `master` as the "stable" release. PRs can be made against `develop`, but if they're deemed to be large, likely unstable, features, we can adjust on the fly to create a feature branch.

**Comment by jeremyfelt** [comment]
"Fixed" in ab282e34c606f0df9
