### ISSUE TITLE
xip.io custom domains.

### ISSUE THREAD

**Issue by grappler** [Varying-Vagrant-Vagrants/VVV#536]
I was able to get http://192.168.50.4.xip.io/ to return the same as vvv.dev but I when I access http://local.wordpress.dev.192.168.50.4.xip.io/ I get vvv.dev. local.wordpress.dev works fine.

I added the changes in this PR https://github.com/Varying-Vagrant-Vagrants/VVV/pull/507

I am on Windows.

Any ideas what is going wrong?

**Comment by jeremyfelt** [comment]
Hi @grappler, sorry to leave you hanging. The address should be `http://local.wordpress.192.168.50.4.xip.io` (no `.dev`) once port forwarding is enabled.

**Comment by grappler** [comment]
Thanks @jeremyfelt it works now. Do you know how I can get it to work for a custom site that I have created?

**Comment by salcode** [comment]
@grappler How are you setting up your custom sites? 

## Using a Modified VVV Site Wizard
I'm using the VVV Site Wizard and I've modified it to include support for an xip.io url.  [Modified version of VVV Site Wizard for xip.io Support](https://github.com/salcode/vvv-site-wizard/).

You can see my modifications in this [commit 6f4236](https://github.com/salcode/vvv-site-wizard/commit/6f42369d5b91dca8eeba97331d39074573a34e61)

## Manually
In the custom site nginx config, I'm adding a regular expression __server_name__.

## Example

### Original __server_name__ without xip.io
```
server_name  genesis.dev;
```
### Modified __server_name__ with xip.io
```
server_name  genesis.dev ~^genesis\.\d+\.\d+\.\d+\.\d+\.xip\.io$;
```

I hope this helps.

**Comment by cfoellmann** [comment]
@jeremyfelt this is resolved.
CLOSE
