### ISSUE TITLE
Keep DB in the VM

### ISSUE THREAD

**Issue by ericmann** [Varying-Vagrant-Vagrants/VVV#539]
When we started working on VVV back in the day, we worked to mount a `/data` directory from the host into the VM so the actual database files would live on the host rather than inside the guest. This was great as it meant your local environment would survive `vagrant destroy`.

Unfortunately, it also means DB lookups, particularly against un-indexed fields, can be _painfully_ slow, particularly when using VirtualBox shares by default.

Considering we have better scripts for both exporting DB snapshots/dumps and re-ingesting them on a fresh `vagrant up` (or even `vagrant provision`), I'd argue that the need to store the DB files in the host filesystem has disappeared.

Furthermore, I'd like to argue for moving these files _back_ into the guest as _not_ using a shared directory will be much faster for file access.

**Comment by zamoose** [comment]
@ericmann 1.2 addressed this. Fresh installs won't do the host storage DB trick.

**Comment by ericmann** [comment]
Fair 'nuff. Was under the impression we had abandoned versioning a while ago, so I never caught this change.

**Comment by jeremyfelt** [comment]
FYI, a full history of this with related issue numbers is in #322.
