### ISSUE TITLE
Using git with themes within VVV

### ISSUE THREAD

**Issue by mxpimp47** [Varying-Vagrant-Vagrants/VVV#540]
I wanted to make sure it's ok to have a repo for my theme development inside the Wordpress default dir. When I ran the init it gave me the notice I'm within another repo (VVV) so I said to myself I better check the the devs. If I missed this question already asked I appoligize. If you have any recommendations for best practice with this scenario I would love to hear them! Thanks - Clayton

**Comment by jeremyfelt** [comment]
Hey Clayton, thanks for stopping by!

It's completely ok to setup a git repository within the VVV structure. We [exclude the stuff](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/.gitignore#L37-L38) in `www/` from the VVV repository, so there should never be a conflict.

**Comment by mxpimp47** [comment]
Ok, thank you for clearing thay up for me!

**Comment by thinkhuman** [comment]
@jeremyfelt That doesn't seem to be true for me. Inside my ```vagrant-local/www``` subfolder, ```git remote -v``` shows this:

```origin	git://github.com/Varying-Vagrant-Vagrants/VVV.git (fetch)```
```origin	git://github.com/Varying-Vagrant-Vagrants/VVV.git (push)```

In fact, *all* subdirectories inside the ```vagrant-local``` folder show the ```develop``` branch of that repo.

I work on several sites, using VVV and @bradp 's vv. For each of those sites, the theme files I work on are in a remote git repo. However, when I try to change the repo for each site, it changes the upstream repo for *every folder* inside ```vagrant-local```. I haven't seen this before. Any ideas?

**Comment by bradp** [comment]
You can try removing the `.git` folder in the base of VVV. That way there isn't anything besides your site-specific git repos touching git.

**Comment by thinkhuman** [comment]
Thanks @bradp . For some reason, I thought that VVV needed that git setup for updates. I'll try your suggestion.
