### ISSUE TITLE
Intermittent Nginx connection issues on Windows

### ISSUE THREAD

**Issue by petermac-** [Varying-Vagrant-Vagrants/VVV#542]
Vagrant up is completing successfully but I'm experiencing intermittent connection issues with Nginx.  Every few minutes I'll get a 404 Not Found error on a page that previously loaded fine.  Refreshing the page several times fixes the issue temporarily.  I checked all of the guest machine's log files but found nothing of value.  Any ideas on what could be causing this issue and how it can be fixed?

OS: Windows 8.1 Pro x64
Vagrant: 1.7.2
VirtualBox: 4.3.20 r96997

**Comment by petermac-** [comment]
I tried deleting the cache in Google Chrome and in Windows, restarting the dns cache service, and restarting the machine but I still had the same issue.

What eventually worked was using a different private network IP, bridged IP, and alias so I suspect this was a caching problem despite having cleared the DNS cache.

**Comment by jeremyfelt** [comment]
I may have noticed this problem in the past two when a second VM is running and conflicting somehow. Sometimes opening the VirtualBox GUI can highlight an issue. I've never been able to reliably reproduce it though.

**Comment by kressentolm** [comment]
This was definitely it, @jeremyfelt. If anyone has had issues with intermittent problems, take a look at the GUI. I was able to see that I had an old instance of VVV that was running against my new fresh install... I should have noticed that but thanks for the suggestion.

**Comment by fearlex** [comment]
Thank you @jeremyfelt This seems to have solved the issue for me.
