### ISSUE TITLE
Logs in /var/log/ have restrictive permissions

### ISSUE THREAD

**Issue by ericandrewlewis** [Varying-Vagrant-Vagrants/VVV#543]
When I log into the vvv box, I'm identified as the `vagrant` user on the machine. 

As this user, I don't have read access nginx error logs (`/var/log/nginx/error_log`) and other logs like mysql. 

Is this intentional? Should I be expected to switch to `root` to look at logs?

**Comment by zamoose** [comment]
This is the default for Debian and its derivatives (Ubuntu, Mint,
Cinnamon), RedHat/CentOS, and SuSE, at the very least. Log-viewing is
generally considered a matter of security and sensitivity under *NIX and so
most entries in /var/log get access-controlled.

On Sun, Jan 11, 2015 at 10:17 PM, Eric Lewis <notifications@github.com>
wrote:

> When I log into the vvv box, I'm identified as the vagrant user on the
> machine.
>
> As this user, I don't have read access nginx error logs (
> /var/log/nginx/error_log) and other logs like mysql.
>
> Is this intentional? Should I be expected to switch to root to look at
> logs?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/543>.
>



-- 
-Doug

**Comment by TobiasBg** [comment]
Doesn't that log get mapped to the host machine (`vvv-folder/log/`), per https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/Vagrantfile#L127?

**Comment by zamoose** [comment]
/srv/log != /var/log

--
Doug Stewart

**Comment by TobiasBg** [comment]
Ah, my bad, hadn't spotted that difference.

**Comment by ericandrewlewis** [comment]
Would syncing the `/log` folder on the host machine's vvv dir to `/var/log` inside the virtual machine be more helpful?

**Comment by cfoellmann** [comment]
We need to define logging like this https://github.com/cfoellmann/varying-vagrant-vagrants/blob/feature/provision-split/www/vvv-sites/local.wordpress.dev/vvv-nginx.conf#L13-L14 , right?
I hope we can move in #319 soon

**Comment by jeremyfelt** [comment]
Right now only PHP logs are saved to `/srv/log/` - 2cf4497fa2d12e9bb27aeb06b267e4e937a1d3f5

I think it could be useful to start saving others. #319 is definitely a priority before moving on other stuff as it may change how we handle this on a per site level.

As for permissions inside the box, as @zamoose said - this is normal in a production environment and should likely remain in VVV. When bouncing off a wall, `sudo !!` :)

**Comment by jeremyfelt** [comment]
> #319 is definitely a priority before moving on other stuff as it may change how we handle this on a per site level.

I take that back. We should just make sure that logs are easily accessible. I think we should look at using `/var/log/` as the proper log location and mapping this to a log directory on the host machine.

**Comment by rene-hermenau** [comment]
@jeremyfelt is this already done?

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1495 moves the mysql logs to `/srv/log`

**Comment by Mte90** [comment]
I see this error right now with the latest version on git:
```
    default: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
    default: 2018/05/15 13:06:36 [emerg] 19070#19070: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
    default: nginx: configuration file /etc/nginx/nginx.conf test failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command                                                                                                                                             
should be in the log above. Please read the output to determine what                                                                                                                                                
went wrong.  
```
I created the folder manually and now start without issue

**Comment by tomjn** [comment]
That bug has already been fixed:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L446

**Comment by tomjn** [comment]
For reference, the log changes were reverted, and moved to `/var/log` again, and the log vagrant mount was changed to `/var/log`
