### ISSUE TITLE
.dev domain namecollisions

### ISSUE THREAD

**Issue by wturrell** [Varying-Vagrant-Vagrants/VVV#544]
I'm finding, I can no longer access .dev sites served by vagrant from my (host) browser, even with the usual hosts file entries present and correct.

This is apparently due to something [ICANN did on purpose](https://icann.org/namecollision) – namely unused `.dev` and certain other domains are resolved to 127.0.53.53 to alert people to name collisions;  .dev is now, or soon will be, a valid TLD…

Weirdly though, the hosts file entries added by [hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) (192.168.50.4 for `vvv.dev` and the various WordPress branches) are being ignored by everything except Google Chrome – no matter how many times I restart the browser / clear it's history / clear the OS X DNS cache etc.

1) is there a way to make the browser/system honour /etc/hosts regardless? 
2) should we change .dev to something else in the project to avoid future confusion – e.g. `.vvv`?

**Comment by wturrell** [comment]
[Asked about this on StackOverflow](http://stackoverflow.com/questions/27928920/127-0-53-53-name-collisions-hosts-file-ignored/) and subsequently discovered the cause; if /etc/hosts file is a symlink OS X does a DNS lookup first and only looks at /etc/hosts if it doesn't resolve.

Unclear why Chrome still worked (and it was only Chrome stable that did, not Canary.)

**Comment by cfoellmann** [comment]
I am on Windows and do not have the issue but I like the idea of using `.vvv`

**Comment by evelynriossf** [comment]
Thanks for this answer.  I had a similar problem while using Bedrock with VVV. For me, the problem only manifested with Chrome 40.0.2214.111 (64-bit) on OSX, and not with any other browser (Firefox, etc..).
Changing .dev to .vvv fixed the problem, as it doesn't resolve.

**Comment by jeremyfelt** [comment]
Interesting stuff. `.dev` has always been weird, though seemed appropriate. I wouldn't mind switching to `.vvv` at some point in a backward compatible way.

**Comment by morganestes** [comment]
Just to update this, I'm starting to get errors from ICANN when trying to view VVV sites in Chrome (47.0.2526.106 on OS X 10.11.2):

    dial tcp 127.0.53.53:80: connection refused

I can view the site by IP in Chrome, and by domain name in Safari. Dig returns the message:

    vvv.dev.		3599 IN	TXT "Your DNS configuration needs immediate attention see https://icann.org/namecollision"

It looks like my hosts file is being ignored because sure, why not?

**Comment by evelynriossf** [comment]
Morganestes, could be a symlink issue. As Wturrell mentioned earlier in the thread " if /etc/hosts file is a symlink OS X does a DNS lookup first and only looks at /etc/hosts if it doesn't resolve." That was the same issue I encountered earlier this year.

**Comment by morganestes** [comment]
@evelynriossf I thought about that, but my hosts file isn't symlinked and I'm not running any other hosts files, either. It's only Chrome and `dig` that are having problems; Safari, Firefox, and `ping` all return the correct site.

I did a full halt and reload, and it's working again in the browsers (`dig` still returns the ICANN notices). This kind of thing is just going to keep creeping up as Google updates Chrome and ICANN starts to enforce new, unused TLDs.

**Comment by f4bsch** [comment]
Regarding long term support, there is no other option than `.local` or `.localhost`, since `.vvv` or `.test` or anything else might be available in (far) future.

**Comment by GhostToast** [comment]
This issue just popped up for me overnight as well, and it turned out TunnelBear Chrome extension was engaged. In case that rings true for anyone else.

**Comment by jeremyfelt** [comment]
Aligning some things and closing this ticket in favor of #583. I should pay attention in the future as to what was opened first before linking to the other. :)

Thanks for the conversation here everyone!
