### ISSUE TITLE
vvv-nginx.conf not picked up from a site folder

### ISSUE THREAD

**Issue by ericandrewlewis** [Varying-Vagrant-Vagrants/VVV#545]
Looking at the [auto site setup notes on the nginx config file](https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Auto-site-Setup#nginx-config), I assumed that placing a file named `vvv-nginx.conf` inside a site's folder (e.g. `www/my-site/vvv-nginx.conf`) would get copied to the right location for nginx. However, this did not happen. The docs aren't clear here - where is a `vvv-nginx.conf` file supposed to go?

**Comment by ericandrewlewis** [comment]
Sorry - didn't realize, this acutally does happen. Copies inside the virtual machine, doesn't copy files on the host machine.

**Comment by jeremyfelt** [comment]
:+1: Thanks for clarifying the docs in the wiki!
