### ISSUE TITLE
Auto Site Setup instructions for domain setup don't work

### ISSUE THREAD

**Issue by ericandrewlewis** [Varying-Vagrant-Vagrants/VVV#546]
The [instructions for domain auto-setup](https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Auto-site-Setup#the-domains-for-your-site) imply the provisioner will add a line to your host's `/etc/hosts` file, but this isn't true - this happens only in the virtual machine. Is there an automated way to do this?

**Comment by westonruter** [comment]
It does if you have the `vagrant-hostsupdater` plugin installed.

**Comment by ericandrewlewis** [comment]
> It does if you have the vagrant-hostsupdater plugin installed.

Got it installed, no :game_die: :game_die:

**Comment by ericandrewlewis** [comment]
I have a feeling this may happen because I'm running `vagrant provision` rather than `vagrant reload`, since it looks like the changes on the host are described in the Vagrantfile. I'll confirm that in a sec and modify the docs accordingly.

**Comment by ericandrewlewis** [comment]
Yep, that's it.

**Comment by jeremyfelt** [comment]
Running `vagrant up` again will trigger this as well, even if the machine is already running. That can be a bit quicker than `vagrant reload`.
