### ISSUE TITLE
vagrant halt returned a failed exit code. Run `vagrant up` first.

### ISSUE THREAD

**Issue by andresandres** [Varying-Vagrant-Vagrants/VVV#547]
Even though VVV was installed and is working properly but vagrant halt returns as failed. 

![vagrant_halt_status](https://cloud.githubusercontent.com/assets/5767459/5751904/43be0416-9c20-11e4-906c-28bee786d33f.png)

Am I doing something wrong?

Thanks,
Andy

**Comment by jeremyfelt** [comment]
Did you use `sudo vagrant up` to start? I ran into some serious trouble with that the other day and a virtual machine ended up in another universe. Take a look at the VirtualBox GUI and see what machines it reports.

**Comment by andresandres** [comment]
Thanks for the response @jeremyfelt. So I decided to re-install everything to ensure I ran everything using sudo and got this...

![vm_vagrant_error](https://cloud.githubusercontent.com/assets/5767459/5753738/980f5da4-9c42-11e4-89d5-bac18ec24325.png)

which changed while writing this to the previous image.

**Comment by andresandres** [comment]
So after a lot of debugging I found that if you install VVV on a hard drive other than "/home" you  will get  " `vagrant halt returned a failed exit code. Run vagrant up` " or " `.bash_profile: permission denied` " even though it was running properly. In order to fix it I had re-install [ubuntu on 2 hard drives] (http://www.linuxbsdos.com/2014/05/31/dual-boot-ubuntu-14-04-windows-7-on-a-pc-with-2-hdds-and-uefi-firmware/). 

So it seems like VVV or Vagrant, I'm not sure which, in order to work properly it needs to be installed on the drive where "/home" is installed.

Andy
