### ISSUE TITLE
Weirdness pulling in submodules

### ISSUE THREAD

**Issue by hilja** [Varying-Vagrant-Vagrants/VVV#549]
I was using WordPress Skeleton that has WP as submodule and wrote a little init script that clones the repo and pulls in submodules:

``` bash
install_wp_from_git() {
    message_install_wp \
    && mkdir htdocs \
    && cd htdocs \
    && git clone $GIT_REPO . \
    # The problematic line
    && git submodule update --init \
    && cd ..
}
```

The cloning works fine, if I have defined submodules in `.gitmodules` like following:

```
[submodule "wp"]
    path = wp
    url = git://github.com/WordPress/WordPress.git
```

But not if using the SSH clone URL:

```
[submodule "wp"]
    path = wp
    url = git@github.com:WordPress/WordPress.git
```

It gives an error:

```
==> default: Cloning into '.'...
==> default: Submodule 'wp' (git@github.com:WordPress/WordPress.git) registered for path 'wp'
==> default: Cloning into 'wp'...
==> default: Host key verification failed.
==> default: fatal: Could not read from remote repository.
==> default:
==> default: Please make sure you have the correct access rights
==> default: and the repository exists.
==> default: Clone of 'git@github.com:WordPress/WordPress.git' into submodule path 'wp' failed
```

I have authenticated to GitHub, and I'm able to clone via SSH and init submodules in the VM command line, so the authentication seems to be working, but in VVV only with this URL format: `git://github.com/WordPress/WordPress.git`. Host machine authentication also works.

Maybe this is a common thing that I had no idea of. All the docs say that SSH URL structure can be used to when adding submodules.

**On a related note:** is there a way to show the progress when pulling in the submodules? It might take up 15 minutes to pull in WP, and VVV just sits there looking dead.

**Comment by jeremyfelt** [comment]
Hey @hilja, sorry no response ever came.

It sounds like some of this may be related to #360. I wonder if the same thing would happen with the HTTPS repository vs the git repository.
