### ISSUE TITLE
Running multisite with WP in own directory

### ISSUE THREAD

**Issue by almhorn** [Varying-Vagrant-Vagrants/VVV#552]
Hi, 

Trying to run a subdirectory multisite installation with Wordpress in it's own directory. Is there support for that or do I need to add something to the nginx config?

**Comment by grappler** [comment]
There is a multisite version here https://github.com/Varying-Vagrant-Vagrants/vvv-multisite

**Comment by almhorn** [comment]
@grappler Yes I'm aware of that but it's only for subdomains and not subdirectories. And again, the problems appear when giving wordpress it's own directory in /wp instead of having it in the root (it works just fine with wp-includes and wp-admin directories in the root).

**Comment by aubreypwd** [comment]
What I do is tell NGINX to pull from `/wp` or whatever your WordPress install is in. Then, of course, make sure and not use `/wp` in `home_url`, etc. I only have to do this on sub-directory sites, not sub-domains.

**Comment by almhorn** [comment]
@aubreypwd would you mind sharing your nginx config for reference?

**Comment by cfoellmann** [comment]
I can add a configuration to https://github.com/Varying-Vagrant-Vagrants/vvv-multisite later.
I am not 100% sure what your desired network looks like.

Is the URL `http://subfolder.dev/wp/<site-slug>` , right?

**Comment by almhorn** [comment]
The URL should be http://example.dev/ and http://example.dev/site2 http://example.dev/site3 etc. 
So the wp directory should not be in the URL. 

The folder structure looks like this: 
```
wp-config.php
wp-content
 - themes
 - plugins
 - etc. 
wp
 - wp-admin
 - wp-includes
```

**Comment by cfoellmann** [comment]
That is the same folder structure I use. But with subdomains.
Config coming up

**Comment by cfoellmann** [comment]
@almhorn have a look at this https://github.com/cfoellmann/vvv-multisite/tree/move-wp-content/wpmu-subdirectory.dev - Changes see https://github.com/cfoellmann/vvv-multisite/commit/d02e98bf53ed7f2e42eaee4a8ca3c911d10491bb

**Comment by almhorn** [comment]
@cfoellmann that doesn't seem to work. The only thing the provision script does is to install WordPress in the /wp directory right? And the you have an alias for wp-content directory in the nginx config. 
I'm still just able to access the main site.

**Comment by cfoellmann** [comment]
there is also the change in wp-config.php.
I provisioned the subdirectory multisite without the wp-content outside of wp and it works. https://github.com/Varying-Vagrant-Vagrants/vvv-multisite/tree/master/wpmu-subdirectory.dev

**Comment by aubreypwd** [comment]
@almhorn, here's a good example.

```
server {
	listen		80;
	root 		/var/www/dbrains.dev/wp;
	index 		index.html index.htm index.php;
	server_name wpmdb1-release-dir.aubreypwd.com;
	client_max_body_size 100M;
}
```

**Comment by almhorn** [comment]
Thanks @aubreypwd but I think you misunderstood me here. I have WordPress Core in a separate directory (/wp/) and not a separate site. I'm taking another swing at @cfoellmann's solution...

**Comment by cfoellmann** [comment]
@almhorn my config is flawed. I am currently fixing it.

**Comment by cfoellmann** [comment]
It took me some time because of Virtualbox issues and the constant provisioning but I think I fixed it https://github.com/cfoellmann/vvv-multisite/tree/move-wp-content

**Comment by cfoellmann** [comment]
@almhorn did my latest fixes work for you?

**Comment by almhorn** [comment]
@cfoellmann haven't had the chance to try it yet, was in quite a hurry so just moved Core out to the root instead. I've found some other issues on WordPress trac that relates to this so I'll try it again soon and let you know. And thanks!

**Comment by cfoellmann** [comment]
@almhorn any news?

**Comment by kraftner** [comment]
I just tried it and it seems to work. But I think what @almhorn was trying to achieve was a little bit different from your setup.

You're moving the install to /wp, including wp-config.php and set this as the document root and then alias the wp-content from one level above.
```
wp-content
 - themes
 - plugins
 - etc. 
 wp
 - wp-admin
 - wp-includes
 - wp-config.php
 - etc.
```
What @almhorn (and me too) seem to be trying is something like this:

```
wp-config.php
wp-content
 - themes
 - plugins
 - etc. 
 wp
 - wp-admin
 - wp-includes
 - etc.
```

I've come to realize that this needs some changes to the rewrite rules, something along those lines:

```
if (!-e $request_filename) {
   rewrite ^(/wp-.*\.php)$ /wp$1;
   rewrite ^(/wp-.*) /wp$1;
}
```
But I haven't properly tested this yet.

**Comment by cfoellmann** [comment]
you can always move the `wp-config.php` one level up. WP looks for it there automatically.
Your visualization shows the WP main directory within `wp-content`? Can be right, right?
Must be on the same level as `wp-content`

**Comment by kraftner** [comment]
Sorry, formatting error. Fixed that.

I just tried moving it up. Had some weird errors I haven't looked in yet so I guessed it might have something to do with the changed document root.

**Comment by kraftner** [comment]
Okay I just had to adapt `WP_CONTENT_DIR`. Sorry for the mess. Everything is working like it should.
