### ISSUE TITLE
Errors after vagrant up — all .dev sites produce 404

### ISSUE THREAD

**Issue by josiahwiebe** [Varying-Vagrant-Vagrants/VVV#553]
After running the initial `vagrant up` command, I'm unable to open any of the default .dev pages. 

I tried doing some searching in the issues, and found a few similar issues, but none quite the same. I ran `vagrant halt` and `vagrant provision` a few times, as well as trying to use `vagrant destroy` to destroy and rebuild the machine to no avail. 

I also removed the machine completely and re-downloaded this repo in another attempt, to no avail. 

I have [Pow](http://pow.cx) installed on my machine and am wondering if that might be an issue? Although I have successfully used VVV on a different machine with Pow installed.

**Comment by cfoellmann** [comment]
Lately the provision process failed because the grunt process for the wordpress-develop repos hangs. Everytime.

I just remove the develop repo for now

**Comment by josiahwiebe** [comment]
Thanks, I'll try that. Perhaps a SVN issue?

```bash
==> default: Updating WordPress Stable...
==> default: Success: WordPress is up to date.
==> default: Updating WordPress trunk...
==> default: Updating '.':
==> default: At revision 31266.
==> default: Updating WordPress develop...
==> default: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
==> default: svn: E155004: Working copy '/srv/www/w==> default: svn: E155004: Working copy '/srv/www/w==> default: svn: E155004: Working copy '/srv/www/w==> default: svn: E155004: Working copy '/srv/www/wordpress-develop' locked.
==> default: svn: E155004: '/srv/www/wordpress-develop' is already locked.
==> default: Updating npm packages...
==> default: Initializing grunt in WordPress develop... This may take a few moments.
==> default: A valid Gruntfile could not be found. Please see the getting started guide for
==> default: more information on how to configure grunt: http://gruntjs.com/getting-started
==> default: Fatal error: Unable to find Gruntfile.
```

**Comment by cfoellmann** [comment]
My error was different.
The grunt process just stuck and I had to abort provisioning hard.
