### ISSUE TITLE
Question regarding obtaining files from the vagrant

### ISSUE THREAD

**Issue by miketricking** [Varying-Vagrant-Vagrants/VVV#554]
This may sound like a silly question but I am quite new to this at the moment and any help would be greatly appreciated. 

I'm curious on how to get a copy of the files from the vagrant. Say for example you developed a theme in the vagrant in wp-content/themes and you were happy with it and wanted to obtain this copy theme you have created.

What would be the best way to obtain it from the vagrant so a copy is then on your local machine?

Thank you

**Comment by cfoellmann** [comment]
The directories you WP site _lives_ in is mapped to your host machine.
It is in the `www/*` folder. You have your theme under this folder. That way you always have access to make your changes/develop your stuff. So it never really leaves the host machine

**Comment by cfoellmann** [comment]
@miketricking I hope this is resolved and you are now a happy VVV user.
If this is cleared up close this issue, please. Otherwise just ask what is still unclear.

**Comment by miketricking** [comment]
Perfect, thank you
