### ISSUE TITLE
Unable to install/update themes in synced folder

### ISSUE THREAD

**Issue by Pezzab** [Varying-Vagrant-Vagrants/VVV#555]
I can't install or update themes in my config.vm.synced_folder any more (getting permissions errors in the WP dashboard).

I've attempted chmod on my synced folder but weaker permissions don't have any effect.

If I revert to keeping themes within the vagrant box there are no issues.

The only major change I can think I've made to my system recently is the upgrade to Yosemite.

**Comment by ezekg** [comment]
Could you post the `config.vm.synced_folder` line within your Vagrantfile here? If I remember correctly, I had the same issue and resolved it by providing`mount_options` for the synced folder.

```ruby
config.vm.synced_folder "path/to/local", "path/to/vm", mount_options: ["dmode=777", "fmode=777"]
```

**Comment by Pezzab** [comment]
Much appreciated @ezekg, odd that it wasn't needed before.

Now found mount_options over in the Vagrant docs though I probably wouldn't have figured out the syntax based on what's there.

Cheers!

**Comment by ezekg** [comment]
No problem, glad it worked!

**Comment by cfoellmann** [comment]
I do not really understand the issue and what you did to resolve it.
Is there anything we need/can change in VVV to make it work on Yosemite "out-of-the-box"?

**Comment by Pezzab** [comment]
Hi @cfoellmann - @ezekg's solution got it working again. Looks like there was no issue, though I didn't have to include mount_options before.

**Comment by cfoellmann** [comment]
So this is a custom folder you are syncing? The VVV mappings are all working correctly?

**Comment by Pezzab** [comment]
That's right. Just to be clear I work on themes and plugins in external folders and have VVV synced with these (this way I can keep my themes in a Dropbox folder so they are backed up while I work on them)

**Comment by cfoellmann** [comment]
OK. Please close this issue.
