### ISSUE TITLE
synched_folder only creates empty directories

### ISSUE THREAD

**Issue by Daronspence** [Varying-Vagrant-Vagrants/VVV#556]
So I added a `Customfile` to my VVV directory and added the following lines
```
if vagrant_version >= "1.3.0"
   config.vm.synced_folder "~/plugins/", "/srv/www/acfwidgets.demo/htdocs/wp-content/plugins/", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
end
```
When I run `vagrant reload` (or something similar) I can see it creating the folder in the console output
```
/srv/www/acfwidgets.demo/htdocs/wp-content/plugins => /Users/daron/plugins
```
However, that created (or merged) folder is completely empty. No files, no other folders, nothing. I'm pulling my hair out because I can't figure this out. This is almost the exact same include that is used by vvv itself for the www directory. What is going on?

**Comment by zamoose** [comment]
Silly question:
What's in ~/plugins? Is there anything there on your Mac?

--
Doug Stewart

**Comment by Daronspence** [comment]
Yes, two folders with files in each as well an empty php file I added just
to see if anything would copy.

**Comment by Daronspence** [comment]
Ah ok I think I figured it out. I got the stuff to sync up. Is there anyway I can concatenate the synced folder with the one that is there?
