### ISSUE TITLE
vagrant provision fails - http for WordPress repo vs https

### ISSUE THREAD

**Issue by jeckman** [Varying-Vagrant-Vagrants/VVV#561]
Running vagrant provision returns these errors:

svn: E120108: Unable to connect to a repository at URL 'http://core.svn.wordpress.org/trunk'

svn: E120108: Unable to connect to a repository at URL 'http://develop.svn.wordpress.org/trunk'

Looks to me like the repo does respond to their https versions - where would I change that for my existing develop and trunk sites inside vagrant?

Perhaps the issue is just that the http versions are down and will be back, but it would be nice to get them over https if one so chooses

**Comment by jeckman** [comment]
Here's what I did. 

sudo vagrant ssh 
cd /vagrant/www/wordpress-trunk
svn relocate https://core.svn.wordpress.org/trunk

cd /vargrant/www/wordpress-develop
svn relocate https://develop.svn.wordpress.org/trunk

--

Will this persist now across vagrant up/down?

**Comment by cfoellmann** [comment]
that will be fine on up/down and even when you re-run provision.

**Comment by jeremyfelt** [comment]
It would be nice to detect existing `http` checkouts and run `svn relocate` during provisioning now that we're using the HTTPS repositories.

**Comment by jeremyfelt** [comment]
At this point it's probably better to make sure this scenario is well documented either as a FAQ via #605 or in the wiki. We've been forced HTTPS a while now and I haven't heard much.

We should document this as part of the 1.3.0 changelog.

**Comment by jeremyfelt** [comment]
It looks like we did this in 9c1d453b4d2b271a4fa520a7ba8cc39035b65d61 :)
