### ISSUE TITLE
wp-cli support for local machine

### ISSUE THREAD

**Issue by EHLOVader** [Varying-Vagrant-Vagrants/VVV#563]
Opening an issue here from [generator-vvv](https://github.com/lkwdwrd/generator-vvv/issues/39) I figured out that it can be accomplished in core and would benefit more this way.

> wp-cli is used in the VM for installation and configuration, but it would be really nice to have wp-cli support from outside the VVV VM. This should be possible through a custom wp-cli.yml in the project path.

> You could define the database connection for the VM using the external user and then you can use some of the scaffolding tools offered. I do foresee an issue with the folder paths however.

I actually have an implementation so I will be able to submit a PR for this shortly.

**Comment by cfoellmann** [comment]
would this allow me to open a cmd in the mapped folder on my host machine and use `wp` to be applied to the vm code?
If so :+1: :+1: :+1:

**Comment by EHLOVader** [comment]
Yes, it works that way for me. 

It uses the external user settings to connect to `vvv` from the VM host machine instead of connecting to `localhost` from the VM itself.

**Comment by jeremyfelt** [comment]
This was merged into `develop` (and accidentally `master` 😁) via #564.
