### ISSUE TITLE
Unable to get public_network setting to work

### ISSUE THREAD

**Issue by salcode** [Varying-Vagrant-Vagrants/VVV#566]
Based on @jeremyfelt's [Various Networking Configurations in VVV](https://jeremyfelt.com/2015/01/31/various-networking-configurations-vvv/), I'm attempting to get the Public Network option working but thus far I've been unsuccessful.

In __Vagrantfile__, I've uncommented the line
```
config.vm.network :public_network
```
and performed a `vagrant reload`.

I choose __en0: Wi-Fi (AirPort)__, as I am accessing the network via Wi-Fi (see [details here](https://gist.github.com/salcode/b09f6d10978d42b38619#file-bridged-network-interfaces-txt)).
Then I run `vagrant ssh` and `ifconfig`.  Based on the [ifconfig result](https://gist.github.com/salcode/b09f6d10978d42b38619#file-ifconfig-response-txt), I assume the IP address is `10.0.2.15`.

When I go to `http://10.0.2.15/` from my host computer (or from another computer on the network), I get  Chrome's __This webpage is not available__ message.

Are others successfully using the __public_network__ option?

## Setup Details
- OS X 10.9.5
- VVV 1.2.0
- VirtualBox 4.3.20 r96996
- Vagrant 1.7.2

**Comment by salcode** [comment]
Adding a specific IP address,
```
config.vm.network :public_network, ip: "10.0.1.114"
```

And still selecting __en0: Wi-Fi (AirPort)__

Results in `http://10.0.1.114/` working on my local machine but not other machines on the network.

[ifconfig results](https://gist.github.com/salcode/cee499746cdd383ffff4)

**Comment by cfoellmann** [comment]
I havent played with this but if I understand it right you would need to use the ip of your vagrant host (the machine running virtualbox) from a second machine. That should forward the request to the vm.

**Comment by salcode** [comment]
@cfoellmann 
I agree with your description of the expected behavior, unfortunately this is not the behavior I'm seeing.  I've tested this again and outlined my changes, expected, and actual behavior below.

I'm happy with the [VVV port forwarding solution](http://salferrarello.com/vagrant-vvv-setup-wordpress/#vvv-customfile), I currently have in place but I am concerned others trying this public network option will have the same experience I've had.

Changes Implemented
-------------------------------

#### Comment out private network
```
  # config.vm.network :private_network, ip: "192.168.50.4"
```

#### Uncomment public network
```
config.vm.network "forwarded_port", guest: 80, host: 8080
```

#### Restart the VM with the new settings
```
$ vagrant reload --provision
```

#### Determine Local IP Address of the Host Machine
```
$ ipconfig getifaddr en0
```
Result is http://10.0.1.6/  
(This is definitely the local ip address for the host machine, as I have used this to access MAMP on this machine today as well)

Expected
-------------

After restarting, going to http://10.0.1.6/ will load the VVV default page which lists the links to tools like phpMyAdmin and the default sites.

Actual
---------

After restarting, going to http://10.0.1.6/ results in 
> This webpage is not available
> ERR_CONNECTION_REFUSED

**Comment by cfoellmann** [comment]
Let's keep this open for others to find and possibly help.
I don't have the time (and the need) to look into this myself.

**Comment by JPry** [comment]
@salcode Is this still an issue for you with a new VVV implementation? I'm asking because I'm doing something slightly different with the public network, and I had this working for me today. I commented out this default line:

```
config.vm.network :private_network, ip: "192.168.50.4"
```

and uncommented this line:

```
config.vm.network :public_network
```

This is different from the port forwarding you mentioned, but I'm curious if the port forwarding is still broken for you.

**Comment by salcode** [comment]
@JPry I just:

### 1. Updated to the latest version of VVV on `master`

### 2.  Made the changes you listed

![image](https://cloud.githubusercontent.com/assets/5194588/8778964/c2b7f22c-2ece-11e5-8a50-271c03b148ea.png)

### 3.  Booted up (with `vagrant up --provision`)
Chose `1) en0: Wi-Fi (AirPort)`

![screenshot 2015-07-20 10 32 49](https://cloud.githubusercontent.com/assets/5194588/8778938/967d9496-2ece-11e5-9745-39ffa286bf8e.png)

### 4.  Attempted to go to http://10.0.1.6/
This is my machine's local IP address, as determined by `ipconfig getifaddr en0`

## Result:
This webpage not available
![image](https://cloud.githubusercontent.com/assets/5194588/8779057/4f0699e0-2ecf-11e5-99ef-b0eacdac9435.png)

I also attempted http://vvv.dev/, which did not work (which makes sense since it is mapped to 192.168.50.4).

Should I be trying to visit a different IP address for the URL?
Can you clarify how you got it to work?

**Comment by JPry** [comment]
@salcode 

> Should I be trying to visit a different IP address for the URL?

Yes. The virtual machine should have its own IP address assigned by your router. So it will **not** be the address for your host machine, and it will not be the normal 192.168.50.4 that is created. When I set up my vagrant with public networking, I had an address in the 192.168.1.x block.

Running `ifconfig` on the vagrant should reveal all interfaces, and since your local machine has an IP of 10.0.1.6, I would expect the vagrant to also be in the 10.0.1.x range.

**Comment by JPry** [comment]
@salcode It's worth noting that I ended up using the `Customfile` to set up public networking instead of modifying the `Vagrantfile`. So in the end, I had multiple networking devices on the guest machine:

```
vagrant@vvv:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:cf:da:f3  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fecf:daf3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:120157 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41949 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:133209210 (133.2 MB)  TX bytes:3180167 (3.1 MB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:4a:23:7b  
          inet addr:192.168.1.30  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe4a:237b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:325 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:33102 (33.1 KB)  TX bytes:1522 (1.5 KB)

eth2      Link encap:Ethernet  HWaddr 08:00:27:17:c8:06  
          inet addr:192.168.50.4  Bcast:192.168.50.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe17:c806/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:26 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4922 (4.9 KB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by salcode** [comment]
@JPry 

Ha ha, brilliant.  This works for me on http://10.0.1.4/

Thank you for helping me understand that the virtual machine gets a new (separate) IP address assigned to it.  This was my misconception that was creating such a road block.

It is interesting that the IP address is on `eth1` even though I'm accessing the network via WiFi (`eth0`) but I assume this is because from the perspective of the virtual machine, it thinks it is accessing a wired connection (which is all part of the VirtualBox magic).  I apologize for all these notes but I anticipate they may be helpful to me (or others) in the future.

![image](https://cloud.githubusercontent.com/assets/5194588/8779629/45d3686e-2ed2-11e5-9aae-16e24dab2113.png)

:+1: on using the `Customfile` for your modifications so you can update VVV without worrying about changes

Now I need to decide if I'm going to move away from my port forwarding solution in favor of this public IP solution.  Am I correct you prefer this public IP solution?

**Comment by JPry** [comment]
@salcode 

> Now I need to decide if I'm going to move away from my port forwarding solution in favor of this public IP solution. Am I correct you prefer this public IP solution?

Personally I think the public IP is a bit cleaner, but of course it also has drawbacks:

* (I *think*) you need to `vagrant reload --provision` if you change Wifi access points.
* New IP if you change Wifi access points (after vagrant reload)
* If you're on public Wifi (vs. being at your own home/office), then anyone else can get to your vagrant too.

I would say as long as I'm working at home on my own network, I like the public IP route. But if any of the above apply to your work situation, it might be easier for you to go with the port forwarding option (if it's working correctly), so that you only ever need to know your local IP.

So... TL;DR is "It depends" 😉

**Comment by salcode** [comment]
@JPry 

1.  I think the port forwarding option should have this same drawback.
> If you're on public Wifi (vs. being at your own home/office), then anyone else can get to your vagrant too.

**Comment by salcode** [comment]
@JPry 

I think the port forwarding option has this same drawback
> If you're on public Wifi (vs. being at your own home/office), then anyone else can get to your vagrant too.

With port forwarding, I do __not__ need to `vagrant reload` or `vagrant reload --provision` when changing Wifi access points.  I almost always `vagrant suspend` and rarely _reload_ my Vagrant instance.

This is a deciding factor for me that will keep me using Port Forwarding.

I'm guessing there may be a command you can run to update the vagrant public IP (either from within the Virtual machine via `vagrant ssh` or from the host machine command line) but I don't know what it is.  This would put the Public IP and Port Forwarding more on the same level in my eyes.

**Comment by JPry** [comment]
My `Customfile`:

```ruby
  # Set up with a Public network
  config.vm.network :public_network
```

I've also found that you can do this with a `Vagrantfile` in `~/.vagrant.d/`. The benefit to that method is the same as the drawback: it applies to **all** of your vagrant instances, and not just a single one. In any case, here's the `~/.vagrant.d/Vagrantfile` I use:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Set up with a Public network
  config.vm.network :public_network
end
```
