### ISSUE TITLE
VVV for self-hosted live site

### ISSUE THREAD

**Issue by HughP** [Varying-Vagrant-Vagrants/VVV#569]
I am brand new to VVV. It is really awesome so far. I have a question about deployment. That is, I have my own mac mini server, in my office, with dynamic IP resolution (No-IP type). Is VVV the kind of thing that I could put on that server and attach to the web, if I wen through and changed the Passwords and usernames on Wordpress and MySQL.  Or are there other security concerns. I realize that this is probably out of scope of intended use cases for VVV, but perhaps someone here knows of a different vagrant set up for this use case, or an online tutorial/blogpost where this use case is discussed in relation to VVV?

**Comment by fa7ad** [comment]
I think VVV is more suited for a development environment.
You have a better shot at hosting using some other production-ready Vagrant box and install wordpress on it. maybe you can RSync between this vvv and the production box to update changes.
I would advise on using a different Hypervisor too, Virtualbox is really bad in terms of production-grade performance.
Try using [PuPHPet](http://puphpet.com/) to generate the configuration, _the site suggests a lot dos and don'ts_ "for production boxes". Or maybe give [ProtoBox](http://getprotobox.com/) a try for the configuration.

**Comment by jeremyfelt** [comment]
+1 for @fa7ad's explanation. This is definitely local environment only. You could technically use the bash provisioning on a production server so that it matches, though some tweaks are likely necessary. We do try to match what someone would consider a good, performant server configuration though.
