### ISSUE TITLE
access files in 'provision' folder within provision process

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#573]
how can I access files within the `provision` folder for usage within provision.php?
Is there a constant? Or what is the path while vagrant is provisioning?

**Comment by cfoellmann** [comment]
Maybe there is a constant for this but I will simply use the mapped vagrant folder `/vagrant/provision`

**Comment by jeremyfelt** [comment]
There may be an environment variable, but I'm not certain.
