### ISSUE TITLE
set PHPCS default to WordPress

### ISSUE THREAD

**Issue by pbearne** [Varying-Vagrant-Vagrants/VVV#574]
Hi Guys

Just little suggestion lets set the default standard to WordPress for the installed PHPCS 

this is the command needed
phpcs --config-set default_standard WordPress

Paul

**Comment by westonruter** [comment]
Actually, it should be `WordPress-Core`. The `WordPress` standard is a superset of all the standards and shouldn't be used in practice. And this command should only be run when first cloning the repo for the first time.
