### ISSUE TITLE
The SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by neilgee** [Varying-Vagrant-Vagrants/VVV#579]
Starting getting this error on vagrant up...

==> default: stdin: is not a tty
==> default: start: Job is already running: mysql
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

cant see it in log above....

neilg@[~/vagrant-wordpress]:(master) vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Checking for host entries
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/neilg/vagrant-wordpress
    default: /srv/www => /Users/neilg/vagrant-wordpress/www
    default: /srv/config => /Users/neilg/vagrant-wordpress/config
    default: /srv/database => /Users/neilg/vagrant-wordpress/database
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: start: Job is already running: mysql
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by neilgee** [comment]
I have run on the guest
```lsmod | grep vboxsf```
and get
```vboxsf                 43786  4 
vboxguest             248441  2 vboxsf```

**Comment by jeremyfelt** [comment]
Sorry for never replying to this. 😞 

My guess is that you've figured the issue out (or abandoned VVV). If not, feel free to reopen and discuss. It seems like it may have been an issue with local permissions and the `.vagrant` directory, but that's a wild guess at this point. :)
