### ISSUE TITLE
Centos VM Guest on Windows 7 

### ISSUE THREAD

**Issue by rsraider113** [Varying-Vagrant-Vagrants/VVV#582]
Is Centos/VirtualBox/Windows a configuration that is expected to work?

Cant get any Centos box (chef,nrel,6.5, 6.6, 7) setup  and running correctly on Virtualbox 4.3.22 on Windows 7.  Trusty64 installs and runs as expected.  

Primary problem is related to mounting shares, followed any and all suggestions found here, no luck

Have seen other comments on folks having problems with Centos, but most are not resolved.

**Comment by zamoose** [comment]
Package named, etc. differ significantly. This won't work out of the box. 



—
Doug

**Comment by zamoose** [comment]
Names*




Darn you autocorrect. 



—
Doug

**Comment by rsraider113** [comment]
Thanks Doug
