### ISSUE TITLE
Vagrant connection timeout and forcing shutdown

### ISSUE THREAD

**Issue by michaelavena** [Varying-Vagrant-Vagrants/VVV#584]
I'm using Vagrant for the first time on a Windows 8 machine (64-bit) and I can't get VVV to start properly.  Vagrant works fine by itself but VVV crashes shortly after starting.  I have already enabled the GUI and the machine gets to the login screen; in the console I get:

==> default: Machine booted and ready
==> default: Checking for guest additions in VM...
==> default: Checking for host entries
==> default: adding to (C:/Windows/system32/drivers/etc/hosts)

I get many of the last statements with a bunch of characters on the ends and then:

==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...

I've been searching for a solution of Google but nothing has helped so far.  Does anyone know what could be causing the issue?

**Comment by zamoose** [comment]
Make sure virtualization is enabled in your BIOS. 

--
Doug Stewart

**Comment by michaelavena** [comment]
I'm working on a new acer laptop, and from what I understand from looking online I cannot change the virtualization settings in the BIOS without a serious headache.  Is there any way around changing the settings?

**Comment by zamoose** [comment]
Alas, no. It's pretty much a necessity for things to work correctly for
VirtualBox.

On Fri, Mar 6, 2015 at 9:08 AM, michaelavena <notifications@github.com>
wrote:

> I'm working on a new acer laptop, and from what I understand from looking
> online I cannot change the virtualization settings in the BIOS without a
> serious headache. Is there any way around changing the settings?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/584#issuecomment-77563517>
> .
>



-- 
-Doug

**Comment by michaelavena** [comment]
Ok so maybe I fixed the issue?  I didn't do anything but it's not crashing anymore... I am getting a new error, however:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\micha_000>cd vagrant-local

C:\Users\micha_000\vagrant-local>vagrant-up
'vagrant-up' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\micha_000\vagrant-local>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/precise32' is up to date...
==> default: Setting the name of the VM: vagrant-local_default_1426201465554_189
90
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "1b382e91-5c72-4eaa-8c4b-25e0929e81db", "--nic1", "nat", "
--nic2", "hostonly", "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapte
r #3", "--cableconnected2", "on"]

Stderr: VBoxManage.exe: error: The machine 'vagrant-local_default_1426201465554_
18990' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), c
omponent Machine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at lin
e 471 of file VBoxManageModifyVM.cpp

C:\Users\micha_000\vagrant-local>

**Comment by jeremyfelt** [comment]
Could it be possible there's an issue with the `vagrant-hostsupdater` plugin? That it fails at that step seems suspect. Can you try removing the plugin (`vagrant plugin uninstall`)? Also, a full dump of the error text would be helpful.

In the end though, @zamoose is right. If virtualization is not enabled, things aren't going to be great.

**Comment by sugalvojau** [comment]
I am not sure if this is related, but I have exactly the same issue with the new instance made via PuPHPet. 

This is the log of vagrant up (CentOS case):
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/centos65-x64'...

[KProgress: 10%
[KProgress: 20%
[KProgress: 30%
[KProgress: 40%
[KProgress: 50%
[KProgress: 60%
[KProgress: 70%
[KProgress: 80%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/centos65-x64' is up to date...
==> default: Setting the name of the VM: nfq_default_1430665895880_35533
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 7371 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Checking for host entries
==> default: adding to (C:/Windows/system32/drivers/etc/hosts) : 192.168.56.108  nfq-test.dev  # VAGRANT: d5961f5a0cd7f57dc2d31fa160f34561 (default) / 11a07dd3-7f2c-4134-bf55-8b761007b618
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'puppet' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...

I cannot start any of new guest systems (nor Ubuntu Trusty 14.04 LTS x64, nor CentOS 6 x64). 
I am on Windows 8.1 Pro 64-bit host, Vagrant version is 1.7.2, VirtualBox version is 4.3.26 r98988.

**Comment by sugalvojau** [comment]
Just did vagrant up on the newly downloaded instance (https://github.com/sugalvojau/veikt.com - the vagrant instance resides in dev-helpers/vagrant). Running vagrant up on this instance works just fine.

I would assume that BIOS settings have nothing to do with the problem of immediate shutdown...
