### ISSUE TITLE
Install and enable FTP server by default

### ISSUE THREAD

**Issue by ericandrewlewis** [Varying-Vagrant-Vagrants/VVV#585]
While working on [#31528](https://core.trac.wordpress.org/ticket/31528) I'm installing vsftpd on my vvv instance following [Digital Ocean's tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-vsftpd-on-ubuntu-12-04) to test FTP as a filesystem method.

We should consider doing this for vvv's out-of-the-box installation.

**Comment by cfoellmann** [comment]
FTP is so old school :older_man: but I am pretty sure it would not hurt or slow down the VM

**Comment by jeremyfelt** [comment]
Agreed - see also #801 for similar core troubleshooting needs.

**Comment by cfoellmann** [comment]
@ericandrewlewis can you work on a PR for this?

**Comment by jeffslofish** [comment]
I can work on this. But would we want FTP or SFTP or both?

**Comment by tomjn** [comment]
Is this still wanted? IMO it should be implemented as a Utility rather than going in VVV core

**Comment by tomjn** [comment]
I'm going to close this one out. I agree it's useful, but a quick `ftp/provision.sh` that installs an FTP server in a VVV utility should suffice
