### ISSUE TITLE
phpMemcachedAdmin - Google Code is going down

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#589]
phpMemcachedAdmin is hosted on google code https://code.google.com/p/phpmemcacheadmin/  and as we know that one is going away.
I am not really confident that the dev is going to migrate the project to GH or anywhere else. I just sent him an email (I hope the mail address in the code is still active, otherwise someone with a LinkedIn premium account could contact him over LinkedIn) asking about his plans and the offer to move and maintain it on GH if he doesnt want to keep it.

**Comment by jeremyfelt** [comment]
Any word back from the author @cfoellmann? We could probably fork/host the current working version if needed.

**Comment by cfoellmann** [comment]
I got a reply from the author and he gave me the green light for making an official move to github. He has not abandoned the project completely but he just didnt get around to it.
I moved the code here https://github.com/wp-cloud/phpmemcacheadmin and published it on packagist https://packagist.org/packages/wp-cloud/phpmemcacheadmin
