### ISSUE TITLE
Apache mod_rewrite issues

### ISSUE THREAD

**Issue by andrew-boyd** [Varying-Vagrant-Vagrants/VVV#59]
First off, I've found this to be an incredible resource! Thanks to everyone involved for your hard work in putting this together. 

Secondly, I'm way over my head when it comes to server administration, so forgive me if this doesn't make complete sense. Best I can tell, mod_rewrite is not enabled with this setup which is resulting in some of my wordpress sites having issues with their URLs and properly loading page resources. 

It's also preventing me from using the .htaccess tip found here to look for assets that aren't found on local by checking the coresponding path on production (last code snippet in the article): http://stevegrunwell.com/blog/keeping-wordpress-under-version-control-with-git

If someone more gifted in this area than myself could get mod_rewrite working I'd be very thankful.

**Comment by strider72** [comment]
+1 on the possibility of running Apache on VVV

**Comment by ivcreative** [comment]
+1 to to make this use Apache which is more common on every webserver

**Comment by otjutt** [comment]
+1 in support for Apache.
