### ISSUE TITLE
Pulling latest WordPress trunk causes fatal error.

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/VVV#591]
Sometimes when I run a vagrant provision, it pulls the latest WordPress trunk, and it pulls in merge conflicts, EG:
```
<<<<<<< .mine
$wp_version = '4.2-alpha-31595';
=======
$wp_version = '4.2-alpha-31600';
>>>>>>> .r31581
```

How can I prevent this?

**Comment by jeremyfelt** [comment]
Hi @joelworsham, thanks for stopping by.

I haven't personally seen this problem and I've updated trunk with `vagrant provision`, by running `svn up` locally, and by running `svn up` inside the VM. Is there any chance a local change was made to the repository? It's strange that this would be a conflict.

**Comment by joelworsham** [comment]
Could updating to the latest nightly build in trunk from the WP admin dashboard update screen be an issue?

**Comment by cfoellmann** [comment]
Yes.
You should Never update via WP-admin. That screws up the svn repo

**Comment by joelworsham** [comment]
Good to know. That's probably my problem. Thanks @cfoellmann

**Comment by cfoellmann** [comment]
You can delete all files in the Wordpress folder except for the WP-content folder and the run the provision. That should reset to the current version
