### ISSUE TITLE
VVV and Continuous Integration

### ISSUE THREAD

**Issue by caseypatrickdriscoll** [Varying-Vagrant-Vagrants/VVV#593]
If I want to build a local ci/jenkins/selenium server, is there wisdom to running a second separate vagrant instance dedicated to testing, or should I install and run on vvv. It seems like an arbitrary distinction, but might be a performance thing? I'm naive to most of this currently.

Anyone have experience with this?

**Comment by cfoellmann** [comment]
What first comes to mind: Do __NOT__ use a second VVV if you go with a second vm. This will lead to a multitude of problems.
Second: Virtualbox VMs are not really the fastest. So a second box might prevent performance issues

**Comment by jeremyfelt** [comment]
Agreed. Using a dedicated testing VM would be interesting for sure, but it would probably be best as a barebones, separate instance.
