### ISSUE TITLE
Provisioning is sloooow

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/VVV#595]
Okay, I don't know much about how Vagrant provisioning works, but is there ANY way to provision just one site install? Or is there any way to mimick this? Having to provision the whole thing after installing one site can be quite time consuming when you have 10+ sites.

Any alternative methods even?

**Comment by BronsonQuick** [comment]
@joelworsham If you just want a one site install that's super fast to spin up and provision checkout https://github.com/Chassis/Chassis/ it'll probably suit you needs better from the sound of it.

**Comment by cfoellmann** [comment]
@joelworsham do you mean the first `vagrant up`? Yes, that is super slow. Or just a `vagrant provision` to add an additional site?

**Comment by joelworsham** [comment]
vagrant provision. I've since done some workarounds to only run a couple sites at a time to help provisioning take less time.

**Comment by cfoellmann** [comment]
this shouldn't be. What extensive provisioning are doing per site?
When you run  `vagrant provision` on a fresh VVV directly after the initial `vagrant up` it should take about ~30-60 seconds since all checks for updates run. If I misunderstood you and you mean the initial provisioning of all services and packages I feel your pain.
I have some PRs up that can reduce provision time drastically but progress is slow

**Comment by joelworsham** [comment]
I don't mean the initial provisioning. I'm referring to once I've got a few sites (currently about 10)

**Comment by EHLOVader** [comment]
I agree it has been dreadfully slow and seems to do unnecessary installs or checks each time. For every site.

**Comment by jonathan-dejong** [comment]
+1 on this. VVV and vagrant is awesome but now that I've got 20+ projects running provisioning is very slow. Luckily I of course don't have to provision every day but it sort of takes away the "quick start" of a new project.

**Comment by topdown** [comment]
I also see this issue. At first I thought it was the custom site creation scripts, but I noticed all of the additional checks just running ```vagrant provision``` 

Isn't there a PR being worked on for the provision.sh? Will that address some of this performance issue?

**Comment by jeremyfelt** [comment]
It is slooooow. :) I'd like to see some better handling of incremental updates rather than the blanket provisioning process. IMO, provisioning is probably best for updating the server. Making quick changes to add a site could probably go just fine without it if we prepped the right way.

**Comment by devster31** [comment]
VVV could be a base box with the necessary software installed and the provision could just update stuff like composer, npm and the wordpress installations, this way you could import the box once and reprovision it only when adding newstuff, something like [this gist](https://gist.github.com/devster31/30e58cc73e10f6df2d9c) as a base provisioning could be a start?

**Comment by EHLOVader** [comment]
@devster31 I discussed/suggested this somewhat here https://github.com/Varying-Vagrant-Vagrants/VVV/issues/594 I think it would work well. That is how other dev env seem to be setup these days. Homestead for example.

I also suggest separating the provisioning to each site, so you don't spend time reprovisioning sites you already have, and can recover some time lost when you have many projects in a VVV instance.

**Comment by riuvshin** [comment]
I have same issue, vagrant up with provision works well, but vagrant provision takes a loooot of time, for example ```Running provisioner: shell...``` step with echo takes ~3-5 mins.
Ubuntu 14.04
Vagrant 1.8.1
VBox 5.0.14

**Comment by jeremyfelt** [comment]
I'm going to close this in favor of some other tickets that will hopefully continue to improve the provisioning experience. The first is #753 which should allow for new sites without a full provision.
