### ISSUE TITLE
MySQL slow queries and queries not using index logs

### ISSUE THREAD

**Issue by EHLOVader** [Varying-Vagrant-Vagrants/VVV#596]
I know it is easy to turn on manually, but I thought it might be useful to enable by default and configure the log location in `/srv/log` instead of `/var/log` which was the default. 

Would others, plugin developers or people working with applications outside of WordPress find that useful?

```
# Here you can see queries with especially long duration
log_slow_queries        = /srv/log/mysql_slow.log
long_query_time = 2
log-queries-not-using-indexes
```

Also not enabled by default a mysql error log might be useful.

```
log_error = /srv/log/mysql_error.log
```

**Comment by jeremyfelt** [comment]
This makes sense, the more log files exposed the better. :)

**Comment by cfoellmann** [comment]
@EHLOVader will send a PR for this or should I ?

**Comment by EHLOVader** [comment]
I could probably look at it tonight. 
I think that it was just adding/uncommenting the above snippets in the config.

**Comment by mikemcguire** [comment]
See: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/811/files for PR
