### ISSUE TITLE
WP in a subdirectory and multisite subdirectory install

### ISSUE THREAD

**Issue by phh** [Varying-Vagrant-Vagrants/VVV#598]
Hi there,

I have a problem using VVV with a multisite installation. Seems like subdomain/directory works fine out of the box.

Having WordPress in a subdirectory AND install multisite with subdirectory does not seems to work. Trying to log in results in an unending loop. The subsite itself seems to a couple of 404's, like `http://site.dev/subsite/wp-includes/css/admin-bar.min.css Failed to load resource: the server responded with a status of 404 (Not Found)`.

## htacess:

```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) wp/$2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ wp/$2 [L]
RewriteRule . index.php [L]´
```

## wp-config.php:

```
/** Master site */
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', false );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
define( 'DOMAIN_CURRENT_SITE', 'site.dev' );
```

**Comment by cfoellmann** [comment]
`.htaccess` files are not supported. VVV runs nginx which does not get its rules from `.htaccess` files.
Have a look at these configs: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx-wp-common.conf
You need to import that file like here: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/sites/default.conf#L80

**Comment by phh** [comment]
Already doing that:

`server {
    listen          80;
    listen          443 ssl;
    server_name     wp-test.dev *.wp-test.dev;
    root            {vvv_path_to_folder}/frontend;
    include         /etc/nginx/nginx-wp-common.conf;
}`

And my structure is:

- frontend
    - wp
    - wp-content
    index.php
    wp-config.php

So having WP in a subdir while multisite is also a subdirectory install does not work on with the nginx-wp-common.conf file.

**Comment by cfoellmann** [comment]
I suspect your wordpress install is in the `wp/` folder. If that is so your root needs to be `{vvv_path_to_folder}/frontend/wp;` and you need to account for moving your wp-content folder

**Comment by phh** [comment]
This seems to work as for the admin part, but the frontend now seems messy. I guess this is due to the wp-content folder is outside the wp/ dir.

**Comment by cfoellmann** [comment]
```php
// Set path & url for Content
define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/../wp-content' );
```
should do it

**Comment by phh** [comment]
Ending up with a white screen on the frontend now. But if root is `frontend/wp` can the URL the fetch the images from `../wp-content/`?

**Comment by jeremyfelt** [comment]
This is where using `nginx-wp-common.conf` included with VVV may break down a little bit. You probably need more specific handling for the `wp-content/` directory. See my [WSU config file](https://github.com/washingtonstateuniversity/WSU-Web-Provisioner/blob/master/provision/salt/config/nginx/wsuwp-common.conf.jinja#L9-L15) for an example of how an alias might work.

**Comment by phh** [comment]
Awesome!! I have added this to my vvv-nginx file:

```
    ...
    include         /etc/nginx/nginx-wp-common.conf;

    location ~ ^/wp-content/(.*)$ {
        expires 48h;
        alias {vvv_path_to_folder}/frontend/wp-content/$1;
    }
```

Thank you so much! We've had a problem for so long!
