### ISSUE TITLE
413 Request Entity Too Large  nginx when uploading to phpmyadmin

### ISSUE THREAD

**Issue by roulendz** [Varying-Vagrant-Vagrants/VVV#599]
I am trying to upload, 48M file to phpmyadmin. But all the time I get error

```
413 Request Entity Too Large

nginx
```
my php-suctom.ini
```

; Maximum size of POST data that PHP will accept.
post_max_size = 70M

; Maximum allowed size for uploaded files.
upload_max_filesize = 70M

; Maximum number of files that can be uploaded via a single request
max_file_uploads = 20

; Default timeout for socket based streams (seconds)
default_socket_timeout = 60
```

and nginx.conf
```
    # Max size of a body to allow. This affects uploads, but can be overwritten at
    # the individual site level
    client_max_body_size 70M;
```

Any idea what could be wrong?

**Comment by neilgee** [comment]
Having the same issue, I am trying to upload a 150mb db but can't seem to shift from the default limit

php-custom.ini
```
; Maximum size of POST data that PHP will accept.
post_max_size = 180M

; Maximum allowed size for uploaded files.
upload_max_filesize = 180M

; Maximum number of files that can be uploaded via a single request
max_file_uploads = 20

; Default timeout for socket based streams (seconds)
default_socket_timeout = 60
```

nginx.conf
```
    # Max size of a body to allow. This affects uploads, but can be overwritten at
    # the individual site level
    client_max_body_size 180M;
```

result still is - 413 Request Entity Too Large

**Comment by onlyskyguy** [comment]
I'm having the same issue. I'm trying to do it through ssh command line. When I ssh into the machine, I just see a bin directory which contains the vagrant scripts. Where do I need to have the database file so that I can have mysql command import it? Guess maybe I'm asking more of a vagrant ssh question at this point.

**Comment by neilgee** [comment]
It's all at the root level
cd /vagrant

**Comment by jeremyfelt** [comment]
There's an override of 25M in the default site config that handles phpMyAdmin requests - https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/config/nginx-config/sites/default.conf#L49

We should probably bump this all around to 200MB or something in all configs as it is a development environment. I do think larger databases are probably easier at the command line.

**Comment by jeremyfelt** [comment]
Looks like I suggested 1GB in #273. Objections to that?

**Comment by neilgee** [comment]
sounds like a plan - thanks

**Comment by cfoellmann** [comment]
Setting the limit to 1GB sounds good. On a dev machine there is no harm in having limits that are higher than one might be comfortable with in production

**Comment by joelworsham** [comment]
+1

**Comment by mpeshev** [comment]
Somewhat related to @neilgee's comment - my `/vagrant-local/config/php5-fpm-config/php-custom.ini` config file is not loaded at all (hence overrides don't work) while my `/etc/php5/fpm/php.ini` and `/etc/php5/fpm/conf.d/*` custom overrides work like a charm.

Other config files such as my nginx-wp-common.conf are loaded properly from `/vagrant-local/config/`.

**Comment by onthisearth** [comment]
+1 (setting the limit to 1GB)

**Comment by CFXd** [comment]
+1 for increasing the upload limit to 1GB

**Comment by harisnp** [comment]
+1

**Comment by kevinakuviza** [comment]
> 
> 
> +1

**Comment by tomjn** [comment]
If you're dealing with large amounts of data, you would be better off using a dedicated SQL client such as HeidiSQL/PostgreSQL. Then there is no limit other than what storage you have available and time to spend.

There's a SequelPro config file in the `database` folder you can use to connect automagically to VVV's database.


As for the Nginx config change, it was bumped up to 1GB 4 years ago https://github.com/jb510/VVV/blob/master/config/nginx-config/nginx.conf#L103
