### ISSUE TITLE
Issues to update or install plugins

### ISSUE THREAD

**Issue by juan-manuel-alberro** [Varying-Vagrant-Vagrants/VVV#601]
Hello all,

I'm getting this error when I try to add or update a plugin (maybe it fails with themes to but didn't try)

    vagrant@vvv:/vagrant/www/wavetower/htdocs$ wp plugin install bbpress --activate
    Installing bbpress
    Unpacking the package...
    PHP Warning:  ZipArchive::open(): Empty string as source in /vagrant/www/wavetower/htdocs/wp-admin/includes/file.php on line 581
    Warning: ZipArchive::open(): Empty string as source in /vagrant/www/wavetower/htdocs/wp-admin/includes/file.php on line 581
    PHP Warning:  unlink(): No such file or directory in /vagrant/www/wavetower/htdocs/wp-admin/includes/class-wp-upgrader.php on line 278
    Warning: unlink(): No such file or directory in /vagrant/www/wavetower/htdocs/wp-admin/includes/class-wp-upgrader.php on line 278
    Warning: The package could not be installed. PCLZIP_ERR_MISSING_FILE (-4) : Missing archive file ''

That happen using `WP-CLI` and from the Wordpress Dashboard, I cannot update nor install new plugins. I run `chmod` into the `htdocs` folder but without lucky.

Any clue regarding this?
Thanks in advance.

**Comment by jeremyfelt** [comment]
Hi @juan-manuel-alberro, thanks for stopping by.

* Are you able to perform other wp-cli actions as normal?
* Does the same thing occur when trying to install a theme?
* Does the same thing happen when trying to install a plugin on one of the sites included with VVV by default?

**Comment by ymladenov** [comment]
- Are you able to perform other wp-cli actions as normal?
– Yes, I am.
- Does the same thing occur when trying to install a theme?
– Yes.
- Does the same thing happen when trying to install a plugin on one of the sites included with VVV by default?
– No it does not. Used wordpress-default installation for testing.

The installation I am currently having issues with is 4.4.8 and this issue occurred after updating Vagrant a week ago.
Here is my error message:

> PHP Warning:  ZipArchive::open(): Empty string as source in /srv/www/outjewels.co.uk/wp-admin/includes/file.php on line 613
PHP Warning:  unlink(): No such file or directory in /srv/www/outjewels.co.uk/wp-admin/includes/class-wp-upgrader.php on line 295
Warning: The package could not be installed. PCLZIP_ERR_MISSING_FILE (-4) : Missing archive file ''

**Comment by ymladenov** [comment]
I just noticed a similar issue on my web host. Seems to be wordpress-specific.

> Warning: ZipArchive::open(): Empty string as source in /home/bulghar/public_html/wp-admin/includes/file.php on line 628

Warning: unlink(): No such file or directory in /home/bulghar/public_html/wp-admin/includes/class-wp-upgrader.php on line 167
The package could not be installed. PCLZIP_ERR_MISSING_FILE (-4) : Missing archive file ''
