### ISSUE TITLE
ffi-1.9.8-x86-mingw32.gem not found

### ISSUE THREAD

**Issue by Pharetra** [Varying-Vagrant-Vagrants/VVV#603]
Hello,

I'm trying to setup Vagrant using your guide, but without much success. Whenever I try to install vagrant-hostsupdater with ````vagrant plugin install vagrant-hostsupdater````, PowerShell throws this error at me:

````Bundler::GemNotFound: Could not find ffi-1.9.8-x86-mingw32.gem for installation````

I had to move Vagrant's home directory because there is a space in my username. Might that be related to this issue?

**Comment by jeremyfelt** [comment]
Hi @Pharetra, thanks for stopping by. I'm not sure if moving Vagrant's home directory would cause this. If you skip this step are you able to `vagrant up` without issue? It may be there is an issue specific to that plugin, which unfortunately hasn't been updated in a couple years.
