### ISSUE TITLE
Track FAQ Topics

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#605]
There are some questions that occur in similar forms every so often that would be nice to have documented in full somewhere. The varyingvagrantvagrants.org site may be good or the wiki here.
- Permissions was the thing that made me think we needed an FAQ somewhere. (e.g. https://github.com/Varying-Vagrant-Vagrants/VVV/issues/261#issuecomment-33122399)
- A good guide on common Windows issues. Possibly Linux issues? Bring up a Vagrant VM in OSX is usually a dream, I know it can be a pain in other environments.
- Pointers for errors possibly not related to VVV - Vagrant, plugins, etc..

Other topics?

**Comment by cfoellmann** [comment]
### Virtualization extension WARNING in readme
We should add a big warning to check the virtualization extension in the BIOS.
I would send a PR but I am not sure where to put it in the README.md.

**Comment by tomjn** [comment]
I added a virtualisation warning to the install doc, we also have https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/

I do think that the installation page could do with some work or rethinking, a huge list of bullet points isn't ideal

**Comment by Mte90** [comment]
I am closing it because right now we tracked all of them and any case we can open new one with new questions
