### ISSUE TITLE
Ubuntu terminal command for PHPMyAdmin

### ISSUE THREAD

**Issue by Hanque** [Varying-Vagrant-Vagrants/VVV#612]
I am getting close to "Vagrant up."
I need a terminal line command to make a launch icon for PHPMyAdmin.
Ubuntu 14.04, Vagrant, LAMP, Virtualbox VM inside Ubuntu 14.04 desktop.
Best regards,
Hanque

**Comment by cfoellmann** [comment]
I am not sure what you want to achieve.
launch icon?
VVV is __not__ LAMP since it uses nginx and not Apache.

**Comment by Hanque** [comment]
Thanks, that explains a lot. I would start from scratch if I had a guide of some sort. I cleaned everything out now. A friends has promised to help me get going in a Centos7 way, but that was last week.
