### ISSUE TITLE
Can only view sites once before getting the NGINX welcome screen...

### ISSUE THREAD

**Issue by mishtershmart** [Varying-Vagrant-Vagrants/VVV#614]
Howdy,

Just starting out with VVV, but I'm running into an issue. For whatever reason, after running `vagrant up`, I can only look at one of the wordpress sites once before I start getting the "Welcome to NGINX" page on page reload.

I have no idea where to start on this one, so any tips?

**Comment by mishtershmart** [comment]
I should also add that the site actually works while provisioning, but after NGINX restarts, I get the welcome page once again.

**Comment by cfoellmann** [comment]
Maybe there is an issue with a nginx config file. What does it say when you go `vagrant ssh` and do a `sudo service nginx restart`?

**Comment by mishtershmart** [comment]
Thanks for the help – running the restart seems to fix the problem, as the site works again afterwards. This is my first install of VVV; did something potentially go wrong during the installation that might be causing this?

**Comment by mishtershmart** [comment]
It looks like I've sorted it out with a full re-install of VVV. Something must have gone wrong during the initial installation.

**Comment by cfoellmann** [comment]
The provisioning is pretty long at the moment and it sometimes gets screwed up but I am always working on improving that
