### ISSUE TITLE
Xdebug debugger will not connect to vvv out of the box

### ISSUE THREAD

**Issue by kipraske** [Varying-Vagrant-Vagrants/VVV#615]
I had the hardest time getting my IDE to connect to xdebug. I am not sure if this is something specific to the environment I am using, or if other people were getting the same problem. In either case, this information may help people down the road if they can't get the remote debugger to work properly.

I was able to resolve my connection problem by setting `xdebug.remote_host = 10.0.2.2` instead of the default `xdebug.remote_host = "192.168.50.1"`

I am running vvv on OSX Yosemite (10.10.1) if that makes any difference.

**Comment by EHLOVader** [comment]
Had you changed the subnet of your VM. I believe it would be in the vagrant file. VVV comes by default with a configuration using the `192.168.50.x` subnet.

Unless you have a conflicting VM or personal network which is using the same subnet it shouldn't give you troubles.

The `10.0.2.2` IP does appear to be the default gateway for some vritualbox configurations.

**Comment by kipraske** [comment]
I have had not changed the subnet of the VM, though perhaps that also would have worked. I do not seem to have any conflicting VMs or services on my personal host network. I also confirmed that it wasn't my firewall, that the xdebug request packets were being sent from the VM to the host (but the host never receives them), and that the requesting IP address on the VM is in fact coming from the `192.168.50.x` subnet.

I agree that it should work just fine out of the box. I have no idea why it would not be. If it is just my machine/network being inexplicably strange, and no one else is having this problem then perhaps this is not an issue after all.
