### ISSUE TITLE
Can't find php_errors.log

### ISSUE THREAD

**Issue by lmartins** [Varying-Vagrant-Vagrants/VVV#622]
Ok, this is most likely a dumb question but I can't seem to find the php_errors.log file.
In `php-custom.ini` inside of `/config/php5-fpm-config` the following is being declared:

```
; Log errors to specified file.
error_log = /srv/log/php_errors.log
```
Can you help please?
Tks

**Comment by cfoellmann** [comment]
this is mapped to your local VVV folder under `log/` but WP sites log their errors into `wp-content/debug.log` if WP_DEBUG is set.

**Comment by lmartins** [comment]
Thank you @cfoellmann that is what I was looking for :)
