### ISSUE TITLE
==> default: /tmp/vagrant-shell: line 138: /etc/postfix/main.cf: No such file or directory

### ISSUE THREAD

**Issue by hubdotcom** [Varying-Vagrant-Vagrants/VVV#628]
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/provision/provision.sh#L138

**Comment by af7** [comment]
It also hits error for me (Win 8 host).

**Comment by chetanchauhan** [comment]
@hubdotcom @af7 Does software gets installed automatically in the virtual machine for you while doing provisioning? I am also getting this error and for me software aren't getting installed.

**Comment by jeremyfelt** [comment]
Are there other errors during provisioning? I've provisioned from scratch a few times recently and haven't had any trouble, though it's possible that this error displays.

Can you paste the entire provisioning log into a gist or pastebin? It may be helpful to see all of those details.

**Comment by chetanchauhan** [comment]
Can you tell me how to copy the provisioning log from git bash?

**Comment by jeremyfelt** [comment]
Depending on the terminal in use, you may be able to configure how many lines of scrollback are available. In OSX or Linux, you can pipe the results like `vagrant provision > results.txt` to capture a text file. You may be able to do the same thing here.

Have you tried starting over with `vagrant destroy`, then `vagrant up`? There shouldn't be any different behavior inside the VM itself once provisioning starts between Linux, OSX, and Windows.

**Comment by chetanchauhan** [comment]
I have already tried `vagrant destroy` then `vagrant up`, even reinstalled virtualbox and vagrant, but no success so far.

**Comment by jeremyfelt** [comment]
Ahh, it looks like this may be key:

```
==> default: Failed to fetch http://nginx.org/packages/mainline/ubuntu/pool/nginx/n/nginx/nginx_1.9.1-1~trusty_amd64.deb  Hash Sum mismatch
==> default: E
==> default: : 
==> default: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I'm going to try a fresh `vagrant up` on my end. The switch to nginx 1.9.1 for the mainline branch is recent.

**Comment by jeremyfelt** [comment]
Ok, everything worked fine during a fresh `vagrant up` just now. I'm wondering if this thread could shed some light on the issue - http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error

Are you behind a proxy at all?

Note - this is unrelated to the error in the original title of this issue. I do get that, but it's more of an informational error—though we should find a way to fix it.

**Comment by chetanchauhan** [comment]
> Ahh, it looks like this may be key:
> 
> ==> default: Failed to fetch http://nginx.org/packages/mainline/ubuntu/pool/nginx/n/nginx/nginx_1.9.1-1~trusty_amd64.deb  Hash Sum mismatch
> ==> default: E
> ==> default: : 
> ==> default: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> I'm going to try a fresh vagrant up on my end. The switch to nginx 1.9.1 for the mainline branch is recent.

Yes this indeed is the key. After I removed the nginx mainline signing key and custom sources added by vvv from the vm and installed the stable nginx(1.4.6) manually, it seems to be working.

> Ok, everything worked fine during a fresh vagrant up just now. I'm wondering if this thread could shed some light on the issue - http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error
> 
> Are you behind a proxy at all?
> 
> Note - this is unrelated to the error in the original title of this issue. I do get that, but it's more of an informational error—though we should find a way to fix it.

No, I am not behind a proxy.

**Comment by jeremyfelt** [comment]
I'm still seeing this postfix error during provisioning. Just updating with a note that this line may be it - https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/provision/provision.sh#L195-L196
