### ISSUE TITLE
extend contributing guide

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#634]
I think we should add something about testing and feedback to the contributing.md
testing of and feedback on PRs are invaluable to determine validity, right?

What do your think`?

**Comment by jeremyfelt** [comment]
That would be excellent. I'm not sure if we need to go into too much technical detail, but a general overview of the usefulness would be great.

**Comment by michaelbeil** [comment]
Also, perhaps adding a blurb about code documentation would be helpful: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/CONTRIBUTING.md

**Comment by Mte90** [comment]
We have now a contribute guide https://varyingvagrantvagrants.org/docs/en-US/contribute/, it's not complete but is a first step.
I will close it so we can discuss in new tickets what is missing and close this old one.
