### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by neilgee** [Varying-Vagrant-Vagrants/VVV#636]
Started getting a 502 Bad Gateway when trying to import a site via Duplicator plugin to an instance created via Variable VVV

After Googling http://www.nginxtips.com/502-bad-gateway-using-nginx/ resolution was to restart php5-fpm directly on the box

```sudo restart php5-fpm```

**Comment by cfoellmann** [comment]
Is this a question or a possible solution for others with the same problem?
If it is an issue it might be good to post it as a vv issue!?

**Comment by neilgee** [comment]
Wasn't too sure it was vv or VVV vagrant issue - as it occurred after vagrant reprovisioned to 4.2.1

**Comment by neilgee** [comment]
This was probably a resource issue - which needs some RAM allocation - closing this now.
