### ISSUE TITLE
new domain restart/provision

### ISSUE THREAD

**Issue by byronyasgur** [Varying-Vagrant-Vagrants/VVV#638]
In the conf sample file the instructions are 

`Once your new domain has been added, make sure to restart the
nginx process by running 'vagrant provision' in your local
environment or 'sudo service nginx restart' after 'vagrant ssh`

I tried restarting nginx but only a provision would work. The provision takes an awful lot longer ( it too 12 minutes on my machine vs the restart a second) . Is the restart supposed to work? ( the documentation doesn't mention the restart only the provision )

If the restart could be made to work it would be a major advantage in my view; otherwise I suppose the contents of the conf sample file are misleading.

**Comment by jonathan-dejong** [comment]
following

**Comment by jeremyfelt** [comment]
On an already provisioned instance of VVV, running `vagrant provision` again should not take much time at all.

It's possible that a restart would not work because the custom nginx config files may not have been copied over. We should take a closer look at the workflow for this.

Sorry to keep you hanging, thanks for the ticket @byronyasgur!

**Comment by itsazzad** [comment]
Updated already?

**Comment by mheesters** [comment]
Also ran into this.

It would be nice if the custom_vvv function in the provision.sh script could be ran separately.
So you wouldn't have to go through the whole provisioning script.

I've put in in a seperate file, just for adding/updating/removing sites from my VVV
https://gist.github.com/mheesters/39e765d03d0c01121418

But a more ideal solution would be if you could run 'vagrant provision <functionname>'.
Or ./provision.sh custom_vvv (so there would be still 1 provision.sh file).

**Comment by jeremyfelt** [comment]
> It would be nice if the custom_vvv function in the provision.sh script could be ran separately.
So you wouldn't have to go through the whole provisioning script.

Indeed. Let's do this in #753.
