### ISSUE TITLE
Error in grunt build - new install

### ISSUE THREAD

**Issue by ngaller** [Varying-Vagrant-Vagrants/VVV#641]
Hello, I have just cloned the repo yesterday and having these errors:

==> default: ERROR
==> default: >> Error: Cannot find module 'amdefine'
==> default: Loading "imagemin.js" tasks...
==> default: ERROR
==> default: >> Error: Cannot find module 'vinyl-fs'
==> default: >> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
==> default: >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
==> default: Loading "sass.js" tasks...
==> default: ERROR
==> default: >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
==> default: Warning: Task "uglify:core" not found. Use --force to continue.
==> default: Aborted due to warnings.

So I tried going into the /srv/www/wordpress-develop folder and running "npm install" but this gives some more errors:

npm WARN package.json WordPress@4.3.0 No README data
npm ERR! tar.unpack untar error /home/vagrant/.npm/delayed-stream/0.0.5/package.                                                                                                                                                             tgz
npm WARN optional dep failed, continuing form-data@0.1.4
npm ERR! Linux 3.13.0-51-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.0
npm ERR! path /srv/www/wordpress-develop/node_modules/grunt-contrib-qunit/node_m                                                                                                                                                             odules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/node_mod                                                                                                                                                             ules/rimraf/node_modules/glob/node_modules/once/package.json.b15182d7a3a3bb7dc4f                                                                                                                                                             f4c03c7928483
npm ERR! code EPERM
npm ERR! errno 50

(some more EPERM errors after that)

I wondered, could this be a problem due to my host OS being Windows, something like the path names being too long?  Maybe something related to this VirtualBox issue: https://www.virtualbox.org/ticket/11976

So I moved my directory for VVV from C:\Projects\Vagrant-Local to C:\VVV and ran "vagrant up" then "vagrant provision", this worked better but it still gave a warning about "node-sass" not being available and this error:

Warning: Task "sass:colors" not found. Use --force to continue.

Aborted due to warnings.

I tried running "npm install node-sass" manually and got the same type of "EPERM" errors as before.

I guess my bottom line question is, is VVV supported on Windows?  This might actually be more of a Vagrant issue though as I see in this thread https://github.com/mitchellh/vagrant/issues/1953 . So I will try downloading the master version when I get more time and test with that.  But wanted to do a sanity check with you VVV folks first and make sure my box wasn't haunted (other than having the misfortune of being loaded with Windows)?

**Comment by af7** [comment]
I have the **same** problems, did you (or anybody else) find any solution?

I also have Windows (8.1) as the host.

**Comment by af7** [comment]
Most likely this is the solution:
https://github.com/mitchellh/vagrant/pull/5495

**Comment by ngaller** [comment]
Yes, I think you are right.  I gave up on using Vagrant though and went back to my plain Debian VirtualBox.... another problem I had was the machine would often freeze for a few seconds after editing a file.

**Comment by jeremyfelt** [comment]
Sorry to hear about the troubles. I'm going to close this in favor of the upstream Vagrant fix, but it's good to have this documented. I know several people are running things in Windows just fine, but it is often an unfortunate pain point.
