### ISSUE TITLE
vvv.dev getting a 403 Forbidden

### ISSUE THREAD

**Issue by JohnLauber** [Varying-Vagrant-Vagrants/VVV#642]
I'm going crazy trying to figure out how or what changed that I continue to get 403 Forbidden on vvv.dev. 

For my last try, I ran vagrant destroy, deleted some of the directories (including default) and then vagrant up. Now I don't have local.wordpress.dev and I still get 403 forbidden on vvv.dev. 

Any ideas what I'm missing? Permissions that somehow need to be reset? Anything?

Thanks.

**Comment by JohnLauber** [comment]
I found my issue, but I don't know why it happened. There was no index.php or phpinfo directory in my default directory. 

Any insight into how/why this would happen?

**Comment by jeremyfelt** [comment]
These files are included with the repository rather than provisioned in, so it seems the only way for this to happen would be during an interrupted checkout. Glad to hear it's back though!

**Comment by JohnLauber** [comment]
I'm curious how they were removed though. I had to add them back manually.

**Comment by thinkhuman** [comment]
I have this issue too, but I'm unclear how to fix it. I can launch my VMs, but can't run any vagrant commands--Suddenly, I get 'A Vagrant environment or target machine is required to run this
command.' Then instructions to create a new Vagrant environment.

Also, vvv.dev returns a 403. 

Help?

**Comment by twoelevenjay** [comment]
I am getting `403` on `vvv.dev` as well. When I look at `/VVV/www/default` in finder, I see all the needed files and directories including `index.php`, but when I `vagrant ssh` and cd to `vagrant@vvv:/srv/www/default` I only one directory (the `webgrind` directory) and no files. How can this be?
