### ISSUE TITLE
xdebug.ini empty zend_extension?

### ISSUE THREAD

**Issue by fbm-static** [Varying-Vagrant-Vagrants/VVV#645]
Hello,

When I issued 'sudo bin/xdebug_on' it ran okay but the file at /etc/php5/fpm/conf.d/50-xdebug.ini has empty zend_extension="". Have I missed something?

**Comment by jeremyfelt** [comment]
Hi @fbm-static, thanks for the ticket. I don't think `sudo` is necessary, but I'm not sure if it would cause an issue. I run `xdebug_on` as the vagrant user and it works fine. I just tried now and it modifies a `/etc/php5/fpm/conf.d/20-xdebug.ini` file and includes the `zend_extension` directive. I'm not sure if that matters or why you would be seeing `50-xdebug.ini`.

Have you tried without `sudo`?
