### ISSUE TITLE
Run alternate PHP version

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/VVV#647]
It would be incredible to be able to switch the PHP version on the fly, but if that's unrealistic, is it possible to simply install this with a different PHP version from the get-go? I don't mind having multiple environments for various PHP verisons (5.5, 5.4, 5.3, 5.2)

**Comment by cfoellmann** [comment]
See #635

**Comment by joelworsham** [comment]
Awesome, really hoping this gets added soon
