### ISSUE TITLE
VVV PR status

### ISSUE THREAD

**Issue by topdown** [Varying-Vagrant-Vagrants/VVV#648]
Is there a reason that some of the great PR's are not being merged in?
Especially a lot of the PRs from @cfoellmann 
Like https://github.com/Varying-Vagrant-Vagrants/VVV/pull/611

Is there anything that can be done to speed up the process?

**Comment by cfoellmann** [comment]
I think we need more people with commit access. That way we can establish a workflow with enough capacity to test and check PRs in a timely fashion.

**Comment by jeremyfelt** [comment]
Only because I'm behind :)

I agree, I would like to mix up the current list of committers. Let me think through a few things that I'd like to establish first.

**Comment by jeremyfelt** [comment]
I'm going to close this and focus on documenting the current processes in #962.
