### ISSUE TITLE
Change mysql version

### ISSUE THREAD

**Issue by dmassiani** [Varying-Vagrant-Vagrants/VVV#651]
Hi,

I don't find the way to change the mysql version in provision.

I found a solution because my remote mysql version is 5.1 and vvv is 5.5.
The problem is 5.5 character encoding is utf8mb4 and 5.1 don't accept this.
If someone has another solution to make it compatible, I take it.

**Comment by dmassiani** [comment]
My temporary solution, a wordmove fork with replace utf8mb4 to utf8 https://github.com/dmassiani/wordmove

**Comment by jeremyfelt** [comment]
It would be nice to be able two switch between MySQL versions easily.

**Comment by evanwebdesign** [comment]
+1 for the ability to switch between MySQL versions. I ran into the exact same problem as dmassiani.

**Comment by jeremyfelt** [comment]
I'm going to close this and defer to #835 and #949.
