### ISSUE TITLE
Getting 504 Gateway Timeout

### ISSUE THREAD

**Issue by paperrobots** [Varying-Vagrant-Vagrants/VVV#652]
I'm able to vagrant up my box and I can SSH in just fine. However no pages will load not even vvv.dev. I get 504 Gateway Time-Out error message. I'm pretty new to this so I'm not entirely sure how to troubleshoot at this point. I tried restarted the nginx service but that didn't seem to help. 

Update: I'm narrowed it down to the php function file_get_contents() I'm using to load an SVG image into my site. For some reason this function cripples my entire vagrant environment. Do I need to change a setting for this function to work properly?

**Comment by jeremyfelt** [comment]
Hey @paperrobots, sorry you never got a response. :disappointed: 

If you're still having trouble and need some help, please re-open this issue. Hope things are sorted!
