### ISSUE TITLE
Postfix Not Sending Mail

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [Varying-Vagrant-Vagrants/VVV#653]
Hi, I installed this and then installed mailutils (an extension of Postfix that provides the mail command) and I am unable to send mail.

Steps taken:
1) Git clone repo
2) Vagrant up
3) su -> password: vagrant
4) apt-get install mailutils
5) echo "body" | mail -s "subject" example@domain.com

**Comment by jeremyfelt** [comment]
Hi @TimeTravelersHackMe, thanks for the report.

I'm seeing two different issues here:
* Something has happened recently that has made the changes from #347 seem broken. I'm having issues with DNS when running unit tests. I wasn't able to send mail via postfix today until I updated `resolv.conf` to use Google DNS. I want to dig into this further to see if that's a long term solution or if the DNS NAT should still be working.
* The installation of Mailcatcher in #632 was great in that it gave us a web interface for mail, but it does take over `sendmail` when WordPress tries to use it. I had to comment out the config in `/etc/php5/mods-available/mailcatcher.ini` for that to start working.

**Comment by om4james** [comment]
I'm also seeing this issue @jeremyfelt.

`/etc/resolv.conf` is defaulting to:
`nameserver 10.0.2.3`

and that nameserver isn't returning the public MX records for my domains.

At this stage I'm not sure why the proxying of DNS (#347) isn't correctly resolving some public DNS records.

Any ideas?

Thank you,

**Comment by tomjn** [comment]
We use MailHog in VVV 3, since this is an old issue and so much has changed I'm going to close it out.

Note that VVV isn't configured out of the box for public SMTP servers, I'd advise against trying to send actual emails to real people, and instead rely on MailHog which will intercept any emails sent via the server and show them in an inbox style interface
