### ISSUE TITLE
Mysql tmp MYI files can't be written/created - database mangled

### ISSUE THREAD

**Issue by HongPong** [Varying-Vagrant-Vagrants/VVV#655]
I left my VVV instance running for a week or so and ignored it. When I returned to it, database content was thrashed. I'm glad I had a recent backup because I'm not sure if this is recoverable.

Accessing over Sequel Pro says something like "Mysql said: file './dbname/dbtable.MYD' not found (errcode: 30)' . When I do vagrant halt I get:

==> default: mysqldump: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
==> default: mysqldump: Couldn't execute 'show fields from `6sub5bay_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
==> default: mysqldump:
==> default: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
==> default: mysqldump: Couldn't execute 'show fields from `wp_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
==> default: mysqldump
==> default: : Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
==> default: mysqldump: Couldn't execute 'show fields from `wp_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
==> default: mysqldump:
==> default: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
==> default: mysqldump: Couldn't execute 'show fields from `wp_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
==> default: mysqldump
==> default: : Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
==> default: mysqldump: Got error: 29: File './wp_suburban/6sub5bay_options.MYD' not found (Errcode: 30) when using LOCK TABLES
==> default: Command execution finished.
The command "vagrant ssh -c 'vagrant_halt'" returned a failed exit code. The
error output is shown below:

mysqldump: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
mysqldump: Couldn't execute 'show fields from `6sub5bay_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
mysqldump: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
mysqldump: Couldn't execute 'show fields from `wp_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
mysqldump: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
mysqldump: Couldn't execute 'show fields from `wp_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
mysqldump: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
mysqldump: Couldn't execute 'show fields from `wp_commentmeta`': Can't create/write to file '/tmp/#sql_ffc_0.MYI' (Errcode: 30) (1)
mysqldump: Error: 'Can't create/write to file '/tmp/#sql_ffc_2.MYI' (Errcode: 30)' when trying to dump tablespaces
mysqldump: Got error: 29: File './wp_suburban/6sub5bay_options.MYD' not found (Errcode: 30) when using LOCK TABLES

Anyway it's possible this was some accident that happened locally but I'm not sure what that would have been. The host computer went through several sleep-wake cycles. I find now that vagrant halt does not actually halt the VM. I tried using the command internally $ sudo shutdown -h now  and that didn't work. Halting the VM through Virtualbox stopped it, but now I get Connection timeout... Retrying when attempting to bring it back up. I think I will have to rebuild the VVV from scratch again and not leave it turned on for long periods. And continue to make a lot of backups.

Please feel free to close this ticket, but I thought the situation was odd enough that it was worth noting something strange happened with Mysql and the tmp folder, and things took a dive from there.

**Comment by jeremyfelt** [comment]
Thanks for the info, @HongPong. I have experienced strange issues in the past when leaving a VM up throughout different sleep cycles. It will often work just fine, and doesn't seem to have as much issue now, but using `vagrant halt` at the end of each day is definitely a preferred workflow.
