### ISSUE TITLE
Time Zone setting

### ISSUE THREAD

**Issue by strider72** [Varying-Vagrant-Vagrants/VVV#660]
It would be great to have a config or setting for the Time Zone, that would be set for Ubuntu and PHP.  It's frustrating reading PHP logs while debugging and having to translate timestamps.

**Comment by jeremyfelt** [comment]
UTC is a good default to stick with on servers in general. There's likely something you can do with custom provisioning scripts that sets [tzdata](https://wiki.debian.org/TimeZoneChanges) to something different.

**Comment by strider72** [comment]
What's odd is I managed to set the server's time via SSH, but it didn't affect the web server's timestamps -- e.g. on the PHP error log.  (No, I'm really not a server person....)
