### ISSUE TITLE
can mysql databases in the guest be synced to the host

### ISSUE THREAD

**Issue by helgatheviking** [Varying-Vagrant-Vagrants/VVV#661]
Are the databases only stored in the virtual guest machine? If so, can they be synced to the host machine somewhere so that I can access them from my other partition when I am running a different OS?

**Comment by grappler** [comment]
You can access the database when going to http://vvv.dev/database-admin/. I think the databases are saved locally when it is halted.

**Comment by jeremyfelt** [comment]
Yes, the databases are only inside the virtual machine. If the vagrant triggers plugin is installed, the `db_backup` [script](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/homebin/db_backup) will fire on halt, suspend, and destroy and backup your databases locally.

We kept backward compatibility for existing VVV instances that mapped the database locally, so there's a bit of a [hack available](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/8a24b70751bb81f36b5979c2b924b27b08b2f90f/Vagrantfile#L143-L154) if you did want to do this. Things are much quicker now though.

See #322 and #287 for some more history on why this is the way it is.

**Comment by helgatheviking** [comment]
So the only thing I need to do is install the vagrant triggers plugin?

**Comment by jeremyfelt** [comment]
@helgatheviking, I think I missed this reply. :no_mouth:

Yes, installing the vagrant triggers plugin will cause the database backup script to fire automatically.
