### ISSUE TITLE
Provision from github repo

### ISSUE THREAD

**Issue by GuerrillaCoder** [Varying-Vagrant-Vagrants/VVV#663]
Hi,

Really enjoying VVV, its such a cool way to manage local environment.

Is there a way to do something like:

`git clone https//user@gitbub.com/repo/git.git`

If I do that normally it then asks me for password but doing `vagrant provision` it will fail due to no password supplied.  Do I have to do it through SSH in the shell script?

I don't want to include password in URL as then it will be saved in the config.

**Comment by jeremyfelt** [comment]
Hi @GuerrillaCoder. I'm guessing some of the discussion in #360 could be helpful. I don't think we have a documented perfect solution though.
