### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by nathansmonk** [Varying-Vagrant-Vagrants/VVV#666]
Not an Issue, and if this is the wrong place to ask, please let me know, but wondered if anyone knew how to have the entire vagrant instance in a google drive folder?

**Comment by cfoellmann** [comment]
You could just test it.
I am not familiar with google drive in particular but I suspect that it will come to serious sync conflicts.

**Comment by jeremyfelt** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/88 may have some useful information as well.
