### ISSUE TITLE
Vagrant crashes when running vagrant up

### ISSUE THREAD

**Issue by mxpimp47** [Varying-Vagrant-Vagrants/VVV#668]
I bought a new Mac a week ago. Synced up all my old info from my other Mac from time machine. Trying to fire up Vagrant to work and it displays the message - 

"Vagrant cannot forward the specified ports on this VM.... The forwarded port to 2222 is already in use on the host machine. etc...." 

I followed the instruction for adding the config.vm.network :forwarded_port... didnt help me any.

When running "vagrant up" again with the forwarded ports or not added to the Vagrantfile it starts to go through the process.

Bringing machine 'default' up with 'virtualbox' provider...
Checking if box 'ubuntu/trusty64' is up to date...
Resuming suspended VM... <-- (is this because I ran vagrant up initially?)
Booting VM...

Then my Mac crashes and restarts. 

Why would I encounter this error when my old machine worked just fine? It was Yosemite just like my new Mac.

**Comment by jeremyfelt** [comment]
Are you able to load another virtual machine with VirtualBox? It seems more likely the issue would lie there than with Vagrant or VVV. I'd try a VM from modern.ie first to see how that goes, then a bare bones Vagrant VM.

**Comment by mxpimp47** [comment]
I reinstalled both VirtualBox and Vagrant and I was able to start up last night. A friend mentioned he had transferred his environment from one computer to the next and had the same issue. It fixed it for me by reinstalling. Hopefully it will help anyone else who has the same problem. 

Thank you for the support!
