### ISSUE TITLE
Mapping /tmp folder

### ISSUE THREAD

**Issue by GuerrillaCoder** [Varying-Vagrant-Vagrants/VVV#669]
Hi,

I'd like to map the /tmp folder so I can analyze profile snapshots.  Where should I add the mapping code?  Any help is appreciated as I am new to vagrant and don't know any ruby.

Thanks

**Comment by jeremyfelt** [comment]
You should be able to do this with a `Customfile` using the same syntax that we use in `Vagrantfile`. See https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L216-L218
