### ISSUE TITLE
vvv-init.sh user interaction not possible

### ISSUE THREAD

**Issue by jezmck** [Varying-Vagrant-Vagrants/VVV#671]
I have the following in my `vvv-init.sh` file but the user doesn't get a chance to answer the question.

    ...
    read -p "    Import (replace) database from \`$DB_FILE\` (y/n)? " answer
    case ${answer} in
        y|Y )
            echo "    Importing DB ..."
            mysql -u root --password=root $DB_NAME < $DB_FILE
        ;;
        * )
            echo "    Skipping DB import ..."
        ;;
    esac
    ...

Is it possible?

**Comment by westonruter** [comment]
Probably not, if the `stdin: is not a tty` warning is any indication.

**Comment by jeremyfelt** [comment]
Yeah, once provisioning has started in Vagrant, user interaction is done. This may require a custom Vagrant plugin instead to achieve the desired effect.
