### ISSUE TITLE
What is the difference between the four instances of wordpress on VVV?

### ISSUE THREAD

**Issue by avnarun** [Varying-Vagrant-Vagrants/VVV#672]
Hi there,
I have installed VVV and trying to poke around to learn it. I am new to wordpress development and also new to how things are arranged on wordpress SVN repo - my understanding is trunk is latest work on dev, branches are WIP dev and tags are the releases.

So when I saw four instances of wordpress in VVV - I am trying to figure out which version is best for what kind of development? Can you please review and comment on my comments below.

http://local.wordpress.dev for WordPress stable (www/wordpress-default)
[avnarun] This should be good for usual wordpress implementations (project/production driven).

http://local.wordpress-trunk.dev for WordPress trunk (www/wordpress-trunk)
[avnarun] This should be good if and when I want to contribute to core? or maybe not.. this should be good for when I want to do a wordpress implementation with latest from trunk?

http://src.wordpress-develop.dev for trunk WordPress development files (www/wordpress-develop/src)
[avnarun] I frankly do not understand difference between this trunk and above trunk. I am hoping they are the same, the only difference being here we have additional things like phpunit test which will aid in core development.

http://build.wordpress-develop.dev for a Grunt build of those development files (www/wordpress-develop/build)
[avnarun] I haven't yet caught up to grunt except watching few intro videos. But I guess this will be the build/output folder when I will be doing core development.

Thanks in advance and sorry if I am asking something obvious .. I looked around to find if this question is already answered but could not find it. I am still researching on my own and may find the answer in a day or two - but thought to post here if someone can answer quickly.

**Comment by gkobilansky** [comment]
From the README:

* Use wp-content/themes in either the www/wordpress-default or www/wordpress-trunk directories to develop themes.
* Use wp-content/plugins in either the www/wordpress-default or www/wordpress-trunk directories to develop plugins.
* Use the www/wordpress-develop directory to participate in WordPress core development.

**Comment by avnarun** [comment]
Thanks Gene, that explains it and I am actually sorry that I missed it while reading README :) .. nevertheless, I will close this thread.
