### ISSUE TITLE
VVV wiki, questions regarding Connect to Your Vagrant Virtual Machine with PuTTY

### ISSUE THREAD

**Issue by rlaan** [Varying-Vagrant-Vagrants/VVV#673]
Hi,

Connecting with Putty to my Windows based VVV is still not possible with method provided in this article in the wiki.
I'd love to help out with the documentation for this, the thing is, since it is not working at the moment, I cannot trust my own settings etc.

In my view the documentation falls short on some relevant points:
- Click on the Save private key button. => where do I save this file (does it matter where?)
- You can regain the security offered by the SSH protocol by creating your own SSH key pair and editing the Vagrantfile, accordingly. => This is largely vague, I managed to get the location into the provisioning file, but it still doesn't work. 
- Does it require a vagrant halt/up cycle or a vagrant provision? 
- The SSH key pair, is that in the now created private key file? 
- Does the authorized_keys folder have anything to do with this (and if so, how?)
- maybe related: I've read stuff about Putty not being compatible with the OpenSSH key, if tried some workarounds as well, no luck.

If I can supply more info to help further this issue, please let me know.

Best regards,
Ruud

**Comment by grappler** [comment]
- You can save the private key anywhere. I like saving it in `C:\Users\[username]\.ssh`
- I am using the key provided. I don't think you need to generate your own key as it is a local setup and not connected directly to the internet.
- Once vagrant is up you can connect using Putty

You can use this file to login https://cloudup.com/cBnLnUlXzYz

![image](https://cloud.githubusercontent.com/assets/1785641/8308134/525ced7c-19c3-11e5-9e65-b5eaf1c41ece.png)
![image](https://cloud.githubusercontent.com/assets/1785641/8308115/32ed2560-19c3-11e5-852e-ae3fae5e4a3b.png)
![image](https://cloud.githubusercontent.com/assets/1785641/8308088/0c35f046-19c3-11e5-9cef-805448ebfb11.png)

If the key is not recognized when you try to log in then the password is `vagrant`

**Comment by jeremyfelt** [comment]
Tagging #605 to track this as something to add to FAQs. Thanks for the ticket, @rlaan. Thanks for the answer @grappler!
