### ISSUE TITLE
Vagrant Triggers fail on Windows and Hyper-V

### ISSUE THREAD

**Issue by ericmann** [Varying-Vagrant-Vagrants/VVV#674]
It's no secret that I moved from VirtualBox to Hyper-V some time ago, but I still love using VVV for development. I finally got around to installing the Vagrant Triggers plugin and ... it's broken my install.

Namely, once a VM is started, it can't be `halt`ed, `suspend`ed, or `destroy`ed because the triggers hang on execution. The current `run` command is running `vagrant ssh` within an existing `vagrant halt` that entirely locks the Ruby VM whenever it makes an attempt.

I know this is not the expected behavior, so I took some time to figure out what's going on and how to fix it.
## Vagrant Triggers

It's undocumented, but the Vagrant Triggers system includes _two_ ways to execute scripts:
- `run` is meant to execute a script on the _host_ (hence the need to use `vagrant ssh` to run scripts inside the machine
- `run_remote` is meant to execute a script on the _guest_

The one caveat here is that `run_remote` uses sudo to execute commands, so mapping things to the Vagrant user's bin directory means we can't just do a one-to-one swap out of the script. That said, I think we should use the command intended to run remote scripts to run our remote scripts rather than the current, somewhat hacky workaround.

**Comment by jeremyfelt** [comment]
Thanks for the info, @ericmann. So if we use `run_remote`, we would ditch the `vagrant ssh -c` part as well?

I'd be okay to adjust this. I wonder if there's a chance that sudo would screw with someone's custom script that's already in place as part of the chain.

**Comment by sethrubenstein** [comment]
@jeremyfelt @ericmann I'm interested in this as well - whats the correct patch here for the Vagrantfile?
Is it to change all the `run "vagrant ssh -c ..."` to be `run_remote "vagrant ssh -c ..."` or what?

**Comment by ericmann** [comment]
@sethrubenstein We don't have a full resolution yet (which is why the issue is still open). The change would likely be migrating `run` to `run_remote`, but _without_ the `vagrant ssh -c` part (as `run_remote` is _already_ executing against the remote guest.

The issue is that `run_remote` executes remotely as root while `run "vagrant ssh -c ..."` executes remotely as the Vagrant user. That particular difference won't break anything for a new or vanilla install (as we can place custom hooks in the root user's bin directory or global bin), but if anyone has added their own custom scripts, they'd be lost in the transition. That was what Jeremy was getting at with his own question.

**Comment by tomjn** [comment]
Triggers was merged into Vagrant core, if this is still an issue under Vagrant 2.1 or above, open an issue on the Vagrant github

**Comment by tomjn** [comment]
As an aside, our vagrant file now uses `run_remote` which was documented recently as of `2.2`
