### ISSUE TITLE
Replace wp core upgrade with wp core update

### ISSUE THREAD

**Issue by kennyr87** [Varying-Vagrant-Vagrants/VVV#675]
On line 576 of provision.sh 'wp core upgrade' should be 'wp core update'.  See: http://wp-cli.org/commands/core/update/.

**Comment by michaelbeil** [comment]
you mean `wp core update` as in your title correct?

**Comment by kennyr87** [comment]
yea, easy to confuse upgrade and update :-)

**Comment by michaelbeil** [comment]
You should submit a PR ot the dev branch.

**Comment by jeremyfelt** [comment]
We still have `wp core upgrade` in `provision.sh`. I haven't actually paid attention to whether it's broken or not. :)
