### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by wturrell** [Varying-Vagrant-Vagrants/VVV#677]
Hello. What's the correct procedure – if there is one – for upgrading the OS of an existing VVV installation: i.e. to a more recent version of Ubuntu and therefore more recent packages (including PHP 5.6)?

I tried it the usual way (apt-get upgrade + dist-update) but had to roll back to a backup because of issues with the shared directories no longer working… (OS X 10.10, VirtualBox).

**Comment by cfoellmann** [comment]
I wouldn't recommend upgrading the OS.
If you "only" need a newer php version you should test the `feature/phpbrew` branch.

**Comment by fabianhenzler** [comment]
did you try just `vagrant provision` to let it upgrade?

**Comment by wturrell** [comment]
@fabianhenzler I was under the impression that would reset all my existing WordPress installations (is that wrong?) I was after a way to upgrade without needing to reconfigure Nginx, MySQL etc.

**Comment by cfoellmann** [comment]
if you run `vagrant provision` the provision script runs but your "work" is safe. the included WP installs will be updated but nothing will be reset or overwritten

**Comment by fabianhenzler** [comment]
@cfoellmann exactly =) 
@wturrell If you have a little time, just dig into the [provision/provision.sh](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh). It's always checking if the folders - e.g. wordpress-default - exists and if yes, then it only updates the installation with the latest and greatest of Wordpress, but your database stays untouched.
Even if you do a `vagrant destroy` your database will be backuped to [/database/backups](https://github.com/Varying-Vagrant-Vagrants/VVV/tree/develop/database/backups).

VVVz awesomeness never stopps =D

**Comment by ronezone** [comment]
So what is the initial output of `vagrant up` referring to with `vagrant box update`?  ...to update to the latest version of what, the VIrtualBox?

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20150930.0.0'. The latest is version '20151201.0.0'. Run
==> default: `vagrant box update` to update.
```

**Comment by jeremyfelt** [comment]
This will be documented better in the future via #961.
