### ISSUE TITLE
How to enable short_open_tag

### ISSUE THREAD

**Issue by marcodamm** [Varying-Vagrant-Vagrants/VVV#679]
I have inherited a relatively large PHP project and some of the files use short open tags. I tried setting 

`short_open_tag = On`

in the VMs `/etc/php5/cli/php.ini` and restarting the webserver, the VM, etc., but vvv's phpinfo still tells me that `short_open_tag = Off`

Do I need to edit another php.ini for this to work or am I missing something different here?

**Comment by cfoellmann** [comment]
the file you want to change is `/etc/php5/fpm/php.ini`.
The file you changed is for php code executed in the linux shell.

**Comment by marcodamm** [comment]
Hi Christian,

Sorry, I forgot that I originally enabled those as well, but that did not help either.
phpinfo is still telling me that short_open_tags are set to Off

**Comment by cfoellmann** [comment]
did you execute `service php-fpm restart`?

**Comment by marcodamm** [comment]
restarted with `service php5-fpm restart` again for good measure, but that did not change anything. short_open is still listed as being `Off`

**Comment by cfoellmann** [comment]
Have a look at `/etc/php5/fpm/conf.d/php-custom.ini`

**Comment by cfoellmann** [comment]
@jeremyfelt this is a good example for the fact that we need some other kind of public support system for VVV
