### ISSUE TITLE
Downloading/extracting phpMyAdmin 4.2.13.1 fails

### ISSUE THREAD

**Issue by schikulski** [Varying-Vagrant-Vagrants/VVV#692]
Running ```vagrant up``` I'm getting the following error when it's trying to install phpmyadmin.

    ==> default: Downloading phpMyAdmin 4.2.13.1...
    ==> default: tar: 
    ==> default: This does not look like a tar archive
    ==> default: 
    ==> default: gzip: 
    ==> default: stdin: unexpected end of file
    ==> default: tar: 
    ==> default: Child returned status 1
    ==> default: tar: 
    ==> default: Error is not recoverable: exiting now
    ==> default: mv: 
    ==> default: cannot stat ‘phpMyAdmin-4.2.13.1-all-languages’
    ==> default: : No such file or directory
    ==> default: cp: 
    ==> default: cannot create regular file ‘/srv/www/default/database-admin/’
    ==> default: : Not a directory

Looks like the file that it's trying to download isn't a tar archive.
No biggie. Can always use the ```mysql```, but let me know if someone knows how to fix this.

Vagrant 1.7.2
OS X 10.10.4

**Comment by cfoellmann** [comment]
you need to update the VVV files. It was fixes in 111cf5f7de7f1b6d79f312b98755ed768d6a7ef7 / 30d88d99d18b3f97289fa4f1ecf6cc8b7ebc5f96

**Comment by schikulski** [comment]
Great, thanks!
