### ISSUE TITLE
general suggestions to improve your "read me" file.

### ISSUE THREAD

**Issue by sohaeb** [Varying-Vagrant-Vagrants/VVV#695]
I just learned vagrant yesterday (newbie). Anyway, found your VVV through someone.  Thank you guys for this. 

Anyway, I was trying to follow your tutorial but it was kinda complicated lol. I would just like to give some suggestions that might make it faster for us to figure out how to install a vagrant box that is not included in the https://atlas.hashicorp.com/boxes/search

1- I suggest changing the title from "The First Vagrant Up" to "how to install"
2- Put the How to install at the top
3- Include how to install your vagrant box. 
i.e: Clone our vagrant box then run "$vagrant box add /path/to/VVV --name". 
4- Remove the "vagrant-hostsupdater" plugin since using it will end up with this error:

```
    Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:

    Could not find gem 'vagrant-hostsupdate (>= 0) ruby' in the gems available on this machine.
```

5- More noob friendly tutorial for where the location of the host file is ?

I hope this wont come off as too harsh. Just some suggestions to help newbies like me.

EDIT: I just found out that suggestion number 3 was mentioned as the step number 5 in your read me file. I would suggest making it step #3 and make step #2 & #3 one step

**Comment by jeremyfelt** [comment]
Thanks for the suggestions @sohaeb! We're always looking for ways to make the documentation better and easier to follow. I'll take a closer look at this when I dig through README the next time.

**Comment by jeremyfelt** [comment]
I'm going to close this out with our docs refresh in #1112. Thanks!
