### ISSUE TITLE
Your current setup does not support InnoDB Full-Text Search. MySQL version 5.6.4 or later is required

### ISSUE THREAD

**Issue by shaneholloman** [Varying-Vagrant-Vagrants/VVV#696]
I use https://deliciousbrains.com/wp-migrate-db-pro/ for my dev stuff

I have a production site that uses InnoDB Fulltext Indexes. What is the procedure update my local VVV installation to handle this please?

Many thanks in advance... there's a small PayPal gift waiting for the solution!

**Comment by grappler** [comment]
Strange. I use VVV without any issues with Migrate DB Pro.
