### ISSUE TITLE
npm 'jsx' package doesn't watch appropriately

### ISSUE THREAD

**Issue by caseypatrickdriscoll** [Varying-Vagrant-Vagrants/VVV#700]
Not a high priority, just something I noticed. Currently just watching with jsx on local Mac.

The node package `jsx` for compiling jsx files doesn't watch correctly on Ubuntu 14.04. It compiles the first time, then just sits. 

http://stackoverflow.com/questions/22739672/react-jsx-watch-does-nothing-after-first-conversion
https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager

**Comment by jeremyfelt** [comment]
I'm going to close this out as a non-VVV issue because I don't think there's anything we can do, but it is good to have logged here for reference.
