### ISSUE TITLE
Cannot access local WordPress Dashboard; redirects to live site

### ISSUE THREAD

**Issue by ronezone** [Varying-Vagrant-Vagrants/VVV#701]
My live site: `http://www.myexample.com`

My VVV custom site:  `local.myexample.dev`

I've populated `~/vagrant-local/www/myexample-com/` with the contents of the live site's `/htdocs` and also imported the live site's DB.

Whenever I attempt to login via `local.myexample.dev/wp-admin` the page redirects to `www.myexample.com/wp-login.php?redirect_to=http%3A%2F%2Flocal.myexample.dev%2Fwp-admin%2F&reauth=1` and upon login I arrive at `http://www.myexample.com/wp-admin/`

I know I need to change a reference to the live site's URL somewhere, but don't know where.  Do I need to update the DB and replace all instances of `www.myexample.com` with `local.myexample.dev` ?  Or maybe something in `wp-login.php`?  Can someone please help?

**Comment by ronezone** [comment]
Found my own answer (of course immediately after submitting new issue.)  I accessed the DB via phpMyAdmin and changed the `siteurl` to http://local.myexample.dev in `wp_options` table.

I know this is not really an issue with VVV, but maybe this info will help others better use VVV.

**Comment by ronezone** [comment]
I actually wound-up having to search and replace entire DB; exported DB as "REPLACE"; then imported

In VIM...

FIND:  www.myexample.com
REPLACE WITH:  local.myexample.dev

FIND:  "myexample.com"
REPLACE WITH:  "myexample.dev"

**Comment by zamoose** [comment]
You can also use WP-CLI's `search-replace` sub command.  

--
Doug Stewart
