### ISSUE TITLE
"host path of shared folder missing" 

### ISSUE THREAD

**Issue by dantveita** [Varying-Vagrant-Vagrants/VVV#709]
Yesterday: installed vagrant vvv, did my first ever "vagrant up" with great success. didnt do much though because it was sleepytime.

Today: booting up iTerm, firing off "vagrant up", but receiving this 

![image](https://cloud.githubusercontent.com/assets/13351909/8839498/4a1112d6-30d6-11e5-8252-25d4c8aa130f.png)

being a noob at this, im not sure where to start looking for answers. why would this happen? it worked yesterday?

**Comment by jeremyfelt** [comment]
Sorry you never got a reply. 😞 

Please reopen if you still need help!
