### ISSUE TITLE
Sync homebin to local folder

### ISSUE THREAD

**Issue by jxmallett** [Varying-Vagrant-Vagrants/VVV#710]
Is there a reason the `/home/vagrant/bin` folder isn't linked to `config/homebin`? It looks like one is just a copy of the other but, as it stands, I have to run `vagrant provision` in order to synchronize them. This makes the writing and testing of custom halt scripts etc. quite tedious.

Aside from that, I'm loving VVV!

**Comment by tomjn** [comment]
Not entirely sure actually, perhaps @LoreleiAurora can shed some light on this
