### ISSUE TITLE
Symlinks in host machine do not work in www that is mounted to Virtualbox

### ISSUE THREAD

**Issue by meglio** [Varying-Vagrant-Vagrants/VVV#711]
My setup is the following:
- macos
- wordpress plugin in ~/wp-plugin
- vvv/www/wordpress-default/wp-content/plugins/wp-plugin symlinked to ~/wp-plugin
- after `vagrant up` and `vagrant ssh` and then `ls -al` the wp-content directory, it shows:
  `wp-plugin -> /Users/meglio/wp-plugin/`

So, symlinks get no transformed.

All configuration that is needed to allow for symlinks to work anywhere inside www folder should be ON by default in Vagrantfile. Could you fix this?

**Comment by cfoellmann** [comment]
See #592 
It works on windows but maybe it does on OS X, too.
Let me know there if it does

**Comment by cfoellmann** [comment]
@meglio does #715 fix this for you?
Can you please test and give feedback. Would be much appreciated

**Comment by Mte90** [comment]
We changed a lot of things about folders that are simylinked so is better to do a new ticket if it is still a problem.
