### ISSUE TITLE
connection Timeout or slow to ssh 127.0.0.1:2222

### ISSUE THREAD

**Issue by pascalcarmoni** [Varying-Vagrant-Vagrants/VVV#717]
I fix it by adding "UseDNS no" to /etc/ssh/sshd_config
To edit the file on my box I need to do : sudo nano -w /etc/ssh/sshd_config
There's another way to do it via VVV config file or vagrantFile?
Thanks

**Comment by iandunn** [comment]
`UseDNS no` didn't work for me, so there may be multiple causes.

A workaround is to using `ssh` directly, instead of `vagrant ssh`. Adding this to `~/.ssh/config` on the host machine makes it just as convenient. Make sure to update the `Host` and `IdentityFile`.

```
Host vvv-personal
  HostName 192.168.50.4
  User vagrant
  Port 22  
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/ian/vhosts/vvv-personal/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
```

Related mitchellh/vagrant#2462

**Comment by richard-scott** [comment]
When you run:
```
$ vagrant ssh --debug
```

Vagrant does a lot of background work each time it connects... Vagrant takes a while to initially output debug data to the console, and then a few seconds pass until it actually attempts to SSH to the VM

Surely that information could be cached as its not going to change (much) next time given we are still on the same host?

**Comment by tomjn** [comment]
`vagrant ssh-config` will give you something you can put in your ssh config for a faster direct SSH rather than running vagrant
