### ISSUE TITLE
How to target individual domains via ip?

### ISSUE THREAD

**Issue by cratervale** [Varying-Vagrant-Vagrants/VVV#718]
I am using nginx to set up a local proxy to forward the vagrant domain http://local.wordpress.dev to a localhost route (http://localhost:5001/blog).  However, the alias keeps resolving to the dashboard page. 

How can I access the local.wordpress.dev domain directly?  Can this be done with the ip address?

**Comment by cratervale** [comment]
Found the answer after a few hours of hunting.  I wish this was more clear in the documentation -- 

Target http://local.wordpress.dev with http://local.wordpress.192.168.50.4.xip.io (notice no .dev)

**Comment by salcode** [comment]
I prefer using xip.io for accessing sites from other machines on my network (though ngrok can be used as well).  You might also want to check out #263 for a lot of discussion on the topic.

My notes and the specific `Customfile` I use are available at http://salferrarello.com/vagrant-vvv-setup-wordpress/
