### ISSUE TITLE
xdebug 502

### ISSUE THREAD

**Issue by jmarceli** [Varying-Vagrant-Vagrants/VVV#719]
After enabling `xdebug` and generating some mysql error like (it might be any mysql bug):

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'xyz' cannot be null
```

If I leave default `xdebug` configuration:

```
xdebug.var_display_max_children = -1
xdebug.var_display_max_data = -1
xdebug.var_display_max_depth = -1
```

I get **502 Bad Gateway** instead of error message mentioned above.

My only working solution is to comment out `xdebug` settings to use default values.

The real cause of the problem is probably related to some nginx or php-fpm settings but I don't know which one.

**Comment by tomjn** [comment]
Since this predates VVV 2 I'm going to close for now, but if this is still a problem on `develop` or `2.2.1` comment and mention me and I'll reopen
