### ISSUE TITLE
Very strange issue: site forces /wp-admin/setup-config.php after saving any file

### ISSUE THREAD

**Issue by MickeyKay** [Varying-Vagrant-Vagrants/VVV#720]
Here's a screen cast: http://recordit.co/U4bde8Ko4i

Steps I'm taking:
1. VVV was broken and I'm not super savvy, so I completely deleted and re-installed it following the steps in the readme.
1. After first `vagrant up`, everything seems great.
1. Go to edit one of the plugin files, and after saving, the site suddenly points me to `/wp-admin/setup-config.php` as though the wp-config.php file isn't there (although it is, and the permissions seem okay on first glance).
1. Run `vagrant halt`
1. Run `vagrant up`
1. Site seems to be working again
1. Try to save my plugin file and the same issue arises

Any ideas what might be causing this issue? Is there debugging info I can provide that would be helpful?

I do have the following installed:
* vagrant-hostsupdater plugin
* vagrant-triggers plugin
* https://github.com/bradp/vv (fork of vvv-site-wizard)

Thanks!

**Comment by michaelbeil** [comment]
What versions of Vagrant and Virtual Box do you have installed?

**Comment by MickeyKay** [comment]
Vagrant: 1.7.4
VirtualBox: 4.3.14 r95030

Just an update. At first it seemed like saving files was causing this issue, however now it appears as though this is just occurring on it's on at some sort of interval. For example, I repeated the process of re-entering the db details at `/wp-admin/setup-config.php` (even though this doesn't even write to wp-config.php, but somehow seems to trigger something that again makes this okay), and without even editing any files, the issue appeared to re-arise after a few minutes.

**Comment by MickeyKay** [comment]
btw - hi @michaelbeil :) Been a while!

**Comment by MickeyKay** [comment]
Another update. . .

So I tried running `vagrant destroy` and `vagrant up --provision` to see if maybe something had gone wrong on the first try, but no difference.

Also, I've confirmed that this happens just from clicking around the admin for long enough (and potentially refreshing a page) - here's a screen cast for you to see: http://recordit.co/T35eSVBl5r

Steps:
1. Fill out http://local.wordpress-trunk.dev/wp-admin/setup-config.php, even though wp-config.php already exists, and even though this process says it can't write to wp-config.php 
1. Click around the nav for a while
1. Refresh one page
1. Suddenly redirected to  http://local.wordpress-trunk.dev/wp-admin/setup-config.php again

**Comment by MickeyKay** [comment]
So I finally seem to have resolved this by removing the entire /vagrant-local folder and installing the tagged 1.2.0 release from scratch. 

It could've just been that the original provision attempts failed in some way, however I tried re-provisioning numerous times. So that leads me to wonder if maybe there is an issue with the master branch, as this seems to work fine now that I'm running the 1.2.0 release directly.

Any thoughts/insights would be much appreciated!

**Comment by vardumper** [comment]
This issue isn't dead just yet. I am having the same issue on WP 5.2.4 and Docker...  Just FYI.

**Comment by Mte90** [comment]
It is the case to open a new ticket because in 4 years a lot of things are changed
