### ISSUE TITLE
404.php not working

### ISSUE THREAD

**Issue by altrovideo** [Varying-Vagrant-Vagrants/VVV#721]
Hi,
Maybe it's my fault, but I can't be able to test the 404.php theme file using vvv vagrant: have I to change nginx.conf or am I missing something?

Thank you
Bye

**Comment by salcode** [comment]
Your permalinks may be set to the default `http://local.wordpress.dev/?p=123`, in which case going to http://local.wordpress.dev/page-does-not-exist/ will display the home page (not the 404 page).

I'd look at http://local.wordpress.dev/wp-admin/options-permalink.php and if you are set to the default change it to __Post name__.

![image](https://cloud.githubusercontent.com/assets/5194588/9311414/f8b7d650-44e3-11e5-9f84-1a8b55da8fc6.png)
