### ISSUE TITLE
xip.io doesn't work for me

### ISSUE THREAD

**Issue by MickeyKay** [Varying-Vagrant-Vagrants/VVV#723]
So I've been attempting to find a way to test my locally developed sites on my phone, which has led me to xip.io. I've taken a peek at a bunch of different tutorials, including the following:
- https://jeremyfelt.com/2015/01/31/various-networking-configurations-vvv/
- http://salferrarello.com/vagrant-vvv-setup-wordpress/
- http://webdevstudios.com/2015/08/04/how-to-view-a-locally-developed-website-devices/

For background, I'm running:
- Vagrant 1.7.4
- Virtual Box 4.3.14 r95030
- VVV 1.2.0
- vagrant-hostsupdater plugin
- vagrant-triggers plugin
- Variable VVV (https://github.com/bradp/vv) - similar to VVV Site Wizard

Most recently I attempted the steps outlined here: http://webdevstudios.com/2015/08/04/how-to-view-a-locally-developed-website-devices/
1. Add a `Customfile` to my /vagrant-local folder with `config.vm.network :public_network`
2. Run `vagrant up` and select option [en0: Wi-Fi (AirPort)] for the network bridge interface.
3. Run `vagrant ssh` and `ifconfig` to get the IP address for my phone (192.168.1.29).
4. Visit `local.wordpress.192.168.1.29.xip.io` on my iPhone.
5. See the following:
   ![image](https://cloud.githubusercontent.com/assets/3189678/9290931/dc8f5bd2-4359-11e5-9ba1-a64bc2fb336d.png)
6. Notice that the stylesheet reference is clearly incorrect (as many others, I'm sure), and links still point to `local.wordpress.dev` - they don't preserve the xip.io URL schema.
7. Try installing and activating Root Relative URL's plugin, which fixes some issues, but breaks other plugin links - not functional. Is this supposed to even be necessary, or should VVV handle this automatically?

Any idea what I'm doing wrong? Are there other settings I was supposed to configure that I missed?

Any and all help would be much appreciated - thanks!

**Comment by ezekg** [comment]
Since it looks like xip.io _is_ doing it's job (acting as a wildcard DNS), try using the [Dynamic Hostname](https://wordpress.org/plugins/dynamic-hostname/) plugin.
