### ISSUE TITLE
Include support for running QUnit tests

### ISSUE THREAD

**Issue by ntwb** [Varying-Vagrant-Vagrants/VVV#724]
To be able to run WordPress' Qunit test framework a tweak or two to `wordpress-develop` will be needed.

To run the QUnit tests you need to run `/tests/qunit/index.html` from the "develop" repo checkout.

Currently both `http://src.wordpress-develop.dev` and `http://build.wordpress-develop.dev` do not allow us access to the "parent root" folder of the checkout which is where `/tests/qunit/index.html` is located.

Possibly setting up a third root e.g `http://qunit.wordpress-develop.dev` would be the quickest/easiest option at the moment so that e.g. `http://qunit.wordpress-develop.dev/tests/qunit/index.html` is available.

Thoughts? Ideas? Other suggestions?

**Comment by jeremyfelt** [comment]
Good call, QUnit access would be nice. We could probably setup a static alias in nginx to point src.wordpress-develop.dev/tests/ to the proper directory. We don't have to deal with PHP there, so it may just be a couple lines.

**Comment by ntwb** [comment]
Let's close this issue, I've just found out that you can run the QUnit tests using the `file:///` protocol e.g: `file:///Users/netweb/dev/vvv/wordpress-develop/tests/qunit/index.html`

Updated QUnit docs https://make.wordpress.org/core/handbook/testing/automated-testing/qunit/
