### ISSUE TITLE
Provision hangs on COMPOSER_HOME=/usr/local/src/composer composer self-update line

### ISSUE THREAD

**Issue by mariusvetrici** [Varying-Vagrant-Vagrants/VVV#725]
Hello, 

today I ran into this issue: Upon reprovisioning the virtual machine, it started hanging up on this last message:
==> default: ack-grep already installed

I debugged the provision.sh script and seems that the script is actually hanging up on this line:
COMPOSER_HOME=/usr/local/src/composer composer self-update

I executed this line in the Ubuntu terminal (vagrant ssh) and it just hangs up - nothing happens.

I upgraded the virtual box and pulled the project from git, but still get the same issue.

Any clue to this?

Thank you in advance for any help.

**Comment by mariusvetrici** [comment]
Seems that this issue fixes with this pull request:
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/729

**Comment by jeremyfelt** [comment]
Hi @mariusvetrici, thanks for the ticket and sorry for the delay in response.

I'm not able to reproduce this issue during re-provisioning at this point. I don't think I want to merge #729 in unless we're sure it resolves the issue at hand. Provisioning already runs as root, so sudo should not be necessary here.

I'm going to leave this open for now pending steps to reproduce. It's possible some other update has helped to resolve the issue.
