### ISSUE TITLE
Cant Access local.wordpress.dev or create new sites?

### ISSUE THREAD

**Issue by marklovett** [Varying-Vagrant-Vagrants/VVV#727]
Having trouble getting VVV to work properly on my mac. After installation of vvv, virtual box and sequel pro the result is that I can access some of the default vvv sites but can't create any new sites.

URL: http://local.wordpress.dev     cant access
/src URL: http://src.wordpress-develop.dev     -   cant access
URL: http://local.wordpress-trunk.dev     - is accessible
/build URL: http://build.wordpress-develop.dev    -    is accessible

Running:
Virtual Box 4.3.3 
Vagrant 1.7.4
vagrant-hostsupdater  0.0.11

The new sites that I have created were added in users/marklovett instead of users/marklovett/vagrant-local/www and contained 4 files. 
vvv-hosts 
vvv-init.sh 
webexperts.conf 
wp-cli.yml

Also, when using vv to create new site getting errors: default: Warning: DocumentRoot [/srv/www/wordpress-default] does not exist

When I go in the browser to my new sites I get message Not Found.
When I try to access local.wordpress.dev it says Not Found  Apache/2.2.22 (Ubuntu) Server at local.wordpress.dev Port 80

Spoke to Brad at vv, and he feels it's a vvv issue not a vv issue.

A couple of basic questions:
Does MAMP need to be shut down while working with vvv ?
Also, must sequel pro be running while working with vvv ?

Will you please give me some help to get it working?

**Comment by jeremyfelt** [comment]
I think the Apache 404 indicates that another server is capturing the request on that host/IP. It sounds like MAMP is intercepting it. I would check your /etc/hosts file to see where local.wordpress.dev as well as what IP MAMP is responding to.
