### ISSUE TITLE
Can't shutdown install, hangs on vagrant triggers

### ISSUE THREAD

**Issue by willenglishiv** [Varying-Vagrant-Vagrants/VVV#728]
currently using the latest develop branch of VVV,
Mac OSX 10.5.5
vagrant 1.7.4
virtualbox 5.0.2

and I updated vagrant-triggers to 0.5.1.

I recently upgraded everything because I tried running vagrant_halt on my terminal and it would not shut down the virtualbox.  It hangs on the Executing command 'vagrant ssh -c vagrant_halt' command until I CTRL+C out of the execution.  I can still vagrant ssh in and run vagrant_halt myself.

I've tried destroying the VM from the VirtualBox GUI and re-provision the box.

```
homemac:Sites wenglish$ vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
^C
==> default: Waiting for cleanup before exiting...
==> default: ==> default: Waiting for cleanup before exiting...
homemac:Sites wenglish$ ==> default: Killed by signal 2.
==> default: Command execution finished.
The command "vagrant ssh -c 'vagrant_halt'" returned a failed exit code. The
error output is shown below:

Killed by signal 2.
```

**Comment by GaryJones** [comment]
Latest is now virtualbox 5.0.16, vagrant 1.8.1 and VVV 1.3.0, so updating all, re-provisioning may help.
