### ISSUE TITLE
Create new page to display public_network IP address

### ISSUE THREAD

**Issue by salcode** [Varying-Vagrant-Vagrants/VVV#730]
Lots of great discussion in #566 helped me understand how to use the **public_network** property properly.

@jpry's notes about `vagrant ssh` / `ifconfig` to determine the public_network IP address are great

I'm wondering if we could create a page at something like http://vvv.dev/public-ip/ which could display either:

> This site is not available on any public IP, see how to configure public_network

or

> Your public IP is: <display IP address here>

I'm happy to look into this but I wanted to float the idea first.

**Comment by cfoellmann** [comment]
Good idea :+1: 
I think this shouldn't get a seperate page. Put it on the dashboard page.

**Comment by jeremyfelt** [comment]
Agreed, I think having this as part of the default dashboard would make sense.

**Comment by salcode** [comment]
I've been looking into this.  I'm not sure how best to tackle this so I'm going to put some of my notes here in case anyone else has any insights or recommendations.

I've not determined a way to access the Vagrant configuration from within the Guest machine.  Ideally, I'd like to determine if the `config.vm.network :public_network` setting were in place, since if it is not, we would skip displaying any information about a public IP address.

I'd also like to read the private network IP from the Vagrant configuration if there is one (e.g. `config.vm.network :private_network, ip: "192.168.50.4"`).  Knowing this information would help me exclude it when I extract the public IP address from `ifconfig`.

**Comment by salcode** [comment]
## Current state

I'm listing the IP addresses returned by `/sbin/ifconfig` however this results in addresses that do not resolve.  Right now the output looks like this for me:

![image](https://cloud.githubusercontent.com/assets/5194588/11195781/c6fd40ba-8c81-11e5-8250-3e9cf7953648.png)

In this case http://192.168.0.101/ is the publicly accessible IP address.  I'd like to mark it as the public IP but I'm not clever enough to determine this from within the Guest OS.

## Next Steps

My thought is we could make AJAX calls to each of the IP addresses and determine if they return a page containing `Varying Vagrant Vagrants Dashboard` in the __title__ tag.  If they do contain that title tag, we mark the URL in some way.

This feels over engineered but is currently my best thought.  I thought I'd include these notes for two reasons:

1.  To remind me of my game plan for when future me sits down to write this
2.  To give others an opportunity to point out problems with this approach or a more elegant solution

**Comment by topdown** [comment]
Why not just `$_SERVER['SERVER_ADDR'];`
I realize it does not help for private IP. But its less load then scanning a config via PHP shell command.

**Comment by salcode** [comment]
@topdown thank you for the suggestion but I don't think this will work.

When I tested outputting `$_SERVER['SERVER_ADDR']`, the value varied based on the IP address used to load the page.

![image](https://cloud.githubusercontent.com/assets/5194588/11195781/c6fd40ba-8c81-11e5-8250-3e9cf7953648.png)

In this scenario using the public network option, I get the following values when I use these different URLs.

- http://vvv.dev/, displays `192.168.50.4`
- http://192.168.50.4/, displays `192.168.50.4`
- http://192.168.0.101/, displays `192.168.0.101`

Since `192.168.0.101` is the public IP, this is the IP we want to display regardless of which URL is used to access the page.

To review the goal of this patch, when someone uses the public network option, I'd like them to be presented with the public IP address without having to hunt for it.  Specifically, I'd like them to be able to visit the default page and see it listed there.

**Comment by tomjn** [comment]
I'm going to close this out as we don't officially support exposing VVV to the public web for security reasons. It's not hardened for public exposure.
