### ISSUE TITLE
Strange Issue: No wp-config or db tables created

### ISSUE THREAD

**Issue by andrew40** [Varying-Vagrant-Vagrants/VVV#733]
Had not had this with VVV before but today no wp-config files created on provision and the db are created but no tables imported.

==> default: Updating WordPress Stable...
==> default: Error: wp-config.php not found.
==> default: Either create one manually or use `wp core config`.
==> default: Updating WordPress trunk...

Not sure how to fix this. As I have said never had it before. Have halted, destroyed, reprovisioned and it happens the same..

**Comment by kellenmace** [comment]
Hi Andrew. I'm encountering a similar issue right now: my sites all have wp-config.php files, and I have the necessary DB lines in init-custom.sql. When vagrant boots up, it only creates the databases though – no tables are imported. Were you ever able to resolve this issue?
