### ISSUE TITLE
Can not install on Win 10 + VirtualBox 5.0.2

### ISSUE THREAD

**Issue by webmandesign** [Varying-Vagrant-Vagrants/VVV#735]
Hi,

I've read and heard many times that using Vagrant for development is much better solution than using XAMPP or similar approach. So I would like to give it a try. However, I am not able to make it work on Windows 10 with VirtualBox 5.0.2 (I've also tried the newest 5.0.3 beta build with no luck).

The `vagrant up` is not able to create and configure the host network interface. I've tried manually, in VirtualBox Prefferences screen, but as soon as I close the app, the new network interface I've just created is gone (not sure if this is normal behavior).

Here is the output of `vagrant up` command:

	PATH_TO\Vagrant\wordpress-vvv>vagrant up
	Bringing machine 'default' up with 'virtualbox' provider...
	==> default: Checking if box 'ubuntu/trusty64' is up to date...
	==> default: Clearing any previously set network interfaces...
	There was an error while executing `VBoxManage`, a CLI used by Vagrant
	for controlling VirtualBox. The command and stderr is shown below.

	Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #3", "--ip", "192.168.50.1", "--netmask", "255.255.255.0"]

	Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
	VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
	VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 204 of file VBoxManageHostonly.cpp

	PATH_TO\Vagrant\wordpress-vvv>

My question is whether this is an issue with VirtualBox and whether there is some workaround/solution for the problem so I could install VVV correctly on my machine.

Thanks and regards,

Oliver

**Comment by grappler** [comment]
The current stable version of VirtualBox is not compatible with Windows 10. If you install the current dev version it should work fine. I am using VVV on two Windows 10 computers.

I was getting the same error when using the VirtualBox stable version.

**Comment by webmandesign** [comment]
Hi,

Thanks for the answer. I've actually tried the dev version downloaded from https://www.virtualbox.org/wiki/Testbuilds but with no luck. I will try that again then.

Regards,

Oliver

**Comment by Nikschavan** [comment]
Even I was having problems getting the dev build of virtual box to work on windows 10.
Te problem is Host only networks are not working in windows 10

So My Solution to this is - 

1. I disabled the `Private Network` by commenting line `config.vm.network :private_network, ip: "192.168.50.4"` in the `vagrantfile`
2. And enabled the `Port Forwarding` by uncommenting the line `config.vm.network "forwarded_port", guest: 80, host: 8080`
3. I manually added host enteries in the windows `hosts` file and set ip addess  to be `127.0.0.1`
So now I had all my sites available at port 8080, Eg `http://local.wordpress.dev:8080`
4. I forwarded all traffic from `127.0.0.1:8080` to `127.0.0.1` by runing command `netsh interface portproxy add v4tov4 listenport=80 listenaddress=127.0.0.1 connectport=8080 connectaddress=127.0.0.1` in command prompt as **Administrator**

So VVV works just normal without having to add port 8080 at the end.

**Comment by webmandesign** [comment]
Hi,

Thanks for your solution @Nikschavan, but as I don't want to mess with Windows files, this is not for me ;) But seems to be a good workaround, thanks for sharing.

I've tried installing recent dev build (`VirtualBox-5.0.3-102322-Win.exe`), but still doesn't work. I've also tried to set the VirtualBox to run in Win7 (and also 8) compatibility mode and with admin privileges. No luck.

I guess it's not time for Vagrant for me yet...

Thanks for help anyway.

Regards,

Oliver

**Comment by DevinWalker** [comment]
I have the latest VirtualBox working on Windows 10 but now I'm getting this when I run `vagrant up`:

```
The provider 'virtualbox' that was requested to back the machi                                     ne
'default' is reporting that it isn't usable on this system. Th                                     e
reason is shown below:

Vagrant has detected that you have a version of VirtualBox ins                                     talled
that is not supported. Please install one of the supported ver                                     sions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

**Comment by eric7** [comment]
I fixed this issue by Downgrading to 4.3

I was getting an issue with it running after running the "vagrant up" command

**Comment by rwrobe** [comment]
I'm seeing a strange situation in which VB and VVV work just fine in Chrome and FireFox, but Microsoft Edge will not connect to the host entry or the IP address. Anyone else seeing this?

**Comment by lancewillett** [comment]
Why can't we use Virtualbox 5.0.x? I upgraded to be able to run the latest features for Windows VMs and now my VVV setup is borked. :/

**Comment by webmandesign** [comment]
Upgrading to VirtualBox 5.0.4 resolved my issue and I'm able to use VVV! Hooray!

**Comment by eduplessis** [comment]
@rwrobe  I have the same problem with another box

**Comment by eduplessis** [comment]
@rwrobe When using Fiddler. Edge is responding nicely

**Comment by N1010N** [comment]
I have the same problem in Windows 10 and virtual box 5.0.10 extension

**Comment by ronezone** [comment]
@Nikschavan, a 1000 thank yous!  Your solution was my only hope.  (HP Envy 15 i7 64-bit)

Windows 10 Pro + VirtualBox-4.3.34 + Vagrant-1.7.4 + vagrant up!

**Comment by onthisearth** [comment]
@rwrobe Were you able to solve the problem? Having the same problem (newest versions of Windows 10, Vagrant, VVV, VB).
