### ISSUE TITLE
phpcs: command not found

### ISSUE THREAD

**Issue by mantismamita** [Varying-Vagrant-Vagrants/VVV#736]
I have been trying to run `phpcs` from the command line but can only run it by including the complete path to phpcs in which case it can't find the appropriate file as in `phpcs --standard=WordPress -s wp-cron.php` because it is in the wrong directory. How can I get it so I can run it in the right place with out getting `bash: phpcs: command not found`? I realise I might be missing something here.

**Comment by ericandrewlewis** [comment]
`phpcs` is installed inside the virtual machine. Are you trying to access it on your host?

**Comment by mantismamita** [comment]
Yes, I am just trying to run the `phpcs` command within the wp installation. For now the only way I can run the command is by going directly to the `phpcs` folder in the virtual machine.

**Comment by jeremyfelt** [comment]
Sorry for letting this sit open for so long. I'm able to run `phpcs` inside the VM after a new provision and haven't had trouble in the past. I'm hoping that this was due to an error during provisioning and that this was solved at some point in the last year and half.

**Comment by mantismamita** [comment]
No problem. I think it was a provisioning error. Definitely has been solved since then :)
