### ISSUE TITLE
Vagrant Halt fails

### ISSUE THREAD

**Issue by bigandy** [Varying-Vagrant-Vagrants/VVV#740]
Running 'vagrant halt' I get the following error messages:

==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
==> default: bash: /home/vagrant/.bash_profile: Permission denied
==> default: bash: vagrant_halt: command not found
==> default: Command execution finished.
The command "vagrant ssh -c 'vagrant_halt'" returned a failed exit code. The
error output is shown below:

bash: /home/vagrant/.bash_profile: Permission denied
bash: vagrant_halt: command not found

Running vvv latest from github develop branch.
vagrant version: 1.7.4
virtualbox version 5.0.2
osx: El Capitan Public Beta 6, also tried on osx yosemite latest.

**Comment by vladimirlukyanov** [comment]
default: Warning: Connection timeout. Retrying... – same issue

**Comment by wesbos** [comment]
Same issue here - any ideas? Seems to be an SSH issue. I'm not on El Capitan yet...

**Comment by jeremyfelt** [comment]
The SSH issue may be related to #375. The original issue here may be related to Vagrant and El Capitan.

@bigandy: have you had any luck since posting this?

**Comment by bigandy** [comment]
Yes. Works well now.
