### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by TheAggressive** [Varying-Vagrant-Vagrants/VVV#744]
Installed on Windows 10 and when I pull up vvv.dev it comes back as connection timed out.

Any help or solutions to this problem??

Thanks!!

**Comment by cfoellmann** [comment]
why closed?

**Comment by TheAggressive** [comment]
I tried to upgrade the VirtualBox GuestAdditions to 5.0.4 with the command <code>vagrant plugin install vbguest</code>  

I uninstalled the current version of VirtualBox (5.0.4).

I deleted all virtualbox folders in <code>C:/Users/user_name/.VirtualBox</code> as well as <code>C:/Users/user_name/VirtualBox VMs</code> folder.

I then Downloaded VirtualBox 4.3.10 and installed since it's stated in the docs of VVV. 

Right Clicked and opened git bash with administrator rights.

<code>cd C:/to/the/folder/of/VVV</code>

ran <code>vagrant up</code>

it did the whole install again and set up. Tried to point my browser at vvv.dev and it worked. No time out this time. I then ran <code>vagrant halt</code> and waited for shutdown of VM. Restarted the host computer and once up opened Git Bash with adminstrator rights and cd to the directory of VVV and ran vagrant up again to make sure the vvv.dev comes up since sometimes it would work until the host computer is shut down and booted again, then it would not work. It worked again and since then has worked.
