### ISSUE TITLE
"RTL Tester" plugin issues

### ISSUE THREAD

**Issue by dashkevych** [Varying-Vagrant-Vagrants/VVV#746]
Hello,

I am just wondering if anybody had the same issues as I have with the "RTL Tester" plugin by By Yoav Farhi and Automattic ( https://wordpress.org/plugins/rtl-tester/ ). It, basically, messes up with the admin panel by ignoring css styling. Here is a screenshot: https://cloudup.com/cgk5eqbwLjU
Any ideas why it happens and how to fix it?
Thanks :)

**Comment by jeremyfelt** [comment]
Hi @dashkevych, thanks for stopping by!

I haven't seen that specific issue, though it looks like something is causing one or more resources to not load entirely. If you look at the browser's console, are there any errors listed?
