### ISSUE TITLE
WordPress $_SESSION Super Global Getting Resting

### ISSUE THREAD

**Issue by magbicaleman** [Varying-Vagrant-Vagrants/VVV#749]
If I visit a page and echo the session_id(), followed by refreshing the page the session_id changes every time. 

I'm aware that Wordpress is stateless and you need plugins to enable the idea of the super global $_SESSION. 

We have Pantheon's [wp-native-php-session](https://wordpress.org/plugins/wp-native-php-sessions/), installed in our Wordpress project, but this solves nothing. Looking at the session configs, the save_path is _/var/lib/php5_. Which does not seem to have read or write.

I've tried to created a folder in the root directory of the project called _sessions and then do an init_set and point the save_path to that folder. It's writeable, but this does not seem to be working either.

I'm not sure if this specified configuration in VVV, or perhaps I'm just writing my plugin logic an incorrect way but I'd love to have come clarity. Thanks!

**Comment by cfoellmann** [comment]
Is it possible that the plugin you are using to make this happen is not working as advertised?

**Comment by magbicaleman** [comment]
@cfoellmann Thanks for the quick reply.

That's definitely possible. What I want to find out, is if the _$_SESSION super global_ work as it is intended or does VVV suppress (by design) it because Wordpress is stateless.

**Comment by magbicaleman** [comment]
@cfoellmann so after _deactivating_ the [wp-native-php-session](https://wordpress.org/plugins/wp-native-php-sessions/) plugin, and the adding the following code to the top of wp-config-local.php

```php
if (!session_id())
    session_start();
```
My session_id is the same, after refresh. Thanks again for your feedback.

**Comment by cfoellmann** [comment]
No problem. Happy to help.
VVV does as little as possible to WP in its after-install state.
