### ISSUE TITLE
Add site without re-provisioning existing site

### ISSUE THREAD

**Issue by Shelob9** [Varying-Vagrant-Vagrants/VVV#753]
Not sure if this is a support or feature request, but I want to be able to provision new sites without running the complete provisioning process on existing sites? Mainly I'm trying to speed up the process and avoid SVN merge errors. Is this possible?

**Comment by ezekg** [comment]
You could probably take a look at the [provision.sh](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L522-L658) file and comment out the sections for the WordPress core updates (highlighted) and anything else you don't want to provision.

**Comment by Shelob9** [comment]
@ezekg Yes, that would do it. Wondering if its worth introducing a flag for this in the bash command.

**Comment by ezekg** [comment]
Either that or possibly migrating the provisioning scripts for WP core into a separate bash file that can be run manually if needed. But since I don't use the default WP sites, I just removed that section altogether.

**Comment by Shelob9** [comment]
Or this: https://github.com/bradp/VVV-Provision-Flipper

**Comment by jonathan-dejong** [comment]
Good god how great flippers default "quick" was... my provisioning took 60 seconds instead of the usual ~5min.

Of course I'd have to use the regular provisioning from time to time just to keep everything up to date but for getting a new project off the ground it's fantastic.

**Comment by jeremyfelt** [comment]
> Not sure if this is a support or feature request, but I want to be able to provision new sites without running the complete provisioning process on existing sites?

Yes. I think we should stop using `vagrant provision` to manage individual sites beyond what is originally configured with VVV. It should be possible to add custom sites by running a command within the VM.

I think the first step is to move the `custom_vvv` scripting into the `homebin/` directory so that it is accessible everywhere.

**Comment by jeremyfelt** [comment]
After the merge of #980, it is now possible to provision a new site with `vagrant provision --provision-with site-site-name`.
