### ISSUE TITLE
vagrant up Fails with SMB Error

### ISSUE THREAD

**Issue by alexphelps** [Varying-Vagrant-Vagrants/VVV#758]
On Mac OSX 10.11 (El Capitan), fresh install of Vagrant, fresh install of  VVV, I ran into an error trying to start VVV. 

`vagrant up` produces this error. 

```
SMB shared folders are only available when Vagrant is running
on Windows. The guest machine can be running non-Windows. Please use
another synced folder type.
```
After digging through the VagrantFile I commented line 232 that sets up smb for the file system which fixes it and am able to start VVV. 

```
if ! options[:type]
    #options[:type] = "smb"
end
```

I tried to install Samba, but with no avail, still haven't figured that out yet.

**Comment by steveworkman** [comment]
I can confirm that I get the same thing on El Capitan, not sure whether it works on other platforms

**Comment by timiwahalahti** [comment]
I can confirm this and previously told fixes with Yosmite (10.10.5).

**Comment by lkwdwrd** [comment]
This is going to be related with the Hyper-V support I helped add. That code should only be running when the provider is set to Hyper-V, but admittedly I only tested it with Hyper-V. I don't have time right this second to help fix it, but can do some cross platform testing this evening and get a fix in place for this.

```ruby
  # The Hyper-V Provider does not understand "dmode"/"fmode" in the "mount_options" as
  # those are specific to Virtualbox. Furthermore, the normal shared folders need to be
  # replaced with SMB shares. Here we switch all the shared folders to us SMB and then
  # override the www folder with options that make it Hyper-V compatible.
  config.vm.provider :hyperv do |v, override|
    override.vm.synced_folder "www/", "/srv/www/", :owner => "www-data", :mount_options => ["dir_mode=0775","file_mode=0774","forceuid","noperm","nobrl","mfsymlinks"]
    # Change all the folder to use SMB instead of Virtual Box shares
    config.vm.synced_folders.each do |id, options|
      if ! options[:type]
        options[:type] = "smb"
      end
    end
  end
```

I made the assumption that being wrapped in the provider statement it would prevent it from running when it wasn't in the Hyper-V environment. Commenting it out will work as a temporary fix for any other platform, but will kill the Hyper-V support which needs SMB mounts. If someone wants to experiment with other means of looping through the configured shared folders to set SMB for only the Hyper-V provider before I get to it, that will be the fix here.

**Comment by nekojira** [comment]
happening the same on Ubuntu 15.04

**Comment by ericmann** [comment]
@nekojira The PR linked above resolves the issue entirely without commenting anything out - apparently using `config` even inside a scoped conditional doesn't jive well with Vagrant's bundled Ruby interpreter.

**Comment by nekojira** [comment]
yes I meant the solution proposed in your commit not the commenting out proposed in the comment earlier - sorry it wasn't clear
