### ISSUE TITLE
Webgrind update / replacement needed

### ISSUE THREAD

**Issue by GaryJones** [Varying-Vagrant-Vagrants/VVV#760]
I've basically got the issue outlined [here](http://stackoverflow.com/questions/28962688/webgrind-not-shoing-function-names-or-file-source) and [here](http://stackoverflow.com/questions/29303996/xdebug-missing-function-names-show-only-numbers) - that the webgrind analyser is showing numbers instead of function names and line numbers. It's unusable with Xdebug 2.3+.

[This](https://github.com/michaelschiller/webgrind/) is one fork which [supports](https://github.com/michaelschiller/webgrind/commit/9c689d0f956f766f265b1378cc91f37d2345bce5) the function and file name compression that Xdebug 2.3+ introduced.

As a side note - if the cachegrindout file could be stored somewhere that the host machine could easily access it, then PHPStorm or other analysers could be used instead.

**Comment by jeremyfelt** [comment]
Thanks for catching that, @GaryJones! I've tested the fork and things seem to work great. Let's go for it.
