### ISSUE TITLE
Run composer inside vagrant with vvv-init.sh

### ISSUE THREAD

**Issue by jonathan-dejong** [Varying-Vagrant-Vagrants/VVV#762]
Hey!

Trying to run composer from within vagrant with the vvv-init bash script. 
I start off with an empty folder. Place a vvv-hosts file, vvv-nginx file, vvv-init file and a composer.json file in there. Do the necessary settings in each file then run vagrant provision. 

The site provisions, after htdocs have been created I run this code inside vvv-init to attempt to run composer from within vagrant. 

```
#Move composer.json into htdocs
	mv composer.json htdocs
	cd htdocs

	# Run composer
	echo "Update composer"
	vagrant ssh -c "composer install --prefer-dist"
```
(ignore the cd htdocs, it's there because I initially ran composer from outside vagrant).
It does not work. It always end up with `vagrant: command not found`. I've tried it with sudo, both on  the local computer and within vagrant.

Can't figure out what I need to do to make it work? When i ssh into vagrant manually composer is available (tested composer --version).

**Comment by jonathan-dejong** [comment]
Update:

so I realized I first need to cd to the new projects directory...
`vagrant ssh -c "cd /srv/www/projects/testprojekt/htdocs && composer install --prefer-dist"`.
However it still wont work when running this from within vvv-init. It works when i run this manually in the terminal tho.

**Comment by jonathan-dejong** [comment]
It seems it can't even use `vagrant ssh` from within the bash file?

**Comment by cfoellmann** [comment]
You do not need to use ssh here.
The script is running in the command line of the vvv  directly!
Just use it without vagrant ssh

**Comment by jonathan-dejong** [comment]
Yeah but if I want to run it as the vagrant user?
So you mean that vvv-init.sh already runs inside vagrant as the vagrant user?

**Comment by cfoellmann** [comment]
I am on the "road".
Yes, it is as if you are already logged in via ssh.
Do not hesitate to ask anything. You might get help ;-)

**Comment by jonathan-dejong** [comment]
Alright thanks for clearing that up for me @cfoellmann
