### ISSUE TITLE
Any issues with creating vvv-hosts and vvv-nginx.conf file dynamically?

### ISSUE THREAD

**Issue by jonathan-dejong** [Varying-Vagrant-Vagrants/VVV#763]
Hi!

I was just thinking about how to make setting up a new site even simpler for our company. 
We already have an `vvv-init.sh` file that's modified with wp cli and composer. 

Now I'm thinking wether we can create the necessary `vvv-hosts` and `vvv-nginx.conf` files directly from vvv-init.sh? That was we'd only need to modify one file to setup a new site and we could just have a few variables at the top of the file to fill in making it super easy. 

I was thinking something like this inside `vvv-init.sh` inside the check for htdocs but before htdocs dir is created:
```
#create vvv-hosts file automatically
echo "Create a vvv-hosts file"
printf "$SITE_URL" > vvv-hosts

#Create nginx file automatically
echo "Create nginx file"
printf "server {\nlisten			80;\nserver_name		$SITE_URL;\nroot			{vvv_path_to_folder}/htdocs;\ninclude			/etc/nginx/nginx-wp-common.conf;\n}" > vvv-nginx.conf

```

Can you see any issues/restrictions with this or would it be a good idea?

**Comment by jonathan-dejong** [comment]
So no feedback at all on this?? I would've thought it'd be a nice touch if it works :)

**Comment by topdown** [comment]
I'm pretty sure this package https://github.com/bradp/vv does what you are asking for.

**Comment by jeremyfelt** [comment]
Agreed, I think these efforts are probably better spent with tools outside of VVV. VV is a great way to go.

**Comment by jonathan-dejong** [comment]
Hi guys,

Sorry for possibly being unclear. I'm not asking wether you can add this to VVV.
I'm just asking if people smarter than me see an issue in us doing this for our own installation?
Like possible permissions problems or maybe just bad practice.

@topdown that package sort of does it but we've got a lot of customisation ourselves in these files so it won't do. It would just be another dependency that we've tweaked ourselves.
