### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#765]
I can see that the changelog is not updated from 9 months in develop branch and is difficult track all the new feature of that branch.

**Comment by jeremyfelt** [comment]
The changelog has now been updated for 1.3.0. It would be easier to update it as we go, I'll try to work on that as part of the process. :)

**Comment by cfoellmann** [comment]
@jeremyfelt we should look into the new github (pull request) templates to require devs to submit a changelog addition with the code for the feature

**Comment by jeremyfelt** [comment]
@cfoellmann I think I'd still prefer to maintain the changelog separately. Sometimes several different commits and PRs end up being related and can be grouped together. I'm okay with contributors not having to worry about that.
