### ISSUE TITLE
Enabling Docker provider in VVV VagrantFile

### ISSUE THREAD

**Issue by scarstens** [Varying-Vagrant-Vagrants/VVV#770]
Have you guys considered adding compatibility with the docker provider from Vagrant? I was forced to upgrade to VirtualBox 5.0.8, which no longer works with Vagrant, or VVV. I'm attempting to use Parallels, but with the big trend to move to Docker containers, seems like it would be a good fit for VVV?

https://docs.vagrantup.com/v2/docker/configuration.html

**Comment by jeremyfelt** [comment]
Hi @scarstens, thanks for the ticket. Sorry for the wait. :)

I haven't explored providing a Docker provider config in the default `Vagrantfile`. Is it something that could work in parallel with the other providers? Definitely open to adding this if someone submits a PR or approach that can be properly tested.

**Comment by cfoellmann** [comment]
@scarstens I am not sure if docker is anywhere near the scope of VVV but you should be able to run VVV with the current VB 5.x version. It does for me.

**Comment by scarstens** [comment]
@jeremyfelt @cfoellmann there is a docker driver already
https://www.vagrantup.com/docs/provisioning/docker.html

VVV just needs the added configuration to allow a flag to turn on docker as an option. The VVV option for parallels already works great, but docker is ... well free. I'm hoping docker performs better then virtualbox, which is why I was hoping to see an updated Vagrantfile config that had docker as an option.

**Comment by zamoose** [comment]
Seth:
What OS are you running? If it's anything other than Linux, Docker isn't
"free". It *has* to run on Linux, so if you're using Mac OS X, you'll need
to have Virtualbox anyways.

On Fri, Feb 26, 2016 at 1:44 AM, Seth Carstens <notifications@github.com>
wrote:

> @jeremyfelt <https://github.com/jeremyfelt> @cfoellmann
> <https://github.com/cfoellmann> there is a docker driver already
> https://www.vagrantup.com/docs/provisioning/docker.html
>
> VVV just needs the added configuration to allow a flag to turn on docker
> as an option. The VVV option for parallels already works great, but docker
> is ... well free. I'm hoping docker performs better then virtualbox, which
> is why I was hoping to see an updated Vagrantfile config that had docker as
> an option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/770#issuecomment-189132020>
> .
>



-- 
-Doug

**Comment by scarstens** [comment]
@zamoose I don't know what your talking about. I have a dozen or so docker containers  that I run in OSX right now, at zero cost. We are talking about the same docker right? Lol.

https://docs.docker.com/engine/installation/mac/

Cost... none.

**Comment by zamoose** [comment]
@scarstens you said 

> I'm hoping docker performs better then virtualbox

I'm saying Docker, unless you're running on Linux itself, *requires* Virtualbox (or Parallels, or HyperV, or VMware, etc.). If you're on a Mac, by default it will try to use Virtualbox to run the `default` VM, which it will then run Docker containers on top of. From the link you referenced:

> In an OS X installation, the docker daemon is running inside a Linux VM called default. The default is a lightweight Linux VM made specifically to run the Docker daemon on Mac OS X. The VM runs completely from RAM, is a small ~24MB download, and boots in approximately 5s.

A Dockerized VVV would still require a VM provider to be able to run on a Mac (or a Windows PC), as Docker itself requires Linux containers ([LXC](https://en.wikipedia.org/wiki/LXC)) to run. 

Adding the capability to run Docker containers within the Ubuntu base that VVV runs on by default may well have advantages and be a practical solution to various issues. What it isn't is "free" or likely to be more performant than simply running VVV directly.

Does that make sense?

**Comment by scarstens** [comment]
Word! Thanks for the explanation:

https://docs.docker.com/engine/installation/images/mac_docker_host.svg

**Comment by crissoca** [comment]
Hi guys just picking up the convo, I read that LXC was removed from docker, now with native Docker clients is there still a problem to implement support?

**Comment by diddledan** [comment]
Docker support will be especially useful on Windows due to the evilness that is the hyper-v provider requiring vagrant to be run as Administrator.

I need hyper-v for other tasks so I cannot use the VirtualBox provider. Native Docker backs-onto hyper-v but providers sugar for file-system sharing and the like.

**Comment by jeremyfelt** [comment]
I added a note to #968 for this as well. While entirely possible, I'm wary of the maintenance cost in supporting Docker as another provider. Thanks for all of the feedback on this ticket!

**Comment by patilswapnilv** [comment]
Any update on this?

**Comment by diddledan** [comment]
update from my side is that VVV is completely unusable on Windows for me now that the Hyper-V box is gone. My only choices now are remove Hyper-V and sacrifice OS-provided virtual machine support and development of Windows devices apps which require HyperV for emulating the devices, and sacrificing native Docker which also uses Hyper-V to back onto.

**Comment by patilswapnilv** [comment]
[Wocker](http://wckr.github.io/) seems to be a good alternative for using Vagrant along with Docker. At least for now. 

@diddledan No idea, if that is something which will help you. But it's worth checking.

**Comment by diddledan** [comment]
thanks for the pointer. however as the second step is "install virtualbox" then I'm assuming it requires boot2docker and therefore won't work with Native Docker (which is required in my setup because I have hyper-v installed for other things.)
