### ISSUE TITLE
Webgrind issue with newest versions of XDebug (2.3.x)

### ISSUE THREAD

**Issue by dkotter** [Varying-Vagrant-Vagrants/VVV#777]
This isn't necessarily an issue that needs to be fixed within VVV, but it's something I ran into and had to figure out, so thought I'd document that here if anyone else has the same issue.

But the newest versions of XDebug (2.3.x) introduce function name compression (can see ticket here for Webgrind: https://github.com/jokkedk/webgrind/issues/62) that results in just seeing numbers in Webgrind, instead of seeing function names. Also, the click to view code button won't take you to the right place.

So for anyone that's run vagrant provision lately, they'll be updated to the next version of Xdebug and they'll get this issue. I figured you could probably downgrade Xdebug, but I found a forked version of Webrind that fixed the issue: https://github.com/michaelschiller/webgrind

I ended up just changing the remote URL from https://github.com/jokkedk/webgrind.git to https://github.com/michaelschiller/webgrind.git and that fixed the issue for me. Don't think that's probably a permanent solution, as I'm not sure if this fork will be kept up-to-date, but until Webgrind fixes this themselves, this is a workaround for anyone that needs it.

**Comment by jeremyfelt** [comment]
Hey @dkotter, thanks for the report. #774 is in the develop branch of VVV, which fixes the issue for new provisions. Existing provisions will need to either do what you did (switch the remote) or delete the `default/webgrind` directory and run `vagrant provision` again. I toyed with switching the remote automatically, but that could confuse some things in the rarest of cases.
