### ISSUE TITLE
Running commands on vagrant up

### ISSUE THREAD

**Issue by jonathanbardo** [Varying-Vagrant-Vagrants/VVV#778]
Hey everyone!

I am trying to figure out the best method to run certain commands on vagrant up.

I always find myself running the following commands and I tried to automate it without any success.
```
xdebug_on
export PHP_IDE_CONFIG="serverName=src.wordpress-develop.dev"
```

I tried look at the provisionning script and couldn't find anything that would help me achieve this.

**Comment by cfoellmann** [comment]
maybe we can add an if clause to the trigger here https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L287-L306 for a custom file?

**Comment by jonathanbardo** [comment]
That was something I was going to propose but I wanted to make sure there wasn't any other way.

**Comment by cfoellmann** [comment]
maybe there is a "native" vagrant command you can add to the Vagrantfile. But I am no Vagrant expert

**Comment by michaelck** [comment]
@jonathanbardo You may want to check out issue #332. It looks like some folks had success for similar issues by using a Customfile or provision-post.sh

**Comment by jonathanbardo** [comment]
Thanks for point that out!
You should have something that would allow us to do all sorts of things when we vagrant up.

**Comment by jonathanbardo** [comment]
I've implemented a solution that works perfectly for my use case.
A simple `vagrant_up_custom` file containing `xdebug_on` in `config/homebin`.
Any feedback more than welcome!

**Comment by jeremyfelt** [comment]
Added in #782
