### ISSUE TITLE
Intermittent 404 errors on local dev sites

### ISSUE THREAD

**Issue by davedenis** [Varying-Vagrant-Vagrants/VVV#784]
I'm running VVV with Variable VVV. I've looked at #290 and this doesn't seem to be my issue because mine is intermittent. That is, sometimes I try to load http://vvv.dev or http://local.wordpress.dev and get a 404 Nginx error, sometimes I try 2 seconds later and it loads fine. I thought maybe this issue was the most closely related #727 I'm on a Mac, not running MAMP. I am running a VPN when connected to public wifi though, entry from /etc/hosts:

127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
\# BEGIN section for OpenVPN Client SSL sites
127.94.0.1	client.openvpn.net
\# END section for OpenVPN Client SSL sites
192.168.50.4  vvv  # VAGRANT: 072a3b0f5b97cfb4aff7e04fe569db84 (default) / 25251cd7-a343-4231-8f06-3171daeaf42f
192.168.50.4  vvv.dev  # VAGRANT: 072a3b0f5b97cfb4aff7e04fe569db84 (default) / 25251cd7-a343-4231-8f06-3171daeaf42f
192.168.50.4  local.wordpress.dev  # VAGRANT: 072a3b0f5b97cfb4aff7e04fe569db84 (default) / 25251cd7-a343-4231-8f06-3171daeaf42f
192.168.50.4  local.wordpress-trunk.dev  # VAGRANT: 072a3b0f5b97cfb4aff7e04fe569db84 (default) / 25251cd7-a343-4231-8f06-3171daeaf42f
192.168.50.4  src.wordpress-develop.dev  # VAGRANT: 072a3b0f5b97cfb4aff7e04fe569db84 (default) / 25251cd7-a343-4231-8f06-3171daeaf42f
192.168.50.4  build.wordpress-develop.dev  # VAGRANT: 072a3b0f5b97cfb4aff7e04fe569db84 (default) / 25251cd7-a343-4231-8f06-3171daeaf42f
192.168.50.4  vvv  # VAGRANT: 1fb2f502133451fbf5bf19b5fa23e84e (default) / a959e5db-b6a9-4ee6-b208-417ed26eb7f7
192.168.50.4  vvv.dev  # VAGRANT: 1fb2f502133451fbf5bf19b5fa23e84e (default) / a959e5db-b6a9-4ee6-b208-417ed26eb7f7
192.168.50.4  local.wordpress.dev  # VAGRANT: 1fb2f502133451fbf5bf19b5fa23e84e (default) / a959e5db-b6a9-4ee6-b208-417ed26eb7f7
192.168.50.4  local.wordpress-trunk.dev  # VAGRANT: 1fb2f502133451fbf5bf19b5fa23e84e (default) / a959e5db-b6a9-4ee6-b208-417ed26eb7f7
192.168.50.4  src.wordpress-develop.dev  # VAGRANT: 1fb2f502133451fbf5bf19b5fa23e84e (default) / a959e5db-b6a9-4ee6-b208-417ed26eb7f7
192.168.50.4  build.wordpress-develop.dev  # VAGRANT: 1fb2f502133451fbf5bf19b5fa23e84e (default) / a959e5db-b6a9-4ee6-b208-417ed26eb7f7

Any thoughts?

**Comment by alex1a** [comment]
I think this could help you: #375

**Comment by jeremyfelt** [comment]
Hi @davedenis, thanks for opening a ticket. Sorry for the lack of response.

Though this ticket was opened first, I'm going to close it as a duplicate of #810 as we've started tracking some more information there. If you can leave a comment there and verify whether or not the 404s appear in the nginx logs, that would be excellent.
