### ISSUE TITLE
Sometimes vagrant up don't mount www folder

### ISSUE THREAD

**Issue by sielay** [Varying-Vagrant-Vagrants/VVV#786]
I have that every other time. I do `vagrant halt`. Later `vagrant up` link in `/srv/www` seems broken. Then I do `vagrant halt`, `vagrant up` and it works... any ideas?

**Comment by alex1a** [comment]
i think i have the same problem rarely

**Comment by alex1a** [comment]
I think this help you: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/375

**Comment by jeremyfelt** [comment]
Hi @sielay, sorry for the delay. Can you provide more details about your operating system, Vagrant version, and VirtualBox version? Do you see any errors during `vagrant up` that may help troubleshoot the problem?

**Comment by sielay** [comment]
I don't work on the same machine, nor company anymore. On my private had no problems so far. So I think we can close it.
