### ISSUE TITLE
Help for newbie or what I learned

### ISSUE THREAD

**Issue by frannetcny** [Varying-Vagrant-Vagrants/VVV#789]
Thank you for your wonderful project.  I was able to get up and running in a few hours.  I'd like to provide some practical help for the newbie (for others like myself) in the instructions. Note I'm using a windows machine so some of the instructions didn't make sense at first. I also didn't search the issues or archives I just plunged headlong to my own demise.  They make sense now but it took some time to figure it out.  I'm sure these are obvious to most of you and to me now. By the way I'm willing to help edit the instructions to make them more useful.    Here is where I failed:
- I didn't realize that you don't really do anything with virtualbox except load it.  Vagrant takes care of everything for you.Possibly I will need to tweak something sometime but not in the initial startup.  ( a note next to the virtual box instructions saying "just load this but you will not need to run or use it (until later or never)." 
- Also some suggested setting for virtualbox.  I think I setup a 10GB fixed section on my HD and 1 GB of Ram.  I'm a little unsure why I did this at this point.  Possibly I needed to do this in the install of virtualbox possibly it was because of my running it separately without vagrant.  If there are suggested settings it would be nice to know them.  
- I'd like to know of any conditions when I might want to edit or control from virtualbox or possibly I never need to use that.
- In step 3 I kind of jumped over  the first bullet "vagrant will now be available as a command in your terminal, try it out".  I kept trying to run vagrant from the start menu and virtualbox.  I thought the instructions meant the virtualbox terminal or a putty terminal.  It wasn't clear to me that for the PC that terminal window meant cmd prompt (cmd.exe) Possibly adding "On a PC open a cmd prompt window" then the next bullet  type vagrant -v may make more sense.
- When I finally figured it out and I started with cmd.exe and it went to my C:\Users\default>.  this made things very messy in that directory.  I later changed to a new directory c:\vagrant to which I added c:\vagrant\vvv-develop.  This made things neater and nicer.  Just a suggestion. Possibly Instructions such as "On a windows machine create a new directory on my PC suggestion c:\vagrant change to that directory prior to running any vagrant commands then create subdirectory vvv-develop, download the Github repository into the subdirectory vvv-develop"
- I jumped ahead in the instructions and once in my c:\users\default directory ran vagrant up without the repository This made a mess of my default directory and created a virtualbox "default"  it wasn't pretty. I went round and round trying to figure out where the development was.  
- I'd like some instructions for shutting down my PC.  Do I need to run vagrant halt or just shutdown the PC and startup the next day? What will happen. I was always taught to turn the lights off before you leave a room.  Possibly I don't need to do that if I want to run it when I boot up the next day.  I haven't tried this yet still doing a vagrant halt before shutting down my PC. 
- Lastly i needed to make some changes to the PHP.ini file and wp-config.php.  Some help in finding the correct file to edit so that these settings get changed.  Also it took me a while to find "vagrant reload" to get these settings to update.  Some specific instructions would be helpful.   I'm still trying to figure out where to change the php.ini setting max_execution_time = 60. and max_input_vars = 3000;  It does not seem to be updating when I change them in php-custom.ini.  I need it for my avada theme.  The theme tells me to put some settings into .htaccess file.  

A separate topic might be needed for this but how to copy a site (from say a host) into this environment and get it up and running.  Possibly instructions exist and I have not found them yet.  I'm again willing to write those instructions when I figure out how to do it.  

Ultimate thanks for creating this project it is really great and I am seeing incredible speed advantages.

**Comment by thurrockdan** [comment]
There should be no need to do anything in virtualbox as the vagrantfile does everything, if you change anything outside of the vagrant file it will defeat the point of the system and that its to allow you and others to build a completely identical system from scratch, if you was working with other developers you would have your vagrant file in version control and any adjustments to the virtualbox environment would be using the vagrant file, running shell commands directly or with you creating additional build files to run on vagrant up.

I managed to corrupt a virtual box by just shutting down the computer, I now vagrant halt and switch the lights off before I leave.

you can override most php.ini directives in your functions.php of you template or plugin using ini_set(); or create a local php.ini in your project root that will override the global php.ini, editing the virtualboxes php ini is something that I would not do as when you rebuild your environment these could/will be overwritten.  if additional php extensions are required or need enabling then create a shell file as mentioned above to do it on vagrant up.

**Comment by jeremyfelt** [comment]
Thanks for the great feedback @frannetcny! We'd love to continue improving the docs and this will help.

**Comment by tomjn** [comment]
Marking this as closed as the installation instructions have been rewritten since then
