### ISSUE TITLE
wp_mail() not being caught by mailcatcher

### ISSUE THREAD

**Issue by magbicaleman** [Varying-Vagrant-Vagrants/VVV#791]
MailCatcher was not working form me when Wordpress was sending out emails. I followed by installing a Wordpress called MailCatcher, which also didn't work, after trying several different configurations I gave up on it. Admittedly I never tried to set the MailCatcher plugin to port 25 :/. The default configuration is as follows;

```php
$defaults = array(
			"from"	   => "local@local.dev",
			"fromname" => "local",
			"host"     => "127.0.0.1",
			"port"     => "1025",
			"smtpauth" => false
		);
```

Then installed `Check Email` plugin to test, and see if even my dev environment was indeed sending out emails. It's worth mentioning that a mailing plugin was deactivated; in this case that was MailGun's plugin. `Check Email` plugin does display current mail settings:

```
SendMail path (UNIX): /usr/local/rvm/bin/catchmail -f admin@local.dev
SMTP server (Windows): localhost
SMTP port (Windows): 25
Add X header: 1
```

After deactivating MailGun's plugin, and trying just MailCatcher plugin, it was still failing and this is when I deactivated. After visiting the following issue: https://github.com/sj26/mailcatcher/issues/103. I just went ssh-ed into vagrant, modified the MailCatcher.ini by just adding the port.

__path__: `/etc/php5/mods-available/mailcatcher.ini`
```
sendmail_path = "/usr/local/rvm/bin/catchmail --smtp-port 25 -f admin@local.dev"
```

```
sudo service nginx reload
```

Wordpress emails are now being caught. Hopefully this helps anyone else. If you know of a better way, I'm all ears. 

![Image of Ears](https://media4.giphy.com/media/3o85xsGXVuYh8lM3EQ/200.gif)

**Comment by jeremyfelt** [comment]
Hi @magbicaleman, thanks for the info. I haven't had a problem recently with the Mailcatcher config, but this may help others that run into trouble. Thanks!

**Comment by davetgreen** [comment]
@magbicaleman you sir are a LEGEND! This is really helping me debug email functionality in my plugin. 🥇
