### ISSUE TITLE
http://vvv.dev/ error 404

### ISSUE THREAD

**Issue by polykrom** [Varying-Vagrant-Vagrants/VVV#792]
Hi,

After reporting an issue about phpmyadmin link from http://vvv.dev/ that doesn't work, i've restarted Vagrant in order to check if it wasn't a solution...
Now wen i go to http://vvv.dev/ i get a 404 error page :-/

Doesn't know why

Any help ?

**Comment by polykrom** [comment]
Here is what i get when restarting vagrant : 

iMacdeFrancois:VVV polykrom$ sudo vagrant reload
Password:
==> default: Removing hosts
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.34
    default: VirtualBox Version: 5.0
==> default: Checking for host entries
==> default: adding to (/etc/hosts) : 192.168.50.4  vvv  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: adding to (/etc/hosts) : 192.168.50.4  blaamy.dev  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: adding to (/etc/hosts) : 192.168.50.4  vvv.dev  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: adding to (/etc/hosts) : 192.168.50.4  local.wordpress.dev  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: adding to (/etc/hosts) : 192.168.50.4  local.wordpress-trunk.dev  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: adding to (/etc/hosts) : 192.168.50.4  src.wordpress-develop.dev  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: adding to (/etc/hosts) : 192.168.50.4  build.wordpress-develop.dev  # VAGRANT: 63a2b1c89073c420b7107240fe5fe76a (default) / ba133698-fb21-4385-b102-6d859241dca9
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/polykrom/Documents/VVV
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

**Comment by polykrom** [comment]
Mmhh... reinstall Vagrant and VirtualBox and it works now for http://vvv.dev/ but the phpMyAdmin link still not work, the db isn't in the default www folder and http://local.wordpress.dev is the only wp installation that works ...

**Comment by polykrom** [comment]
Ok, Find the solution to this issue...
In my first install of vvv i used the zip released of VVV , i've just installed the git version and it works simply nice with it !

Wooow ... 

:)

**Comment by jeremyfelt** [comment]
Sorry for the troubles and for the late response @polykrom. Glad you sorted it out.

I see @cfoellmann has created an issue to make sure we have the zip version properly updated. I'm guessing the `master` branch no longer provisions properly either. We should ship a new version sooner than later. :smile:
