### ISSUE TITLE
Check .zip release version

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#793]
SEE: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/792#issuecomment-161358758
SEE: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/772#issuecomment-161361203

The stable.zip might be broken!?

**Comment by luisnjuarez** [comment]
Hi guys, I found the same issue, I have destroyed the vm and started it over, however, I still can't access phpmyadmin. Has the new zip file been published? is there any workaround in the meantime?

**Comment by jeremyfelt** [comment]
I think we're good now that 1.3.0 has been released.
