### ISSUE TITLE
Which WordPress version is local development version?

### ISSUE THREAD

**Issue by tyidnet** [Varying-Vagrant-Vagrants/VVV#794]
I got Vagrant box running successfully, and I can see Default, Trunk, SRC and Build versions in my vagrant-local. If I want to add themes and plugin, or create customized themes, which version should I work with?

Thanks!

Tony

**Comment by cfoellmann** [comment]
If you only want to create/test your theme you should use `trunk` so you can see if you code runs smoothly on the latest and greatest.
