### ISSUE TITLE
Added memory and CPU increase to Customfile

### ISSUE THREAD

**Issue by colin-marshall** [Varying-Vagrant-Vagrants/VVV#795]
Hi, I tried changing the memory and CPU parameters for my VVV VirtualBox by using the snippet in my Customfile from: https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Customising-your-Vagrant's-attributes-and-parameters

I tried both of the snippets and can't get the memory or CPU's to increase. They stay at the default 1gb, 1 core. I ran `vagrant provision` a few times and it didn't do anything. Do I have to do a `vagrant destroy` in order for the memory and CPU changes to take effect? Thanks!

**Comment by cfoellmann** [comment]
did you run `vagrant reload`?
SEE: https://docs.vagrantup.com/v2/cli/reload.html

**Comment by colin-marshall** [comment]
Not sure how I missed that! Thank you!!!
