### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by dashkevych** [Varying-Vagrant-Vagrants/VVV#796]
Hi guys,

I am wondering if anyone knows how to fix this issue:

> Parse error: syntax error, unexpected '<<' (T_SL) in /srv/www/wordpress-develop/src/wp-> includes/version.php on line 7

I got it after *vagrant up --provision* command.

Regards,
Taras

**Comment by topdown** [comment]
Those characters should not be in the version.php file
Did you have changes to that WordPress install?
I'm guessing its diff/merge characters.
You could just try redoing `vagrant provision`
