### ISSUE TITLE
Vagrant up slow

### ISSUE THREAD

**Issue by kutakizukari** [Varying-Vagrant-Vagrants/VVV#798]
Just started using VVV and every time I vagrant up it takes 18 to 25 minutes to finish. Is that normal?

**Comment by kutakizukari** [comment]
Using Lubuntu 14.04.3 LTS

**Comment by cfoellmann** [comment]
For the first up which runs the complete provision this time sounds ok.
After that everything should only take a few seconds.

**Comment by unfulvio** [comment]
I'm on Ubuntu 15.10... 

first vagrant up with provisioning takes between 45 minutes and 2 hours -- this only happens with VVV not with other vagrant boxes - I would really know why but haven't figured out the issue; tried tweaks in vagrantfile, tried changing adapter in virtualbox... it's surely a network issue, it takes long time to download package and provision the machine - but haven't figured out what

normal vagrant up after provision takes few minutes and the machine is fast to run a site
