### ISSUE TITLE
Hosts name and folder connection

### ISSUE THREAD

**Issue by tyidnet** [Varying-Vagrant-Vagrants/VVV#799]
Which file has settings of "local.wordpress.dev" point to "wordpress-default" folder? If I want to create a customized local dev host name, for example, local.projectname.com, and point it to "wordpress-default" folder, how do I do that?

Thanks!

**Comment by jeremyfelt** [comment]
Hi @tyidnet, thanks for stopping by. Sorry for not answering sooner. :)

You can see the config for default sites in the [default.conf](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/sites/default.conf) file.

See the [Add New Domain](https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Add-New-Domain) instructions in the wiki for adding your own domain.

You may also find the [VV project](https://github.com/bradp/vv) interesting as it removes some of the steps.
