### ISSUE TITLE
Update the Virtualbox guest addition

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#800]
http://kvz.io/blog/2013/01/16/vagrant-tip-keep-virtualbox-guest-additions-in-sync/

I've followed that guide to update the VB guest addition but is a simple plugin for vagrant that check on update on `vagrant up`.
Maybe is possible integrate in vvv?

**Comment by fxbenard** [comment]
+1

**Comment by cfoellmann** [comment]
Isn't this something we can only add to the readme as a recommendation?
The vagrant plugins are local and independent from Vvv or any other vagrant configuration

**Comment by fxbenard** [comment]
@cfoellmann You're right, let's keep plugins apart from vvv. The recommendation will be a good move.

**Comment by jeremyfelt** [comment]
Yeah, I think a README addition could work. I've never needed to update VB guest additions myself, but I have heard from others that they help.

Does this conflict at all with the updating of the ubuntu/trusty64 box through `vagrant box update`?

**Comment by Mte90** [comment]
Not create conflict i am using that solution from months without problem.

**Comment by 16nsk** [comment]
I agree with @cfoellmann . I've been using that vagrant plugin for a few years and didn't have any problems.

It should be just a __recommendation__ in the VVV Readme.

**Comment by meitar** [comment]
I was just hit by this issue today and found the recommended `vagrant-vbguest` plugin helpful, so I added it to VVV's recommended list of plugins in the README.

Also, sorry for the commit-spam, I had a brain fart and forgot to `git add` before I `--amend`ed.

**Comment by jeremyfelt** [comment]
Documentation was added via #875.
