### ISSUE TITLE
Add ssh php module

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#801]
For fix a ticket in WordPress core I had the support for that.
So I've followed that guide to install the module http://www.asim.pk/2010/05/27/installing-phps-ssh2-extension-on-ubuntu/.
Maybe add that package in the provision simplify for others that problem.

**Comment by jeremyfelt** [comment]
Hi @Mte90, thanks for the ticket.

Can you provide more detail as to what the `libssh2-1-dev` and `libssh2-php` would offer for us?

It may also make sense to use one of the custom provisioning scripts to add this to your specific configuration.

**Comment by Mte90** [comment]
In the the credentials form to update wordpress there is the support for sftp but without that libraries wordpress not reconize that support and that form is incomplete.
https://core.trac.wordpress.org/ticket/34376

**Comment by jeremyfelt** [comment]
Ok, that makes sense. I'd be open to adding support for this to help with core testing.

**Comment by cfoellmann** [comment]
@Mte90 can you send us a PR for this? Please include an addtion to the contributors list (if you are not already on it) and an addtion to the changelog

**Comment by Mte90** [comment]
Done :-)

**Comment by jeremyfelt** [comment]
This was added and then it was unadded when we installed PHP7. The current ticket tracking this is #923.
