### ISSUE TITLE
VVV.DEV 404

### ISSUE THREAD

**Issue by rsordillo** [Varying-Vagrant-Vagrants/VVV#807]
New to this so a steep learning curve but.. looking through install log this came back does anyone have any ideas? Thanks

==> default: Initializing grunt in WordPress develop... This may take a few moments.
==> default: >> Local Npm module "grunt-browserify" not found. Is it installed?
==> default: Loading "sass.js" tasks...
==> default: ERROR
==> default: >> Error: The `libsass` binding was not found in /srv/www/wordpress-develop/node_modules/node-sass/vendor/linux-x64-11/binding.node
==> default: >> This usually happens because your node version has changed.
==> default: >> Run `npm rebuild node-sass` to build the binding for your current node version.
==> default: Running "clean:all" (clean) task
==> default: >> 0 paths cleaned.
==> default: Running "copy:files" (copy) task
==> default: Created 142 directories
==> default: , copied 1230 files
==> default: Running "copy:wp-admin-rtl" (copy) task
==> default: Copied 1 file
==> default: Running "copy:version" (copy) task
==> default: Copied 1 file
==> default: Running "cssmin:core" (cssmin) task
==> default: >> 21 files created. 322.69 kB ��� 531.23 kB
==> default: Warning: Task "sass:colors" not found. Use --force to continue.
==> default: Aborted due to warnings.
==> default:

**Comment by rsordillo** [comment]
==> default: No custom MySQL scripting found in database/init-custom.sql, skippi                                               ng...
==> default: Initial MySQL prep...
==> default: Start MySQL Database Import
==> default: No custom databases to import
==> default: Network connection detected...
==> default:
==> default: Installing/updating wp-cli and debugging tools
==> default: Updating wp-cli...
==> default: Cannot pull with rebase: You have unstaged changes.
==> default: Please commit or stash them.
==> default: Loading composer repositories with package information

**Comment by rsordillo** [comment]
==> default: Setting up pkg-php-tools (1.11) ...
==> default: Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
==> default: Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.30.7-0ubuntu1.2) ...
==> default: Processing triggers for ufw (0.34~rc-0ubuntu2) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Processing triggers for php5-fpm (5.5.9+dfsg-1ubuntu4.14) ...
==> default: php5-fpm stop/waiting
==> default: php5-fpm start/running, process 17080
==> default: /usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
==> default: npm@3.5.2 /usr/lib/node_modules/npm
==> default: WARN
==> default:
==> default: engine
==> default:  npm-check-updates@2.5.6: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"                                    3.5.2"})
==> default: WARN
==> default:
==> default: engine
==> default:  npm-check-updates@2.5.6: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"                                    3.5.2"})
==> default: WARN
==> default:
==> default: engine
==> default:  get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"3.5.2"                                    })

**Comment by iandunn** [comment]
None of those errors seem relevant, maybe it's related to https://github.com/cogitatio/vagrant-hostsupdater/issues/92 ?

What's the content of your `/etc/hosts` file?

**Comment by rsordillo** [comment]
I think I have honed in on the errors, after provisioning with bradp vv after some time the database seems to bring up a host of Javascript PMA errors - however I am not sure how to proceed here. I am still a beginner so troubleshooting seems a very long winded process

**Comment by rsordillo** [comment]
Something to do with 'phpmyadmin.pma__tracking'

**Comment by jeremyfelt** [comment]
@rsordillo are you still getting the 404 errors for vvv.dev? Are other URLs doing the same thing?

**Comment by raulillana** [comment]
@jeremyfelt i'm having this issue too after last update.

Clean provisioning. It works, but after some navigation it starts throwing 404 in all sites. After some time, the reloads work and load the websites. Navigation leads you again to 404s.

It stopped working after i did destroy my first box, and installed it again in a new location. I've installed VV after that, so i guess it's not related. Also tried `provisioning` and `up --provisioning`. Clean responses. All seems legit.

$ vagrant HALP? :_)

**Comment by jeremyfelt** [comment]
Hi @raulillana, can you check out issue #810 and leave a comment there. I'd especially be interested as to whether these 404 requests are appearing in the VM's nginx access or error logs. I have a feeling this might all be related to the `.dev` suffix.

I'm going to close this issue (807) out as 810 is more focused.
