### ISSUE TITLE
vagrant up (hostsupdater) fails with permission denied on /etc/hosts

### ISSUE THREAD

**Issue by shankiesan** [Varying-Vagrant-Vagrants/VVV#812]
Obviously this isn't a universal problem, but on my machine, running `vagrant up` (as part of the 'getting started' instructions in the readme) fails with the following message:

`/Users/shankie/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.1/lib/vagrant-hostsupdater/HostsUpdater.rb:85:in 'initialize': Permission denied @ rb_sysopen - /etc/hosts (Errno::EACCES)`

I've managed to work around it for now by:

`sudo chmod o+w /etc/hosts`

... but this seems like a Bad Idea!

Any thoughts anyone?

**Comment by shankiesan** [comment]
I've worked around this in the meantime by adding myself to the wheel group and then making `/etc/hosts` group-writable.

Not ideal but works for now!

**Comment by standoutsites** [comment]
I'm having the same problem. Are there more people having this problem? So the suggested workaround is the only fix for now?

**Comment by jb510** [comment]
same issue. see: https://github.com/cogitatio/vagrant-hostsupdater/issues/92

**Comment by jeremyfelt** [comment]
Thanks for raising the issue. I think we're going to want to move forward with supporting more than one hosts updating plugin. I'm going to close this out, but follow #606 and #815
