### ISSUE TITLE
All sites give 404 or 403 errors

### ISSUE THREAD

**Issue by adamf321** [Varying-Vagrant-Vagrants/VVV#814]
Hi there,

I set-up VVV and it was working fine, until I installed the VV (https://github.com/bradp/vv) plugin to automatically configure new WP installs.

After that the server wouldn't start-up (I got SSH timeout errors). I updated the Vagrant config file so it opens the terminal at start-up and I saw it was now asking for a login - so I entered vagrant / vagrant and it booted.

However, the web server is still not working - when I go to http://local.wordpress.dev/ I get a 404 error. The site I added with VV gives 403.

Any ideas how to debug this?

**Comment by jeremyfelt** [comment]
Hi @adamf321, thanks for the ticket.

This may be a question to raise as a VV issue as it sounds like things were working fine before VV was used. It's possible there is a conflicting configuration from a site added through VV.

I would try running `vagrant provision` again to see if the default configs can be reset. You may also want to manually remove any non-core VVV configs.
