### ISSUE TITLE
vagrant halt Could not locate Gemfile 

### ISSUE THREAD

**Issue by altrovideo** [Varying-Vagrant-Vagrants/VVV#816]
Hi , I'm using Debian https://wiki.debian.org/DebianStretch with Vagrant 1.7.4 for wordpress vvv
and I have this error:
```
root@debian:~/vagrant-local# vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
==> default: /usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
```
I've solved with
```
vagrant ssh
sudo su
shutdown -h now
```

**Comment by jeremyfelt** [comment]
Hi @altrovideo, thanks for opening a ticket.

VVV uses the ubuntu/trusty64 box, so it's possible there are several types of errors or misconfigurations that would occur when switching linux versions.

It is good to note for others who may have the same issue.
