### ISSUE TITLE
Vagrant up fails on Mac OSX Yosemite (10.10.5)

### ISSUE THREAD

**Issue by praisegeek** [Varying-Vagrant-Vagrants/VVV#817]
## Vagrant up fails to pass provisioning stage. I'm using 
- Virtual Box 4.3.3
- Vagrant 1.7.3

### Log output

Praisegeeks-MBP:vagrant-local praisegeek$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Removing hosts
==> default: No machine id, nothing removed from /etc/hosts
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vagrant-local
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Checking for host entries
==> default: adding to (/etc/hosts) : 192.168.50.4  vvv  # VAGRANT: b305f7432f7760bce774115e55d59b0b (default) / 05fe2978-ca83-4e41-8875-e6e181e113ef
==> default: adding to (/etc/hosts) : 192.168.50.4  vvv.dev  # VAGRANT: b305f7432f7760bce774115e55d59b0b (default) / 05fe2978-ca83-4e41-8875-e6e181e113ef
==> default: adding to (/etc/hosts) : 192.168.50.4  local.wordpress.dev  # VAGRANT: b305f7432f7760bce774115e55d59b0b (default) / 05fe2978-ca83-4e41-8875-e6e181e113ef
==> default: adding to (/etc/hosts) : 192.168.50.4  local.wordpress-trunk.dev  # VAGRANT: b305f7432f7760bce774115e55d59b0b (default) / 05fe2978-ca83-4e41-8875-e6e181e113ef
==> default: adding to (/etc/hosts) : 192.168.50.4  src.wordpress-develop.dev  # VAGRANT: b305f7432f7760bce774115e55d59b0b (default) / 05fe2978-ca83-4e41-8875-e6e181e113ef
==> default: adding to (/etc/hosts) : 192.168.50.4  build.wordpress-develop.dev  # VAGRANT: b305f7432f7760bce774115e55d59b0b (default) / 05fe2978-ca83-4e41-8875-e6e181e113ef
Password:
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/praisegeek/vagrant-local
    default: /srv/www => /Users/praisegeek/vagrant-local/www
    default: /srv/log => /Users/praisegeek/vagrant-local/log
    default: /srv/config => /Users/praisegeek/vagrant-local/config
    default: /srv/database => /Users/praisegeek/vagrant-local/database
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: /var/folders/cr/msynsd1d3jj9f58x6x24kxw40000gn/T/vagrant-shell20160124-1754-1szs3cm.sh
==> default: Network connection detected...
==> default: Bash profile setup and directories.
==> default: sending incremental file list
==> default: db_backup
==> default: develop_git
==> default: makepot
==> default: vagrant_destroy
==> default: vagrant_halt
==> default: vagrant_suspend
==> default: xdebug_off
==> default: xdebug_on
==> default: sent 2.22K bytes  received 168 bytes  4.78K bytes/sec
==> default: total size is 3.00K  speedup is 1.25
==> default:  * Copied /srv/config/bash_profile                      to /home/vagrant/.bash_profile
==> default:  * Copied /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
==> default:  * Copied /srv/config/vimrc                             to /home/vagrant/.vimrc
==> default:  * Copied /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
==> default:  * rsync'd /srv/config/homebin                          to /home/vagrant/bin
==> default: Network connection detected...
==> default:  
==> default: Main packages check and install.
==> default:  * php5-fpm [not installed]
==> default:  * php5-cli [not installed]
==> default:  * php5-common [not installed]
==> default:  * php5-dev [not installed]
==> default:  * php5-memcache [not installed]
==> default:  * php5-imagick [not installed]
==> default:  * php5-mcrypt [not installed]
==> default:  * php5-mysql [not installed]
==> default:  * php5-imap [not installed]
==> default:  * php5-curl [not installed]
==> default:  * php-pear [not installed]
==> default:  * php5-gd [not installed]
==> default:  * nginx [not installed]
==> default:  * memcached [not installed]
==> default:  * mysql-server [not installed]
==> default:  * imagemagick [not installed]
==> default:  * subversion [not installed]
==> default:  * git-core [not installed]
==> default:  * zip [not installed]
==> default:  * unzip [not installed]
==> default:  * ngrep [not installed]
==> default:  * curl                                                7.35.0-1ubuntu2.5
==> default:  * make                                                3.81-8.2ubuntu3
==> default:  * vim                                                 2:7.4.052-1ubuntu3
==> default:  * colordiff [not installed]
==> default:  * postfix [not installed]
==> default:  * ntp [not installed]
==> default:  * gettext [not installed]
==> default:  * graphviz [not installed]
==> default:  * dos2unix [not installed]
==> default:  * g++ [not installed]
==> default:  * nodejs [not installed]
==> default:  * libsqlite3-dev [not installed]
==> default: /tmp/vagrant-shell: line 196: /etc/postfix/main.cf: No such file or directory
==> default: Linked custom apt sources
==> default: Applying Nginx signing key...
==> default: OK
==> default: gpg: requesting key C7917B12 from hkp server keyserver.ubuntu.com
==> default: gpg: no valid OpenPGP data found.
==> default: gpg: 
==> default: WARNING: nothing exported
==> default: gpg: 
==> default: no valid OpenPGP data found.
==> default: Running apt-get update...
==> default: Ign http://ppa.launchpad.net trusty InRelease
==> default: Ign http://nginx.org trusty InRelease
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Get:1 http://ppa.launchpad.net trusty Release.gpg [316 B]
==> default: Get:2 http://nginx.org trusty Release.gpg [287 B]
==> default: Get:3 http://ppa.launchpad.net trusty Release [15.1 kB]
==> default: Ign http://ppa.launchpad.net trusty Release
==> default: Get:4 http://nginx.org trusty Release [3,047 B]
==> default: Get:5 http://ppa.launchpad.net trusty/main Sources [829 B]
==> default: Get:6 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
==> default: Get:7 http://nginx.org trusty/nginx Sources [3,366 B]
==> default: Get:8 http://ppa.launchpad.net trusty/main amd64 Packages [756 B]
==> default: Get:9 http://nginx.org trusty/nginx amd64 Packages [4,460 B]
==> default: Get:10 http://ppa.launchpad.net trusty/main Translation-en [604 B]
==> default: Get:11 http://archive.ubuntu.com trusty-backports InRelease [64.5 kB]
==> default: Ign http://ppa.launchpad.net trusty/main Translation-en_US
==> default: Get:12 http://archive.ubuntu.com trusty Release.gpg [933 B]
==> default: Get:13 http://archive.ubuntu.com trusty-updates/main Sources [248 kB]
==> default: Get:14 http://archive.ubuntu.com trusty-updates/restricted Sources [5,359 B]
==> default: Get:15 http://archive.ubuntu.com trusty-updates/universe Sources [147 kB]
==> default: Get:16 http://archive.ubuntu.com trusty-updates/multiverse Sources [5,161 B]
==> default: Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
==> default: Get:17 http://archive.ubuntu.com trusty-backports/main Sources [8,221 B]
==> default: Get:18 http://archive.ubuntu.com trusty-backports/restricted Sources [28 B]
==> default: Get:19 http://archive.ubuntu.com trusty-backports/universe Sources [33.2 kB]
==> default: Get:20 http://archive.ubuntu.com trusty-backports/multiverse Sources [1,898 B]
==> default: Get:21 http://archive.ubuntu.com trusty-backports/main amd64 Packages [9,402 B]
==> default: Get:22 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [28 B]
==> default: Get:23 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [39.8 kB]
==> default: Get:24 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1,571 B]
==> default: Get:25 http://archive.ubuntu.com trusty-backports/main Translation-en [5,549 B]
==> default: Get:26 http://archive.ubuntu.com trusty-backports/multiverse Translation-en [1,215 B]
==> default: Get:27 http://archive.ubuntu.com trusty-backports/restricted Translation-en [14 B]
==> default: Get:28 http://archive.ubuntu.com trusty-backports/universe Translation-en [34.6 kB]
==> default: Ign http://security.ubuntu.com trusty-security InRelease
==> default: Get:29 http://security.ubuntu.com trusty-security Release.gpg [933 B]
==> default: Get:30 http://security.ubuntu.com trusty-security Release [63.5 kB]
==> default: Get:31 http://security.ubuntu.com trusty-security/main Sources [103 kB]
==> default: Get:32 http://security.ubuntu.com trusty-security/universe Sources [32.7 kB]
==> default: Get:33 http://security.ubuntu.com trusty-security/main amd64 Packages [410 kB]
==> default: Get:34 http://security.ubuntu.com trusty-security/universe amd64 Packages [123 kB]
==> default: Get:35 http://security.ubuntu.com trusty-security/main Translation-en [221 kB]
==> default: Ign http://nginx.org trusty/nginx Translation-en_US
==> default: Ign http://nginx.org trusty/nginx Translation-en
==> default: Get:36 http://security.ubuntu.com trusty-security/universe Translation-en [71.9 kB]
==> default: Get:37 http://archive.ubuntu.com trusty Release [58.5 kB]
==> default: Get:38 http://archive.ubuntu.com trusty/main Sources [14 B]
==> default: Get:39 http://archive.ubuntu.com trusty/restricted Sources [5,433 B]
==> default: Get:40 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
==> default: Get:41 http://archive.ubuntu.com trusty/multiverse Sources [174 kB]
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com trusty/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
==> default: Err http://archive.ubuntu.com trusty/restricted Translation-en_US
==> default:   Connection failed [IP: 91.189.91.14 80]
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 8,362 kB in 4min 11s (33.3 kB/s)
==> default: W
==> default: : 
==> default: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B9316A7BC7917B12
==> default: W
==> default: : 
==> default: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch
==> default: W
==> default: : 
==> default: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch
==> default: W
==> default: : 
==> default: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/source/Sources  Hash Sum mismatch
==> default: W
==> default: : 
==> default: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/binary-amd64/Packages  Hash Sum mismatch
==> default: W
==> default: : 
==> default: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/universe/binary-amd64/Packages  Hash Sum mismatch
==> default: 
==> default: W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/i18n/Translation-en  Hash Sum mismatch
==> default: 
==> default: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/source/Sources  Hash Sum mismatch
==> default: 
==> default: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/restricted/i18n/Translation-en_US  Connection failed [IP: 91.189.91.14 80]
==> default: 
==> default: E: Some index files failed to download. They have been ignored, or old ones used instead.
==> default: Installing apt-get packages...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Some packages could not be installed. This may mean that you have
==> default: requested an impossible situation or if you are using the unstable
==> default: distribution that some required packages have not yet been created
==> default: or been moved out of Incoming.
==> default: The following information may help to resolve the situation:
==> default: The following packages have unmet dependencies:
==> default:  g++ : Depends: g++-4.8 (>= 4.8.2-5~) but it is not going to be installed
==> default:  libsqlite3-dev : Depends: libsqlite3-0 (= 3.8.2-1ubuntu2) but 3.8.2-1ubuntu2.1 is to be installed
==> default:  php5-dev : Depends: libssl-dev but it is not going to be installed
==> default:  php5-fpm : Depends: php5-common (= 5.5.9+dfsg-1ubuntu4.14) but 5.5.9+dfsg-1ubuntu4 is to be installed
==> default: E
==> default: : 
==> default: Unable to correct problems, you have held broken packages.
==> default: /tmp/vagrant-shell: line 234: npm: command not found
==> default: /tmp/vagrant-shell: line 235: npm: command not found
==> default: /tmp/vagrant-shell: line 242: pecl: command not found
==> default: Installing ack-grep as ack
==> default: /tmp/vagrant-shell: line 258: composer: command not found
==> default: Installing Composer...
==> default: /tmp/vagrant-shell: line 260: php: command not found
==> default: c
==> default: u
==> default: r
==> default: l
==> default: :
==> default:  
==> default: (
==> default: 2
==> default: 3
==> default: )
==> default:  
==> default: F
==> default: ailed writing body (0 != 16133)
==> default: chmod: 
==> default: cannot access ‘composer.phar’
==> default: : No such file or directory
==> default: mv: 
==> default: cannot stat ‘composer.phar’
==> default: : No such file or directory
==> default: /tmp/vagrant-shell: line 273: composer: command not found
==> default: /tmp/vagrant-shell: line 288: grunt: command not found
==> default: Installing Grunt CLI
==> default: Adding graphviz symlink for Webgrind...
==> default: Generate Nginx server private key...
==> default: /etc/nginx/server.key: No such file or directory
==> default: 140386699302560:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/nginx/server.key','w')
==> default: 140386699302560:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
==> default: Sign the certificate using the above private key...
==> default: Error opening Private Key /etc/nginx/server.key
==> default: 140678909068960:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/nginx/server.key','r')
==> default: 140678909068960:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
==> default: unable to load Private Key
==> default: Setup configuration files...
==> default:  * Copied /srv/config/init/vvv-start.conf               to /etc/init/vvv-start.conf
==> default: cp: 
==> default: cannot create regular file ‘/etc/nginx/nginx.conf’
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file ‘/etc/nginx/nginx-wp-common.conf’
==> default: : No such file or directory
==> default: mkdir: 
==> default: cannot create directory ‘/etc/nginx/custom-sites/’
==> default: : No such file or directory
==> default: sending incremental file list
==> default: rsync: mkdir "/etc/nginx/custom-sites" failed: No such file or directory (2)
==> default: rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]
==> default:  * Copied /srv/config/nginx-config/nginx.conf           to /etc/nginx/nginx.conf
==> default:  * Copied /srv/config/nginx-config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf
==> default:  * Rsync'd /srv/config/nginx-config/sites/              to /etc/nginx/custom-sites
==> default: gpg: 
==> default: new configuration file `/root/.gnupg/gpg.conf' created
==> default: gpg: 
==> default: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
==> default: gpg: 
==> default: requesting key D39DC0E3 from hkp server keyserver.ubuntu.com
==> default: gpg: 
==> default: requesting key BF04FF17 from hkp server keyserver.ubuntu.com
==> default:  * RVM [not installed]
==> default:  Installing from source
==> default: Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
==> default: Downloading https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
==> default: gpg: 
==> default: Signature made Mon 30 Mar 2015 09:52:13 PM UTC using RSA key ID BF04FF17
==> default: gpg: 
==> default: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
==> default: gpg: 
==> default: WARNING: This key is not certified with a trusted signature!
==> default: gpg: 
==> default:          There is no indication that the signature belongs to the owner.
==> default: Primary key fingerprint:
==> default:  409B
==> default:  6B17
==> default:  96C2
==> default:  7546
==> default:  2A17
==> default:  
==> default:  0311
==> default:  3804
==> default:  BB82
==> default:  D39D
==> default:  C0E3
==> default:      Subkey fingerprint:
==> default:  62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
==> default: GPG verified '/usr/local/rvm/archives/rvm-1.26.11.tgz'
==> default: Creating group 'rvm'
==> default: Installing RVM to /usr/local/rvm/
==> default: Installation of RVM in /usr/local/rvm/ is almost complete:
==> default:   * First you need to add all users that will be using rvm to 'rvm' group,
==> default:     and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.
==> default:   * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
==> default:     in all your open shell windows, in rare cases you need to reopen all shell windows.
==> default: # Administrator,
==> default: #
==> default: #   Thank you for using RVM!
==> default: #   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
==> default: #
==> default: # ~Wayne, Michal & team.
==> default: In case of problems: http://rvm.io/help and https://twitter.com/rvm_io
==> default: rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
==> default: Searching for binary rubies, this might take some time.
==> default: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/ruby-2.2.1.tar.bz2
==> default: Checking requirements for ubuntu.
==> default: Installing requirements for ubuntu.
==> default: Updating system
==> default: ............
==> default: Error running 'requirements_debian_update_system ruby-2.2.1',
==> default: showing last 15 lines of /usr/local/rvm/log/1453624966_ruby-2.2.1/update_system.log
==> default: ++ /scripts/functions/logging : rvm_pretty_print()  78 > case "${TERM:-dumb}" in
==> default: ++ /scripts/functions/logging : rvm_pretty_print()  81 > case "$1" in
==> default: ++ /scripts/functions/logging : rvm_pretty_print()  83 > [[ -t 2 ]]
==> default: ++ /scripts/functions/logging : rvm_pretty_print()  83 > return 1
==> default: ++ /scripts/functions/logging : rvm_error()  117 > printf %b 'There has been error while updating '\''apt-get'\'', please give it some time and try again later.
==> default: 404 errors should be fixed for rvm to proceed. Check your sources configured in:
==> default:     /etc/apt/sources.list
==> default:     /etc/apt/sources.list.d/*.list
==> default: \n'
==> default: There has been error while updating 'apt-get', please give it some time and try again later.
==> default: 404 errors should be fixed for rvm to proceed. Check your sources configured in:
==> default:     /etc/apt/sources.list
==> default:     /etc/apt/sources.list.d/*.list
==> default: 
==> default: ++ /scripts/functions/requirements/ubuntu : requirements_debian_update_system()  53 > return 100
==> default: Requirements installation failed with status: 100.
==> default:  * Mailcatcher [not installed]
==> default: ERROR:  Could not find a valid gem 'mailcatcher' (>= 0) in any repository
==> default: ERROR:  Possible alternatives: mailcatcher
==> default: Regenerating system wrappers
==> default: ..............
==> default: Could not find file 'mailcatcher' nor '/usr/local/rvm/wrappers/system/mailcatcher'.
==> default: Could not find file 'catchmail' nor '/usr/local/rvm/wrappers/system/catchmail'.
==> default:  * Copied /srv/config/init/mailcatcher.conf    to /etc/init/mailcatcher.conf
==> default: cp: 
==> default: cannot create regular file ‘/etc/php5/mods-available/mailcatcher.ini’
==> default: : No such file or directory
==> default:  * Copied /srv/config/php5-fpm-config/mailcatcher.ini    to /etc/php5/mods-available/mailcatcher.ini
==> default: cp: 
==> default: cannot create regular file ‘/etc/php5/fpm/php5-fpm.conf’
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file ‘/etc/php5/fpm/pool.d/www.conf’
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file ‘/etc/php5/fpm/conf.d/php-custom.ini’
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file ‘/etc/php5/fpm/conf.d/opcache.ini’
==> default: : No such file or directory
==> default: cp: 
==> default: cannot create regular file ‘/etc/php5/mods-available/xdebug.ini’
==> default: : No such file or directory
==> default: sed: can't read /etc/php5/mods-available/xdebug.ini: No such file or directory
==> default:  * Copied /srv/config/php5-fpm-config/php5-fpm.conf     to /etc/php5/fpm/php5-fpm.conf
==> default:  * Copied /srv/config/php5-fpm-config/www.conf          to /etc/php5/fpm/pool.d/www.conf
==> default:  * Copied /srv/config/php5-fpm-config/php-custom.ini    to /etc/php5/fpm/conf.d/php-custom.ini
==> default:  * Copied /srv/config/php5-fpm-config/opcache.ini       to /etc/php5/fpm/conf.d/opcache.ini
==> default:  * Copied /srv/config/php5-fpm-config/xdebug.ini        to /etc/php5/mods-available/xdebug.ini
==> default:  * Copied /srv/config/memcached-config/memcached.conf   to /etc/memcached.conf
==> default: Restart services...
==> default: nginx: unrecognized service
==> default: memcached: unrecognized service
==> default: stop: Unknown instance: 
==> default: mailcatcher start/running, process 5587
==> default: /tmp/vagrant-shell: line 483: php5dismod: command not found
==> default: /tmp/vagrant-shell: line 486: php5enmod: command not found
==> default: /tmp/vagrant-shell: line 489: php5enmod: command not found
==> default: php5-fpm: unrecognized service
==> default: mysql: unrecognized service
==> default: Setup MySQL configuration file links...
==> default: cp: 
==> default: cannot create regular file ‘/etc/mysql/my.cnf’: No such file or directory
==> default:  * Copied /srv/config/mysql-config/my.cnf               to /etc/mysql/my.cnf
==> default:  * Copied /srv/config/mysql-config/root-my.cnf          to /home/vagrant/.my.cnf
==> default: service mysql restart
==> default: mysql: unrecognized service
==> default: No custom MySQL scripting found in database/init-custom.sql, skipping...
==> default: /tmp/vagrant-shell: line 409: mysql: command not found
==> default: Initial MySQL prep...
==> default: 
==> default: Start MySQL Database Import
==> default: No custom databases to import
==> default: Network connection not detected. Unable to reach google.com...
==> default: No network connection available, skipping package installation
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by praisegeek** [comment]
Ok Solved by updating the mirrors.

**Comment by mariadanieldeepak** [comment]
@praisegeek : I'm facing a similar issue in Windows. Could you please elaborate on how you solved the above issue.
