### ISSUE TITLE
provision.sh issues on windows

### ISSUE THREAD

**Issue by squibsy** [Varying-Vagrant-Vagrants/VVV#818]
After finally getting provisioning going for vvv (provision script did not run until I did a vagrant provision), the provisioning script itself has a host of failures. 

Downloading of wordpress, for example, failed. It looks like a permissions issue. the /srv/www directory is owned by root on the VM and when I ssh in and run the curl command copy pasted from the script, it fails to write the file - access denied. I'm assuming provisioning script is run as vagrant user too? It works if I do sudo -i to change to root, or chmod 777, but there are other errors later when I rerun the provisioning - e.g. wp-cli core config fails because access is denied for the user wp which hasn't been set up . As a vagrant newbie this is making me tear my hair out. Any idea what might cause this (aka what have I done wrong)?

The only other salient point I can think of is that vagrant halt command fails (vagrant_halt not found). Searches suggest this might be wrong EOF chars but I've got git bash set to use linux style eof.

**Comment by cristovaov** [comment]
I just did a fresh clone but could not reproduce your problem on my end.

I'd like to know your `[OS] - [VIRTUALBOX | VMWARE VERSION] - [VAGRANT VERSION]`

What terminal do you use? What shell are you using: `[BASH]` or `[CMD]` or `[Cygwin]` or `[PowerShell]`?

Do you run this as Administrator?

Mine is: `Win8.1 x64 - VirtualBox 5.0.12 - Vagrant 1.7.4`

My terminal is ConsoleZ  with a BASH shell. 

I do not run this as Admin.

**Comment by squibsy** [comment]
I'm on Win 8.1 x64. Virtualbox is a little downrev at 5.0.0 vagrant is 1.8.1. I'll update Virtualbox for now and see if that helps.

I've tried from command prompt and git bash. I'm curious if you can check whether /srv/www dir is owned by root, and whether the provision.sh is run by vagrant user? It seems to be this combination of factors that's causing at least some of my issues.

**Comment by jeremyfelt** [comment]
Here is a snapshot of directory ownerships in a fresh VVV instance:

```
vagrant@vvv:~$ ls -lrt /srv/www
total 4
-rwxrwxr-- 1 www-data vagrant 562 Nov 20  2014 vvv-hosts
drwxrwxr-x 1 www-data vagrant 748 Jan 18 01:18 wp-cli
drwxrwxr-x 1 www-data vagrant 646 Jan 18 01:22 phpcs
drwxrwxr-x 1 www-data vagrant 748 Jan 18 01:22 wordpress-default
drwxrwxr-x 1 www-data vagrant 782 Jan 18 01:22 wordpress-trunk
drwxrwxr-x 1 www-data vagrant 272 Jan 18 01:27 default
drwxrwxr-x 1 www-data vagrant 680 Jan 25 21:51 wordpress-develop
vagrant@vvv:~$ ls -lrt /srv
total 0
drwxr-xr-x 1 vagrant  vagrant 238 Nov 20  2014 database
drwxr-xr-x 1 vagrant  vagrant 578 Jul 20  2015 config
drwxrwxr-x 1 www-data vagrant 306 Jan 18 01:22 www
drwxr-xr-x 1 www-data vagrant 170 Jan 26 20:44 log
```

I believe that the VM's root does run `provision.sh`.

**Comment by cristovaov** [comment]
To complement @jeremyfelt 's answer (sorry got distracted!):

Vagrant runs the provisioning script as root indeed and permissions are enforced by Vagrant:
- https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L204-L213

No additional permissions are set in the provisioning script.

**Comment by squibsy** [comment]
I tried again with latest virtualbox, and it sailed thruogh with no issues. Thanks.
