### ISSUE TITLE
Wish to remove Git for core development - NEWBIE! - HELP!

### ISSUE THREAD

**Issue by hollysdesigns** [Varying-Vagrant-Vagrants/VVV#819]
First Time User: On a MAC
I did all of the steps under: The First Vagrant Up
and then I stupidly did these steps without knowing what I was doing:

Use Git instead of Subversion for WordPress core development

By default, VVV provisions WordPress into /www/wordpress-develop/ from the WordPress Subversion repository.

If you prefer to use Git, there is a bundled script that converts to using the Git mirror.

To enable Git for core development, use vagrant ssh to access the virtual machine and then run develop_git. Alternatively, do this in one line with: vagrant ssh -c /srv/config/homebin/develop_git.

Now I don't know how to shut it down because vagrant halt no longer works because I get this:

vagrant@vvv:~$ vagrant halt
The program 'vagrant' is currently not installed. To run 'vagrant' please ask your administrator to install the package 'vagrant'
vagrant@vvv:~$ 

PLEASE TELL ME HOW TO TAKE IT BACK TO HOW IT WAS BEFORE I SWITCHED IT TO GIT SO THAT VAGRANT HALT SHUTS IT DOWN. 
THANK YOU!

**Comment by cfoellmann** [comment]
There shouldn't be any thing blocking halting the van because of the switch to git. Something went wrong for you.
Easiest way is to `vagrant destroy` and set up VVV anew

**Comment by hollysdesigns** [comment]
I got an answer from a colleague. I had to type exit. and then vagrant halt worked. 
He said that I was inside the vagrant machine? vagrant destroy command wasnt working at that time either. 
Alas, problem has been fixed. Thank you for your response though.

**Comment by cfoellmann** [comment]
Good to hear that. Its hard to debug issues like yours over the issue tracker - online.
