### ISSUE TITLE
How to use Vagrant Share on multiple sites in one VM

### ISSUE THREAD

**Issue by mightymight88** [Varying-Vagrant-Vagrants/VVV#820]
I've been trying to figure out how I can change the ports for each site I create and use Vagrant Share to share each individual site using only one VM. I use Variable VVV by bradp to create new sites.

**What I have done so far:**

- Tried following http://www.brownfort.com/2014/10/vagrant-share-for-multiple-sites-in-the-same-vm/ but at the bottom of the page it says _"IF you are running nginx, figure out how can you run multiple websites on different ports."_

- So I added

```
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8082
```
to my vagrantfile

- went into my .conf file that Variable VVV created for my new site and changed the listening port from 80 to 81.

- performed `vagrant reload` and the output looked like this

```
==> default: [vagrant-hostsupdater] Removing hosts
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
default: Adapter 1: nat
default: Adapter 2: hostonly
==> default: Forwarding ports...
default: 80 (guest) => 8080 (host) (adapter 1)
default: 81 (guest) => 8082 (host) (adapter 1)
default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
```
it reloads with no complications, but you can see that if found the ports that I added to my vagrantfile.

- I run `vagrant share --http 80` and it gives me a url, which takes me to vvv.dev.

- I stop the share and then run `vagrant share --http 81` and it gives me a url which then doesn't work.

I feel like I'm missing a step and am not sure what to do. I'm not familiar with this process at all, so any help would be awesome!

Thanks for such a great tool btw!

**Comment by jeremyfelt** [comment]
This likely comes down to 2 things:

1. Make sure the `.conf` file containing the rules for handling these URLs has been properly copied to `/etc/nginx/custom-sites/`
2. Make sure nginx has been reloaded to use the new config files.

A `vagrant reload` won't necessarily do either of these things.

To make sure it worked, I skipped straight to the VM and updated `/etc/nginx/custom-sites/default.conf` to include these two server blocks:

```

**Comment by mightymight88** [comment]
Ahh, that was probably my problem. I appreciate the help. My co-worker and I are just getting into version control and are very new to all these tools. I appreciate the help you have provided.
