### ISSUE TITLE
VVV Version Control Help

### ISSUE THREAD

**Issue by mightymight88** [Varying-Vagrant-Vagrants/VVV#821]
I'd like to reference the issue #508 about VVV Version Control. Through that thread I was still a little lost, so maybe someone can clarify some of my questions for me.

Basically I want to know how to keep the VM identical between multiple collaborators.
This includes the vagrantfile, all the host files created by Variable VVV, the server config files... etc.

Do I just version control the complete VVV directory? Then do I version control each site within the www folder of the VVV directory?

Am I on the right path here? Thanks for the help.

**Comment by jeremyfelt** [comment]
It seems like you're on the right path. As an abstract—the repository should provide a description of the pieces needed to provision the environment that your collaborators will be using. How detailed this should be is up to you.

* By default, VVV describes an environment with Nginx, PHP, etc.. and includes a handful of web directories.
* You may want to adjust/add server configs and add them with custom provisioning.
* You may want to add an entire directory containing plugins/themes.

It may also be beneficial to treat these as pieces. VVV contains provisioning for the server, and then you check out another repository inside the web directory containing your application work.

In the end, the VM won't necessarily by *identical*, but the description of the VM should be and should allow for collaboration in identical environments.

**Comment by cristovaov** [comment]
Hi @mightymight88 

For version control of your provisioned Vagrant box you will need to repackage the box through the Vagrant cli and distibute that repackaged box. 

Ie: Provision the box, configure it according to your project, if your team needs vcs of directories configure this inside the VM, once finished repackage and distribute it to your team. 

You will have to write your own Vagrantfile for the repackaged box to set shared folders and other Vagrant configurations.

Please see the following Vagrant commands documentation: 
`vagrant box --repackage` [link](https://www.vagrantup.com/docs/cli/box.html#repackage)
`vagrant package` [link](https://www.vagrantup.com/docs/cli/package.html)

**Comment by danielquintero** [comment]
This is valuable piece of information, however  I don't seem to find a more detailed guide on how to achieve this vagrant/VVV/git workflow. @mightymight88 my picture gets a bit blurry with the last part:

>  You will have to write your own Vagrantfile for the repackaged box to set shared folders and other Vagrant configurations.

could you provide a sample of the resulting vagrantfile for the repackaged box? or even better you know of some step by step guide towards this solution?

Thanks a lot in advance!

**Comment by mightymight88** [comment]
@danielquintero, to be honest, my team and I decided to just go with a WAMP/git workflow. There are a few handy tools missing from Vagrant, but all we're doing is building websites, so 99% of the time we aren't needing to replicate our server environment. I'm sorry I didn't have the information you were looking for.
