### ISSUE TITLE
1.3.0 Release Work

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#823]
We've been ready to push some sort of update for a long while now. The `master` branch and 1.2.0 version is horribly out of date and probably doesn't work from scratch. The current `develop` branch is working well. Only some documentation really stands in the way now. :8ball: 

Things to do in prep for the 1.3.0 release:

* [x] Clone `develop` branch and `vagrant up` from scratch and verify.
* [x] Clear docs tickets from [1.3.0 milestone](https://github.com/Varying-Vagrant-Vagrants/VVV/milestones/1.3.0)
* [x] Write 1.3.0 CHANGELOG
* [x] Make sure all contributors have been accounted for in README
* [x] Write 1.3.0 Blog post on varyingvagrantvagrants.org

Please chime in here if you see anything blocking a 1.3.0 release.

**Comment by cfoellmann** [comment]
How about releasing smaller updates in the future?
Maybe 1.3.1-beta? When tagging these "releases" we can have a "bleeding" version that can easily be donwloaded as .zip archives

**Comment by jeremyfelt** [comment]
Agreed! I don't think we need the betas, but I would like to start doing quarterly releases or similar. Most of the stuff will be maintenance.

**Comment by jeremyfelt** [comment]
Doing it! :)
