### ISSUE TITLE
Cut down on provision time...

### ISSUE THREAD

**Issue by blakebarber** [Varying-Vagrant-Vagrants/VVV#826]
Just found these two nifty tools [prestissimo](https://github.com/hirak/prestissimo) and [ied](http://gugel.io/ied/). I'll try to implement them and send a pull request.

**Comment by clakeb** [comment]
There is also this tool [pnpm](https://github.com/rstacruz/pnpm) which might be more compatible than just a straight replacement of npm.

**Comment by cfoellmann** [comment]
Prestissimo Sounds great!

**Comment by jeremyfelt** [comment]
Are these packages that should be implemented as part of the upstream project `composer.json` and `package.json` files or will they work during provisioning as globally available?

**Comment by cfoellmann** [comment]
@cblakebarber can you send a PR for prestissimo? Please do not forget the addition to the contributors list (if you are not already on it) and the entry to the changelog!
