### ISSUE TITLE
error installing vagrant 

### ISSUE THREAD

**Issue by hazephase** [Varying-Vagrant-Vagrants/VVV#829]
The home directory you specified is not accessible. The home
directory that Vagrant uses must be both readable and writable.

I get this error , can how one tell me how to fix it ?

**Comment by jeremyfelt** [comment]
Hi @hazephase. What command did you run when this error appeared?

**Comment by 16nsk** [comment]
@hazephase Could you detail the steps you've done?

Seems like you are trying to start VVV from a folder your User has no W+ permissions - that you'd have for other Vagrant boxes, not just VVV.

**Comment by jeremyfelt** [comment]
I'm going to close this out, but please feel free to reopen with more details. :)
