### ISSUE TITLE
Is VVV currently broken?

### ISSUE THREAD

**Issue by eduwass** [Varying-Vagrant-Vagrants/VVV#830]
I'm sorry but VVV is not working for me, tried develop branch, master branch, 1.2.0 tag, 1.1.0 tag... resulting on everything apparently going well, but the /etc/hosts only contains a 'vvv' host (not 'vvv.dev') and none of the other .dev WordPress hosts.

Hardware: 
MBP Retina 2013

Software:
Mac OS X 10.10.5
Vagrant 1.8.1
VirtualBox 5.0.14

I believe I followed all the correct steps, any info on current status?

Thanks :+1:

**Comment by cfoellmann** [comment]
I provisioned the `develop` branch version and it worked on my system. Win10 + VB 5.0.14 + Vagrant 1.7.4
Had some bad issues with Vitrualbox but nothing VVV specific. There must be another issue with your machine. Did you install all vagrant plugins? (reinstall them) Did you run your console in admin mode (no idea if this applies to OSX)

**Comment by eduwass** [comment]
Hi @cfoellmann 
I've deleted everything and reinstalled again and now hosts are there and everything is working fine.
Not sure what went wrong the first time,
Anyways, thanks for the help! :facepunch:
Issue closed

**Comment by cfoellmann** [comment]
@eduwass nice to hear that.
For me most problems come from VB. But it is oracle oss and we all know that you can't expect much from that
