### ISSUE TITLE
Upgrade PHP to 5.6.x or 7.0.x

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#834]
We're way behind right now with PHP 5.5.x. We should do better.

So what's the right answer? I lean toward PHP 7, but am definitely willing to hear reasons for sticking with PHP 5.6.

**Comment by cfoellmann** [comment]
I would love to have php 7 as the default.

**Comment by GaryJones** [comment]
PHP 7, but with phpbrew (another ticket already open) for those who wish to change down per domain to match production setups. Even if someone isn't using any of the new features from PHP 7, there's no harm in having a faster localhost.

**Comment by itsazzad** [comment]
Better if would be selectable per project. Like project X with PHP5.6, Y with PHP7.

**Comment by slaFFik** [comment]
Agree with @itsazzad : selectable PHP version.

**Comment by 16nsk** [comment]
Agree with selectable. Only supported versions. Once 5.5 is off, it should not be present in VVV as well.
Who needs older versions could always just checkout a previous version of VVV that supported that particular version.

**Comment by jjeaton** [comment]
Another vote for phpbrew. While I would love PHP7 as the default, it'll be a long time before the production environments for local sites are all up to PHP7.

**Comment by LoreleiAurora** [comment]
Another vote for PHP7 with phpbrew

**Comment by neilgee** [comment]
Selectable version would be great

**Comment by rowatt** [comment]
As much as I would love to have access to PHP7 in VVV, I think that sticking with PHP5.5 might be the right answer until there's a way to make it user selectable (ideally per project, but for the whole VVV install would be OK).

Why?

If I'm developing for a site which is PHP5.5 in production, then running PHP7 (or 5.6) in VVV isn't going to pick up any issues relating to my code (or plugins, libraries etc) using PHP5.6 or PHP7 features. While I am sure nobody here (except me :-O) ever pushes code directly from VVV on localhost to production, having things not work on a staging environment but work perfectly on VVV is still a pain to debug.

On the other hand, if a host is PHP5.6 or PHP7, it's far less likely to cause problems if I've developed and tested on PHP5.5. Not impossible but less likely I think.

The ideal is for VVV to match a production environment as closely as possible, but until that's possible with a choice of PHP version in VVV, I'd suggest that being conservative is the right way to go (alas).

**Comment by GaryJones** [comment]
Let me offer a counter-argument to rowatt's case.

My client's site is currently on PHP 5.6. We want to move to PHP 7. Before I ask their sysops to bump the staging server PHP version (and later, the live server), I'd like to have my local VVV run PHP 7 so I can test for issues first. Despite my best efforts, I've not yet managed to convince Nginx to use the PHP 7 FPM.

The consensus here is for PHP version to be selectable, and phpbrew is a way for that - there's even a PR open for it already that just needs a bit of TLC.

The ticket title is asking between 5.6 and 7. PHP 5.5 is not actively supported, and only security supported for another 4 months. I see no valid reason not to jump straight to PHP 7, since more and more production sites will be PHP 7 as time goes on, and having VVV at the latest version allows local testing of that. As has been previously said - if one need to stay on 5.5 as that's what production is, then stick with the older release of VVV.

**Comment by jeremyfelt** [comment]
I reframed the project goal a bit when shipping 1.3.0 for clarity. "server configuration common for high traffic WordPress sites" is now "modern server configuration". That should help guide decisions like this. IMO, we're already behind quite a bit by not switching to PHP 5.6 earlier. I think that helps push us toward PHP 7 as the right answer for "modern server".

**Comment by rowatt** [comment]
Whether or not a PHP version is supported doesn't necessarily translate into whether or not it is in widespread use, but GaryJones's counter argument makes good sense.

I had missed the "modern server configuration" goal, which would certainly make sticking with PHP5.5 inappropriate. Alas very few of the servers I develop for are on PHP5.6 let alone PHP7.

Perhaps I could add a request... if VVV moves to PHP7 (or 5.6) before phpbrew or similar is in place, then it would be a great help to tag the last release including PHP5.5 and perhaps mention in the documentation which tag to checkout for those needing PHP5.5.

Irrespective of what you decide, thanks for listening and thanks for all the effort that's gone into this wonderful tool.

**Comment by andrewdcato** [comment]
@GaryJones has already made the case that I came to make - another vote for VVV with phpbrew.

**Comment by spenserhale** [comment]
Were are making our production servers php7. I have already SSH into my vagrant and installed PHP7 and it worked fine, just lost my Xdebug (which can be added back). We would love VVV to either have PHP7 by default / an selectable option. More and more stacks are moving toward 7. https://roots.io/trellis/

**Comment by rclilly** [comment]
I like the idea of using phpbrew, as long as it's contained completely within VVV, since it doesn't run on Windows; It has to be inside of the virtual machine. If we don't have selectable PHP versions I vote to go straight to 7.

**Comment by jeremyfelt** [comment]
The support for PHP 7 both here and in the informal Twitter poll is pretty high. I think that's the right way forward.

We should get PHPBrew working at or near the same time, that will be a nice addition. For those that aren't aware, we have a Phpbrew [feature branch](https://github.com/Varying-Vagrant-Vagrants/VVV/tree/feature/phpbrew) setup that needs to be updated against the current develop branch and tested.

**Comment by GaryJones** [comment]
[Xdebug](https://xdebug.com/) 2.4.0 was released yesterday, and this adds support for PHP 7.

**Comment by GaryJones** [comment]
Also, [Imagick](http://pecl.php.net/package/imagick) 3.4.0 has been released today, which also adds support for PHP 7.

**Comment by cfoellmann** [comment]
maybe we can start by going for xdebug 2.4.0 and Imagick 3.4.0 to make "anything possible"

**Comment by jmichaelward** [comment]
I just did a Google search for "Varying Vagrant Vagrants 5.6" and am glad to see some discussion about the possibility for making PHP7 the base version. That said, I agree with others that it would be wonderful to be able to boot up any of the supported versions, and wanted to add my voice to those who are asking for that.

**Comment by ihorvorotnov** [comment]
One more vote for PHP 7 as a base version + possibility to switch to older version if needed would be nice.

**Comment by ntwb** [comment]
Just read this:

> "PHP 7.0 is now the default PHP package shipping in Ubuntu LTS 16.04 (Xenial Xerus) starting from April 2016!"

**Comment by jeremyfelt** [comment]
Time to celebrate. :tada: 

#844 is merged and provides PHP7, #869 is merged and provides Xdebug for that PHP7. Please test and open any bug tickets as necessary. :bug: 

Big thanks to @LoreleiAurora for the super clean pull request.

I'll start paying more attention to the PHPbrew PR #854 soon.
