### ISSUE TITLE
Add VisualPHPUnit

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#838]
Is possible add https://github.com/VisualPHPUnit/VisualPHPUnit to manage the unit test?

**Comment by cfoellmann** [comment]
This Looks amazing

**Comment by jeremyfelt** [comment]
This does look pretty amazing. My gut says that it would be most useful on a project to project basis depending on your workflow. I'm not sure how it would fit in as a default interface for all projects configured in VVV.

Happy to look at a PR to see how it works, but I'd probably encourage setting it up with a custom script.
