### ISSUE TITLE
Two php-fpm .conf files? php5-fpm.conf vs php-fpm.conf

### ISSUE THREAD

**Issue by eduwass** [Varying-Vagrant-Vagrants/VVV#839]
So I was trying to customize my conf for PHP-FPM and I noticed that there's a file in /config/php5-fpm-config/ that gets copied on provision:

provision.sh:348

```
cp "/srv/config/php5-fpm-config/php5-fpm.conf" "/etc/php5/fpm/php5-fpm.conf"
```

That was ideal, I would just paste my configs on the local file, and it would be copied over on provision.

But when running vagrant I couldn't see my config changes applied, so SSHing into the vagrant boxed I noticed the following file structure in /etc/php5/fpm:

```
/etc/php5/fpm/
├── conf.d
├── php5-fpm.conf
├── php-fpm.conf
├── php.ini
└── pool.d
```

php5-fpm.conf gets copied over correctly, but apparently the one being executed is php-fpm.conf , which doesn't make sense IMO

Is this a mistake or am I missing something?

**Comment by tomjn** [comment]
I'm not sure but as we're on PHP 7.1 and the provisioner has been rewritten since then I'm going to close this out
