### ISSUE TITLE
hubot not installing with vagrant - EACCES: permission denied

### ISSUE THREAD

**Issue by DannyWatson23** [Varying-Vagrant-Vagrants/VVV#841]
I have the provisioner on Github and it does everything fine apart from actually installing hubot.

I have tried to use "sudo vagrant" in with the provisioner file as when I've done this manually it has allowed me to install hubot. 

`su vagrant`
`cd /a/b/c`
`yo hubot --defaults
`

It gives me a permission denied error saying `/root/.config/configstore/insight-yo.json` you don't have access to this file.

How can I explicitly state that the provisioner has access to the file when automatically installing all this shit? 

Thanks

**Comment by cfoellmann** [comment]
why dont you do a `su yo hubot --defaults`?

**Comment by DannyWatson23** [comment]
@cfoellmann I'll give it a shot, I'll edit this when I get the output
