### ISSUE TITLE
404 Not Found when tring to access local.wordpress.dev

### ISSUE THREAD

**Issue by mariadanieldeepak** [Varying-Vagrant-Vagrants/VVV#842]
I'm running Windows 8.1 Pro 64-bit OS and installed Virtual Box 5.0 and Vagrant 1.8.1.

After executing the line `vagrant up --provision` in **Command Prompt**, I'm getting the following errors and then when tried to access `local.wordpress.dev`, [404 Not Found](https://www.dropbox.com/s/v12u3me6xfducc0/unable-to-access-wp.png) is displayed.

```
==> default: Initializing grunt in WordPress develop... This may take a few mome
nts.
==> default: >> Local Npm module "grunt-browserify" not found. Is it installed?
==> default: Loading "sass.js" tasks...
==> default: ERROR
==> default: >> Error: The `libsass` binding was not found in /srv/www/wordpress
-develop/node_modules/node-sass/vendor/linux-x64-11/binding.node
==> default: >> This usually happens because your node version has changed.
==> default: >> Run `npm rebuild node-sass` to build the binding for your curren
t node version.
==> default: Running "clean:all" (clean) task
==> default: >> 0 paths cleaned.
==> default: Running "copy:files" (copy) task
==> default: Created 142 directories
==> default: , copied 1247 files
==> default: Running "copy:wp-admin-css-compat-rtl" (copy) task
==> default: Copied 1 file
==> default: Running "copy:wp-admin-css-compat-min" (copy) task
==> default: Copied 2 files
==> default: Running "copy:version" (copy) task
==> default: Copied 1 file
==> default: Running "cssmin:core" (cssmin) task
==> default: >> 36 files created. 634.73 kB → 535.78 kB
==> default: Warning: Task "sass:colors" not found. Use --force to continue.
==> default: Aborted due to warnings.
==> default:
==> default: VVV custom site import
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 2911 seconds
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql stop/waiting
==> default: mysql start/running, process 28333
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default:    ...done.
```

Please note: I manually modified the hosts file with the following
```
192.168.50.4 vvv.dev local.wordpress.dev local.wordpress-trunk.dev src.wordpress-develop.dev build.wordpress-develop.dev
```

Is there anything related to Windows that causes the above error and giving a 404? I'm totally new to Vagrant and VVV and your help would be very much appreciated.

Thanks.

**Comment by mariadanieldeepak** [comment]
Finally, I resolved the issue that I reported.

Windows users must use `vagrant up --provision` and this solved the issue. Ensure to run the command prompt as **Administrator**.

Answer to issue #712 helped resolving this.

**Comment by dhansshree** [comment]
Not fixing the issue for me either.

**Comment by mariadanieldeepak** [comment]
dhansshree,

I assume you're using Windows 8. Check if you're using any Antivirus in your machine and remove it. Then try `vagrant up --provision`. This should work.

If you still face the issue,, try the following steps.

- Install Git as mentioned here ([http://blog.osteel.me/posts/2015/01/25/how-to-use-vagrant-on-windows.html](http://blog.osteel.me/posts/2015/01/25/how-to-use-vagrant-on-windows.html))
- Configure Firewall as mentioned in Step 3 in [http://main.justinflowers.ca/web/wordpress/?p=36](http://main.justinflowers.ca/web/wordpress/?p=36)
- Use Git bash to Vagrant up (vagrant up --provision)

Hope this helps.

**Comment by dhansshree** [comment]
I am on Windows 7.

Already , I installed git as mentioned in the blog.
Just added the firewall configuration as said.
Used got bash to run provision.

Still getting same 404 error.

**Comment by mariadanieldeepak** [comment]
dhansshree,

What do you use to `vagrant up`? **Command Prompt or Git Bash?** Try `vagrant up --provision` by running Command Prompt or Git Bash as Administrator. That should work.

Otherwise, I would recommend you to re-install.

After you un-install Vagrant and Virtual Box, remove the [.virtualbox folder](https://forums.virtualbox.org/viewtopic.php?f=9&t=52255) and then you try repeating the steps mentioned earlier.

**Comment by mariadanieldeepak** [comment]
dhansshree,

I think you should probably open a new issue and that way more people would be aware of your issue. You might get help from some one else too.
