### ISSUE TITLE
Changing PHP version with phpbrew.

### ISSUE THREAD

**Issue by Nikschavan** [Varying-Vagrant-Vagrants/VVV#847]
I am using branch `feature/phpbrew` I have successfully installed and set up phpbrew for version 7.0.4 with command `phpbrew switch 7.0.4`

`php -v` says version 7.0.4 is installed, but checking `phpinfo();` still shows `php 5.5` 

How to correctly use phpbrew with VVV?

**Comment by tomjn** [comment]
There's a mechanism for changing PHP versions on a per site basis in VVV 2 now, PHPBrew support can be added via a utility, allowing unsupported PHP versions to become available
