### ISSUE TITLE
`Customfile` from any folder, not just Vagrantfile path (or alternative)

### ISSUE THREAD

**Issue by rheinardkorf** [Varying-Vagrant-Vagrants/VVV#851]
Scenario:
We would like to be able to execute certain actions during a `vagrant up`. Different project may have their own set of tasks to perform. Ideally, these tasks would be defined in the project's git repository.

At the moment this can be accomplished by making use of the `Customfile` and adding tasks in here. However, this is not part of the project and when different projects require tasks it needs to be added to `Customfile` outside of the project repo.

Suggestion would be to allow multiple `Customfile`s to be created in the Vagrantfile's directory tree. 

Example:

```
Dir.glob('**/Customfile').each do |f|
    eval(IO.read(File.join(vagrant_dir,f)), binding)
end  
```

vs

```
if File.exists?(File.join(vagrant_dir,'Customfile')) then
    eval(IO.read(File.join(vagrant_dir,'Customfile')), binding)
end
```

This can be unstable and potentially a risk of allowing arbitrary `Customfile`s to be defined in projects.  

Open to suggestions.

**Comment by jeremyfelt** [comment]
It is now possible for each site to have it's own `Customfile` which is selectively fired based on a YAML configuration. See #980. :tada:
