### ISSUE TITLE
Can't install new wordpress sites

### ISSUE THREAD

**Issue by Alessbruno** [Varying-Vagrant-Vagrants/VVV#853]
Hello, I have successfully installed vagrant and vvv on my windows10 machine. I can open http://local.wordpress.dev/ and see the dashboard at vvv.dev; trouble comes when I try to add a new domain: after following the instructions at [https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Add-New-Domain] , when I open mydomain.dev on the browser I find the dashboard again!
See screenshot:
![image](https://cloud.githubusercontent.com/assets/8136117/13828886/49cddd46-ebc4-11e5-99e7-881d945e796a.png)
I have then tried again using variable vv on a different domain, and got the same result.
I am new to vagrant, so I apologize if I am posting an obvious question.
Thanks

**Comment by Alessbruno** [comment]
Hostupdater is not working properly - manually updating hosts did the trick. cheers

**Comment by cfoellmann** [comment]
just try reinstalling the vagrant plugin and lets hope we can move on to ghost soon
