### ISSUE TITLE
Shared DB

### ISSUE THREAD

**Issue by clawfire** [Varying-Vagrant-Vagrants/VVV#860]
I got some question regarding the ability to share content across the different instances of WP. Is it possible ? Reading the `README` file I though the content and config are shared between all the wp instances, letting me develop once and test everywhere, but it seems not. 

Did I miss something or is it not supported ? If so, is it something you consider implementing ?

**Comment by topdown** [comment]
Its mostly site specific from what I have seen.
But there are work arounds you could do I am sure.
IE. symlinks, change DB settings in the wp-config file, etc..

**Comment by clawfire** [comment]
@topdown thanks for the contribution. But it make me a little bit confused. I though VVV is about providing a way to ensure your theme / plugin work across the different versions of WordPress.

Making it connect to the same DB will not help as the versions of the php files & so on will not be the same. For me it miss : 

* having theme & plugin shared between the different instances. To code once and test everywhere
* having a way to sync the content of  the site (pages, articles, medias, ...) but also some settings. In this case there's a need of being compatible between different versions of WP and that's the biggest problem to solve :)

**Comment by cfoellmann** [comment]
Although a lot of people use VVV to code and test their plugins/themes it is mainly for contributing to WP core.
"We" need to look into setting up some kind of `addon` for VVV to provide the configs and tools you describe

**Comment by topdown** [comment]
You could setup for wp version testing like this, example domains
```
site-main.dev
site-4.4.2.dev
site-4.5-RC1.dev
```

Say site-main.dev has the wp-content you want to test.
In the other 2 sites wp-config.php files you could do something like this

```
define( 'WP_CONTENT_DIR', '/srv/www/site-main/htdocs/wp-content' );
define( 'WP_CONTENT_URL', 'http://site-main.dev/wp-content');
define( 'WP_PLUGIN_DIR', '/srv/www/site-main/htdocs/wp-content/plugins' );
define( 'WP_PLUGIN_URL', 'http://site-main.dev/wp-content/plugins');
```

The only thing that would not be correct is the media paths.
With enough digging around that could probably be solved also.

**Comment by jeremyfelt** [comment]
VVV provides both the current release of WordPress (e.g. 4.4) and the current release being developed. This should help with testing and developing plugins for the current and future. Adding additional versions for testing is definitely doable after that, though you will need to manage how your plugin/theme is installed in each of those directories. It's kind of like a shared host on your local machine. :)
