### ISSUE TITLE
putty netWork error 

### ISSUE THREAD

**Issue by ninem** [Varying-Vagrant-Vagrants/VVV#866]
hi 
i am trying to create ssh tunnel to connect remotly to mysql databse 

i already installed OpenSSH in both computers
when i ping the server pc from my pc it works 

using putty in the session  => host name /@ ip => my destination ip adress with port :22 ( i allowed it in the config file )
in the connection =>tunnels => port 3306 
                                              => Destination 3306

when i try to connect => error network , time out 

i tried to disable a fire wall same result

any idea  please

**Comment by cfoellmann** [comment]
why do you want to tunnel anything? Just connect directly to VVV_IP:3306
