### ISSUE TITLE
"git status" slow inside VM, super fast outside (OS X 10.11.4)

### ISSUE THREAD

**Issue by tdlm** [Varying-Vagrant-Vagrants/VVV#867]
From inside:

```
$ time git status
On branch dev
Your branch is up-to-date with 'origin/dev'.

nothing to commit, working directory clean

real	0m4.111s
```

From outside:

```
$ time git status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working directory clean
git status  0.04s user 0.07s system 111% cpu 0.103 total
```

It has been this way for over a year and it's frustrating at times. From what I've read, this probably has to do with the way the shared directories are mounted but I don't know enough about Vagrant in general to make the proper modifications to `Vagrantfile` without messing things up.

Should I try mounting the shared directory as NFS? Not sure what to do.

I would like to add that the `4 second` time you see above is what I consider "fast" from inside the VM. I just did another test and it took nearly `12 seconds`!

**Comment by PascaleBeier** [comment]
Are you running VirtualBox as vagrant Provider?

VirtualBox is known to slow down anything network related.

**Comment by tdlm** [comment]
@PascaleBeier Yes. There's no way around that?

**Comment by jeremyfelt** [comment]
@tdlm This probably depends a bit on the size of the git repository. As @PascaleBeier mentioned, the speed at which files are synced by VirtualBox can be much slower than when managing the files locally. I personally would recommend using `git` outside of the virtual machine if possible.

You may also want to try something like `git gc` to [clean up](https://www.kernel.org/pub/software/scm/git/docs/git-gc.html) the repository and increase performance if it's been going for a while and not cleaning up automatically for some reason.
