### ISSUE TITLE
Theme folder with name "files" causes issue in a multisite

### ISSUE THREAD

**Issue by Frique** [Varying-Vagrant-Vagrants/VVV#874]
This took a while to debug. I'm running a multisite install with a WP theme that has a folder called "files/" in it. Accessing the files in that folder causes a rewrite that's actually meant for multisite media uploads. 

I'm assuming the related rewrite in nginx-wp-common.conf needs to be a bit more specific to avoid targeting regular theme folders.

**Comment by lkwdwrd** [comment]
I've hit this a couple of times doing WP-Parser work which has a taxonomy
named 'files'. At this point are we not far enough that we can abstract
this portion of the nginx.conf out into something like a
'lagacy-ms-nginx.conf' file or similar? That way most sites can continue to
hum along perfectly and even use the files/ namespace as needed while
legacy sites still needing the config can include it?

Luke Woodward – Associate Director of Engineering
10up Inc. <http://10up.com> | luke.woodward@10up.com | @lkwdwrd

**Comment by Frique** [comment]
By legacy, do you mean the rewrite is only there for older WP versions? If so, up to what version?

**Comment by lkwdwrd** [comment]
My understanding is this is a change that happened in WordPress 3.5. At
least that's what the codex page seems to indicate
https://codex.wordpress.org/Multisite_Network_Administration. Basically
http://example.com/files/... is not used for networks created on 3.5 plus.
What I am loosely referring to as a legacy network site.

Luke Woodward – Associate Director of Engineering
10up Inc. <http://10up.com> | luke.woodward@10up.com | @lkwdwrd

**Comment by Frique** [comment]
That's good to know. Then I'll just remove it in my case. But who needs WP < 3.5 support anyway?
Thanks for the information!

**Comment by jeremyfelt** [comment]
>At this point are we not far enough that we can abstract
this portion of the nginx.conf out into something like a
'lagacy-ms-nginx.conf' file or similar?

Yes! I keep on forgetting that this is part of the config. Let's fix it. :)

**Comment by Mte90** [comment]
@tomjn we still need to support wp < 3.5?

**Comment by tomjn** [comment]
lets close this out
