### ISSUE TITLE
Update from MySQL 5.5 to MariaDB 10.0

### ISSUE THREAD

**Issue by ottok** [Varying-Vagrant-Vagrants/VVV#876]
If I'd write a pull request that updates MySQL 5.5 to MariaDB 10.0 (from official Ubuntu repositories), would the community here accept it?

Motivation:
- Many are upgrading from Oracle MySQL to truly open source MariaDB by original creators of MySQL. For example Fedora/RedHat and SUSE ship by default only MariaDB since a few years back. MariaDB has been available in Ubuntu since 14.04 and in Debian since version 8. Debian is planning to have MariaDB as default in next release, Ubuntu might follow.
- Projects like [XAMPP](https://www.apachefriends.org/) already has MariaDB as default.
- Automattic, the company behind WordPress, is a sponsor of the [MariaDB Foundation](http://mariadb.org) and much of the new WordPress infrastructure builds on MariaDB
- Techincal benefits listed at https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql

Why version 10.0 and not 10.1?
- Official Ubuntu repositories have MariaDB 10.0, so for maintenance in long term it is best to stick to it and upgrade when Ubuntu/Debian also upgrade.

I want to have a thumbs up before I invest a lot of time in developing and testing.

**Comment by ottok** [comment]
Any comments from VVV developers? Will you merge the PR if I implement this?

**Comment by johnjamesjacoby** [comment]
+1 for MariaDB

**Comment by moorscode** [comment]
I would love to have MySQL updated from 5.5 to anything at this point.
Though it seems to be harder to change to MariaDB if we first go to MySQL 5.7 in #930 so this would have to be a consideration when looking at that PR.

It seems that going for MySQL 5.7 would be the easiest way to pick, but going for MariaDB the most future-compatible one. Though I wouldn't mind to hear some counter arguments for switching to MariaDB, just to get an idea of what they would be.

I can imagine that a lot of sites are still running on MySQL and might get updated to 5.6 or 5.7 and with the internal choices growing apart this would not fair well on having a reproduction of the production server as development environment. Though this is just speculation and some logic thrown around :)

**Comment by jeremyfelt** [comment]
I've created https://github.com/Varying-Vagrant-Vagrants/VVV/issues/876 to discuss this further.

**Comment by moorscode** [comment]
@jeremyfelt you mean https://github.com/Varying-Vagrant-Vagrants/VVV/issues/949

**Comment by lukecav** [comment]
+1 for MariaDB

**Comment by jeremyfelt** [comment]
A long time coming. :)

I'd like our default to be MariaDB 10 in VVV. We can also provide MySQL Sandbox, but we can handle that in #835.

**Comment by ottok** [comment]
@LoreleiAurora I already have a PR open in #1005, installing MariaDB 5.5 from official Ubuntu 14.04 repos.

Do we intend to upgrade to 16.04 soon? In official Ubuntu 16.04 repos MariaDB 10.0 would be available. If not, I can make a PR that installs a backported Ubuntu 16.04 MariaDB 10.0 to the Ubuntu 14.04 based Vagrant image.

**Comment by jeremyfelt** [comment]
Excellent, thanks @ottok! I just updated the Ubuntu 16.04 ticket (#954). I don't see us updating until at least mid next year, if not later.

**Comment by LoreleiAurora** [comment]
@ottok When switching to MariaDB 10 i would recommend using this PPA `https://launchpad.net/~ondrej/+archive/ubuntu/mariadb-10.0`.
It is maintained by the same person who maintains the PHP we use, and is widely used in production environments.
It is also compatible with the package in the ubuntu PPA so the upgrade process from MariaDB should be as simple as an `apt-get upgrade`.
