### ISSUE TITLE
xdebug.idekey won't update from xdebug.ini

### ISSUE THREAD

**Issue by GuerrillaCoder** [Varying-Vagrant-Vagrants/VVV#879]
In xdebug.ini the default setting was:

xdebug.idekey = "vagrant"

I have tried changing this but it doesn't come into effect.  When I check phpinfo() it is set as:

xdebug.idekey = "VVVDEBUG"

Where is this set?  I assumed xdebug.ini value would be used but it seems like it is ignored and set elsewhere.

Edit:

I updated the idekey over ssh in the php config files which worked but I assume the config/xdebug.ini is meant to work.  Also the values I'm setting in config/php.ini aren't taking effect.

**Comment by jeremyfelt** [comment]
Hi @GuerrillaCoder, thanks for opening an issue.

The `xdebug.idekey` is set to `VVVDEBUG` in VVV's [xdebug.ini](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/php-config/xdebug.ini#L100) file, which is copied over during provisioning.

You could probably maintain a custom version of that and copy it over in `provision-post.sh`.
