### ISSUE TITLE
Clarify VVV in Dropbox

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#88]
This isn't really a VVV problem, but we're in a decent place to figure it out and at least document it somewhere. I'm not entirely sure it's a problem yet either.

It seems that strange things can happen if you initiate a `vagrant up` from within a Dropbox directory. My working theory is that the `.vagrant/` directory created during the process syncs with Dropbox and then somehow loses track of its uniqueness at some point, so when you do `vagrant halt` and `vagrant up` again, a second VM launches in Virtualbox and causes strangeness.

Totally unverified. And now that I'm writing this up without the book in front of me, I forget the setting that can be changed (I think) to move the `.vagrant/` directory somewhere else.

All aside. I want to test VVV in Dropbox and see if we can clarify some behavior around it.

**Comment by simspace-dr** [comment]
I just learned about the VAGRANT_DOTFILE_PATH env variable here:
https://github.com/mitchellh/vagrant/issues/3362

This simple change enables one vagrant environment on Dropbox of Copy by creating unique .vagrant directories for each computer. I did this on three different macs for vvv-apache and it worked perfectly.

I now have vvv-apache shared across three macs using Copy (similar to Dropbox). 
In the vvv-apache directory are three .vagrant directories:
``` 
   .vagrant-home 
   .vagrant-work
   .vagrant-laptop
 ```
Here's how it's done ...

```
1. vagrant halt to shutdown machines
2. added "export VAGRANT_DOTFILE_PATH=.vagrant-laptop" to ~/.bashrc or  ~/.bashrc_profile
3. open new terminals to inherit the new env var
4. move .vagrant to .vagrant-laptop
5. vagrant up -- it works!
6. change "/.vagrant" to "/.vagrant*" in my .gitignore
```
Hope you find this helpful!
Chris S.

**Comment by kopepasah** [comment]
@simspace-dr I've confirmed that this works (thanks); however, instead of modifying the `.gitignore` (which is shared by the repo), you can add an exclusion to `.git/info/exclude` instead.

Cheers.

**Comment by colin-marshall** [comment]
@simspace-dr @jeremyfelt @kopepasah:
Looking to set this up between my laptop and desktop and I'm a little confused about the workflow in regards to making sure the database stays synced between computers.

- I'm assuming that I should never run `vagrant up` on one computer before running `vagrant halt` on the other computer so that they're never running the VM at the same time. Is this correct?
- Do I need to write a script for importing the databases every time I switch computers and run `vagrant up`, even if I have setup the `VAGRANT_DOTFILE_PATH` on each system?

Thanks!

**Comment by kopepasah** [comment]
@colin-marshall it is my understanding that syncing databases between machines is not possible, since there will be an entirely different machine.

**Comment by colin-marshall** [comment]
@kopepasah ok thanks, that answers my 2nd question. I believe it is possible to do but it would involve writing a script that would import the database backup files (created by the vagrant triggers plugin) on every `vagrant up`.

Were you just doing that manually @kopepasah or just not messing with the database on one of the systems?
