### ISSUE TITLE
Is .gitignore missing some file?

### ISSUE THREAD

**Issue by sciamannikoo** [Varying-Vagrant-Vagrants/VVV#880]
Maybe I'm missing the point, but shouldn't `/config/php-config/php-custom.ini` be added to `.gitignore`?

**Comment by cfoellmann** [comment]
sounds reasonable...

**Comment by jeremyfelt** [comment]
`/config/php-config/php-custom.ini` is the (possibly poorly named) official VVV custom PHP config, so it's okay that it's part of the repository.

**Comment by sciamannikoo** [comment]
In this case, wouldn't make sense to have another custom php ini (to add to the gitignore file), where we can add/change some settings?
