### ISSUE TITLE
ZipArchive disabled in 1.3.0

### ISSUE THREAD

**Issue by Kirlat** [Varying-Vagrant-Vagrants/VVV#882]
It seems that ZipArchive PHP extension is not installed in VVV release 1.3.0. However, some WordPress plugins are relying on it. This is also a change from 1.2.0 where ZipArchive was installed. As a result, upgrading from 1.2.0 to 1.3.0 stops several WP plugins from working properly.

I've checked a provision.sh script and it seems that php7.0-zip module that installs ZipArchive in PHP 7 is not listed there. I think we should fix the issue by adding php7.0-zip into a defualt provision.sh configuration.

**Comment by hishawn** [comment]
@kirlat, I ran into a similar issue. I fixed it by adding "php7.0-zip" to the provision file. 

1) open your "provision.sh"
(your VVV directory)/provision/provision.sh
 
2) add "php7.0-zip" at the end of the section titled "# Extra PHP modules that we find useful"

3) Save and close. Then run "vagrant up --provision" 

Not elegant, but should get your WP plugins dependent on zip archive up & running.

**Comment by Kirlat** [comment]
@hishawn, thanks for sharing your experience! I figured out how to fix this too. My point is that provision.sh should be updated with inclusion of php7.0-zip. There are so many plugins that uses ZipArchive so it deserves to be in Vagrant's default configuration (as it was before, in version 1.2).

**Comment by hishawn** [comment]
@Kirlat, I feel you homie. The flip-side is that not loading extra modules
keeps provisioning time to a minimum. We all want minimal provisioning, but
not everyone needs to load everything. Perhaps you and I join forces and
propose a wiki entry on custom provisioning. That way if/when someone runs
into this issue, there will be some documentation.
What say you?

**Comment by neilgee** [comment]
@hishawn thanks for documenting this - I had an issue with failing packages when using **Duplicator** plugin with Zip Archive as the reason, adding in the provision.sh script fixed the issue.

**Comment by Webcascade** [comment]
@neilgee same here.
@hishawn thanks for sharing, cheers!

**Comment by Kirlat** [comment]
@hishawn, sorry for the late response, but all this crazy work load I had recently made stop any sideline activities.

I think the current provision is by no means minimal. On my Core i7 machine with 8Mbs Internet connection it takes minutes to finish. It's OK with me though because I do not need to do it often. I believe adding a little tiny ZipArchive installation won't hurt anybody anyhow.

Of course, one can edit provision file to add a ZipArchive manually. But what will happen if VVV gets updated? We'll have a merge conflict to resolve. This is not what I want to spend my time on, if it's possible to avoid.

What I think would be an ideal solution is to have a custom provision file that will be loaded during a provisioning process. It can be loaded and executed by the 'main' provision.sh script. This way when provision.sh will be updated, it will not affect our custom provision file at all. I believe this is a win-win situation.

Do you know if such thing can be done currently? There is nothing about it in documentation, I believe.

I would be happy to contribute to documentation (although my current time resources are very limited), but I just think editing provision.sh is wrong. I would be happy to document the 'right' way to do though it, if such exists.

**Comment by hubdotcom** [comment]
PR added: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/945

**Comment by neilgee** [comment]
This is not working now.... not too sure why  - i have in my provision.sh

```
# Extra PHP modules that we find useful
  php-memcache
  php-imagick
  php7.0-mbstring
  php7.0-mcrypt
  php7.0-mysql
  php7.0-imap
  php7.0-curl
  php-pear
  php7.0-gd
  php7.0-soap
  php7.0zip
```

But when I provision I get in the rolling credits...

```
==> default:  * php7.0zip [not installed]
```
I manually installed it in the box

```
sudo apt-get install php7.0-zip
```

Did another provision and still get ...
```
==> default:  * php7.0zip [not installed]
...
==> default: Reading package lists...
==> default: Installing apt-get packages...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E
==> default: :
==> default: Unable to locate package php7.0zip
==> default: E
==> default: :
==> default: Couldn't find any package by regex 'php7.0zip'
==> default: Removing unnecessary packages...
```
Anyone know how I get it installed...

**Comment by hubdotcom** [comment]
It's: `php7.0-zip` instead of `php7.0zip`

**Comment by neilgee** [comment]
thanks ! - I missed the `-`

**Comment by jeremyfelt** [comment]
#945 is merged, so we should be good here. My guess is that the php5-common or other package we used to use came with php-zip by default. The php7.0 repository must not include it.
