### ISSUE TITLE
error_log not writing logs to file

### ISSUE THREAD

**Issue by advaittrivedi** [Varying-Vagrant-Vagrants/VVV#883]
Hi,
I have a standard vvv setup, in my function I am doing:

error_log('called', 3, '/home/vagrant/php_error.log');

I am definitely sure that my function executes (because I tested this function in an identical environment but outside of vvv), but when I run this function in vvv I am not able to find php_error.log file. I even tried creating php_error.log manually at this location before running the test. But still no logs in that file.

**Comment by grappler** [comment]
It may be better to use the WP defaults. You can activate it with `define( 'WP_DEBUG_LOG', true );`.
The file is then avaiable under `/wp-content/debug.log`
https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG_LOG

**Comment by advaittrivedi** [comment]
@grappler thanks, that works.
