### ISSUE TITLE
Strange problems after "vagrant box update"

### ISSUE THREAD

**Issue by AndreaBarghigiani** [Varying-Vagrant-Vagrants/VVV#884]
Hi all and first and foremost *thank you for this huge tool that has helped me a lot with my local development!*

It is the first time that I get to write an issue bucause it is the first time that I get a strange error using VVV, but you now there's always a first time.

So I've been using VVV a lot in the last years but this time when I run `vagrant box update` I got some errors...

- when I try to see my dashboard on `vvv.dev` I get a 504 Gateway Time-out. I am usign the wonderful https://github.com/topdown/VVV-Dashboard but I do not think this is the problem here;
- if I try to connect via SSH with the terminal there is just no response at all. The terminal is still there waiting for a response of my server and nothing happen

The strange thing is that if I try to work on the projects that I have installed on it everything seem work, I tryed to edit some files on my machine and they have updated the ones on my virtual machine.

I do not have great knowledge of server web or system administration so I am writing to you to find a solution about it. There are some command that I could run in order to solve this problem? I've already destroyed the machine and _upped_ and even if I got my sites working the dashboard is still unreachable.

Before it I got some problems with the gem `net-ssh` but I do not think is something relevant...

If can help the logins and updates of my WordPress installations are getting really slow, some thimes I get just a timeout error or that it wasn't possible to reach WordPress.org.

I am thinking to remove completely my VVV installation by destroyng the box and then delete the `vagrant-local/` folder in order to start qith a fresh installation, do you think this is gonna help and solve my problem? Are those the right steps in order to start wit a fresh installation of VVV?

I am running VVV on a El Capitan 10.11.4 and never encountered this problem before.

Thank you for the future help,
Andrea

**Comment by AndreaBarghigiani** [comment]
If this can help I've updated from `20160107.1.0` to `20160406.0.0`

**Comment by jeremyfelt** [comment]
Hi @AndreaBarghigiani, thanks for opening an issue. I hope things have started to work for you since April. :)

If not...

* What version of Vagrant is installed?
* What version of VirtualBox is installed?
* What version of VVV are you using?

**Comment by jeremyfelt** [comment]
I'm going to close this out, but please feel free to continue discussion. We can always reopen if needed.
