### ISSUE TITLE
Blackfire PHP profiler support

### ISSUE THREAD

**Issue by dwenaus** [Varying-Vagrant-Vagrants/VVV#885]
Does the community envision Blackfire PHP profiler support anytime soon? (https://blackfire.io/)

**Comment by jeremyfelt** [comment]
Hi @dwenaus, thanks for opening an issue. Sorry about the wait. :)

Blackfire looks interesting, but I don't see it being an officially supported profiler. This may be the perfect thing for configuring through `provision-post.sh` though.
