### ISSUE TITLE
Move www path somewhere else

### ISSUE THREAD

**Issue by alexidro** [Varying-Vagrant-Vagrants/VVV#888]
I already searched everywhere online but not found any answer about this.

I was wondering if it's possible and how to move the `www` directory somewhere else.

I work also with Laravel + Homestead (Laravel's default vagrant environment) for example, and I use to have all the code under `~/Dev/www` and have the vagrant Homestead dir under `~/Homestead`.

Homestead also provides an alias file referencing it's vagrant file everywhere else, so it's possible to execute `homestead up` from everywhere (equivalent to `vagrant up` inside the Homestead path) instead having to execute from it's directory.

I find this very convenient. 

Is it possible with VVV?

Thank You

**Comment by jeremyfelt** [comment]
Hi @alexidro, sorry to leave you waiting.

It's probably possible, though it may involve quite a bit. If I were going to do it, I'd probably map the other `www` drive to `/var/www/` inside the VM as part of a `Customfile` and then use `provision-post.sh` to setup the nginx config, etc... That's stretching the bounds quite a bit though.

There *may* be a way in `Customfile` to unmount the existing directory and re-mount another, but I haven't looked into that at all.
