### ISSUE TITLE
Virtual Machine Asking to Log in?

### ISSUE THREAD

**Issue by rwrobe** [Varying-Vagrant-Vagrants/VVV#889]
I've tried to vagrant up my machine and I get the error `default: Warning: Authentication failure. Retrying...` endlessly. To try to see what's going on I looked at the virtual machine GUI, which asks for my vvv login. None of the combinations of root, admin, password, anything else seems to get past this prompt.

**Comment by jeremyfelt** [comment]
The Virtualbox GUI will probably show you a standard console. In that case, the default user/pass should be vagrant/vagrant as suggested by the [base box](https://www.vagrantup.com/docs/boxes/base.html) guidelines. I'm guessing the issue causing the repeated auth failure is probably related to #375.

**Comment by etrock** [comment]
I think when you get  `default: Warning: Authentication failure. Retrying...` your VM still booting. I always get 4 ,6 times this messagen and then ` default: Machine booted and ready!
`.

**Comment by ntwb** [comment]
It could also be a MySQL memory issue, I've been coming across this quite frequently recently where trying to login to `http://src.wordpress-develop.dev/wp-admin/` using the default `admin` / `password` will never actually log me in 😞 

Try:
SSH into VVV: `vagrant ssh`
Restart MySQL: `sudo service mysql restart`
