### ISSUE TITLE
Can't start xdebug

### ISSUE THREAD

**Issue by mojosef** [Varying-Vagrant-Vagrants/VVV#892]
Hi there.

I'm trying to get xdebug to start using the instructions but am receiving the error below? If anyone could shed any light on what to do I would be really greatful..

`xdebug_on`
`WARNING: Module xdebug ini file doesn't exist under /etc/php/5.5/mods-available`
`php7.0-fpm stop/waiting`
`php7.0-fpm start/running, process 16481`

**Comment by topdown** [comment]
It was missing completely for me running current master branch
I had to 
```
vagrant ssh
su
#password
vagrant

# XDEBUG Missing
pecl install xdebug

XDEBUG_PATH=$( find /usr -name 'xdebug.so' | head -1 ) sed -i "1izend_extension=\"$XDEBUG_PATH\"" "/etc/php5/mods-available/xdebug.ini"

service php5-fpm restart

exit
# then try xdebug_on
xdebug_on
```

**Comment by jeremyfelt** [comment]
I'm hoping this was an issue in the initial upgrade to PHP7.0. I just tested on the current `develop` branch and xdebug is working as expected.

Some better upgrade management documentation is in our future. :)
