### ISSUE TITLE
All wordpress installations not working fully after database import on a new installation.

### ISSUE THREAD

**Issue by allisongrey** [Varying-Vagrant-Vagrants/VVV#897]
I recently created a new wordpress installation via vvv on a vagrant local box. I did a database import with the Database All In One WP Migration plugin that I've done maybe 100 times before with no problem. 

The first thing I noticed was the site I was trying to import to after completing the import fine gave a Too many Redirects error and wouldn't load the front end. Then I started experiencing this when I tried to load other wordpress installations I had previously worked on (having made no changes to these sites yet since they last were working fine.)

Now some of the sites give the redirect loop (even after dumping cookies and cache) and other websites will load only partial content, and very oddly which content will load and which one, whole pieces of the website including headers, text blocks, etc will just be missing leaving a like half there half not partial shell of the website. 

Its like when that one database was upgraded it experienced a failure that has cascaded to the rest.

I have tried updating vagrant to the latest version but that made no difference.

Any advice would be really appreciated - both what might be wrong and how to salvage my websites.

I've attached three photos to help. The first is the redirect issue. the second two are the local environment and the live site both scrolled to the same position so you can see what is missing from the local to the live site. 
<img width="1113" alt="screen shot 2016-05-07 at 1 35 44 pm" src="https://cloud.githubusercontent.com/assets/9970026/15094443/0ebeea7a-1459-11e6-9cd9-39d902f8f3ab.png">
<img width="1400" alt="screen shot 2016-05-07 at 1 36 20 pm" src="https://cloud.githubusercontent.com/assets/9970026/15094441/0ebde544-1459-11e6-830a-eefaddec799e.png">
<img width="1397" alt="screen shot 2016-05-07 at 1 37 55 pm" src="https://cloud.githubusercontent.com/assets/9970026/15094442/0ebe052e-1459-11e6-871f-d1e7907eab49.png">

**Comment by jeremyfelt** [comment]
Hi @allisongrey, thanks for taking the time to open an issue. This sounds like the right thing to pass to the support team for the All In One WP Migration plugin. The MySQL configuration in VVV should not alter how this plugin works.

I would also recommend looking at something like [WP CLI](http://wp-cli.org/) in the future for migrating sites.
