### ISSUE TITLE
Shutting down MySQL

### ISSUE THREAD

**Issue by christianmagill** [Varying-Vagrant-Vagrants/VVV#899]
I have a site where I need to be able to use SSH forwarding. This being the case I need to be able to stop mysql to make the port available. I am having trouble however stopping mysql through vagrant ssh. Any suggestions?

I've tried:

mysqladmin -u root -p shutdown
tested passwords:  <blank>, vagrant, secret and password

I've also just tried "mysqladmin shutdown" with no success.

Thanks.

**Comment by christianmagill** [comment]
I tried a password of "root" as well, and while that seems to be the password for root user the command does not solve my problem.

**Comment by zamoose** [comment]
Hmmm? What has SSH forwarding to do with MySQL's port?

On Mon, May 9, 2016 at 12:23 PM, christianmagill <notifications@github.com>
wrote:

> I have a site where I need to be able to use SSH forwarding. This being
> the case I need to be able to stop mysql to make the port available. I am
> having trouble however stopping mysql through vagrant ssh. Any suggestions?
>
> I've tried:
>
> mysqladmin -u root -p shutdown
> tested passwords: , vagrant, secret and password
>
> I've also just tried "mysqladmin shutdown" with no success.
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/899>
>



-- 
-Doug

**Comment by christianmagill** [comment]
It's occupying the port I need to use, so when I try and bind with "ssh -L"... I receive a port already in use message.

**Comment by zamoose** [comment]
I'm not following your use case here. What is it you're trying to accomplish? Why are you trying to bind something to 3306?

**Comment by cfoellmann** [comment]
The command is `mysql` not "mysqladmin"

**Comment by jeremyfelt** [comment]
`vagrant ssh -c "sudo service mysql stop"`, though I'm also not sure why SSH forwarding would conflict with this. :)
