### ISSUE TITLE
Can we run PHP projects whlie using VVV for WordPress?

### ISSUE THREAD

**Issue by mariadanieldeepak** [Varying-Vagrant-Vagrants/VVV#900]
Apologies if this question sounds basic.

I wanted to run PHP projects and would like to know if I can use VVV to do the same. I originally installed VVV for WordPress development and I'm not sure if I can use VVV instead of using similar vagrants such as Laravel Homestead to run PHP projects.

**Comment by bradp** [comment]
Yes, this works without a problem. You can follow the custom site setup, and ignore the WordPress-specific parts. [vv](http://github.com/bradp/vv) also supports non-WP projects, and there don't seem to be any issues with it.

**Comment by mariadanieldeepak** [comment]
Thanks @bradp. Will try it out.
