### ISSUE TITLE
No longer need the init-custom.sql?

### ISSUE THREAD

**Issue by jonathan-dejong** [Varying-Vagrant-Vagrants/VVV#901]
Hey,

I think I read a while back about making `init-custom.sql` redundant in VVV.. 
What's the status on that? Do I still need to add new site DBs to this file? 
I'm currently running VVV v1.3 (latest it seems). I've been using it for some time tho so I do have quite a few dbs in there (maybe 15).

**Comment by jeremyfelt** [comment]
Hi @jonathan-dejong, thanks for opening an issue.

`init-custom.sql` is still supported as the way to ensure basic database information is available during provisioning. There may be a smarter way to do this in the future, but we'll maintain back-compat here as long as possible.

Some other DB processing, mainly auto backups, has been dropped by default in the past unless the vagrant triggers plugin is installed.
