### ISSUE TITLE
Where are my sites in the vm?

### ISSUE THREAD

**Issue by thinkhuman** [Varying-Vagrant-Vagrants/VVV#904]
I'm using vagrant/VVV/VV, and have created several sites using vv. I can see vvv.dev and all my sites (mysite1.dev, mysite2.dev, etc.).

But when I ```vagrant ssh``` to login to my VM, I don't see my sites duplicated there inside the VM, in any directory. 

[UPDATED] Sorry, I completely forgot--the sites are in ```/srv/www/```. If that's not in the VVV docs (I couldn't find it), I propose adding it.

**Comment by fab9** [comment]
@thinkhuman I'm also using vagrant/vvv/vv and can also see vvv.dev and all my other sites.

But when I `vagrant ssh` I still can't find where they are inside the VM. I don't see the directory `srv`.
Can you please tell me exactly where it is? Thanks!

**Comment by thinkhuman** [comment]
@fab9 that's one of those less intuitive Unix things. Try ```cd /srv/www```. The beginning slash is important.

**Comment by topdown** [comment]
In Unix systems

`cd srv/www` would look for `srv/www` in the current place you are at in the system
where as
`cd /srv/www` will look in the root of the drive for srv/www

So with / and without / have 2 different meanings in Unix systems.
