### ISSUE TITLE
Machine is off in Virtualbox, but still running

### ISSUE THREAD

**Issue by coffeeneed** [Varying-Vagrant-Vagrants/VVV#906]
I'm a beginner, so just wondering why the machine is working with www and ssh, but the machine is turned off in Virtualbox. Why?

In additon to that I get the "failed to open session for the virtual machine vagant-local" if I try to boot/start/double click it.

**Comment by jeremyfelt** [comment]
Hi @coffeeneed. I'm not sure how this can happen. It sounds like Vagrant and VirtualBox have somehow become disconnected. You may want to check out the [Vagrant](https://github.com/mitchellh/vagrant) repository for support.
