### ISSUE TITLE
vagrant-local already exists?

### ISSUE THREAD

**Issue by cbananal** [Varying-Vagrant-Vagrants/VVV#907]
I was working fine and steady as usual when vagrant suddenly stopped working. It says "closed by remote host." So I did  a "vagrant up" again and now it says, "A VirtualBox machine with the name 'vagrant-local' already exists. Please use another name or delete the machine with the existing name, and try again." I Googled but still don't know what the problem might be as I didn't do anything other than doing my usual code. Thank you!

**Comment by grappler** [comment]
I don't have a problem solution. 

Te first step I take is to stop all VirtualBox process and try again. If it does not work you can remove the box from the gui and rerun `vagrant up` which will need to provision everything again. You can remove the files as all of your code in `vagrant-local` is safe.

**Comment by cbananal** [comment]
Thank you for response. I did that but still no luck. Decided to switch to MAMP for now since I'm working on a time-sensitive project. But thank you. Appreciate it! 👍

**Comment by ntwb** [comment]
Weird, I'm having this same issue today :/

I'll dig around and follow up more with anything I find and/or create new issues as needed
