### ISSUE TITLE
/usr/lib/ruby/vendor_ruby/bundler.rb:163:in `rescue in root'

### ISSUE THREAD

**Issue by antoscarface** [Varying-Vagrant-Vagrants/VVV#912]
Hi,

When I try to execute any command of vagrant, I receive this error:

==> default: /usr/lib/ruby/vendor_ruby/bundler.rb:163:in `rescue in root'
==> default: : Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:159:in `root'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:71:in `bundle_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:419:in `configure_gem_home'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:407:in `configure_gem_home_and_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:57:in `configure'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:118:in `definition'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:88:in `setup'
==> default: 	from /usr/bin/vagrant:75:in `<main>'
==> default: Command execution finished.
The local command "vagrant ssh -c 'vagrant_up'" returned a failed exit
code or an exception. The error output is shown below:

/usr/lib/ruby/vendor_ruby/bundler.rb:163:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
	from /usr/lib/ruby/vendor_ruby/bundler.rb:159:in `root'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:71:in `bundle_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:419:in `configure_gem_home'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:407:in `configure_gem_home_and_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:57:in `configure'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:118:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:88:in `setup'
	from /usr/bin/vagrant:75:in `<main>'

I've looked everywhere, here and on google, but the only one solution found is #816. It solves on next vagrant command but if I do again vagrant up, again the error appears.

I have the master version of github, so the latest version and I have also 1.8.1 version of vagrant. I am on Ubuntu 16.04. 

Should I revert to specific version of vvv? Or what else I need to do?

Thanks in advice.

**Comment by topdown** [comment]
If you machine actually starts...
I had a bunch of stuff missing on the current Master branch of VVV do to install script errors eg `vagrant up --provision`

This is the list of commands that I had to run from within the machine `vagrant ssh`
Then my list is here https://gist.github.com/topdown/6ee7c237b300a0cda03717ccc69599cd

Not saying it will fix your situation, but just giving you the link so you can try.

**Comment by jeremyfelt** [comment]
@antoscarface can you try the `develop` branch of VVV and see if there is any change?

**Comment by antoscarface** [comment]
Yes, I tryed `develop` branch and it works very well now.. I haven't
realized that exists a `develop` branch and it's the working one :D

Thanks.

Il giorno mar 14 giu 2016 alle ore 09:00 Jeremy Felt <
notifications@github.com> ha scritto:

> @antoscarface <https://github.com/antoscarface> can you try the develop
> branch of VVV and see if there is any change?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/912#issuecomment-225796056>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB1TTZv3qhaDfewkgHUerKRlOYO6lnRbks5qLlGegaJpZM4IqQdb>
> .
>
-- 

Antonino Scarfì

**Comment by jeremyfelt** [comment]
Great! I'm a little worried that `master` was broken for you, but also happy that `develop` is good. :)
