### ISSUE TITLE
Vagrant up & Vagrant  halt  both generate error messages

### ISSUE THREAD

**Issue by pvanbavel** [Varying-Vagrant-Vagrants/VVV#915]
I'm a newbee on vagrant and I'm having trouble both on `vagrant up` as well as on `vagrant halt`. In both cases I get a `returned a failed exit` and some explanatory messages that don't explain anything to me. Sorry.
What's wrong? How can I get rid of these error messages.

`$ vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
==> default: D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:10:in `rescue in change_env': uninitialized constant Vagrant::Util::SafeEnv::Errors (NameError)
==> default:    from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:8:in `change_env'
==> default:    from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/bundler.rb:72:in `init!'
==> default:    from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:23:in `<main>'
==> default: Command execution finished.
The local command "vagrant ssh -c 'vagrant_halt'" returned a failed exit
code or an exception. The error output is shown below:

D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:10:in `rescue in change_env': uninitialized constant Vagrant::Util::SafeEnv::Errors (NameError)
        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:8:in `change_env'
        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/bundler.rb:72:in `init!'
        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:23:in `<main>'
`

`$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: VirtualBox VM is already running.
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress-trunk.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:10:in `rescue in change_env': uninitialized constant Vagrant::Util::SafeEnv::Errors (NameError)
==> default:    from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:8:in `change_env'
==> default:    from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/bundler.rb:72:in `init!'
==> default:    from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:23:in `<main>'
==> default: Command execution finished.
The local command "vagrant ssh -c 'vagrant_up'" returned a failed exit
code or an exception. The error output is shown below:

D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:10:in `rescue in change_env': uninitialized constant Vagrant::Util::SafeEnv::Errors (NameError)
        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_env.rb:8:in `change_env'
        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/bundler.rb:72:in `init!'
        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:23:in `<main>'
`

**Comment by jeremyfelt** [comment]
Hi @pvanbavel. It's _possible_ that the error is related to the Vagrant Triggers plugin, but it's hard to tell. What happens if you run `vagrant up` after uninstalling that plugin?

`vagrant plugin uninstall vagrant-triggers`

**Comment by pvanbavel** [comment]
Hey Jeremy,

Then everything works smoothly, I think. See attached screen output.
Is that triggers pluin necessary?

Regards,

Paul van Bavel
=====================================================================
$ *vagrant plugin uninstall vagrant-triggers*
Uninstalling the 'vagrant-triggers' plugin...

Paul@PC-Paul /cygdrive/d/HashiCorp/vagrant/vagrant-local
$ vagrant halt
==> default: Attempting graceful shutdown of VM...
==> default: [vagrant-hostsupdater] Removing hosts

Paul@PC-Paul /cygdrive/d/HashiCorp/vagrant/vagrant-local
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed
version of
    default: VirtualBox! In most cases this is fine, but in rare cases it
can
    default: prevent things such as shared folders from working properly.
If you see
    default: shared folder errors, please make sure the guest additions
within the
    default: virtual machine match the version of VirtualBox you have
installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4
local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4
local.wordpress-trunk.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4
src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4
build.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4
themereview.wordpress.dev
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/HashiCorp/Vagrant/vagrant-local
    default: /srv/www => D:/HashiCorp/Vagrant/vagrant-local/www
    default: /srv/log => D:/HashiCorp/Vagrant/vagrant-local/log
    default: /srv/config => D:/HashiCorp/Vagrant/vagrant-local/config
    default: /srv/database => D:/HashiCorp/Vagrant/vagrant-local/database
==> default: Machine already provisioned. Run `vagrant provision` or use
the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always
will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql stop/waiting
==> default: mysql start/running, process 7536
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:443, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:443, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:443, ignored
==> default: nginx: [warn] conflicting server name
"themereview.wordpress.dev" on 0.0.0.0:443, ignored
==> default:    ...done.


Friendly Regards,
Met vriendelijke groet,


Paul van Bavel
President van Rijenlaan 57
4741 DG Hoeven
Nederland

T:  +31 165 32 58 16
M: +31  6 2390 1667

**Comment by jeremyfelt** [comment]
Good to hear. The plugin is not necessary, only if you'd like to run additional scripts (based on triggers) during up, halt, reload, etc... Really there isn't too much use for it overall unless you are doing quite a bit of custom provisioning.
