### ISSUE TITLE
Provision falsely claim to add domain to hosts file

### ISSUE THREAD

**Issue by jonathan-dejong** [Varying-Vagrant-Vagrants/VVV#917]
Hey!

Been experimenting with dynamically creating the necessary files for nginx and hostsupdater. 
Creating the nginx conf file works great!
```
#Create nginx file automatically
	cat <<-EOF >vvv-nginx.conf
	server {
	    listen			80;
	    listen          443 ssl;
	    server_name		$SITE_URL;
	    root			{vvv_path_to_folder}/htdocs;
	    include			/etc/nginx/nginx-wp-common.conf;
	}
	EOF
```

However creating the `vvv-hosts` file causes trouble. 
```
echo "Create hosts file automatically"
	cat <<-EOF >vvv-hosts
	$SITE_URL
	EOF
```
The file is created and it seems to be located BUT even tho the output claims that it's being added to the hosts file on my local mac it is not. I have to run `vagrant reload` for it to actually get written. 
So while the output from doing a `vagrant provision` says:
`==> default:  * Added testing.wordpress.dev from /srv/www/projects/testing/vvv-hosts`
it does not. If I immediately after the provision run a `vagrant reload` this is output:
`==> default: adding to (/etc/hosts) : 192.168.50.4  testing.wordpress.dev  # VAGRANT: fc2950b8c4cf1501bfc5aecbd3f2c632 (default) / 58fec294-5584-4dfd-bf5a-9878f76900b8`
and it actually gets added.

I figure this must be something in either VVV or the hostsupdater plugin? To me it sounds like the actual update of /etc/hosts happens before the file is created and then the output to the terminal happens after the file is created? 

Anyone with any ideas on this? Would love to be able to create the vvv-hosts file dynamically as well.. then it would just be the .sh file (and our own composer file) for each new project. 

thanks!

**Comment by jonathan-dejong** [comment]
So did a bit more digging and found that the output from `vagrant provision` is on row 766 in `vvv/provision/provision.sh` (if it's not been moved around.. not sure I run the latest version). 
I'm not well versed in bash etc. and not sure wether it actually adds anything but it looks to me like it just echoes to terminal..?

```
# Parse any vvv-hosts file located in www/ or subdirectories of www/
  # for domains to be added to the virtual machine's host file so that it is
  # self aware.
  #
  # Domains should be entered on new lines.
  echo "Cleaning the virtual machine's /etc/hosts file..."
  sed -n '/# vvv-auto$/!p' /etc/hosts > /tmp/hosts
  mv /tmp/hosts /etc/hosts
  echo "Adding domains to the virtual machine's /etc/hosts file..."
  find /srv/www/ -maxdepth 5 -name 'vvv-hosts' | \
  while read hostfile; do
    while IFS='' read -r line || [ -n "$line" ]; do
      if [[ "#" != ${line:0:1} ]]; then
        if [[ -z "$(grep -q "^127.0.0.1 $line$" /etc/hosts)" ]]; then
          echo "127.0.0.1 $line # vvv-auto" >> "/etc/hosts"
          echo " * Added $line from $hostfile"
        fi
      fi
    done < "$hostfile"
  done

```

**Comment by lkwdwrd** [comment]
The hosts logic in the provisioning script adds hosts to the _internal_ hosts file (the guest). The hostsupdater plugin, which adds hosts entries to the _external_ (the host) machine, runs prior to provisioning. The only way to add hosts via the hostsupdater if you create the vvv-hosts file during provisioning is to run `vagrant reload` or re-running `vagrant up`.

This is generally why there are tools like [vv](https://github.com/bradp/vv) or my [generator-vvv](https://github.com/lkwdwrd/generator-vvv) which work to create those files outside the VM before running vagrant commands or provisioning scripts.

**Comment by jonathan-dejong** [comment]
@lkwdwrd Thanks for some clarification..
So when I have a vvv-hosts file present it works because the hostsupdater runs on `vagrant provision` but before our provision script? Because if there is a manually created vvv-hosts file it works. 

Is there a reason why it would need to run before the provision script? If it's only task is to add entries to the external machine it seems it could just as well run after the provision script.

**Comment by lkwdwrd** [comment]
I don't think it's necessarily a requirement, but hostsupdater is a vagrant plugin and I'm not much of a rubyist, nor have I dug into the depths of vagrant to see if there is a later hook available. The hostsupdater plugin is also somewhat abandoned at this point, one of the reasons I'd like to [see us replace it](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/606) with [Vagrant Ghost](https://github.com/10up/vagrant-ghost) - a more updated fork of the plugin. That still runs on the same hook, though, not after provisioning.

**Comment by lkwdwrd** [comment]
Also, to be it clear -- [Vagrant Hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) and Vagrant Ghost are separate projects from VVV, so it's not really something this project can change.

**Comment by jonathan-dejong** [comment]
Yeah. Sorry if I sounded snarky :) I know they're separate projects but like you I'm not much of a rubyist so I figured I throw out the question. Now I got your two cents and it sounds like I'll be keeping the vvv-hosts file. No biggie!
