### ISSUE TITLE
Install PHPCS globally with composer rather than git

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#922]
Via #608, VVV doesn't necessarily need to provide PHP_Codesniffer via git clone and can instead use Composer to install it globally.

It would be interesting to hear from anyone working on the [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) project as to whether its helpful to have the PHP_Codesniffer git repository available. /cc @westonruter, @GaryJones 😄

**Comment by westonruter** [comment]
I would say it is not really necessary to have it installed by default as a Git clone. It is rare that I need to change out the PHPCS version when developing for WPCS.

**Comment by tomjn** [comment]
Closing as it's already been implemented
