### ISSUE TITLE
Provide more proper documentation

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#924]
I think it would be nice to have a VVV docs site.

* I love the work that everyone has done with the GitHub Wiki, but it doesn't seem like the most useable or maintainable interface.
* The README file is huuuuuuuuge now.

What's the right answer?

* Jekyll to varyingvagrantvagrants.org?
* Map varyingvagrantvagrants.org to GitHub Pages?
* Something else?

**Comment by brianjking** [comment]
@jeremyfelt Yes, I agree. Something certainly should be done to enhance and streamline the documentation. 

I suggest using MkDocs or Sphinx. I'd be happy to help out in any way that I can. I'm very familiar with both of the tools below.

* https://github.com/mkdocs/mkdocs
* https://github.com/sphinx-doc/sphinx

**Comment by DrewAPicture** [comment]
MkDocs could work, or GitHub pages. GitHub pages seems fitting since it's not a huge move from the wiki and easily maintainable. Sphinx is probably not a great choice since it's intended for code documentation more so than what we're talking about here.

**Comment by brianjking** [comment]
@DrewAPicture I don't agree about Sphinx **only really** fitting for code documentation, most of what I use Sphinx for is for more prose content. http://help.duelingdogs.net/en/latest/

**Comment by brianjking** [comment]
@DrewAPicture The other benefit of Sphinx over MkDocs is if we hosted the built documentation on ReadTheDocs is the production of PDF/EPUB for offline access to the documentation for those that may benefit from this. 

Unfortunately, despite MkDocs being able to be built/served from ReadTheDocs it doesn't feature the PDF build/output options as part of Sphinx.

**Comment by DrewAPicture** [comment]
@brianjking I'm only saying that Sphinx was _intended_ for code documentation. You very well may be using it for something entirely different, but that's what it was built for. And the offline options are nice :)

**Comment by brianjking** [comment]
@DrewAPicture Regardless, VVV needs better documentation and I'm happy to help in whatever way I can. What is the next step?

@jeremyfelt -- Input?

**Comment by brianjking** [comment]
I think VVV could also benefit from a Discourse site, lots of good info can be gathered and then transferred into official docs that could assist many users. I know the Discourse install over at EasyEngine has helped me out a few times!

**Comment by jeremyfelt** [comment]
Thanks for kicking off the discussion @brianjking and @DrewAPicture!

I'm leaning toward GitHub Pages for how simple it would be to maintain. The workflows there should be pretty straight forward to define for updating documentation via pull request.

It would be great to work toward a structure that could provide documentation in multiple languages. I think that would be possible in Jekyll using something like https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin. It would not be too difficult to move from GitHub Pages to self-hosted Jekyll when that time comes.

> Regardless, VVV needs better documentation and I'm happy to help in whatever way I can. What is the next step?

Excellent! I think the next step is for me to create a repository.

Once we have the repository, we can toss around some possibilities for data architecture. This will also involve combing through open and closed issues to find where FAQs have been answered and not properly documented elsewhere yet.

**Comment by josephfusco** [comment]
+1 for GitHub pages. It will keep everything together in one place.

@jeremyfelt I am also happy to help with the development of the Jekyll theme if we are looking for a custom solution.

**Comment by jeremyfelt** [comment]
Ok. The documentation repository is at https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org, which is where it will live for at least the near term. If a better solution comes up that will help integrate that repo with this one, we can do that. If not, what we have now is better than what we did. :smile:
