### ISSUE TITLE
Upgrade MySQL to 5.6

### ISSUE THREAD

**Issue by mikkamp** [Varying-Vagrant-Vagrants/VVV#928]
One of the minimum requirements for WordPress is MySQL 5.6.

Ubuntu 14.04 still has the default version at 5.5 but 5.6 is available in the default repositories.
I changed provision/provision.sh line 59 from mysql-server to mysql-server-5.6 then did a vagrant provision to get it updated.
So far everything is running well without any problems.

**Comment by jeremyfelt** [comment]
Thanks @mikkamp, I think this is a great idea. If 5.7 is available, I would be in favor of that as well. If not, then 5.6 is 👍

**Comment by jeremyfelt** [comment]
I've created https://github.com/Varying-Vagrant-Vagrants/VVV/issues/876 to discuss this a bit further.

**Comment by ottok** [comment]
Ubuntu 14.04 also has MariaDB 10.0 available.

**Comment by jeremyfelt** [comment]
I'm going to close this and defer to the combo of #930 and #949.
