### ISSUE TITLE
Check if hosts file is read only before attempting to update it

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#929]
It seems that in some versions of Windows, the hosts file is now read only by default and may cause some issues during provisioning with host name plugins installed.

If possible, we should have some kind of flight check that determines whether hosts updating will work.

**Comment by cgsmith** [comment]
@jeremyfelt I can check to update the hostsupdater plugin to see if the plugin can handle this.

**Comment by btsimonh** [comment]
additional - if you run the first 'vagrant up' in an administrative command prompt so that the host updater works; then all your folder permissions are wrong.... (win 10)

**Comment by Mte90** [comment]
Vagrant-hostsupdater plugin do that check now https://github.com/cogitatio/vagrant-hostsupdater/blob/master/lib/vagrant-hostsupdater/HostsUpdater.rb#L142
