### ISSUE TITLE
Question: How to migrate to a production WP environment

### ISSUE THREAD

**Issue by rmurillo21** [Varying-Vagrant-Vagrants/VVV#936]
Hello all,

I am using the VVV project successfully for local development.   I now want to use it to provision a production multi-site WP environment on AWS.

Forgive the noop quesition:  Would I just copy/clone this repo into a new one, and start changing it to support the provision of a new WP config that is production ready?

Any suggestions for using this project as a basis for launching production ready instances that have the same config as my development boxes?

Thanks!

**Comment by islanddog** [comment]
Personally I used: https://oliverveits.wordpress.com/2016/04/01/aws-automation-using-vagrant-a-hello-world-example/ and found it worked great.
