### ISSUE TITLE
/etc/hosts changes assume an empty line at end of file

### ISSUE THREAD

**Issue by digikami** [Varying-Vagrant-Vagrants/VVV#939]
In using VVV in conjunction with Acquia Dev Desktop, I have noticed that when VVV (version 1.3.0) makes changes to /etc/hosts, it simply appends the entries at the end of the file without first checking if the file ends in a newline. If the hosts file has an entry at the end without a trailing newline, `vagrant up` will break the entry, then `vagrant down` will permanently remove it from the hosts file.

**Comment by digikami** [comment]
I mentioned Dev Desktop partially so anyone with a similar issue can find this ticket, but also because its code does not leave trailing newlines when it makes changes to the hosts file. It is possible other systems work similarly, and I have left a request with Acquia to leave a trailing newline on any hosts edits, but to be honest VVV's process seems the more problematic one, both in assuring that its own changes work (if there is a conflict, the first `vagrant up` will have a broken hosts entry for `http://vvv/`) and making sure it plays nicely with any given hosts file.

The issue can be replicated by having any entry at the end of the hosts file without leaving a trailing newline.

**Comment by jeremyfelt** [comment]
Hi @digikami, thanks for the ticket! I'm not sure if we can fix this in VVV proper, as those lines are added by the Vagrant hostsupdater plugin - https://github.com/cogitatio/vagrant-hostsupdater. It may be worth opening an issue there as well.

**Comment by tomjn** [comment]
Closing as this is a vagrant hosts updater issue
