### ISSUE TITLE
WordPress Customizer won't work?

### ISSUE THREAD

**Issue by daviedR** [Varying-Vagrant-Vagrants/VVV#942]
I installed fresh installation of VVV and added some new sites using Variable VVV. I leave the default sites (4 sites) untouched. And then I fgiured out, the Customizer page won't work, there are js error:

![image](https://cloud.githubusercontent.com/assets/1287713/16936632/5bcec728-4d92-11e6-92e2-76c6510fac6b.png)

Any idea?

**Comment by topdown** [comment]
Try downloading a fresh copy of WordPress and replacing the wp-admin and wp-includes directory. My guess is the download was interrupted on setup.
