### ISSUE TITLE
local WP addresses not responding 

### ISSUE THREAD

**Issue by AntonEmery** [Varying-Vagrant-Vagrants/VVV#946]
Hi Folks, I'm new to Vagrant. Went through the basic install of Vagrant and VVV.  I can't seem to reach any of the addresses like http://local.wordpress.dev/  It says the site can't be reached.  If i go to http://192.168.50.4 it does take me to the home page, and all the links work except for the WordPress ones at the bottom. Any thoughts? Thanks!

**Comment by grappler** [comment]
Are the dev URLs added to the host file? If not did you install the vagrant host updater plugin?

Sometimes just reloading the box can help.

**Comment by AntonEmery** [comment]
Duh, I should have read the instructions closer..  I see now that you have either install the plugin or update the host file.  Installing the plugin did the trick.  Thanks!
