### ISSUE TITLE
No entries are written to hosts file

### ISSUE THREAD

**Issue by stalal** [Varying-Vagrant-Vagrants/VVV#947]
Despite installing the hostsupdater plugin, no entries were inserted into the hosts file. Manually inserting them works.

**Comment by mariadanieldeepak** [comment]
@stalal,

Are you using Windows OS? If yes, try running the Command Prompt as Administrator and execute the commands.

**Comment by stalal** [comment]
Yes, I am running Windows 10. That fixed it. Thank you so much!

**Comment by mariadanieldeepak** [comment]
@stalal, 

You're welcome :)
