### ISSUE TITLE
NFS shares?

### ISSUE THREAD

**Issue by CormacBracken** [Varying-Vagrant-Vagrants/VVV#95]
I'm running my vm on an admittedly underpowered laptop. On one fairly php-heavy page, the page timed out after 60s having loaded maybe 20% of the generated content. (the same page loads ok on a 512mb server. ). 

After poking around with fpm settings without result, I looked into switching to NFS shares, and found a startling benchmark - 5+ minutes vs 14s (http://docs-v1.vagrantup.com/v1/docs/nfs.html). Sure enough, when I got NFS working, my page loaded in around 10s (on first hit).

Only problem with that is, vagrant doesn't like the owner/permissions currently set when VVV shares /srv/www. I didn't fully understand the issue, so I just deleted the owner and permission arguments, and it works so I'm going with that...

Is there a reason not to use NFS shares?

**Comment by Kevinlearynet** [comment]
To add to what @jeremyfelt mentions about strange issues happening with database files, I found this explanation very helpful:

> To get NFS permissions right, your users need to have the same UID and GUID on host and guest. It's pretty tricky to setup and you should not change it from the guest. Maybe you can change it on the host to make it writeable to mysql and make UID and GUID the same. Of course, the moment the host changes this won't work anymore.

[StackOverflow answer](http://stackoverflow.com/questions/22796386/pre-existing-mysql-data-with-vagrant-virtualbox#answer-22812296)

After a lot of digging I was able to get this running on my Macbook pro w/OS X El Capitan. I'm using a custom forked setup of VVV with the following `synced_folder` configuration:

```
# https://github.com/mitchellh/vagrant/issues/6360
config.nfs.verify_installed = false

config.ssh.forward_agent = true
config.vm.synced_folder "database/", "/srv/database", 
  :nfs => true

if File.exists?(File.join(vagrant_dir,'database/data/mysql_upgrade_info')) then
  config.vm.synced_folder "database/data/", "/var/lib/mysql", 
    :nfs => true, 
    :mount_options => ['rw', 'vers=3', 'tcp', 'fsc', 'actimeo=2']
end
```
