### ISSUE TITLE
Git clone pulls from develop branch by default

### ISSUE THREAD

**Issue by rclations** [Varying-Vagrant-Vagrants/VVV#953]
It appears that `develop` is the default branch for the repo, but there are no instructions for users to switch to the master branch when cloning VVV for the first time.

I think there should either be instructions added between steps 6 & 7, or master should be set as the default branch for the project so it clones that branch by default. I'm happy to create a PR if modifying the docs is the preferred method.

**Comment by jeremyfelt** [comment]
Let's document this on varyingvagrantvagrants.org via #961.

In general:
* `develop` is probably the best branch to use, though will be unstable from time to time
* We should have more releases to make `master` more stable
* `develop` is the right branch for `git clone` to encourage contributions.
* Instructions should be available for running master or specific tagged versions.

**Comment by jeremyfelt** [comment]
And thanks for opening a ticket, @rclations!
