### ISSUE TITLE
[Firefox] XML Parsing Error:

### ISSUE THREAD

**Issue by mikromakro** [Varying-Vagrant-Vagrants/VVV#955]
`XML Parsing Error: undefined entity Location: jar:file:///Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/chrome/browser/content/browser/aboutNetError.xhtml Line Number 22, Column 12:
    <title>&loadError.label;</title>
-----------^`

I get this error a lot. VVV works with a 25-40% uptime. But the majority of the time I spend refreshing the page and get this error, and I don't know why. I try running `vagrant provision` and or `vagrant reload`. 

I find myself spending too much time, provision, halt, up and reloading. I'm running the standard version of VVV straight of the box on OS X 10.11.6.

Am I doing something wrong, or can I tweak things?

**Comment by jeremyfelt** [comment]
Hi @mikromakro. Can you provide a list of steps to reproduce this issue? Does this happen with one of the default sites or a custom site?

**Comment by mikromakro** [comment]
@jeremyfelt Hi, and thanks for asking. I'm sorry but it was my own fault. It was a Firefox add-on setting in No Resource URI Leak. If you can delete this issue, please go ahead. It serves no value.

**Comment by jeremyfelt** [comment]
No worries, glad you found the issue!
