### ISSUE TITLE
Unable to Disable STRICT PHP Errors

### ISSUE THREAD

**Issue by bjonesy** [Varying-Vagrant-Vagrants/VVV#96]
Unable to disable STRICT PHP Errors.  Edited the php-custom.ini file and replaced the default error reporting with error_reporting = E_ALL & ~E_STRICT and restarted local server.  Even vagrant destroyed and still not working. I already let Jeremy know and he will look into when he gets a chance.  I will look into finding a temporary solution.

**Comment by peterblazejewicz** [comment]
@johnpbloch thansk!
Note: in my case I've added it to theme's `functions.php`
