### ISSUE TITLE
vagrant too slow with nfs and can't ssh with nfs = true

### ISSUE THREAD

**Issue by ishandutta2007** [Varying-Vagrant-Vagrants/VVV#960]
config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", :nfs => true 
connects but the server is very slow,
config.vm.synced_folder ".", "/vagrant", id: "vagrant-root"
always times out.
I have verified my firewall is disabled.

**Comment by jeremyfelt** [comment]
Hi @ishandutta2007, thanks for opening an issue. At first glance, this seems like more of a general Vagrant question - https://github.com/mitchellh/vagrant / https://vagrantup.com.

It may be helpful to reproduce the issue with no provisioning on a base box to try and narrow down possibilities.

**Comment by jeremyfelt** [comment]
I'm going to close this out, but please feel free to continue discussion. We can always reopen if needed.
