### ISSUE TITLE
What is the best procedure to update?

### ISSUE THREAD

**Issue by eno812** [Varying-Vagrant-Vagrants/VVV#964]
Do I just do the vagrant box update or is there another procedure I should be using to update vvv?

**Comment by jeremyfelt** [comment]
Hi @eno812, thanks for stopping by.

There isn't yet a well documented procedure for this. We have a new area for documentation that I'm hoping to populate with some good instructions. #845 has some discussion that will turn into documentation at some point.

Loosly:
* Update Vagrant when needed
* Update VirtualBox when needed
* `vagrant box update` when needed
* `git pull origin develop` (or master) from VVV and `vagrant provision` to apply changes
