### ISSUE TITLE
Outbound SMTP messages not caught by MailCatcher

### ISSUE THREAD

**Issue by iandunn** [Varying-Vagrant-Vagrants/VVV#965]
If PHPMailer is configured to send via SMTP, messages will bypass MailCatcher and be sent directly to the SMTP server.

I think that will eventually lead to clients/users receiving unintended messages from developer's test environments.

Once you understand what's going on, it makes sense that this is the expected behavior, but I don't think that it's immediately obvious, and I'm guessing that it's not the desired behavior in most use cases.

Fixing this at the WordPress layer [is easy enough](https://gist.github.com/iandunn/58453917f91ebb53bdb5152c98662fba), but that's not a practical solution for VVV. Ideally, it should be done at the server layer, so that it's safe by default, and developers don't have to think about it unless they want to override the default behavior.

I don't think that will be easy, though, since PHPMailer just opens a socket directly to the external SMTP server. Maybe a custom PHP module could intercept that and re-route it to MailCatcher? Or maybe some `php.ini` setting that would let us hook into WP for all vhosts? I'm thinking of something like `auto_prepend_file`, but running _after_ WP has loaded.

At the very least, I think the behavior should be liberally documented if it can't be avoided.

Possibly related: #791

**Comment by Mte90** [comment]
We are now using mailhog so this one is obsolete
