### ISSUE TITLE
phpmyadmin directory not renaming on install

### ISSUE THREAD

**Issue by ecrookes** [Varying-Vagrant-Vagrants/VVV#975]
I just re-installed VVV on my Windows 10 laptop today and noticed all of the links in the dashboard worked except for phpmyadmin ( http://vvv.dev/database-admin/ )

When I looked in file explorer, I noticed that phpmyadmin hadn't moved during installation, and was still located in the directory 'phpMyAdmin-4.6.0-all-languages'. Renaming the directory manually worked.

I checked a previous working version of VVV and the only change in code for the phpmyadmin install seemed to be line 692 in provision.sh:

`cp "/srv/config/phpmyadmin-config/config.inc.php" "/srv/www/default/database-admin/"`

The previous version didn't have the directory paths in quotes. Not sure if that makes any difference.

**Comment by jeremyfelt** [comment]
Hi @ecrookes, thanks for opening an issue.

I'm wondering if something tripped up provisioning and interrupted the `mv` line here somehow - https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L686-L688

There's a good chance that running `vagrant provision` again after the initial run would resolve the issue.

I've run provisioning from scratch a few times recently getting things prepped for the next release and haven't run into this issue yet, so I'm hopeful it's a one off.

**Comment by jeremyfelt** [comment]
I'm going to go ahead and close this out. Feel free to comment and/or re-open if this appears again.

**Comment by ecrookes** [comment]
Ended up encountering the same problem again today using the newest versions of Vagrant, Virtualbox & VVV on Windows 10, using git clone.

==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: -----------------------------
==> default: Provisioning complete in 731 seconds
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-9456-8q8t1w.sh
==> default: Updating core resources...
==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-utilities
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Already on 'master'
==> default: Your branch is up-to-date with 'origin/master'.
==> default: Running provisioner: utility-core-memcached-admin (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-9456-1rz3g0o.sh
==> default: phpMemcachedAdmin already installed.
==> default: Running provisioner: utility-core-opcache-status (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-9456-1hbtbhd.sh
==> default: Updating Opcache Status
==> default: From https://github.com/rlerdorf/opcache-status
==> default:  * branch            master     -> FETCH_HEAD
==> default: Current branch master is up to date.
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-9456-1o2clpj.sh
==> default: Downloading phpMyAdmin...
**==> default: mv:
==> default: cannot move ‘phpMyAdmin-4.6.0-all-languages’ to ‘database-admin’
==> default: : Operation not permitted
==> default: cp:
==> default: cannot create regular file ‘/srv/www/default/database-admin/’
==> default: : Not a directory**
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I renamed the downloaded directory phpMyAdmin-4.6.0-all-languages to database-admin and ran the provision again, which seemed to clear up that issue.

==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: -----------------------------
==> default: Provisioning complete in 144 seconds
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-6956-ermahy.sh
==> default: Updating core resources...
==> default: From https://github.com/Varying-Vagrant-Vagrants/vvv-utilities
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Already on 'master'
==> default: Your branch is up-to-date with 'origin/master'.
==> default: Running provisioner: utility-core-memcached-admin (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-6956-12p5lw3.sh
==> default: phpMemcachedAdmin already installed.
==> default: Running provisioner: utility-core-opcache-status (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-6956-1j8t7r.sh
==> default: Updating Opcache Status
==> default: From https://github.com/rlerdorf/opcache-status
==> default:  * branch            master     -> FETCH_HEAD
==> default: Current branch master is up to date.
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-6956-1jhe8lo.sh
==> default: PHPMyAdmin already installed.
==> default: Running provisioner: utility-core-webgrind (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-6956-u9ld2.sh
==> default: Downloading webgrind, see https://github.com/michaelschiller/webgrind.git
==> default: Cloning into '/srv/www/default/webgrind'...
==> default: Running provisioner: site-wordpress-default (shell)...
    default: Running: C:/Users/ericd/AppData/Local/Temp/vagrant-shell20170205-6956-1wg1nxm.sh
==> default: Downloading wordpress-default, see https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
==> default: Cloning into '/srv/www/wordpress-default'...
==> default: Creating database 'wordpress_default' (if it's not already there)
==> default:  DB operations done.
==> default: Downloading WordPress Stable, see http://wordpress.org/

Everything runs fine until it gets to:

==> default: > phantomjs-prebuilt@2.1.14 install /tmp/wordpress-develop/node_modules/phantomjs-prebuilt
==> default: > node install.js
==> default: Initializing grunt and creating build.wordpress-develop.dev, this may take several minutes.
==> default: Loading "sass.js" tasks...
==> default: ERROR
==> default: >> Error: ENOENT: no such file or directory, scandir '/tmp/wordpress-develop/node_modules/node-sass/vendor'
==> default: Running "clean:all" (clean) task
==> default: >> 0 paths cleaned.
==> default: Running "copy:files" (copy) task
==> default: Created 160 directories
==> default: , copied 1429 files
==> default: Running "copy:wp-admin-css-compat-rtl" (copy) task
==> default: Copied 1 file
==> default: Running "copy:wp-admin-css-compat-min" (copy) task
==> default: Copied 2 files
==> default: Running "copy:version" (copy) task
==> default: Copied 1 file
==> default: Running "cssmin:core" (cssmin) task
==> default: >> 37 files created. 671.15 kB → 565 kB
==> default: Warning: Task "sass:colors" not found. Use --force to continue.
==> default: Aborted due to warnings.
==> default: Moving WordPress develop to a shared directory, /srv/www/wordpress-develop/public_html
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/gauge/node_modules/.bin/supports-color’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/node-gyp/node_modules/.bin/nopt’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/detective/node_modules/.bin/acorn’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/cross-spawn/node_modules/.bin/which’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/sshpk-sign’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/lpad-align’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/browser-pack’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/uglifyjs’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/node-gyp’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/umd’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/cake’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/rimraf’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/sshpk-conv’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/sha.js’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/csso’: Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/gifsicle’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/jpegtran’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/JSONStream’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/coffee’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/sassgraph’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/which’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/har-validator’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/miller-rabin’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/extract-zip’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/watchify’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/insert-module-globals’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/browserslist’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/phantomjs’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/esvalidate’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/node-sass’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/not-in-install’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/in-publish’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/find-versions’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/seek-bunzip’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/executable’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/seek-table’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/cleancss’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/strip-indent’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/rtlcss’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/shjs’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/browserify’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/optipng’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/rc’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/sshpk-verify’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/not-in-publish’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/grunt-jsvalidate’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/strip-dirs’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/esparse’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/mkdirp’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/svgo’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/jshint’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/deps-sort’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/js-yaml’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/gzip-size’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/acorn’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/findup’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/module-deps’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/nopt’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/strip-json-comments’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/in-install’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/uuid’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/semver’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/.bin/bin-version-check’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/request/node_modules/.bin/uuid’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/maxmin/node_modules/.bin/pretty-bytes’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/extract-zip/node_modules/.bin/mkdirp’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/watchify/node_modules/.bin/browserify’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/phantomjs-prebuilt/node_modules/.bin/which’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/grunt-lib-phantomjs/node_modules/.bin/rimraf’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/grunt-contrib-clean/node_modules/.bin/rimraf’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/svgo/node_modules/.bin/esvalidate’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/svgo/node_modules/.bin/esparse’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/svgo/node_modules/.bin/js-yaml’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/sass-graph/node_modules/.bin/window-size’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/syntax-error/node_modules/.bin/acorn’
==> default: : Protocol error
==> default: mv:
==> default: cannot create symbolic link ‘/srv/www/wordpress-develop/public_html/node_modules/bin-version-check/node_modules/.bin/semver’
==> default: : Protocol error
==> default: Creating wp-config.php for src.wordpress-develop.dev and build.wordpress-develop.dev.
==> default: Installing src.wordpress-develop.dev.
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added src.wordpress-develop.dev from /srv/www/wordpress-develop/provision/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/wordpress-develop/provision/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /vagrant/vvv-config.yml
==> default:  * Added build.wordpress-develop.dev from /vagrant/vvv-config.yml
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Stopping MariaDB database server mysqld
==> default:    ...done.
==> default:  * Starting MariaDB database server mysqld
==> default:    ...done.
==> default:  * Checking for corrupt, not cleanly closed and upgrade needing tables.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default:    ...done.

I then manually renamed /srv/www/wordpress-default/wordpress to /srv/www/wordpress-default/public_html

I ran provision again, without issue. It seems the issue is with the mv command.
