### ISSUE TITLE
xdebug not working with phpbrew

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/VVV#979]
I've been using xdebug with vvv for a while now with _no_ issues. I wanted to test on an older version of PHP (I was on 7), so I switched to the feature/phpbrew branch and provisioned. Worked great for switching PHP versions.

I switched to 5.5.9 and confirmed with `php --version` that I was on the proper version. I then turned on xdebug, but my breakpoints aren't firing. I use PHP Storm, and as stated earlier, it was working before. Now, with the only change being phpbrew, it is not working.

In efforts to get xdebug working, I used `phpbrew switch-off` to go back to system default. Again I ran `php --version` and was back on 7. xdebug still is not working :/ My previously working breakpoints won't fire anymore.

**Comment by jeremyfelt** [comment]
Hi @joelworsham, thanks for opening an issue with this information. I'm going to tag #854 so that it's referenced there as that is still an open pull request / feature.
