### ISSUE TITLE
Unable to update wp-cli on provision

### ISSUE THREAD

**Issue by jjeaton** [Varying-Vagrant-Vagrants/VVV#983]
In provision.sh, wp-cli gets [updated like this](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L591):

```
cd /srv/www/wp-cli
git pull --rebase origin master
composer update
```

This will work the first time that wp-cli is updated on provision. However, `composer update` modifies the `composer.lock` file, so now there are unstaged changes in the git checkout. The next time you provision, the git pull fails due to unstaged changes.

Would it be better to install wp-cli using the normal install method as suggested here: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/82#issuecomment-19367345?

**Comment by theukedge** [comment]
Can someone smarter than me help me to update wp-cli in the interim?

**Comment by jjeaton** [comment]
@theukedge 

you can try this:

```
vagrant ssh
cd /srv/www/wp-cli
git checkout -- .
git pull --rebase origin master
composer update
```

**Comment by theukedge** [comment]
@jjeaton you're a legend. Thank you sir

**Comment by jeremyfelt** [comment]
Thanks for opening an issue @jjeaton. I think it would be nice to switch the provisioning for WP-CLI to the "official" process. For those that contribute to directly to WP-CLI, it should be relatively painless to setup a custom config. For those that don't, it will be much easier to keep updated with `wp cli update --nightly`.

**Comment by jjeaton** [comment]
@jeremyfelt I've opened a PR #1057 that makes this change. Although, after seeing #990, that fixes the core issue. I agree that the standard installation will make wp-cli updates easier for most users.
