### ISSUE TITLE
Error installing mailcatcher

### ISSUE THREAD

**Issue by JDGrimes** [Varying-Vagrant-Vagrants/VVV#985]
When I run `vagrant provision`, I get an error in regard to Mailcatcher:

```
ERROR:  Error installing mailcatcher:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:2:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/eventmachine-1.0.9.1/ext/gem_make.out
```

The provision script continues, and works fine, but Mailcatcher obviously hasn't been installed.

I did a little searching on the error, and found https://github.com/sj26/mailcatcher/issues/144 and ultimately https://github.com/sj26/mailcatcher/issues/277. It seems that while Mailcatcher itself is compatible with Ruby 1.9.x, some of its dependencies aren't. The solution is to either [install a lower version of those dependencies](https://github.com/sj26/mailcatcher/issues/277#issuecomment-209154903), or update Ruby.

I ran these commands to install mailcatcher:

``` bash
sudo apt-get install ruby-dev
sudo gem install mime-types --version "< 3"
sudo gem install --conservative mailcatcher
```

Despite the last command issuing an error about the `mime-types` dependency version, running `mailcatcher` seems to work:

```
vagrant@vvv:~$ mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

However, Firefox can't connect to `http://127.0.0.1:1080`. I guess maybe I have to run provision again now or something?

**Comment by JDGrimes** [comment]
> However, Firefox can't connect to http://127.0.0.1:1080. I guess maybe I have to run provision again now or something?

Still cannot connect to http://127.0.0.1:1080 or http://vvv.dev:1080, even after running `vagrant up --provision`.

I didn't get the errors related to Mailcatcher, but I did get this:

```
==> default: sh: 1: 
==> default: /usr/local/rvm/bin/catchmail: not found
```

Is this related?

Running`which catchmail` reveals `/usr/local/bin/catchmail`.

**Comment by cfoellmann** [comment]
I don't know. 
Have you tested provisioning a new VVV from scretch?

**Comment by bonnerl** [comment]
I was getting the same error and provisioning VVV from scratch solved it.

**Comment by JDGrimes** [comment]
For posterity: I just updated to VVV 2.0 and destroyed my box and reprovisioned. Now Mailcatcher is working for me.

**Comment by kraftner** [comment]
So I am still facing this issue with the current version of VVV.

I got mailcatcher running manually by following the steps mentioned by @JDGrimes taken from https://github.com/sj26/mailcatcher/issues/277
```
sudo apt-get install ruby-dev
sudo gem install mime-types --version "< 3"
sudo gem install --conservative mailcatcher
```

To actually get it working (make it accessible outside the VM, instruct PHP to use it) you need to do more, namely fixing the paths for the service and PHP:
```
sudo sed -i 's/\/rvm//g' /etc/init/mailcatcher.conf
sudo sed -i 's/\/rvm//g' /etc/php/7.0/mods-available/mailcatcher.ini
sudo sed -i 's/\/rvm//g' /etc/php/5.6/mods-available/mailcatcher.ini
```
This will fix the path
`/usr/local/rvm/bin/mailcatcher` ->
`/usr/local/bin/mailcatcher` in those three config files above.

After that you need to restart (not reprovision) the VM or restart all relevant services as done in [the provision script](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/ed7bee10d29b989d05c7ce8203af1dd8e42f4cc1/provision/provision.sh#L547-L570).

**Comment by kenguest** [comment]
I ran into this issue too, and found that also needed to install the dev package of sqlite. Not a biggie - just thought I should mention it for completeness.

**Comment by dannyb195** [comment]
I just ran into this issue on VVV 2.0.0, @kraftner 's comments id work for me though (https://github.com/Varying-Vagrant-Vagrants/VVV/issues/985#issuecomment-314806759)

local ruby `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

box ruby after provision `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`
