### ISSUE TITLE
"Do not run Composer as root/super user!"

### ISSUE THREAD

**Issue by JDGrimes** [Varying-Vagrant-Vagrants/VVV#986]
When I run `vagrant provision`, whenever composer is used it complains:

```
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
```

Is this normal? I understand that maybe there could be reasons that composer needs to be run as root in this case, or it just does as a side-effect of the provisioning script being run as root, but I didn't find any information on it, so I wanted to be sure that it wasn't a configuration issue of some sort on my part. (I have incorrectly set up composer to run as root before on my local machine, and although I've since fixed that, I'm wondering whether it had leaked to the VM somehow.)

**Comment by cfoellmann** [comment]
I believe the vagrant `provisioner: shell` runs as root and there is nothing we can do about it.
this is a security concern of the composer team which we need to ignore. Shouldn't be too risky.

**Comment by JDGrimes** [comment]
I figured that it was something like that. Now I'm just wondering if there is any way to launch a non-root sub-shell? (I'll admit I'm not a shell genius.) Short of that, I guess maybe VVV shouldn't just silence the error, even though it is expected, so that people know that this issue exists and can make their own assessment.

**Comment by cfoellmann** [comment]
You can create a new user and ssh into the box.
