### ISSUE TITLE
Provision problems when WordPress is in sub directory

### ISSUE THREAD

**Issue by mishtershmart** [Varying-Vagrant-Vagrants/VVV#987]
Hey there,

I have a site that has the WP core files in a directory called `wordpress`. I just moved this site into VVV (as I'm sick of changing between dev environments for various projects) and everything was working well. After running a `vagrant provision` however, the WordPress core files ended up installed in the projects root dir and the WP installer kicked in.

I'm wondering how I define WordPress' location as being in a sub dir to prevent this happening again?

Thanks!

**Comment by topdown** [comment]
In the projects root `www/your_project_name/` there should be a file `vvv-init.sh`
You will have to edit the first parts of the file
Example,
The typical setup looks like this
```
if [ ! -d "htdocs/wp-admin" ]; then
	echo 'Installing WordPress (release version) in kyevans/htdocs...'
	if [ ! -d "./htdocs" ]; then
		mkdir ./htdocs
	fi
	cd ./htdocs
```

A custom setup would look like this
```
if [ ! -d "public/wp/wp-admin" ]; then
	echo 'Installing WordPress (release version) in wpstarter/public...'
	if [ ! -d "./public ]; then
		mkdir ./public
	fi
	cd ./public
```
NOTE: these are just parts and not complete!

If you make a change like htdocs to public then you have to also edit the `wp-cli.yml` in your projects root to have the correct path.

**Comment by mishtershmart** [comment]
Beautiful – this worked perfectly. Thanks for your help @topdown
