### ISSUE TITLE
Problems installing custom site in www subfolder nginx config

### ISSUE THREAD

**Issue by mantismamita** [Varying-Vagrant-Vagrants/VVV#989]
I recently installed a second vvv to test a specific project with php7. I changed the IP address in the Vagrant files and everything is up and running. I installed the database in the correct folder and have no trouble accessing it through wp-cli. The only difference between this and any other site I've installed in VVV is that it is in a subdirectory so the path to the root is: 

```
/srv/www/examplesite/www/
```

rather than `/srv/www/`

I've created the .conf file that is equivalent to my url which is http://local.wp.examplesite.fr/ and so named local.wp.examplesite.fr.conf and placed it in the sites directory of the nginx-config directory.

I tried simply updating the root and when that didn't work tried looking at eh [nginx docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#root) for answers and tried the following: 

```
server {
    listen       80;
    listen       443 ssl;

    server_name  local.wp.examplesite.fr;
    #root         /srv/www/examplesite/www;

    # Subdirectory location settings
    location /i/ {
        root  /srv/www/examplesite/www;
        index       index.php;
    }
}
```

but I don't seem to be getting anywhere.

When I do `sudo nginx -t` I get:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by mantismamita** [comment]
Ok I got it working by switching out the contents of `local.wp.examplesite.fr.conf` with the `default.conf` and reprovisioning. Is there a reason that my custom site is not being read?  I would ideally like to keep the default.conf and the custom config separate so that it doesn't get overrwritten during an update.

**Comment by JDGrimes** [comment]
I think that you just needed to include the WordPress-specific configuration file in `local.wp.examplesite.fr.conf`, like this:

```
server {
    listen       80;
    listen       443 ssl;

    server_name local.wp.examplesite.fr

    root         /srv/www/examplesite/www;

    include /etc/nginx/nginx-wp-common.conf;
}
```

Note the last line: `include /etc/nginx/nginx-wp-common.conf;`.
