### ISSUE TITLE
Trying to access local links with no internet connection

### ISSUE THREAD

**Issue by simkessy** [Varying-Vagrant-Vagrants/VVV#991]
I figured this should work but it's not at the moment. 

I deployed VVV and everything went fine as far as I can tell. I have the VM up and running but I can't seem to access any of the links when I'm not connected to the internet. I'm at work with no Wifi but I was hoping I'd be able to work on a site or play around even if I didn't have internet access since it's all local. 

Am I wrong?

**Comment by LoreleiAurora** [comment]
Windows or mac?

**Comment by simkessy** [comment]
Hey @LoreleiAurora the host machine is Ubuntu 14 and I'm using Chrome.

**Comment by LoreleiAurora** [comment]
Try the following:

1. Go to chrome://settings
1. Click on `Show advanced settings...`
1. Uncheck `Use a prediction service to load pages more quickly`
1. Check if the DNS prefetching is really disabled by going to chrome://dns. You should see there something like DNS pre-resolution and TCP pre-connection is disabled. If the prefetching is not disabled, you'll see some tables.

**Comment by simkessy** [comment]
Tried that and tried fireworks, nothing workings.

**Comment by simkessy** [comment]
I'll just blow it away and start from scratch.
