### ISSUE TITLE
Can't run older versions of WordPress

### ISSUE THREAD

**Issue by ericandrewlewis** [Varying-Vagrant-Vagrants/VVV#992]
Trying to run 3.8 on VVV gives me this white screen

```
Your PHP installation appears to be missing the MySQL extension which is required by WordPress.
```

I would guess this has to do with the PHP 7 upgrade. 

I saw #98 is a discussion about swapping out different versions of PHP in VVV.

This isn't necessarily a bug, but wanted to bring this up. I'll probably check out v1.1 of VVV to run older versions.

**Comment by cfoellmann** [comment]
@jeremyfelt Maybe we should add a note to the README stating the oldest WP version with full PHP 7 support.

**Comment by jeremyfelt** [comment]
We should definitely add some documentation around PHP versions. Once we have some PHP version swapping available (like Eric mentioned above), then the documentation can be even more helpful. ;)

**Comment by jeremyfelt** [comment]
The ability to provision a site with PHP 5.6, 7.0, or 7.1 via #1055 *should* help this.

**Comment by LoreleiAurora** [comment]
@jeremyfelt this does solve this :) im using it personally

**Comment by jeremyfelt** [comment]
This takes a combination of two things (which we should have documented as well):

The [VVV Utilities](https://github.com/Varying-Vagrant-Vagrants/vvv-utilities) repo has provisioning for PHP 5.6 in addition to PHP 7.0. In VVV's `vvv-config.yml` or in a custom config, `php56` will need to be added to the core utilities configuration:

```
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - php56
```

And then, the `nginx_upstream` needs to be set for the site in the config:

```
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.dev
    nginx_upstream: php56
```

Running `vagrant provision` will provision both PHP 5.6 and the `wordpress-default` site. If PHP 5.6 is already available and you want to change a site from the default PHP 7.0 upstream to PHP 5.6, then only `vagrant provision --provision-with=site-wordpress-default` is necessary.

**Comment by maxreality** [comment]
@jeremyfelt Is there a way to verify the site is running PHP56? Is it a global that can be checked with 'php -v'? The reason I ask is I've tried all of these steps without success. I'm assuming wordpress-default is irrelevant and only used in this example where site-xxx can be substituted according to the correlating custom.yml?

**Comment by maxreality** [comment]
@jeremyfelt I was trying to use VV which was the issue. Please disregard the previous question.

**Comment by capitaladot** [comment]
2017/03/31 17:37:34 [error] 25321#25321: *1 no port in upstream "php56", client: 192.167.50.1, server: local.wordpress.dev, request: "GET /wp-admin/ HTTP/1.1", host: "local.wordpress.dev"
