### ISSUE TITLE
phpcs executable file path for editor integration?

### ISSUE THREAD

**Issue by mikromakro** [Varying-Vagrant-Vagrants/VVV#993]
Thanks for making this available and maintaining it for us all of us, I really appreciated it.

Though there is  something I cannot get working. Or perhaps I have misunderstood what it is and what it is for.

I can see that there is a `phpcs` folder in the `www` folder, so I'm gussing that VVV come with Codesniffer all ready to go, it just needs to be integrated with the code editor of choice. 

There is a Atom package [linter-phpcs](https://atom.io/packages/linter-phpcs) for this. And as I read the documentation, it should really just been as easy as entering the path to the executable file and Code Standard, like `WordPress`.

But exactly what is the path the executable file? `/www/phpcs/CodeSniffer/Standards/WordPress/bin`?

I can't really figure out what path or what file extension I should be looking for. 

Thank you. *(Sorry this isn't really an issue, but I didn't know where else to ask)*
___
###### My setup: Mac, Atom and VVV.

**Comment by JDGrimes** [comment]
To find the executable file, ssh into VVV, and then run `which phpcs`:

```bash
$ vagrant ssh

[...]

vagrant@vvv:~$ which phpcs
/srv/www/phpcs/scripts//phpcs
```

As you can see, it gave me `/srv/www/phpcs/scripts//phpcs`. `which` is a very useful tool for locating executables in your path. :-)

**Comment by mikromakro** [comment]
@JDGrimes Very clever! I got it working, thanks :dancer:
