### ISSUE TITLE
Documentation for updating WordPress

### ISSUE THREAD

**Issue by johnbillion** [Varying-Vagrant-Vagrants/VVV#999]
A common question we get at contributor days is how to update WordPress to the latest version.

AFAICT the simplest way is to re-provision the box, but this takes time, and the fastest way is to update via svn from each `wordpress-*` directory, but this is more involved for the end user.

What's the recommended method? And can this be added to the documentation?

**Comment by cfoellmann** [comment]
@LoreleiAurora  can we just provision sites with your new provision process?

**Comment by LoreleiAurora** [comment]
Yes you can `vagrant provision --provision-with site-wordpress-develop`

**Comment by jeremyfelt** [comment]
👍  Good idea. We should get a section of this going in the documentation.

**Comment by jeremyfelt** [comment]
Related: #961
